### PR TITLE
Add check-dynamic-macros-android.sh script

### PR DESCRIPTION
**Pull request by sjchmiela**
# Why

https://github.com/expo/expo-cli/pull/98#issuecomment-431037961

# How

Write a simple shell script naively parsing `template-files/android-paths.json` file and checking whether files listed there exist.

# Test Plan

Manual testing proved the script works.

### CODE REVIEW

**Comment by ide** [comment]
LGTM! Maybe we should consider adopting "Python without dependencies" as our scripting language instead of Bash haha

**Review by ide — APPROVED** [review]

**Review by dsokal — APPROVED** [review]
:+1:

**Review by dsokal — APPROVED** [review]
:+1:

**Review by dsokal — APPROVED** [review]
:+1:

**Review by dsokal — APPROVED** [review]
:+1:

**Pull request merged**
