### PR TITLE
upgrade react-native 0.73.4

### PR DESCRIPTION
**Pull request by gabrieldonadel**
# Why

Follow up https://github.com/expo/expo/pull/26308 for react-native 0.73 upgrade 

# How

- update package versions
  - `react-native 0.73.2 -> 0.73.4`   
  
# Test Plan

- bare-expo ios / android
- Expo Go
- fabric ios / android
- ci passed
 

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Review by tsapeta — APPROVED** [review]

**Review by lukmccall — APPROVED** [review]

**Comment by gabrieldonadel** [comment]
I'm holding on merging this for now given this new version is throwing a warning as soon as the app starts and will probably cause some confusion for people.
A PR fixing this issue has already been opened on core https://github.com/facebook/react-native/pull/42734 and it will be cherry-picked in 0.73.4

**Review by douglowder — APPROVED** [review]

**Comment by hasanaktas** [comment]
Expo 50.0.5 version has been released, but react native version is still 0.73.2.

Do you have any information about when it will be published?

**Comment by brentvatne** [comment]
@hasanaktas - we intentionally did not land this yet because we don't believe it's good to upgrade to 0.73.3. as @gabrieldonadel pointed out, 0.73.3 includes a regression that results in a warning on startup on every ios app. it will be fixed by https://github.com/facebook/react-native/pull/42734 and then when

**Comment by joeyhotz** [comment]
0.73.4 out now fyi :)

**Review by tsapeta — APPROVED** [review]

**Review by brentvatne — APPROVED** [review]

**Pull request merged**
