### PR TITLE
Changed text while loading app in android

### PR DESCRIPTION
**Pull request by vkupar**
"Made with Exponent" changed "Made with ❤"
P.S. >> I don't have java knowledge to make this optional but I changed text...

### CODE REVIEW

**Comment by vatex** [comment]
If you have knowledge of java and doesn't like what I done. please make this text optional. developer can show or hide text: "Made with Exponent" or write whatever developer's like...

**Comment by jesseruder** [comment]
@vatex we're going to make this text optional soon so I don't think we want to change what it says. thanks!

**Comment by ChenLi0830** [comment]
Hey @jesseruder, I was wondering has this made optional yet?

**Comment by ChenLi0830** [comment]
Hey @jesseruder, I found it, thanks for the great work on Exponent!

**Pull request closed without merging**
