### PR TITLE
[docs] Add store icon to eas metadata

### PR DESCRIPTION
**Pull request by byCedric**
# Why

Now all EAS parts have an icon.

# How

- Added `StoreIcon` to EAS Metadata

Ideally, we would have a unique icon for EAS Metadata. We do have one for `vscode-icons` (we added an icon to `store.config.json` files, [here](https://github.com/vscode-icons/vscode-icons/pull/3059)) but that doesn't exist in the `@expo/styleguide`.

# Test Plan

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Comment by byCedric** [comment]
cc @jonsamp

**Review by Simek — CHANGES_REQUESTED** [review]
We already use `StoreIcon` for EAS Submit in the same links list.

**Comment by jonsamp** [comment]
If we need an icon urgently, can we use the `<CodeIcon>`?

Screen Shot 2022-09-14 at 5 54 41 PM

This icon is more generic and is not already associated with a service.

---

Related: it would be great to get a list of visual assets we need for EAS Metadata, so that we can create a consistent set of icons/etc so that it feels cohesive. Can we make a list? Also can you brainstorm some ideas on what you'd want an icon to have? (an idea that come to mind are open/close curly braces)

**Comment by byCedric** [comment]
@jonsamp we just need an icon, to illustrate EAS Metadata. Evan and I prototyped a few versions, but we came up with the one I linked. I think code is too abstract, it doesn't show the power of EAS Metadata; automating/simplifying the app information in the stores.

Imho, I think the store icon fits better than the code icon.

We can leave it as is, without an icon for now. I just thought it might be nice to have an icon since this is the only one in the list without:
image

**Pull request closed without merging**
