### PR TITLE
[ios][expo-image] SWWebImage support for 3rd party privacy manifest

### PR DESCRIPTION
**Pull request by aparedes**
SDWebImage has been marked by Apple as an sdk that requires a 3rd party privacy manifest.

# Why

Apple has marked SDWebImage as an SDK that requires a [3rd Party Privacy Manifest](https://developer.apple.com/support/third-party-SDK-requirements/)

# How

SDWebImage has been updated on 5.18.7 to include the privacy manifest https://github.com/SDWebImage/SDWebImage/releases/tag/5.18.7

# Test Plan

Built and ran bare-expo app, went through all Components -> Image tasks
image

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Comment by alanjhughes** [comment]
Hi @aparedes - How have you tested this change? Your test plan is empty?

**Review by aleqsio — APPROVED** [review]
Thanks!

Looks reasonable, needed fix, did you have a chance to test the expo image with this change just to be sure?

**Review by tsapeta — CHANGES_REQUESTED** [review]
As @alanjhughes mentioned, this needs to be tested before merging. Also, please run `pod install` in `apps/bare-expo` and `apps/expo-go` to update Podfile locks

**Comment by aparedes** [comment]
Something went wrong here. will create a new pr

**Pull request closed without merging**
