### PR TITLE
Revert "[SDK-51] fix(metro-runtime): Update native LoadingView to sup…

### PR DESCRIPTION
**Pull request by dejagersh**
It's probably not as easy to simply revert, but the referenced PR doesn't seem to work: https://github.com/expo/expo/pull/31001

image

There's more people with this issue on the Expo discord: https://discord.com/channels/695411232856997968/1273381163787882619/1273381163787882619

If anyone is looking for a quickfix: I downgraded Expo to `51.0.27` and expo-router to `3.5.21`

### CODE REVIEW

**Comment by zhengyuanjun** [comment]
Try uninstall react-native, then execute yarn add react-native again. it works for me

**Comment by brentvatne** [comment]
is anyone able to provide a minimal reproducible example for the issue here?

**Comment by marklawlor** [comment]
I can see a scenario where a custom`tsconfig`/`babel` could be breaking your applicaition

For example turning off `esModuleInterop` could cause your `import` to transpile differently. Instead of transpiling `import 'package'` to `require('package').default`, it would compile to `require('package')` (the old TS behaviour) https://www.typescriptlang.org/tsconfig/#esModuleInterop.

But we would need someone to submit a reproduction with their config to test it. 

If you are turning off this setting, be aware that the official React Native `tsconfig` enables this setting https://www.npmjs.com/package/@tsconfig/react-native, so it is expected that project should have this enabled.

**Comment by dejagersh** [comment]
Already fixed in a recent update. Thx team!

**Pull request closed without merging**
