### PR TITLE
[docs][expo-document-picker][refactor]: Fixed a minor typo

### PR DESCRIPTION
**Pull request by Jemeni11**
# Why
This PR fixes the typo in the type field of the [DocumentPickerOptions table](https://docs.expo.dev/versions/latest/sdk/document-picker#documentpickeroptions)

# How
I changed the sentence: 
> The [MIME type(s)](https://en.wikipedia.org/wiki/Media_type) of the documents that are available to be picked. Is also supports wildcards like `image/*` to choose any image. 

to
> The [MIME type(s)](https://en.wikipedia.org/wiki/Media_type) of the documents that are available to be picked. It also supports wildcards like `image/*` to choose any image.

# Test Plan

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Review by Simek — COMMENTED** [review]
Hello @Jemeni11, thank you for spotting that typo and updating JSON data! 👍 

In general, those files are generated from the source code and JSDoc comments for the given package, so it would be great if you can also correct the typo in there, and rebuild the build files:
* https://github.com/expo/expo/blob/main/packages/expo-document-picker/src/types.ts#L5

This will ensure, that next time when someone runs `et gdad` (command from `tools` to generate JSON files) your changes won't be overwritten. A more detailed guide can be found here:
* https://github.com/expo/expo/tree/main/docs#updating-api-reference-docs

**Comment by amandeepmittal** [comment]
Hey @Jemeni11, I'd suggest reverting the changes in the JSON file in this PR and then follow the process as Simek mentioned from here: https://github.com/expo/expo/tree/main/docs#updating-api-reference-docs. Then you, when you run the command `yarn build` while editing the file: https://github.com/expo/expo/blob/main/packages/expo-document-picker/src/types.ts#L5, and then run the `et` commands ([as specified here](https://github.com/expo/expo/tree/main/docs#step-2-apply-typedoc-updates-to-expodocs-repo)), the JSON files will automatically get those updates.

**Review by Simek — APPROVED** [review]
I have updated the source files and rebuild the package, so this change should be ready to ship. Thank you @Jemeni11 for working on this! 👍

**Comment by Jemeni11** [comment]
Hey @Simek @amandeepmittal 
Thanks for all the help
I'm sorry I wasn't able to complete the pull request as I was pretty busy and I forgot about it at a point.
Thanks once again for helping me contribute to such a great product :+1:

**Pull request merged**
