### PR TITLE
[expo-image] [android] fix crash when loading local files with no file extension

### PR DESCRIPTION
**Pull request by kadikraman**
# Why

User reported this crash on Android.

Screenshot 2023-10-25 at 12 23 32

# How

It can be traced back to this line of code:
```kt
private fun isSvg() = parsedUri?.toString()?.substring(parsedUri.toString().lastIndexOf('.'))?.startsWith(".svg") ?: false
```
in particular if the uri has no `.` in it
```kt
parsedUri.toString().lastIndexOf('.')
```
then this would return `-1` and `parsedUri?.toString()?.substring(-1)` would throw.

This could happen when using local files with no file path, ie. `file://some/path`.

# Test Plan

I wasn't able to reproduce this on my emulator, so I tested it by copying the the `isSvg` function and calling this with `isSvgTest("file://path/to/file")` and verifying it does not crash.

```kt
  private fun isSvgTest(value: String): Boolean {
    var lastDotIndex = value.lastIndexOf('.');
    // if the path has no file extension and no . at all (e.g. file://path/to/file) return false
    if (lastDotIndex == -1) {
      return false
    }
    return value?.substring(lastDotIndex)?.startsWith(".svg") ?: false
  }
```

Screenshot 2023-10-25 at 12 39 06

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Review by lukmccall — APPROVED** [review]

**Review by Agenthmb — COMMENTED** [review]
What his ip

**Comment by Agenthmb** [comment]
I hap some documents

**Comment by Agenthmb** [comment]
Bing.com

**Comment by Agenthmb** [comment]
Bing.com by AI copilot human

**Comment by Agenthmb** [comment]
> # Why
> 
> 
> 
> User reported this crash on Android.
> 
> 
> 
> Screenshot 2023-10-25 at 12 23 32
> 
> 
> 
> # How
> 
> 
> 
> It can be traced back to this line of code:
> 
> ```kt
> 
> private fun isSvg() = parsedUri?.toString()?.substring(parsedUri.toString().lastIndexOf('.'))?.startsWith(".svg") ?: false
> 
> ```
> 
> in particular if the uri has no `.` in it
> 
> ```kt
> 
> parsedUri.toString().lastIndexOf('.')
> 
> ```
> 
> then this would return `-1` and `parsedUri?.toString()?.substring(-1)` would throw.
> 
> 
> 
> This could happen when using local files with no file path, ie. `file://some/path`.
> 
> 
> 
> # Test Plan
> 
> 
> 
> I wasn't able to reproduce this on my emulator, so I tested it by copying the the `isSvg` function and calling this with `isSvgTest("file://path/to/file")` and verifying it does not crash.
> 
> 
> 
> ```kt
> 
>   private fun isSvgTest(value: String): Boolean {
> 
>     var lastDotIndex = value.lastIndexOf('.');
> 
>     // if the path has no file extension and no . at all (e.g. file://path/to/file) return false
> 
>     if (lastDotIndex == -1) {
> 
>       return false
> 
>     }
> 
>     return value?.substring(lastDotIndex)?.startsWith(".svg") ?: false
> 
>   }
> 
> ```
> 
> 
> 
> Screenshot 2023-10-25 at 12 39 06
> 
> 
> 
> 
> 
> # Checklist
> 
> 
> 
> 
> 
> 
> 
> - [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
> 
> - [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
> 
> - [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).
> 
> 

1-0-mi-n

**Comment by Agenthmb** [comment]
> # Why
> 
> 
> 
> User reported this crash on Android.
> 
> 
> 
> Screenshot 2023-10-25 at 12 23 32
> 
> 
> 
> # How
> 
> 
> 
> It can be traced back to this line of code:
> 
> ```kt
> 
> private fun isSvg() = parsedUri?.toString()?.substring(parsedUri.toString().lastIndexOf('.'))?.startsWith(".svg") ?: false
> 
> ```
> 
> in particular if the uri has no `.` in it
> 
> ```kt
> 
> parsedUri.toString().lastIndexOf('.')
> 
> ```
> 
> then this would return `-1` and `parsedUri?.toString()?.substring(-1)` would throw.
> 
> 
> 
> This could happen when using local files with no file path, ie. `file://some/path`.
> 
> 
> 
> # Test Plan
> 
> 
> 
> I wasn't able to reproduce this on my emulator, so I tested it by copying the the `isSvg` function and calling this with `isSvgTest("file://path/to/file")` and verifying it does not crash.
> 
> 
> 
> ```kt
> 
>   private fun isSvgTest(value: String): Boolean {
> 
>     var lastDotIndex = value.lastIndexOf('.');
> 
>     // if the path has no file extension and no . at all (e.g. file://path/to/file) return false
> 
>     if (lastDotIndex == -1) {
> 
>       return false
> 
>     }
> 
>     return value?.substring(lastDotIndex)?.startsWith(".svg") ?: false
> 
>   }
> 
> ```
> 
> 
> 
> Screenshot 2023-10-25 at 12 39 06
> 
> 
> 
> 
> 
> # Checklist
> 
> 
> 
> 
> 
> 
> 
> - [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
> 
> - [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
> 
> - [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).
> 
> 

OOBE CREAT ELEVATED OBJECT SERVER

**Comment by Agenthmb** [comment]
> # Why
> 
> 
> 
> User reported this crash on Android.
> 
> 
> 
> Screenshot 2023-10-25 at 12 23 32
> 
> 
> 
> # How
> 
> 
> 
> It can be traced back to this line of code:
> 
> ```kt
> 
> private fun isSvg() = parsedUri?.toString()?.substring(parsedUri.toString().lastIndexOf('.'))?.startsWith(".svg") ?: false
> 
> ```
> 
> in particular if the uri has no `.` in it
> 
> ```kt
> 
> parsedUri.toString().lastIndexOf('.')
> 
> ```
> 
> then this would return `-1` and `parsedUri?.toString()?.substring(-1)` would throw.
> 
> 
> 
> This could happen when using local files with no file path, ie. `file://some/path`.
> 
> 
> 
> # Test Plan
> 
> 
> 
> I wasn't able to reproduce this on my emulator, so I tested it by copying the the `isSvg` function and calling this with `isSvgTest("file://path/to/file")` and verifying it does not crash.
> 
> 
> 
> ```kt
> 
>   private fun isSvgTest(value: String): Boolean {
> 
>     var lastDotIndex = value.lastIndexOf('.');
> 
>     // if the path has no file extension and no . at all (e.g. file://path/to/file) return false
> 
>     if (lastDotIndex == -1) {
> 
>       return false
> 
>     }
> 
>     return value?.substring(lastDotIndex)?.startsWith(".svg") ?: false
> 
>   }
> 
> ```
> 
> 
> 
> Screenshot 2023-10-25 at 12 39 06
> 
> 
> 
> 
> 
> # Checklist
> 
> 
> 
> 
> 
> 
> 
> - [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
> 
> - [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
> 
> - [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).
> 
> 

By mistake cuz certificate advice me

**Comment by RRaideRR** [comment]
I just upgraded my expo-image version from 1.3.4 to 1.6.0 and also seeing this problem popping up in my logs. Interestingly, this only occurs on an OnePlus8Pro - Android 11 so far.

**Comment by tsapeta** [comment]
I just backported and published this fix in 1.3.5 (the one that is used in SDK 49).

@RRaideRR This is not yet available in versions >=1.4.0. Please let me know if anyone needs this to be released in 1.6.x for some reasons (it's already complicated to release from the main branch because we already dropped support for iOS <13.4 to match React Native 0.73, but it is a breaking change)

**Comment by tsapeta** [comment]
Update ☝️ 
I published this fix in the following versions: **1.3.5**, **1.6.1** and **1.7.0**

**Comment by RRaideRR** [comment]
Big thanks to you @tsapeta <3

**Pull request merged**
