### PR TITLE
[Android][sdk 45] Update standalone app build files

### PR DESCRIPTION
**Pull request by bbarthec**
# Why

[Android Standalone QA](https://github.com/expo/expo/blob/main/guides/releasing/Release%20Workflow.md#22-standalone-app-quality-assurance)

# How

1. `et android-build-packages` to generate new `aar`s
2. add missing `includeBuild('../node_modules/react-native-gradle-plugin')` to `settings.gradle` as it was missing for standalone build

# Test Plan

1. ` et android-shell-app --url https://exp.host/@bbarthec/native-component-list/index.exp\?sdkVersion\=45.0.0 --sdkVersion 45.0.0`
2. `adb install /tmp/shell-debug.apk`
3. Clicked through all the screens and gathered all observations in [Notion docs](https://www.notion.so/expo/Android-Standalone-QA-03dde78a17134a238deb7a86d3e9d601)

### CODE REVIEW

**Comment by bbarthec** [comment]
I've built the packages basing of the `main` branch (I suppose I should have done it basing of `sdk-45` branch), but looking at the commits tree graph I see there's nothing that needs to be adjusted 👀 
Screenshot 2022-04-26 at 10 48 12

**Comment by Kudo** [comment]
@bbarthec thanks for pushing standalone build and QA ready. could you double check whether we would commit the prebuild packages into git? from my memory, we didn't and [instead to upload the prebuild packages](https://github.com/expo/expo/blob/10cb8fb25096e706ad7c91b946b00cadfa3bc214/.github/workflows/shell-app-android.yml#L73-L91). please correct me if i missed something 😅

**Comment by bbarthec** [comment]
@kudo, to be honest I've got no idea as I've haven't touched this part of the release process for a longer while 😅 
cc @tsapeta, @brentvatne 
If we changed the process I wonder why we do not provide any up-to-date instructions for an outsider like me 🤔😝

**Comment by brentvatne** [comment]
@bbarthec - yeah we don't commit these to the repo, i don't think anything has changed on this in a while but the instructions perhaps could be more clear. we're not paying too much attention to classic build stuff since it's going to be gone very soon!

**Comment by brentvatne** [comment]
to elaborate on that - if you were able to get a standalone app built locally after running `expotools android-build-packages` then we're good to go with our smoke test qa here! when we're ready to deploy this, we follow [these steps](https://github.com/expo/expo/blob/main/guides/releasing/Release%20Workflow.md#stage-4---standalone-apps)

**Comment by bbarthec** [comment]
@kudo, @brentvatne I've removed prebuild packages ❌ 
Let me know what else is there to be done in terms of Versioned QA on Android 😉

**Review by Kudo — APPROVED** [review]
maybe to change the pr's title because it's now not from `expotools android-build-packages`.

thanks for your help 🙏

**Pull request merged**
