### PR TITLE
[docs] Update gestures.mdx

### PR DESCRIPTION
**Pull request by nachoiacovino**
# Why

Wouldn't work with the provided code

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [x] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Comment by amandeepmittal** [comment]
Hi @nachoiacovino, adding a `uri` in the source will break this component since it all the sticker images are already using `require` syntax. You can verify this by seeing the example code here: https://github.com/expo/examples/blob/18e116472c547d14db8fba80600d33866d208649/stickersmash/components/EmojiList.tsx#L10

**Comment by nachoiacovino** [comment]
> Hi @nachoiacovino, adding a `uri` in the source will break this component since it all the sticker images are already using `require` syntax. You can verify this by seeing the example code here: https://github.com/expo/examples/blob/18e116472c547d14db8fba80600d33866d208649/stickersmash/components/EmojiList.tsx#L10

ah damn that makes sense, my typescript was still complaining for some reason, will take a look again on why was that happening, thanks and sorry for wasting your time!

**Comment by nachoiacovino** [comment]
@amandeepmittal my typescript kept failing with `Type 'string' is not assignable to type 'ImageSourcePropType | SharedValue<ImageSourcePropType | undefined> | undefined'.ts(2322)` so I changed pickedEmoji to be of type `ImageSource` from "expo-image" and that fixed it, it has multiple changes so I'm happy to take it if you want but wanted to check with you first, I believe otherwise it will _still_ work for people but they are gonna run into type issues because string is not correct since as you said, you're doing the `require`

**Comment by amandeepmittal** [comment]
Hey @nachoiacovino, would you like to create a PR for that? I'll be happy to test it and discuss it with you :)

**Pull request closed without merging**
