### PR TITLE
[docs] Move anchor icon to the right and make header clickable

### PR DESCRIPTION
**Pull request by byCedric**
# Why

This updates the permalinks to fix a couple of things:

- Move anchor to the right to allow other symbols (like bullets) to render without conflicts (like [Firebase](https://firebase.google.com/docs/ios/setup#prerequisites) or [NextJS](https://nextjs.org/docs#related))
- Replace space between anchor and icon to allow moving mouse over to anchor without hiding the icon
- Makes header fully-clickable instead of the icon only
- Use `em` for icon size to scale down based on the text size

# How

- Updated `<Permalink />`
- Moved fix for collapsible permalinks to permalink itself
- Added fix for code blocks in links for Safari to inline code block

Component | Chrome | Safari | Firefox
--- | --- | --- | ---
`<h2>` | chrome-h2 | safari-h2 | firefox-h2
`<h3>` | chrome-h3 | safari-h3 | firefox-h3
`<summary>` | chrome-details | safari-details | firefox-details
`<code`> | chrome-code | safari-code | firefox-code

# Test Plan

I've deployed this to my own S3 bucket, these are the links that are interesting:

- [bare/hello-world](http://cedrics-expo.s3-website.eu-central-1.amazonaws.com/bare/hello-world/#android-configuration) - using h2 and h3
- [versions/v39.0.0/config/app](http://cedrics-expo.s3-website.eu-central-1.amazonaws.com/versions/v39.0.0/config/app/) - using code
- [introduction/faq](http://cedrics-expo.s3-website.eu-central-1.amazonaws.com/introduction/faq/) - using collapsible component
- [workflow/web](http://cedrics-expo.s3-website.eu-central-1.amazonaws.com/workflow/web/#-progressive-web-apps) - using link in permalink

### CODE REVIEW

**Comment by barthap** [comment]
> - Makes header fully-clickable instead of the icon only

What about headings which are links already? E.g. here: https://docs.expo.io/workflow/web/#-progressive-web-apps

**Comment by byCedric** [comment]
> > * Makes header fully-clickable instead of the icon only
> 
> What about headings which are links already? E.g. here: https://docs.expo.io/workflow/web/#-progressive-web-apps

Although I wouldn't recommend it, it works just like you would expect. 😄

**Comment by barthap** [comment]
There's one problematic place: http://cedrics-expo.s3-website.eu-central-1.amazonaws.com/versions/v39.0.0/sdk/app-auth/#oauthnonceparameter

The anchor goes to the next line there. I think that the solution would be to format it the same way as "Progressive web apps" in `workflow/web`. Custom heading components are used there

**Review by barthap — COMMENTED** [review]
There's one problematic place: http://cedrics-expo.s3-website.eu-central-1.amazonaws.com/versions/v39.0.0/sdk/app-auth/#oauthnonceparameter

The anchor goes to the next line there. I think that the solution would be to format it the same way as "Progressive web apps" in `workflow/web`. Custom heading components are used there

**Comment by byCedric** [comment]
Ah I see, thanks for noticing! It's a bit strange how MDX parses that header. It has this structure:

```
Permalink
└── Paragraph
    └── Link
        └── Code
```

I'm not sure why the paragraph is added here, but it shouldn't. And that's causing the next line (it renders paragraphs as blocks). I'll add a wrapper around the permalink content that forces its content to `inline-block`, to play nice with the anchor element.

**Review by jonsamp — APPROVED** [review]
This looks great to me!

**Review by barthap — APPROVED** [review]
It's not that strange when you look at the `.md` file:
```js
<H2 sidebarTitle="....">

`HeaderAsACode`

</H2>
```

There must be one blank line between JSX and Markdown tags to let MDX parse them as _inline code inside JSX tag_. But those blank lines also make MDX reading the middle one as a separate paragraph, just because that's the way markdown works.
That's one drawback of ~~mixing~~ nesting markdown and JSX. Another solution would be to just use JSX:
```js
<H2 sidebarTitle="...">
  <inlineCode>HeaderAsACode</inlineCode>
</H2>
```
That's what I did in `workflow/web` with _"Progressive web apps"_ link. Maybe there's a better solution that I don't know.

Anyway, now it looks good to me 👍

**Review by brentvatne — APPROVED** [review]
thank you, and exemplary pr description 👏

**Pull request merged**
