### PR TITLE
[expo] fix fetch streaming does not complete

### PR DESCRIPTION
**Pull request by Kudo**
# Why

fix streaming request does not complete if the request is complete before streaming started. this is a regression from my #33577

# How

streaming requests rely on event listeners. if the request is complete, we unregister all event listeners. the caller will never return then.
this pr tries to return the queuedData from startStreaming. for completed requests, we don't use event listeners anymore.

# Test Plan

add an e2e test and the ci test-suite should pass

# Checklist

- [x] I added a `changelog.md` entry and rebuilt the package sources according to [this short guide](https://github.com/expo/expo/blob/main/CONTRIBUTING.md#-before-submitting)
- [x] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)

### CODE REVIEW

**Comment by fobos531** [comment]
@Kudo Please let us know once this is published on NPM - Do you know on starting with which `expo` version the #33577 regression was introduced?

**Comment by Kudo** [comment]
@fobos531 `expo@52.0.18` should not be impacted by #33577. i can publish a next dist-tag version if you want to try it out. sorry for having the regression

**Comment by fobos531** [comment]
> @fobos531 `expo@52.0.18` should not be impacted by #33577. i can publish a next dist-tag version if you want to try it out. sorry for having the regression

Sure, that works! Thank you and no worries.

**Comment by Kudo** [comment]
we published `expo@52.0.21` which includes the fix. please let me know if that doesn't work for you. thanks!

**Pull request merged**
