### PR TITLE
[home] Use more modern graphql-codegen for queries and types

### PR DESCRIPTION
**Pull request by wschurman**
# Why

This upgrades some packages related to graphql-codegen and uses the new generated hooks for queries in the app.

# How

Upgrade packages, upgrade codegen config, replace manual queries with hooks.

# Test Plan

Run home, see all the data loading works.

### CODE REVIEW

**Comment by Simek** [comment]
Refs #15124

**Review by jonsamp — APPROVED** [review]
im not familiar with this repo, but the changes look fine to me. Thanks for upgrading dependencies/code gen

**Comment by wschurman** [comment]
> It looks like to me like you are reverting some of the changes applied in the reference above PR 😛

Yep. We can go back to using the generated hooks if we remove `typed-document-node` (not necessary) and add `typescript-react-apollo`. The generated hooks provide better typesafety for things like the refetch and merge parameters as far as I can tell.

**Review by Simek — APPROVED** [review]
Just to quote the referenced discussion:
> [...] you probably don't need `typescript-react-apollo` if you are using `typed-document-node`.

It looks like it is a matter of preference, more that the recommended setup, so if you want switch back from `typed-document` to Apollo plugin it's fine to me. 🙂 

Pre-generated hooks are useful, not denying that, but I personally not a big fan of the types name changes, for example:
* `AccountData` to `Home_AccountDataQuery` etc.

**Comment by wschurman** [comment]
> Pre-generated hooks are useful, not denying that, but I personally not a big fan of the types name changes

We can probably alias them or rename the queries. The key is that defining the data types manually encourages people to `any` cast results from the graphql query in order to share code that operates on that data, yet there's no guarantee that the field selections were the same. For example, let's say I have two queries:

```graphql

query Q1 {
  app {
    id
    name
    link
  }
}

query Q2 {
  app {
    id
    name
    link
  }
}

type App {
  id: string;
  name: string;
  link: string;
}

const data = ((await execute Q1) as any) as App;
const data2 = ((await execute Q2) as any) as App;

fun(app: App): ... {}
```

We've seen this happen quite a lot on the Expo website codebase, and it causes very subtle but preventable bugs. By using the actual GraphQL result types in combination with things like `Partial` and `Pick`, the type safety is retained.

**Pull request merged**
