### PR TITLE
[templates] Upgrade bare templates to Gradle 5

### PR DESCRIPTION
**Pull request by IjzerenHein**
# Why

The templates for bare-projects still use Gradle 4, but the Expo client and react-native 0.61 use Gradle 5. We should have an up-to-date bare-template.
This also fixes eject to bare for `expo-firebase-analytics` #7579

# How

- Upgraded `expo-template-bare-minimum`
- Upgraded `expo-template-bare-typescript`

# Test Plan

I tested this by ejecting an app (which then uses the latest template from npm) and then making exactly these changes to my ejected app in order to upgrade to Gradle 5.

# Requirements

- `expo-updates` should also be updated, see PR  #7577

### CODE REVIEW

**Review by sjchmiela — APPROVED** [review]
This looks great to me, thanks for jumping on this so quickly. 🙌 I'm wondering if we would like to update the rest of the template files too (if there is a newer version available in `react-native-lab/react-native/template`). What do you think?

**Review by brentvatne — APPROVED** [review]

**Comment by brentvatne** [comment]
going to ship this now but might be a good idea to update the template @sjchmiela mentioned as well

**Comment by IjzerenHein** [comment]
> This looks great to me, thanks for jumping on this so quickly. 🙌 I'm wondering if we would like to update the rest of the template files too (if there is a newer version available in react-native-lab/react-native/template). What do you think?

Yes totally, that's a great idea, we should do that!

**Comment by IjzerenHein** [comment]
@brentvatne there's another issue which makes the Gradle 5 build. This PR #7577 update is also required for making Gradle 5 work

**Pull request merged**
