### PR TITLE
[cli] Add start command

### PR DESCRIPTION
**Pull request by EvanBacon**
# Why

- Hardest part of versioning the CLI so this is gonna be a tricky PR to review.
- Resolve ENG-2751 ENG-2760 ENG-2765

The contents of this feature can be visualized as six sections:
1. **Utilities**: Standalone functions that can be reliably tested in-memory. #16508
2. **Doctor**: Modules used to assert prerequisites. These are broken up into project-level and system-level checks. 
3. **Platforms**: Modules that delegate interacting with Apple and Android specific functionality. The majority of which is implemented in cross-platform classes that share logic and testing across platforms. Platform code is mostly used for 'launching' apps based on URLs. The platforms ensure devices are installed, apps can be launched, and URLs are opened. #16516
4. **Servers**: Modules the manage the life-cycle of bundler development servers. These modules also maintain how dev server URLs are generated. The server code calls into the platform code to launch server URLs on devices. Server code also manages how bundlers are loaded and runtime logging is presented to the user. Server code also contains the custom middleware for interstitial pages and manifest signing/serving. #16517
5. **Interface**: The keystroke and logging modules used to create the 'Terminal UI'. The interface calls into the server code to perform actions like sending web socket commands to the respective runtimes, opening URLs, selecting devices, and presenting URLs as QR codes. #16518
6. **CLI**: Finally we have the actual bin code which converts CLI arguments into options for instantiating servers, and launching the UI. #16518

# How

Some features have been strategically dropped, either to make reviewing easier (they'll be migrated later) or just dropped in general as a way to reduce bundle size. This PR will significantly increase the net install size of `expo` so we're looking for places to make cutbacks wherever possible.

- Dropped `XDL_PORT`, `XDL_HOST`, `XDL_SCHEME`, `SERVER_URL` in favor of `EXPO_STAGING` and `EXPO_LOCAL` environment variables.
- Dropped `WEB_PORT`, `EXPO_PACKAGER_HOSTNAME`, `EXPO_MANIFEST_PROXY_URL`, `EXPO_EDITOR`.
- Dropped `.exprc` support which we read from but didn't write to.
- Dropped support for SDK 40 auto TypeScript setup since the `expo/tsconfig.json` is now always present.
- Dropped dev tools UI. This is very heavy, slow, unmaintained, creates race conditions since it can only be opened while the CLI is opened, and generally just not very useful. Dropping the dev tools UI now can give us a path to redesigning and potentially adding back later (wouldn't recommend). We started sunsetting this feature a year ago https://github.com/expo/expo-cli/pull/3207 with an even larger step 3 months ago https://github.com/expo/expo-cli/pull/3966.
- Dropped `lodash`.
- Dropped most project settings (`.expo/settings.json`) (all but url randomness for ngrok -- pending). I've restructured the CLI to be more tightly integrated, instead of parsing params then writing them to a bunch of different persistent files, we now just pass them around in-memory. This eliminates the need for extra cache clearing measures https://github.com/expo/expo-cli/issues/2953 https://github.com/expo/expo-cli/issues/2952 since the CLI has less caching.
- Dropped packager info (`.expo/packager-info.json`) in favor of passing arguments around in-memory. pid tracking is also no longer needed since React Native packager is gone.
- Dropped support for legacy React Native packager, this version of `expo start` will only support the "new" dev server API.
- Dropped double ngrok system. We now only need to run one instance of ngrok, this also means we drop all logic for handling "ill" states where some ports don't work.
- Dropped deprecated `.expo.*` extension warning. Can move this feature to doctor if needed.
- Dropped amplitude analytics. This was done previously in the auth commands PR.
- Dropped sendTo option. ENG-2765 we started sunsetting this feature long ago when the sms option was removed. The replacement was dev sessions (automatically showing recent projects in Expo Go).
- Dropped deprecated url options. https://github.com/expo/expo-cli/pull/4092
- Dropped warning about updating the CLI. This is no longer needed now that the CLI is versioned with Expo.
- Dropped support for using global `@expo/metro-config`.
- Dropped EXPO_USE_APPLE_DEVICE temporarily to simplify transition.
- Replaced `axios` with `node-fetch` in the module that downloads and installs apps on the simulator and emulator.
- Reduced the overhead of converting args to settings to options. Still more work to be done here.
- Improved documentation on feature flags and functions.
- Changed default command `npx expo` to be `npx expo start`

- [ ] Binary support (watchman, adb)
- [x] Reduce log mitigation with bunyan.
- [x] Automated testing...

# Test Plan

- [x] E2E downloading apps with progress indication. 
- [x] Test dev server logging.
- [x] Test URL utils.
- [x] Manifest handler shape.
- [x] Simulator validations.
- [x] Emulator validations.
- [ ] TBD...

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] This diff will work correctly for `expo build` (eg: updated `@expo/xdl`).
- [x] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Comment by bbarthec** [comment]
@EvanBacon, you know that absolutely nobody is going to review this PR? 👀
And clicking `Approve` button without performing an actual review is missing the whole point.
Number of changes is impossible to get grasp of. I know it's in the `Draft` stage so I hope you're going to split it into multiple PRs that are approachable, because this one is not approachable at all.

**Comment by dsokal** [comment]
Totally agreed with @bbarthec, this PR is a nightmare for reviewers. I'm more than sure that you'll get approvals only because "TLDR".

**Comment by EvanBacon** [comment]
Closing in favor of https://github.com/expo/expo/pull/16518

**Review by nocus75-debug — COMMENTED** [review]
Appears to be able to resolve my problem. Will give it a try.

**Pull request closed without merging**
