### PR TITLE
Clarify Supported Node Versions

### PR DESCRIPTION
**Pull request by cruzach**
# Why

CLI [#661](https://github.com/expo/expo-cli/issues/661)

Saying v10 or newer wasn't accurate since support for v11 ends tomorrow.

### CODE REVIEW

**Comment by ide** [comment]
How about "10 or a newer stable version"? (even-numbered releases are stable)

**Comment by cruzach** [comment]
Ah I didn’t know that about even-numbered versions. You think to just omit that we support 8, though?

**Comment by ide** [comment]
We should include 8, too, with something like “8 or newer stable version”.

**Comment by cruzach** [comment]
Lmk if that looks better to you (Ville mentioned in the issue to state we recommend v10, that's why I kept it in there)

**Comment by ide** [comment]
This wording looks good to me.

**Pull request merged**
