### PR TITLE
refactor: Replace `tempy` with equivalent code

### PR DESCRIPTION
**Pull request by kitten**
# Why

Resolves ENG-13001
Related: #30425
Related: https://github.com/expo/node-bunyan/pull/1
Related: https://github.com/expo/devcert/pull/2

This is for the dependency chain:
- `tempy@0.7.1`
- `del@6.1.1`
- `rimraf@3.0.2`

The `rimraf@3.0.2` causes a deprecation warning, which we can avoid. While we can't upgrade `tempy` without running into its ESM-only issues for now, we can replace it with direct dependencies on `temp-dir@~2.0.0` (and `unique-string@~2.0.0`) to retain identical behaviour.
(Note: We could also replace them but that's not relevant for this PR)

This is only to then avoid the dependency chain on `rimraf` avoiding the deprecation warning.
This warning may still be retained even when all related PRs are merged due to `@react-native/codegen@0.74.85 -> jscodeshift@0.14.0`.

# How

- Remove `tempy`
- Replace it with `temp-dir@~2.0.0` and `unique-string@~2.0.0`
- Add equivalent code for the `file` and `directory` functions

# Test Plan

- Ran unit tests and E2E tests locally where appropriate 

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Comment by kitten** [comment]
Two tests in `@expo/prebuild-config` seem to be failing for unrelated reasons. Snapshots are out of date. Reproduces on `main`.

**Review by byCedric — APPROVED** [review]
thank-you

**Comment by byCedric** [comment]
@kitten I think the `expo-test-runner` changes are triggering linting issues on CI though, but looks great!

image

**Comment by byCedric** [comment]
If you rebase on `main`, the `prebuild-config` tests should succeed now!

**Review by Kudo — APPROVED** [review]

**Pull request merged**
