### PR TITLE
[expo-notifications][Android] Fix FCMv1 icons and NPE

### LINKED ISSUE #24844: Push Notification Icon not working on Android
### Minimal reproducible example

https://github.com/jkstrawn/notify-genie

### Summary

The push notification icon for my expo app shows up as a white circle on my Pixel 7 Android 13 phone. I've made a test project "Notify Genie" for demonstrating the issue.

Screenshot_20231012-094746

Here is what the notification icon file looks like:

notification-icon

I'm sending the push notification through the FCM "Notification" type message. I understand this doesn't make use of the expo-notifications library, but I'm still using the library for setting channels and granting permission.

I'm setting the app icon in the `app.config.ts` file like this:
```

const assetUrl = "./src/assets/images";

{
...
    notification: {
        icon: `${assetUrl}/notification-icon.png`,
        color: "#5e71bc",
    },
...
}
``` 

The request I'm sending to FCM looks like this:
```
{
  "message": {
    "token": "fUJpTkIBR3yt3_lZIdRaMH:APA9...",
    "notification": {
      "title": "This is a default message",
      "body": "how does the icon look? 😢",
    }
  }
}
```

I'm testing by creating a build, downloading the app onto my phone, and sending the push notification request through FCM.

```
eas build -p android --profile alpha
```

I haven't seen anyone getting this particular icon issue, so I don't know if there's something funky about my particular app setup or what. The icon for the app itself works fine, it's only the notification icon that isn't working, and only on some of the phones that it's been tested on. I'm still working on compiling a list of working/not-working phones from my team, but at least for my particular phone the icon doesn't work.

Please let me know if there's any other information I should provide. Thank you

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 18.0.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
      npm: 8.6.0 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      @expo/webpack-config: ^19.0.0 => 19.0.0
      expo: 49.0.8 => 49.0.8
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.72.5 => 0.72.5
      react-native-web: ~0.19.0 => 0.19.9
    Expo Workflow: managed

### PR DESCRIPTION
**Pull request by douglowder**
# Why

- Fixes #24844 
- Corrects an NPE that can happen if a deep link in the app is opened

# How

- Change constants in the `expo-notifications` plugin to the correct ones expected for FCMv1
- Add the recommended code to guard against NPE when logging Android lifecycle events

# Test Plan

- CI should pass
- Test app should show the correct icon and color in notification banners

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Review by christopherwalter — APPROVED** [review]

**Comment by douglowder** [comment]
Published in expo-notifications 0.28.5

**Comment by mlukasik-dev** [comment]
@douglowder, @christopherwalter,
The release did not resolve the NPE issue. It still occurs when a user opens an app link.

Although I'm not a Java developer, I am curious about how using `Objects.requireNonNull` would solve this issue.
From my understanding, this method throws a [customized] exception when the value is null.

**Comment by douglowder** [comment]
@mlukasik-dev thanks for the report. I will get the NPE fixed in the next two days. Sorry for my confusion about that API.

**Comment by douglowder** [comment]
@mlukasik-dev NPE is fixed in #29370 and published in `expo-notifications@0.28.6`

**Comment by mlukasik-dev** [comment]
That was quick. Thank you very much! I can confirm that the issue has been resolved and deep links are working correctly on Android.

**Pull request merged**
