### PR TITLE
Upgrade uuid package and update uuid/v4 import to new format

### PR DESCRIPTION
**Pull request by wschurman**
# Why

https://github.com/expo/expo/pull/20013

# How

patch https://github.com/expo/expo/pull/20013 and `et cp`

# Test Plan
`et cp`
wait for CI

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Review by douglowder — APPROVED** [review]

**Comment by brentvatne** [comment]
i'm not sure this is safe -- we had to revert an upgrade to uuid v8 before: https://github.com/expo/expo/pull/13037#issuecomment-848558810

if v9 still depends on `crypto.getRandomValues()` then we'll need to polyfill that by default in all expo projects by default before loading any code that uses uuid

**Comment by tsapeta** [comment]
For the reasons mentioned by Brent, I had to revert this change (https://github.com/expo/expo/commit/3329e04d849b3ce0de9f59d38d66a29455573c80)

Running bare-expo app resulted with this error:
>  ERROR  Error: crypto.getRandomValues() not supported. See https://github.com/uuidjs/uuid#getrandomvalues-not-supported, js engine: hermes
 ERROR  Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 11): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient, RCTEventEmitter.
        A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native., js engine: hermes

**Comment by KingDoxik** [comment]
Would it be possible to use polyfill like this: https://www.npmjs.com/package/react-native-get-random-values?

**Comment by brentvatne** [comment]
@KingDoxik - yes, we also have a polyfill for `crypto.getRandomValues()`: https://github.com/expo/expo/tree/main/packages/expo-standard-web-crypto. the problem is that we would need to include this in every project that uses the expo package just to use the uuid package.

i think the best way forward for us here is to remove the uuid dependency in the expo package and vendor any code we need to generate a uuid.

**Comment by brentvatne** [comment]
another alternative - we can fork `uuid@3.4.0` to `@expo/uuid` and consume that package instead? then we don't end up with any of these odd dependency conflicts

**Comment by wschurman** [comment]
Thanks for reverting! Sorry for the thrash.

**Pull request merged**
