### PR TITLE
[docs] versionCode on Android is a number, not a string

### PR DESCRIPTION
**Pull request by kbrandwijk**
# Why

See title

# How

# Test Plan

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] This diff will work correctly for `expo build` (eg: updated `@expo/xdl`).
- [ ] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Review by Simek — COMMENTED** [review]
Hmm, I'm afraid that changing docs is not enough here, and we need to investigate the code and ensure what is really happening.

For example, there is platform agnostic field https://docs.expo.dev/versions/latest/sdk/application/#applicationnativebuildversion, which type is set to `string | null`, so in this context something didn't match with types.

**Comment by kbrandwijk** [comment]
I'm not sure what you mean. `expo.android.versionCode` in `app.json` is documented as integer here: https://docs.expo.dev/versions/latest/config/app/#versioncode, and also validated in VS Code and elsewhere as such.
image

`Application.nativeBuildVersion` has to be a string, because it's shared across platforms, and the iOS equivalent is a string. But that is not the field mentioned here in the docs. This is simply the field from app.json that is correctly shown to be an integer everywhere else.

**Comment by Simek** [comment]
Working with packages and adding autogenerated docs allow me to learn, that some changes are not that straight forward, as they looks, so I like to ask questions.

In this case, as you can see in the code, there is also a field called like that in `Constants`, and it is a part of an old Android manifest types, which is deprecated in favor of field I have linked you above:
* https://github.com/expo/expo/blob/main/packages/expo-constants/src/Constants.types.ts#L72=L80

This got me confused a bit, but in short, I think that we talk about two different pieces of code called the same. 😅

**Comment by kbrandwijk** [comment]
No problem, it's always good to doublecheck! But in this case, I think we can safely conclude that this is, in fact, a typo in the docs, and not an underlying issue in our type definitions.

**Review by Simek — APPROVED** [review]
Yup, you are right and this change is correct, let's ship it! 🙂

**Pull request merged**
