### PR TITLE
[Android][LocalAuthentication] Fixed cancelAuthenticate not working in Android

### PR DESCRIPTION
**Pull request by HuiSF**
# Why

`cancelAuthenticate` API actually cannot dismiss biometric prompt in Android. As the original implementation is incorrectly using `CancellationSignal` to attempt to cancel authentication flow initiated by `androidx.biometric.BiometricPrompt`. 

- `CancellationSignal` should be used in pair with `android.hardware.biometrics.BiometricPrompt` ([Reference](https://developer.android.com/reference/android/hardware/biometrics/BiometricPrompt#authenticate(android.os.CancellationSignal,%20java.util.concurrent.Executor,%20android.hardware.biometrics.BiometricPrompt.AuthenticationCallback)))

- To cancel authentication flow initiated by  `androidx.biometric.BiometricPrompt` should use its method `cancelAuthentication` ([Reference](https://developer.android.com/reference/androidx/biometric/BiometricPrompt#cancelAuthentication()))

# How

- Removed usage of `androidx.core.os.CancellationSignal`
- Updated implementation of `safeCancel` method to use `cancelAuthentication` method of `androidx.biometric.BiometricPrompt`

# Test Plan

- invoke `LocalAuthentication.cancelAuthenticate` method, biometric prompt should be dismissed correctly

# Screen records

| Before fix                                                   | After fix                                                    |
| ------------------------------------------------------------ | ------------------------------------------------------------ |
| BeforeFixScreenRecord | AfterFixScreenRecord |

### CODE REVIEW

**Review by lukmccall — CHANGES_REQUESTED** [review]
LGTM 💪

But you need to update the changelog -> https://github.com/expo/expo/blob/master/packages/expo-local-authentication/CHANGELOG.md

**Review by lukmccall — APPROVED** [review]

**Comment by HuiSF** [comment]
Thanks for the feedback and merging the fix @lukmccall ! A quick follow up question - do we have a estimated date to release this fix please?

**Comment by lukmccall** [comment]
Unfortunately, I don't know when we release this fix. If changes were only in js, I could publish it even right now. However, you changed the native code.

**Comment by HuiSF** [comment]
Thanks @lukmccall  :)

Yes I'm using `expo-local-authentication` with the bare flow. That would be great if you can release the fix soon for bare flow.

**Comment by lukmccall** [comment]
I'll release it as soon as I fixed some problems which I faced when I've tried to do it. Those problems aren't connected with this PR. So this fix should be live soon.

**Comment by lukmccall** [comment]
The package was published as `next` - https://www.npmjs.com/package/expo-local-authentication/v/9.4.0.

**Pull request merged**
