### PR TITLE
[linking] Fix useURL warning about removeEventListener

### LINKED ISSUE #16376: Update removeListener to remove() for useURL in expo-linking
### Summary

In `expo-linking` using the useURL hook triggers this warning. For the time being I have suppressed it with `LogBox.ignoreLogs` but would be nice to have removeListener updated to remove()

```
EventEmitter.removeListener('url', ...): Method has been deprecated. Please instead use `remove()` on the subscription returned by EventEmitter.addListener. 
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

44

### Environment

```
expo-env-info 1.0.2 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 14.15.5 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.17 - C:\Program Files\nodejs\yarn.CMD
      npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 29, 30, 31, 32
        Build Tools: 30.0.2, 30.0.3, 32.0.0
        System Images: android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom_64, android-30 | Google APIs Intel x86
 Atom, android-30 | Google Play Intel x86 Atom, android-32 | Google APIs Intel x86 Atom_64
    npmPackages:
      expo: ^44.0.6 => 44.0.6
      metro: 0.68 => 0.68.0
      react: 17.0.2 => 17.0.2
      react-native: 0.67.2 => 0.67.2
    Expo Workflow: managed
```

### Reproducible demo

Use the useURL hook and refresh the simulator a few times and the warning will popup

### PR DESCRIPTION
**Pull request by frankcalise**
# Why

Fixes [Update removeListener to remove() for useURL in expo-linking](https://github.com/expo/expo/issues/16376#)

# How

- `addEventListener` returns `EmitterSubscription` rather than `void` to match the React Native Linking API
- `useURL` hook now cleans up `addEventListener` via `remove` rather than `removeEventListener`

# Test Plan

Updated `test-suite` app and checked a sandbox app that the warning did not appear

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] This diff will work correctly for `expo build` (eg: updated `@expo/xdl`).
- [ ] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Review by tsapeta — APPROVED** [review]
Looks good! 👏 Thanks for your contribution 🤗
We'll be publishing the packages to npm pretty soon, I'll let you know once it's out 🙂

**Comment by tsapeta** [comment]
I've just published some packages, including `expo-linking@3.1.0` with your changes 😉 For now it's tagged as `next` on the npm. We'll promote it to `latest` at the end of the SDK45 release, but feel free to use before that.

**Comment by forki** [comment]
Is would be nice if the example could be fixed as well: https://github.com/expo/examples/issues/370

**Comment by forki** [comment]
the examples project is still not updated.

**Pull request merged**
