### PR TITLE
[ios][expo-av] Do not update session configuration when app is switched to background

### LINKED ISSUE #19042: [expo-av] Ducked Audio doesn't stop being ducked.
### Summary

I'm working on updating an app that utilizes Audio playback from Expo 44 to Expo 46. (expo-av ~10.2.0 to ~12.0.4).
Prior to updating, using `sound.stopAsync` / `sound.pauseAsync` would resume the ducked audio (e.g. of music playing). 

Now, no matter what I do, the ducked audio won't resume at full volume. Also, the ducked audio will pause when the app is closed now. 

Note that *unlike* https://github.com/expo/expo/issues/16272 , this is for *ducked audio*:
```tsx
      await Audio.setAudioModeAsync({
        playsInSilentModeIOS: true,
        interruptionModeIOS: InterruptionModeIOS.DuckOthers,
      });
```

See snack for a simple reproduction of this.

It's unclear to me if the API has changed, and the audio mode needs to be cleared, or something else done with the sound when paused now, or if this is broken. Any help would be very appreciated! 

### What platform(s) does this occur on?

iOS

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.3
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.20.0 - ~/.nvm/versions/node/v14.20.0/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 6.14.17 - ~/.nvm/versions/node/v14.20.0/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^46.0.0 => 46.0.10
      react: 18.0.0 => 18.0.0
      react-dom: 18.0.0 => 18.0.0
      react-native: 0.69.5 => 0.69.5
      react-native-web: ~0.18.7 => 0.18.9
    Expo Workflow: managed

### Minimal reproducible example

Reproduction steps:
1. Have a background sound playing (e.g. music from spotify).
2. Load the snack onto your device
3. play the audio (music should duck)
4. pause the audio (music should un-duck, but does NOT)
5. close the expo app (music will STOP, which is further-bad)

https://snack.expo.dev/@jacobjaffe/ludicrous-yogurt

### PR DESCRIPTION
**Pull request by de1acr0ix**
# Why

When app is switched to background, `expo-av` may set the audio session category to `AVAudioSessionCategorySoloAmbient` in the following call
https://github.com/expo/expo/blob/86589e9cabb9542cb535a4aa28182437640c79f8/packages/expo-av/ios/EXAV/EXAudioSessionManager.m#L159-L174
If all foreground modules are removed, the `_getRequestedCategory` call in `_updateSessionConfiguration` will always return `AVAudioSessionCategorySoloAmbient`. This means application will interrupt other apps audio sessions as `expo-av` is not deactivating its audio session anymore.

# How

Simply remove the `_updateSessionConfiguration` call in `moduleDidBackground`. It does not really make sense there. When app is switched to background, moduleDidBackground is supposed to be called by all foreground modules, one by one. And eventually you get an empty foreground module list. So it will always update the audio session category and stops non-mixable audio playback in other apps such as Spotify.

When app is put back to foreground, the correct audio session category will be handled automatically by `_updateSessionConfiguration` call in `moduleDidForeground`. This fixes #19042.

# Test Plan

Manual test with `bare-expo` and Spotify on real device (it includes app switching so I am not sure how to automate it).
- Build & install `bare-expo` on real iOS device.
- Open Spotify and play some music.
- Switch to `bare-expo` and select Audio in API tests.
- Ensure "Mix with others" and selected and start playback in test.
- Put `bare-expo` into background.
- Spotify shouldn't stop playback (without the changes it stops playback).

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Review by barthap — CHANGES_REQUESTED** [review]
Two things here:
- You shouldn't change the code in `ios/versioned`. We don't want to affect older SDK versions with this change. Leave changes only in the `packages/` directory.
- Please update the test plan in the PR description

> Simply remove the `_updateSessionConfiguration` call in `moduleDidBackground`. It does not really make sense there. When app is put into foreground, the correct audio session category will be handled by `_updateSessionConfiguration` call in `moduleDidForeground`.

We need to consider if it doesn't make sense only in your use case or in general. Personally, I don't have enough knowledge to have an opinion on this change.

**Comment by de1acr0ix** [comment]
> Two things here:
> 
> * You shouldn't change the code in `ios/versioned`. We don't want to affect older SDK versions with this change. Leave changes only in the `packages/` directory.
> * Please update the test plan in the PR description
> 
> > Simply remove the `_updateSessionConfiguration` call in `moduleDidBackground`. It does not really make sense there. When app is put into foreground, the correct audio session category will be handled by `_updateSessionConfiguration` call in `moduleDidForeground`.
> 
> We need to consider if it doesn't make sense only in your use case or in general. Personally, I don't have enough knowledge to have an opinion on this change.

I believe it does not make sense in general. When app is switched to background, `moduleDidBackground` is supposed to be called by all foreground modules, one by one. And eventually you get an empty foreground module list. So it will always update the audio session category and stops non-mixable audio playback in other apps such as Spotify.

**Comment by behenate** [comment]
@de1acr0ix Since you don't want to interrupt other apps, I'm assuming that your app has `staysActiveInBackground` set to false. In that case in here:
https://github.com/expo/expo/blob/49c358f7556e3e197480494dddfa73090b43ab79/packages/expo-av/ios/EXAV/EXAV.m#L167-L182
This
https://github.com/expo/expo/blob/49c358f7556e3e197480494dddfa73090b43ab79/packages/expo-av/ios/EXAV/EXAV.m#L171
Will be called before this:
https://github.com/expo/expo/blob/49c358f7556e3e197480494dddfa73090b43ab79/packages/expo-av/ios/EXAV/EXAV.m#L176

When you go down the `self _deactivateAudioSession` function it does  ` [self _updateSessionConfiguration];` elsewhere anyways. So even though I'd have to agree that changing the audio session on every backgrounding of the app might not make sense (audio session should actually be activated/deactivated depending on whether the app is playing or not and not based on the activity state of the app, but we won't be making such large changes to AV now), I'm not sure how this PR fixes the issue (I'm probably missing something here, since you tested your code) 🧐

At the same time I don't see how removing this line would break anything, the level of complexity here is why we are redoing AV as `expo-audio` and `expo-video` 😣

 Let me know if you can see a case where `[self _deactivateAudioSession];` won't call `[self _updateSessionConfiguration]`, but `[_kernelAudioSessionManagerDelegate moduleDidBackground:self];` will.

**Comment by de1acr0ix** [comment]
> @de1acr0ix Since you don't want to interrupt other apps, I'm assuming that your app has `staysActiveInBackground` set to false. In that case in here:
> 
> https://github.com/expo/expo/blob/49c358f7556e3e197480494dddfa73090b43ab79/packages/expo-av/ios/EXAV/EXAV.m#L167-L182
> 
> 
> This
> https://github.com/expo/expo/blob/49c358f7556e3e197480494dddfa73090b43ab79/packages/expo-av/ios/EXAV/EXAV.m#L171
> 
> 
> Will be called before this:
> https://github.com/expo/expo/blob/49c358f7556e3e197480494dddfa73090b43ab79/packages/expo-av/ios/EXAV/EXAV.m#L176
> 
> When you go down the `self _deactivateAudioSession` function it does ` [self _updateSessionConfiguration];` elsewhere anyways. So even though I'd have to agree that changing the audio session on every backgrounding of the app might not make sense (audio session should actually be activated/deactivated depending on whether the app is playing or not and not based on the activity state of the app, but we won't be making such large changes to AV now), I'm not sure how this PR fixes the issue (I'm probably missing something here, since you tested your code) 🧐
> 
> At the same time I don't see how removing this line would break anything, the level of complexity here is why we are redoing AV as `expo-audio` and `expo-video` 😣
> 
> Let me know if you can see a case where `[self _deactivateAudioSession];` won't call `[self _updateSessionConfiguration]`, but `[_kernelAudioSessionManagerDelegate moduleDidBackground:self];` will.

Sorry that my reply comes late. I don’t have much spare time for side projects now. But I am taking leaves next week and I will set some time to re-look into this.

**Comment by de1acr0ix** [comment]
@behenate When `[self _updateSessionConfiguration]` is called in `[self _deactivateAudioSession]`, all the foreground modules are still there (they are removed in `[_kernelAudioSessionManagerDelegate moduleDidBackground:self]`). Therefore, it will pick up a valid audio session category and option from the top foreground module, which is usually the active ones. So it will in fact skip the configuration. But if it is called in `[_kernelAudioSessionManagerDelegate moduleDidBackground:self]`, every time a foreground module has been removed and the active audio session category and option may change. Eventually all foreground modules get removed and the default values will be applied.

However, there is a PR, #24198, merged a while ago. It changes the default audio session category from `AVAudioSessionCategorySoloAmbient` to `AVAudioSessionCategoryAmbient`. So in fact now `expo-av` won't affect other apps when it is switched to background. That said, I don't feel we shall change the audio session category and option when app is switched to background at all as developers may deliberately set the category to `AVAudioSessionCategorySoloAmbient`.

**Review by behenate — APPROVED** [review]
@de1acr0ix  Ok, I missed the fact that the modules may be empty by the time `[self _shouldBeActive]` will be called, in this case I think this change should be fine

**Pull request merged**
