### PR TITLE
[docs] deploy docs to docs.expo.dev bucket

### PR DESCRIPTION
**Pull request by FiberJW**
# Why

We want docs.expo.dev to work, so we need to upload our exported files to the docs.expo.dev bucket as well as the existing docs.expo.io bucket.

# How

- Made a `buckets` list and looped the uploading part of the deploy script over each entry in that list
- Updated next.config.js to generate sitemaps for multiple domains
- Updated deploy deploy script to exclude sitemaps on main upload, but upload and rename the local sitemap files separately. (sitemaps are named `${domain}-sitemap.xml`, so I can choose to cp/rename it to sitemap.xml during the loop)

# Test Plan

When deploying docs, http://docs.expo.dev.s3-website.us-east-2.amazonaws.com/ should also be updated.

### CODE REVIEW

**Comment by byCedric** [comment]
We probably need to do some refactoring too, can help with that!

**Review by byCedric — APPROVED** [review]

**Comment by FiberJW** [comment]
@byCedric re-requesting because i updated the code to generate + upload domain-specific sitemaps

**Comment by byCedric** [comment]
Screenshot 2021-06-04 at 13 36 06

There are a few places left where we need to change this too. I think we can roll this out in 2 ways:

1. "The Yolo" - Changing everything in a single PR from `docs.expo.io` to `docs.expo.dev`
2. "The mirror" - Deploying to both buckets, and slowly migrating towards `docs.expo.io`.

If we go for 1, we need to do some more work before merging this. If we go for 2, I think we can merge this right already 😄

**Review by byCedric — APPROVED** [review]

**Comment by FiberJW** [comment]
Yeah "the mirror" is my plan. Get both things deployed, and then change expo.io references in subsequent PRs. Also, these links will be redirected to expo.dev anyway on the website, so no big deal if there are some links that aren't fully converted when docs.expo.dev starts getting traffic

**Comment by byCedric** [comment]
For context, to avoid duplicate search results for both `expo.io` and `expo.dev`, we are "hiding" `expo.dev` until we fully migrate over to `expo.dev`.

**Pull request merged**
