### PR TITLE
[bug fix] Only show USB attached Apple devices

### PR DESCRIPTION
**Pull request by shreeve**
# Why

It is common on macOS, for a physical iOS device (like an iPhone) to have both a `Network` and a `USB` entry in the device list. When running `expo`, both of these entries look same and show the little plug emoji (🔌 ). However, the `Network` version is not usable and, if selected, will crash with `TypeError: Cannot read properties of undefined (reading 'udid')`. This PR will only preserve true `USB` devices from the list of physical Apple devices, thus avoiding the annoying error of picking the `Network` device (since they look the same) and bombing out.

# How

I had to find out where the Apple device list was being built and then had to find the latest stage where the distinction between `USB` and `Network` devices could be used to filter out the `Network` devices. This code just lets the `USB` Apple devices through.

# Test Plan

Run the code and see that the list no longer includes spurious and non-working Apple device entries. Only `USB` physical Apple devices are shown now.

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [x] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Comment by Simek** [comment]
Refs ENG-6650

**Comment by shreeve** [comment]
> Refs [ENG-6617](https://linear.app/expo/issue/ENG-6617) & [ENG-6650](https://linear.app/expo/issue/ENG-6650)

@Simek - What do these two references point to? I can't follow those links.

**Comment by Simek** [comment]
Those are internal issues related to this change, I have referenced them for the context for reviewers.

**Comment by Simek** [comment]
@shreeve Going to close this one, since after changes in referenced above PR network connected device should be fully usable now.

Thank you for your contribution anyway, and feel free to open a new issue if you encounter any problems with the network connection after the next CLI release.

**Pull request closed without merging**
