### PR TITLE
[Camera] Fix return type of scanFromURLAsync

### PR DESCRIPTION
**Pull request by janicduplessis**
# Why

`scanFromURLAsync` returns an array of result as per the documentation and the native implementations, but the typescript type says it returns a single item.

# How

Fix the type by returning an array of BarcodeScanningResult

# Test Plan

Tested that scanFromURLAsync works and that there are no more type errors.

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [x] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Review by alanjhughes — APPROVED** [review]
Thanks @janicduplessis can you rebuild the js and I will merge?

**Comment by janicduplessis** [comment]
@alanjhughes Should be good now

**Comment by alanjhughes** [comment]
@janicduplessis sorry, looks like the test screen in NCL needs to be updated.

**Comment by janicduplessis** [comment]
Ok done!

**Pull request merged**
