### PR TITLE
📝 Update some URL's

### PR DESCRIPTION
**Pull request by rauldeheer**
I've noticed that a lot of URL's on the site are broken, throwing the following error:
```An unexpected error has occurred.```

Here are a few fixes.

# Why

Because some links did not work.

### CODE REVIEW

**Comment by brentvatne** [comment]
hello! can you update this in the `unversioned` directory as well? thanks!

**Comment by rauldeheer** [comment]
@brentvatne done: #3871

**Comment by brentvatne** [comment]
thanks

**Comment by nicknovitski** [comment]
Thank you @rauldeheer!  I fixed some more broken links similar to `/distribution/` in #3895 and also changed the test-server command so we can catch them in CI from now on.

**Pull request merged**
