### PR TITLE
Added Segment alias methods

### PR DESCRIPTION
**Pull request by ctgardner**

### CODE REVIEW

**Comment by terribleben** [comment]
Hey there, it looks like this doesn't build on iOS. We appreciate the contribution, but can you be sure and make sure your code runs before opening a PR? :)

**Comment by abi** [comment]
Bump @ctgardner

**Comment by ctgardner** [comment]
@terribleben Thanks for the feedback. I think your request is very reasonable, however I don't know how to run this locally. Could you point me in the right direction?

**Comment by ide** [comment]
@ctgardner There are setup instructions in the readme (https://github.com/expo/expo#set-up), they might be outdated in a few places though.

**Comment by peterpme** [comment]
@ctgardner :wave: were you able to get anywhere with this? Would love to help push this along because we'd like to use `alias` as well. Thanks!

**Comment by ctgardner** [comment]
@peterpme Thanks for reaching out to me. Unfortunately, I was unable to get `expo` running locally.

**Comment by raphaelrk** [comment]
Created a canny feature request for this:
https://expo.canny.io/feature-requests/p/missing-segmentalias

**Comment by tcdavis** [comment]
Closing since this has gotten pretty stale.  We'd love to see another PR though :)

**Comment by pwfcurry** [comment]
Added by this PR: https://github.com/expo/expo/pull/2440

**Pull request closed without merging**
