### PR TITLE
[github] always use `ubuntu-20.04` in workflows

### PR DESCRIPTION
**Pull request by Simek**
# Why

Currently, some of the workflow use `ubuntu-latest` as running environment, but there are also several using specific version `ubuntu-18.04`. AFAIK there should not be a reason to not use `latest` everywhere.

# How

This PR updates all Ubuntu workflows to use `ubuntu-latest` as running environment.

# Test Plan

Run the CI.

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] This diff will work correctly for `expo build` (eg: updated `@expo/xdl`).
- [ ] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Review by tsapeta — COMMENTED** [review]
I think there was no discussion about that yet, so it's good you bring this up.
My opinion is not to use `-latest` — mostly because the software installed on these runners can change over time without our knowledge and break some of our workflows. Fortunately, that never happened yet, but just wanted to note my concerns.

cc @ide to decide on this 😄

**Comment by Simek** [comment]
Thanks for the opinion! I think that you concerns may be valid, but since GitHub themselves added this alias and it's used in many guides and examples, we can assume there that even when something brakes for the `latest` it would be fixed quickly or reverted.

Also we can also switch to specific version which is used as `latest` now, which is `20.04`:
* https://github.com/actions/virtual-environments#available-environments

**Comment by tsapeta** [comment]
It doesn't have to be broken globally to affect us. When they switch the latest tag, it may result in a new version of Yarn/Node/Homebrew/Clang/Gradle/Python/whatever being used in our workflows which could lead to issues. There is a reason why we use lockfiles elsewhere, lock to a specific version of Xcode etc.

**Comment by Simek** [comment]
Just to precise something, specific virtual evn versions are updated weekly, and every week something can brake due to those changes.

> We typically deploy weekly updates to the software on the virtual environments. 

History of `20.04` env changes:
* https://github.com/actions/virtual-environments/commits/releases/ubuntu20/20220410/images/linux/Ubuntu2004-Readme.md

**Review by ide — CHANGES_REQUESTED** [review]
For workflows that test our code, we want to keep the builder environment stable and use pinned versions, similar to how we pin the versions of Xcode, the Android SDK, and Node.

For workflows that perform tasks like commenting on a PR, it's probably fine to use ubuntu-latest.

**Comment by Simek** [comment]
I have decided to use `20.04` in all workflows, just for thew consistency. Usually when new workflows are created, people tend to copy part of actions from the old ones, which in time, could lead to using `latest` in the wrong type of workflow. Hope this is fine approach.

**Review by tsapeta — APPROVED** [review]
Just remember to change PR's and commit's title 🙃

**Review by ide — APPROVED** [review]

**Comment by Simek** [comment]
> Just remember to change PR's and commit's title 🙃

FYI, GitHub automatically changes default commit message if you have edited the PR title:

Screenshot 2022-04-15 084231

**Pull request merged**
