### PR TITLE
[go][iOS][Android] Upgrade `react-native-webview` from `11.18.1` to `11.22.4`

### PR DESCRIPTION
**Pull request by lukmccall**
# Why

Closes ENG-5509

# How

Run
```
et uvm --module "react-native-webview" --commit "v11.22.4" --target "expo-go"
```

# Test Plan

- iOS:
   - NCL ✅
Screenshot 2022-06-30 at 14 21 14
- Android 
  - NCL ✅
 
image

### CODE REVIEW

**Review by bbarthec — APPROVED** [review]
Another point for you 👍 😁

**Comment by fobos531** [comment]
Hey @lukmccall, great work on this PR!

However, I have discovered a couple of issues in `react-native-webview`'s own repo which pertain to using `injectJavaScript` on Android. The issues in question are https://github.com/react-native-webview/react-native-webview/issues/2569 and https://github.com/react-native-webview/react-native-webview/issues/2557

Since this PR bumps the dependency version to `11.22.x`, which has been reported, to suffer from this issue, it may be a good idea to verify that this specific use case does indeed work here on Android. If this has already been done/handled, kindly disregard my comment.

**Comment by lukmccall** [comment]
@fobos531, I tested this module using code like this: 
``` js
// ...
const injectedJavaScript = `window.ReactNativeWebView.postMessage(JSON.stringify(window.location));`;
// ... 
function WebViewRemoteSource() {
  const [isLoading, setLoading] = React.useState(true);

  return (
    <View style={styles.container}>
      <H2 style={styles.header}>Remote Source</H2>
      <WebView
        // ...
        injectedJavaScript={injectedJavaScript}
      />
      {isLoading && <ActivityIndicator style={StyleSheet.absoluteFill} />}
    </View>
  );
}
// ...
```
and the js code was injected and I got a message:
```
Got a message from WebView:  Object {
  "ancestorOrigins": Object {},
  "hash": "",
  "host": "expo.dev",
  "hostname": "expo.dev",
  "href": "https://expo.dev/",
  "origin": "https://expo.dev",
  "pathname": "/",
  "port": "",
  "protocol": "https:",
  "search": "",
}
```

I'm not sure if that's enough. However, everything seems to be fine.

**Comment by fobos531** [comment]
Would you mind trying to inject JavaScript via the method exposed on the ref instead of the prop on the component itself? I'd test it myself, but I'm currently unable to due to other work I have to attend to.

**Comment by lukmccall** [comment]
Yes, of course. 

Test:
```js
function WebViewRemoteSource() {
  const [isLoading, setLoading] = React.useState(true);
  const ref = React.useRef();
  return (
    <View style={styles.container}>
      <H2 style={styles.header}>Remote Source</H2>
      <WebView
        source={{ uri: 'https://expo.dev/' }}
        onLoadEnd={() => {
          setLoading(false);
          ref.current.injectJavaScript(injectedJavaScript);
        }}
        onMessage={({ nativeEvent: { data } }: MessageEvent) => {
          console.log('Got a message from WebView: ', JSON.parse(data));
        }}
        ref={ref}
      />
      {isLoading && <ActivityIndicator style={StyleSheet.absoluteFill} />}
    </View>
  );
}
```
Result: still getting a message ✅

**Pull request merged**
