### PR TITLE
[expo-image] Add expo-image test app to NCL

### PR DESCRIPTION
**Pull request by IjzerenHein**
# Why

Initial test app/framework for `expo-image` for testing and develop expo-image features (within bare, web & Expo client). The app allows for testing properties, styles, native & JS animatable properties, and events. At the same time this is useful for showcase purposes and QA.

# How

Add `Image` category to `Components` tab to NCL.

# Test Plan

App currently uses the `<Image>` component from react-native. Once the `expo-image` package is added, NCL should be updated to point to `expo-image`.

image

### CODE REVIEW

**Review by sjchmiela — COMMENTED** [review]
Great work! This should let us thoroughly test the Image component before announcing it as stable and ready.

However, I'm afraid that nesting tests inside different screens will make it too tedious to test all the features at once. Would it be possible to change it to something more like a long scroll view which you can scroll through and quickly notice any differences between what is being rendered and what should be rendered? 🤔 Maybe you have some other solution to this problem?

**Comment by IjzerenHein** [comment]
Yep agree on that completely. We also need a long list which displays the tests so you spot errors quickly. I will add that 👍

**Comment by IjzerenHein** [comment]
NCL now displays a visual list of all tests, see screenshot at the top.
You can press on the test to see the detail screen, and you can press on the right-top icon to enter the category list view.

The expo-image is displayed along side a regular `<Image>`. This way we can test for feature parity with regular Image for now, and the in the future we can possibly replace this with pre-renderings, if that makes more sense.

**Review by sjchmiela — APPROVED** [review]
This looks like a great way to test feature parity with `Image`! We still will need to figure out a way to measure performance, but this is a great great start! 🎖

**Comment by IjzerenHein** [comment]
> This looks like a great way to test feature parity with Image! We still will need to figure out a way to measure performance, but this is a great great start!

Yep agree, this does not yet measure performance. Potentially we can use the "event" panel to monitor loading times, but I'm not sure how useful and accurate that will be.

**Pull request merged**
