### PR TITLE
[expo-asset] handle nullable file and fileInfo

### PR DESCRIPTION
**Pull request by hyochan**
# Why

After upgrading `expo-asset` to `8.9.0` with expo SDK 48, the test breaks because return value from the expo `FileSystem` could be nullable. This will apparently fail in test environment.

```
 FAIL  test/components/pages/Temp.test.tsx
  ● [Temp] render › renders without crashing

    TypeError: Cannot read properties of undefined (reading 'md5')

      at node_modules/expo-asset/src/PlatformUtils.ts:67:10
      at asyncGeneratorStep (node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
      at _next (node_modules/@babel/runtime/helpers/asyncToGenerator.js:22:9)
```

# How

Handle `fileInfo` and `file` with [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining).

# Test Plan

```
git clone https://github.com/dooboolab/dooboo-expo.git
git checkout release/48
```
> You can see the [PR](https://github.com/dooboolab/dooboo-expo/pull/48) is failing shortly.

After the current [PR] patch, the test will pass.

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [x] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Comment by hyochan** [comment]
I am not sure where to put the changelog. Should I create `## 8.10.0 - 2023-02-26`?

The description could be below.
```
- Fix nullable file and fileInfo ([#20258](https://github.com/expo/expo/pull/21410) by [@hyochan](https://github.com/hyochan))
```

**Review by wschurman — APPROVED** [review]

**Comment by wschurman** [comment]
@hyochan - for the changelog you should put your change in the unpublished section. You should be able to find examples of this in other changelogs in the repo.

Also, can you please run `et cp expo-asset` to generate the built files (so that the CI step passes)?

**Comment by hyochan** [comment]
> @hyochan - for the changelog you should put your change in the unpublished section. You should be able to find examples of this in other changelogs in the repo.
> 
> Also, can you please run `et cp expo-asset` to generate the built files (so that the CI step passes)?

@wschurman I've updated the changelog and generated the build file for `expo-asset`. I am not sure what you mean by `et cp expo-asset` command though 🤔 Could you kindly explain what it means?

**Comment by hyochan** [comment]
@wschurman @tsapeta Hi there. Is there any chance for this `PR` to be merged?
We are still waiting to upgrade expo SDK 48 in our project.

https://github.com/dooboolab/dooboo-ui/actions/runs/4459777286/jobs/7832466333?pr=248

**Review by wschurman — CHANGES_REQUESTED** [review]
Looking at this again, I don't think `FileSystem.getInfoAsync` should ever return null/undefined. Maybe there's an issue in the test setup/mocking/etc?

**Comment by wschurman** [comment]
Can you paste the contents of `test/components/pages/Temp.test.tsx` with a minimum reproducible example? I'm not able to locate the failure in the CI run you linked to.

**Comment by hyochan** [comment]
> Can you paste the contents of `test/components/pages/Temp.test.tsx` with a minimum reproducible example? I'm not able to locate the failure in the CI run you linked to.

Sure here it is https://github.com/dooboolab/dooboo-expo/blob/main/test/components/pages/Temp.test.tsx

**Comment by hyochan** [comment]
> Looking at this again, I don't think `FileSystem.getInfoAsync` should ever return null/undefined. Maybe there's an issue in the test setup/mocking/etc?

Why should we mock the function that we are not using locally? If this is technical debt, I think we need sample mocking code for users to copy and paste.

**Comment by wschurman** [comment]
> Why should we mock the function that we are not using locally?

I'm not able to follow the code in that repo too closely since I'm not familiar with it, but it seems that if an `expo-asset` method is being called, in this case `downloadAsync`, then it is being used locally. As a general principle, I tend to mock out dependencies that are not intended to be tested, so in this case my hypothesis for a solution would be to mock out expo-asset.

> If this is indeed a technical debt issue, perhaps providing sample mocking code for users to reference would be beneficial. This way, should there be any changes to expo's internal functions in the future, users will be better prepared to adapt. It would be great if this information could be clearly communicated to ensure users are aware of potential changes.

I'm not aware of any major changes to this code. The only commit that changed anything here was https://github.com/expo/expo/commit/6552d688ec5770ae6e472264532f6f868eb9c82d so maybe that made it incompatible with some sort of existing mock. I would just mock the whole module with `jest.mock('expo-asset')` (if using jest). cc @Simek

**Comment by hyochan** [comment]
> Member

I've just mocked out every thing in `expo-font` and not `expo-asset`. Thanks for your suggestion!

What I meant by `using locally` was that I am not using `loadSingleFontAsync` function anywhere in my code and this causes the test to fail. I think this is used inside `useFonts`.

Now the CI passed https://github.com/dooboolab/dooboo-expo/actions/runs/4464770230/jobs/7841215854.

You may close the PR if you still think there is nothing to be changed here.

@wschurman Thank you.

**Comment by tsapeta** [comment]
> You may close the PR if you still think there is nothing to be changed here

Yeah, the current code seems to be correct from the implementation side. We'll take a look at our generated mocks, but I believe our checks would fail as well if the mocks are broken 🤔

**Pull request closed without merging**
