### PR TITLE
[fingerprint] Show more information in fingerprint diff

### PR DESCRIPTION
**Pull request by wschurman**
# Why

The idea behind this PR is that a diff should show the before and after when the diff item is "changed". That way, a viewer of the diff can see the contents before and contents after in the debug and diff the contents themselves.

This is especially helpful for expoConfig source and other JSON file sources where the contents can be diffed in plain text.

# How

Update code to change output format of diff.

# Test Plan

Run test.

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Comment by wschurman** [comment]
* **#32487** <a href="https://app.graphite.dev/github/pr/expo/expo/32487?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#32486** <a href="https://app.graphite.dev/github/pr/expo/expo/32486?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @wschurman and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by Kudo — CHANGES_REQUESTED** [review]
looks good for the code changes. please help to resolve test error and i think we should also update the code in eas-build: https://github.com/expo/eas-build/blob/68a4cacd4743c1041603aca3bbfc5911db573cef/packages/build-tools/src/utils/fingerprint.ts#L93

should we take care backward compatibility? e.g. newer eas-build with sdk 51 older fingerprint?

**Comment by wschurman** [comment]
> i think we should also update the code in eas-build: https://github.com/expo/eas-build/blob/68a4cacd4743c1041603aca3bbfc5911db573cef/packages/build-tools/src/utils/fingerprint.ts#L93

I'm planning to make eas-build call into the versioned fingerprint CLI to diff (so we can test diff changes in PRs that run EAS builds), but until then yep, I can update the code there.

> should we take care backward compatibility? e.g. newer eas-build with sdk 51 older fingerprint?

This only changes the diff result, not the fingerprint output. So backwards compatibility is unaffected. That being said, being able to diff fingerprints from different fingerprint versions is a good thing to think about, but outside the scope of this PR.

**Review by kadikraman — APPROVED** [review]

**Comment by Kudo** [comment]
> This only changes the diff result, not the fingerprint output. So backwards compatibility is unaffected. That being said, being able to diff fingerprints from different fingerprint versions is a good thing to think about, but outside the scope of this PR.

the backwards compatibility problem i mentioned is after you update eas-build, it could break original diff parser for sdk 51 projects. but you've answered the question for me regarding the "make eas-build call into the versioned fingerprint CLI"

**Review by Kudo — APPROVED** [review]

**Comment by wschurman** [comment]
> it could break original diff parser for sdk 51 projects

Don't think we have a diff parser anywhere. Just simple JSON.stringify/JSON.parse on the output.

**Comment by wschurman** [comment]
### Merge activity

* **Oct 31, 3:13 PM EDT**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/expo/expo/32486).

**Comment by Kudo** [comment]
> Don't think we have a diff parser anywhere. Just simple JSON.stringify/JSON.parse on the output.

you are right, thanks for checking that. https://github.com/expo/eas-build/blob/68a4cacd4743c1041603aca3bbfc5911db573cef/packages/build-tools/src/utils/fingerprint.ts#L164-L180

**Pull request merged**
