### PR TITLE
[fingerprint] Remove runtimeVersion from ignore normalization of expo config when policy

### PR DESCRIPTION
**Pull request by wschurman**
# Why

As of https://github.com/expo/expo/pull/26901, the `fingerprintExperimental` runtimeVersion policy produces a consistent result that doesn't change in-between fingerprint runs (It produces `file:fingerprint`).

But the main reason this is important is because I think a runtime with a fingerprint A that has a runtimeVersion policy A != runtime with fingerprint B that has a runtimeVersion policy B. I may be incorrect though and it might be okay to normalize out runtimeVersion since it'll still produce a consistent fingerprint without it. I think the case we have to think about is if someone changes their policy.

This PR fixes a bug for platform-specific runtime versions and applies the same removal to `ios.runtimeVersion` and `android.runtimeVersion` and `web.runtimeVersion`.

Closes ENG-11461.

# How

Remove runtimeVersion normalization when a policy.

# Test Plan

Run tests.

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Comment by Kudo** [comment]
thanks for taking care of this. originally the normalization is that for people using fingerprint hash as the custom runtimeVersion. not sure whether that is still useful nowadays? alternatively, we can strip out runtimeVersion only when `typeof(runtimeVersion) === 'string'`. if people changing runtime version policy, that's considered as a fingerprint change.

**Comment by wschurman** [comment]
ping

**Comment by Kudo** [comment]
> thanks for taking care of this. originally the normalization is that for people using fingerprint hash as the custom runtimeVersion. not sure whether that is still useful nowadays? alternatively, we can strip out runtimeVersion only when typeof(runtimeVersion) === 'string'. if people changing runtime version policy, that's considered as a fingerprint change.

wdyt for the previous comment?

**Comment by wschurman** [comment]
> > thanks for taking care of this. originally the normalization is that for people using fingerprint hash as the custom runtimeVersion. not sure whether that is still useful nowadays? alternatively, we can strip out runtimeVersion only when typeof(runtimeVersion) === 'string'. if people changing runtime version policy, that's considered as a fingerprint change.
> 
> wdyt for the previous comment?

Yep, this PR was updated to only strip it out if string (see updated summary as well).

**Comment by wschurman** [comment]
I think in general we'll probably want to direct people towards using the policy once it's ready since it's too easy to get it wrong when done manually.

**Comment by Kudo** [comment]
sorry i missed that the pr was updated already.

> I think in general we'll probably want to direct people towards using the policy once it's ready since it's too easy to get it wrong when done manually.

agree that, just in case people are using runtimeVersion for other purposes. let see how it goes first.

**Review by Kudo — APPROVED** [review]

**Pull request merged**
