### PR TITLE
[docs] fix copy paste issue in expo-location

### PR DESCRIPTION
**Pull request by forki**
# Why

fix copy paste issue in docs

### CODE REVIEW

**Review by Simek — COMMENTED** [review]
Nice catch, thank you for the correction! 👍 

Can you also update versioned files for Location package?
* https://github.com/expo/expo/tree/main/docs/pages/versions

**Comment by forki** [comment]
@Simek  looks like this is rather new error - did not find it in older docs

**Comment by Simek** [comment]
The typo is also present in SDK 48 docs:
* https://github.com/expo/expo/blame/main/docs/pages/versions/v48.0.0/sdk/location.mdx#L28

**Comment by forki** [comment]
done

**Review by Simek — APPROVED** [review]
Thank you for the update, LGTM! 🚀

**Pull request merged**
