### PR TITLE
[docs] Remove tippy

### PR DESCRIPTION
**Pull request by nicknovitski**
# Why

[Tippy](https://atomiks.github.io/tippyjs/) is a tooltip/popover library.  We have code that intends to change `span`s with the classes `token comment` to have the class `code-annotation`, and have tippy handle that class.  In other words, anything in a code block which prism considers a comment, tippy would somehow turn into a popup.

This currently doesn't work and I'd rather not anyone try to make it work.

### CODE REVIEW

**Comment by brentvatne** [comment]
screen shot 2019-01-23 at 9 36 02 am

seems to work in production?

**Comment by brentvatne** [comment]
I don't think we should remove this, it works and I think it's useful to have. See https://github.com/expo/expo/blob/master/docs/versions/unversioned/sdk/auth-session.md for an example of how to take advantage of it - it doesn't just apply to every comment, you need to add `@info` to the start of the comment for it to be marked as a tooltip

**Comment by nicknovitski** [comment]
Oh!  Thanks, I was totally wrong.

**Comment by nicknovitski** [comment]
I'd prefer us to use [the official react component](https://github.com/atomiks/tippy.js-react) to make things more obvious, but I think that is not currently practical with our approach to "compiling" markdown to js.  Just noting that down for the future.

**Pull request closed without merging**
