### PR TITLE
[expo-av] Allow audio playback/recording when the app is in background

### PR DESCRIPTION
**Pull request by sjchmiela**
# Why

Closes https://github.com/expo/expo/pull/3304. Also, somehow moves https://expo.canny.io/feature-requests/p/audio-playback-in-background forward (however, I would consider this canny request a bit broader than just allowing this functionality).

# How

Following suggestion found in https://github.com/expo/expo/pull/3304 by @redpandatronicsuk I implemented a way to disable pausing of all AV objects when the app goes into background.

# Test Plan

Tested on NCL. With `audio` background mode enabled and `setAudioMode` called with `staysActiveInBackgroundIOS` playback and recordings continue in background.

### CODE REVIEW

**Comment by brettdh** [comment]
This is real exciting to see. Do I understand correctly that the reason that this is iOS-specific is that there's nothing special required on Android to get bg audio working (besides perhaps general backgrounding configuration as released in SDK 32)? Or is there further implementation required to make this work on Android?

It would be great to see a minimal example that works on iOS and Android

Thanks! Looking forward to using this.

**Comment by RapsIn4** [comment]
Excited to see progress on this! Would be great to see both iOS and Android support!

**Comment by redpandatronicsuk** [comment]
I think for Android a similar approach can be used. Not sure, but I think the code we want to prevent from being executed when we want to keep audio running when going to background mode is around here: https://github.com/expo/expo/blob/c5a18838f760ccb06b4c4c799bcb85d5b9ce005c/android/versioned-abis/expoview-abi30_0_0/src/main/java/abi30_0_0/host/exp/exponent/modules/api/av/AVModule.java#L155

**Comment by sjchmiela** [comment]
Thanks, will see!

**Review by tsapeta — APPROVED** [review]
👌

**Comment by samkuhn** [comment]
This is great thanks guys. We've been waiting to launch our app but have been unable due to a firm requirement of background audio and have been reluctant to detach from Expo. Hoping there's an easy android patch as well 🤞

**Comment by ladigitale** [comment]
We are 🤞 for Android support.

**Comment by yutin1987** [comment]
https://github.com/expo/expo/blob/31ac0c3c3b10aaca8190382070361b5619014ebe/packages/expo-av/ios/EXAV/EXAV.m#L267-L269
```
if (_isBackgrounded) { 
   return UMErrorWithMessage(@"This experience is currently in the background, so the audio session could not be activated."); 
 } 
```
Need to delete it, because `new Audio.Sound()` and play in background will show error `[Error: Play encountered an error: audio session not activated.]`

**Comment by turbozv** [comment]
Any update on this PR?

**Comment by turbozv** [comment]
Nice! It's merged, thanks guys!

**Comment by wilbyang** [comment]
It's awesome work! How could we use this feature.

**Comment by aviggiano** [comment]
Looking forward to it! Is there a way to use this while still in beta, or not publicly released?

**Comment by sjchmiela** [comment]
There's no easy way right now, we would have to publish an update to `expo-av` package and you would have to be either ejected or on bare project to be able to pull the changes.

**Comment by jennya** [comment]
Would love to see an updated expo-av package!

**Comment by sjchmiela** [comment]
Published `expo-av@4.1.0` with this PR included. If trying it out, don't forget to also add proper `UIBackgroudMode` to the application configuration! 🙂

**Comment by eltoob** [comment]
@sjchmiela do you know if that will make the speech api work in the background?
Also what's the best way to get it to work in my detached expo app?

**Comment by james-berry** [comment]
any updates on when this gets released? or how to use it?

**Comment by ide** [comment]
There are two main ways to use the code in this repo:

- *Managed workflow:* Wait for the next SDK release. For updates on the SDK releases, follow https://blog.expo.io.
- *Bare workflow:* When a unimodule is published on npm, you can try installing it.

**Comment by james-berry** [comment]
just confirming, this PR means that there is background audio for IOS in SDK 33, but not on Android? 😕

**Comment by brettdh** [comment]
@james-berry I think it's supported on iOS and Android, largely based on [the relevant documentation](https://github.com/expo/expo/blob/master/docs/pages/versions/unversioned/sdk/audio.md#audiosetaudiomodeasyncmode) (that is, the lack of any mention of "unsupported on Android", and the mention of a minor iOS-specific requirement).

**Pull request merged**
