### PR TITLE
[iOS][Android] Update `react-native-svg` to `13.4.0`

### PR DESCRIPTION
**Pull request by lukmccall**
# Why

Closes ENG-6532.

# How

Run:
```
 et uvm -m react-native-svg
```

> Note:
This version of SVG requires a new version of the home app. It will be created later because I faced other problems with the home app - see https://github.com/expo/expo/pull/19495

# Test Plan

- home - android, ios ✅
- NCL - android, ios ✅

### CODE REVIEW

**Comment by Simek** [comment]
Superseed https://github.com/expo/expo/pull/19080

**Comment by Simek** [comment]
Do we still need the patch file for `children` in types?
* https://github.com/expo/expo/pull/19434/files#diff-9e24fd95549c8c1cc6355538037b7526a33b3d414562ef7fe4d69486becf71eb

**Comment by lukmccall** [comment]
> Do we still need the patch file for `children` in types?
> 
> * [`2c8b770`/patches/react-native-svg%2B13.3.0.patch](https://github.com/expo/expo/blob/2c8b770808bb2a3016c0b989f9218f6fda21ba64/patches/react-native-svg%2B13.3.0.patch)

It seems to be needed :shrug:

**Review by tsapeta — APPROVED** [review]

**Comment by zakharchenkoAndrii** [comment]
Is that possible to bump version of  `react-native-svg` to `13.6.0`? 

Asking because we have a crash on android on 13.4 version:
`Invariant Violation: requireNativeComponent: "RNSVGSvgViewAndroid" was not found in the UIManager]`

When 13.4 installed bare RN crashes with this error, bumping to 13.6 fixes native crash but when I launch it in Expo go we have this issue... I suspect (hope) that it will resolve the issue.

cc/ @lukmccall

**Pull request merged**
