### PR TITLE
[expo] Remove dependency on react-native-safe-area-context

### PR DESCRIPTION
**Pull request by brentvatne**
# Why

We depend on react-native-safe-area-context in the DevLoadingView in the expo package, and this view is used on iOS in Expo Go. As we start to recommend installing the expo package more broadly, we need to be even more careful than before about its dependencies. It's important to remove react-native-safe-area-context because if you end up with multiple versions of libraries with view managers, React Native will not be very happy about that (it will crash in production / show red screen in development). The expo package shouldn't dictate the version of react-native-safe-area-context in everyone's projects (although it does in managed projects).

# How

Use the `initialWindowMetrics` from the react-native-safe-area-context native module directly instead of depending on the JS package. This API will give us the insets for the device on iOS 11+. This allows us to remove the react-native-safe-area-context dependency because we always install the native module in Expo Go.

# Test Plan

I tested this in Expo Go with an iPhone 12 mini to ensure that we are getting the insets as expected. I also tested on iPhone 8 to ensure that we don't add any unnecessary padding. As you can see below, it works as expected.

Screen Shot 2021-09-17 at 2 16 00 PM

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.io and README.md).
- [x] This diff will work correctly for `expo build` (eg: updated `@expo/xdl`).
- [x] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

# Humour

GitHub Copilot called me out on this one

Screen Shot 2021-09-17 at 1 31 24 PM

### CODE REVIEW

**Review by ide — APPROVED** [review]
Is the necessary native code very big? If not, it might be best to inline it inside of the dev client (sort of like vendoring but not the whole module if it's just a few methods).

**Review by EvanBacon — APPROVED** [review]
lgtm

**Comment by ide** [comment]
A thought came to mind - it would be helpful for the comments in this PR to also say what code they need to be kept in sync with. Brent's commit 7faa5983b15f8c5f68cf52d31e85e62714b6355e from over a year ago was the last to make changes to the vendored SafeArea code, will let him decide how best to raise awareness that the code in this PR needs to be compatible with the vendored native code.

**Comment by brentvatne** [comment]
> Is the necessary native code very big? If not, it might be best to inline it inside of the dev client (sort of like vendoring but not the whole module if it's just a few methods).

pretty small https://github.com/th3rdwave/react-native-safe-area-context/blob/e04ac163a5752aeab5c3e1669b6e8845c462b078/ios/SafeAreaView/RNCSafeAreaProviderManager.m#L21-L59

**Comment by ide** [comment]
Nice. If the time comes that maintaining this becomes too tricky, we could easily export this as part of the Kernel module (or make another kernel-only module).

**Pull request merged**
