### PR TITLE
[constants] Add deprecation messages for deprecated Constants fields

### PR DESCRIPTION
**Pull request by ide**
We deprecated Constants.installationId but didn't make this very visible outside of the changelog. Push back the removal target date by one SDK cycle and add console warnings, TypeScript deprecation messages, and backported warnings to the SDK 40 docs.

Tested by running the docs locally and going to http://localhost:3002/versions/v40.0.0/sdk/constants/ to see the changes.

### CODE REVIEW

**Review by brentvatne — APPROVED** [review]

**Comment by brentvatne** [comment]
needs changelog but otherwise looks good. made task to remove these in sdk 44 project https://linear.app/expo/issue/ENG-301/remove-constantsinstallationid-and-constantslinkingurl

**Comment by yvbeek** [comment]
Is it possible to disable these deprecation warnings?

In our project we aren't using Expo-Constants directly but it is a dependency of `react-native-unimodules`.
It looks like `react-native-unimodules` is using the deprecated properties.

**Comment by leethree** [comment]
Looks like these warnings are not implemented correctly. `deviceId` `linkingUrl` and `installationId` are meant to be lazy. But actually they are evaluated on construction. So the warnings will be triggered even if deprecated properties are not used.

**Comment by ide** [comment]
Could you please send a PR showing what you mean?

**Comment by leethree** [comment]
I'm not familiar with expo-constants enough to fix it. But the problem here is essentially this:

```js
{
  ...nativeConstants,
  get installationId() {
    if (...) console.warn(...);
    return nativeConstants.installationId;
  },
}
```

will be transpiled by babel to:

```ts
Object.assign({}, nativeConstants, {
   get installationId() {
    if (...) console.warn(...);
    return nativeConstants.installationId;
  }
})
```

And the getter will be called when object is assigned. So the warning will be triggered no matter what.

Hope this is clear enough.

**Comment by ide** [comment]
I suspect the issue is with the Babel configuration. JS's object spread doesn't cause getters to be invoked. Looking at metro-react-native-babel-transformer@0.59.0, the version used in this repo, the object spread plugin is configured with:

```js
const objectRestSpread = [require("@babel/plugin-proposal-object-rest-spread")];
```

Notice how there are no plugin options. Namely, `{ loose: true }` is not provided. The [compiled code](https://babeljs.io/repl/#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=MYewdgzgLgBFCm0YF4YG8BQMYDo9oF8AaLGAc3lgBsBDALwE8AFAJxAAd4WoGAKASnQxQkEFXg4qIMrwDktRuUoIWMAJZgAbiADW8ACaz-AbhgEMBYxgwiIYiVJmyQAIwBW8YLGAt4NBIYmGAjQkvTMbJzcDFa29pLScvBg-jAgAGZwiFBGxkA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=&prettier=false&targets=&version=7.14.8&externalPlugins=%40babel%2Fplugin-proposal-object-rest-spread%407.14.7) doesn't eagerly invoke getters.

However, the docs for the spread plugin mention that the plugin's [`loose`](https://babeljs.io/docs/en/babel-plugin-proposal-object-rest-spread#loose) option and the Babel config's [`setSpreadProperties`](https://babeljs.io/docs/en/assumptions#setspreadproperties) option use `_extends` (basically `Object.assign`).

Since the code here runs correctly in a JS-compliant environment and the issue lies in postprocessor, I don't think we'll change this code. If the Babel configuration is something in this repo, we can change that.

**Comment by leethree** [comment]
I see. We are using React Native 0.64, which explicitly enabled `{ loose: true }` for some reason:

https://github.com/facebook/metro/blob/457073fdad0180ff346eb3729e3058186b0eb3fb/packages/metro-react-native-babel-preset/src/configs/main.js#L105-L107

It's added since this commit
https://github.com/facebook/metro/commit/c88f8b99e086b5004a0ddc02276b484cd0119e7e

**Comment by ide** [comment]
I see. When this repo updates the metro plugin, we'll figure out what to do with it.

**Comment by ide** [comment]
@leethree - in https://github.com/expo/expo/pull/13984 we're updating `babel-preset-expo` (which you can use in place of `metro-react-native-babel-preset`) to override `metro-react-native-babel-preset`'s object rest spread plugin.

`babel-preset-expo` makes getters/setters in spread objects behave according to the JavaScript spec once again. This fixes the issue we discussed above and makes any other JS code like your own application code or npm packages that depend on the JS spec work correctly.

**Review by SaintPatricksCoin — APPROVED** [review]

**Review by SaintPatricksCoin — APPROVED** [review]

**Comment by leethree** [comment]
@ide sounds reasonable to me. will check out. thanks!

**Pull request merged**
