### PR TITLE
[eslint-config] remove `arrowParens` overwrite, reformat files

### PR DESCRIPTION
**Pull request by Simek**
# Why

Refs #13858

The `arrowParens` config overwrite has been introduced temporarily to make the ESLint bump changeset a bit smaller. The removal has been scheduled after the merge, so it time to tackle this change.

# How

This PR removes the `arrowParens` overwrite from `shared/prettier.js` and includes the reformat needed for the files in the Expo workspace.

# Test Plan

I have performed almost all lints and checks locally like `et check-packages`, I have also build NCL, but with this amount of changes there is a the possibility that I have missed something, so I would rely on CI for the final tweaks.

# Checklist

- [X] Documentation is up to date to reflect these changes (eg: https://docs.expo.io and README.md).
- [X] This diff will work correctly for `expo build` (eg: updated `@expo/xdl`).
- [X] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Comment by Simek** [comment]
It looks like CI failures are not related to this PR, so lets switch it to ready for review.

P.S. I have tried to not notify the whole team, but I have failed.😄

**Comment by barthap** [comment]
That's sad, I appreciated the possibility of skipping parenthesis on lambda args 😞

**Comment by Simek** [comment]
> That's sad, I appreciated the possibility of skipping parenthesis on lambda args 😞

For the context, the change has been requested by @ide in there: https://github.com/expo/expo/pull/13858#discussion_r682332595

**Review by ide — APPROVED** [review]
We use the parentheses in our other codebases and there are other places for us to better spend our attention. This makes our last major codebase consistent with the rest.

**Review by barthap — APPROVED** [review]
I understand the consistency reasons and I don't mind changes made in this PR. I just personally don't like parentheses when unnecessary, that's all 😄

**Review by bbarthec — APPROVED** [review]

**Pull request merged**
