### PR TITLE
[docs] Fix Facebook init example in Firebase guide

### PR DESCRIPTION
**Pull request by IjzerenHein**
# Why

Facebook logIn example does not work

# How

Updated doc according to Facebook API docs.

# Test Plan

Tested in https://github.com/IjzerenHein/expo-firebase-demo app

### CODE REVIEW

**Comment by IjzerenHein** [comment]
@EvanBacon I've created a PR for this because I wanted to verify 2 things:
- Do I typically need to create a PR for such a doc change?
- Do I need to update the v36 SDK docs as well?
Thanks!

**Comment by brentvatne** [comment]
> Do I typically need to create a PR for such a doc change?

not really needed

> Do I need to update the v36 SDK docs as well?

yep! i'm going to look into https://github.com/danger/danger-js to see if we can automate this in the future.. but for now yep

**Comment by brentvatne** [comment]
@IjzerenHein - I forced pushed your branch because I rebased master so you can see the warning I added in #6890 :)

**Comment by IjzerenHein** [comment]
> @IjzerenHein - I forced pushed your branch because I rebased master so you can see the warning I added in #6890 :)

Nice, no idea that was even possible :)

**Comment by IjzerenHein** [comment]
Lol (*and hits himself in the head*), I went ahead merging without adding it to SDK 36. Fixing..

**Pull request merged**
