### PR TITLE
[ios] New ExpoAppDelegate independent of singleton modules

### PR DESCRIPTION
**Pull request by tsapeta**
# Why

Currently `EXAppDelegateWrapper` is connected with singleton modules from the old expo modules architecture. In other words, it works only in expo modules, using it in standard RN library would add a lot of burden. We'd like to give the developers the ability to use AppDelegate subscribers in standard RN libs.

Moreover, in Sweet API there will be no singleton modules, so this seems to be a good partial replacement for them and another step forward to the new architecture and migrating code to Swift.

# How

- Created new `ExpoAppDelegate` (in Swift) and implemented some `UIApplicationDelegate` methods that we've used so far. I'll add more later.
- Renamed existing `EXAppDelegateWrapper` to `EXLegacyAppDelegateWrapper`. Legacy wrapper becomes a subscriber of the new app delegate to keep backwards compatibility for singleton modules.
- `EXAppDelegateWrapper` now provides backwards compatibility for existing projects and app delegates written in Objective-C.
- Updated autolinking to include `getAppDelegateSubscribers()` method in `ExpoModulesProvider` which returns an array of subscriber classes.
- New config field in `expo-module.config.json` — `ios.appDelegateSubscribers`.
- Subscribers needs to be initialized and registered right after the binary is loaded and right before any other code is executed. That's what static `load` method is doing, but it's not being called in Swift, so I had to create a helper ObjC class for that (`EXAppDelegatesLoader`).
- Added `ScreenOrientationAppDelegate` as `ExpoAppDelegate` subscriber. It's been extracted from the singleton module.

# Test Plan

Ran test-suite tests:
- ScreenOrientation to test the new approach
- Notifications to test backwards compatibility (it has some singleton modules)
- Others are tested on the CI

### CODE REVIEW

**Review by lukmccall — APPROVED** [review]
Very impressive 🚀

Just one note. In the old system, we were able to control the order of the app delegate wrappers, weren't we? And for most of the functions, is not needed, but we may want to have that ability for `didFinishLaunchingWithOptions` in the future.

**Review by bbarthec — COMMENTED** [review]
I like the work you've done in this aspect very much 😊 👏 
I wonder about the name `subcontractors` though 🤔 As I can see in `AppDelegateSubcontractor.swift` file I wonder if `Subdelegate` is not sufficient enough? I mean, `AppDelegate` is very well established so I imagine we can take advantage of it and use `AppSubdelegate`. I know that you expose more than `UIApplicationDelegate` via this class (there's `UIResponder` as well), but does it even matter? What do you think?

**Review by EvanBacon — APPROVED** [review]

**Comment by Kudo** [comment]
> Yeah, singleton modules have the "priority" property by which the subcontractors are sorted. However, we didn't use it so far, so I'd say not to implement something that we don't need yet. It could make sense in Expo Go because we need to maintain how modules behave with others. For 3rd-party libs it doesn't make much sense to provide it, because they are not aware of the other libs the users have in the project. Imho we just need to be clear in the docs that we don't guarantee the order and all operations should be order-insensitive 😉

i did use it 😅
https://github.com/expo/expo/blob/537725585d2b58ce62141ee36576af7db33de5b6/packages/expo-updates/ios/EXUpdates/EXUpdatesAppDelegate.m#L35-L40

my thought is that we may in the future to define some in-house modules priority in e-m-c.

e.g.
```
#define MODULE_PRIORITY_EXPO_UPDATES 10
#define MODULE_PRIORITY_EXPO_DEV_LAUNCHER 20
```

especially to determine whom to create the bridge.

**Comment by tsapeta** [comment]
@Kudo, yeah but it seems to be the case only for modules living in our repo — I don't really want to let others (from outside the repo) to override the behavior. The delegate for expo-updates is still using the legacy way, so it's still before others.

**Comment by Kudo** [comment]
got it. so the question is now how i design the priority stuff for android wrapper and only internal for expo modules. will think about this and get back in my pr #14883 tomorrow.

**Pull request merged**
