### PR TITLE
[expo-updates][expo-asset] add ability to load unpublished embedded bundle/assets

### PR DESCRIPTION
**Pull request by esamelson**
# Why

PR 1/3 in the no publish workflow [2](https://github.com/expo/expo/pull/8006) [3](https://github.com/expo/expo/pull/8007)

Previously, installing expo-updates would overwrite the default RN build scripts for embedding the JS bundle and assets, in order to add our own publish-based scripts.

This PR adds the ability for expo-updates to run a bundle embedded in the app by the default RN build scripts, and changes the installation instructions to keep these scripts.

# How

The update is inserted into expo-updates' database with a special `EMBEDDED` status and none of the assets are copied into the document directory or inserted into the database (this will be added in a later commit).

Updates launched with the `EMBEDDED` status directly use the JS and assets embedded in the binary and do not override asset resolution with expo-asset. There is a new `isUsingLocalAssets` field exported on the module to let expo-asset determine whether or not to override asset resolution, since we now have a case where the module may be enabled but we want to use the assets embedded in the binary.

We add an extra script to the build steps to embed a minimal manifest with some data about the JS bundle and assets, including a UUID, commitTime, and information about the assets (to be used in a later PR). This lets us know with certainty whether or not a new binary (with an updated embedded bundle) has been installed, and sets us up to copy assets later on.

# Test Plan

All tests apply to both iOS and Android

- [x] release build launches successfully with an embedded update
- [x] release build shows embedded assets successfully and has `isUsingLocalAssets === false`
- [x] release build resolves embedded asset to correct scale (`@2x`)
- [x] running `expo publish` after the build allows a new update to be downloaded and launched successfully
- [x] making a new build after running `expo publish` uses the embedded update since its commitTime is newer

### CODE REVIEW

**Comment by ide** [comment]
For the uuid package: can't we just list it as a dependency?

**Comment by esamelson** [comment]
Oh yeah, I think you're right 🤔 I can't remember why I didn't do that in the first place! Will make that change now.

**Review by ide — APPROVED** [review]
Would it make sense to replace `isUsingLocalAssets` with `!isUsingEmbeddedAssets`? I think it is clearer to have "embedded asset mode" be triggered by a variable that has "embedded" in the name.

**Comment by esamelson** [comment]
Yeah, that makes a lot of sense, thanks for that suggestion. I've updated the names accordingly and inverted the logic, as well as adding the assertion, in https://github.com/expo/expo/pull/8003/commits/e75ac0a0b26a58c4516231d71429d8cd9c22f4fd.

**Pull request merged**
