### PR TITLE
Fix naming for ensure slash methods

### PR DESCRIPTION
**Pull request by phatmann**
Fixes the names of the `ensureLeadingSlash` and `ensureTrailingSlash` methods. They were backwards.

# Why

The methods were named incorrectly.

# How

Renamed the methods

# Test Plan

No test plan.

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.io and README.md).
- [ ] This diff will work correctly for `expo build` (eg: updated `@expo/xdl`).
- [ ] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Review by barthap — CHANGES_REQUESTED** [review]
Hello, this is a nice find! 👍  Thank you for this Pull Request.

As this is your first contribution, a few notes:
- When you make modifications to TypeScript code, make sure to run `yarn build` inside `packages/expo-linking` directory in order to rebuild the generated javascript. The CI will fail otherwise.
  You can [read more here](https://github.com/expo/expo/blob/master/CONTRIBUTING.md#%EF%B8%8F-editing-sdk-packages)
- A test plan is almost always a must-have when editing code behavior. Here it's just a method name swap, but they're both called somewhere - precisely inside [`createURL()`](https://github.com/expo/expo/blob/aa0b8988635b54dc78e576de57a6498b43e3ab81/packages/expo-linking/src/Linking.ts#L113-L130). We have to make sure it doesn't change behavior of that method.
- Fortunately, that method has [some unit tests written](https://github.com/expo/expo/blob/aa0b8988635b54dc78e576de57a6498b43e3ab81/packages/expo-linking/src/__tests__/Linking-test.ts) - you can check them by running `yarn test`, as described in ["Unit Tests"section of contribution guide](https://github.com/expo/expo/blob/master/CONTRIBUTING.md#-testing-your-changes). 
- As this isn't user-facing change (both methods are private) - you can ignore the _CI Bot's_ warning about changelog 😉

**Comment by phatmann** [comment]
Some tests are failing with my change. Looking into it.

**Comment by phatmann** [comment]
I swapped the method invocations and now the tests are passing again. So feel free to merge this.

Next step: see if the method calls make sense and file additional PRs as needed. But I don't want to pollute this PR.

**Comment by barthap** [comment]
Thanks for the update, could you rebase this branch or merge `upstream/master` into it, then rebuild the JS again? That would resolve the conflict and hopefully the failing CI check.

**Comment by phatmann** [comment]
I rebased my branch on to master, re-built the JS files, and force pushed the changes. All checks now pass!

Note: Github is showing a conflict in Linking.js.map. Not sure how to resolve that or if this is even a valid message.

**Comment by barthap** [comment]
I tried to resolve that conflict with `Linking.js.map` but it still has problems with CI check.
If you edit the PR and check "Allow edits from maintainers", I'll be able to rebuild and push the fix myself 😉

**Comment by phatmann** [comment]
Allíow edits was already on. I toggled it just in case.

**Comment by barthap** [comment]
I'm sorry, I could not push to this branch - it says I have no write access to this branch despite "Allow edits for maintainers" being checked.

I opened a new PR #14242, closing this one.

Thanks again for Your contribution! 😄 🎉

**Pull request closed without merging**
