### PR TITLE
Remove untested modules from bare-expo detox tests

### PR DESCRIPTION
**Pull request by EvanBacon**
# How

- Remove all untested modules from bare-expo (we can bisect later)

# Test Plan

CI should pass

### CODE REVIEW

**Comment by ide** [comment]
iOS Detox CI is passing without this -- we probably can leave master as-is.

**Comment by tsapeta** [comment]
I agree with James. We also don't want to remove `optionalRequire`s since they are used in `standalone-ncl`.

**Comment by EvanBacon** [comment]
1. We definitely want to remove optional requires for test-suite, if a module isn't included CI should fail. 
2. This doesn't remove optional requires from NCL
3. This will speed up CI by a lot. Since we aren't testing these modules yet it makes no sense to install their pods in CI.

**Comment by ide** [comment]
I agree with removing the optionalRequires from test-suite, they are dangerous. We probably should delete standalone-ncl once test-suite support in bare-expo is complete and we have a nice way to run NCL in it as well.

**Pull request closed without merging**
