### PR TITLE
fix(cli): remove non-standard error.code check

### PR DESCRIPTION
**Pull request by littledivy**
`error.code` is non-standard property not part of the URL API. This fixes compatibility issues with Deno (running Expo via Deno's Node.js compat layer).

This patch removes the `error.code` check because  `new URL()` can only throw when URL is invalid.

Ref https://github.com/denoland/deno/issues/22970

### CODE REVIEW

**Comment by littledivy** [comment]
ping @EvanBacon

Is there anything else required to have this merged? It will unblock running Expo natively in Deno.

**Comment by byCedric** [comment]
Hey @littledivy! Just for my understanding, is it possible in Deno to do something like: `if ('code' in error && error.code === 'X')`?

**Comment by lucacasonato** [comment]
This is possible, but why would you do that? If `URL` throws an error, it's always a parse error. This branch will never not be hit :)

**Comment by lucacasonato** [comment]
Or rather, that exact code would not fix it, it would have to be `if (!("code" in error) && error.code === "...") ...`. This is because `error.code` is not a standard property on errors. It's just something Node adds to some errors.

**Review by EvanBacon — APPROVED** [review]
lgtm, ensure changelog entry

**Pull request merged**
