### PR TITLE
Using Bugsnag

### PR DESCRIPTION
**Pull request by zeba1naqvi**
# Why

We are adding the Expo integration guide for Using Bugsnag. We have this included in our documentation as well: https://docs.bugsnag.com/platforms/react-native/expo/

# How

N/A

# Test Plan

N/A

### CODE REVIEW

**Comment by brentvatne** [comment]
hello! thanks for this, much appreciated! i'll give it a review shortly :)

**Comment by zeba1naqvi** [comment]
Thank you!

**Comment by zeba1naqvi** [comment]
Is there anything that we can help with to move this along? Thanks!

**Comment by zeba1naqvi** [comment]
@brentvatne, please let me know if there is anything we can help with to move this along. Thanks!

**Comment by brentvatne** [comment]
hi @zeba1naqvi, I'm just back from vacation today and will be looking soon!

**Comment by zeba1naqvi** [comment]
@brentvatne thanks!

**Review by brentvatne — APPROVED** [review]
this looks good, thank you!

**Pull request merged**
