### PR TITLE
Polyfill console logging in bare workflow

### PR DESCRIPTION
**Pull request by EvanBacon**
# Why

If the app is being run outside of the Expo Go app and not using `expo-dev-menu`, then we can attempt to polyfill the `logUrl` to enable console logging in the CLI.

# How

Check if the manifest is defined, if so, then get the dev server URL and append the `logs` path component. This will ensure logs get sent to the console when dev menu isn't installed. 

# Test Plan

- Copy into a bare project that doesn't have `expo-dev-menu` installed.
- Run the project with `expo start --dev-client` or use `expo run:ios`, `expo run:android` (RN CLI logging still works).
- Run the project with `npx react-native start` to ensure that logs aren't being printed twice.

### CODE REVIEW

**Review by ide — COMMENTED** [review]
What do you think about printing out a warning if `logUrl` is not provided? This would be for two reasons:

- It's fragile to polyfill the logUrl. There is strong coupling between the server's log endpoint and logging.fx.ts, which need to be kept in sync (not good).
- We have a mechanism for specifying logUrl. If the development server does not provide this, that indicates a mistake on the development server's part.

**Comment by EvanBacon** [comment]
I think we should warn but also attempt to polyfill since it's pretty cumbersome to use RN without console log debugging. When dev menu is in a better place I'd be comfortable removing this polyfill, but right now it seems reasonable to ensure expo CLI can be used to run most native React projects.

**Review by ide — APPROVED** [review]

**Comment by ide** [comment]
One other thought -- why would the `expo` package be used in RN projects? And wouldn't RN's implementation of console.log work with RN CLI?

**Comment by EvanBacon** [comment]
When a user ejects, the project is now bare and using expo without expo-dev-menu. RN's implementation assumes the user is running from React Native community CLI which logs anything that comes through metro. 

This PR addresses how someone in the future who uses expo-dev-menu may just use expo start --dev-client, expo run:ios, or expo run:android in any project regardless of it has expo-dev-menu installed at the time.

**Pull request merged**
