### PR TITLE
Added warning about Android not being supported

### PR DESCRIPTION
**Pull request by rasmusrim**
# Why

I have just spent several hours trying to get this to work with Android, only to find out that it does not support that OS. I think adding a warning at the top of this page would save some developers lots of time.

# How

Irrelevant

# Test Plan

Irrelevant

### CODE REVIEW

**Comment by IjzerenHein** [comment]
Hi! Firebase also works on Android. Can you describe what problem you are having by submitting an issue?

**Comment by rasmusrim** [comment]
Hi, IjzerenHein!
Well, in that case I am terribly sorry. I spent almost the entire day yesterday getting it to work, and then I found several threads saying that it does not work on Android. One of them are even mentioned in the document in question. See clark tank's or Brent Vatne's comment at the top on https://expo.canny.io/feature-requests/p/full-native-firebase-integration.

Anyway. This code works when run in the browser, but not when running in an Android emulator on Windows 10. I do not have the possibility of checking on iOS. No error messages, but nothing is stored.

`import React, { Component } from 'react';
import firebase from 'firebase'
import '@firebase/firestore';

export default class HomeScreen extends Component {

    constructor() {
        super()
    }

    render() {
        return (
            <></>
        )
    }

    componentDidMount() {
        this.saveCity();

    };

    saveCity() {

        let config = {
            apiKey: "secret",
            authDomain: "secret",
            databaseURL: "secret",
            projectId: "secret",
            storageBucket: "secret",
            messagingSenderId: "secret",
            appId: "secret"
        }
        firebase.initializeApp(config);
        var database = firebase.firestore();

        database.collection("cities").doc("LA").set({
            name: "Los Angeles",
            state: "CA",
            country: "USA"
        })


    }

}
`

**Comment by IjzerenHein** [comment]
Firestore should definitely work on Android as well. That comment is from 2017 at which the Firestore JS SDK did not fully support the react-native environment.
I will check it out whether I can reproduce it.

**Comment by rasmusrim** [comment]
@IjzerenHein Hi, again! I did some more testing now, and it seems it is only Android emulators which do not save these values. I have tried with both API 28 and 29. Connecting the app to an actual Android phone (with API 29) seems to work fine.

Have you been able to reproduce this? It would be interesting to find the reason for this, but I assume this is the wrong place for this issue now.

**Comment by IjzerenHein** [comment]
Hi! Which version of the Firebase JS SDK are you using?
[We've also just found out that the latest Firebase JS SDK contains some regressions and doesn't work anymore](https://github.com/expo/expo/issues/7507#issuecomment-608299120).

**Comment by IjzerenHein** [comment]
What exactly do you mean by:

> Android emulators which do not save these values

You mean that the `.set` call is not showing up in the cloud database right?

**Comment by rasmusrim** [comment]
@IjzerenHein Exactly.

I am using version 7.9.0. This is my package.json file:

```
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject",
    "test": "jest --watchAll"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@expo/vector-icons": "~10.0.0",
    "@react-native-community/geolocation": "^1",
    "@react-native-community/masked-view": "0.1.5",
    "@react-navigation/bottom-tabs": "^5.0.0",
    "@react-navigation/native": "^5.0.0",
    "@react-navigation/stack": "^5.0.0",
    "@react-navigation/web": "~1.0.0-alpha.9",
    "base-64": "^0.1.0",
    "crypto": "^1.0.1",
    "expo": "~36.0.0",
    "expo-asset": "~8.0.0",
    "expo-background-fetch": "~8.0.0",
    "expo-constants": "~8.0.0",
    "expo-font": "~8.0.0",
    "expo-location": "~8.0.0",
    "expo-permissions": "~8.0.0",
    "expo-web-browser": "~8.0.0",
    "firebase": "^7.9.0",
    "react": "~16.9.0",
    "react-dom": "~16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz",
    "react-native-background-timer": "^2.2.0",
    "react-native-chart-kit": "^5.3.0",
    "react-native-geolocation": "^1.0.0",
    "react-native-gesture-handler": "~1.5.0",
    "react-native-safe-area-context": "0.6.0",
    "react-native-screens": "2.0.0-alpha.12",
    "react-native-web": "~0.11.7",
    "react-native-xml2js": "^1.0.3",
    "react-native-svg": "9.13.3"
  },
  "devDependencies": {
    "@babel/core": "^7.0.0",
    "babel-preset-expo": "~8.0.0",
    "jest-expo": "~36.0.1"
  },
  "private": true
}

```

**Comment by IjzerenHein** [comment]
Hmm, interesting. I have tested on Android Emulator API 29 and my test application is able to successfully write to Firestore and I see new documents appear in the collection.

Have you tried checking whether the `.set` call throws an error?

```
try {
  await database.collection("cities").doc("LA").set({
            name: "Los Angeles",
            state: "CA",
            country: "USA"
        });
 } catch (err) {
  console.log(err);
}
```


Also, in your example you are always updating the same document. Is this intentional? How do you know that your `.set` call was succesful, do you delete the document from the cloud collection?

**Comment by IjzerenHein** [comment]
Hey I just noticed this in package.json `^7.9.0`. This will install `7.9.3` which contains the `atob` bug. Please install `firebase@7.9.0`

**Pull request closed without merging**
