### PR TITLE
Add GoogleService-Info.plist to bare-expo

### PR DESCRIPTION
**Pull request by IjzerenHein**
# Why

This PR adds a secret GoogleService-Info.plist file to the bare-expo iOS project. This file is needed for tests in the test-suite that utilize firebase-services.

# How

The GoogleService-Info.plist is generated automatically from the `template-files` and `secrets` upon building the bare-expo iOS project. When a public contributor works with bare-expo (who does not have access to the secrets), then the GoogleService-Info.plist is not linked into the project. If that contributors wants to test with anything firebase related, he or she can then copy a custom GoogleServices-Info.plist into the project.

# Test Plan

- prepare bare-expo
- load project in XCode
- start it

- project starts correctly
- GoogleServices-Info.plist is generated in `apps/bare-expo/ios/BareExpo`
-

### CODE REVIEW

**Review by sjchmiela — COMMENTED** [review]
I think you may also need to:
- add an entry to `template-files/ios-paths.json` for the file to be copied to `apps/bare-expo/ios`,
- add a `.gitignore` entry for the file to be ignored (so that it doesn't leak secrets when the file is generated by us)

**Comment by IjzerenHein** [comment]
> I think you may also need to:
> 
> * add an entry to `template-files/ios-paths.json` for the file to be copied to `apps/bare-expo/ios`,
> * add a `.gitignore` entry for the file to be ignored (so that it doesn't leak secrets when the file is generated by us)

Thanks for the feedback. I made those changes but something went wrong and they didn't end up in the PR. Will fix asap

**Review by sjchmiela — APPROVED** [review]
LGTM! 👍

**Comment by IjzerenHein** [comment]
@sjchmiela I'm noticing the client check has failed. Is this something I should ignore?

**Comment by sjchmiela** [comment]
I don't think this is anywhere near this PR's fault, but we could check whether the job passes on `master` and rerun it in this PR, just to be on the safe side. The error that is printed is:
```
[01:20:10]: ▸ /Applications/Xcode-11.GM.Seed.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -target i386-apple-ios10.0-simulator -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=gnu11 -fobjc-arc -fobjc-weak -fmodules -fmodules-cache-path=/Users/distiller/project/ios/simulator-build/ModuleCache.noindex -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/distiller/project/ios/simulator-build/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -Os -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Werror=return-type -Wdocumentation -Wunreachable-code -Wno-implicit-atomic-properties -Werror=deprecated-objc-isa-usage -Wno-objc-interface-ivars -Werror=objc-root-class -Wno-arc-repeated-use-of-weak -Wimplicit-retain-self -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wdeprecated-implementations -DPOD_CONFIGURATION_RELEASE=1 -DCOCOAPODS=1 -DNS_BLOCK_ASSERTIONS=1 -DOBJC_OLD_DISPATCH_PROTOTYPES=0 -isysroot /Applications/Xcode-11.GM.Seed.2.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.0.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -g -Wno-sign-conversion -Winfinite-recursion -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wno-semicolon-before-method-body -Wunguarded-availability -fobjc-abi-version=2 -fobjc-legacy-dispatch -iquote /Users/distiller/project/ios/simulator-build/Build/Intermediates.noindex/Amplitude-iOS.build/Release-iphonesimulator/Amplitude-iOS.build/Amplitude-iOS-generated-files.hmap -I/Users/distiller/project/ios/simulator-build/Build/Intermediates.noindex/Amplitude-iOS.build/Release-iphonesimulator/Amplitude-iOS.build/Amplitude-iOS-own-target-headers.hmap -I/Users/distiller/project/ios/simulator-build/Build/Intermediates.noindex/Amplitude-iOS.build/Release-iphonesimulator/Amplitude-iOS.build/Amplitude-iOS-all-target-headers.hmap -iquote /Users/distiller/project/ios/simulator-build/Build/Intermediates.noindex/Amplitude-iOS.build/Release-iphonesimulator/Amplitude-iOS.build/Amplitude-iOS-project-headers.hmap -I/Users/distiller/project/ios/simulator-build/Build/Products/Release-iphonesimulator/Amplitude-iOS/include -I/Users/distiller/project/ios/Pods/Headers/Private -I/Users/distiller/project/ios/Pods/Headers/Private/Amplitude-iOS -I/Users/distiller/project/ios/Pods/Headers/Public -I/Users/distiller/project/ios/Pods/Headers/Public/Amplitude-iOS -I/Users/distiller/project/ios/simulator-build/Build/Intermediates.noindex/Amplitude-iOS.build/Release-iphonesimulator/Amplitude-iOS.build/DerivedSources-normal/i386 -I/Users/distiller/project/ios/simulator-build/Build/Intermediates.noindex/Amplitude-iOS.build/Release-iphonesimulator/Amplitude-iOS.build/DerivedSources/i386 -I/Users/distiller/project/ios/simulator-build/Build/Intermediates.noindex/Amplitude-iOS.build/Release-iphonesimulator/Amplitude-iOS.build/DerivedSources -F/Users/distiller/project/ios/simulator-build/Build/Products/Release-iphonesimulator/Amplitude-iOS -w -Xanalyzer -analyzer-disable-all-checks -include /Users/distiller/project/ios/Pods/Target\ Support\ Files/Amplitude-iOS/Amplitude-iOS-prefix.pch -MMD -MT dependencies -MF /Users/distiller/project/ios/simulator-build/Build/Intermediates.noindex/Amplitude-iOS.build/Release-iphonesimulator/Amplitude-iOS.build/Objects-normal/i386/AMPTrackingOptions.d --serialize-diagnostics /Users/distiller/project/ios/simulator-build/Build/Intermediates.noindex/Amplitude-iOS.build/Release-iphonesimulator/Amplitude-iOS.build/Objects-normal/i386/AMPTrackingOptions.dia -c /Users/distiller/project/ios/Pods/Amplitude-iOS/Amplitude/AMPTrackingOptions.m -o /Users/distiller/project/ios/simulator-build/Build/Intermediates.noindex/Amplitude-iOS.build/Release-iphonesimulator/Amplitude-iOS.build/Objects-normal/i386/AMPTrackingOptions.o
[01:20:10]: ▸ fatal error: error in backend: Unexpected end of file
[01:20:10]: ▸ clang: error: clang frontend command failed with exit code 70 (use -v to see invocation)
[01:20:10]: ▸ Apple clang version 11.0.0 (clang-1100.0.33.8)
[01:20:10]: ▸ Target: i386-apple-ios10.0-simulator
[01:20:10]: ▸ Thread model: posix
[01:20:10]: ▸ InstalledDir: /Applications/Xcode-11.GM.Seed.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
[01:20:10]: ▸ clang: note: diagnostic msg: PLEASE submit a bug report to http://developer.apple.com/bugreporter/ and include the crash backtrace, preprocessed source, and associated run script.
[01:20:10]: ▸ clang: note: diagnostic msg:
[01:20:10]: ▸ ********************
[01:20:10]: ▸ PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
[01:20:10]: ▸ Preprocessed source(s) and associated run script(s) are located at:
[01:20:10]: ▸ clang: note: diagnostic msg: /var/folders/1b/gl7yt7ds26vcyr1pkgld6l040000gn/T/AMPTrackingOptions-6aaf73.m
[01:20:10]: ▸ clang: note: diagnostic msg: /var/folders/1b/gl7yt7ds26vcyr1pkgld6l040000gn/T/AMPTrackingOptions-6aaf73.cache
[01:20:10]: ▸ clang: note: diagnostic msg: /var/folders/1b/gl7yt7ds26vcyr1pkgld6l040000gn/T/AMPTrackingOptions-6aaf73.sh
[01:20:10]: ▸ clang: note: diagnostic msg: Crash backtrace is located in
[01:20:10]: ▸ clang: note: diagnostic msg: /Users/distiller/Library/Logs/DiagnosticReports/clang_<YYYY-MM-DD-HHMMSS>_<hostname>.crash
[01:20:10]: ▸ clang: note: diagnostic msg: (choose the .crash file that corresponds to your crash)
[01:20:10]: ▸ clang: note: diagnostic msg:
[01:20:10]: ▸ ********************
```

**Comment by IjzerenHein** [comment]
Master builds and PR as well now. Merging..

**Pull request merged**
