### PR TITLE
[menu] Fix the duplicated `DevMenuRNGestureHandlerStateManager.h` output file error

### LINKED ISSUE #18397: [SDK 46] expo-build-properties in custom dev client leads to build error
### Summary

Using `expo-build-properties` with the following configuration in `app.json` (needed in one of my projects for `react-native-firebase`)

```
["expo-build-properties", {"ios": {"useFrameworks": "dynamic"}}]
```

leads to the following error while build custom dev client

```
  error: Multiple commands produce '/Users/mlecoq/Library/Developer/Xcode/DerivedData/buildIssue-gbpimdiuimzzgjfjovhgjfixvrfb/Build/Intermediates.noindex/ArchiveIntermediates/buildIssue/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/EXDevMenu.framework/PrivateHeaders/DevMenuRNGestureHandlerStateManager.h'
```

### Managed or bare workflow? If you have made manual changes inside of the `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### Package versions

```
 "expo": "^46.0.1",
 "expo-build-properties": "~0.3.0",
 "expo-dev-client": "^1.1.1",
```

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.13.1 - /var/folders/md/1qkynwbs1216d57grkbc682h0000gn/T/fnm_multishells/69834_1658836725379/bin/node
      Yarn: 1.22.15 - /var/folders/md/1qkynwbs1216d57grkbc682h0000gn/T/fnm_multishells/69834_1658836725379/bin/yarn
      npm: 8.1.2 - /var/folders/md/1qkynwbs1216d57grkbc682h0000gn/T/fnm_multishells/69834_1658836725379/bin/npm
      Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7935034
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^46.0.1 => 46.0.1 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.3 => 0.69.3 
      react-native-web: ~0.18.7 => 0.18.7 
    npmGlobalPackages:
      eas-cli: 0.55.1
      expo-cli: 5.6.0
    Expo Workflow: managed

### Reproducible demo

Example app here : https://github.com/mlecoq/expoBuildIssue/tree/sdk46

### Stacktrace (if a crash is involved)

 duplicate output file '/Users/mlecoq/Library/Developer/Xcode/DerivedData/buildIssue-gbpimdiuimzzgjfjovhgjfixvrfb/Build/Intermediates.noindex/ArchiveIntermediates/buildIssue/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/EXDevMenu.framework/PrivateHeaders/DevMenuRNGestureHandlerStateManager.h' on task: CpHeader /Users/mlecoq/Library/Developer/Xcode/DerivedData/buildIssue-gbpimdiuimzzgjfjovhgjfixvrfb/Build/Intermediates.noindex/ArchiveIntermediates/buildIssue/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/EXDevMenu.framework/PrivateHeaders/DevMenuRNGestureHandlerStateManager.h /var/folders/md/1qkynwbs1216d57grkbc682h0000gn/T/eas-build-local-nodejs/fb938a77-6dc4-4a99-a340-8df3ac0e8e8b/build/node_modules/expo-dev-menu/vendored/react-native-reanimated/ios/DevMenuRNGestureHandlerStateManager.h (in target 'expo-dev-menu' from project 'Pods')

### PR DESCRIPTION
**Pull request by lukmccall**
# Why

Fixes https://github.com/expo/expo/issues/18397.

# How

Removed duplicated header file.

# Test Plan

- compile bare-expo and https://github.com/mlecoq/expoBuildIssue/tree/sdk46

### CODE REVIEW

**Review by ajsmth — APPROVED** [review]

**Review by esamelson — APPROVED** [review]
I imagine we'll need to remember to re-apply this change manually next time we vendor reanimated -- might be good to also add a warning/note to the vendoring script

**Comment by pehagg** [comment]
If I'm not mistaken, this won't fix the issue. The issue is caused by duplicate header files, commenting out the code inside the header file doesn't resolve the issue. You need to remove the header file. This is at least what I had to do to fix the issue locally.

**Comment by jorgebaraltq** [comment]
how can I pull this fix into my project?

**Comment by mechaadi** [comment]
@jorgebaraltq Did you find how to use this fix in your project?

**Comment by lukmccall** [comment]
You can use a patch package to apply diff or wait for a new version. It should be available soon ;)

**Comment by amin79** [comment]
@lukmccall I have upgraded to "expo": "^46.0.6" and "react-native": "0.69.4". But the problem is not solved.

**Comment by amin79** [comment]
@lukmccall could you please let us know we should wait for which version to get it fixed? We are on version 46.0.7 and still it is not fixed.

**Comment by esamelson** [comment]
@amin79 please try upgrading to `expo-dev-client@1.2.0`.

**Pull request merged**
