### PR TITLE
[ios][in-app-purchases] Fixes unhandled switch error cases

### PR DESCRIPTION
**Pull request by liampmccabe**
# Why

Handles new SKErrorCodes https://developer.apple.com/documentation/storekit/skerrorcode?changes=latest_min_4_5_____8

# How

Edited `EXInAppPurchasesModule.m` in `expo-in-app-purchases` package

# Test Plan

No longer fails when building. Struggling to run on Simulator but probably a lack of experience with the Expo repo or the latest Big Sur/Xcode betas.

### CODE REVIEW

**Comment by ide** [comment]
Could you talk more about the API design and how you decided to associate all these codes with 15? Should these be different error codes? Is 15 associated with anything on the JS side? Since this affects the API we need to make a thoughtful decision.

**Review by ide — CHANGES_REQUESTED** [review]
Requesting changes for an API design proposal and JS changes.

**Comment by liampmccabe** [comment]
@ide I couldn't recognise any pattern to the codes, they seemed arbitrary? Happy to amend once realised :) If anything they should go under 12 for Xcode version or 14 for iOS version?

**Comment by ide** [comment]
Read through the JS more so that you get a strong understanding of what's going on and can come up with an API proposal.

**Comment by liampmccabe** [comment]
Ah I see now, my bad! 

Despite three of the codes being related to the Overlay, the errors themselves seem unique enough for their own error code.

**Comment by ide** [comment]
You'll also need to rebuild the JS in order to get the tests passing. 

We also need to take Android and other future platforms into consideration. The way to approach this is to design a universal Expo API and then map it back to Android & iOS & web & etc... rather than looking at the iOS API and directly exposing it 1:1.

Should these error codes be grouped together or with existing error codes? Are there Android error codes we should take into consideration? How should the names of the TS enum values look for a universal API (right now it looks like they just map to the iOS enum names)?

**Comment by ide** [comment]
Superseded by https://github.com/expo/expo/pull/10224

**Pull request closed without merging**
