### PR TITLE
Use separate intent tags for AndroidManifest

### PR DESCRIPTION
**Pull request by quicksnap**
# Why

After upgrading to Beta SDK 42, I came across the android build error when using `yarn android`:

```
Unable to install /BlahBlahBlah/android/app/build/outputs/apk/debug/app-debug.apk
com.android.ddmlib.InstallException: INSTALL_PARSE_FAILED_MANIFEST_MALFORMED: Failed parse during installPackageLI: /data/app/vmdl932567260.tmp/base.apk (at Binary XML file line #44): intent tag may have at most one data type.
```

**I'm not sure if this is correct**. I just kind of threw things at the file until it started working. :) Happy to close this PR and open a bug if this fix is not correct.

### CODE REVIEW

**Comment by Kudo** [comment]
@quicksnap thanks for this help 👍 
it looks like there is yet another place at
https://github.com/expo/expo/blob/4b8f60490183b9bc5f27f71cd251b8c84f3e6926/packages/expo-sms/android/src/main/AndroidManifest.xml#L11-L17
do you mind to update the pr to fix them together?

**Comment by quicksnap** [comment]
@Kudo Sure thing, but before that, can you confirm that my approach is correct? 

I'm unfamiliar with Android's XML stuff. It seems to work so far, which is a good sign :)

**Comment by Kudo** [comment]
yes, i wrote some tests and can confirm multiple intent tag works.
please help to update expo-sms and changelog files.
thanks for your contribution 👍

**Comment by quicksnap** [comment]
Sure thing! I'll try to get it ready in the next hour

**Comment by quicksnap** [comment]
@Kudo  Updated PR and added changelog entries. Let me know if there's anything else needed!

**Comment by Kudo** [comment]
@quicksnap thanks for your help. you did really great for this pr 👍
will land after the CI passed 🚀

**Review by Kudo — APPROVED** [review]

**Pull request merged**
