### PR TITLE
[image][web] Fix a warning about invalid nativeViewRef prop

### PR DESCRIPTION
**Pull request by intergalacticspacehighway**
# Why
`ref.current.nativeViewRef.current` is null on web and it also shows a warning as it forwards invalid prop `nativeViewRef` on web.

# How
Pass `nativeViewRef` to `img` element on web.

# Test Plan
`ref.current.nativeViewRef` should hold the native `img` html element ref.

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [x] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Review by aleqsio — APPROVED** [review]

**Comment by aleqsio** [comment]
Thank you for your contribution!

**Comment by intergalacticspacehighway** [comment]
@aleqsio seems like type definition for `nativeViewRef`: `RefObject<ExpoImage>` is not very accurate as `nativeViewRef` gets passed as ref to the native Image object which doesn't have all the methods valid for `RefObject<ExpoImage>`. I think we can create a new type or just have `RefObject<any>` 😅 . So maybe we can have something like `nativeViewProp: RefObject<ExpoModuleNativeImage | HTMLImageElement>` and define `ExpoModuleNativeImage` to have methods exposed by native expo module's ref? wdyt?

**Comment by hirbod** [comment]
@aleqsio still a thing in SDK 50 Preview.11 + expo-image ~1.10.3

**Review by tsapeta — APPROVED** [review]

**Review by tsapeta — COMMENTED** [review]
Oops, I approved but then noticed that the SDK workflow on CI is failing and you didn't rebuild JS files. Can you please run `yarn build` and resolve TS issues if needed?

**Comment by intergalacticspacehighway** [comment]
@tsapeta Done. Type fix felt a bit of workaround but `nativeViewRef` seems undocumented anyways. So we can revisit if it's made official at some point 😅

**Pull request merged**
