### PR TITLE
[expo-firebase-*] Remove libraries

### PR DESCRIPTION
**Pull request by keith-kurak**
# Why

We deprecated `expo-firebase-analytics` / `expo-firebase-recaptcha` (and hence, `expo-firebase-core`) in SDK 47, with removal planned in 48.

# How

Remove `expo-firebase-analytics`, `expo-firebase-recaptcha`, `expo-firebase-core` packages. Updated dependencies in test apps/ Expo Go, removed Scoped Firebase class. 

Needed to update `com.google.firebase:firebase-core` to 21.1.0 in **expoview/build.gradle** due to the below error. I think this was related to the Expo Firebase packages requiring this version anyway, which was likely inhibiting the error.

```
Duplicate class com.google.android.gms.internal.firebase_messaging.zza found in modules jetified-firebase-iid-20.0.2-runtime (com.google.firebase:firebase-iid:20.0.2) and jetified-firebase-messaging-22.0.0-runtime (com.google.firebase:firebase-messaging:22.0.0)
...
Duplicate class com.google.firebase.iid.FirebaseInstanceIdReceiver found in modules jetified-firebase-iid-20.0.2-runtime (com.google.firebase:firebase-iid:20.0.2) and jetified-firebase-messaging-22.0.0-runtime (com.google.firebase:firebase-messaging:22.0.0)
```

# Test Plan

Tested building bare-expo and Expo Go on iOS and Android.

# Checklist

~~**NOTE**: will open up a separate PR to update documentation; there's a decent amount of cross-linked stuff, don't want to miss that in a large-ish diff.~~

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [x] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Comment by Simek** [comment]
We also need to remove docs for those packages, and setup the redirects to ensure that people don't land on 404.

**Review by tsapeta — COMMENTED** [review]
Usually we don't remove the entire package from the repo, even if we remove it from the SDK. We should keep `package.json` and `README.md` that states that this package is no longer maintained and also publish that to npm.

**Comment by keith-kurak** [comment]
> Usually we don't remove the entire package from the repo, even if we remove it from the SDK. We should keep `package.json` and `README.md` that states that this package is no longer maintained and also publish that to npm.

Good point- I was cribbing off of the Amplitude removal, and thought it was completely removed, but, [per this comment](https://github.com/expo/expo/pull/18168#issuecomment-1181133795), it turns out it was actually copied to a separate repo, with readme updated and set to read-only.

What's preferred in this case (copying to a new repo or leave package.json/ readme)? Copying perhaps makes it a little easier to see the final state before removal, I suppose.

**Comment by keith-kurak** [comment]
> We also need to remove docs for those packages, and setup the redirects to ensure that people don't land on 404.
Done - I added the redirects [based on how they were done on this PR](https://github.com/expo/expo/pull/20443), but couldn't see a change (locally, it redirects back to SDK 47 docs), so appreciate an additional check there.

**Comment by Simek** [comment]
Can you also remove entries for docs data generation from the file mentioned below?
* https://github.com/expo/expo/blob/main/tools/src/commands/GenerateDocsAPIData.ts#L54-L55

**Comment by keith-kurak** [comment]
> > What's preferred in this case (copying to a new repo or leave package.json/ readme)? Copying perhaps makes it a little easier to see the final state before removal, I suppose.
> 
> If that sounds easier to you then yeah, go with copying 😉

These are copied/ archived now:
https://github.com/expo/expo-firebase-analytics/
https://github.com/expo/expo-firebase-core/
https://github.com/expo/expo-firebase-recaptcha/

**Review by tsapeta — APPROVED** [review]

**Comment by Simek** [comment]
Looks good from the docs side too! 👍

**Review by Simek — APPROVED** [review]
Looks good from the docs side too! 👍

**Pull request merged**
