### PR TITLE
fix: withIosSplashScreenStoryboardBaseMod: Cannot read properties of undefined (reading 'findIndex')

### PR DESCRIPTION
**Pull request by Albert-Gao**
# Why

image

# How

got error when running this: `npx expo config --type introspect`, which also blocks building.

# Test Plan

tested locally that no error anymore.

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Comment by Albert-Gao** [comment]
I do not know why the diff is not showing up, 
but it is just a 1-liner

image

the only thing I changed is the line 68, from `imageSection.findIndex(` to `imageSection?.findIndex(`

**Comment by alanjhughes** [comment]
Hi @Albert-Gao - Looks like your modifying the build file. You need to change `expo/packages/@expo/prebuild-config/src/plugins/unversioned/expo-splash-screen/InterfaceBuilder.ts` and rebuild the js.

**Comment by Albert-Gao** [comment]
Hi, @alanjhughes 

Thanks for pointing it out, silly me, I updated the Typescript file,

However, the build process rebuilt all files, and caused a merge conflict with the master branch,

the procedure I was taking for building is as the following:
image

Anything I am missing here? Thanks

**Comment by Albert-Gao** [comment]
Hi, @alanjhughes 

Thanks for pointing out, I've updated the PR.

**Comment by alanjhughes** [comment]
Hi @Albert-Gao no, no need to bump the version. Let's see how CI goes now

**Comment by clarkg** [comment]
Hi @Albert-Gao @alanjhughes thanks for doing this but can we please merge this? this is blocking a bunch of us 

https://discord.com/channels/695411232856997968/809586753719238656/1302608570172444732

**Comment by froilansam** [comment]
I am blocked by this

**Comment by alanjhughes** [comment]
Thank you for your contribution @Albert-Gao! I am taking a slightly different approach in #32858 so I will close in favour of that

**Comment by Albert-Gao** [comment]
Thank you :)

**Pull request closed without merging**
