### PR TITLE
[expo-asset] Move side effects into a separate .fx.ts file

### LINKED ISSUE #4659: Move expo-asset side effects into an .fx.ts file
This lets us tell tools like Webpack about sideEffects more easily.

### PR DESCRIPTION
**Pull request by hesyifei**
# Why

Fixes #4659.
This lets us tell tools like Webpack about sideEffects more easily.

# How

I moved side effects into a separate .fx.ts file and `import` it from the main file.

# Test Plan

It passes `jest`.

### CODE REVIEW

**Comment by EvanBacon** [comment]
Great work, could you run something like native component list to ensure it's not breaking something.

**Review by ide — APPROVED** [review]
Thank you! Please also run `yarn build` and commit the changed .js files too.

**Comment by hesyifei** [comment]
There's this warning because the `.fx` file needs to use the static function `fromMetadata` in `Asset`. Would it be better to move `fromMetadata` and other static functions to a separate file (and call those functions in `Asset`) or are there better ways to address this?

```
Require cycle: ../../packages/expo-asset/build/Asset.js -> ../../packages/expo-asset/build/Asset.fx.js -> ../../packages/expo-asset/build/Asset.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
```

**Comment by ide** [comment]
Good catch -- we want to break the cycle. Asset.fromMetadata calls into the Asset constructor, so a simple approach is probably to have three files: index.ts, Asset.fx.ts, and Asset.ts. index.ts would be the new entry point of the package (update `main` and `types` in package.json):

index.ts:
```
import './Asset.fx';

export * from './Asset';
```

**Review by ide — APPROVED** [review]
Looks good; go ahead and squash & commit!

**Pull request merged**
