### PR TITLE
[docs] Add React Native UI Lib as one of the UI Libraries

### PR DESCRIPTION
**Pull request by cloudmu**
React Native UI Lib by Wix is a feature rich and popular open source user interface library.  It should be included.

# Why
React Native UI Lib by Wix is a feature rich and popular open source user interface library. It should be included.

# How
It's added at the end of the current UI lib list, following the same format.

# Test Plan
The changes display as expected.

### CODE REVIEW

**Comment by cruzach** [comment]
This library contains native code, so it's not managed workflow friendly unfortunately :( (the rest of the options in that list are) 

Could you add a note, just saying `(bare workflow only)` on the same line?

**Comment by cloudmu** [comment]
> 
> 
> This library contains native code, so it's not managed workflow friendly unfortunately :( (the rest of the options in that list are)
> 
> Could you add a note, just saying `(bare workflow only)` on the same line?

@cruzach The library showcases a pretty comprehensive demo as an expo-snack.  It has been kept up to date with the latest lib releases. 
https://wix.github.io/react-native-ui-lib/

@ethanshar Could you please chime in on react-native-ui-lib's use with Expo?

**Comment by brentvatne** [comment]
it looks like the only dependency that is required that we do not include is this:

@react-native-community/blur": ">=3.4.1"

but if it runs in snack then it seems to work without this. either way it'd be nice for the instructions in the rn-ui-lib docs to be clear about this and provide `expo install` instructions to copy paste similar to https://reactnavigation.org/docs/getting-started

**Comment by ethanshar** [comment]
Hi, 
sorry for the delay. 

First, we have plans on removing usage of the **@react-native-community/blur** native package in our next major version. 
The expo snack works as long as you don't open a component that uses the **blur** package (As far as I remember). 

TBH, Im not that familiar with Expo and only had some experience when I created the expo-snack. 
What is required by us to be included in Expo?

**Comment by brentvatne** [comment]
it looks like this ended up getting added in another pr: https://docs.expo.dev/guides/userinterface/

cheers

**Pull request closed without merging**
