### PR TITLE
Add Street Number to reverse geocode (iOS)

### LINKED ISSUE #12187: A returned address by Location.reverseGeocodeAsync lacks some fields
### Summary

A returned address by `Location.reverseGeocodeAsync` lacks some required fields for an address in Japan.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

40

### Environment

  Expo CLI 4.2.1 environment info:
    System:
      OS: macOS 11.2.3
      Shell: 5.8 - /usr/local/bin/zsh
    Binaries:
      Node: 15.11.0 - /var/folders/1y/l347vl3x7szbd93vm9fb6q6w0000gn/T/yarn--1615450234418-0.4526026348325587/node
      Yarn: 1.22.10 - /var/folders/1y/l347vl3x7szbd93vm9fb6q6w0000gn/T/yarn--1615450234418-0.4526026348325587/yarn
      npm: 7.6.0 - /usr/local/bin/npm
    IDEs:
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: ^40.0.0 => 40.0.0
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.0.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

When you call `Location.reverseGeocodeAsync()` method like below, you can get the result.

```typescript
const coordinate = { latitude: 34.7275805, longitude: 135.2723769 }
const results = await Location.reverseGeocodeAsync(coordinate)
```

on iOS

```
Array [
  Object {
    "city": "神戸市東灘区",
    "country": "日本",
    "district": "田中町",
    "isoCountryCode": "JP",
    "name": "田中町1丁目7-22",
    "postalCode": "658-0081",
    "region": "兵庫県",
    "street": "田中町1丁目",
    "subregion": null,
    "timezone": "Asia/Tokyo",
  },
]
```

on Android
```
Array [
  Object {
    "city": "神戸市",
    "country": "日本",
    "district": "東灘区",
    "isoCountryCode": "JP",
    "name": "２２",
    "postalCode": "658-0081",
    "region": "兵庫県",
    "street": "１丁目",
    "subregion": null,
    "timezone": null,
  },
]
```

The actual address of the point is `兵庫県 / 神戸市 / 東灘区 / 田中町 / 1丁目 / 7-22`, but the result on Android lacks `田中町` and `7`.

I think `getPremises()` and `getSubThoroughfare()` method in [Address](https://developer.android.com/reference/android/location/Address) object in Android API return those lacking attributes. So I propose add those fields as `premises` and `subStreet` in address object in the return value of `Location.reverseGeocodeAsync` method.

Fortunately, `CLPlacemark` object on iOS has `subThoroughfare` attribute. Therefore I think we can map those attributes between iOS and Android.

### PR DESCRIPTION
**Pull request by chrisdrackett**
# Why

Without this value addresses returned are not really valuable or exact. fixes #12187 

# How

Added `subThoroughfare` to iOS which apple uses for the street number (https://developer.apple.com/documentation/corelocation/clplacemark/1423782-subthoroughfare)

# Test Plan

Reverse geocode a location and make sure street number comes back.

# Checklist

- [X] Documentation is up to date to reflect these changes (eg: https://docs.expo.io and README.md).
- [x] This diff will work correctly for `expo build` (eg: updated `@expo/xdl`).
- [x] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Review by lukmccall — APPROVED** [review]
Looks good to me 💪
Thanks for your contribution 🏅

To test that you need to build `bare-expo`. See https://github.com/expo/expo/blob/master/CONTRIBUTING.md

**Comment by chrisdrackett** [comment]
I'm having a really hard time figuring out how to use this in my project while waiting for this PR to make it into expo. As far as I can tell at some point expo-location is built when being published to npm, but I can't for the life of me figure out where or how that happens.

**Comment by lukmccall** [comment]
@chrisdrackett, sorry for the late reply, but I was on vacation. Please resolve the conflicts and I'll test it on my end :D

**Comment by chrisdrackett** [comment]
@lukmccall I'm fixing the conflicts now. Gotta admit, it's insane to me that it hasn't been a higher priority to get this fixes. IMO reverse geocoding is 100% unusable without the street address!

**Comment by chrisdrackett** [comment]
@lukmccall ok, it took longer than I'd like, but I've cleaned up the merge conflicts.

**Pull request merged**
