### PR TITLE
[print] add doc comments in source

### PR DESCRIPTION
**Pull request by Simek**
# Why

To utilize the auto generation feature for API section the package source code must contain the relevant documentation.

Refs #12239

Fixes ENG-790

# How

This PR moves the current documentation of `Print` API - https://docs.expo.io/versions/latest/sdk/task-manager/ - (with minor tweaks and addition) to the package source code.

The changes also include an addition of missing `base64` related field in `FilePrintOptions` and `FilePrintResult`, as well as missing `width` and `height` fields in `PrintOptions` (they were present in other type, but not here). This should be checked and reviewed, because I have trusted the previous docs with this changes, which might not be accurate.

Also the `Orientation` and `OrientationType` structure might be a bit confusing for the users. I'm not sure why `OrientationType` isn't an enum or why an additional layer of typing occurs in case of `Orientation` constant. Maybe someone from the team will have a clue.

Within this PR I have also added type to the `APISectionContants` entries. Constant were earlier used on the `Application` page, but the original constants structure do not include a constant type, so until now types were missing in there.

# Test Plan

The changes and generated content have been tests running docs website on localhost.

# Preview

Screenshot 2021-04-27 at 13 18 40

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.io and README.md).
- [x] This diff will work correctly for `expo build` (eg: updated `@expo/xdl`).
- [x] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

CC: @bbarthec

### CODE REVIEW

**Review by lukmccall — APPROVED** [review]
LGTM 👍

**Review by tsapeta — APPROVED** [review]

**Comment by mstach60161** [comment]
Hi @Simek
Unfortunately due to a changing `orientation` to enum, type of `orientation` is displayed as `undefined | undefined`.
Do you have any idea, how can we fix it?
https://docs.expo.dev/versions/latest/sdk/print/#printoptions

**Comment by Simek** [comment]
> Hi @Simek
> Unfortunately due to a changing `orientation` to enum, type of `orientation` in docs is displayed as [`undefined | undefined`](https://docs.expo.dev/versions/latest/sdk/print/#printoptions).
> Do you have any idea, how can we fix it?

I will look at it, thank you for the ping! 🙂

**Comment by Simek** [comment]
> Unfortunately due to a changing `orientation` to enum, type of `orientation` in docs is displayed as [`undefined | undefined`](https://docs.expo.dev/versions/latest/sdk/print/#printoptions).

Just to be clear, I have not changed this type to Enum, and the weird type config for the `OrientationType` is the problem in the first place. As stated in the original comment, this is confusing (and lead to issues as we see). 😉 TypeDoc is confused by keyed references in interface like `OrientationType['portrait']`, which did not make much sense in the first place.

Additionally it looks like JSON API data files are not updated to match the current state of the source code, which also might me part of the reason. I will update the JSON files in the separate PR.

I have asked about why the type looks like that on the Discord when I was initial working on the conversion, but it looks like the one who works on this package earlier is no longer with Expo.

The best way to solve this, if you feel confident enough that there will be no regression, will be `OrientationType` type refactor to string enum, string literal or `type` with `orientation` key.

**Pull request merged**
