### PR TITLE
Treat SQLite PRAGMA statements as result-returning SELECT statements

### PR DESCRIPTION
**Pull request by iffy**
Attempted fix for #1489.  I will also make a PR to add tests to expo/test-suite for this change.

### CODE REVIEW

**Comment by iffy** [comment]
I should note that I haven't compiled this or run any tests (because I haven't yet figured out how to do either).

**Comment by jesseruder** [comment]
Thanks @iffy!

**Comment by iffy** [comment]
@jesseruder Is there something I can subscribe to to know when this change has landed in an expo release?

**Comment by ide** [comment]
Hi @iffy - you can subscribe to our blog at https://blog.expo.io, which is where we'll announce the next Expo client release (SDK 30), which will include your patch. We sometimes do minor releases as well between SDKs -- if you have the Expo client installed and your phone is configured to notify you some way of updated apps, you could see when a new Expo client is out.

**Pull request closed without merging**
