### PR TITLE
[notifications][ios][android] Support custom notification sounds

### PR DESCRIPTION
**Pull request by hesyifei**
# Why

https://expo.canny.io/feature-requests/p/push-notification-include-custom-sound-files-in-build

# How

Allow `sound` to be either a `boolean` (`true` means the default sound) or a `string` (the audio file name).

See also https://github.com/expo/expo-cli/pull/998 and https://github.com/expo/universe/pull/3679.

# Test Plan

Note that custom notification sound files will only work in the standalone build. If the notification is send to the Expo client, you will always hear the default sound.

Only `.wav` file is supported by both iOS and Android.

In `app.json`:

```jsonc
{
  "expo": {
    // ...
    "notification": {
      // ...
      "bundledSounds": ["./assets/sound1.wav", "./assets/sound2.wav"]
    }
}
```

For Android channel:
```js
// No sound
Notifications.createChannelAndroidAsync('noSoundChannel', {
  // ...
  sound: false // or remove this line
)

// Default sound
Notifications.createChannelAndroidAsync('defaultSoundChannel', {
  // ...
  sound: true // or 'default'
})

// Custom sound
Notifications.createChannelAndroidAsync('customSoundChannel', {
  // ...
  sound: 'sound1.wav'
})

Notifications.createChannelAndroidAsync('anotherCustomSoundChannel', {
  // ...
  sound: 'sound2.wav'
})
```

For local notification:

```js
// No sound
Notifications.presentLocalNotificationAsync({
  // ...
  ios: {
    sound: false // or remove this line
  },
  android: {
    channelId: 'noSoundChannel'
  }
});

// Default sound
Notifications.presentLocalNotificationAsync({
  // ...
  ios: {
    sound: true // or 'default'
  },
  android: {
    channelId: 'defaultSoundChannel'
  }
});

// Custom sound
Notifications.presentLocalNotificationAsync({
  // ...
  ios: {
    sound: 'sound1.wav'
  },
  android: {
    channelId: 'customSoundChannel'
  }
});
```

For push notification:

```json
[
  {
    "to": "ExponentPushToken[aaaaaaaaaaaaaaaaaaaaaa]",
    "body": "With no sound",
    "channelId": "noSoundChannel"
  },
  {
    "to": "ExponentPushToken[bbbbbbbbbbbbbbbbbbbbbb]",
    "body": "With default sound",
    "sound": "default",
    "channelId": "defaultSoundChannel"
  },
  {
    "to": "ExponentPushToken[cccccccccccccccccccccc]",
    "body": "With custom sound",
    "sound": "sound2.wav",
    "channelId": "anotherCustomSoundChannel"
  }
]
```

### CODE REVIEW

**Comment by Szymon20000** [comment]
I will be more than happy if we could introduce this feature after notifications are moved to unimodule.
It seems that your changes can be easily moved to the new expo-notifications module.
If it’s not possible then I have a couple of comments/questions.
What about Androids below Oreo? I think we want to set them a custom sounds as well. 
Currently, we have two places where we build notifications (Look at PushNotificationHelper).

**Comment by vernondegoede** [comment]
Hey all, not trying to push anyone, but I was wondering what the status of this PR is. Is this PR on hold until this is moved to the `expo-notifications` module?

**Comment by devstarman** [comment]
Hi, don't want to push anyone but will there be progress on that?
It's really crucial feature for apps designed for merchants (loud and long alarms when new order appears) and in my app we're actually thinking about going back to native to implement it right now :(

**Comment by moparlakci** [comment]
Is it possible to merge this, want to use this feature definitely, I think it is the most wanted option in expo, anyone have a launch date?

**Comment by santhoshdasari786** [comment]
Hey Can we expect this Feature in SDK 37

**Comment by almassapargali** [comment]
?

**Comment by sjchmiela** [comment]
Hello all,

I’m sorry to say it, but the current `Notifications` API available in Expo will be deprecated (most probably around SDK38). We are in process of developing a new `expo-notifications` module from scratch, which will work in both managed and bare workflows (available in SDK38 and earlier as a package for bare).

This PR has not been merged for SDK37, so it will not support custom notification sounds, but we will make sure to port the changes to `expo-notifications`, so it should support custom notification sounds soon. 🙂

**Comment by santhoshdasari786** [comment]
Thanks for the update. we are eagerly waiting for it . 
Would it be correct to assume we can expect it by June ?

**Comment by ide** [comment]
6/30 is the target date for the next-next managed workflow release. Depending on your tradeoff priorities and if this feature important enough to you, updates to the expo-notifications package sometimes can be published outside of the managed release schedule in which case you could use it sooner with the bare workflow.

**Comment by fkanout** [comment]
Hi @hesyifei , I'm not sure if this could work, but what If used your forked branch of Expo in my project, could I have a working custom notification sounds? 🤔

**Comment by di9it** [comment]
> Hello all,
> 
> I’m sorry to say it, but the current `Notifications` API available in Expo will be deprecated (most probably around SDK38). We are in process of developing a new `expo-notifications` module from scratch, which will work in both managed and bare workflows (available in SDK38 and earlier as a package for bare).
> 
> This PR has not been merged for SDK37, so it will not support custom notification sounds, but we will make sure to port the changes to `expo-notifications`, so it should support custom notification sounds soon. 🙂

Folks, are you going to include in SDK38 images as well or just sound support?

**Comment by tsapeta** [comment]
Closing this PR as this is now a part of the new `expo-notifications` module that will land in SDK38.

**Comment by flalex** [comment]
Great work!

Despite the risks is there opportunity to try it right now in managed workflow?
@fkanout Have you got success with the forked branch?

**Comment by sjchmiela** [comment]
Hey @flalex, I'm sorry to say that even though `expo-notifications` are going to land in SDK38 in managed workflow, using custom sounds won't be supported (yet?) in managed workflow.

**Comment by santhoshdasari786** [comment]
> Hey @flalex, I'm sorry to say that even though `expo-notifications` are going to land in SDK38 in managed workflow, using custom sounds won't be supported (yet?) in managed workflow.

Hey @hesyifei custom ringtone or  customsounds for notifications will be there in sdk 38 managed workflow or not ?

**Pull request closed without merging**
