### PR TITLE
fix(expo-updates): pass absolute entry path from gradle plugin and convert to relative path in Node

### PR DESCRIPTION
**Pull request by byCedric**
# Why

This is a follow-up of #30652, #30633, #30621

Kinda annoying that we use relative entry paths for iOS, and absolute for Android. But it is what it is.

# How

This moves the incorrect relative path modification in the `expo-updates-gradle-plugin` to the Node script itself, where we can reuse the functions from `@expo/config/paths`. These shared functions takes the server or project root into account.

# Test Plan

See CI, specifically test-suite android.

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Comment by byCedric** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/expo/expo/30654?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#30654** <a href="https://app.graphite.dev/github/pr/expo/expo/30654?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#30652** <a href="https://app.graphite.dev/github/pr/expo/expo/30652?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#30633** <a href="https://app.graphite.dev/github/pr/expo/expo/30633?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#30621** <a href="https://app.graphite.dev/github/pr/expo/expo/30621?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @byCedric and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by douglowder — APPROVED** [review]
Looks good -- if e2e (updates enable) does not pass on Android, I'll take a look to see what's going on under the hood...

**Comment by byCedric** [comment]
Thanks @douglowder! I just restarted them, if that passes we are good. I don't expect this change to cause test failures.

**Review by wschurman — APPROVED** [review]

**Comment by byCedric** [comment]
### Merge activity

* **Jul 30, 11:23 AM EDT**: @byCedric started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/expo/expo/30654).

**Pull request merged**
