### PR TITLE
[camera] Fix web imports

### LINKED ISSUE #26504: [expo-camera] The method or property expo-modules-core.requireNativeViewManager is not available on web
### Minimal reproducible example

https://snack.expo.dev/@adamhari-kashoo/vigorous-orange-popcorn

### Summary

This error appeared in a project after upgrading Expo 49 --> 50 and Expo Camera 13.x --> 14.x.

```
Uncaught Error: The method or property expo-modules-core.requireNativeViewManager is not available on web, are you sure you've linked all the native dependencies properly?
    at requireNativeViewManager (NativeViewManagerAdapter.js:7:2)
    at ExpoCamera.js:3:30
    at loadModuleImplementation (require.js:352:5)
    at guardedLoadModule (require.js:242:1)
    at metroRequire (require.js:128:1)
    at Camera.js:6:1
    at loadModuleImplementation (require.js:352:5)
    at guardedLoadModule (require.js:242:1)
    at metroRequire (require.js:128:1)
    at index.js:3:1
```

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 13.6
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.16.0 - /usr/local/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 9.5.1 - /usr/local/bin/npm
      Watchman: 2022.10.03.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /Users/adamhari/.rvm/gems/ruby-2.7.6/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8193401
      Xcode: 15.0/15A240d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.2 => 50.0.2 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.73.2 => 0.73.2 
      react-native-web: ~0.19.9 => 0.19.9 
    npmGlobalPackages:
      eas-cli: 3.12.0
    Expo Workflow: bare

### PR DESCRIPTION
**Pull request by alanjhughes**
# Why
Closes #26504
Files were renamed to `ExpoCamera` but the web specific files were still `ExponentCamera` leading to an error when importing on web.

# How
Renamed the files. 

# Test Plan
Tested in a local project. Web specific files are found and work correctly.

### CODE REVIEW

**Review by lukmccall — APPROVED** [review]

**Comment by WatchmansEase** [comment]
This bug still exists if you create a new Expo Repository, and setup a fresh component of Expo Camera. It will work on Android Emulator, it will error on Web.

**Comment by brentvatne** [comment]
@WatchmansEase - can you share a minimal reproducible example repository please? https://stackoverflow.com/help/minimal-reproducible-example

**Comment by alanjhughes** [comment]
@WatchmansEase - what version of `expo-camera` are you using? Should be 14.0.2

**Comment by alanjhughes** [comment]
@WatchmansEase - I've just tested this in a new expo project and it is working on web

**Comment by WatchmansEase** [comment]
@alanjhughes My apologies and my thanks - upgrading to `expo-camera` to 14.0.2 fixed this.

**Comment by alanjhughes** [comment]
@WatchmansEase - no problem 👍 glad it's working for you.

**Pull request merged**
