### PR TITLE
[expo-facebook] Updated version of Facebook SDK to 9.0.0

### PR DESCRIPTION
**Pull request by dreamolight**
# Why
To be compliant with iOS 14, Facebook iOS SDK needs to be at least 8.0.0, and there were some difficulties upgrading to 8.0.0 for expo due to Swift being introduced, the issue is fixed in 9.0.0.

# How
* Switched to use pre-built pod of Facebook SDK
* Provided wrapper function to call `setAdvertiserTrackingEnabled` which is essential to be compliant with Apple's iOS 14 tracking policy

# Test Plan
Run bare-expo via `yarn ios`, then run `Facebook` test.

### CODE REVIEW

**Comment by dreamolight** [comment]
The failed check seemed to be related to vercel token ($ZEIT_TOKEN).

**Comment by dreamolight** [comment]
Hi @bbarthec and @tsapeta , could you provide guidance on how to bypass the `publish expo web` failure? Seems that $ZEIT_TOKEN is missing, any extra steps I need to conduct when submitting the PR?

**Comment by tsapeta** [comment]
Hey @dreamolight, thanks for the PR! You don't need to care about this failing job, it doesn't work for everyone outside organization members (we'll need to fix it).
As the PR is kinda big, we have to review it more thoroughly and do more QA on it — we'll let you know soon!

**Comment by sergioAgudelo** [comment]
Hi @tsapeta is there any estimated date for this solution to be merge?

Thanks in advanced.

**Comment by brentvatne** [comment]
@sergioAgudelo - if we merge it then it would be deployed in sdk 41, to be released at the beginning of april

**Comment by dreamolight** [comment]
Hi @brentvatne , is there any chance this could be picked and released sooner? The wrapper API for setAdvertiserTrackingEnabled would be required for iOS apps using FB SDK to be compliant with Apple's privacy policy.

**Comment by tsapeta** [comment]
Just wanted to let you know that I'm taking over this PR — I think there are a little bit more things to change and since we're making such a big leap in versions it requires some QA before merging.
I'm closing this PR and gonna open another one and link to here.

**Comment by dreamolight** [comment]
Thanks @tsapeta, please let me know if there is further change needed from me.

**Pull request closed without merging**
