### PR TITLE
Syntax error in docs has been fixed

### PR DESCRIPTION
**Pull request by abduraufsherkulov**
# How

How did you build this feature or fix this bug and why?

I just noticed while working with FlatView.

### CODE REVIEW

**Comment by nicknovitski** [comment]
There's actually many react-native pages with code like `${"{"}`.  I think it's caused by a bug in the script we use to import them. @ccheever @ide

**Comment by nicknovitski** [comment]
[Looks like it's these lines](https://github.com/expo/expo/blob/ef8b2cf9fd631b95c2247ee0c09b704165964b99/docs/scripts/import-react-native-docs.js#L149-L153)/

**Comment by ide** [comment]
I opened up https://github.com/expo/expo/issues/3356 for the long term fix. It looks like this PR has a merge conflict, though -- perhaps the bug at hand was fixed?

**Comment by nicknovitski** [comment]
[No, still there](https://docs.expo.io/versions/v32.0.0/react-native/flatlist/).  I'll take care of it.

**Comment by nicknovitski** [comment]
Sorry @abduraufsherkulov, I created the merge conflict by rearranging the docs directory.  Instead of telling you to rebase, I'm going to close this PR in favor of #3399, where I fixed all of the errors I could find, but it's all thanks to you.  Thank you again!

**Pull request closed without merging**
