### PR TITLE
[expo] add more modules from SDK to error blacklist

### PR DESCRIPTION
**Pull request by esamelson**
# Why

https://exponent-internal.slack.com/archives/C1QNF5L3C/p1661513844440269

# How

opened NCL and test-suite in Expo Go, added modules which caused errors to be thrown (vector-icons, async-storage, expo-image) to blacklist

# Test Plan

NCL and test-suite both open in Expo Go without errors

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Review by tsapeta — COMMENTED** [review]
I think it solves the problem only partially. There might be more libs that don't expect that `NativeModules.*` will throw an error.

This is probably another one that we should exclude: https://github.com/LinusU/react-native-get-random-values/blob/0a48c10a395c19affb9e24044a31e6e56afbf20a/index.js#L27

**Review by ide — APPROVED** [review]
Makes sense for packages we don't maintain. For ones we do maintain, I think it'd be better to provide a way for module authors (just us at the moment) to disable the error checking for their own native module.

I could imagine something like disableMissingNativeModuleErrors but it accepts a single module's name and adds it (vs clobbering) to the set to ignore. An extension of this idea to consider is a method to re-enable errors as well. The pattern could be like this:

```js
disable errors for module
code that tests if a module is available
enable errors for module
```

or perhaps instead of methods to disable/enable errors, there could be a method like `getNativeModuleIfExists(moduleName)` that just returns null without throwing an error.

Approving this PR in any case. In the long term, we don't want one file to need to specify all of the exemptions though.

**Comment by brentvatne** [comment]
@tsapeta - good call with react-native-get-random-values

@ide - my guess is that if a developer understands what is happening enough to disable a missing native module warning by name, they likely can just want to disable every missing native module warning. that said, one exception I can think of here is that if you organize your team such that you have native developers that work on the runtime and js developers that work on the application code - but i'm not convinced it really matters in that case.

**Comment by esamelson** [comment]
@brentvatne we don't have a very good way of doing that right now (people can import NativeModules directly from `react-native/Libraries/BatchedBridge/NativeModules' but of course that is not a very good thing to suggest).

I'll add the random-values one to this list for now and follow up with another PR implementing something like what @ide proposed for module authors -- agree this is a missing piece right now.

**Comment by ide** [comment]
I was thinking about the case where a module author wants to write their code in a way that uses feature detection. They need to not have side effects that affect other modules.

**Pull request merged**
