### PR TITLE
[github-actions][client][iOS] Switch Xcode version to 12.1

### PR DESCRIPTION
**Pull request by bbarthec**
# Why

Followup of https://github.com/expo/expo/pull/10864 but for Expo Client

### CODE REVIEW

**Comment by ide** [comment]
Looks like there are some issues with the dynamic macros script:
```
2020-10-29T17:05:59.3725860Z +++++ awk '/EXECUTABLE DIRECTORY/ {print $4}'
2020-10-29T17:05:59.3727690Z /Users/runner/.rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/spec_set.rb:86:in `block in materialize': Could not find rake-13.0.1 in any of the sources (Bundler::GemNotFound)
2020-10-29T17:05:59.3729140Z 	from /Users/runner/.rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/spec_set.rb:80:in `map!'
2020-10-29T17:05:59.3730360Z 	from /Users/runner/.rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/spec_set.rb:80:in `materialize'
2020-10-29T17:05:59.3731570Z 	from /Users/runner/.rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/definition.rb:170:in `specs'
2020-10-29T17:05:59.3732800Z 	from /Users/runner/.rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/definition.rb:237:in `specs_for'
2020-10-29T17:05:59.3734050Z 	from /Users/runner/.rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/definition.rb:226:in `requested_specs'
2020-10-29T17:05:59.3735350Z 	from /Users/runner/.rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:101:in `block in definition_method'
2020-10-29T17:05:59.3736600Z 	from /Users/runner/.rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:20:in `setup'
2020-10-29T17:05:59.3737730Z 	from /Users/runner/.rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler.rb:149:in `setup'
2020-10-29T17:05:59.3739020Z 	from /Users/runner/.rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/setup.rb:20:in `block in <top (required)>'
2020-10-29T17:05:59.3740240Z 	from /Users/runner/.rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/ui/shell.rb:136:in `with_level'
2020-10-29T17:05:59.3741410Z 	from /Users/runner/.rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/ui/shell.rb:88:in `silence'
2020-10-29T17:05:59.3742600Z 	from /Users/runner/.rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/setup.rb:20:in `<top (required)>'
2020-10-29T17:05:59.3743710Z 	from /usr/local/Cellar/ruby/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
2020-10-29T17:05:59.3747150Z 	from /usr/local/Cellar/ruby/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
2020-10-29T17:05:59.3747950Z ++++ GEM_PATH=
2020-10-29T17:05:59.3748440Z Command PhaseScriptExecution failed with a nonzero exit code
2020-10-29T17:05:59.3748820Z 
2020-10-29T17:05:59.3751090Z warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.1.99. (in target 'FirebaseMLVisionFaceModel-GoogleMVFaceDetectorResources' from project 'FirebaseMLVisionFaceModel')
2020-10-29T17:05:59.3752750Z ** BUILD FAILED **
2020-10-29T17:05:59.3752930Z 
2020-10-29T17:05:59.3753090Z 
2020-10-29T17:05:59.3753410Z The following build commands failed:
2020-10-29T17:05:59.3755240Z 	PhaseScriptExecution Generate\ Dynamic\ Macros /Users/runner/work/expo/expo/ios/simulator-build/Build/Intermediates.noindex/Exponent.build/Release-iphonesimulator/Exponent.build/Script-78CEE2F21ACDF25E0095B124.sh
2020-10-29T17:05:59.3756780Z (1 failure)
```

**Comment by nicknovitski** [comment]
I am fixing this ruby/fastlane problem in #10900.

**Comment by bbarthec** [comment]
Dynamic Macros Script that is executed as in `Build Phases` is most probably failing because of missing `node` binary, but the logs are not showing this. One of the possible solution would be to get rid of this `Build Phase` all together as it can be/it is executed on CI as a separate step anyway.
Plase see https://github.com/expo/expo/pull/10907 for more info.

**Comment by sjchmiela** [comment]
As suggested on Slack and forwarded by @bbarthec here, I'd propose removing `| xcpretty` from XDL. It helped me debug an issue fixed in https://github.com/expo/expo/runs/1081335865.

To do this I added `patch-package` to `expotools`, like in this commit: https://github.com/expo/expo/commit/0a2fe9d46306009429c4d611c754b97856ecda4c

I think this is the time to fix the `xcpretty` problems and maybe use the _Raw `xcodebuild` option configuration_ described in [`xcpretty` README](https://github.com/xcpretty/xcpretty#raw-xcodebuild-output).

**Comment by ide** [comment]
It sounds like we need to do two things:

- Change how we use xcpretty in XDL. We may want to tee the logs to a file (treated as a CI artifact that can be downloaded for debugging) and through xcpretty to stdout.
- Get Xcode in CI to configure PATH so that Xcode can find `node`. We have some code that looks for shell config files (ex: bashrc). Perhaps that code needs to change.

**Pull request closed without merging**
