### PR TITLE
[ios][android] disable flipper in bare-expo

### PR DESCRIPTION
**Pull request by ajsmth**
# Why

The flipper plugin has caused some issues running locally:
- https://github.com/facebook/flipper/issues/2215 
- https://github.com/facebook/react-native/issues/31480

### CODE REVIEW

**Review by tsapeta — COMMENTED** [review]
Can't we just switch the `FB_SONARKIT_ENABLED` constant so that it is disabled in both schemes?

**Comment by ajsmth** [comment]
Is there some way to do this via Xcode? Or do I manually modify the `.pbxproj`

**Comment by tsapeta** [comment]
@ajsmth Click on the BareExpo project -> select BareExpo target -> Build Settings -> search for Preprocessor Macros -> click on the value under Debug configuration and remove `FB_SONARKIT_ENABLED=1` (you can compare it with `BareExpoDetox` target where it's already removed)

**Comment by ajsmth** [comment]
> @ajsmth Click on the BareExpo project -> select BareExpo target -> Build Settings -> search for Preprocessor Macros -> click on the value under Debug configuration and remove `FB_SONARKIT_ENABLED=1` (you can compare it with `BareExpoDetox` target where it's already removed)

I just tried this - Flipper modules are still being compiled and leading to build errors for Xcode 12.5

**Review by brentvatne — COMMENTED** [review]
i think the approach of commenting out the `use_flipper!` method is fine, but we should make it work without needing to comment out the code to set up flipper in source code - this is what we do in the bare ios template, for example.

**Comment by tsapeta** [comment]
> I just tried this - Flipper modules are still being compiled and leading to build errors for Xcode 12.5

@ajsmth you probably did sth wrong as it works in `BareExpoDetox` target already 😅

**Comment by ajsmth** [comment]
> i think the approach of commenting out the `use_flipper!` method is fine, but we should make it work without needing to comment out the code to set up flipper in source code - this is what we do in the bare ios template, for example.

updated the implementation to be more like what we have in bare iOS template - comment / uncomment Podfile to install flipper

**Comment by ajsmth** [comment]
> > I just tried this - Flipper modules are still being compiled and leading to build errors for Xcode 12.5
> 
> @ajsmth you probably did sth wrong as it works in `BareExpoDetox` target already 😅

for future reference - there were other references to FB_SONAR_ENABLED: 

Screen Shot 2021-07-09 at 12 22 08 PM
Screen Shot 2021-07-09 at 12 22 28 PM

although the implementation in this PR doesn't need to disable those

**Review by tsapeta — APPROVED** [review]

**Pull request merged**
