### PR TITLE
[docs] Remove private push notification API from docs and note web-only fields are not supported

### PR DESCRIPTION
**Pull request by ide**
The private fields that start with underscores are unstable and never should have been public, not because there is any issue with functionality or security but because we cannot commit to supporting the API and may change it at any time. Also marked the public web-only fields as unsupported.

Backported the changes to prior SDK docs.

Can add back by partially reverting this or looking at https://github.com/expo/expo/pull/4963 later.

### CODE REVIEW

**Comment by cruzach** [comment]
Do we want to remove ALL references to web push notifications in the SDK 36 docs? we have notes on uploading VAPID keys & additional config with Next

**Review by cruzach — COMMENTED** [review]
Do we want to remove ALL references to web push notifications in the SDK 36 docs? we have notes on uploading VAPID keys & additional config with Next

**Comment by ide** [comment]
None of it is actually supported so probably should remove or make a note not to try it.

**Comment by cruzach** [comment]
all gone besides `unversioned`, where you added the note that it's unsupported/subject to change anyways

**Comment by ide** [comment]
Removed more web notification references.

**Pull request merged**
