### PR TITLE
Fix _emitter is undefined

### PR DESCRIPTION
**Pull request by LorhanSohaky**
# Why
Fix FCM integration for web #10094 

# How
Checking that the emitter has not yet started

# Test Plan
Use the example at #10094

### CODE REVIEW

**Comment by brentvatne** [comment]
thanks! can you adjust it as per @sjchmiela's recommendation in https://github.com/expo/expo/pull/9823/files#r474914047?

**Comment by LorhanSohaky** [comment]
@brentvatne a internal function?

**Comment by LorhanSohaky** [comment]
@brentvatne, can this also be released for SDK 37?

**Review by sjchmiela — APPROVED** [review]
Looks good to me! Thank you for ensuring it's implemented fail-safe!

**Comment by jaxoncreed** [comment]
Has this been pushed to yet? I've updated to version `"expo": "^39.0.3"`, but I'm still seeing the old code.

**Comment by cruzach** [comment]
this has just been published @jaxoncreed, just update to `expo@39.0.4`

**Pull request merged**
