### PR TITLE
[docs] Create troubleshooting section

### PR DESCRIPTION
**Pull request by tcdavis**
# Why

We'd like to have a home for our troubleshooting guides findable in the docs site 

# How

Created the section under Managed workflow as this is the location for content relevant to both Managed and Bare workflows.
Moved existing faq pages.

# Test Plan

Ran with yarn dev and inspected result.

### CODE REVIEW

**Review by cruzach — CHANGES_REQUESTED** [review]
Since these troubleshooting pages are most likely to be found via search engines (most people aren't going to look in the sidebar for "Error: XXX"), I don't think we need to add more sidebar links, since it's already too many to really sort through 😅 

Could you add `"Troubleshooting"` to [`hiddenSections`](https://github.com/expo/expo/blob/master/docs/constants/navigation.js#L393)? That will hide it from the sidebar, but it will still be indexed for search (both search engines, and the internal docs search)

**Comment by tcdavis** [comment]
- Hid troubleshooting section
- Added pointers to existing troubleshooting docs from common development errors page

**Review by cruzach — CHANGES_REQUESTED** [review]
> Hid troubleshooting section

I don't think this was committed, still [just see `FAQ` there](https://github.com/expo/expo/blob/%40tc/troubleshooting-section/docs/constants/navigation.js#L393)

**Comment by tcdavis** [comment]
> > Hid troubleshooting section
> 
> I don't think this was committed, still [just see `FAQ` there](https://github.com/expo/expo/blob/%40tc/troubleshooting-section/docs/constants/navigation.js#L393)

😮  sorry about that, thanks!

**Review by cruzach — APPROVED** [review]
👍

**Pull request merged**
