### PR TITLE
[expo][config-types] make privacy manifest config strongly typed

### PR DESCRIPTION
**Pull request by SarjuHansaliya**
# Why

- Related to https://github.com/expo/expo/issues/27796
- It would be nice DX if `privacyManifests` config is strongly typed according to values provided by Apple instead of just string type.

Reference links:
- [Describing data use in privacy manifests](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_data_use_in_privacy_manifests)
- [Describing use of required reason API](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api)

# How

- Updated type for `privacyManifests` config under `@expo/config-types` package

# Test Plan

- I made sure that types I have added to `privacyManifests` reflects to app config under `apps` directory.

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [x] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Comment by aleqsio** [comment]
I'm a bit worried about the maintenance burden here, especially since apple says it will want to update those reasons periodically, but I do agree the UX improvement here would be quite nice.

**Comment by SarjuHansaliya** [comment]
@aleqsio I agree that there will be a modest amount of maintenance involved, but I believe this will substantially save developers numerous hours to go and search for correct type and reasons.

**Comment by SarjuHansaliya** [comment]
@tsapeta When you get a chance, can you please review this PR and provide your feedback ? TIA

**Comment by SarjuHansaliya** [comment]
@aleqsio is there anyway I can help fast forward this one ?

**Comment by brentvatne** [comment]
this file is generated from our schemas: https://exp.host/--/api/v2/project/configuration/schema/50.0.0 / https://github.com/expo/expo/blob/main/packages/%40expo/config-types/scripts/generate.ts - so we need to update the schema first and then pull it into here. unfortunately these schema files still live in our private server repo, so @aleqsio would need to take care of this

**Comment by SarjuHansaliya** [comment]
@brentvatne That make sense now. I was thinking why there is no changelog in `@expo/config-types` package.

**Comment by brentvatne** [comment]
hey @SarjuHansaliya - we appreciate this pr! we've decided that the maintenance work tradeoff here isn't something we're willing to take on at this particular moment, because any change in the future here would require us also backporting it to all older sdk versions. perhaps you could build a utility of some kind, cli or a website, that helps you create the config in this format?

**Pull request closed without merging**
