### PR TITLE
[router] Fix navigation when using browser back/forward

### LINKED ISSUE #29954: hash in useLocalSearchParams not working on loading a page
### Minimal reproducible example

https://github.com/nikgraf/expo-bug-reproduction

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

metro

### Summary

When I use ` const { '#': hash } = useLocalSearchParams<{ '#': string }>();` the `hash` value is not set when directly visiting the page.

In addition to that I noticed that `router.setParams({ '#': 'my-hash' })` doesn't overwrite the hash, but appends it.

I recored an example showing both cases:

https://github.com/expo/expo/assets/223045/f4e22087-6889-4a79-afff-09f1e8982597

How I setup the repository: I ran `npx create-expo-app@latest` and then added this one commit: https://github.com/nikgraf/expo-bug-reproduction/commit/4ae4f0207c604ef90a668dfd389b36d444bbda2e

### Environment

``` 
 expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.19.1 - ~/.nvm/versions/node/v18.19.1/bin/node
      Yarn: 1.22.22 - /usr/local/bin/yarn
      npm: 10.2.4 - ~/.nvm/versions/node/v18.19.1/bin/npm
    Managers:
      CocoaPods: 1.15.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
      Android SDK:
        Android NDK: 25.1.8937393
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.14 => 51.0.14 
      expo-router: ~3.5.16 => 3.5.16 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.2 => 0.74.2 
      react-native-web: ~0.19.10 => 0.19.12 
    npmGlobalPackages:
      eas-cli: 10.0.2
    Expo Workflow: managed
```

### LINKED ISSUE #31747: expo-router: doesn't restore state when using browser back/forward buttons
### Minimal reproducible example

npx create-expo-app@latest; npm run web

### What platform(s) does this occur on?

Web

### Where did you reproduce the issue?

on web

### Summary

https://www.loom.com/share/feae2f6b331a4f3cb9951633b3f7cf70

This issue repros on web if you create the Expo starter project via npx create-expo-app@latest

Repro steps:
1. Load the app in a web browser
2. Click the "Explore" tab at the bottom
3. Click the browser's back button
4. Click the browser's forward button

Expected: you should be back on the Explore tab

Actual: you're still on the home page, and there's this error in the console:

```
The action 'RESET' with payload {"stale":false,"type":"stack","key":"stack-89f_vt6bznNwe8ZDmp0mR","index":0,"routeNames":["(tabs)","+not-found","_sitemap"],"routes":[{"name":"(tabs)","state":{"stale":false,"type":"tab","key":"tab-Ecfq_pT2uRroKfUj4Po-9","index":1,"routeNames":["index","explore"],"history":[{"type":"route","key":"index-dvBVUdqMOoqRmecNnOOhN"},{"type":"route","key":"explore-UpUnmnhhbnvqR2dlmlgQn"}],"routes":[{"name":"index","path":"/","key":"index-dvBVUdqMOoqRmecNnOOhN"},{"name":"explore","key":"explore-UpUnmnhhbnvqR2dlmlgQn"}]},"key":"(tabs)-qAmiwyZ8AwBcDAYrlGgYK"}]} was not handled by any navigator.
```

There is this issue from react-navigator which might have a clue on the fix: https://github.com/react-navigation/react-navigation/issues/9128

Someone in that thread said:

>  I was experiencing the same issue hitting back to the initial screen. My fix was to stop setting initialState on web as described in https://reactnavigation.org/docs/navigation-container/#initialstate

### Environment

```text
expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.6.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.10.0 - ~/.local/bin/node
      npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
      Watchman: 2024.05.06.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Android Studio: 2024.1 AI-241.18034.62.2411.12071903
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.28 => 51.0.34
      expo-router: ~3.5.23 => 3.5.23
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.74.5 => 0.74.5
      react-native-web: ~0.19.10 => 0.19.12
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check if the project meets version requirements for submission to app stores
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!
```

### PR DESCRIPTION
**Pull request by stephentuso**
# Why

Fix: #31747 

# How

This issue started after the fork of `createMemoryHistory` [here](https://github.com/expo/expo/pull/29990/files#diff-8e22bc1cd48d45e4074c0042c548120fde9c1d8af547e622f464579d9f0f3ef9). The logic that was commented out is necessary to prevent the state from breaking.

I was thinking we may want to just switch back to importing that function directly from `@react-navigation/native`, but doing so breaks e2e tests because it isn't included in react navigation's package `exports` (due to `Experimental module resolution is enabled`? I'm not familiar with that yet).

So due to the import issue I just updated the fork of `createMemoryHistory` to match [react-navigation](https://github.com/react-navigation/react-navigation/blob/66cc899e2d9264903ed8800980711c619bb3b499/packages/native/src/createMemoryHistory.tsx).

It was originally forked to fix [this issue](https://github.com/expo/expo/issues/29954), but I confirmed the e2e tests added for that are still passing. I didn't look too deeply but I think this is due to the hash being handled correctly [here](https://github.com/expo/expo/blob/91392d8a29727ffce35eaaeedb7b86f0ae174fb1/packages/expo-router/src/fork/getPathFromState.ts#L300) now.

The only upstream change since the fork was [this](https://github.com/react-navigation/react-navigation/pull/11876/files#diff-a26254cf49ae583ad492ff076aa1cd374edb4bb7071618aecfffa38e8e2f1230), which also seems to relate to not duplicating the hash. The main changes of that PR were in `useLinking` which we have already updated. I also added an e2e on our end to cover the issue mentioned in that PR.

While working on this I found a new issue relating to navigating to a URL with both the hash and query parameters set, but I confirmed it wasn't introduced by this and I'll open a new ticket for that.

# Test Plan

Added breaking e2e test and then fixed issue

# Checklist

- [x] I added a `changelog.md` entry and rebuilt the package sources according to [this short guide](https://github.com/expo/expo/blob/main/CONTRIBUTING.md#-before-submitting)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)

### CODE REVIEW

**Review by marklawlor — APPROVED** [review]

**Comment by ericlyoung** [comment]
THIS IS NOT FIXED

**Comment by marklawlor** [comment]
@ericlyoung The fix hasn't been released yet, but has been merged in to the `sdk-52` branch and will be in the next release. This issue was closed automatically by github as a PR that referenced this issue was merged into `main`. But we still need to test on `main` before we add it to the SDK release

**Comment by joernroeder** [comment]
experiencing this issue locally and found this issue. I'm on expo-router: 4.0.17

**Comment by VariabileAleatoria** [comment]
why bo backporting to v3?

**Pull request merged**
