### PR TITLE
[expo-local-authentication] add fallbackLabel option to the docs

### PR DESCRIPTION
**Pull request by changLiuUNSW**
# Why

update doc for changes

https://github.com/expo/expo/pull/4612

### CODE REVIEW

**Comment by changLiuUNSW** [comment]
@tsapeta

**Comment by tsapeta** [comment]
Thanks you for your PRs! I've applied some (breaking, but with temporary backwards compatibility just for one SDK ahead) changes after merging the previous one and added all of these changes to the docs - so I need to close this PR because it is no longer up to date. See #4631.

Also, I can't add these changes into SDK33 directly as it's a new feature and not a bugfix, however if I remember correctly, your app is ejected so I'd be able to release only the `expo-local-authentication` package as a prerelease version. Let me know if this would help you 😉

**Comment by changLiuUNSW** [comment]
I'd be able to release only the expo-local-authentication package as a prerelease version

Yes, please

**Comment by tsapeta** [comment]
Published as `6.0.0-rc.0`, feel free to test it in ejected app 😉

**Comment by changLiuUNSW** [comment]
@tsapeta I just tried ```"expo-local-authentication": "^6.0.0-rc.0" ``` in my project with Expo 33, but I got this error in EXScopedLocalAuthentication when building the app in XCode.
Screen Shot 2019-07-09 at 10 50 19 pm

**Comment by changLiuUNSW** [comment]
Just find out in https://github.com/expo/expo/pull/4631/files
ios/Exponent/Versioned/Core/UniversalModules/EXScopedLocalAuthentication.m get updated.
It means we cannot use it without upgrading ExpoKit and hence cannot be used in Expo 33

**Pull request closed without merging**
