### PR TITLE
[docs] Upgrade docs to Next 9.5

### PR DESCRIPTION
**Pull request by byCedric**
# Why

This is the "light" version of #10075 and only includes the necessary changes for Next 9.5.

# How

1. Upgraded to Next 9.5+ using the [upgrade guide](https://nextjs.org/docs/upgrading).
2. Moved `static` and `robots.txt` to `public/` to use [new public folder support](https://nextjs.org/blog/next-9-1#public-directory-support).
3. Replaced `/api/` page redirect with `pages/_error` redirect, to [avoid Next handling it as API endpoint](https://nextjs.org/docs/api-routes/introduction).
4. Added workaround for the exported 404-fallback issue when [using `trailingSlash` config](https://github.com/vercel/next.js/issues/16528). → _note: once this is fixed, we can remove the fallback workaround from `package.json`_

# Test Plan

- Run the docs locally with `$ yarn export && yarn export-server` _(validates 1)_
- Check if the robots and static files are returned _(validates 2)_
- Check if the path `/api` still redirects to `/versions/latest` _(validates 3 and 4)_
- Check if both with and without trailing slashes resolves the page on S3
- Run `$ yarn test-links`, while `$ yarn export-server` is running, to validate the redirects
- Run `$ yarn test` to perform the unit tests on components

### CODE REVIEW

**Comment by byCedric** [comment]
The timeout is expected, this doesn't change anything about the performance. Please double-check the testing plan to validate if the change is working as expected.

**Review by ide — APPROVED** [review]
One thing we should verify is that both https://docs.expo.io/tutorial/image/ and https://docs.expo.io/tutorial/image work (with and without the trailing slash; I just picked two pages at random).

Other than that, looks good.

**Comment by byCedric** [comment]
I can confirm both `/tutorial/image/` and `/tutorial/image` works with both `$ yarn dev` and `$ yarn export-server`. I still have to test it on S3, so I'll go ahead and test it in my own bucket first 😄

**Comment by ide** [comment]
If you find that testing it on your own bucket is too time-consuming, I think it's fine to deploy and test. We can always roll back and this isn't likely to be very disruptive.

**Comment by byCedric** [comment]
Oh no, that's fine. I think it's better to test these kinds of changes in a separate staging environment anyways. I did that and it looks like everything is working as expected (even the `/api` and `/api/` redirects 😄)

- http://cedrics-expo.s3-website.eu-central-1.amazonaws.com/
- http://cedrics-expo.s3-website.eu-central-1.amazonaws.com/versions/latest
- http://cedrics-expo.s3-website.eu-central-1.amazonaws.com/tutorial/image

I'm going to merge this PR! 😄

**Comment by ide** [comment]
Nice work!

**Pull request merged**
