### PR TITLE
[media-library] Refactor to Kotlin 5 - Utilities

### PR DESCRIPTION
**Pull request by barthap**
# Why, How etc...

See #14562 description for details.

**_Please review fff07e2 separately - I'm totally unsure about the best way_**

---

This is part of a PR stack:

1. #14562
2. #14563
3. #14564
4. #14565
5. **This PR** - rewritten rest of `MediaLibraryUtils` and `MediaLibraryConstants` to Kotlin
6. Coroutines + refactor error handling (No PR yet)

### CODE REVIEW

**Review by barthap — COMMENTED** [review]
I'm not sure about a few things - suggestions welcome 🙂 

Please take a look at commit fff07e2 separately

**Review by kkafar — COMMENTED** [review]
Good job

**Review by lukmccall — APPROVED** [review]
LGTM ✅

**Review by mstach60161 — APPROVED** [review]
👍👍👍

**Pull request merged**
