### PR TITLE
[web-browser] Fix `removeSubscription()` deprecation warnings

### LINKED ISSUE #17559: expo-web-browser: AppState.removeListener('change', ...): Method has been deprecated
### Summary

`expo-web-browser`
On web, the following warning message surfaces when `openAuthSessionAsync()` in `ExpoWebBrowser.web.ts` is invoked. Additionally, on Expo Go (Android, iOS) this same warning message surfaces from `_stopWaitingForRedirect()` in `WebBrowser.ts`

```
AppState.removeListener('change', ...): Method has been deprecated. Please instead use `remove()` on the subscription returned by `AppState.addEventListener`.
```

The event listeners should be updated to use `.remove()` instead of the deprecated `.removeEventListener()`
This issue is related to #16376

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS, Web

### SDK Version (managed workflow only)

45

### Environment

```
  expo-env-info 1.0.3 environment info:
    System:
      OS: Linux 5.14 Ubuntu 20.04.4 LTS (Focal Fossa)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 16.10.0 - /usr/local/bin/node
      Yarn: 1.22.18 - /usr/local/bin/yarn
      npm: 8.3.0 - /usr/local/bin/npm
    npmPackages:
      @expo/webpack-config: ~0.16.2 => 0.16.24 
      expo: ~45.0.0 => 45.0.4 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
    npmGlobalPackages:
      eas-cli: 0.50.0
      expo-cli: 5.0.3
    Expo Workflow: managed
```

### Reproducible demo

I ran into this error when running [this standard Google Authentication sample code](https://docs.expo.dev/guides/authentication/#web-apps) from the Expo docs.

I created a mini demo that directly invokes `WebBrowser.openAuthSessionAsync()` since that is what `promptAsync()` from the `Google.useAuthRequest()` hook uses. I was unable to reproduce the console warnings via Snack but is reproducible on my local Linux machine.
Copy this demo code to your local environment, run web or mobile, click the button. A popup window will appear. Close the popup window. Observe the deprecation warnings in your terminal.
https://snack.expo.dev/@alberm/expo-web-browser-test

I went ahead and forked the repo to fix this issue myself. Here is my proposed solution. I can create a pull request if this issue does not already have a solution in the works.
https://github.com/expo/expo/compare/main...alberme:%40alberme/fix/web-browser-eventListener-deprecation

### LINKED ISSUE #17639: EventEmitter.removeListener('url', ...): Method has been deprecated
### Summary

EventEmitter.removeListener('url', ...): Method has been deprecated. Please instead use `remove()` on the subscription returned by `EventEmitter.addListener`.
at node_modules/react-native/Libraries/vendor/emitter/_EventEmitter.js:164:4 in EventEmitter#removeListener
at node_modules/react-native/Libraries/EventEmitter/NativeEventEmitter.js:108:4 in removeListener
at node_modules/react-native/Libraries/Linking/Linking.js:57:4 in removeEventListener
at node_modules/expo-web-browser/build/WebBrowser.js:354:4 in _stopWaitingForRedirect
at node_modules/expo-web-browser/build/WebBrowser.js:347:31 in _openAuthSessionPolyfillAsync

`expo-auth-session`

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS, Web

### SDK Version (managed workflow only)

_No response_

### Environment

  expo-env-info 1.0.3 environment info:
    System:
      OS: Linux 5.15 Ubuntu 22.04 LTS 22.04 LTS (Jammy Jellyfish)
      Shell: 5.1.16 - /bin/bash
    Binaries:
      Node: 16.15.0 - /usr/bin/node
      Yarn: 1.22.19 - /usr/bin/yarn
      npm: 8.5.5 - /usr/bin/npm
    npmPackages:
      expo: ~45.0.0 => 45.0.4 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
    npmGlobalPackages:
      eas-cli: 0.52.0
      expo-cli: 5.4.6
    Expo Workflow: managed

### Reproducible demo

login by auth0 using `expo-auth-session`

### PR DESCRIPTION
**Pull request by barthap**
# Why

Fixes #17559 
Fixes #17639

# How

- Replaced `_redirectHandler` with an `EmitterSubscription` object and `Linking.removeSubsctiption(...)` with `subscription.remove()`
- Did the same with `appStateListener` in the web implementation

# Test Plan

- [x] NCL/TestSuite openAuthSession on Android
- [x] NCL/TestSuite on Web

### CODE REVIEW

**Review by bbarthec — APPROVED** [review]
LGTM 👍

**Comment by barthap** [comment]
Until this fix is published on npm, you can use patch-package to apply it locally

**Comment by barthap** [comment]
You can download the diff from here: https://patch-diff.githubusercontent.com/raw/expo/expo/pull/17645.diff but you need to replace all `packages/expo-web-browser/` paths with `node_modules/expo-web-browser/`, then save it as text file named: `your_repo/patches/expo-web-browser+10.2.1.patch`, where `10.2.1` should be your actual `expo-web-browser` version (i guess it's that version but you can double check it with e.g. `yarn why expo-web-browser`).
Then run `npx patch-package` and your patch should be applied.

**Comment by julian-hecker** [comment]
Sorry to ask, but when could we expect this fix to be published? looks like it was merged a month ago.

**Comment by barthap** [comment]
Most likely with SDK 46, but there's a small chance that it might be a little sooner. But you can always use a patch-package as I suggested above

**Comment by wasupak** [comment]
> You can download the diff from here: https://patch-diff.githubusercontent.com/raw/expo/expo/pull/17645.diff but you need to replace all `packages/expo-web-browser/` paths with `node_modules/expo-web-browser/`, then save it as text file named: `your_repo/patches/expo-web-browser+10.2.1.patch`, where `10.2.1` should be your actual `expo-web-browser` version (i guess it's that version but you can double check it with e.g. `yarn why expo-web-browser`). Then run `npx patch-package` and your patch should be applied.

Any more step ? 
1. Download Diff
2. use text editor , replace string  `packages/expo-web-browser/` with `node_modules/expo-web-browser/`
3. save as /patches/expo-web-browser+10.2.1.patch
4. npx patch-package

I got this error ...

patch-package 6.4.7
Applying patches...

**ERROR** Failed to apply patch for package expo-web-browser at path

    node_modules/expo-web-browser

  This error was caused because patch-package cannot apply the following patch file:

    patches/expo-web-browser+10.2.1.patch

  Try removing node_modules and trying again. If that doesn't work, maybe there was
  an accidental change made to the patch file? Try recreating it by manually
  editing the appropriate files and running:

    patch-package expo-web-browser

  If that doesn't work, then it's a bug in patch-package, so please submit a bug
  report. Thanks!

    https://github.com/ds300/patch-package/issues


---
patch-package finished with 1 error(s).

**Comment by barthap** [comment]
There must've arisen some difference between this diff and the package in the meantime.

> ERROR Failed to apply patch for package expo-web-browser at path
> 
> `node_modules/expo-web-browser`
> This error was caused because patch-package cannot apply the following patch file:
> 
> `patches/expo-web-browser+10.2.1.patch`
> 
> Try removing `node_modules` and trying again. If that doesn't work, maybe there was
> an accidental change made to the patch file? **Try recreating it by manually
> editing the appropriate files and running:**
> 
> `patch-package expo-web-browser`

This error message is telling you exactly what to do (I emphasized it with **bold**)

**Comment by wasupak** [comment]
> There must've arisen some difference between this diff and the package in the meantime.
> 
> > ERROR Failed to apply patch for package expo-web-browser at path
> > `node_modules/expo-web-browser`
> > This error was caused because patch-package cannot apply the following patch file:
> > `patches/expo-web-browser+10.2.1.patch`
> > Try removing `node_modules` and trying again. If that doesn't work, maybe there was
> > an accidental change made to the patch file? **Try recreating it by manually
> > editing the appropriate files and running:**
> > `patch-package expo-web-browser`
> 
> This error message is telling you exactly what to do (I emphasized it with **bold**)

Sorry my mistake, just first time to patch.
Try again with command 

npx patch-package expo-web-browser

Command work now, but seem nothing happen.

patch-package 6.4.7
• Creating temporary folder
• Installing expo-web-browser@10.2.1 with npm
• Diffing your files with clean files
⁉️  Not creating patch file for package 'expo-web-browser'
⁉️  There don't appear to be any changes.

----------

Is this patch apply for expo-auth-session too ?
Do I need to npm install expo-web-browser to apply this patch ?

I just use expo-auth-session 3.6.1 and got warning EventEmitter.removeListener('url', ...): Method has been deprecated....
(Android only, no warning in iOS)

**Comment by jamesst20** [comment]
[expo-web-browser+10.2.1.patch.zip](https://github.com/expo/expo/files/9174027/expo-web-browser%2B10.2.1.patch.zip)

Here is the patch I had to use to make it work

**Pull request merged**
