### PR TITLE
[docs] add `autoIncrement` option at the root of the build profile

### PR DESCRIPTION
**Pull request by szdziedzic**
# Why

Update code snippets related to https://github.com/expo/eas-cli/pull/1298 (use `autoIncrement` option at the root of the build profile instead of using `autoIncrement` option under platform-specific keys.
Reverts https://github.com/expo/expo/commit/e84ed45541da17f668c51db9ff63b9eaa1d27ed5.
[ENG-6029](https://linear.app/expo/issue/ENG-6029/support-autoincrement-at-root-of-build-profile)

# How

Use `autoIncrement` option at the root of a build profile in code snippets.

# Test Plan

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Review by Simek — APPROVED** [review]
LGTM, thank you for the docs update! 👍

**Comment by wkozyra95** [comment]
You also need to add that field here https://docs.expo.dev/build-reference/eas-json/

https://github.com/expo/expo/blob/main/docs/scripts/schemas/unversioned/eas-json-build-common-schema.js

**Review by dsokal — APPROVED** [review]

**Comment by szdziedzic** [comment]
@wkozyra95 It's added now

**Review by brentvatne — APPROVED** [review]

**Comment by kbrandwijk** [comment]
@szdziedzic I don't think the root level description is correct. According to the eas-cli PR, it supports 'true' or 'version', in the docs it is listed as boolean that only supports 'true', and the description only mentions the versionCode/buildNumber behavior.

**Comment by szdziedzic** [comment]
I'm so sorry @kbrandwijk I forgot to update the description of PR in `eas-cli` project after changing possible values for `autoIncrement` at the root level from the `boolean | 'version'` to only `boolean`. It should be fixed now.

**Comment by szdziedzic** [comment]
The `autoIncrement` option at the root level only handles `boolean` in the current version, so docs should be correct. Please, let me know if you have more questions 🙂

**Comment by kbrandwijk** [comment]
Ah, that makes sense now. My comment was just based on reading the eas-cli PR description, but as long as it matches the implementation, all is fine by me. Thanks for clarifying!

**Pull request merged**
