### PR TITLE
[expo-notifications] Aligned return type based on PermissionStatus possible values

### PR DESCRIPTION
**Pull request by cHaLkdusT**
# Why
Possible returned values from native iOS does not match declared TypeScript enum

# How
TypeScript defines `PermissionResponse.status: PermissionStatus`, however, the actual data type value for `status` returns number and because of that, ESLint gives a warning message.

Previously, we check the status using number equivalent
code

With this fix, we are guaranteed that `status` will return either ['denied', 'granted', 'undetermined']
code2

# Test Plan
* Updated unit-test
* Tested NotificationScreen, the Alert dialog now shows `Status: granted` instead of `Status: 1`

### CODE REVIEW

**Review by sjchmiela — CHANGES_REQUESTED** [review]
Thank you very much for taking the time to fix this issue!

Unfortunately I'm afraid I have to guide you to a different solution — while the proposed one solves the issue for `requestPermissionsAsync` it breaks the code when `getPermissionsAsync` is called. If you compare implementations of

https://github.com/expo/expo/blob/483db655aee826a564f7fbf5626ec8a1afcc5d08/packages/expo-notifications/ios/EXNotifications/Permissions/EXNotificationPermissionsModule.m#L43-L49

and

https://github.com/expo/expo/blob/483db655aee826a564f7fbf5626ec8a1afcc5d08/packages/expo-notifications/ios/EXNotifications/Permissions/EXNotificationPermissionsModule.m#L33-L41

you will see that `getPermissionsAsync` uses `UMPermissionsMethodsDelegate` to get the permissions, but while `requestPermissionsAsync` calls the `_requester` directly — there's our bug!

Proper solution to this issue would be to change the implementation of `requestPermissionsAsync` so it uses `UMPermissionsMethodsDelegate`, similar to:

https://github.com/expo/expo/blob/5dcabadf151eecba599eae2da6a72fbad8a6befe/packages/expo-media-library/ios/EXMediaLibrary/EXMediaLibrary.m#L109-L117

Would you care to change your PR accordingly?

**Comment by cHaLkdusT** [comment]
Gotcha! Thanks for reviewing this pull request @sjchmiela. I have now reverted the initial code and applied your recommendation. Would you be able to review it again?

**Review by sjchmiela — APPROVED** [review]
Now this looks great! I'll let myself also ask @lukmccall for an opinion. 🙂 

I have a bad feeling I don't know why I've used the requester directly instead of using `UMPermissionsMethodsDelegate`… I hope this doesn't break anything… 😃

**Comment by lukmccall** [comment]
@sjchmiela, I think I know why you used the requester directly 😅 Writing it in that way, you bypass the scoping in the `expo-client`. I'm not sure why would you want to do that 😜 but that's the only thing that comes to my mind.


This fix should be relatively safe to merge because in the `EXScopedPermissions` we don't scope `notification` permission anyway - see https://github.com/expo/expo/blob/c255aee5170bd594a767b0b47097aeb7863c6a28/ios/Exponent/Versioned/Core/UniversalModules/Permissions/EXScopedPermissions.m#L162-L166.

**Review by lukmccall — APPROVED** [review]
LGTM 🚀🚀🚀

**Review by sjchmiela — APPROVED** [review]
Thank you @lukmccall for your great memory! It would indeed break asking for notifications permissions in Expo client if only we haven't fixed it already in https://github.com/expo/expo/commit/096a701bb60cc446b45aa7c0b67b5d4f5f2253cd:
> - since new notification permission requesters now may return `null` inside the permission response I had to either:
>    - add support for `NSNull` in `EXPermissionsManager` (it is returned by the user notifications permissions requester)
>    - exclude `notifications` and `userFacingNotifications` from being saved to kernel service since we don't scope them even so (thanks @lukmccall for the tip!)

Thank you @cHaLkdusT for taking care of it! 💯

**Pull request merged**
