### PR TITLE
Fix broken link in Expo's Webview docs

### PR DESCRIPTION
**Pull request by codinsonn**
# Why

The link in the following section of the Expo docs is broken:
https://docs.expo.dev/versions/latest/sdk/webview/#usage

Screenshot 2022-10-25 at 16 25 53

Screenshot 2022-10-25 at 16 26 15

# How

Replace the link url's `Guide.mdx` reference with `Guide.md` instead

```suggestion
https://github.com/react-native-webview/react-native-webview/blob/master/docs/Guide.mdx#react-native-webview-guide
https://github.com/react-native-webview/react-native-webview/blob/master/docs/Guide.md#react-native-webview-guide
```

# Test Plan

Preview change in (vscode) Markdown preview, click on `[react-native-webview docs](https://github.com/react-native-community/react-native-webview/blob/master/docs/Guide.md#react-native-webview-guide)` to see that the link is no longer broken

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [x] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Review by Simek — APPROVED** [review]
Hello @codinsonn, nice catch, thank you for the fix, LGTM! 👍

**Comment by Simek** [comment]
Btw. Can you backport this change to the versioned (older) docs? You can find the file for other versions here:
* https://github.com/expo/expo/tree/main/docs/pages/versions

It can be done in the separate PR if you like, also if you don't have a time for that just LMK, then I will follow up on this PR.

**Comment by codinsonn** [comment]
@Simek sure, no problem, I'll have a look in a separate PR right now ⏳

**Comment by codinsonn** [comment]
@Simek Backports available in https://github.com/expo/expo/pull/19702 🎉

**Pull request merged**
