### PR TITLE
[docs] Restore snack links for custom fonts guide

### PR DESCRIPTION
**Pull request by IjzerenHein**
# Why

Using custom fonts with snack has been fixed and released. Update our docs so ppl can use snack to demonstrate and play with custom fonts.

# How

- Adds inline snack
- Upgrades ccheevers snacks to SDK 37

# Test Plan

- Verified that embedded snacks are working
- Verified that inline snack is working
- Looked good to me

### CODE REVIEW

**Comment by byCedric** [comment]
Once SDK 38 lands, we might want to switch from:

```
import { useFonts } from '@use-expo/font';
```

to

```
import { useFonts } from 'expo-fonts';
```

Code is landed, docs about this hook is created in `unversioned`. It's only waiting for the release 😄

**Review by brentvatne — APPROVED** [review]
thanks!

one thing i'd love to see with snack embeds is support for specifying external assets. i think it's always preferable to keep the source code for the examples in the docs so that people can easily submit prs to fix and we don't bind the examples to a specific user-id/slug

```
<SnackInline
  label="Font"
  dependencies={["expo-font"]}
  assets={{ "assets/fonts/Inter-Black.otf": "path/to/Inter-Black.otf" }}
>
  /* code here */
</SnackInline>
```

**Comment by IjzerenHein** [comment]
> thanks!
> 
> one thing i'd love to see with snack embeds is support for specifying external assets. i think it's always preferable to keep the source code for the examples in the docs so that people can easily submit prs to fix and we don't bind the examples to a specific user-id/slug
> 
> ```
> <SnackInline
>   label="Font"
>   dependencies={["expo-font"]}
>   assets={{ "assets/fonts/Inter-Black.otf": "path/to/Inter-Black.otf" }}
> >
>   /* code here */
> </SnackInline>
> ```

Yep, definitely!

**Comment by IjzerenHein** [comment]
@byCedric Snack is now using SDK 38 by default. I've updated the `useFonts` example to use the hook from `expo-font`. Could you verify that is okay?

**Comment by byCedric** [comment]
Looks good on my OnePlus 6, but when I use Appetize I get a weird error that "useFonts" is not a function (maybe related to Expo client version?).

Also the Snack https://snack.expo.io/@ijzerenhein/custom-font-example doesn't import the hook from `expo-font`, maybe we should do that for the sake of simplicity 😄

**Review by byCedric — APPROVED** [review]

**Comment by IjzerenHein** [comment]
Thanks for checking this out, I'll have a look at both issues 👍

**Comment by IjzerenHein** [comment]
Fixed the snacks by upgrading them to sdk 38

**Pull request merged**
