### PR TITLE
[docs] Managed EAS Build

### PR DESCRIPTION
**Pull request by brentvatne**

### CODE REVIEW

**Comment by brentvatne** [comment]
@axeldelafosse - looks like maybe a webpack 5 related docs failure again - yarn export worked fine on my local machine

**Comment by axeldelafosse** [comment]
I tried to re-run the action and got a timeout. Webpack 5 now takes more time to export: https://github.com/expo/expo/pull/12633

**Comment by axeldelafosse** [comment]
We might also run out of memory. We could add a [self-hosted runner](https://docs.github.com/en/actions/hosting-your-own-runners/adding-self-hosted-runners) with more RAM but it is not recommended for open-source repository.

**Comment by axeldelafosse** [comment]
OK this one should help too: https://github.com/expo/expo/pull/12637

**Comment by axeldelafosse** [comment]
@brentvatne this issue is fixed now!

**Pull request merged**
