### PR TITLE
Update image-picker.md

### PR DESCRIPTION
**Pull request by asabahebwa**
This pull request is aimed at fixing a typo on line 26 where you say `to install the a version of` instead of `to install a version of`

# Why

Please describe the motivation for this PR, and link to relevant GitHub issues, forums posts, or feature requests.

# How

How did you build this feature or fix this bug and why?

# Test Plan

Please describe how you tested this change and how a reviewer could reproduce your test, especially if this PR does not include automated tests! If possible, please also provide terminal output and/or screenshots demonstrating your test/reproduction.

### CODE REVIEW

**Comment by cruzach** [comment]
thanks! can you make the same change to the `unversioned` docs?

**Comment by ahebwa49** [comment]
> thanks! can you make the same change to the `unversioned` docs?

How do I access those `unversioned` docs?

**Comment by cruzach** [comment]
https://github.com/expo/expo/blob/master/docs/pages/versions/unversioned/tutorial/image-picker.md

**Comment by IjzerenHein** [comment]
@cruzach Tutorials are not versioned, so it doesn't exist in `unversioned`.

**Review by IjzerenHein — APPROVED** [review]
Looks good to me

**Comment by cruzach** [comment]
they were versioned back when this PR was created (that's why this PR is targeting `docs/pages/versions/v36.0.0/tutorial/image-picker.md ` file rather than `expo/docs/pages/tutorial/image-picker.md`)

this PR is superseded by https://github.com/expo/expo/commit/f793f2836062d7734ffc12aebc6e73a9fcf0c9b7

**Comment by IjzerenHein** [comment]
> they were versioned back when this PR was created (that's why this PR is targeting docs/pages/versions/v36.0.0/tutorial/image-picker.md file rather than expo/docs/pages/tutorial/image-picker.md)

Silly me, yep you're totally right 👍

**Pull request closed without merging**
