### PR TITLE
[expo-media-library] Add isNetworkAsset flag to ios

### PR DESCRIPTION
**Pull request by jarvisluong**
# Why & How

Mentioned in https://github.com/expo/expo/issues/8541

# Test Plan

With a real device, make huge asset so that iCloud delete the local version, then open the test app and select that asset

### CODE REVIEW

**Comment by jarvisluong** [comment]
One thing I just noticed that the key `PHImageResultIsInCloudKey` and `PHContentEditingInputResultIsInCloudKey` is only present if we make `networkAccessAllowed` to `NO` like in here:

https://github.com/expo/expo/blob/e166a8d8b72263a5ab75f04871e7a5d2da9729e9/packages/expo-media-library/ios/EXMediaLibrary/EXMediaLibrary.m#L407

However, setting that flag to `NO` won't download the iCloud asset to the device, so we would need to fetch first with `NO` value, then again with `YES` for the asset to be downloaded.

**Review by lukmccall — COMMENTED** [review]
> Otherwise, we would need to make the method `getAssetInfoAsync` to be more configurable in JS side (in order to dynamically specify `PHContentEditingInputRequestOptions` and `PHVideoRequestOptions`

I believe that is the best option - I don't like making two calls for the asset. 
Nevertheless, please update the documentation ;)

**Comment by tsapeta** [comment]
Yeah, I agree that making it more configurable is a good idea 👍

Does it also mean that `PHContentEditingInputResultIsInCloudKey` is not available when `networkAccessAllowed` is set to `YES`? What's its value then? We need to make sure it's not `nil` because it would throw an exception when converting it to JS object. We would need to use `[NSNull null]` instead of `nil`.

**Comment by jarvisluong** [comment]
> Yeah, I agree that making it more configurable is a good idea 👍
> 
> Does it also mean that `PHContentEditingInputResultIsInCloudKey` is not available when `networkAccessAllowed` is set to `YES`? What's its value then? We need to make sure it's not `nil` because it would throw an exception when converting it to JS object. We would need to use `[NSNull null]` instead of `nil`.

You are right, the value will be nil

**Comment by jarvisluong** [comment]
I started working on an updated PR, hence closing this one

**Pull request closed without merging**
