### PR TITLE
[notifications] Export NotificationPermissions.types

### PR DESCRIPTION
**Pull request by brentvatne**
# Why

[This example code from the README](https://github.com/expo/expo/tree/master/packages/expo-notifications#examples-5) currently results in `[TypeError: undefined is not an object (evaluating 'Notifications.IosAuthorizationStatus.PROVISIONAL')]`: 

```js
import * as Notifications from 'expo-notifications';

export async function allowsNotificationsAsync() {
  const settings = await Notifications.getPermissionsAsync();
  return (
    settings.granted || settings.ios?.status === Notifications.IosAuthorizationStatus.PROVISIONAL
  );
}
```

# How

Exported `NotificationPermissions.types` from `index.ts` and added a simple check to verify that `Notifications.IosAuthorizationStatus` is defined when importing from `expo-notifications` entry point to prevent regression in the future.

# Test Plan

Run test included in PR, run the code provided in the "Why" section above.

### CODE REVIEW

**Review by sjchmiela — APPROVED** [review]
Thank you very much! Would you care to add a changelog entry for this, please? 🙏

**Review by sjchmiela — APPROVED** [review]
10q! 🙏

**Comment by hassey13** [comment]
whats the fix for this, I have this issue currently?

**Comment by benhjames** [comment]
Could do this in the meantime:

```tsx
import * as Notifications from "expo-notifications";
import { IosAuthorizationStatus } from "expo-notifications/build/NotificationPermissions.types";

export async function allowsNotificationsAsync() {
  const settings = await Notifications.getPermissionsAsync();
  return (
    settings.granted || settings.ios?.status === IosAuthorizationStatus.PROVISIONAL
  );
}
```

**Comment by brentvatne** [comment]
@hassey - this should be included in the latest release, at the time of writing expo-notifications@0.6.0

**Pull request merged**
