### PR TITLE
[docs] no more migrators from expo build

### PR DESCRIPTION
**Pull request by quinlanj**
# Why

Are people still migrating from classic builds? It's been so long since we've shut it off, it may be better off archived.

# How
 - move expo build migration to archive
 - add redirects to archive

# Test Plan

- [ ] manually inspected

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Review by amandeepmittal — COMMENTED** [review]
Instead of migrating it to `/classic-updates/`, I'd suggest archiving this doc under Classic Builds.

CleanShot 2024-02-07 at 14 05 51@2x

I know this deprecated doc contains info about page but the main focus I think is `expo build` to EAS Build.

**Comment by quinlanj** [comment]
Also can someone confirm that we actually do want to deprecate this doc

**Comment by amandeepmittal** [comment]
> @amandeepmittal one weird thing i noticed is that all builds documents are under the `classic-updates` folder and there is no `classic-builds` folder (now that you mention it, that's probably not intended?)
> 
> https://github.com/expo/expo/blob/b6ff87f7ba7e7a1c25b42aee4c1a8a4060ea1421/docs/constants/navigation.js#L474-L477
> 
> What do you think about this plan:
> 
> * In this PR, we can make the `classic-builds` folder and move the article there
> * in a followup pr, we could move everything else that was incorrectly classified under `classic-updates` to `classic-builds`. Happy to do it, if you'd like :)

This sounds perfect! Apologies, I didn't pay attention to the `classic-builds` folder not existing before, but that's a great catch! Let's not block this PR, and I can follow up with migration from `classic-updates` to `classic-builds` 😄

**Comment by amandeepmittal** [comment]
> Also can someone confirm that we actually do want to deprecate this doc

cc: @brentvatne

**Review by brentvatne — APPROVED** [review]

**Review by amandeepmittal — APPROVED** [review]

**Review by szdziedzic — APPROVED** [review]
thanks!

**Pull request merged**
