### PR TITLE
[splashscreen] Handle resizeMode correctly

### LINKED ISSUE #33138: expo-splash-screen plugin does not respect `resizeMode`
### Minimal reproducible example

https://github.com/expo/expo/issues/32515#issuecomment-2489350076

### What platform(s) does this occur on?

iOS

### Where did you reproduce the issue?

in a standalone app

### Summary

As mentioned [here](https://github.com/expo/expo/issues/32515#issuecomment-2489350076), the following splash configuration works great to create a full-screen splash image on iOS (Expo 52):

```
"expo": {
  "splash": {
    "image": "./assets/splash.png",
    "backgroundColor": "#232323",
    "enableFullScreenImage_legacy": true,
    "resizeMode": "cover"
  }
}
```

If you do the same in the `expo-splash-screen` plugin configuration, the image will not be shown full-screen, but there will be gray margins (either on the top/bottom or left/right, depending on the screen and image size). `resizeMode: cover` should make the image cover the whole screen.

Sorry for not providing a Snack, but this behavior is only on a built app, since AFAIK Expo Go cannot use the expo-splash-screen plugin. I hope the description is specific enough.

@brentvatne said @alanjhughes can handle that ticket.

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 14.6
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 21.6.0 - ~/.nvm/versions/node/v21.6.0/bin/node
      Yarn: 1.22.22 - /opt/homebrew/bin/yarn
      npm: 10.2.4 - ~/.nvm/versions/node/v21.6.0/bin/npm
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.1, iOS 18.1, macOS 15.1, tvOS 18.1, visionOS 2.1, watchOS 11.1
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 16.1/16B40 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^52.0.0 => 52.0.7 
      react: 18.3.1 => 18.3.1 
      react-dom: 18.3.1 => 18.3.1 
      react-native: 0.76.2 => 0.76.2 
      react-native-web: ~0.19.6 => 0.19.13 
    npmGlobalPackages:
      eas-cli: 13.2.3
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check native tooling versions
✔ Check if the project meets version requirements for submission to app stores
✔ Check for common project setup issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check for issues with Metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK
```

### PR DESCRIPTION
**Pull request by alanjhughes**
# Why
Closes #33138

# How
`resizeMode` was not being handled correctly, instead it was left hardcoded to `contain`. Really, it was our examples that show incorrect usage, `resizeMode` should be set as part of the `ios` or `android` config objects and not as a top level property but it's fine to add support for it here too because the legacy config supports it there. 

# Test Plan
Sandbox. A full screen image correctly has `scaleAspectFill` applied when `resizeMode` is `cover` and `scaleAspectFit` when it is `contain`.

### CODE REVIEW

**Review by chrfalch — APPROVED** [review]

**Comment by emartiros** [comment]
hey folks, it doesn't cover ios 😢

**Comment by alanjhughes** [comment]
Hi @emartiros - resize mode is applied on iOS.

**Comment by emil-martirosian** [comment]
@alanjhughes well, then it doesn't work. I expect that some changes in Splashscreen.storyboard are needed to fix the resizeMode on ios. I will try to prepare a minimal reproducible example then

**Comment by alanjhughes** [comment]
@emartiros in what way is it not working?

**Comment by emil-martirosian** [comment]
After setting resizeMode to cover/contain, the splashscreen image still has fixed width

**Comment by alanjhughes** [comment]
@emartiros it does have a fixed width. It is whatever you have set `imageWidth` or 100 if you don't provide it. resizeMode refers to how the image you provide scales to fill its container https://developer.apple.com/documentation/uikit/uiview/contentmode

**Comment by brushton-ces** [comment]
Also ran into some bugs here trying to maintain my iOS splash screen with resizeMode: 'cover'.  

I expected this to use "cover" but it used "contain" instead.
```
[
      'expo-splash-screen',
      {
        ios: {
          enableFullScreenImage_legacy: true,
          resizeMode: 'cover', // <- does not work
          image: envConfig.splashPath,
          backgroundColor: envConfig.splashBackgroundColour,
        },
        android: {
          backgroundColor: envConfig.splashBackgroundColour,
          image: envConfig.splashPathAndroid,
          imageWidth: 300,
        },
      },
    ],
```


What worked for me in the plugin config (after a lot of debug and ending up in the plugin code, and hence here I am):

```
[
      'expo-splash-screen',
      {
        enableFullScreenImage_legacy: true,
        resizeMode: 'cover', // <- this needs to be at the top level, not in the ios/android objects

        ios: {
          // resizeMode: 'cover', <- don't put this here, it will get overwritten by the plugin to 'contain'
          image: envConfig.splashPath,
          backgroundColor: envConfig.splashBackgroundColour,
        },

        android: {
          backgroundColor: envConfig.splashBackgroundColour,
          image: envConfig.splashPathAndroid,
          imageWidth: 300,
        },
      },
    ],
```

Maybe it would be better if the withSplashScreen function was something like this?:
```
const withSplashScreen: ConfigPlugin<PluginConfig> = (config, props) => {
  const android: AndroidSplashConfig = {
    ...props,
    ...props?.android,
    dark: {
      ...props?.android?.dark,
      ...props?.dark,
    },
  };
  const resizeMode = props?.ios?.resizeMode || props?.resizeMode || 'contain'; // consider the nested value?
  const ios: IOSSplashConfig = {
    ...props,
    ...props?.ios,
    resizeMode: resizeMode === 'native' ? 'contain' : resizeMode,
    dark: {
      ...props?.ios?.dark,
      ...props?.dark,
    },
  };

  // Need to pass null here if we don't receive any props. This means that the plugin has not been used.
  // This only happens on Android. On iOS, if you don't use the plugin, this function won't be called.
  config = withAndroidSplashScreen(config, props ? android : null);
  config = withIosSplashScreen(config, ios);
  return config;
};
```

The bug seems to be resizeMode in the iOS object does not work properly still.

**Pull request merged**
