### PR TITLE
Change baseline icon pixel size

### PR DESCRIPTION
**Pull request by aleqsio**
# Why

Closes #ENG-6880

# How

Changing the baseline to align with new Adaptive Icon docs
https://developer.android.com/develop/ui/views/launch/icon_design_adaptive
`All layers must be sized at 108 x 108 dp.`

# Test Plan

Changed this value in node_modules, tested if prebuild result is as expected. Fixes the problem

# Checklist

- [x] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Comment by Simek** [comment]
This should also fix #17728 and #19881

**Review by brentvatne — APPROVED** [review]

**Comment by ontech7** [comment]
Tested `eas build` for Android APK, and seems [#19881](https://github.com/expo/expo/issues/19881) is not fixed yet.

I don't know if it's testing phase, or it's already in prod

**Comment by brentvatne** [comment]
@ontech7 - this was released in expo@47.0.4. i recommend updating to the latest expo@47 version, which at the time of writing is 47.0.8. update the version in your package.json then run `npm install` or `yarn` again

**Comment by mrtry** [comment]
@aleqsio 

Hi!
I'd like to know a few things 🙏 
With this modification, is the size of the foreground image going to be 72dp? 👀 

The layer size of the adaptive icon is 108dp, but it says that the foreground image should be 72dp.

> The logo must be at least 48 x 48 dp; it must not exceed 72 x 72 dp because the inner 72 x 72 dp of the icon appears within the masked viewport.
> [Adaptive icons | Android Developers](https://developer.android.com/develop/ui/views/launch/icon_design_adaptive#design-adaptive-icons:~:text=of%20the%20icon.-,The%20logo%20must%20be%20at%20least%2048%20x%2048%20dp%3B%20it%20must%20not%20exceed%2072%20x%2072%20dp%20because%20the%20inner%2072%20x%2072%20dp%20of%20the%20icon%20appears%20within%20the%20masked%20viewport.,-The%20outer%2018)

I only read the code for the constants, but I couldn't find the constant 72dp, so I was worried and commented 🙇‍♂️ 
My apologies if this has already been addressed.
Your pull request has been helpful 🥳 
Thank you very much 🤝

**Comment by ontech7** [comment]
> @aleqsio
> 
> Hi! I'd like to know a few things 🙏 With this modification, is the size of the foreground image going to be 72dp? 👀
> 
> The layer size of the adaptive icon is 108dp, but it says that the foreground image should be 72dp.
> 
> > The logo must be at least 48 x 48 dp; it must not exceed 72 x 72 dp because the inner 72 x 72 dp of the icon appears within the masked viewport.
> > [Adaptive icons | Android Developers](https://developer.android.com/develop/ui/views/launch/icon_design_adaptive#design-adaptive-icons:~:text=of%20the%20icon.-,The%20logo%20must%20be%20at%20least%2048%20x%2048%20dp%3B%20it%20must%20not%20exceed%2072%20x%2072%20dp%20because%20the%20inner%2072%20x%2072%20dp%20of%20the%20icon%20appears%20within%20the%20masked%20viewport.,-The%20outer%2018)
> 
> I only read the code for the constants, but I couldn't find the constant 72dp, so I was worried and commented 🙇‍♂️ My apologies if this has already been addressed. Your pull request has been helpful 🥳 Thank you very much 🤝

The function called for generating the Icon is called for the foreground and the background icon (if it's used).

image

**Comment by ontech7** [comment]
> @ontech7 @mrtry
> 
> I'm think both layers are supposed to be 108dp images, it's just that the foreground logo should not exceed 72dp of visible area in the center, with the outside pixels being transparent.

As I understand from the docs, it's correct. In fact I'm not objecting it. I was expecting that the bug was about the wrong dp(s). Now it's solved on Xiaomi devices, when updating to the lastest Expo SDK dependency.

**Comment by aleqsio** [comment]
Awesome, thank you for verifying the fix @ontech7!

**Pull request merged**
