### PR TITLE
[expo-camera] fix quality option check condition

### PR DESCRIPTION
**Pull request by davidavz**
# Why

Setting the `takePictureAsync` quality option to `0` has absolutely no effect

# How

The condition to check if the quality option is set is not correct because if you set it to `0` it will return `true` and overwrite it to `1`. We should test instead if it is `undefined`.

# Test Plan

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Review by lukmccall — CHANGES_REQUESTED** [review]
Could you rebuild the JS files by running `yarn build` in the `expo-camera` directory? Also, have you tested this change? I'm not sure if the native code would work when we pass 0.

**Comment by davidavz** [comment]
> Could you rebuild the JS files by running `yarn build` in the `expo-camera` directory? Also, have you tested this change? I'm not sure if the native code would work when we pass 0.

Yes I have tested it and it works fine with `0` as value

**Comment by lukmccall** [comment]
> Yes I have tested it and it works fine with `0` as value

Great! Thanks for that. The last thing, and it should be ready to be merged: could you add the changelog entry?

**Review by lukmccall — APPROVED** [review]
Looking good! Thanks
I'll merge it as soon as the CI pass

**Pull request merged**
