### PR TITLE
[firebase-recaptcha] Update web imports and add _reset for v9

### PR DESCRIPTION
**Pull request by byCedric**
# Why

Backport of #15102 and #15038 for SDK 43

# How

Cherry-picked and fixed the conflicts

~~It also includes an unversioned docs change, but which is available on master as well. Once this is merged and published, I'll update the docs for SDK 43~~ This got merged already! Only need to publish

# Test Plan

See #15117 and #15038

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] This diff will work correctly for `expo build` (eg: updated `@expo/xdl`).
- [ ] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Comment by kevinhylant** [comment]
@byCedric Thank you for fixing this - just ran into this issue when upgrading to SDK 43 + EAS & followed the breadcrumbs to this PR. Good timing for me ;p

Sorry, n00b question, **but does merging this PR create a new dot release for SDK 43**? meaning that we'd just have to install the latest Expo SDK version 43.0.1 (?) and this fix will get pulled in automatically?

Thanks in advance!

**Review by brentvatne — APPROVED** [review]

**Review by tsapeta — APPROVED** [review]

**Comment by adriaanbalt** [comment]
Also curious what the eta is. I'm hoping to launch before the holidays. Thanks!

**Comment by kevinhylant** [comment]
@byCedric Sorry for being annoying here 😬  but any status update?

**Comment by tsapeta** [comment]
@kevinhylant @adriaanbalt 
This fix will be already included in the upcoming SDK44, but I'm going to figure out if we can publish a patch for SDK43 too. I'll keep you informed 😉

**Comment by kevinhylant** [comment]
Thank you @tsapeta that would be great 🙏

**Comment by tsapeta** [comment]
Alright, we published these changes in `expo-firebase-recaptcha@2.1.0` (`next` tag) — the same will be used in SDK44, but it should also work with SDK43.

**Pull request merged**
