### PR TITLE
[expo-module-template] Move kotlin classes to java src repository.

### PR DESCRIPTION
**Pull request by mczernek**
# Why

Currently, when we create new module using `et cu` all android native kotlin files are places in `android/src/main/kotlin` dir, while out `gradle.groovy` script assumes all android classes being in `android/src/*/java/` dirs.

# How

Change location of kotlin files in `expo-module-template`

# Test Plan

Create new unimodule using `et cu` and open expo in Android Studio.

### CODE REVIEW

**Review by tsapeta — COMMENTED** [review]
@bbarthec recently updated the template to use Kotlin and I guess it's been intended to be under `kotlin` dir... so maybe instead of renaming it would be better to add support for such path to `react-native-unimodules`?

**Comment by bbarthec** [comment]
I'm not sure what are the kotlin/java guidelines for the packages naming 🤔
I just disliked the idea of having `java` in package name for any `kotlin` file 😅

**Comment by mczernek** [comment]
> I'm not sure what are the kotlin/java guidelines for the packages naming 🤔
> I just disliked the idea of having `java` in package name for any `kotlin` file 😅

I am not sure if it is even supported to have any sources outside java directory. It does not work straight away, for sure, and I do not see any code in `unimodules-core.gradle` that might break that.

I've just created new Android project in Android Studio, and it puts all Kotlin files in java dir, even though there are no java files whatsoever.

**Review by bbarthec — APPROVED** [review]
@mczernek, you're right 👍 I've just searched for some Android apps written in kotlin and each of them has the kotlin files under java package 😉

**Review by tsapeta — APPROVED** [review]
then you got an approval from me as well 😄

**Pull request merged**
