### PR TITLE
webp format support (Android Only) for GLContext.takeSnapshot function

### PR DESCRIPTION
**Pull request by pacoelayudante**
# Why

At some point (API 14), Android added native WebP support ([Bitmap.CompressFormat.WEBP](https://developer.android.com/reference/android/graphics/Bitmap.CompressFormat#WEBP)), so adding the option to export the render to WebP is trivial.
Creating a new module just for converting from PNG to WebP is silly since you can get the GL render as WebP directly. Also converting from PNG to WebP could create quality loss.

# How

In GLContext.java, I extended the block that specifies using png (instead of jpeg, the default) to recognize webp as another posible format.

# Test Plan

Sadly, a combination of living in Windows OS and lack of experience in some aspects of software development, I was not able to test this change using the proper methods (unit test, and that). But I did tried the change in the App I'm building and it worked fine

Thanks for your attention, sorry for any mistake in the PR, this is the second time I do a PR

### CODE REVIEW

**Comment by pacoelayudante** [comment]
@brentvatne ping like this?

**Comment by brentvatne** [comment]
@nikki93 will review this next time he's around!

**Comment by nikki93** [comment]
@pacoelayudante thanks for the PR! I just tested it and the code does work on Android. We would also need an accompanying documentation change in https://github.com/expo/expo/blob/master/docs/pages/versions/unversioned/sdk/gl-view.md#glviewtakesnapshotasyncgl-options explaining the option, and clearly explaining that it isn't supported on Android. Also I think a corresponding change should be added on iOS with a proper error message explaining that the format isn't available on iOS. I think these changes should be included before it makes it into the main library.

**Comment by pacoelayudante** [comment]
So, I have no Mac, and I have to make the programming skillcheck with a -2 penalty since I don't have any skill point on Objective-C. So well... I'll just give it a go and hope for the best.
Also, I think is better to display a warning and exporting the image as png, sounds reasonable to me.
And finally, I will try a way to not clutter the docs, tell me what you think about it

**Comment by pacoelayudante** [comment]
OK! so check it out @nikki93

**Review by tsapeta — APPROVED** [review]
Thanks @pacoelayudante! 👍

**Pull request merged**
