### PR TITLE
[templates] Upgrade bare templates to react-native 0.61.5

### PR DESCRIPTION
**Pull request by IjzerenHein**
# Why

This PR upgrades the bare-templates (minimum & typescript) to react-native 0.61.5.

# How

This updates the tooling and android files to be consistent (where possible) with a vanilla `react-native@0.61.5` installation.

## Bundling

- Remove `.babelrc` and `metro-react-native-babel-preset` dependency

## Android

- Project files were updated
- Add missing `debug/AndroidManifest.xml`
- Debug signing config updated
- Had to keep `sdkTargetVersion` on 27 ([as 28 gives this error](#7690)).
- There seems to be some partial Flipper support in 0.61.5, but Flipper does not work out of the box

## iOS

- No changes were made for iOS
- Fix `/ios/pods` .gitignore for `expo-template-bare-minimum`

# Test Plan

- Create tarball for each bare template project (`npm pack`)
- Used `expo init --template <tarball_location>` to create empty projects
- Tested with `expo-template-bare-minimum`
  - `yarn android` ✅ *
  - build android release (`cd android && ./gradlew assembleRelease`) ✅
  - `yarn ios` ✅
  - `yarn web` ✅
- Tested with `expo-template-bare-typescript`
  - `yarn android` ✅ *
  - build android release (`cd android && ./gradlew assembleRelease`) ✅
  - `yarn ios` ✅
  - `yarn web` ✅

* **ATTENTION REQUIRED**

When running `expo init --template <tarball_location>`, the Android `debug.keystore` file doesn't seem to be copied correctly.  It gets encoded/encrypted. When copying the file by hand, everything is okay.

### CODE REVIEW

**Comment by IjzerenHein** [comment]
@ide do you have any idea why this could be? (see description above)

> When running expo init --template <tarball_location>, the Android debug.keystore file doesn't seem to be copied correctly. It gets encoded/encrypted. When copying the file by hand, everything is okay.

**Review by brentvatne — APPROVED** [review]

**Comment by brentvatne** [comment]
I fixed the targetSdkVersion 28 issue in https://github.com/expo/expo/commit/23872617a7dd0e567c7943307e21976986dcf534 so we should be good to go there!

**Comment by brentvatne** [comment]
re: keystore issue on init, I believe it's due to this: https://github.com/expo/expo-cli/blob/5b7d2739ac8face51ec68ce78afebd21ab3aa186/packages/xdl/src/Exp.ts#L77-L87

I'll update that in expo-cli so the `.keystore` extension is also treated as binary... but perhaps we should switch to an allow list rather than disallow list here

**Comment by IjzerenHein** [comment]
> re: keystore issue on init, I believe it's due to this: https://github.com/expo/expo-cli/blob/5b7d2739ac8face51ec68ce78afebd21ab3aa186/packages/xdl/src/Exp.ts#L77-L87
> 
> I'll update that in expo-cli so the `.keystore` extension is also treated as binary... but perhaps we should switch to an allow list rather than disallow list here

Ah I see. Yep that must be it!

Thanks for fixing! 👍

**Pull request merged**
