### PR TITLE
fix(expo-updates): take server root into account when collecting assets

### PR DESCRIPTION
**Pull request by byCedric**
# Why

This fixes an issue in `expo-updates` related to enabling `EXPO_USE_METRO_WORKSPACE` by default.

> Note, we might also need to copy the windows fix to always convert entry points to a valid Node module specifier (using `./my/file.js` POSIX notation). Will verify before merging

# How

Previously, `expo-updates` was collecting assets by generating the Metro graph directly, and then pulling all assets from the graph. Unfortunately, when resolving the entry point, it didn't take the server root into account.

This adds a function `getRelativeEntryPoint` to `@expo/config/paths` that does these same thing, but takes possible server roots into account.

# Test Plan

See CI

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Comment by byCedric** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/expo/expo/30633?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#30633** <a href="https://app.graphite.dev/github/pr/expo/expo/30633?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#30621** <a href="https://app.graphite.dev/github/pr/expo/expo/30621?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @byCedric and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by wschurman — APPROVED** [review]
Change to expo-updates looks good but wait for approval from @EvanBacon for the change to config before landing.

**Comment by byCedric** [comment]
There are a few issues on `main` related to bare-expo and the RN 75 upgrade, have to hold off on these PRs for now. Will rebase both PRs when that's resolved.

**Comment by byCedric** [comment]
### Merge activity

* **Jul 30, 11:23 AM EDT**: @byCedric started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/expo/expo/30633).

**Pull request merged**
