### PR TITLE
Enable background capabilities for audio in iOS

### PR DESCRIPTION
**Pull request by rricard**
I just made an attempt at letting work audio in background with exponent. I don't control anything here but just enabled the option in XCode and it seems to work fairly well in my simulator.

I just wanted to ask if we could just use this like that or do we necessarily need to add some logic to the Video component or even a dedicated Audio API to manage this background more finely (i.e. add controls in control center/lock screen and so on ...) in order to get that integrated into the next exponent build?

### CODE REVIEW

**Comment by rricard** [comment]
I'm open to discuss API design here and I would be happy to try to implement them!

**Comment by brentvatne** [comment]
🤔 cc @nikki93

**Comment by terribleben** [comment]
Thanks for the suggestion @rricard! We have somebody working on an audio API right now. It will eventually include background audio, though the first iteration probably won't. The native background audio API is complicated on iOS (actually there is more than one API depending on what you're trying to do) and we're hoping to come to a solution that makes sense on both platforms to some degree.

**Comment by rricard** [comment]
@terribleben thanks! I'm just using this small patch right now in a custom exponent build and I was hoping that some point in the future I could avoid relying on it and go back on "vanilla" exponent. Which will be the case... So that's pretty cool! Feel free to ping me if you want feedback on this.

**Comment by rricard** [comment]
I'm closing this for now since you seem to be working on a better implementation than this small hack! reopen it if you think it is still relevant...

**Pull request closed without merging**
