### PR TITLE
[sqlite] remove legacy expo-sqlite

### PR DESCRIPTION
**Pull request by Kudo**
# Why

remove deprecated legacy expo-sqlite
close ENG-12985

# How

remove and rename legacy expo-sqlite

# Test Plan

ci passed

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [x] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Review by amandeepmittal — APPROVED** [review]

**Review by alanjhughes — APPROVED** [review]

**Comment by trajano** [comment]
Would this mean that using expo-sqlite/legacy will no longer work?

**Comment by tsapeta** [comment]
@trajano, yes, it will no longer work in the upcoming SDK 52

**Comment by Kudo** [comment]
@trajano we mentioned this from [sdk 51 release log](https://expo.dev/changelog/2024/05-07-sdk-51)
> You can find the old versions at expo-camera/legacy and expo-sqlite/legacy during SDK 51, and they will be removed in SDK 52.

i recommend migrating the new sqlite api. if that takes much effort, you may consider build websql interface on top of the new expo-sqlite. but i feel that the websql interface is lack of flexibility.

**Comment by trajano** [comment]
@tsapeta noted we just updated to Expo 51 due to the Android SDK stuff hopefully there's nothing that would push us to Expo 52 anytime soon.

**Comment by macksal** [comment]
Would there be any consideration to keep the legacy API published somewhere? Maybe as a separate package.

There's a popular ORM, TypeORM that doesn't support the new expo driver yet. [The library seems fairly slow to be implementing new changes while they go through a change of maintainers](https://github.com/typeorm/typeorm/pull/11107).

Myself and likely others are stretched between updating to SDK52 and using an awkward patch, or staying behind. It seems silly when there's no technical barrier here: just shrinkwrap up the old API that was already working and we can call it a day.

**Pull request merged**
