### PR TITLE
[docs] Fix HIG link in storereview.mdx

### PR DESCRIPTION
**Pull request by enagorny**
# Why

Link to Apple Human Interface Guidelines changed

# How

# Test Plan

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Review by amandeepmittal — CHANGES_REQUESTED** [review]
Hey @enagorny, thanks for catching this and fixing it!

can I ask you to backport these changes to other SDK versions?

**Comment by enagorny** [comment]
@amandeepmittal Yes, if you help me how to do it. Should it be separate PRs to separate branches or tags? How many versions are currently supported by expo?

**Comment by amandeepmittal** [comment]
> @amandeepmittal Yes, if you help me how to do it. Should it be separate PRs to separate branches or tags? How many versions are currently supported by expo?

Of course! Updating this PR is fine.

We usually support 2 previous SDK versions (for example, SDK 48 is the current/latest version and SDK 47 and 46 are previous). Each Expo SDK version has a separate `storereview.mdx` file under `versions/` directory. Here is a list of the places that need the same changes applied:
- SDK 47: https://github.com/expo/expo/blob/35108bb42ef08fb81e8ef55a6c863430c1137b10/docs/pages/versions/v47.0.0/sdk/storereview.mdx?plain=1#L29
- SDK 48: https://github.com/expo/expo/blob/35108bb42ef08fb81e8ef55a6c863430c1137b10/docs/pages/versions/v48.0.0/sdk/storereview.mdx?plain=1#L29
- SDK 46: https://github.com/expo/expo/blob/35108bb42ef08fb81e8ef55a6c863430c1137b10/docs/pages/versions/v46.0.0/sdk/storereview.mdx?plain=1#LL29C66-L29C165

Thank you!

**Review by amandeepmittal — APPROVED** [review]
Thank you for backporting the change to all SDK versions!

**Pull request merged**
