### PR TITLE
[asset][expo] Add manifest check in expo and expo-asset to avoid yellowbox on bare workflow apps

### LINKED ISSUE #11888: expo-asset relies on Constants.manifest and throws yellowbox warnings in bare projects
**Summary**

Using expo-asset 8.2.2 in a bare project causes a yellowbox error: 

**Constants.manifest is null because the embedded app.config could not be read. Ensure that you have installed the expo-constants build scripts if you need to read from Constants.manifest.**

Please patch expo-asset to fallback to Updates and not throw this yellowbox on a bare project

**Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!**

bare

**What platform(s) does this occur on?**

iOS

**SDK Version (managed workflow only)**

_No response_

**Environment**
```
Expo CLI 4.1.6 environment info:
    System:
      OS: macOS 11.1
      Shell: 3.1.0 - /usr/local/bin/fish
    Binaries:
      Node: 14.4.0 - ~/.nvm/versions/node/v14.4.0/bin/node
      Yarn: 1.22.4 - ~/.yarn/bin/yarn
      npm: 6.14.11 - ~/.nvm/versions/node/v14.4.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /Users/admin/.rvm/gems/ruby-2.5.1/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
      Android SDK:
        API Levels: 26, 27, 28, 29, 30
        Build Tools: 27.0.3, 28.0.0, 28.0.3, 29.0.2, 29.0.3, 30.0.2
        System Images: android-26 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6953283
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ^40.0.1 => 40.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: 0.63.4 => 0.63.4
      react-native-web: ~0.13.12 => 0.13.18
      react-navigation: ^4 => 4.4.3
    npmGlobalPackages:
      expo-cli: 4.1.6
    Expo Workflow: bare
```
**Reproducible demo or steps to reproduce from a blank project**

N/A this is a known issue

### PR DESCRIPTION
**Pull request by mogery**
# Why

As stated in issue #11888, `expo-asset` (and additionally, `expo`'s `logging.fx.ts`) accessed `Constants.manifest` on bare workflow apps without proper existance checks beforehand. This resulted in annoying yellowbox warnings in bare workflow debug builds.

Therefore, this PR fixes #11888.

# How

I changed `expo-assets -> PlatformUtils.getManifest` to use `IS_MANAGED_ENV` and `IS_BARE_ENV_WITH_UPDATES` to determine available sources for the manifest. If `IS_MANAGED_ENV` is true, it will use `Constants.manifest`, if `IS_BARE_ENV_WITH_UPDATES` is true, it will use `Updates.manifest`, else it will just return `{}`. A similar method is used in `expo -> environment/logging.fx`.

This added `expo-updates` as a dependency to `expo` and `expo-asset`.

(I also had to change `expo-asset -> AssetSources-test._mockConstants` to set `appOwnership`, since that is how `IS_MANAGED_ENV` is determined.)

# Test Plan

 * Ran `yarn test` on `expo` and `expo-assets`
 * Copied updated modules/builds to a bare app to confirm fix

I did not write any extra tests for this, since I don't think it's needed.

### CODE REVIEW

**Comment by mogery** [comment]
I can't find how to fix this symlink error for the life of me. Can someone help?

**Comment by mogery** [comment]
Nevermind, this should fix it.

**Comment by mogery** [comment]
Is Danger's GitHub token broken? Seems to always fail.

**Comment by esamelson** [comment]
Thank you very much for the PR @mogery ! Many apologies that we already happened to be working on this issue at the same time, otherwise we'd gladly work with you to review and accept your PR.

In this case, we're choosing the solution in #12237 instead, for a couple of reasons -- (1) despite your comment on that PR, it does actually fall back to Updates.manifest, by utilizing the logic that already exists in Constants.ts; we'd prefer to expose an internal-facing property on Constants rather than maintain two separate copies of the same logic for finding the manifest, and (2) unfortunately adding expo-updates as a dependency to other packages comes with side effects that we don't want, so we try to avoid this whenever possible.

However, we really appreciate the time and effort you put into this PR -- I know it's not so easy to even get the repo set up currently! -- and look forward to other fixes/contributions from you in the future.

**Comment by mogery** [comment]
Ooooh, sorry, I wasn't aware that Constants had that behaviour already. No problem, my apologies.

**Pull request closed without merging**
