### PR TITLE
Replace deprecated require actual with jest method

### LINKED ISSUE #8344: [jest-expo] incompatibility with jest 26
### Environment

```
  Expo CLI 3.17.11 environment info:
    System:
      OS: Linux 5.3 Ubuntu 19.10 (Eoan Ermine)
      Shell: 5.0.3 - /bin/bash
    Binaries:
      Node: 12.6.0 - /usr/local/bin/node
      Yarn: 1.22.4 - ~/.yarn/bin/yarn
      npm: 6.13.0 - ~/.npm-global/bin/npm
    npmPackages:
      expo: ^37.0.11 => 37.0.11 
    npmGlobalPackages:
      expo-cli: 3.17.11
```

This is an issue with jest-expo 37.0.0

### Steps to Reproduce
Upgrade jest to 26.

Jest-expo still uses the long deprecated [and now removed](https://github.com/facebook/jest/blob/master/CHANGELOG.md#2600) `require.requireActual` which has been moved to `jest.requireActual`. The following changeset fixes the error for me:

```diff
--- a/src/preset/setup.js
+++ b/src/preset/setup.js
@@ -156,2 +156,2 @@ export const includesLowercase = (searchTerm: string) =>
  jest.mock('@unimodules/react-native-adapter', () => {
-   const ReactNativeAdapter = require.requireActual('@unimodules/react-native-adapter');
+   const ReactNativeAdapter = jest.requireActual('@unimodules/react-native-adapter');
    const { NativeModulesProxy } = ReactNativeAdapter;
 
 ```

### Expected Behavior
Tests are running with jest 26

### Actual Behavior
The tests fail to compile and start throwing the following error:

```
  ● Test suite failed to run

    TypeError: require.requireActual is not a function

      at ../../node_modules/jest-expo/src/preset/setup.js:157:40
      at Object.<anonymous> (../../node_modules/@unimodules/core/src/AdapterProxy.ts:1:1)
      at Object.<anonymous> (../../node_modules/@unimodules/core/src/index.ts:1:1)
```

### PR DESCRIPTION
**Pull request by byCedric**
# Why

Fixes #8344

# How

See #8344, and replace all instances of `require.requireActual` with `jest.requireActual`.

# Test Plan

Run all tests.

### CODE REVIEW

**Comment by byCedric** [comment]
CI is failing because of missing environment keys, it's because I created a PR from a fork. The tests itself are running fine 😄

**Review by sjchmiela — APPROVED** [review]
Looks good to me! 💯 Have you tested these changes on the offending version of Jest? Would it be worth upgrading to one in the repo?

**Comment by byCedric** [comment]
I've tested this in Jest 26 and 25, with this change they both work 😄 Unfortunately, there is no real performance benefit. 

 The only real benefit of upgrading to Jest 26 is that we are a bit more "future proof". New features introduced in Jest 26 aren't that widely used, like [new fake timers implementation](https://jestjs.io/blog/2020/05/05/jest-26#new-fake-timers).

> I executed `time expotools check-packages` with Jest 25 and 26, this is the output of those runs

```
// Jest 26
$ expotools check-packages  852.17s user 80.59s system 252% cpu 6:09.34 total
$ expotools check-packages  850.18s user 79.91s system 253% cpu 6:07.61 total

// Jest 25
$ expotools check-packages  851.47s user 80.18s system 253% cpu 6:07.95 total
$ expotools check-packages  851.85s user 81.89s system 253% cpu 6:08.31 total
```

**Review by tsapeta — APPROVED** [review]

**Comment by tills98** [comment]
When is this expected to be available in the jest-expo package on npm? At the moment my tests only work on my local machine with local bugfix but my tests on CI did not work due to this bug.

**Comment by tsapeta** [comment]
It should be out soon as we're now in the process of releasing SDK38, but... it will be for SDK38 😉 Isn't it possible to apply this local bugfix on CI too? Temporarily of course.

**Comment by tills98** [comment]
Okay, thanks! Yes, I found a temporary fix. I've added following line to my CI configuration to replace "require" with "jest":
`sed -i 's/require.requireActual/jest.requireActual/g' node_modules/jest-expo/src/preset/setup.js`

**Pull request merged**
