### PR TITLE
Expo Auth Session Custom HTTP Headers

### PR DESCRIPTION
**Pull request by levizimmerman**
# Why

Feature Request: https://expo.canny.io/feature-requests/p/custom-headers-in-expo-auth-session

Motivation: Need to add extraHeaders to SSO calls so we can add things like: transaction IDs to backtrace errors in our SSO client.

# How

Added extraHeaders to the requestConfig options and a loop to check if extra headers are set. If so than add extra HTTP header params to the request without overwriting the current ones.

# Test Plan

I created multiple requests like so:
```ts
const request = new AccessTokenRequest({
    code,
    redirectUri: REDIRECT_URI,
    clientId: CLIENT_ID,
    clientSecret: CLIENT_SECRET,
    extraHeaders: {
      testProp: 'testValue',
    },
    scopes: SCOPES,
  });
// Validate if `testProp` is added to headers.
console.log('request.getHeaders()', request.getHeaders());
// Use network inspector to validate HTTP header is added.
request.performAsync(discovery)

// Repeat this for: RevokeTokenRequest, RefreshTokenRequest, etc.
```

# Checklist
Documentation needs to be updated with this extra option.

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [x] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Review by chitezh — COMMENTED** [review]
Nice! This will be a great addition.

@levizimmerman  do you mind also updating the [tests](https://github.com/expo/expo/tree/9662aa34c9372bdd315fd317f960ff2b8b0c2db7/packages/expo-auth-session/src/__tests__)?

**Comment by levizimmerman** [comment]
@chitezh Tests are added!

**Comment by levizimmerman** [comment]
How do I solve these merge conflicts? I already rebased on top of `main`...

**Comment by chitezh** [comment]
> How do I solve these merge conflicts? I already rebased on top of `main`...

I don't see the conflicts though. @alanjhughes do you mind chiming in here?

**Comment by levizimmerman** [comment]
image

**Comment by levizimmerman** [comment]
@chitezh @alanjhughes I believe it only needs reviews and then it should be ok

**Review by alanjhughes — APPROVED** [review]
Looks good 👍 can you resolve the conflicts and I'll merge?

**Comment by levizimmerman** [comment]
> Looks good 👍 can you resolve the conflicts and I'll merge?

Resolved!

**Comment by levizimmerman** [comment]
@alanjhughes it can be merged ;)

**Comment by alanjhughes** [comment]
Can run `yarn build` in `packages/expo-auth-session` to fix CI?

**Comment by levizimmerman** [comment]
I closed this MR because I messed the commits up in a rebase. Let me try again.

**Pull request closed without merging**
