### PR TITLE
Upgrade Facebook SDK (Ads and LoginKit) to latest versions

### PR DESCRIPTION
**Pull request by sjchmiela**
# Why

Fixes https://github.com/expo/expo/issues/3339.

# How

See commit list.

# Test Plan

NCL looks ok.

### CODE REVIEW

**Review by tsapeta — APPROVED** [review]

**Comment by zsayenko** [comment]
Thanks for doing this guys.
Is this now available in 32.0.5 or do I need to wait for 33?

I've updated to 32.0.5 and still get the old error: 
`The SDK version in the ad request is no longer supported for new apps. Please upgrade to one of the latest versions of the SDK`

Also when I search for expo-ads-facebook in my npm_modules nothing come up

**Comment by tuqire** [comment]
@zsayenko did you get an answer? I still seem to be on 4.99 even though I updated Expo recently.

**Comment by zsayenko** [comment]
Nope, haven't heard anything yet

**Comment by sjchmiela** [comment]
As per the [CHANGELOG](https://github.com/expo/expo/blob/master/CHANGELOG.md) this change has landed on `master`, but hasn't been deployed neither to standalone app builders nor to `expokit`. This PR will be released along with SDK33. 🙂

**Pull request merged**
