### PR TITLE
[filesystem][docs] Fix superscript tag not rendering correctly

### PR DESCRIPTION
**Pull request by amandeepmittal**
# Why

Currently, in Expo FileSystem API reference, the [FileSystem.getFreeDiskStorageAsync()](https://docs.expo.dev/versions/latest/sdk/filesystem/#filesystemgetfreediskstorageasync) does not renders `<sup>` tag correctly.

CleanShot 2024-01-11 at 01 41 26

This is probably due to TSDoc not being able to render HTML tags.

# How

This PR uses HTML entity code to directly convert numbers to display them as they are with superscript tag.

Changes backported from `unversioned` to SDK 50.

# Test Plan

Run docs locally and visit: https://docs.expo.dev/versions/latest/sdk/filesystem/#filesystemgetfreediskstorageasync

## Preview

CleanShot 2024-01-14 at 17 36 42@2x

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Review by Simek — APPROVED** [review]
Thanks for fixing that! 👍 

I can also look at adding a support for the `sup/sub` tags or a bit more convenient way than HTML entities.

**Review by tsapeta — APPROVED** [review]
Thanks! I agree with Simek, it would be great to support some html tags.

**Comment by ide** [comment]
Could you please fast follow with adding support for HTML tags, or possibly just replacing the HTML entities with the small Unicode characters themselves? It would be better to keep the comment in the source code readable and not let an implementation detail leak through.

**Comment by amandeepmittal** [comment]
Closing this since the underlying issue was fixed in #26412. Thank you so much for fixing it @Simek 🙏

**Pull request closed without merging**
