### PR TITLE
[font] Fix loading fonts on web and Next.js

### PR DESCRIPTION
**Pull request by danieloi**
So it works on web.

Based on this https://github.com/expo/google-fonts/issues/5#issue-655161265

# Why

Fonts don't just work ™️ when you're using a nextjs expo react-native-web app.

# How

The object passed to loadAsync has a 'default' key that's not represented when we're loading the fonts in our SSR app
# Test Plan

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] This diff will work correctly for `expo build` (eg: updated `@expo/xdl`).
- [ ] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Comment by tsapeta** [comment]
Could you please run `yarn build` in the package folder? The SDK checks on the CI are failing without that.

**Comment by danieloi** [comment]
Not exactly a small codebase to clone locally, install deps and run for so small a change. 
Any way I can skip that? 
I made the PR completely on the github web app

**Comment by danieloi** [comment]
> Could you please run `yarn build` in the package folder? The SDK checks on the CI are failing without that.

Not exactly a small codebase to clone locally, install deps and run for so small a change.
Any way I can skip that?
I made the PR completely on the github web app

**Comment by ide** [comment]
You'll need to check out the repo to test your change. We require a test plan, which can be a manual series of steps that you took to test your changes or it can be an automated test (ex. unit test).

**Comment by danieloi** [comment]
All done!

**Review by EvanBacon — APPROVED** [review]

**Comment by codinsonn** [comment]
I can confirm these changes work for Next.js 12.3.0. (by reimplementing them via `patch-package`)
Time to merge? @tsapeta @EvanBacon @danieloi

**Review by tsapeta — APPROVED** [review]

**Comment by Poheart** [comment]
Isn't this PR supposed to merge into `expo:main` instead of `master`? 

@tsapeta

**Comment by tsapeta** [comment]
Ah, good catch @Poheart! I'll cherry pick it to the main branch.

**Pull request merged**
