### PR TITLE
Remove unneeded .ruby-version file

### PR DESCRIPTION
**Pull request by douglowder**
# Why

React Native now supports multiple Ruby versions (see https://github.com/facebook/react-native/pull/36281, which was also cherry-picked for all versions 0.69 and above) so this file should no longer be needed.

# Test Plan

- Test locally, make sure `bundle install` and `et pod-install` work correctly
- CI should pass

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [x] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Comment by douglowder** [comment]
Looks like the CI to build the iOS client wants the Ruby version file, investigating

**Review by ide — COMMENTED** [review]
The most recent version of Ruby is 3.2.2 -- do the workflows we do on our own computers work with the latest version? Or was .ruby-version just for CI anyway?

I did verify that I could install Pods successfully in Expo Go with the latest version of Ruby.

**Comment by douglowder** [comment]
@ide CI looks good now -- versioning Expo Go job is failing due to an unrelated issue in expo-screen-orientation.

> The most recent version of Ruby is 3.2.2 -- do the workflows we do on our own computers work with the latest version? Or was .ruby-version just for CI anyway?

I'll check latest Ruby 3.2.2 on desktop, and also see if it works in CI

**Comment by douglowder** [comment]
> I'll check latest Ruby 3.2.2 on desktop, and also see if it works in CI

Looks good on both. Not sure what is the source of the one failing iOS unit test in CI, it passes locally in NativeTests for me.

**Review by ide — APPROVED** [review]
Thanks for testing!

**Review by tsapeta — APPROVED** [review]

**Pull request merged**
