### PR TITLE
[ios][sharing] Use UIActivityViewController

### PR DESCRIPTION
**Pull request by alanjhughes**
# Why

It was suggested in #21933 that using UIActivityViewController might be better than UIDocumentInteractionController. I agree. It offers much more options and is more straightforward to implement.

# How
Switched from using UIDocumentInteractionController to UIActivityViewController

# Test Plan
Tested in bare expo

### CODE REVIEW

**Review by tsapeta — COMMENTED** [review]
As far as I understand, it changes the behavior of `shareAsync` that it no longer resolves the promise when the view controller is dismissed, instead it resolves immediately. I think we don't want to do this.
Now there is also no way to prevent calling it multiple times – I'm not sure if this is good or not though.

**Comment by alanjhughes** [comment]
@tsapeta we can add a handler to it but it is called more often than just on dismissal. If they start an action and cancel it, it gets called but we still don't want to resolve that case. Certain actions throw an error when they are cancelled but it's not really an error so we need to ignore it. Unfortunately, there's no good way to determine what happened as it's just the generic `Error` that is returned. There is no delegate for this type. I don't think it's necessary to check if sharing is in progress like before because when the modal is presented there is no way to start a second share without dismissing it.

**Comment by tsapeta** [comment]
Hmm ok, but let's keep track on the user reports once we release it. In the future, I would prefer just sending events from the module instead of waiting for the promise to resolve

**Review by tsapeta — APPROVED** [review]

**Review by tsapeta — APPROVED** [review]

**Comment by thespacemanatee** [comment]
Cane we get this released soon? Thank you!

**Comment by tsapeta** [comment]
@thespacemanatee I just released this PR in `expo-sharing@11.3.0` 🚀 
Let us know if it works for you 🙂

**Comment by thespacemanatee** [comment]
@tsapeta Unfortunately after upgrading from `11.2.2`, we are starting to see this error which didn't occur before:

Screenshot 2023-04-13 at 12 30 51 AM

Should I create an issue?

**Comment by alanjhughes** [comment]
@thespacemanatee no need to open an issue, I know what the problem is. Just need to talk to @tsapeta first

**Comment by tsapeta** [comment]
It should be fixed in `11.3.1` 😉

**Pull request merged**
