### PR TITLE
[firebase-recaptcha] Update imports on web for the latest firebase JS sdk

### PR DESCRIPTION
**Pull request by IjzerenHein**
See #14829, fixes `yarn.lock`

Closes #14829

### CODE REVIEW

**Comment by abeaclark** [comment]
@IjzerenHein Thanks for the fix! Do you know when this will be included in a package release? Would love to build on top of this.

Thanks!

**Comment by IjzerenHein** [comment]
@brentvatne Can you help with publishing this?

**Comment by abeaclark** [comment]
Alternatively if there is a way to reference master branch in package.json, that could work. I'm just not sure it's possible with this repo setup?

Thanks again.

**Comment by mattgabor** [comment]
> @brentvatne Can you help with publishing this?

@brentvatne are there any updates on publishing this? It's blocking us from using `expo-firebase-recaptcha` on web

**Comment by brentvatne** [comment]
we'll release sdk 44 soon with this fix along with many other improvements. you can use [patch-package](https://www.npmjs.com/package/patch-package) to fix the library directly in your node_modules for now.

**Comment by sankparatkar** [comment]
I can see this commit included in the package installed ("expo-firebase-recaptcha": "^2.1.0") in my project. But I still get this error. The firebase version used in the project is 7.24.0. I would upgrade this to v9 soon but not immediately due to breaking changes.
Can you suggest a way out? I am not very sure about this but is there any way that the project's firebase version library's dependency could be separated?

**Comment by RazaShehryar** [comment]
Any update on this? using expo sdk 44 but still facing this issue. Using firebase 9.9.1

**Pull request merged**
