### PR TITLE
[jest-expo] Fix jest child process spawn failing on Windows

### PR DESCRIPTION
**Pull request by Artorp**
# Why

On Windows, `npx jest` or calling `jest` from a npm script failed with no error message. https://github.com/expo/expo/issues/2921 The jest wrapper attempts to load the javascript file directly which relies on the `#!/usr/bin/env node` shebang, which is not used on Windows.

# How

The issue was resolved by spawning the child process with `node` as the command, instead of calling the jest javascript file directly.

An alternate fix (not pursued) could be to use the library `cross-spawn` in place of `child_process`, as in https://github.com/expo/expo/pull/2853.

# Test Plan

I tested this on a new expo project initialized with the "tabs" template. I tested it on Linux (Ubuntu 18.04) and Windows 10, by using `npm link` and calling `npx jest`. Before the fix was implemented, Windows would not start jest while Linux did. After the fix, both Windows and Linux executed jest as expected.

### CODE REVIEW

**Comment by sWW26** [comment]
Spent 2 hours trying to find out why `yarn jest` wasn't doing anything... applying this fix locally solved that problem 🙄

**Review by ide — APPROVED** [review]
Please resolve the merge conflicts.

**Comment by ide** [comment]
Committed here: https://github.com/expo/expo/commit/4a652730b0f11874c1b3027ece62d20aa2424c03

**Comment by Artorp** [comment]
Sweet! 😁

**Comment by ide** [comment]
Backported this to 32.0.1 and published to npm.

**Pull request closed without merging**
