### PR TITLE
[expo-updates] Fetch asset manifest through programmatic CLI interface instead of depending on a running React Native CLI server

### PR DESCRIPTION
**Pull request by brentvatne**
# Why

Fixes this issue: https://github.com/expo/expo/issues/8374

Basically you want to be able to run `./gradlew :app:assembleRelease` without running a React Native CLI server beforehand, and this makes it possible to do so.

# How

- Use the Metro `Server` API that is used by `react-native bundle` in the previous build phase.
- Use `@expo/metro-config` to configure Metro, because we don't want to depend on the private configuration code that is internal to `@react-native-community/cli`.

# Test Plan

I patched these changes into an existing bare project and it worked properly on iOS and Android. It was able to unblock me to build on the build service.

### CODE REVIEW

**Review by esamelson — APPROVED** [review]
lgtm! this should also fix https://github.com/expo/expo/issues/8691.

**Comment by todorone** [comment]
@brentvatne This PR broke building iOS project on RN `0.63` because of this commit - https://github.com/facebook/react-native/pull/28354

On `RN 0.63.x` due to above mentioned commit `createManifest.js` is trying to find `package.json` one level higher than it is situated.

**Comment by brentvatne** [comment]
i think you can override the PROJECT_ROOT option in your build phases to make it whatever you like to resolve the issue

**Comment by todorone** [comment]
@brentvatne I was able to resolve issue by adjusting `PROJECT_ROOT` variable and adjusting run path in `Bundle React Native code and images` build phase of the project. Sorry for ping...

**Comment by brentvatne** [comment]
we could possibly add a conditional to handle this for 0.63+

**Comment by brentvatne** [comment]
@todorone - i tried to reproduce this on a new 0.63 project and i was unable to. i created a new project and installed expo-updates on it and the release build worked as expected.

given your description of the problem i attempted a fix: https://github.com/expo/expo/commit/a566b2afecac8b8d922df0046b1eacc16d5757fb

`expo-updates@0.2.14` includes this code. please let me know if it resolves your issue

**Comment by todorone** [comment]
@brentvatne New version works perfect for me, thanks!

**Pull request merged**
