### PR TITLE
[gl-cpp] Support for 64 bit architecture and new JSC

### LINKED ISSUE #3773: GLView crashing in bare project
### Environment

  Expo CLI 2.11.9 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.5.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.1.0.0 AI-173.4907809

### Target

A real Android Pie device

### Steps to Reproduce

1. `expo init --template bare-minimum`
2. `yarn add expo-gl`, `yarn add expo-gl-cpp`
3. Adding `GLPackage` to MainApplication.java
4. Adding `GLView` from `expo-gl` to the app component
5. `yarn android`

### Expected Behavior

App should not crash and show at least a black box.

### Actual Behavior

App crashes and closes immediately after opening. Just got a very short glimpse at the black box. This happens always - even if I don't pass the `onContextCreate` param or trying to paint a black box on the canvas.

The debug log from Android Studio says:

> E/SoLoader: couldn't find DSO to load: libexpo-gl.so caused by: dlopen failed: "/data/data/com.chllng/lib-main/libexpo-gl.so" is 32-bit instead of 64-bit
> E/AndroidRuntime: FATAL EXCEPTION: mqt_js
>                   Process: com.chllng, PID: 16188
>                   java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libexpo-gl.so caused by: dlopen failed: "/data/data/com.chllng/lib-main/libexpo-gl.so" is 32-bit instead of 64-bit

If I add `ndk.abiFilters "armeabi-v7a", "x86"`, this error goes, but I got:

> A/libc: Fatal signal 7 (SIGBUS), code 1 (BUS_ADRALN), fault addr 0x2e in tid 25832 (mqt_js), pid 25760 (com.chllng)

Any ideas how to solve this?

### PR DESCRIPTION
**Pull request by tsapeta**
# Why

Fixes #3773 

# How

- [x] Reworked `expo-gl-cpp` building and packaging process to use [jsc-android](https://www.npmjs.com/package/jsc-android) package from npm instead of webkit repository. It makes things easier to update in the future.
- [x] Updated `expo-gl-cpp` binaries linked with new JSC and built for 64-bit architecture.
- [x] Added `expo-gl-cpp` as a dependency of `expo-gl`, so there is no need to install both packages.

### CODE REVIEW

**Comment by kWeb24** [comment]
@tsapeta When can we expect it?

**Comment by tsapeta** [comment]
@kWeb24 I'm working on it right now, unfortunately I encountered a crash just after the `.so` library for `expo-gl` is loaded. I can't give you any estimation right now 😅 

Also, just to clarify, this pull request is **not** going to enable 64-bit support in Expo Client, but just in `expo-gl` unimodule. Expo Client will get such support in a separate task and pull request.

**Comment by kWeb24** [comment]
@tsapeta That's exactly what I need. I'm trying to replace `react-native-webgl` package with `expo-gl` in non-expo project. 

Let's hope that we are not talking about months here. 🙃 

Good luck then. ;)

**Comment by tsapeta** [comment]
@kWeb24 Unfortunately it may take a bit more time as we found a compatibility issue between react-native 0.58 and 0.59. We used to take JavaScriptContext reference from React Native context and utilize it in our C++ code. However, in 0.59 this reference is not pointing to the same thing as previously - it points to JSI object instead. We need to find a way to pick a pointer to the same object as previously or rewrite some parts of our code or even change things upstream 😞

**Comment by kWeb24** [comment]
@tsapeta Not good. So i'm stuck with `react-native-webgl` for now. 

Changing the package will be quite simple so I have to wait for the fix. ;)

**Comment by JuicyPasta** [comment]
What packages can we revert to make this work in the mean time?

**Comment by danielreuterwall** [comment]
Any updates on new releases for expo-gl and expo-gl-cpp to include these changes?

When I upgraded to react-native 0.59.8 the GLView stopped working and gave me _unrecognized selector sent to instance_ from `ExponentGLObjectManager.createContextAsync`. Could this be related?

**Comment by wkozyra95** [comment]
Fixes are released as rc versions and a normal release will be done with sdk33.

**Comment by danielreuterwall** [comment]
I've tried the new release candidates but no luck. I've tried to create a new project with `react-native init` and followed the unimodules install instructions. Got the same error when I added a `GLView`.

```Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[RCTCxxBridge jsContextRef]: unrecognized selector sent to instance 0x7fddaf50ade0```

Is this related or should I create a new issue?

**Comment by tsapeta** [comment]
@danielreuterwall have you used `react-native-unimodules` in `rc` version as well?

**Comment by danielreuterwall** [comment]
I thought about that just after I posted my comment. I have only tried with
the 0.3.1 version.

I'll give it a try in the morning and keep you posted.

Thanks for your quick response!

**Comment by danielreuterwall** [comment]
Ok, so I've upgraded `react-native-unimodules` to `0.4.0-alpha.3`.
I had to make a change in `AppDelegate.m` in `extraModulesForBridge` and remove `andExperience:nil` as adviced in another issue. I also needed to add `lodash.omit` and `lodash.pick` (needed in `NativeViewManagerAdapter)` to get things running.

Now the app starts but crashes in `UMReactNativeAdapter` in the 0.59 fix in `javaScriptContextRef`.

Any advice on how to proceed?

**Comment by tsapeta** [comment]
@danielreuterwall I've just initialized new project with `react-native@0.59.8` and these prerelease unimodules and seems like GL works as expected for me.
Could you post here the results of `yarn list react-native @unimodules/core @unimodules/react-native-adapter expo-gl expo-gl-cpp` command?

**Comment by danielreuterwall** [comment]
Ok, here's the output:
```
├─ @unimodules/core@2.0.0-rc.1
├─ @unimodules/react-native-adapter@2.0.0-rc.1
├─ expo-gl-cpp@5.0.0-rc.0
├─ expo-gl@5.0.0-rc.0
└─ react-native@0.59.8
```

**Comment by tsapeta** [comment]
Weird, that's exactly the same as I used in my freshly new project 🤔 Could you add a breakpoint there and check if the `_bridge` points to the correct object which has `runtime` property?

**Comment by danielreuterwall** [comment]
Yeah it does have the `runtime` property but it's `NULL`.

I guess I must have done something wrong as it works for you but I cannot figure it out. I followed the same unimodules install guide as I've done before 0.59 gut with the upgraded versions.

Any ideas?

**Comment by danielreuterwall** [comment]
I got it now... I had the simulator set to `Debug JS Remotely`. When I stopped debugging the GLView working and the context got created. Can't believe I missed that.

Just a quick final question, are there plans for allowing debugging? That would help a lot :)

Thanks for your quick response, top class!!!

**Comment by wkozyra95** [comment]
When you have debugging enabled all js code is executed in the browser, react-native would need to support native debugger to make that possible

**Comment by danielreuterwall** [comment]
Got it!
Thanks a again for great support and truly great stuff that you're delivering.

**Pull request closed without merging**
