### PR TITLE
Document --example flag

### PR DESCRIPTION
**Pull request by karlhorky**
# Why

The `--example` flag for `create-expo-app` is undocumented.

# How

I added a section to document the `--example` flag on the [Create a new app](https://docs.expo.dev/get-started/create-a-new-app/) docs page

# Test Plan

Check whether the documentation makes sense like this

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [x] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

# Related

Companion PR in the Expo Examples repo:

- https://github.com/expo/examples/pull/411

# Caveats

The `create-expo-app` CLI still does not have the documentation for the `--example` flag when showing the help via the `--help` flag:

```
$ npx create-expo-app --help
Usage: create-expo-app <path> [options]

Creates a new Expo project

Options:
  -V, --version         output the version number
  -y, --yes             Use the default options for creating a project
  --no-install          Skip installing npm packages or CocoaPods.
  -t, --template [pkg]  NPM template to use: blank, tabs, bare-minimum. Default: blank
  -h, --help            output usage information

  The package manager used for installing
  node modules is based on how you invoke the CLI:

   npm: npm create expo-app
  yarn: yarn create expo-app
  pnpm: pnpm create expo-app
```

There should probably be another PR done for this, maybe here cc @EvanBacon 

https://github.com/expo/expo/blob/5709b55bf2aa838dbd49fa5411a61fad679afd90/packages/%40expo/cli/src/prebuild/index.ts#L28-L45

### CODE REVIEW

**Comment by karlhorky** [comment]
@amandeepmittal oh, that's a shame, undocumented flags are very frustrating for users.

Maybe you would consider at least creating a PR to the `--help` flag docs that I mentioned in the Caveats section of the description above?

**Comment by karlhorky** [comment]
> Yeah, if you want, you can create a PR to display `--example` in the `npx create-expo-app --help`. Let me know, if you don't want to, so that I can forward that request internally.

I can do it, is this the correct location for that PR?

https://github.com/expo/expo/blob/5709b55bf2aa838dbd49fa5411a61fad679afd90/packages/%40expo/cli/src/prebuild/index.ts#L28-L45

**Comment by amandeepmittal** [comment]
Yeah, that file looks fine to me.

**Comment by karlhorky** [comment]
@amandeepmittal done, PR open here:

- https://github.com/expo/expo/pull/21766

**Pull request closed without merging**
