### PR TITLE
added documentation for location permissions scope on ios/more details for associatedDomains config in app.json

### PR DESCRIPTION
**Pull request by dereknelson**
# Why
https://github.com/expo/expo/issues/3130#issuecomment-451778292

Added: 
> **Note (iOS):** SDK 32 and up will return  `permissions` key, which contains: `location: { ios } ` where `ios` which is an object of type: { scope: 'whenInUse' | 'always' | 'none' }

Under Expo.Permissions.LOCATION

Also added to configuration:
> An array that contains Associated Domains for the standalone app. **See apple's docs for config: https://developer.apple.com/documentation/uikit/core_app/allowing_apps_and_websites_to_link_to_your_content/enabling_universal_links
      Entries must be prefixed with "www."**

### CODE REVIEW

**Comment by esamelson** [comment]
Hey @dereknelson - thanks for taking care of this! When you get a chance, could you rebase so that we can ensure the failing tests are not due to your changes? Thanks 😄

**Comment by dereknelson** [comment]
@esamelson pretty sure that did it - however I'm not terribly familiar with rebasing and now I'm rebasing from a separate repo, so I'm gonna post my steps to ensure I did it correctly:
1. `git remote add upstream https://github.com/expo/expo.git`
2. `git fetch upstream`
3. `git rebase upstream/master`
4. `git push`

**Comment by esamelson** [comment]
Hey @dereknelson - sorry for the slow followup here. I'm not sure exactly what happened but it looks like there are now a bunch of other unrelated changes in this PR. 🤔  Maybe the easiest thing to do would be to check out a fresh branch from master and cherry pick your 3(?) commits on top again? Sorry for the trouble!!

**Comment by dereknelson** [comment]
@esamelson no worries! I reset my master branch to the upstream and added my changes on top of it.

**Comment by esamelson** [comment]
@dereknelson - not sure exactly what happened (maybe a bad merge?) but this PR is still showing way more commits and files edited than it should. Can you try doing the same thing again, but instead of merging your changes, cherry-picking or rebasing them on top of expo's master?

**Comment by dereknelson** [comment]
@esamelson sorry this is such a process - I'm in way over my head with git here. made a new pull request that will hopefully solve all this https://github.com/expo/expo/pull/3298

**Pull request closed without merging**
