### PR TITLE
[expo-auth-session][expo-linking] Fix hostUri not present in new manifests

### PR DESCRIPTION
**Pull request by wschurman**
# Why

https://github.com/expo/expo/pull/18103 noticed that expo-auth-session and expo-linking had issues with the change made in https://github.com/expo/expo/pull/17865, but check packages doesn't run in non-touched packages so we didn't find out.

# How

`hostUri` isn't present at all in modern manifests, so it's unclear what the right solution should be. For now, we can just remove it (same runtime behavior as before this PR but correct types).

# Test Plan

`et cp expo-auth-session expo-linking`

### CODE REVIEW

**Review by ide — APPROVED** [review]

**Review by bbarthec — APPROVED** [review]

**Comment by ide** [comment]
@brentvatne merged in https://github.com/expo/expo/commit/e893ff2b01e108cf246cec02318c0df9d6bc603c
https://github.com/expo/expo/commit/6e131f2da851a47c3a24eb3d6fc971a1a7822086 to unblock QA. I don't have a strong opinion on whether to close this PR or rebase + fix merge conflicts on top of it, just wanted to give context.

**Review by brentvatne — APPROVED** [review]
we'll want to revert https://github.com/expo/expo/commit/e893ff2b01e108cf246cec02318c0df9d6bc603c and https://github.com/expo/expo/commit/6e131f2da851a47c3a24eb3d6fc971a1a7822086 (temporary fixes for this issue to unblock publishing)

**Comment by wschurman** [comment]
Looks like expo-auth-session may be more broken than we already knew due to the missing `hostUri` field in the manifest. New manifests don't have this field (it's injected into only classic manifests on the server).

See the TODOs in the tests for breakage.

**Comment by wschurman** [comment]
Looking more into this, we put this field into new manifests in development only. Thus, this fix is incorrect.

**Pull request closed without merging**
