### PR TITLE
[templates][sdk34] Update to SDK 34

### PR DESCRIPTION
**Pull request by bbarthec**
# Why

Part of #4437

# Things to be done
- [ ] update all `.lock` files
- [ ] publish templates

### CODE REVIEW

**Comment by brentvatne** [comment]
@bbarthec - I can take care of publishing the bare template once it's ready to go. I want to make a few changes to it before shipping, but want to wait until everything else is ready so I can test it end-to-end.

**Comment by bbarthec** [comment]
@brentvatne, roger that! 😄

**Comment by brentvatne** [comment]
I still think that it is useful to have this as a base branch though! So I'll keep the PR open

**Comment by brentvatne** [comment]
closing this due to https://github.com/expo/expo/commit/7df1fe62b6a4d507db20bed592ee9852e64ba69f

**Pull request closed without merging**
