### PR TITLE
[docs] change class app to function app

### PR DESCRIPTION
**Pull request by trupakufi**
FontsLoadAsync example was written with class component, I did it with function components and used react hooks.

# Why

Because I think that work with funcitons is better and more pratic, and hooks are amazing.

# How

I onlu convert it to a function component.

# Test Plan

I was auto tested, but also it will work effectively. Try it!
# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [x] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Comment by amandeepmittal** [comment]
Hey @mariovarela99, thanks for taking a stab at it. The example uses class components to show an alternative method for legacy code/apps. For using function components, the docs suggest using `useFonts` hook.  The description before the code snippet also mentions this.

**Comment by mariovarela99** [comment]
> Hey @mariovarela99, thanks for taking a stab at it. smile
> 
> The example uses class components to show an alternative method for legacy code/apps. For using function components, the docs suggest using `useFonts` hook. The description before the code snippet also mentions this.

ham, ok, I didn't pay attention to that part, but it's ok. No stress, thanks for your attention.

**Comment by mariovarela99** [comment]
> > Hey @mariovarela99, thanks for taking a stab at it. smile
> > The example uses class components to show an alternative method for legacy code/apps. For using function components, the docs suggest using `useFonts` hook. The description before the code snippet also mentions this.
> 
> @amandeepmittal  Ham, ok, I didn't pay attention to that part, but it's ok. No stress, thanks for your attention.

**Comment by amandeepmittal** [comment]
No worries at all @mariovarela99 😄

**Pull request closed without merging**
