### PR TITLE
[SDK-51] fix(metro-runtime): Update native LoadingView to support react-native 0.75

### PR DESCRIPTION
**Pull request by gabrieldonadel**
# Why

Same as https://github.com/expo/expo/pull/30606 but for SDK-51

# How

Update metro-runtime LoadingView to dynamic import from react-native and support both react-native 0.74 and 0.75 at the same time

# Test Plan

Test expo-router using the create-expo-app using react-native 0.74 and 0.75

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Review by byCedric — APPROVED** [review]

**Comment by dejagersh** [comment]
I suspect this now breaking apps:

image

@byCedric @gabrieldonadel 

I opened a thread on the Expo discord and there's more people

**Comment by KristianLentino99** [comment]
@byCedric @gabrieldonadel this breaks the app, more details on the expo Discord [here](https://discord.com/channels/695411232856997968/1273381163787882619)

**Comment by brentvatne** [comment]
is anyone able to provide a minimal reproducible example for the issue here?

**Comment by marklawlor** [comment]
I can see a scenario where a custom`tsconfig`/`babel` could be breaking your applicaition

For example turning off `esModuleInterop` coudl cause your `import` to transpile differently. Instead of transpiling `import 'package'` to `require('package').default`, it would compile to `require('package')` (the old TS behaviour) https://www.typescriptlang.org/tsconfig/#esModuleInterop.

**Pull request merged**
