### PR TITLE
[expo-auth-session] allow google updating auth result

### PR DESCRIPTION
**Pull request by imnotjames**
# Why

when the promptAsync function is called multiple times the operations
for authentication complete as expected but do not correctly update the
result sent back to the caller.

this is because we pass fullResult into
the `useEffect` dependencies and default to using fullResult even if we've
just requested a new result

# How

to fix this I've dropped the code that prevents an update of the `fullResult` if `fullResult` is already set

# Test Plan

no automated tests are in place with the Google provider but I have verified this by making multiple authentications against Google and confirmed that the token makes its way back into the application - when it was not before

### CODE REVIEW

**Comment by Jamedjo** [comment]
Also resolves https://github.com/expo/expo/issues/11714 and helps turn https://github.com/expo/expo/issues/11131 into https://github.com/expo/expo/issues/9677

**Comment by nicksinai** [comment]
Hey there, seems like this fix wasn't merged successfully. I'm having this same issue (#11714). Any plans for this to be fixed? Otherwise, any workarounds?

**Review by EvanBacon — APPROVED** [review]
LGTM, maybe just update the changelog.

**Comment by simoneb** [comment]
@EvanBacon we're impacted by the issue addressed in this PR and I'm happy to see it merged. What's the best way to keep track of when it will be released?

**Comment by EvanBacon** [comment]
Hard to say for sure since it's part of the Expo SDK, it could be a while before it's published again. 
Because it's a pure JS package you could easily clone the expo/expo repo, cd into `packages/expo-auth-session`, change the name to something like `@simoneb/expo-auth-session` then republish it for use in your project.

**Comment by simoneb** [comment]
Thanks for the follow up. I'm not in a rush to get this solved, we have an open issue in one of our apps which is caused by this issue so we're keeping an eye on it to check when we can upgrade the SDK and see it solved. Hence the question, I'm not looking for a temporary solution but I would like to know how to find when it's solved in the SDK.

**Pull request merged**
