### PR TITLE
[android] call the correct BranchManager method

### PR DESCRIPTION
**Pull request by n-sviridenko**
# Why

The reason is [here](https://github.com/expo/expo/commit/e7863f268e2c1a0256bd001c682ae3c88656316a#r34224549)

# How

Please read the chat linked above.

# Test Plan

Please read the chat linked above.

### CODE REVIEW

**Comment by n-sviridenko** [comment]
1. `host.exp.exponent.MainActivity` doesn't inherit `com.facebook.react.ReactActivity`
2. there is no method accepting `com.facebook.react.ReactActivity` in RNBranch
3. however in RNBranch there is a method accepting `android.app.Activity` which is a superclass for `host.exp.exponent.MainActivity`

**Review by esamelson — APPROVED** [review]
makes sense, thanks for the PR @n-sviridenko . I'll try and get a new version pushed out in the next day or so.

**Comment by n-sviridenko** [comment]
@esamelson we're looking forward to seeing it released. in the meanwhile, is there any way to install it without waiting for the release?

**Comment by esamelson** [comment]
you can try building the `expokit`/`expoview` package yourself by cloning this repo and checking out the sdk-33 branch. ymmv though

**Comment by esamelson** [comment]
published `expokit@33.0.6` with this fix!

**Comment by n-sviridenko** [comment]
@esamelson thanks a lot for a quick push!

вт, 9 июля 2019 г. в 2:32, Eric Samelson <notifications@github.com>:

**Pull request merged**
