### PR TITLE
[WIP] Android ContactsModule Updates: Bug Fixes + Perf Improvement

### PR DESCRIPTION
**Pull request by tiny-dancer**
solves https://github.com/expo/expo/issues/482 and https://github.com/expo/expo/issues/877 as well as increases performance.

highlights around moving base query from targeting phone content to contact data content, heavily deriving from [react-native-contact](https://github.com/rt2zz/react-native-contacts). 

TODO:
- [ ] expand tests to have seeded/stable data to test against (does this exist?)
- [ ] verify field compatibility beyond email and phone

currently: expo contacts being created out of phone numbers, meaning:
  - contacts without a phone number are not retrieved
  - contacts with X amount of phone numbers are [duplicated X times](https://github.com/expo/expo/issues/877).
  - querying by a single id can lead to multiple results, throwing [promise error](https://github.com/expo/expo/issues/482) 

a side effect is performance issues:
  - base query is pulling phone numbers, any additional data is additional queries.
  - querying phone numbers leads to a larger than necessary query response
    - if each contact has 2 phone numbers, phone based query will process twice as many items than necessary

these updates also led to substantial perf improvements, below our timed results of running test-suite on my nexus 6p (not meant for concrete numbers but helps paint the picture):

before
screenshot_20171231-154423

after
screenshot_20171231-154127

Open questions: 
- if this approach makes sense to expo team, potential option: directly depending on react-native-contacts in expo sdk and wrapping it in the sdk js code for current api compatibility. quick win for getting create, update, delete, search by "matching string" as well.

### CODE REVIEW

**Comment by brentvatne** [comment]
Thank you for the PR @tiny-dancer! It looks like you put a lot of work into this.

@aalices is the maintainer of the Contacts API, and I wasn't aware of it at the time I suggested you submit a PR for this, but I think she may be working on a related change (I'm on holiday at the moment and not totally up to speed). If you want more details about the current state of the API her username is `@awarchal` on our Slack. I'd sync with her before doing any other work on this.

Also -- we don't want to include Robolectric tests in our codebase -- because we want the same API between iOS and Android, we run our tests through JS. We use this https://github.com/expo/test-suite as our main way of testing these types of APIs :)

**Review by aalices — CHANGES_REQUESTED** [review]
@tiny-dancer as I mentioned here: https://github.com/expo/expo/issues/877#issuecomment-354794334 we don't need so many changes to improve the performance. I can take care of that part. Anyway, if you still want to implement adding/removing/etc. stuff feel free but a couple things:
- extending the API requires adding features also for iOS and exposing them in JS (see https://github.com/expo/expo-sdk repo )
- make sure you commit only necessary files (omit `generated` dir, any `-lock` files and pother project specific ones) also do not modify `abi_xxx` stuff
- changing whole module to be a copy of another library is not really necessary here :)

**Comment by tiny-dancer** [comment]
> Actually it seems that changing query won't actually fix this (but will include contacts without a phone number).

yes, you're correct my comment on response size from the query was misguided.  the primary change appears to be the receiving of a bulk of the data in one query (phone, email, org) for all contacts vs several subsequent queries per iteration in loop. from `test-suite` test duration: 1 query (~200ms) vs several hundreds (~4500ms).

> ContactsContract.Data.CONTENT_URI will create an entry for every available contact info (phone, mail, name, whatever) so where's going to be even more duplicates :(

the contact ids are stored as a [key in a hash](https://github.com/tiny-dancer/expo/blob/8242b368ef317b60ad94c39c3c61b5dea47c36bc/android/expoview/src/main/java/versioned/host/exp/exponent/modules/api/ContactsModule.java#L199), a contact is either created or updated as appropriate for each iteration

> changing whole module to be a copy of another library is not really necessary here :)

heh, potentially yes but was a quick and effective way to get a baseline performance comparison on differing implementation.

> make sure you commit only necessary files (omit generated dir, any -lock files and pother project specific ones) also do not modify abi_xxx stuff

will do, some misses on the WIP open here, thanks.

> extending the API requires adding features also for iOS and exposing them in JS (see expo/expo-sdk repo )

depending how this pull request plays out, would likely do this seperately.

thanks for your response, sorry for my delay!

**Comment by tiny-dancer** [comment]
Never did clarify in above comment. @aalices, Whats your preference with this PR, tidy up or disregard?

**Comment by aalices** [comment]
Sorry for that! Okay, good catch with the perf. case! I've actually did some changes for this but I suppose your solution would be even more effective. I would go for making another PR - this would be probably easier than cleaning up this one. 

For the api changes: if I get you right, you want me to first review the Android side and then continue to implement iOS/JS ? If we want to test this we need to have JS code anyway :)

**Comment by tiny-dancer** [comment]
> I would go for making another PR - this would be probably easier than cleaning up this one.

ten four 👍  i'll look to get that opened up in the next couple days here.

> if I get you right, you want me to first review the Android side and then continue to implement iOS/JS ? 

slightly correct, i meant the android perf with the _same api_ will be one PR and then api changes will be a separate PR (inclusive of android, ios, + js repo)

**Pull request closed without merging**
