### PR TITLE
[expo-modules-core] Ensure `uuid.v4` and `uuid.v5` imports available on old architecture

### PR DESCRIPTION
**Pull request by andrejpavlovic**
# Why

It seems that `globalThis?.expo?.uuidv4` is undefined on iOS when this module is loaded. As a result, when trying to call `uuid.v4` later in the code, it keeps throwing `Native UUID version 4 generator implementation wasn't found in 'expo-modules-core'` even though `globalThis?.expo?.uuidv4` at that point is available.

I'm assuming in new architecture `globalThis?.expo?.uuidv4` is set synchronously, so this would not be an issue. In old architecture however, it would be best to reference this value when executing `v4` or `v5` calls themselves.

# How

Use direct reference to `globalThis?.expo?.uuidv4` from inside `uuidv4()` functions to avoid referencing a stale value.

# Test Plan

On iOS the error stops being thrown when calling `uuid.v4` within a component.

```typescript
import { uuid } from 'expo-modules-core'

export const MyComponent = () => {
  useEffect(() => {
    console.log(uuid.v4())
  }, [])
  return null
}
```

# Checklist

- [*] I added a `changelog.md` entry and rebuilt the package sources according to [this short guide](https://github.com/expo/expo/blob/main/CONTRIBUTING.md#-before-submitting)
- [*] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).
- [*] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)

### CODE REVIEW

**Review by Kudo — CHANGES_REQUESTED** [review]
hi there! thanks for the fix. could you help to run the following command the build js files? that would help to resolve the check-packages ci error
```sh
$ cd packages/expo-modules-core
$ yarn prepare
```

**Comment by andrejpavlovic** [comment]
> hi there! thanks for the fix. could you help to run the following command the build js files? that would help to resolve the check-packages ci error

@Kudo  done!

**Review by Kudo — APPROVED** [review]
thanks again for having the fix!

**Comment by Thanaen** [comment]
Hello ! I also have this problem in version 51.0.39. Would it be possible to port this fix to version 51?

**Pull request merged**
