### PR TITLE
fix(expo-server): Fix headers not being passed as raw headers flat array in Vercel adapter

### LINKED ISSUE #29431: Vercel server deployment crashes in latest build
### Minimal reproducible example

https://github.com/younes200/expo-router-issue

### Which package manager are you using? (Yarn is recommended)

bun

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

metro

### Summary

The recent deployment of our project on Vercel encountered difficulties, leading to a crash and displaying a 500 Internal Server Error.

```
Unhandled Rejection: TypeError: The argument 'headers' is invalid. Received [ [ 'content-type', 'text/plain' ] ]
at ServerResponse.writeHead (node:_http_server:373:15)
at ServerResponse.n.writeHead (/opt/rust/nodejs.js:7:2831)
at respond (/var/task/node_modules/@expo/server/build/vendor/vercel.js:62:9)
at /var/task/node_modules/@expo/server/build/vendor/vercel.js:16:16
at processTicksAndRejections (node:internal/process/task_queues:95:5)
at Server.<anonymous> (/opt/rust/nodejs.js:1:10455)
at Server.<anonymous> (/opt/rust/nodejs.js:7:3709) {
code: 'ERR_INVALID_ARG_VALUE'
}
Node.js process exited with exit status: 128. The logs above can help with debugging the issue.
```

Steps to replicate:

- Export the project with the "output" set to "server" : `expo export -p web`.
- Deploy to Vercel following the [documentation](https://docs.expo.dev/router/reference/api-routes/#vercel) using `vercel deploy -prod`

Vercel deployment : https://expo-router-issue-muji978j0-launchtrack.vercel.app/

By removing the nested array provided by vercel solve the issue :  [#29259 ]

### Environment

```
 expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
      npm: 10.2.4 - ~/.nvm/versions/node/v20.11.0/bin/npm
    Managers:
      CocoaPods: 1.15.2 - /Users/younes/.gem/ruby/3.3.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11330709
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 7.5.0
    Expo Workflow: managed
```

### PR DESCRIPTION
**Pull request by kitten**
Resolves #29431

# Why

The missing `.flat()` means that we were passing headers as a list of tuples rather than a flat array in the `request.rawHeader` format.
See: https://nodejs.org/api/http.html#responsewriteheadstatuscode-statusmessage-headers

# How

Add missing `.flat` call

# Test Plan

Manually deployed an Expo web app to Vercel to validate the changes are working.

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Review by EvanBacon — APPROVED** [review]

**Comment by karlhorky** [comment]
@kitten @EvanBacon thanks for this PR!

Would it be possible to get a new published release of `@expo/server` with this change? 

The latest version [`@expo/server@0.4.4`](https://unpkg.com/browse/@expo/server@0.4.4/build/vendor/vercel.js) does not have this change:

```js
async function respond(res, expoRes) {
    res.statusMessage = expoRes.statusText;
    res.writeHead(expoRes.status, expoRes.statusText, [...expoRes.headers.entries()]);
```

Currently we're applying a patch to the package as a workaround, but we're trying to avoid passing this patch along to students.

**Comment by karlhorky** [comment]
Oh it looks like there's a canary release [`@expo/server@0.4.4-canary-20240628-1ba8152`](https://unpkg.com/browse/@expo/server@0.4.4/build/vendor/vercel.js) that's been published 👀 

```js
async function respond(res, expoRes) {
    res.statusMessage = expoRes.statusText;
    res.writeHead(expoRes.status, expoRes.statusText, [...expoRes.headers.entries()].flat());
```

We'll recommend this for now for the students.

**Comment by salieflewis** [comment]
How do I go about bumping the `@expo/server` version being used by `expo`

**Comment by karlhorky** [comment]
@salieflewis maybe you're looking for npm Overrides / Yarn Resolutions / pm Overrides?

**Comment by salieflewis** [comment]
> @salieflewis maybe you're looking for npm Overrides / Yarn Resolutions / pm Overrides?

I'll take a look into this, thank you

**Comment by davidfurlong** [comment]
there's no way this should be under a canary, it's a bugfix, and is wasting tonnes of users' time

**Comment by thomasmorice** [comment]
> Oh it looks like there's a canary release [`@expo/server@0.4.4-canary-20240628-1ba8152`](https://unpkg.com/browse/@expo/server@0.4.4-canary-20240628-1ba8152/build/vendor/vercel.js) that's been published 👀
> 
> ```js
> async function respond(res, expoRes) {
>     res.statusMessage = expoRes.statusText;
>     res.writeHead(expoRes.status, expoRes.statusText, [...expoRes.headers.entries()].flat());
> ```
> 
> We'll recommend this for now for the students.

This works but creates a new issue where I have a request using "Content-Type": "multipart/form-data" which does not work anymore...

**Comment by karlhorky** [comment]
@thomasmorice remember, the version I suggested above (and the other newer versions which have the fix) are canary releases - that means lower stability.

Since your new issue with multipart `Content-Type` is unrelated, I would suggest looking at other issues, trying the new versions, or creating a new issue with a full reproduction of your problem.

**Comment by karlhorky** [comment]
`@expo/server@0.5.0` was released 🎉 It includes the fix:

- `@expo/server@0.5.0`: [`/build/vendor/vercel.js`](https://unpkg.com/browse/@expo/server@0.5.0/build/vendor/vercel.js)

```js
async function respond(res, expoRes) {
    res.statusMessage = expoRes.statusText;
    res.writeHead(expoRes.status, expoRes.statusText, [...expoRes.headers.entries()].flat());
```

**Pull request merged**
