### PR TITLE
docs: Add correct implementation for meta tags with Head.Provider in …

### PR DESCRIPTION
**Pull request by Makhdoom-Sharif**
…expo-router

# Why

The current documentation for adding meta tags in a React Native Expo project using expo-router does not include the necessary step of wrapping the Head component with a Head.Provider. This omission can lead to errors when developers try to implement meta tags on the web platform. This PR corrects the documentation to prevent such issues.

# How

I modified the documentation to include the correct usage of the Head.Provider wrapper around the Head component. This ensures that meta tags are properly applied without causing errors related to react-helmet
# Test Plan

1. Create a new React Native Expo project.
2. Implement the provided example using expo-router to add meta tags.
3. Verify that wrapping the Head component inside Head.Provider works without errors and correctly applies the meta tags on the web platform.

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [x] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Comment by amandeepmittal** [comment]
I'm not sure if the Provider is required or not. We also don't mention any web specific behavior, for example, in this guide: https://docs.expo.dev/router/advanced/apple-handoff/#usage

Maybe @marklawlor can help in verifying this?

**Comment by Makhdoom-Sharif** [comment]
Hi @amandeepmittal,

Thank you for the feedback. I encountered an issue when trying to add meta tags using the `Head` component from `expo-router` in a React Native Expo project. Without wrapping the `Head` component in `Head.Provider`, I received errors related to `react-helmet`, which is used internally by `expo-router`.

After some investigation, I found that using `Head.Provider` resolves these errors and allows the meta tags to be correctly applied. Here’s a summary of the issue and solution:

**Issue:**
When using the `Head` component from `expo-router` to add meta tags, an error related to `react-helmet` occurs if the `Head` component is not wrapped in `Head.Provider`.

**Solution:**
Wrapping the `Head` component with `Head.Provider` resolves the error and allows the meta tags to be correctly applied on the web platform.

**Reproduction Steps:**
1. Create a new React Native Expo project.
2. Attempt to add meta tags using the `Head` component without wrapping it in `Head.Provider`.
3. Observe the error related to `react-helmet`.
4. Wrap the `Head` component in `Head.Provider` and observe that the error is resolved and meta tags are correctly applied.

Here’s the updated code example for the documentation:

```javascript
import Head from 'expo-router/head';
import { Text } from 'react-native';

export default function Page() {
  return (
    <>
      <Head.Provider>
        <Head>
          <title>My Blog Website</title>
          <meta name="description" content="This is my blog." />
        </Head>
      </Head.Provider>
      <Text>About my blog</Text>
    </>
  );
}
```

I hope this provides the necessary context for the change. If there are any further questions or if additional verification is needed, please let me know. Thank you!

**Comment by Makhdoom-Sharif** [comment]
Hi guys @amandeepmittal @markacola @Simek , any update on this?

**Comment by Makhdoom-Sharif** [comment]
Hello guys @amandeepmittal  @markacola @Simek .

**Comment by amandeepmittal** [comment]
Hey @Makhdoom-Sharif, I'll take a look at this week and get back to you. Sorry for the delay.

**Comment by Makhdoom-Sharif** [comment]
@amandeepmittal No problem at all! Take your time, and let me know if you need any further information or assistance.

**Comment by amandeepmittal** [comment]
Hey @Makhdoom-Sharif, if you are seeing this issue, please open a new issue and share a minimal reproducible example so our team can take a look.

From doc updates perspective, I'm closing this PR for now.

**Pull request closed without merging**
