### PR TITLE
[expo-constants] Add getter for expo client config

### PR DESCRIPTION
**Pull request by wschurman**
# Why

One common request is to have the ability to access the Expo Config (derived from app.json/app.js) in a consistent manner across classic and modern manifests. This PR adds a new constant, `expoConfig`, which contains the configuration generated by https://github.com/expo/expo-cli/blob/main/packages/config/src/Config.ts#L92.

- This is embedded in built applications via https://github.com/expo/expo/blob/master/packages/expo-constants/scripts/getAppConfig.js
- This is a subset of fields in the classic manifest. 
- This is in the `extra.expoConfig` field on modern manifests.

Part of ENG-4041.

# How

Add field and test.

# Test Plan

- Run test
- Run NCL with both `expo start` and `EXPO_SDK_VERSION=45.0.0 expo start --force-manifest-type=classic` (need to remove `runtimeVersion` key as well). Navigate to Constants. See the new field.

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] This diff will work correctly for `expo build` (eg: updated `@expo/xdl`).
- [ ] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Comment by ide** [comment]
What does `Constants.expoConfig` print in each type of build we support (am I missing any?)?

- Expo Go, modern manifest from Expo CLI
- Expo Go, modern manifest from EAS Update
- Expo Go, classic manifest from Expo CLI
- Expo Go, classic manifest from Classic Update service
- Development build (expo-dev-client), same 4x matrix as above
- Production build without expo-updates
- Production build with expo-updates, embedded manifest
- Production build with expo-updates, manifest from EAS Update

**Comment by jonsamp** [comment]
> What does `Constants.expoConfig` print in each type of build we support (am I missing any?)?
> 
> * Expo Go, modern manifest from Expo CLI
> * Expo Go, modern manifest from EAS Update
> * Expo Go, classic manifest from Expo CLI
> * Expo Go, classic manifest from Classic Update service
> * Development build (expo-dev-client), same 4x matrix as above
> * Production build without expo-updates
> * Production build with expo-updates, embedded manifest
> * Production build with expo-updates, manifest from EAS Update

I got the first four above, will do the rest this weekend: https://www.notion.so/expo/expo-constants-expoConfig-eaa3ee76eabe44db90f24b248dd1a103

Once I have them all, I can post them all in this PR for history's-sake.

**Comment by ide** [comment]
@jonsamp thanks, also I imagine your tests will help us write clear docs with examples too.

**Comment by wschurman** [comment]
@jonsamp you are a godsend

**Comment by jonsamp** [comment]
Here are all of them except for "Production build without expo-updates". (Also updated the doc with these shapes)

---

<details>
<summary>Expo Go, Expo CLI, classic manifest</summary>

```json
{
  "debuggerHost": "172.19.1.220:19000",
  "packagerOpts": {
    "https": false,
    "urlRandomness": null,
    "minify": false,
    "dev": true,
    "devClient": false,
    "lanType": "ip",
    "hostType": "lan",
    "scheme": null
  },
  "extra": {
    "TESTING_EXTRA_IN_APP_CONFIG": "TEST_VALUE"
  },
  "slug": "test-6-17",
  "updates": {
    "fallbackToCacheTimeout": 0
  },
  "splash": {
    "imageUrl": "http://172.19.1.220:19000/assets/./assets/splash.png",
    "image": "./assets/splash.png",
    "backgroundColor": "#ffffff",
    "resizeMode": "contain"
  },
  "isVerified": true,
  "_internal": {
    "dynamicConfigPath": null,
    "staticConfigPath": "/Users/jon/dev/test-6-17/app.json",
    "projectRoot": "/Users/jon/dev/test-6-17",
    "isDebug": false,
    "packageJsonPath": "/Users/jon/dev/test-6-17/package.json"
  },
  "hostUri": "172.19.1.220:19000",
  "ios": {
    "supportsTablet": true
  },
  "logUrl": "http://172.19.1.220:19000/logs",
  "icon": "./assets/icon.png",
  "platforms": [
    "ios",
    "android",
    "web"
  ],
  "userInterfaceStyle": "light",
  "sdkVersion": "45.0.0",
  "id": "@jonsamp/test-6-17",
  "bundleUrl": "http://172.19.1.220:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&strict=false&minify=false",
  "android": {
    "adaptiveIcon": {
      "foregroundImageUrl": "http://172.19.1.220:19000/assets/./assets/adaptive-icon.png",
      "foregroundImage": "./assets/adaptive-icon.png",
      "backgroundColor": "#FFFFFF"
    }
  },
  "__flipperHack": "React Native packager is running",
  "iconUrl": "http://172.19.1.220:19000/assets/./assets/icon.png",
  "name": "test-6-17",
  "orientation": "portrait",
  "web": {
    "favicon": "./assets/favicon.png"
  },
  "version": "1.0.0",
  "assetBundlePatterns": [
    "**/*"
  ],
  "mainModuleName": "node_modules/expo/AppEntry",
  "developer": {
    "tool": "expo-cli",
    "projectRoot": "/Users/jon/dev/test-6-17"
  }
}
```

</details>

<details>
<summary>Expo Go, classic update service, classic manifest</summary>

```json
{
  "extra": {
    "TESTING_EXTRA_IN_APP_CONFIG": "TEST_VALUE"
  },
  "slug": "test-6-17",
  "updates": {
    "fallbackToCacheTimeout": 0
  },
  "splash": {
    "imageUrl": "https://classic-assets.eascdn.net/~assets/4dc203c1f48ad8b1e9734613e88be661",
    "backgroundColor": "#ffffff",
    "image": "./assets/splash.png",
    "resizeMode": "contain"
  },
  "hostUri": "exp.host/@jonsamp/test-6-17",
  "ios": {
    "supportsTablet": true
  },
  "revisionId": "1.0.0-r.zxz-kJ3Q_",
  "icon": "./assets/icon.png",
  "platforms": [
    "ios",
    "android",
    "web"
  ],
  "locales": {},
  "originalFullName": "@jonsamp/test-6-17",
  "dependencies": [
    "@react-native-clipboard/clipboard",
    "expo",
    "expo-status-bar",
    "expo-updates",
    "react",
    "react-dom",
    "react-native",
    "react-native-web"
  ],
  "isVerified": true,
  "bundledAssets": [],
  "name": "test-6-17",
  "iconUrl": "https://classic-assets.eascdn.net/~assets/4e3f888fc8475f69fd5fa32f1ad5216a",
  "userInterfaceStyle": "light",
  "sdkVersion": "45.0.0",
  "id": "@jonsamp/test-6-17",
  "bundleUrl": "https://classic-assets.eascdn.net/%40jonsamp%2Ftest-6-17%2F1.0.0%2F7629d33e89b0213d73e4d6d8c543f3c3-45.0.0-ios.js",
  "android": {
    "adaptiveIcon": {
      "foregroundImage": "./assets/adaptive-icon.png",
      "backgroundColor": "#FFFFFF",
      "foregroundImageUrl": "https://classic-assets.eascdn.net/~assets/97dae5a0e62ad8551d8a31897b425e63"
    }
  },
  "orientation": "portrait",
  "web": {
    "favicon": "./assets/favicon.png"
  },
  "version": "1.0.0",
  "projectId": "8ce63709-b0a5-4425-9c98-ca09e427e07d",
  "currentFullName": "@jonsamp/test-6-17",
  "scopeKey": "@jonsamp/test-6-17",
  "releaseId": "feff7254-411b-4706-b62c-7f368a7418e1",
  "publishedTime": "2022-06-17T17:03:31.296Z",
  "commitTime": "2022-06-17T17:03:31.344Z",
  "bundleKey": "7629d33e89b0213d73e4d6d8c543f3c3",
  "releaseChannel": "default"
}
```

</details>

<details>
<summary>Expo Go, Expo CLI, modern manifest</summary>

```json
{
  "extra": {
    "TESTING_EXTRA_IN_APP_CONFIG": "TEST_VALUE"
  },
  "slug": "test-6-17",
  "android": {
    "adaptiveIcon": {
      "foregroundImageUrl": "http://172.19.1.220:19000/assets/./assets/adaptive-icon.png",
      "foregroundImage": "./assets/adaptive-icon.png",
      "backgroundColor": "#FFFFFF"
    }
  },
  "version": "1.0.0",
  "updates": {
    "fallbackToCacheTimeout": 0,
    "url": "https://u.expo.dev/8ce63709-b0a5-4425-9c98-ca09e427e07d"
  },
  "platforms": [
    "ios",
    "android",
    "web"
  ],
  "userInterfaceStyle": "light",
  "sdkVersion": "45.0.0",
  "runtimeVersion": {
    "policy": "sdkVersion"
  },
  "orientation": "portrait",
  "web": {
    "favicon": "./assets/favicon.png"
  },
  "assetBundlePatterns": [
    "**/*"
  ],
  "ios": {
    "supportsTablet": true
  },
  "_internal": {
    "dynamicConfigPath": null,
    "staticConfigPath": "/Users/jon/dev/test-6-17/app.json",
    "projectRoot": "/Users/jon/dev/test-6-17",
    "isDebug": false,
    "packageJsonPath": "/Users/jon/dev/test-6-17/package.json"
  },
  "hostUri": "172.19.1.220:19000",
  "icon": "./assets/icon.png",
  "splash": {
    "imageUrl": "http://172.19.1.220:19000/assets/./assets/splash.png",
    "image": "./assets/splash.png",
    "backgroundColor": "#ffffff",
    "resizeMode": "contain"
  },
  "iconUrl": "http://172.19.1.220:19000/assets/./assets/icon.png",
  "name": "test-6-17"
}
```

</details>

<details>
<summary>Expo Go, EAS Update, modern manifest</summary>

```json
{
  "extra": {
    "TESTING_EXTRA_IN_APP_CONFIG": "TEST_VALUE"
  },
  "slug": "test-6-17",
  "android": {
    "adaptiveIcon": {
      "backgroundColor": "#FFFFFF",
      "foregroundImage": "./assets/adaptive-icon.png"
    }
  },
  "version": "1.0.0",
  "updates": {
    "fallbackToCacheTimeout": 0,
    "url": "https://u.expo.dev/8ce63709-b0a5-4425-9c98-ca09e427e07d"
  },
  "platforms": [
    "ios",
    "android",
    "web"
  ],
  "userInterfaceStyle": "light",
  "sdkVersion": "45.0.0",
  "runtimeVersion": {
    "policy": "sdkVersion"
  },
  "assetBundlePatterns": [
    "**/*"
  ],
  "currentFullName": "@jonsamp/test-6-17",
  "splash": {
    "backgroundColor": "#ffffff",
    "resizeMode": "contain",
    "image": "./assets/splash.png"
  },
  "originalFullName": "@jonsamp/test-6-17",
  "ios": {
    "supportsTablet": true
  },
  "web": {
    "favicon": "./assets/favicon.png"
  },
  "orientation": "portrait",
  "icon": "./assets/icon.png",
  "name": "test-6-17"
}
```

</details>

<details>
<summary>Development build, Expo CLI, classic manifest</summary>

```json
{
  "slug": "test-6-17",
  "packagerOpts": {
    "scheme": "exp+test-6-17",
    "lanType": "ip",
    "minify": false,
    "urlRandomness": null,
    "https": false,
    "hostType": "lan",
    "devClient": true,
    "dev": true
  },
  "debuggerHost": "127.0.0.1:8081",
  "extra": {
    "TESTING_EXTRA_IN_APP_CONFIG": "TEST_VALUE"
  },
  "android": {
    "adaptiveIcon": {
      "foregroundImageUrl": "http://127.0.0.1:8081/assets/./assets/adaptive-icon.png",
      "foregroundImage": "./assets/adaptive-icon.png",
      "backgroundColor": "#FFFFFF"
    }
  },
  "bundleUrl": "http://127.0.0.1:8081/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&strict=false&minify=false",
  "icon": "./assets/icon.png",
  "_internal": {
    "packageJsonPath": "/Users/jon/dev/test-6-17/package.json",
    "projectRoot": "/Users/jon/dev/test-6-17",
    "staticConfigPath": "/Users/jon/dev/test-6-17/app.json",
    "isDebug": false,
    "dynamicConfigPath": null
  },
  "name": "test-6-17",
  "version": "1.0.0",
  "iconUrl": "http://127.0.0.1:8081/assets/./assets/icon.png",
  "hostUri": "127.0.0.1:8081",
  "userInterfaceStyle": "light",
  "updates": {
    "fallbackToCacheTimeout": 0
  },
  "orientation": "portrait",
  "web": {
    "favicon": "./assets/favicon.png"
  },
  "ios": {
    "bundleIdentifier": "com.jonsamp.test617",
    "supportsTablet": true
  },
  "sdkVersion": "45.0.0",
  "logUrl": "http://127.0.0.1:8081/logs",
  "__flipperHack": "React Native packager is running",
  "platforms": [
    "ios",
    "android",
    "web"
  ],
  "assetBundlePatterns": [
    "**/*"
  ],
  "mainModuleName": "node_modules/expo/AppEntry",
  "developer": {
    "projectRoot": "/Users/jon/dev/test-6-17",
    "tool": "expo-cli"
  },
  "splash": {
    "resizeMode": "contain",
    "backgroundColor": "#ffffff",
    "image": "./assets/splash.png",
    "imageUrl": "http://127.0.0.1:8081/assets/./assets/splash.png"
  }
}
```

</details>

<details>
<summary>Development build, classic update service, classic manifest</summary>

```json
{
  "slug": "test-6-17",
  "projectId": "8ce63709-b0a5-4425-9c98-ca09e427e07d",
  "extra": {
    "TESTING_EXTRA_IN_APP_CONFIG": "TEST_VALUE"
  },
  "android": {
    "adaptiveIcon": {
      "foregroundImage": "./assets/adaptive-icon.png",
      "backgroundColor": "#FFFFFF",
      "foregroundImageUrl": "https://classic-assets.eascdn.net/~assets/97dae5a0e62ad8551d8a31897b425e63"
    }
  },
  "bundleUrl": "https://classic-assets.eascdn.net/%40jonsamp%2Ftest-6-17%2F1.0.0%2Fe7b804bd7c1a80ee338928e44f4fc4f7-45.0.0-ios.js",
  "icon": "./assets/icon.png",
  "originalFullName": "@jonsamp/test-6-17",
  "dependencies": [
    "expo",
    "expo-dev-client",
    "expo-status-bar",
    "expo-updates",
    "react",
    "react-dom",
    "react-native",
    "react-native-web"
  ],
  "bundledAssets": [],
  "revisionId": "1.0.0-r.yIGt7K1Xo",
  "name": "test-6-17",
  "locales": {},
  "version": "1.0.0",
  "iconUrl": "https://classic-assets.eascdn.net/~assets/4e3f888fc8475f69fd5fa32f1ad5216a",
  "hostUri": "exp.host/@jonsamp/test-6-17",
  "userInterfaceStyle": "light",
  "id": "@jonsamp/test-6-17",
  "updates": {
    "fallbackToCacheTimeout": 0
  },
  "orientation": "portrait",
  "web": {
    "favicon": "./assets/favicon.png"
  },
  "ios": {
    "bundleIdentifier": "com.jonsamp.test617",
    "supportsTablet": true
  },
  "sdkVersion": "45.0.0",
  "currentFullName": "@jonsamp/test-6-17",
  "scopeKey": "@jonsamp/test-6-17",
  "releaseId": "2d8003db-0ee0-45ca-9144-2513f072b118",
  "platforms": [
    "ios",
    "android",
    "web"
  ],
  "publishedTime": "2022-06-18T21:02:18.175Z",
  "commitTime": "2022-06-18T21:02:18.221Z",
  "bundleKey": "e7b804bd7c1a80ee338928e44f4fc4f7",
  "releaseChannel": "default",
  "splash": {
    "resizeMode": "contain",
    "imageUrl": "https://classic-assets.eascdn.net/~assets/4dc203c1f48ad8b1e9734613e88be661",
    "image": "./assets/splash.png",
    "backgroundColor": "#ffffff"
  }
}
```

</details>

<details>
<summary>Development build, Expo CLI, modern manifest</summary>

```json
{
  "extra": {
    "TESTING_EXTRA_IN_APP_CONFIG": "TEST_VALUE"
  },
  "orientation": "portrait",
  "version": "1.0.0",
  "userInterfaceStyle": "light",
  "assetBundlePatterns": [
    "**/*"
  ],
  "ios": {
    "bundleIdentifier": "com.jonsamp.test617",
    "supportsTablet": true
  },
  "updates": {
    "url": "https://u.expo.dev/8ce63709-b0a5-4425-9c98-ca09e427e07d",
    "fallbackToCacheTimeout": 0
  },
  "runtimeVersion": {
    "policy": "sdkVersion"
  },
  "_internal": {
    "packageJsonPath": "/Users/jon/dev/test-6-17/package.json",
    "projectRoot": "/Users/jon/dev/test-6-17",
    "staticConfigPath": "/Users/jon/dev/test-6-17/app.json",
    "isDebug": false,
    "dynamicConfigPath": null
  },
  "hostUri": "192.168.0.78:8081",
  "android": {
    "adaptiveIcon": {
      "foregroundImageUrl": "http://192.168.0.78:8081/assets/./assets/adaptive-icon.png",
      "foregroundImage": "./assets/adaptive-icon.png",
      "backgroundColor": "#FFFFFF"
    }
  },
  "icon": "./assets/icon.png",
  "slug": "test-6-17",
  "web": {
    "favicon": "./assets/favicon.png"
  },
  "splash": {
    "resizeMode": "contain",
    "backgroundColor": "#ffffff",
    "image": "./assets/splash.png",
    "imageUrl": "http://192.168.0.78:8081/assets/./assets/splash.png"
  },
  "platforms": [
    "ios",
    "android",
    "web"
  ],
  "iconUrl": "http://192.168.0.78:8081/assets/./assets/icon.png",
  "sdkVersion": "45.0.0",
  "name": "test-6-17"
}
```

</details>

<details>
<summary>Development build, EAS Update, modern manifest</summary>

```json
{
  "extra": {
    "TESTING_EXTRA_IN_APP_CONFIG": "TEST_VALUE"
  },
  "orientation": "portrait",
  "version": "1.0.0",
  "userInterfaceStyle": "light",
  "assetBundlePatterns": [
    "**/*"
  ],
  "ios": {
    "bundleIdentifier": "com.jonsamp.test617",
    "supportsTablet": true
  },
  "updates": {
    "url": "https://u.expo.dev/8ce63709-b0a5-4425-9c98-ca09e427e07d",
    "fallbackToCacheTimeout": 0
  },
  "runtimeVersion": {
    "policy": "sdkVersion"
  },
  "android": {
    "adaptiveIcon": {
      "backgroundColor": "#FFFFFF",
      "foregroundImage": "./assets/adaptive-icon.png"
    }
  },
  "currentFullName": "@jonsamp/test-6-17",
  "web": {
    "favicon": "./assets/favicon.png"
  },
  "icon": "./assets/icon.png",
  "slug": "test-6-17",
  "splash": {
    "image": "./assets/splash.png",
    "resizeMode": "contain",
    "backgroundColor": "#ffffff"
  },
  "platforms": [
    "ios",
    "android",
    "web"
  ],
  "originalFullName": "@jonsamp/test-6-17",
  "sdkVersion": "45.0.0",
  "name": "test-6-17"
}
```

</details>

<details>
<summary>Production build with expo-updates, embedded manifest</summary>

```json
{
  "extra": {
    "TESTING_EXTRA_IN_APP_CONFIG": "TEST_VALUE"
  },
  "slug": "test-6-17",
  "android": {
    "adaptiveIcon": {
      "foregroundImage": "./assets/adaptive-icon.png",
      "backgroundColor": "#FFFFFF"
    }
  },
  "version": "1.0.0",
  "updates": {
    "fallbackToCacheTimeout": 0,
    "url": "https://u.expo.dev/8ce63709-b0a5-4425-9c98-ca09e427e07d"
  },
  "platforms": [
    "ios",
    "android",
    "web"
  ],
  "userInterfaceStyle": "light",
  "sdkVersion": "45.0.0",
  "runtimeVersion": {
    "policy": "sdkVersion"
  },
  "orientation": "portrait",
  "web": {
    "favicon": "./assets/favicon.png"
  },
  "assetBundlePatterns": [
    "**/*"
  ],
  "currentFullName": "@jonsamp/test-6-17",
  "splash": {
    "backgroundColor": "#ffffff",
    "resizeMode": "contain",
    "image": "./assets/splash.png"
  },
  "originalFullName": "@jonsamp/test-6-17",
  "ios": {
    "supportsTablet": true,
    "bundleIdentifier": "com.jonsamp.test617"
  },
  "icon": "./assets/icon.png",
  "name": "test-6-17"
}
```

</details>

<details>
<summary>Production build with expo-updates, EAS Update manifest</summary>

```json
{
  "extra": {
    "TESTING_EXTRA_IN_APP_CONFIG": "TEST_VALUE"
  },
  "slug": "test-6-17",
  "android": {
    "adaptiveIcon": {
      "backgroundColor": "#FFFFFF",
      "foregroundImage": "./assets/adaptive-icon.png"
    }
  },
  "version": "1.0.0",
  "updates": {
    "fallbackToCacheTimeout": 0,
    "url": "https://u.expo.dev/8ce63709-b0a5-4425-9c98-ca09e427e07d"
  },
  "platforms": [
    "ios",
    "android",
    "web"
  ],
  "userInterfaceStyle": "light",
  "sdkVersion": "45.0.0",
  "runtimeVersion": {
    "policy": "sdkVersion"
  },
  "assetBundlePatterns": [
    "**/*"
  ],
  "currentFullName": "@jonsamp/test-6-17",
  "splash": {
    "backgroundColor": "#ffffff",
    "resizeMode": "contain",
    "image": "./assets/splash.png"
  },
  "originalFullName": "@jonsamp/test-6-17",
  "ios": {
    "supportsTablet": true,
    "bundleIdentifier": "com.jonsamp.test617"
  },
  "web": {
    "favicon": "./assets/favicon.png"
  },
  "orientation": "portrait",
  "icon": "./assets/icon.png",
  "name": "test-6-17"
}
```

</details>

**Comment by jonsamp** [comment]
By the way, this change would make this doc a lot simpler: https://docs.expo.dev/eas-update/environment-variables/#creating-an-envts-file-to-get-environment

It is still necessary to define env vars twice: once during build time and once during publish time, but this will provide a common place to find the env var during development and in production.

**Comment by jonsamp** [comment]
Please let me know when this is merged and released. Once it is released, I can update the docs with this change!

**Comment by wschurman** [comment]
Friendly ping.

**Review by ide — APPROVED** [review]
Looks really consistent across all environments where modern manifests are used, and decently consistent between classic manifests and modern ones.

Looking through the example output, I had a few thoughts:

- It would be nice to sort the fields. This is something we can do in Expo CLI and in EAS Update on the server. I am actually surprised that the JSON passed through something that doesn't maintain object key order.
- Including all of the config fields in the manifest will get very verbose. I think we should have an allowlist of fields in Expo CLI that decides what to put in `manifest.extra.expoClient`. For instance, the android/ios/web config fields are meant for builds. We had a report last week of the servers timing out, which was because a manifest included unnecessarily large infoPlist field data. If a developer really wants to put that information in the manifest, they can duplicate it in "extra".

**Comment by Kudo** [comment]
@wschurman there's a type error (https://github.com/expo/expo/runs/7106453074?check_suite_focus=true) after this change. could you help to check when you get a chance?

**Pull request merged**
