### PR TITLE
[core] Export SharedObject and NativeModule classes

### PR DESCRIPTION
**Pull request by tsapeta**
# Why

To allow importing `SharedObject` and `NativeModule` classes from `expo-modules-core`

# How

- Extracted `ensureNativeModulesAreInstalled` to a separate file and added support for web
- Just export things installed globally
- Use JS implementation from web in `jest-expo`

# Test Plan

Tested in bare-expo on iOS.
I was not able to test it on Android though, looks like there are some other issues (maybe caused by RN upgrade to rc5?).
These changes shouldn't really make any difference as it's just JS that touches common C++ code.

### CODE REVIEW

**Review by Kudo — APPROVED** [review]

**Review by lukmccall — APPROVED** [review]
LGTM, I will test the android when we merge it 😉

**Comment by tsapeta** [comment]
Ok so I rebased this branch with the current `main` and looks like the problem is still there and hard to say what's causing it:

```
> Unable to install Expo modules: Error: Exception in HostFunction: java.lang.IllegalArgumentException: Could not find @ReactModule annotation in expo.modules.adapters.react.NativeModulesProxy
> TypeError: Cannot read property 'NativeModule' of undefined, js engine: hermes
> Running "main" with {"rootTag":11}
> Invariant Violation: "main" has not been registered. This can happen if:
   * Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
   * A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes
 ```

I'll try to dig a bit deeper when I find some time, but maybe someone already has an idea?

**Review by douglowder — APPROVED** [review]

**Comment by lukmccall** [comment]
> I'll try to dig a bit deeper when I find some time, but maybe someone already has an idea?

I've encountered that error before, but I'm not sure how I fixed it :/

**Review by gabrieldonadel — APPROVED** [review]

**Comment by lukmccall** [comment]
Thanks @Kudo! You remained about that problem and how I decided to solve it ;) 

We can add the `@ReactModule` annotation, but I faced some issues with it and don't recall why it didn't work for me. Instead, I have created an extension to get the `NativeModulesProxy`. You can access it via https://github.com/expo/expo/blob/501e40d7056d4576f38284cfae73df90aa24160e/packages/expo-modules-core/android/src/main/java/expo/modules/kotlin/ReactExtensions.kt#L7. If you use it in the `ExpoBridgeModule`, it should work seamlessly.

**Comment by Kudo** [comment]
> . If you use it in the `ExpoBridgeModule`, it should work seamlessly.

thanks @lukmccall! i can confirm that to change the [line](https://github.com/expo/expo/blob/1bea6eb8175023755d5883b827b4383032e1a3a7/packages/expo-modules-core/android/src/main/java/expo/modules/kotlin/ExpoBridgeModule.kt#L16) as `val nativeModulesProxy = context.getUnimoduleProxy()` works great from my local updates-e2e test project.

**Pull request merged**
