### PR TITLE
[expo-updates] add some basic unit tests

### PR DESCRIPTION
**Pull request by esamelson**
# Why

Set up unit testing frameworks for expo-updates & add a few basic tests. This way I can add tests along the way as I'm integrating the module into the managed workflow/app store clients, in case any refactoring needs to happen.

# How

Best to view the 4 commits separately:
- https://github.com/expo/expo/pull/8986/commits/9b8c033552aea991c9e96315cb4c794383e738c0 : add expo-updates to expoview in order to run unit tests through Android Studio (and, later, integrate into the Android Expo client)
- https://github.com/expo/expo/pull/8986/commits/0ce6924d58376b7871c8f5e57a800d6f922b6b82 : add some basic junit tests that pass in Android Studio.
- https://github.com/expo/expo/pull/8986/commits/e86f37feb40b9b1a46ffaa0c622ec9fc5ead4d4a : add iOS example app in order to run tests in library (includes lots of pod files)
- https://github.com/expo/expo/pull/8986/commits/df318aad9a12d42ec1a6c17a924260b8ac273af8 : add some basic XCTests in Xcode, and modified a few Utils functions to allow for dependency injection. Will need to figure out the right way forward with testing this library on iOS -- either significantly restructuring many classes or using something like `OCMock` or a combination.

# Test Plan

Run the tests 😄

### CODE REVIEW

**Comment by mczernek** [comment]
You can use `unimodules-test-core` in android tests if you'd like to mock promise or moduleregistry.

Also, please check whether your tests runs when executing: `et native-unit-tests`.

**Comment by ide** [comment]
I'm a bit worried about adding a whole example app. The repo will get slower and we'll get closer to running up against GitHub's limits if we have one app per module with all the pods. `bare-expo` (we need to rename it eventually) is designed to be the single app in this repo, including for integration tests.

It sounds like CocoaPods support test specs as well as app hosts, but if we go the app host route I think we want to exclude pulling in multiple pods including RN since the focus here is on unit tests.

**Comment by ide** [comment]
Maybe the best way forward with this PR is to land commits 1, 3, and 4 (everything except the test app) and then work on 2 separately.

**Comment by esamelson** [comment]
> Maybe the best way forward with this PR is to land commits 1, 3, and 4 (everything except the test app) and then work on 2 separately.

Makes sense. I've reverted the commit adding the example app and addressed the other direct feedback -- will wait to make sure all the checks complete successfully and then land if so, then follow up with a PR to add expo-updates (along with the iOS unit tests) to bare-expo.

**Review by ide — APPROVED** [review]

**Pull request merged**
