### PR TITLE
Set `foreign_keys = on` by default on iOS

### LINKED ISSUE #3496: Foreign keys not working
Foreign keys are not working in iOS (tested only with the simulator so far). I found that I have to execute PRAGMA foreign_keys = ON; I did this in a transaction, like this:

```typescript
db.transaction((tx: SQLite.Transaction) => {
  tx.executeSql(
    "PRAGMA foreign_keys = ON;",
    [],
    (_, { rows: { _array } }) => {
      console.log(`Enable foreign keys result: ${JSON.stringify(_array)}`)
    },
    ({}, error) => {
      console.log(`Enable foreign keys error: ${error}`)
    }
  )
})
```

It doesn’t seem to work. Cascade delete doesn’t work, and if I log the setting in a new transaction, it says it’s still 0:

```typescript
tx.executeSql(
  "PRAGMA foreign_keys;",
  [],
  (_, { rows: { _array } }) => {
    console.log(`foreign keys result: ${JSON.stringify(_array)}`) // prints {"foreign_keys":0}
  },
  ({}, error) => {
    console.log(`foreign keys error: ${error}`)
  }
)
```

I found this: https://github.com/litehelpers/Cordova-sqlite-storage/issues/45
There the solution seems to be to execute PRAGMA foreign_keys = ON; “directly” on the db, i.e. without a transaction, but I don’t see an api in Expo to do that.

How do I enable foreign keys?

### PR DESCRIPTION
**Pull request by Szymon20000**
# Why

Resolves https://github.com/expo/expo/issues/3496.
As far as I know we can only execute SQL statements in transactions due to webSQL usage. However,
`PRAGMA foreign_keys = ON;` is no-op within a transaction.

# How

I added code which enables foreign key constraints.

# Test Plan

Run the following code in sandbox.

<details><summary> click me </summary>

```
  import * as React from 'react';
  import { Text, View, StyleSheet, Button } from 'react-native';
  import { Constants, SQLite } from 'expo';

  // or any pure javascript modules available in npm
  import { Card } from 'react-native-paper';

  function exec_sql ({ db, sql, parameters = [] }) {
    console.log("start");
    return new Promise((resolve, reject) => {
      db.transaction(tx => {
        console.log(`Executing ${sql} with parameters: ${parameters}`)
        tx.executeSql(sql, parameters,
          (_, result) => {
            console.log(`Have result: ${JSON.stringify(result)}`)
            if (result && result.rows && result.rows._array) {
              resolve({ items: result.rows._array })
            } else {
              resolve()
            }
          },
          (_, err) => {
            console.log(`Error during executing sql: `, err)
            reject(err)
          }
        )
      })
    })
  }

  export default class App extends React.Component {

    sqlTest = async () => {
      const db = SQLite.openDatabase('mydb')
      await exec_sql({ db, sql: `PRAGMA foreign_keys;`});
      await exec_sql({ db, sql: `PRAGMA foreign_keys = ON;`});
      await exec_sql({ db, sql: `PRAGMA foreign_keys;`});
      await exec_sql({ db, sql: `PRAGMA foreign_keys = OFF;`});
      await exec_sql({ db, sql: `PRAGMA foreign_keys;`});
    };

    render() {
      return (
        <View style={styles.container}>
         <Button
          onPress={this.sqlTest}
          title="trigger queries"
          color="#841584"
         />
        </View>
      );
    }
  }

  const styles = StyleSheet.create({
    container: {
      flex: 1,
      justifyContent: 'center',
      paddingTop: Constants.statusBarHeight,
      backgroundColor: '#ecf0f1',
      padding: 8,
    },
    paragraph: {
      margin: 24,
      fontSize: 18,
      fontWeight: 'bold',
      textAlign: 'center',
    },
  });



```
</details>

### CODE REVIEW

**Comment by ide** [comment]
This looks OK to me but is technically a breaking change in case someone already has data in violation of FK checks. Breaking changes are fine but we need to document them. Can you add a line to CHANGELOG.md so we remember to include this in the release notes, along with a suggestion to manually execute `PRAGMA foreign_keys = OFF` for people who have data that violates FK checks?

**Review by ide — APPROVED** [review]
Please add the CHANGELOG entry before committing.

**Comment by Szymon20000** [comment]
> This looks OK to me but is technically a breaking change in case someone already has data in violation of FK checks. Breaking changes are fine but we need to document them. Can you add a line to CHANGELOG.md so we remember to include this in the release notes, along with a suggestion to manually execute `PRAGMA foreign_keys = OFF` for people who have data that violates FK checks?

I believe people won't be able to execute 'PRAGMA foreign_keys = OFF'. The only reason behind this pull-request is fact that we cannot execute 'PRAGMA foreign_keys' within transaction. Are you still ok with this pull request?

**Comment by ide** [comment]
We may need to provide an option when opening the database to skip `PRAGMA foreign_keys = ON`. If someone has a database that currently violates FK checks and then they upgrade their Expo SDK version, I'd expect opening the database or running queries to suddenly fail for them with no way to recover their data. We need to avoid this scenario and give people a way to correct their FK violations.

**Review by ide — CHANGES_REQUESTED** [review]
Would like to see a test plan where we:

- Create a database (before this commit) with two tables and a FK constraint. Insert rows that violate the FK constraint.
- Apply this commit.
- Open the database -- what happens? If the database opens, what happens when we try to read a violating row? What happens when we try to update other columns (not the FK column) of the violating row?

This will give us more confidence we're not breaking anyone's app and also help us choose a smooth migration path if we need to provide a way to skip enabling the FK checks.

**Comment by ide** [comment]
I think it would be much simpler to run this logic in JS and specifically check for `PRAGMA` statements (`/^\s*PRAGMA\s*/.test(query)`). It's simpler to write this in JS and easier to unit test. There still needs to be a new native method like `executePragmaStatementAsync` but pushing more of the logic into JS seems easier.

**Pull request closed without merging**
