### PR TITLE
[android][statusBar] Add configure status bar options for splash screen

### PR DESCRIPTION
**Pull request by vivianzzhu91**
# Why

Due to this feature request (https://expo.canny.io/feature-requests/p/configure-status-bar-for-splash-screen), I decided to add a `android.splash.statusBar` key to `app.json` so that people could configure status bar in splash screen.

# How

Add `android.splash.statusBar` key in `app.json`.

```
"android": {
      "splash":{
        "statusBar": {
      /*
        Determines to show or hide status bar in splash screen.
        "true" to show, "false" to hide.
      */
      "visible": BOOLEAN,

      /*
      Configure the statusbar icons to have light or dark color.
      Valid values: "light-content", "dark-content".
      */
      "barStyle": STRING,

      /*
        Configuration for android statusbar.
        6 character long hex color string, eg: "#000000"
      */
      "backgroundColor": STRING
    }
    },
```

# Test Plan

Tested different configurations in `app.json` with different `backgroundColor`, `barStyle` and `visible`, status bar state in splash screen worked as expected. Status bar styles follows `androidStatusBar` state, if there's none, then status bar would follow `android.splash.statusBar` style throughout the app.

Screen Shot 2019-08-07 at 11 19 52 AM
Screen Shot 2019-08-07 at 2 25 56 PM
Screen Shot 2019-08-06 at 1 52 46 PM

### CODE REVIEW

**Comment by holgersindbaek** [comment]
Will this work for iOS as well?

**Comment by vivianzzhu91** [comment]
@holgersindbaek  This only works for Android in standalone apps.

**Comment by equinusocio** [comment]
At least let people define a dark or light status bar on iOS on the splashscreen..

**Comment by bbarthec** [comment]
I'm closing this PR in favour of #6506.

**Comment by softwareeenginer** [comment]
Is working on Expo project?

**Pull request closed without merging**
