### PR TITLE
[screens][iOS][Android] Upgrade `react-native-screens@3.8.0 ➡️ 3.9.0`

### PR DESCRIPTION
**Pull request by bbarthec**
# Why

[ENG-2533](https://linear.app/expo/issue/ENG-2533/react-native-screens-380-390)
Previous upgrade: #14544

Upgrade to the `3.10.0` should be available soon (ETA: by the end of the week)

# How

1. `et uvm --module "react-native-screens" --commit "3.9.0" --target "expo-go"`
2. `yarn` - this one resulted with updating `yarn.lock` with the followings
    - `@react-native-masked-view/masked-view@0.2.5 -> 0.2.6` (followup for #15362, cc @brentvatne3.8.0)
    - `react-native-pager-view@5.4.6 - > 5.4.9` (followup for #15348, cc @brentvatne)
    - `react-native-webview@11.13.0 -> 11.15.0` (followup for #15330, cc @brentvatne)

# Test Plan

- [x] Test **ncl** in **Expo Go (unversioned)** on Android & iOS
  - clicked here & there randomly
  - openeded `Screens` screen and played with available options
  - on iOS checked portrait & horizontal orientations

# Side notes:

<details>
<summary>dozens packages in ncl are outdated</summary>
Screenshot 2021-12-01 at 16 41 46
</details>
<details>
<summary>navigation in ncl is outdated</summary>
Outdated navigation
</details>

### CODE REVIEW

**Review by brentvatne — APPROVED** [review]

**Review by tsapeta — COMMENTED** [review]
I'd hold off on merging this now. Afaik the new version of screens will be out soon.
CC @kacperkapusciak

**Comment by kacperkapusciak** [comment]
That's true. We're planning on releasing `v3.10.0` tomorrow if everything goes right.

Cheers

**Comment by kacperkapusciak** [comment]
`3.10.0` is out 🚀

**Comment by bbarthec** [comment]
Superseded by #15416

**Pull request closed without merging**
