### PR TITLE
[expo-image-picker] Fixing `launchCameraAsync()` with `allowsEditing` option crashing for some android users

### LINKED ISSUE #11465: Imagepicker.launchCameraAsync() crashing for some android users.
## 🐛 Bug Report
Imagepicker.launchCameraAsync crashes the application without any error logs.

### Summary of Issue 
Some users are reporting "the camera not working", which when I reproduced on Android 10 with a Nexus S emulator was the whole app crashing whenever Imagepicker.launchCameraAsync was called. The camera is never visible, and I have not been able to get any javascript logs from the crash.

**Devices reporting the issue:**
Device: Google Pixel 3a, Android version (SDK): Android 11 (SDK 30)
Device: Google Pixel 5, Android version (SDK): Android 11 (SDK 30)
Device: Samsung Galaxy S10+, Android version (SDK): Android 10 (SDK 29)
Device: Samsung Galaxy Note10+, Android version (SDK): Android 10 (SDK 29)

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

Expo CLI 3.27.14 environment info:
    System:
      OS: macOS 11.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.13.0 - /usr/local/bin/node
      Yarn: 1.22.0 - /usr/local/bin/yarn
      npm: 6.14.5 - /usr/local/bin/npm
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6858069
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: ^39.0.0 => 39.0.4 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz => 0.63.2 
      react-native-web: ~0.13.7 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 3.27.14
    Expo Workflow: managed

### Reproducible Demo
```js
   let result = await ImagePicker.launchCameraAsync({
      mediaTypes: ImagePicker.MediaTypeOptions.Images,
      allowsEditing: true,
        aspect: [4, 3],
      quality: 1,
      base64: true,
    });
```

 
### Steps to Reproduce
Call the above function from an Android 10 Nexus S emulator.

### Expected Behavior vs Actual Behavior

The camera should open to take a picture. Instead the application crashes.

### PR DESCRIPTION
**Pull request by lukmccall**
# Why

Fixes https://github.com/expo/expo/issues/11465.

# How

- Updated the crop package to the newest version which uses the `AndroidX`. 
- Added the crop activity to the manifest - required by the Android 10+

# Test Plan

```js
 let result = await ImagePicker.launchCameraAsync({
    mediaTypes: ImagePicker.MediaTypeOptions.Images,
    allowsEditing: true,
      aspect: [4, 3],
    quality: 1,
    base64: true,
  });
```

# Changelog 

- Fixed `launchCameraAsync()` with `allowsEditing` option crashing for some android users.

### CODE REVIEW

**Review by bbarthec — APPROVED** [review]
Looking good to me 👍 
Add CHANGELOG and we're ready to go 😉

**Comment by Lastofthefirst** [comment]
Which SDK was implemented in?

**Comment by bbarthec** [comment]
@Lastofthefirst, I checked the [`CHANGELOG`](https://github.com/expo/expo/blob/master/CHANGELOG.md) and it seems SDK 41 should have it included 🤔

**Comment by Lastofthefirst** [comment]
@bbarthec I upgraded my app (which was having this issue) to SDK 42 and now the issue doesn't occur when using the app in Expo Go on physical devices or emulators, but does appear in production. Do you have any suggestions for debugging?

**Comment by bbarthec** [comment]
@Lastofthefirst, it seems that accidentally the solution was not ported to the standalone part of the codebase 🤔 We'll have to fix it on our end and there's nothing you can do with the crash right now 😞
I'll create an issue describing this problem and I hope it'll be solved soon! 😊

**Comment by Lastofthefirst** [comment]
@bbarthec Glad to hear it was a straightforward issue, and I'm glad I reached out! Thank you for your support. How can I subscribe to notification as soon as I can add the fix to my application? Would that be with the next SDK release or possibly earlier?

**Comment by bbarthec** [comment]
@Lastofthefirst, as the issue is native-codebase-related you'll have to wait until the next SDK containing this fix is released. Follow the issue I've created and once it's resolved wait for the next SDK containing the fix.

**Comment by Lastofthefirst** [comment]
@lukmccall, sorry  for the delay, (so difficult  to return to a comment). 

I'm having  the  issue on a  wide array  of devices (most all), my issue  is not however that the app crashes with allowsEditing,  rather it  wont open the camera  at  all.  previously thhe issue happened  in production and dev, but since  sdk 42 it only occurs  in production.  Maybe  i ended up  the wrong issue here. I was following a few similar issues.

I think I can provide production logs if its helpful.

**Pull request merged**
