### PR TITLE
[ci] Make CircleCI red when tests fail + retry only "yarn install" commands

### PR DESCRIPTION
**Pull request by ide**
CI was reporting green even when tests failed because the retry loop added `sleep 5` to the end of failing commands. `sleep 5` always succeeds, so CircleCI thought that our tests always passed.

Also, we don't want to retry our unit tests and get in the habit of being OK with flakiness. If they don't always pass we need to fix that. This commit specifies a new "max_tries" parameter only for `yarn install` commands since those can be flaky through no fault of ours.

As part of this commit, I made it so that CI doesn't run `sleep 5` after the last failure since it's unnecessary (we sleep just between tries now).

(Note: CI should fail if this commit is good since our tests actually are broken now)

### CODE REVIEW

**Comment by ide** [comment]
Tests look like they are failing correctly now:
https://circleci.com/gh/expo/expo/4163
https://circleci.com/gh/expo/expo/4167

```
FAIL  src/__tests__/Constants-test.ts
  ● Test suite failed to run

    TypeError: Cannot redefine property: RCTView
        at Function.defineProperty (<anonymous>)

      3 |   get: () => ({
      4 |     NativeProps: {},
    > 5 |     directEventTypes: [],
        |        ^
      6 |   }),
      7 | });
      8 | 

      at Object.<anonymous> (test/setup.js:5:8)

Test Suites: 18 failed, 18 total
Tests:       0 total
Snapshots:   0 total
Time:        1.759s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Exited with code 1
```

**Comment by nicknovitski** [comment]
d'oh!

**Review by nicknovitski — APPROVED** [review]
Approved, since this improves the current situation, but I think ideally _only_ yarn install would retry at all, for the same reasons you describe.  To effect that change, I will probably make a separate yarn_install command.

**Comment by ide** [comment]
A separate yarn_install command makes sense. Will look into whether commands can call other commands.

**Comment by nicknovitski** [comment]
```
$ yarn workspaces info | grep home -A 9
  "@expo/home": {
    "location": "home",
    "workspaceDependencies": [
      "expo-yarn-workspaces",
      "expo",
      "react-native"
    ],
    "mismatchedWorkspaceDependencies": [
      "jest-expo"
    ]
  },
```

I thought there was a script that would detect this problem.

**Pull request merged**
