### PR TITLE
[dev-menu] Fix writing 'r' into text input reloading the app on iOS

### LINKED ISSUE #19911: Typing in TextInput on iOS Simulator will reload the app
### Summary

Hi, 

This is one of my weirdest issues ever but, honestly, one of the most frustrating .. 

For some reason (and the only idea I'm having is an update of Xcode), when I'm typing into a textInput in an iOS Simulator with a development build installed, every time I will type on the "R" key, the app will reload. It's like the text input is not capturing the input and the device did instead. IT NEVER HAPPENED BEFORE ! I literally woke up with this issue ruining my day because the app was reloading by itself every time I'm trying to enter a string with the letter "R" in a text input. 

I really need help here because this is ruining the DX .. 

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

iOS

### Package versions

"expo-dev-client": "~1.3.1",
"expo-updates": "~0.14.5"

### Environment

```

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.0
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
      npm: 8.3.0 - ~/.nvm/versions/node/v16.13.1/bin/npm
    Managers:
      CocoaPods: 1.11.2 - /Users/yonitouboul/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 2.1.0
      expo-cli: 6.0.8
    Expo Workflow: managed


```

### Reproducible demo

https://github.com/yonitou/je-decide-pour-toi

### Stacktrace (if a crash is involved)

_No response_

### PR DESCRIPTION
**Pull request by lukmccall**
# Why

Closes https://github.com/expo/expo/issues/19911.

# How

Don't register key commands on the text inputs. 

# Test Plan

- bare-expo ✅

### CODE REVIEW

**Review by aleqsio — APPROVED** [review]

**Review by douglowder — APPROVED** [review]

**Comment by Albro3459** [comment]
I'm still having this issue with a iPhone 15 simulator on iOS 17.0 with expo go for react native. So annoying

**Comment by Elusv** [comment]
Also still happens with simulator using iPhone 16 and iOS 18+.  what the heck?  2 years?!?

**Comment by rochajulian** [comment]
This is still an issue

**Comment by correafederico25** [comment]
It's happening to me too. I am using an iPhone 15 pro simulator with IOS 17.0

**Comment by jefferyvincent** [comment]
This is still a issue in 18.1

**Comment by JuanchiRios** [comment]
I'm experiencing the same issue using: Iphone 16 pro simulator - IOS 18.2

**Pull request merged**
