### PR TITLE
[Android] Fix headless app for old architecture

### PR DESCRIPTION
**Pull request by robertying**
# Why

I'm getting the following exception in an app running under the old architecture, after this change https://github.com/expo/expo/pull/32146:

```
Fatal Exception: java.lang.ClassCastException: com.facebook.react.bridge.BridgeReactContext cannot be cast to com.facebook.react.v
       at expo.modules.adapters.react.apploader.RNHeadlessAppLoader.invalidateApp(RNHeadlessAppLoader.kt:80)
       at expo.modules.taskManager.TaskService.invalidateAppRecord(TaskService.java:606)
       at expo.modules.taskManager.TaskService$1.run(TaskService.java:215)
       at android.os.Handler.handleCallback(Handler.java:966)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loopOnce(Looper.java:205)
       at android.os.Looper.loop(Looper.java:293)
       at android.os.HandlerThread.run(HandlerThread.java:110)
```

# How

Looks like at least in the old architecture, we can't do `(context as ReactApplication)`.

I updated the code to use `context.applicationContext` instead. I can see in RN, they use `getApplication()` to get the react host or react native host:

https://github.com/facebook/react-native/blob/dc2000c8750f42b2f01bdad75455750814d567c6/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/HeadlessJsTaskService.java#L157

# Test Plan

I can see my background tasks complete successfully under the old arch after the change, but I don't see any errors in new arch before or after the change, so I can't be sure if the change is necessary for new arch. Appreciate if anyone familiar with the new arch chimes in.

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Comment by chrfalch** [comment]
Hi, @robertying - thanks for the PR - To test the new architecture you can easily enable it and test it just by following the steps in this guide: https://docs.expo.dev/guides/new-architecture/

**Comment by chrfalch** [comment]
Could you quickly describe in which context you tested this and how you're using the Headless app loader?

**Comment by robertying** [comment]
> Hi, @robertying - thanks for the PR - To test the new architecture you can easily enable it and test it just by following the steps in this guide: [docs.expo.dev/guides/new-architecture](https://docs.expo.dev/guides/new-architecture/)

Hi @chrfalch. Sorry I wasn't very clear; I meant that in the app with new arch enabled, I don't see any change in behavior before and after I apply this change. I don't see any errors/exceptions in the log. 

Both scenarios result in the same set of logs:

```
Handling intent with task name 'FETCH_ALL_CONTENT_TASK' and app scoping identifier 
Handling job with task name 'FETCH_ALL_CONTENT_TASK' for app with scoping identifier 
Background fetch running with JS
Finished task 'FETCH_ALL_CONTENT_TASK' with eventId
...
Handling intent with task name 'FETCH_ALL_CONTENT_TASK' and app scoping identifier 
Handling job with task name 'FETCH_ALL_CONTENT_TASK' for app with scoping identifier 
Background fetch running with JS
Finished task 'FETCH_ALL_CONTENT_TASK' with eventId
```

It could be that in the new arch, `context` can be cast to `ReactApplication` directly, which is something I am not sure of.

I tested using this code:

```ts
  TaskManager.defineTask(FETCH_ALL_CONTENT_TASK, async () => {
    console.log('Background fetch running with JS');
    return BackgroundFetch.BackgroundFetchResult.NewData;
  });

  await BackgroundFetch.registerTaskAsync(FETCH_ALL_CONTENT_TASK, {
    minimumInterval: 60,
  });
```

**Comment by robertying** [comment]
Ah I guess all the `reactHost` and `reactNativeHost` had got me super confused.

With some breakpoint debugging, I am able to conclude that we should probably always use `applicationContext` to get either `reactHost` or `reactNativeHost` regardless of new arch.

## New arch

`((ReactApplication) context).getReactHost()` gives the exception 
Screenshot 2024-10-28 at 1 32 18 AM

but I was able to get `reactHost` by doing `((BridgelessReactContext) context).mReactHost`
Screenshot 2024-10-28 at 1 33 27 AM

`((ReactApplication) context.getApplicationContext()).getReactHost()` works perfectly
`((ReactApplication) context.getApplicationContext()).getReactNativeHost()` works too
Screenshot 2024-10-28 at 1 35 21 AM


## Old arch

Need `((ReactApplication) context.getApplicationContext()).getReactNativeHost()`
Screenshot 2024-10-28 at 1 39 19 AM

**Comment by chrfalch** [comment]
I'm struggling a bit to reproduce this error - could you help providing a clear step-by-step guide to how you're using this in your app - causing these issues?

**Comment by robertying** [comment]
@chrfalch I saw these errors from Firebase Crashlytics. I can't see the exceptions in logcat by running the app in an emulator either.

---

Basically I'm using the bare workflow with expo. With new arch turned off, and run the following in the app

```ts
  TaskManager.defineTask(FETCH_ALL_CONTENT_TASK, async () => {
    console.log('Background fetch running with JS');

    return BackgroundFetch.BackgroundFetchResult.NewData;
  });

  await BackgroundFetch.registerTaskAsync(FETCH_ALL_CONTENT_TASK, {
    minimumInterval: 60,
  });
```

After the app starts, I put it in background and monitor the log.

With the current expo code (before this PR) and after this PR, in both cases I can see logs `Background fetch running with JS`.

---

I tried to manually log in the file `RNHeadlessAppLoader.kt` with `Log.e("MyTest", if ((context as ReactApplication).reactNativeHost == null) "reactNativeHost is null" else "reactNativeHost found")` but it won't show up in the log either. I suspect that logs are not a good way to look into this issue. That was why I used a breakpoint to check the exact context being passed when the app starts in the foreground. You could do the same to check which attributes are available from the context.

Also, I tagged you here: https://github.com/expo/expo/pull/32146/files#r1823163925. I wonder if this change was intentional.

**Comment by chrfalch** [comment]
Hi, thanks for getting back so quickly again - I'm aware of the change you're pointing to with the context casting - will look into it. What I'm super curious about is how you get to the point where the Headless loader is started? Like a simple step-by-step repro on how to get it to fire? 

The thing is that in the current implementation I'm not finding a clear path to get the Headless task to start from neither notifications, location or the background-fetch package (all three using expo-task-manager to handle background tasks). I'm working on fixing this - so any help would be awesome. 

If the Headless task is loaded in a different way when you're getting these exceptions I'd be super happy to learn about that since it will help a lot in finding out what and where things are going wrong here.

**Comment by robertying** [comment]
> Hi, thanks for getting back so quickly again - I'm aware of the change you're pointing to with the context casting - will look into it. What I'm super curious about is how you get to the point where the Headless loader is started? Like a simple step-by-step repro on how to get it to fire?
> 
> The thing is that in the current implementation I'm not finding a clear path to get the Headless task to start from neither notifications, location or the background-fetch package (all three using expo-task-manager to handle background tasks). I'm working on fixing this - so any help would be awesome.
> 
> If the Headless task is loaded in a different way when you're getting these exceptions I'd be super happy to learn about that since it will help a lot in finding out what and where things are going wrong here.

Are you saying that you can't see any task related logs? With the JS code I provided, you should be able to see logs like these in logcat on Android:

```
Handling intent with task name 'FETCH_ALL_CONTENT_TASK' and app scoping identifier 
Handling job with task name 'FETCH_ALL_CONTENT_TASK' for app with scoping identifier 
Background fetch running with JS
Finished task 'FETCH_ALL_CONTENT_TASK' with eventId
```

**Review by chrfalch — APPROVED** [review]
I've tested this with the BackgroundTask and it works as expected both under the old/new arch with your fixes.

Thanks a lot @robertying :)

**Pull request merged**
