### PR TITLE
[ios] Enable CocoaPods 1.8 improvements

### LINKED ISSUE #4667: [ios] Enable "multiple xcodeproj" files with CocoaPods 1.7 once FBSDK supports it
FBSDK in expo-facebook is keeping us back from enabling the "multiple xcodeproj" option in CocoaPods 1.7 (speeds up Xcode) as well as the "incremental installation" option (speeds up `pod install`). Once FBSDK changes the way it does headers and we upgrade it, we can try enabling these options again.

### PR DESCRIPTION
**Pull request by sjchmiela**
# Why

Closes https://github.com/expo/expo/issues/4667.

# How

- upgraded CocoaPods to 1.8.0.beta1
- enabled CocoaPods improvements
- grouped offending Facebook dependencies together so they can access each other

# Test Plan

Expo client builds and runs ok

### CODE REVIEW

**Review by ide — APPROVED** [review]
Have you noticed any change in how long it takes to pod install or compile the client?

**Comment by sjchmiela** [comment]
In fact I've been doing a couple of things at the same time, so I can't tell 😞 

I'll take a fresh look in a sec

**Comment by sjchmiela** [comment]
Yes!

Before:
`pod install  27,17s user 8,57s system 92% cpu 38,542 total`

After:
`pod install  10,01s user 3,36s system 98% cpu 13,511 total`

**Comment by ide** [comment]
Wow, that is significant. Is that a cold (Pods folder deleted) or warm install?

The CDN may help as well, especially for fetching new versions of pods since we won’t need to git pull the specs repo: https://blog.cocoapods.org/CocoaPods-1.7.2/

**Pull request merged**
