### PR TITLE
Allowing nulls to be bound as query params in SELECT statements

### LINKED ISSUE #2090: SQLite unable to use NULL params in queries on Android
I'm trying to run the following query in my program:

```javascript
const my_group_id = has_group_id ? group_id : null;
tx.executeSql(
    `SELECT max(ranking) as highrank FROM item
      WHERE coalesce(group_id, -1) = coalesce(?, -1)`,
[my_group_id], ..., ...);
```

It succeeds on iOS but fails on Android with this error:

```
Error: the bind value at index 1 is null
```

Here's a snack that succeeds on iOS and fails on Android: https://snack.expo.io/ryEbS49Bm

I don't know what code to fix though.  Is this an Expo problem, a RN problem or an Android problem?

- expo's [SQLiteModule.java](https://github.com/expo/expo/blob/master/android/expoview/src/main/java/abi28_0_0/host/exp/exponent/modules/api/SQLiteModule.java#L132) uses Android's `rawQuery`
- [Android's `rawQuery`](https://github.com/aosp-mirror/platform_frameworks_base/blob/4b1a8f46d6ec55796bf77fd8921a5a242a219278/core/java/android/database/sqlite/SQLiteDatabase.java#L1256) expects bind params to be a String array
- I'm assuming that it eventually ends up at [Android's `bindString` function](https://github.com/aosp-mirror/platform_frameworks_base/blob/4b1a8f46d6ec55796bf77fd8921a5a242a219278/core/java/android/database/sqlite/SQLiteProgram.java#L162) because grepping for the error string led me there.

I'm not sure why `bindString()` throws on nulls.  There's a `bindNull()` right above it that does what `bindString()` would do if the error-throwing code weren't there (which makes me think everything would work fine if the null check were removed).

Is the fix to patch Android's code?  Or is the patch to change expo's SQLiteModule.java to bind parameters itself (using something other than `rawQuery`)?

### Environment

iOS, Android

### PR DESCRIPTION
**Pull request by iffy**
I don't know how to run this code, but this is my best guess at what needs to happen to allow null parameters in SELECT statements.

Fixes #2090 
Tests ~in https://github.com/expo/test-suite/pull/6~ are included!

Feedback welcome (especially from someone who can compile and run the code :) )

### CODE REVIEW

**Comment by iffy** [comment]
@ide Hooray for putting the tests in this repo! I've pushed changes to duplicate https://github.com/expo/test-suite/pull/6

**Comment by esamelson** [comment]
Hi @iffy - I'm sorry for the really slow followup here. We've been working hard to make this repo easier to contribute to and use, but unfortunately in the process a few things have slipped through the cracks. I tried running your changes -- however, they fail to compile because the `android.database.sqlite.SQLiteDirectCursorDriver` import cannot be found.

If you haven't tried running the expo app from this repo, we'd love if it you have time to give it a try 🙂  You can follow the "Running on a device" instructions on this repo's README. Hopefully that will help you be able to debug and fix these changes.

**Comment by iffy** [comment]
@esamelson I ran `cd android; ./run.sh` according to the README and get the error below.  If you want to pursue fixing this, that's fine.  But so far, my experience makes me thinking trying to depend on Expo will be a bad long-term choice.  I'm exploring other options for making mobile apps (including just skipping Expo and using ReactNative).

```
org.gradle.api.ProjectConfigurationException: A problem occurred configuring project ':app'.
        at org.gradle.configuration.project.LifecycleProjectEvaluator.addConfigurationFailure(LifecycleProjectEvaluator.java:94)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:89)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.doConfigure(LifecycleProjectEvaluator.java:70)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.access$100(LifecycleProjectEvaluator.java:34)
        at org.gradle.configuration.project.LifecycleProjectEvaluator$ConfigureProject.run(LifecycleProjectEvaluator.java:110)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:50)
        at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:666)
        at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:135)
        at org.gradle.execution.TaskPathProjectEvaluator.configure(TaskPathProjectEvaluator.java:35)
        at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:62)
        at org.gradle.execution.TaskSelector.getSelection(TaskSelector.java:100)
        at org.gradle.execution.TaskSelector.getSelection(TaskSelector.java:81)
        at org.gradle.execution.commandline.CommandLineTaskParser.parseTasks(CommandLineTaskParser.java:42)
        at org.gradle.execution.TaskNameResolvingBuildConfigurationAction.configure(TaskNameResolvingBuildConfigurationAction.java:44)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter.configure(DefaultBuildConfigurationActionExecuter.java:48)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter.access$000(DefaultBuildConfigurationActionExecuter.java:25)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter$1.proceed(DefaultBuildConfigurationActionExecuter.java:54)
        at org.gradle.execution.DefaultTasksBuildExecutionAction.configure(DefaultTasksBuildExecutionAction.java:44)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter.configure(DefaultBuildConfigurationActionExecuter.java:48)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter.access$000(DefaultBuildConfigurationActionExecuter.java:25)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter$1.proceed(DefaultBuildConfigurationActionExecuter.java:54)
        at org.gradle.execution.ExcludedTaskFilteringBuildConfigurationAction.configure(ExcludedTaskFilteringBuildConfigurationAction.java:47)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter.configure(DefaultBuildConfigurationActionExecuter.java:48)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter.select(DefaultBuildConfigurationActionExecuter.java:36)
        at org.gradle.initialization.DefaultGradleLauncher$CalculateTaskGraph.run(DefaultGradleLauncher.java:268)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.initialization.DefaultGradleLauncher.constructTaskGraph(DefaultGradleLauncher.java:175)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:130)
        at org.gradle.initialization.DefaultGradleLauncher.executeTasks(DefaultGradleLauncher.java:109)
        at org.gradle.internal.invocation.GradleBuildController$1.call(GradleBuildController.java:78)
        at org.gradle.internal.invocation.GradleBuildController$1.call(GradleBuildController.java:75)
        at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:152)
        at org.gradle.internal.invocation.GradleBuildController.doBuild(GradleBuildController.java:100)
        at org.gradle.internal.invocation.GradleBuildController.run(GradleBuildController.java:75)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.tooling.internal.provider.ValidatingBuildActionRunner.run(ValidatingBuildActionRunner.java:32)
        at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner$1.run(RunAsBuildOperationBuildActionRunner.java:43)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner.run(RunAsBuildOperationBuildActionRunner.java:40)
        at org.gradle.tooling.internal.provider.SubscribableBuildActionRunner.run(SubscribableBuildActionRunner.java:51)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:47)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:30)
        at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:39)
        at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:25)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:80)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:53)
        at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:57)
        at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:32)
        at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:36)
        at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:25)
        at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:43)
        at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:29)
        at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:69)
        at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:30)
        at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:59)
        at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:44)
        at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:45)
        at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:30)
        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
        at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
        at org.gradle.util.Swapper.swap(Swapper.java:38)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
        at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:62)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:82)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:295)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: java.lang.RuntimeException: Cannot read packageName from /Users/matt/lib/expo.git/android/app/src/main/AndroidManifest.xml
        at com.android.build.gradle.internal.core.VariantConfiguration.getPackageFromManifest(VariantConfiguration.java:915)
        at com.android.build.gradle.internal.core.VariantConfiguration.getOriginalApplicationId(VariantConfiguration.java:673)
        at com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$ConfigAction.execute(LinkApplicationAndroidResourcesTask.java:720)
        at com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$ConfigAction.execute(LinkApplicationAndroidResourcesTask.java:605)
        at org.gradle.api.internal.tasks.DefaultTaskContainer.create(DefaultTaskContainer.java:148)
        at com.android.build.gradle.internal.TaskFactoryImpl.create(TaskFactoryImpl.kt:50)
        at com.android.build.gradle.internal.TaskManager.createNonNamespacedResourceTasks(TaskManager.java:1266)
        at com.android.build.gradle.internal.TaskManager.createProcessResTask(TaskManager.java:1226)
        at com.android.build.gradle.internal.TaskManager.createApkProcessResTask(TaskManager.java:1181)
        at com.android.build.gradle.internal.ApplicationTaskManager.lambda$createTasksForVariantScope$7(ApplicationTaskManager.java:175)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:81)
        at com.android.build.gradle.internal.ApplicationTaskManager.createTasksForVariantScope(ApplicationTaskManager.java:169)
        at com.android.build.gradle.internal.VariantManager.createTasksForVariantData(VariantManager.java:530)
        at com.android.build.gradle.internal.VariantManager.lambda$createAndroidTasks$1(VariantManager.java:352)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:81)
        at com.android.build.gradle.internal.VariantManager.createAndroidTasks(VariantManager.java:348)
        at com.android.build.gradle.BasePlugin.lambda$createAndroidTasks$6(BasePlugin.java:751)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:81)
        at com.android.build.gradle.BasePlugin.createAndroidTasks(BasePlugin.java:746)
        at com.android.build.gradle.BasePlugin.lambda$null$4(BasePlugin.java:652)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:81)
        at com.android.build.gradle.BasePlugin.lambda$createTasks$5(BasePlugin.java:648)
        at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:91)
        at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:80)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:42)
        at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:230)
        at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:149)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:58)
        at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:324)
        at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:234)
        at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:140)
        at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:37)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
        at com.sun.proxy.$Proxy27.afterEvaluate(Unknown Source)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:76)
        ... 94 more
```

**Comment by esamelson** [comment]
@iffy I'm sorry to hear that. We're right in the middle of a bunch of changes to make things more open-source-centric, and I'm very sorry that we missed this PR in the process. The client app should be runnable now (it turns out there was a missing step in the README directions) but we certainly understand if you don't have the time to pursue this further.

If you have any feedback for what Expo could change to feel like a more viable long-term solution, we'd love to hear it! And either way, best of luck with your app-making pursuits 🙂

**Comment by iffy** [comment]
@esamelson my uneasiness with Expo isn't anything major -- just little things that add up to make me not certain it's going to be here for the long-term or be fixable when I find bugs.

- The delay of PRs getting attention (granted, I could tell you were in a rework stage and this by itself isn't concerning)
- The lack of a changelog which indicates whether or not a PR is included in the version of Expo I'm using.  (I filed this as an issue on... some website where this project is asking for feedback -- can't remember the name or find a link to it anymore)
- The difficulty of "building" Expo or running the tests (as encountered above and at [other times](https://github.com/expo/expo/issues/1984#issuecomment-405669205)).  I've spent too much time with the plumbing of Expo, which has taken me away from time I want to spend building my apps.

Also, I realize I'm not paying anything for Expo -- I expect it not to be perfect.  I appreciate the work you're doing.  I'll keep checking back here (and may looking at fixing this issue as a first step when I get around to it).

**Comment by ide** [comment]
@iffy agree with all of those bullet points and we've been working to address them. Most notably we've moved the Expo team's development to this GitHub repository. We used to develop in a team-only repository and then sync the code to public repositories, similar to React Native. After our change, there's much more alignment and parity between the Expo team's development workflow and the rest of the community's. When development breaks or even just becomes kludgy in this repo, the Expo team is much more likely to notice it and identify how to fix it. I think this will make a huge difference and have a lot of positive downstream effects for people looking to use this repo to modify or contribute to Expo.

We're also adding a changelog here: https://github.com/expo/expo/pull/2356. I think we generally do a good job with our release notes but the changelog should make it easier to look at finer-grained changes.

And we've "defragmented" our GitHub repositories and consolidated them here so that it's much easier to write code that spans JS, native, and eventually the docs too. This was a prereq to moving the Expo client development to this repo and a significant example of how aligning the Expo team's workflows with the rest of the community's makes it generally easier for everyone to use the repo.

Finally, we're also looking to boost quality more than quantity in several ways. One big area is stabilizing Expo's dependencies. We end up spending a lot of time treading water on breaking changes from dependencies instead of swimming forward with more optimizations and features in a responsible way and overall doing right by people who are using Expo for their businesses.

**Comment by iffy** [comment]
That "defragmenting" is a great move.  That gives me a lot more confidence.  And I'll make changelog comments on the related issue.

Thank you for taking the time to write about this.

**Pull request closed without merging**
