### PR TITLE
[local-authentication] switch to the new biometric permission on android

### LINKED ISSUE #8530: [LocalAuthentication] Must have com.samsung.android.bio.face.permission.USE_FACE
## 🐛 Bug Report

Users who preferred `Face recognition` in system `Settings` -> `Biometrics and security` ->`Biometric preferences` -> `Preferred biometric` can't use `LocalAuthentication.authenticateAsync`.

### Environment

  Expo CLI 3.21.3 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.3.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6392135
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild
    npmPackages:
      react: 16.11.0 => 16.11.0 
      react-native: 0.62.2 => 0.62.2 
    npmGlobalPackages:
      expo-cli: 3.21.3

Android

### Steps to Reproduce

On Samsung Galaxy S8 with Android 9:
1. Enable `Face recognition` in `Settings` -> `Biometrics and security` ->`Biometric preferences` -> `Preferred biometric`
2. Try to call `LocalAuthentication.authenticateAsync`

### Expected Behavior

Fallback to fingerprint

### Actual Behavior

`Must have com.samsung.android.bio.face.permission.USE_FACE or android.permission.USE_BIOMETRIC permission.` error

### Reproducible Demo

https://snack.expo.io/@bardiamist/localauthentication

### PR DESCRIPTION
**Pull request by byCedric**
# Why

Fixes #8530

# How

It wasn't mentioned in the [fingerprint migration guide](https://medium.com/androiddevelopers/migrating-from-fingerprintmanager-to-biometricprompt-4bc5f570dccd) but was highlighted in the [BiometricPrompt section of "What's new in Android P"](https://medium.com/appnroll-publication/what-is-new-in-android-p-biometricprompt-d4fc85e55608)

# Test Plan

I haven't tested this, but we fully switched to Biometric Prompts now (with the compat library). I can test this in 1.5 weeks, when I have some new hardware.

### CODE REVIEW

**Review by tsapeta — COMMENTED** [review]
I'm wondering whether it's safe replace the permission. BiometricManager from AndroidX actually falls back to FingerprintManager on older versions of Android, so I guess we may still need to have this old permission 🤔

**Comment by byCedric** [comment]
@tsapeta Is it safe to include them both? I also read something about `android:requiredFeature="false"`, might be good to add it to the biometric permission as well.

**Comment by tsapeta** [comment]
I'm not actually sure if it's safe so it sounds good, let's hold off on this 🙂

**Review by tsapeta — APPROVED** [review]

**Comment by Bardiamist** [comment]
@byCedric Did you test that on Samsung?

**Comment by Bardiamist** [comment]
@byCedric Can you answer? Please.
 Did you test that on Samsung with enabled `Face recognition` (in `Settings` -> `Biometrics and security` ->`Biometric preferences` -> `Preferred biometric`)?

**Comment by Bardiamist** [comment]
That not fixed.

**Pull request merged**
