### PR TITLE
[core] Decouple jsc or hermes runtime lib on Android

### LINKED ISSUE #134: expo-updates and v8 cause app to crash on Expo SDK 46
Hello, I'm having an issue trying to setup expo-updates with v8. I get the fatal error below when running Update from `expo-updates` or when importing `expo-asset` in the entry file.

I'm using Expo SDK 46, RN 0.69.4 and expo-updates 0.14.5.

```
LinkError: dlopen failed: library "libjsc.so" not found: needed by /data/app/~~JDe--RN-XNCYcVj908WL3g==/com.coinbase.android.development-MSfmoA0UnBKbjmUrlMEXXQ==/lib/arm64/libjscexecutor.so in namespace classloader-namespace
08-25 18:48:27.762 19191 20342 I oid.developmen:   at void java.lang.Runtime.loadLibrary0(java.lang.ClassLoader, java.lang.Class, java.lang.String) (Runtime.java:1077)
08-25 18:48:27.762 19191 20342 I oid.developmen:   at void java.lang.Runtime.loadLibrary0(java.lang.Class, java.lang.String) (Runtime.java:998)
08-25 18:48:27.762 19191 20342 I oid.developmen:   at void java.lang.System.loadLibrary(java.lang.String) (System.java:1656)
08-25 18:48:27.762 19191 20342 I oid.developmen:   at void expo.modules.kotlin.jni.JSIInteropModuleRegistry.<clinit>() (JSIInteropModuleRegistry.kt:86)
08-25 18:48:27.762 19191 20342 I oid.developmen:   at void expo.modules.kotlin.AppContext.installJSIInterop() (AppContext.kt:90)
08-25 18:48:27.762 19191 20342 I oid.developmen:   at void expo.modules.kotlin.KotlinInteropModuleRegistry.installJSIInterop() (KotlinInteropModuleRegistry.kt:114)
08-25 18:48:27.762 19191 20342 I oid.developmen:   at java.util.Map expo.modules.adapters.react.NativeModulesProxy.getConstants() (NativeModulesProxy.java:95)
08-25 18:48:27.762 19191 20342 I oid.developmen:   at com.facebook.react.bridge.NativeMap com.facebook.react.bridge.JavaModuleWrapper.getConstants() (JavaModuleWrapper.java:142)
08-25 18:48:27.762 19191 20342 I oid.developmen:   at void com.facebook.react.bridge.queue.NativeRunnable.run() (NativeRunnable.java:-2)
08-25 18:48:27.762 19191 20342 I oid.developmen:   at void android.os.Handler.handleCallback(android.os.Message) (Handler.java:938)
08-25 18:48:27.762 19191 20342 I oid.developmen:   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:99)
```
I've tried to debug expo but I'm a bit lost.

### PR DESCRIPTION
**Pull request by Kudo**
# Why

the expo-modules-core links hermes or jsc to create a js runtime, however the call flow is only for android instrumented test. the test code increases build time as well as introducing the lib dependency to hermes/jsc and then breaks v8 support.
fix https://github.com/Kudo/react-native-v8/issues/134

# How

- Use `UNIT_TEST` preprocessor for the test code.
- change `FOR_HERMES -> USE_HERMES`

# Test Plan

- bare-expo
- `./gradlew :expo-modules-core:connectedAndroidTest` in `android`. this is running instrumented test on jsc
- `./gradlew :expo-modules-core:connectedAndroidTest` in `apps/bare-expo/android`. this is running instrumented test on hermes
- unzip the apk and use `objdump -x /path/to/libexpo-modules-core.so` to make sure there's no hermes or jsc dependency.

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [x] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Review by tsapeta — APPROVED** [review]
🔥
✌️8️⃣

**Comment by evelant** [comment]
@Kudo Is this fix available in any released version? I wanted to try v8 and it works in development but crashes at launch in production due to something attempting to load libjscexecutor.so

**Comment by brentvatne** [comment]
@evelant - it is available in the latest version of `expo@46`

**Comment by evelant** [comment]
@brentvatne OK thanks, there must be some other dependency that's attempting to load libjscexecutor.so but only in release builds. Now to figure out how to track it down...

**Pull request merged**
