### PR TITLE
[expo-app-loading] deprecation warning typo fix

### PR DESCRIPTION
**Pull request by frankcalise**
Just a small spelling error in the deprecated warning about using SplashScreen

### CODE REVIEW

**Comment by Simek** [comment]
Hello @frankcalise, thank you for the typo fixes! 👍 

Since you have edited the message in the package source code, you need to rebuild the package to fix the CI.

Refs: #17371

**Review by bbarthec — CHANGES_REQUESTED** [review]
The change is nice 👍, but I need you to rebuild the `build/` files to make CI green. See [contribution](https://github.com/expo/expo/blob/main/CONTRIBUTING.md#-before-submitting).

**Comment by frankcalise** [comment]
@bbarthec my bad life got busy, sorry I forgot that step, should be able to patch this up today

**Comment by frankcalise** [comment]
Fixed in https://github.com/expo/expo/pull/17513 sorry had some issues with this

**Pull request closed without merging**
