### PR TITLE
Fix typo in the doc

### PR DESCRIPTION
**Pull request by falko189**
Just a small typo fix

# Why

appplication has too many p

# How

I was just reading the doc

# Test Plan

Double check I haven't miss typed it again

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.io and README.md).

### CODE REVIEW

**Review by Simek — APPROVED** [review]

**Review by barthap — APPROVED** [review]
Thank You!  🎉

**Review by barthap — CHANGES_REQUESTED** [review]
Ah, I've just noticed - Could you also apply the same fix in docs for all SDK versions? - it is `docs/pages/versions/v38.0.0 ... v42.0.0/sdk/auth-session.md`. It's also in all of these files 😅

**Comment by falko189** [comment]
Yeah not a problem

**Comment by falko189** [comment]
I am closing this and opened a new one #13676 I have done a project search this time! :)

**Pull request closed without merging**
