### PR TITLE
[screen-orientation] fix: orientationDidChange not firing when modal …

### PR DESCRIPTION
**Pull request by cruzach**
…is open

# Why

Reported by a partner that they couldn't force the orientation back to portrait after closing a modal that allowed both portrait and landscape orientations. 

[Use this snack to reproduce](https://snack.expo.io/@lachlanglen/76bd6d):
- click to open modal
- rotate to landscape
- click to close modal and app _should_ reorient to portrait, but it does not

# How

Found out that `traitCollectionDidChange` isn't called when a Modal is open, which it seems is also the case on iPad, so I removed the check for `isIPad`. 

In my tests, `screenOrientationDidChange` isn't getting called twice in any scenarios (neither with the modal open nor with it closed, but maybe there are more scenarios you can imagine that I should test @lukmccall ?)

# Test Plan

ran screen-orientation test suite, all passed

### CODE REVIEW

**Comment by lukmccall** [comment]
Did you test the normal usage of the module on the iPhone (for example testing the example in NCL)?  I think the listener might be triggered more often now. We don't want to emit the same event twice. I know that we compare the current orientation in both callbacks (`traitCollectionDidChange`, `deviceOrientationDidChange`) and only emit the event if there is a change. But I'm worried about some race condition here. 

Moreover, the only reason why we listen to the `deviceOrientationDidChange` event in that module is to provide the same functionality on iPads. And actually, I don't know if it's a good place to send the event to the user. You can read more about that under this PR https://github.com/expo/expo/pull/5540. 

So maybe we could check if the key view is a modal here? I'm not sure if that is possible and how the RN modal actually works under the hood, but maybe we can explore that.

**Comment by cruzach** [comment]
> Did you test the normal usage of the module on the iPhone (for example testing the example in NCL)?

Yeah, I did, listener is only triggered once in NCL on an iphone

>So maybe we could check if the key view is a modal here? I'm not sure if that is possible and how the RN modal actually works under the hood, but maybe we can explore that.

Not sure what you mean by key view, but it looks like whatever the react native modal is doing is preventing `traitCollectionDidChange` from firing (although adding a `traitCollectionDidChange` to RCTModalViewController _does_ work). Maybe this is more of a bug with react native than with `expo-screen-orientation` 🤔

**Comment by lukmccall** [comment]
So the react-native is adding another view controller to the hierarchy. That's why this doesn't work. We only listen to the `traitCollectionDidChange` in the `EXAppViewController` -> https://github.com/expo/expo/blob/ba046bb1946ccc10ded80facdfde4bb67998e9f3/ios/Exponent/Kernel/Views/EXAppViewController.m#L562-L575 I assume that the method in `EXAppViewController` isn't called because the  `RCTModalViewController` is becoming the root view of the currently running application (or something like this 😜 ).
By `So maybe we could check if the key view is a modal here?` I meant to check if we can detect that the modal is currently opened and if so we could emit the event from the `screen-orientation` module only if it's.

**Comment by cruzach** [comment]
Hm... actually after testing this in bare, the same JS code resulted in the correct behavior. So it's probably something inside of the scoped Expo code that's causing this, thus we really shouldn't need to touch the `expo-screen-orientation` package. I'll continue to investigate

**Pull request closed without merging**
