### PR TITLE
[TS][location][docs] add `maximumAge` to TS, `timeout` to docs, & fix docs error

### LINKED ISSUE #6795: [docs] Location.getCurrentPositionAsync options not in sync with TypeScript definitions
Expo: 36.0.1
Docs: https://docs.expo.io/versions/v36.0.0/sdk/location/#locationgetcurrentpositionasyncoptions

Now, I don't know what side is right or wrong here, but the docs specify a `maximumAge` parameter for `Location.getCurrentPositionAsync`, which is not available in typescript. At the same time there is a `timeout` option in the ts definition of LocationOptions but not in the docs.

### PR DESCRIPTION
**Pull request by cruzach**
# Why

Closes https://github.com/expo/expo/issues/6795 and gets rid of the error logged into console in both dev and production where `TableOfContentSection` needed the unique `key` prop

### CODE REVIEW

**Comment by Xerus2000** [comment]
The timeout does not seem to work, I used it in Android and it doesn't abort the wait.

**Comment by Xerus2000** [comment]
I am also unsure whether the maximumAge parameter is actually working, it has never returned immediately for me...

**Comment by cruzach** [comment]
I tested the timeout and it seemed to work for me 🤔 

Could you share more details and preferably a reproducible demo in the issue you opened?

**Comment by Xerus2000** [comment]
Well, at least the timeout didn't work as long as I was affected by this bug: https://github.com/expo/expo/issues/6816

**Review by lukmccall — APPROVED** [review]
LGTM

**Pull request merged**
