### PR TITLE
[av][ios] Fix audio recording resetting when receiving a phone call

### LINKED ISSUE #24922: Expo iOS Bug: When receiving a call, automatically resets the current audio recording
### Minimal reproducible example

https://github.com/RilDev/bug-expo-ios-call-resets-current-recording

## Expected behaviour

- Start recording
- Receive phone call (the phone call pauses the recording)
- Resume recording (the recording resumes from where it was paused)

## Actual behaviour

- Start recording
- Receive phone call (the phone call pauses the recording & reset the durationMillis to 0)
- When resuming the recording, what was recorded before the phone call is ereased.

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.3.1 - ~/.nvm/versions/node/v20.3.1/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 9.6.7 - ~/.nvm/versions/node/v20.3.1/bin/npm
      Watchman: 2023.10.09.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.0 - /Users/cyril/.rvm/gems/ruby-3.0.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
      Android SDK:
        API Levels: 30, 33, 33
        Build Tools: 30.0.3, 33.0.0, 33.0.2, 34.0.0
        System Images: android-28 | Google ARM64-V8a Play ARM 64 v8a, android-33 | Google Play ARM 64 v8a, android-UpsideDownCake | Google APIs ARM 64 v8a, android-UpsideDownCake | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9619390
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.13 => 49.0.13
      react: 18.2.0 => 18.2.0
      react-native: 0.72.5 => 0.72.5
    npmGlobalPackages:
      eas-cli: 5.4.0
    Expo Workflow: managed
```

### PR DESCRIPTION
**Pull request by behenate**
# Why

We don't pause the recording correctly when receiving an interrupt, which causes iOS to stop the recording completely
Fixes https://github.com/expo/expo/issues/24922

# How

When receiving an interrupt while recording pause the recording

# Test Plan

Tested in Bare Expo on iOS 17 device

### CODE REVIEW

**Review by Kudo — APPROVED** [review]

**Review by tsapeta — APPROVED** [review]

**Review by lukmccall — APPROVED** [review]

**Comment by jogyfelix** [comment]
I'm still experiencing the issue even after upgrading to SDK 50. Has it been resolved?

**Comment by Emmanueldmlr** [comment]
I'm currently experiencing this issue again.

**Comment by maulanafadilah** [comment]
Me too, I'm currently experiencing this issue. I'm on SDK 51

**Comment by Emmanueldmlr** [comment]
> Me too, I'm currently experiencing this issue. I'm on SDK 51

Can you try to update your expo-av version?

**Comment by ddematheu** [comment]
This was still happening on version 14.0.6. Any guidance on fix? Any additional configuration required?

**Comment by Emmanueldmlr** [comment]
So, the issue has been fixed on SDK 51, but the time resets, so it's kind of hard to know except if you inspect, which, in my case, I did.

Firstly, when an interrupt occurs, the recording status changes ti paused, and the recordingObj is preserved, but the timer resets to 0 (The main issue).

To continue the recording, you need a mechanism to detect the interrupt is over and then call the startAsync() function on the recording object to continue and this will continue the recording process (but the timer will start from 0 again).

There are different mechanisms to detect the interrupt is over
1) wrap setTimeInterval with try and catch and try to call the startAsync() on the recording object at intervals. If the interrupt is over, it will start; if not, it will throw an error, which the catch block will catch.
2) the createAsync function takes a callback function you can use to update the status of the recording, and this is called every second. You can decide to put your interrupt handling function inside it; this will ensure it is called every time (make sure you add a check to ensure it is only called when there is an actual interrupt).

Lastly, you need to manually handle the issue with the timer resetting when there is an interrupt. You can create a buffer and initialize it to 0 so that the actual recording time = ActualTime + buffer. You then need a way to move the actualTime to buffer before the interrupt occurs so that the actualTime is preserved before it is reset.

Ideally, expo is meant to handle the issue with the timer. I might try to fix this for them when I'm less busy.

**Comment by ddematheu** [comment]
Appreciate the guidance.

I see the change is status to isRecording false and I can handle that. 

My only concern is differentiating between an interrupt and a recording actually being stopped with stopAsync(). Sounds like the best way to detect this is to looked for paused.

Ideally would love to have some type of event / flag that tells me this is an interrupt.

Happy to aid in fixing the timer. I do handle this on my side by keeping a buffer, but ideally a built-in fix would be amazing.

**Comment by Emmanueldmlr** [comment]
Nice.  I'm available to jump on a call to discuss how to differentiate an interrupt and a recording actually being stopped with stopAsync().

**Comment by ddematheu** [comment]
Appreciate it. I think I got it.

Basically I already have an interval that was refreshing the duration through the getStatusAsync method. I have extended that to detect if isRecording is false even though my apps state is to record. If that is detected, then it automatically start trying to startAsync() (with a try catch). When this is detected the durations is stored to variable and then appended to the new duration.

**Pull request merged**
