### PR TITLE
[expo-blur] Fix Safari support

### PR DESCRIPTION
**Pull request by prichodko**
The guard function correctly checks whether the feature is available with the `-webkit` prefix, but does not use this to set the style property. Setting both `backdropFilter` and `webkitBackdropFilter` fixes the issue for me.

The browsers correctly pick up the property they support (Chrome ignores the `style.webkitBackdropFilter`, and Safari uses it).

(apologies for not following the PR format, I hope it's fine for this minor change)

### CODE REVIEW

**Review by tsapeta — COMMENTED** [review]
Good catch! Thanks for the contribution 🙏 

It's fine if you don't follow the PR description format for such a small thing, but we do require two other things:
- Adding an entry to CHANGELOG.md
- Running `yarn build` in the package folder to regenerate JS files

Could you do that?

**Comment by prichodko** [comment]
Sure thing. 👍

**Comment by prichodko** [comment]
Done. Let me know if there is anything else. 🙂

**Comment by tsapeta** [comment]
Thanks!
I just noticed the PR is targeting the `master` branch which is no longer used, in favor of `main`. I'm wondering if that's why some CI jobs have been canceled by GitHub Actions 🤔 
Could you change the base branch?

**Comment by prichodko** [comment]
So it looks like I accidentally landed on the `master` branch via GitHub search. On the `main`, everything was fixed 2 months ago by Evan (https://github.com/expo/expo/blob/main/packages/expo-blur/src/BlurView.web.tsx#L33-L34). 

Apologies for the confusion @tsapeta. 🙌

**Pull request closed without merging**
