### PR TITLE
[docs] Guides: Remove emoji and unnecessary table of contents in favor right-hand side menu

### PR DESCRIPTION
**Pull request by amandeepmittal**
# Why

Fixes ENG-5361

# How

This PR removes inconsistent emoji usage from Assorted Guides and a few other docs pages under the Guides section. 

It also removes unnecessary Table of Contents (TOC) for "Using Gatsby with Expo for Web" and "Using Electron with Expo for Web" guides. Both of these guides have TOC generated on the right-hand side. (This was not part of the original issue but thought it would be a good refactor.)

# Test Plan

The changes have been tested by running docs locally.

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] This diff will work correctly for `expo build` (eg: updated `@expo/xdl`).
- [ ] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Review by jonsamp — COMMENTED** [review]
As a part of this, can we search for some more emojis? For instance, we use "🍏" for Apple and "🤖" for Android, which I think we can remove.

We also use "⏭" and "👀" in some places. 

This page also has some emojis we can remove: https://docs.expo.dev/workflow/web/

Once we clean those up, I think we can ship this!

**Comment by amandeepmittal** [comment]
@jonsamp, yeah, I can look into more guides and remove emojis from the too. Will update this PR.

**Comment by Simek** [comment]
> we use "🍏" for Apple and "🤖" for Android, which I think we can remove.

I think it would be nice to leave those, as is, so it will be easier to find and replace them in the future with Tags and/or Icons.

Also refs ENG-5271

**Comment by Simek** [comment]
Same with 🚫, ✅ and ❌, where we can use Styleguide Icons instead in the future, but we need test first if it is possible to use icons directly in Markdown files, or did we need to add wrapper/component for them, or maybe find another solution.

**Comment by amandeepmittal** [comment]
I am closing this PR for the new Icon components that are going to be merged (as per my understanding) and moving back the status of the task in Linear to "todo". @Simek's suggestion is great to replace those icons first for which Icon components are available.

I will open a separate PR for emojis that are just used in headers or collapsible notes (emojis that do not need to be replaced with an icon) and do not refer to the apple, andoird, or check mark emojis (emojis that can be replaced with Icon components).

**Pull request closed without merging**
