### PR TITLE
Added Segment group methods

### PR DESCRIPTION
**Pull request by ctgardner**
- added #group and #groupWithTraits to Segment API support

I have added support for the Segment `group` method based upon the documentation. I don't know how to build and/or test this. Also, I am not an Objective-C programmer -could someone closely check the Obj-C code, please?

### CODE REVIEW

**Comment by terribleben** [comment]
Hey there! On the iOS side, the style looks fine, but the Segment module doesn't declare those methods. Here's what's available (not sure how they are meant to be used):
```objc
- (void)group:(NSString *)groupId;
- (void)group:(NSString *)groupId traits:(NSDictionary *)traits;
- (void)group:(NSString *)groupId traits:(NSDictionary *)traits options:(NSDictionary *)options;
```
As you can see, none of those methods take a `userId` parameter, so right now your code won't compile.

**Comment by ctgardner** [comment]
@terribleben Thanks! Yes, I was unsure about the `userId` param. The Android API accepts the `userId`, so I thought the iOS API would need it too. I will update the code.

**Comment by ctgardner** [comment]
@terribleben Could I trouble you to take another look? Alternatively, if you could instruct me on how to verify this myself, that would be better; _teach a man to fish_.

**Comment by terribleben** [comment]
Hi there, sorry for the delay. This looks good and it'll ship next release.

**Pull request closed without merging**
