### PR TITLE
[expo-updates] Deprecate "enabled" configuration setting

### PR DESCRIPTION
**Pull request by wschurman**
# Why

The issue is that people are setting isEnabled to false but the system still expects a URL in order to generate a scopeKey in order to start the NoDatabaseLauncher.

This PR fixes this by removing isEnabled altogether and assuming if expo-updates is installed, the developer wants it to be configured. This has both upsides and downsides:

Pros:
- Much simpler mental model. If it is installed, it is guaranteed to run the same code path for all users. Should be easier to help users if they experience issues (less complexity).
- Clearer what it means to have a "disabled" state. Previously, disabled still ran a bunch of expo-updates code to simulate as if it were not installed, which was liable to be buggy. Now, the way to disable it is to actually remove it which means that the code that runs the bundle is again react native, which is I think what most users expect.
- The library already would throw eventually if not set up correctly. Now, it throws earlier for most users (prebuild users) so they won't find out about it not being set up only in particular run cases.
- Removes the uncertainty about what it means for the JS API when not enabled. Previously users would have to write their javascript to handle when it was disabled in addition to when it was enabled (handle disabled errors). Now, they can assume it is enabled.

Cons:
- Less ability to configure this via app.json. I could imagine this being an issue for users that switched this property in app.config.js. I don't have a great solution to this. But this problem exists for other libraries like `react-native-firebase` and one signal.
- Couples two stages of the development workflow together - defining dependencies and project configuration. One must configure it before they run it, even when just trying it out or starting from a template. IMO this is a definite downside but also exists in other libraries. But IMO the inconvenience here is outweighed slightly by preventing accidental omission of config and erroneously assuming it is set up.

Reading the PR that added this (https://github.com/expo/expo/pull/7358):

> When I initially envisioned this module, I didn't think it was necessary to build in an analog to our current updates.enabled app.json field as people could just not install the module if they didn't want OTA updates. However, since we're most likely going to provide it preinstalled in bare workflow template projects, I think it's worth building in a simple way for people to turn off OTA updates if they don't want them for whatever reason. 

The key here is that, while we did provide it pre-installed for a little while, we removed that pre-installation. So the original premise for adding this is no longer true.

This PR is a re-write of https://github.com/expo/expo/pull/24141 to incorporate decisions from discussions.

Closes ENG-9880.

# How

The way we do this is two-fold:
1. Throw in the config plugin with an extremely detailed error message if the user's previous configuration is no longer supported.
2. Throw at runtime in exactly the same case. This catches users that don't use the config plugin.

Then, we can fix the original bug by removing it altogether.

Most users will not be affected by this. Only those with it set to false, who will be instructed to either configure it or remove it. Those with it set to true but who don't provide a URL would have already seen runtime errors. Those with it set to undefined but don't provide a URL would have also seen runtime errors. We've now improved their experience by telling them about the errors before runtime.

# Test Plan

Build both iOS and android. Run all tests.

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Review by douglowder — APPROVED** [review]
Looks good. We do need to mark the `enabled` flag as deprecated in the Expo config schema in universe and update `@expo/config-types` from there.

**Review by quinlanj — APPROVED** [review]
👍

**Comment by wschurman** [comment]
Going to hold off on landing this and instead look into what it would take to not require a scope key in the NoDatabaseLauncher.

**Comment by wschurman** [comment]
Closing in favor of https://github.com/expo/expo/pull/24466 due to pushback.

**Pull request closed without merging**
