### PR TITLE
fix(mock): fix missing sdkVersion causing jest fail with react-naviga…

### PR DESCRIPTION
**Pull request by kopax**
…tion 5

See https://github.com/react-navigation/react-navigation/issues/6793#issuecomment-583733585

# Why

Please describe the motivation for this PR, and link to relevant GitHub issues, forums posts, or feature requests.

# How

How did you build this feature or fix this bug and why?

# Test Plan

Please describe how you tested this change and how a reviewer could reproduce your test, especially if this PR does not include automated tests! If possible, please also provide terminal output and/or screenshots demonstrating your test/reproduction.

### CODE REVIEW

**Comment by mhuggins** [comment]
I'm running into what I believe is the same error.  This would be nice to fix.

```
 FAIL  __tests__/boot/components/App-test.js
  ● Test suite failed to run

    TypeError: Cannot read property 'split' of undefined

      at Object.global (node_modules/react-navigation-stack/lib/commonjs/vendor/views/Stack/CardStack.tsx:42:26)
      at Object.<anonymous> (node_modules/react-navigation-stack/lib/commonjs/vendor/views/Stack/StackView.tsx:10:1)
```

**Review by EvanBacon — APPROVED** [review]
Ok

**Comment by kopax** [comment]
@EvanBacon , this is blocking update to react-navigation 5 within expo SDK. How can we be informed of the release of this feature? Thanks for merging this feature.

**Comment by brentvatne** [comment]
@kopax - you can use patch-package for now and i'll look at doing a release for this tomorrow

**Comment by kopax** [comment]
https://github.com/react-navigation/react-navigation/issues/6793 got closed and apparently the fix was released.

I am using 

└── jest-expo@36.0.1 

It seems that it was released 2 month ago:

image

May I know how I can get the fix? Thanks!

**Comment by kopax** [comment]
Hi again, can we please have a release of this plugin? I am still stuck and we are now 5.0.5. Please don't forget us :)

**Comment by msell** [comment]
I'm in the same boat as @kopax hoping to see a new release containing the fix soon or at least an estimate of when it might be released.

**Pull request merged**
