### PR TITLE
Use sync random method for auth-session

### PR DESCRIPTION
**Pull request by EvanBacon**
# Why

- fixes the todo

### CODE REVIEW

**Review by brentvatne — APPROVED** [review]

**Comment by stdavis** [comment]
I feel like this broke debugging with React Native Debugger for me because of this issue: https://github.com/facebook/react-native/issues/26705

@brentvatne Are you able to debug with RND using this library after these changes?

**Comment by brentvatne** [comment]
you're right, you won't be able to call this function with react native debugger enabled. you could use the async version or a crypto.getRandomValues, which provides a fallback when sync methods can't be used - https://github.com/expo/expo/blob/master/packages/expo-standard-web-crypto/src/getRandomValues.ts#L23-L30

**Comment by stdavis** [comment]
But I'm not calling this function directly. I'm using `useAuthRequest` which seems to call it behind the scenes. Is there a way for me to configure this hook not to use the problematic sync methods?

**Comment by brentvatne** [comment]
unfortunately no, but you can turn off react native debugger while you're doing auth requests

**Comment by stdavis** [comment]
I'm hoping to use RND to help diagnose issues with my auth requests. :) Is there another option for a debugger?

> we could possibly add an insecure synchronous fallback for the expo-random method being used here...
👍 Are you open to a PR related to this?

**Comment by brentvatne** [comment]
@stdavis - definitely open to a pr!

there is no other option for a debugger at the moment, no. i believe using hermes debugger in flipper would be possible, but we don't support hermes / flipper yet. starting investigations into that soon now that hermes seems to be getting to a good spot.

**Comment by madroneropaulo** [comment]
Yeah I'm having the exact same problem as @stdavis . I'm calling the useAuthRequest and need RN debugger to debug the auth process. So this change is breaking compatibility with chrome based debuggers

**Comment by zchbndcc9** [comment]
Bumping this as I am encountering the same issue. I would like to be able to use the debugger for troubleshooting. Any updates?

**Comment by stdavis** [comment]
I just submitted https://github.com/expo/expo/pull/13616 as an attempt to solve this problem. I'd love feedback! cc @brentvatne

**Pull request merged**
