### PR TITLE
[updates] Add EAS updates to Expo Go project page

### PR DESCRIPTION
**Pull request by wschurman**
# Why

The is a partial re-write of https://github.com/expo/expo/pull/12525 which was closed since it was done a bit early and more requirements needed to be figured out, namely the graphql filtering and manifest permalink for an update object.

This queries EAS updates compatible with this version of Expo Go and platform using the new filtering parameter on the `BranchUpdates` and also doesn't hardcode the URL for the EAS manifest. Instead it gets it from the `manifestPermalink` field on `Update`.

Rough designs, though these include a full app design refresh so this PR is just the structure of launching the project: https://www.figma.com/file/Mcwt6YeqUkQe82lc4mzNNk/Expo-Go-%26-Dev-client?node-id=621%3A31

# How

The main things this does are:

- Change project screen to be a normal stack nav screen instead of a modal since it will need to have a scroll view and a master detail view most likely in the near future, and a stack within a modal is a bit wonky.
- Make the project screen aware of legacy and new updates for showing info like SDK version.
- Make project screen only support apps since it wasn't used for snacks anyways.
- Add a second launch disambiguation screen if the user needs to choose between legacy and new updates.

# Test Plan

https://user-images.githubusercontent.com/189568/116930857-26ca1280-ac15-11eb-86cf-7e763a162b78.mov

### CODE REVIEW

**Comment by esamelson** [comment]
This looks slick  💅  thanks for the video, very helpful in reviewing.

Without looking at any code, my concern is that this adds 2-3 additional screens the user has to click through in order to open a project, which goes against our general ideology of reducing steps & decisions when people are getting started. Can we avoid showing the project screen if there's a compatible update that can be launched right away (keeping the current assumption that the user wants to launch the project when they tap on it in the list)? And if we need to decide between legacy and new updates, can we make our best guess instead of presenting them with a choice (and have a way for them to switch afterwards if they want to)?

**Comment by wschurman** [comment]
> Without looking at any code, my concern is that this adds 2-3 additional screens the user has to click through in order to open a project, which goes against our general ideology of reducing steps & decisions when people are getting started. Can we avoid showing the project screen if there's a compatible update that can be launched right away (keeping the current assumption that the user wants to launch the project when they tap on it in the list)? And if we need to decide between legacy and new updates, can we make our best guess instead of presenting them with a choice (and have a way for them to switch afterwards if they want to)?

We were hesitant to launch an arbitrary manifest since it's becoming far harder to guess the user's intention (many channels, many branches pointing to those channels, and many updates on those branches, legacy and new updates, many compatible SDK versions/exposdk runtime versions). We discussed user preferences and defaults per-project, per-organization, and/or per-user, but decided that they were a bit too complex for this feature at this point.

I'd be okay with making the default tap behavior on the project still be launching the project with an arbitrary manifest, but I do think that at some point information architecture consistency and simplicity across our surfaces will outweigh convenience, even for new users. I don't feel too strongly about anything related to this PR though (I was just implementing the design as discussed and laid out in figma) so I'm probably the wrong person to make an argument for one way or the other. I'll defer to @jonsamp and @tcdavis.

**Comment by tcdavis** [comment]
I did think we were going with something slightly different, where there would be a chevron button to choose your branch if there are multiple options.  This looks like we always present you with the branch selection.
image

> And if we need to decide between legacy and new updates, can we make our best guess instead of presenting them with a choice (and have a way for them to switch afterwards if they want to)?

For the use cases I'm thinking of (demo and testing particular branches) the developer wants to know what it is they're running, so I don't love the idea of running something and fixing it after the fact.   The only idea I recall us discussing that wouldn't add any clicks would be to have a chevron drop down on the items in the project list, but that would not be super usable

**Comment by wschurman** [comment]
> I did think we were going with something slightly different, where there would be a chevron button to choose your branch if there are multiple options. This looks like we always present you with the branch selection.

This is what this PR does. The key thing that @esamelson is talking about though is that on the profile when you currently tap a project it just opens it. This PR makes tapping on a project open the project permalink detail view and then from there the chevron button is tappable.

**Comment by tcdavis** [comment]
OK, cool. I was not getting that from the video.

Generally this PR is expanding the set of things the user might want to launch when they pick a project, and we couldn't find a way to express that without adding clicks.  As designed this adds 1-2 clicks per launch relative to how things work currently. It's possible there's a solution that would make that a flat 1 click, but I don't think it's possible without adding any.

**Comment by wschurman** [comment]
> OK, cool. I was not getting that from the video.

Ah yeah, sorry, I should've included the flow for an app without new updates in the video. Here it is.


https://user-images.githubusercontent.com/189568/116955718-31ea6600-ac48-11eb-93ac-2198a114e77a.mov

**Comment by esamelson** [comment]
> For the use cases I'm thinking of (demo and testing particular branches) the developer wants to know what it is they're running, so I don't love the idea of running something and fixing it after the fact.

That's fair; I guess I don't understand the parameters of exactly what choices the developer will need to be making here. But for the case where the user doesn't need to make any choice, like in the most recent video @wschurman posted, could we reasonably eliminate the intermediate projects screen?

**Comment by wschurman** [comment]
> But for the case where the user doesn't need to make any choice, like in the most recent video @wschurman posted, could we reasonably eliminate the intermediate projects screen?

We can, though to do so we'll need to do a lot of extra data fetching on the profile (same GraphQL request, just a lot more fields). The reason is now we'd need to fetch all the EAS updates on the profile to determine the row tap behavior rather than just the apps to display and then doing the fetch on the permalink page.

**Comment by esamelson** [comment]
Gotcha. Well, if it's a lot of trouble then maybe it isn't a big deal; after all, I guess there are other methods people can use to open projects quickly (QR code, etc).

**Comment by wschurman** [comment]
I think it's more about the inconsistent behavior on a row-by-row basis that concerns me. When tapped, some profile rows will seem to randomly open the experience and others will seemingly randomly push the permalink screen. I think consistency in behavior is probably the better user experience, especially if we don't indicate in the row somehow what will happen when tapped.

**Comment by jonsamp** [comment]
> I think it's more about the inconsistent behavior on a row-by-row basis that concerns me. ...

I think that UX-wise, it's nice to have consistent behavior between every row/navigation, even if it causes some extra taps to get to the project. Also, thinking about the amount of taps here, I don't think it causes a huge issue, because I'd assume you'll navigate to one account's project and view it, and likely not go between every account/project and view them one by one.

Also, I like that the navigation sets up good information hierarchy. (You're a user who owns accounts, those accounts own projects, and projects have details and can be opened)

Later this year, I plan to redesign a lot of these screens, so we can always iterate too if this turns out to be painful for developers.

**Comment by brentvatne** [comment]
here's a mockup of what i think we could change the project detail screen to look like with some notes:

notes

(you should be able to import this png into excalidraw also and resume editing, the scene is embedded).

some things that jumped out to me in the video:

- the main project details screen isn't so useful on its own, we should just put all of the branch/channel stuff there so there is less jumping between screens
- we should also remove metadata that isn't actually necessarily accurate, like the sdk version (each branch / channel could have a different sdk version)
- i am not sure how feasible it is for us to actually list release channels, but i suspect the answer is "not feasible" given the presentation of "Use Classic Updates" or a list of EAS Update branches. either way, i included in the mockup what i think would be more ideal
- launch button does indeed seem to be ambiguous, i made a note about possible things we could do about that in mockup

**Comment by wschurman** [comment]
@brentvatne - what you propose is actually fairly close to what I originally had in my MVP PR that was abandoned (https://github.com/expo/expo/pull/12525) after @jonsamp's redesign.

> launch button does indeed seem to be ambiguous, i made a note about possible things we could do about that in mockup

We talked about a per-project settings where one could configure the button at one point but it seemed like overkill for this MVP. They'd have to live on the server, and we'd have to build out full data models, APIs, etc to support it. What we landed on in design discussions was to do it as a follow-up if we don't land on a completely different design sometime in the nearer future.

> the main project details screen isn't so useful on its own, we should just put all of the branch/channel stuff there so there is less jumping between screens

I don't really feel one way or another other about this, I'm just following the designs at this point. I'm fine making this change if @jonsamp agrees with it.

> we should also remove metadata that isn't actually necessarily accurate, like the sdk version (each branch / channel could have a different sdk version)

I like this idea. @jonsamp - how do you feel about this.

> i am not sure how feasible it is for us to actually list release channels, but i suspect the answer is "not feasible" given the presentation of "Use Classic Updates" or a list of EAS Update branches. either way, i included in the mockup what i think would be more ideal

Yep, not possible. We don't store the release channels as standalone objects in the db so querying them in a paginated (or non-paginated) isn't very doable. For reference, they're just stored as arbitrary denormalized strings on release channel objects which aren't the same thing as release channels (and definitely aren't the same thing as new EAS release channels).

Overall, I do like the simplicity of your proposed changes. I'll pass this back to @jonsamp to address the comment. At some point soon though I'd like to get this landed so people can start using EAS updates internally in Expo Go, and additionally @jonsamp already wants to do a full redesign of this app so whatever we choose will most likely be short-lived.

**Comment by jonsamp** [comment]
I want to avoid having an attention-grabbing button to open a project that's ambiguous, while also having smaller buttons that do similar things below. I think that will confuse users, because usually people don't really read and primary buttons are so easy to click.

I made a revised design that does not require another stack navigation. I think the key is they we conditionally show the big primary button when we can, otherwise show smaller open buttons for all the classic-update/branches options.

https://www.figma.com/file/Mcwt6YeqUkQe82lc4mzNNk/Expo-Go-and-Dev-client?node-id=726%3A1546

project-screen

Would love feedback! @brentvatne @wschurman

**Comment by wschurman** [comment]
@jonsamp - sounds/looks reasonable to me. @brentvatne - any concerns before I implement it?

**Comment by brentvatne** [comment]
my only concern with the mockup is the "Use Classic Updates" button - how does that differ from "Launch project"?

also i'm not sure the description field is needed. i suspect most people don't populate it.

**Comment by wschurman** [comment]
> edit: also re: "Use Classic Updates" - how do we determine whether to show that button or not?

Classic updates will be shown if `app.sdkVersion` is non-null (there is a publish). The launch button will be grayed out if the SDK version is too old.

**Comment by brentvatne** [comment]
@wschurman @jonsamp - what do you think about using the same ui as eas update for classic updates but only showing the `default` branch in the list, then underneath having some description saying to launch from another branch scan the qr code on project page? (or, alternatively, a button that opens an alert to let you enter a branch name).

the "Use Classic Updates" button just really stands out to me as being fairly awkward and likely confusing for users - we should try to pre-empt the question "why not just list all of the branches here?" with the ui

**Comment by wschurman** [comment]
@brentvatne - that sounds good to me

**Comment by wschurman** [comment]
New screen:

https://user-images.githubusercontent.com/189568/118192702-635af280-b3fb-11eb-94dd-bdfcefe08451.mov

**Comment by brentvatne** [comment]
classic update branches -> classic update release channels, perhaps? (it's a lot of words though)

**Review by brentvatne — APPROVED** [review]

**Pull request merged**
