### PR TITLE
Add Class Name to The Expo client app section as it's required by facebook.

### PR DESCRIPTION
**Pull request by Nasseratic**
Add Class Name to The Expo client app section as it's required by facebook.

# Why
It's required by facebook and can't submit without it.

# How
Adding a note and update the image.

### CODE REVIEW

**Comment by cruzach** [comment]
Hey @Nasseratic thanks so much for catching this!

I know this might sound picky- but could you update the image you added to be just of the center view, rather than including the sidebar and all that white space?

**Comment by Nasseratic** [comment]
@cruzach Done! I was trying to help users find their way by leaving the sidebar, but I think it's fine to remove it. :+1:

**Comment by cruzach** [comment]
Thanks! But I think the new image is missing the class name field now 😅

**Comment by brentvatne** [comment]
if the activity class needs to be added for usage in the expo client app as well as in the standalone android app then we should clarify under the android part that people should make sure to set it up for the android expo client before the standalone app

**Comment by Nasseratic** [comment]
Class Name is no longer required by Facebook, I will close this for now!

**Pull request closed without merging**
