### PR TITLE
[docs] Fix image-manipulator Snack examples

### LINKED ISSUE #9783: expo-image-manipulator sample code error [docs]
Run according to the sample code provided on the document and found an error.

link 

https://docs.expo.io/versions/v38.0.0/sdk/imagemanipulator/

code in doc

```
import React, { useState, useEffect } from "react";
import { Button, View, Image } from "react-native";
import { Asset } from "expo-asset";
import * as ImageManipulator from "expo-image-manipulator";

export default function App() {
  const [ready, setReady] = useState(false);
  const [image, setImage] = useState(null);

  useEffect(() => {
    (async () => {
      const image = Asset.fromModule(require("./assets/snack.png"));
      await image.downloadAsync();
      setReady(true);
      setImage(image);
      console.warn(image);
    })();
  }, []);

  const _rotate90andFlip = async () => {
    const manipResult = await ImageManipulator.manipulateAsync(
      image.localUri || image.uri,
      [{ rotate: 90 }, { flip: ImageManipulator.FlipType.Vertical }],
      { compress: 1, format: ImageManipulator.SaveFormat.PNG }
    );
    setImage(manipResult);
  };

  const _renderImage = () => {
    return (
      <View
        style={{
          marginVertical: 20,
          alignItems: "center",
          justifyContent: "center",
        }}
      >
        <Image
          source={{ uri: image.localUri || image.uri }}
          style={{ width: 300, height: 300, resizeMode: "contain" }}
        />
      </View>
    );
  };

  return (
    <View style={{ flex: 1, justifyContent: "center" }}>
      {ready && _renderImage()}
      <Button title="Rotate and Flip" onPress={_rotate90andFlip} />
    </View>
  );
}
```
error

I tried to solve it and found that the order of code execution

This is where I modified

```
 useEffect(() => {
    (async () => {
      const image = Asset.fromModule(require("./assets/snack.png"));
      await image.downloadAsync();
      // change `setReady` `setImage` position.
      setImage(image);
      setReady(true);
      console.warn(image);
    })();
  }, []);
```
So it's not clear what's going on. Has the code on the document been tested?  😭

### PR DESCRIPTION
**Pull request by IjzerenHein**
# Why

Fixes image-manipulator Snack examples, which contain incorrect asset links and a bug (see #10093)

Fixes #9783
Closes #10093

image

image

# How

- Add missing asset for inline Snack
- Fix setImage/setReady order
- Remove example files in favour of inline Snack code
- Update formatting

# Test Plan

- Verified locally for SDK 39
- Verified locally for SDK 38
- Verified locally for SDK 37

### CODE REVIEW

**Review by bbarthec — APPROVED** [review]
LGTM 👍 
Side question: InlineSnacks have different lint rules than other codebase? (here double quotes replaced some single quotes in imports) 🤔

**Review by brentvatne — APPROVED** [review]

**Comment by brentvatne** [comment]
good catch re: formatting @bbarthec. @IjzerenHein - you may want to double check that your editor is using the local prettier config properly - https://github.com/expo/expo/blob/master/docs/.prettierrc should be used in this context and it applies to js that is inside of markdown too

**Comment by IjzerenHein** [comment]
Good catch indeed! The imagemanipulator document in unversioned was using double-quotes, which I just made changes to. I've updated the inline-snack according to the linting rules 👍

**Comment by IjzerenHein** [comment]
We should probably have some automated checking for this. Noticed that many of the `<SnackInline>` definitions mix single- and double quotes @brentvatne

**Pull request merged**
