### PR TITLE
[netinfo] upgrade netinfo to v6.0.2

### PR DESCRIPTION
**Pull request by cruzach**
# Why

https://linear.app/expo/issue/ENG-1891/upgrade-react-native-communitynetinfo

# How

`et uvm` and also deleted `ios/Exponent/Versioned/Core/Api/NetInfo/` 

# Test Plan

NCL ✅

### CODE REVIEW

**Review by tsapeta — APPROVED** [review]
Looks good to me, just add changelog entry 🙂

**Comment by mariomurrent-softwaresolutions** [comment]
Is version > 7 also supported?

**Comment by tsapeta** [comment]
@mariomurrent-softwaresolutions Only since SDK44 😉 It bundles version 7.1.3

**Comment by mariomurrent-softwaresolutions** [comment]
> @mariomurrent-softwaresolutions Only since SDK44 😉 It bundles version 7.1.3

Perfect thx - yeah that's what I meant, if >7 is available since SDK44

**Pull request merged**
