### PR TITLE
Fix issue templates

### PR DESCRIPTION
**Pull request by deniseyu**
# Why

The structure for YAML issue templates has changed! this PR updates the templates so they work again.

# How

n/a

# Test Plan

n/a

### CODE REVIEW

**Comment by cruzach** [comment]
thank you 🙏

**Comment by lukehefson** [comment]
Hey @cruzach! Just wanted to jump on here to say that there are a couple of other breaking changes that you'll want to be aware of [coming to issue forms later today](https://github.com/gh-community/issue-forms-feedback/discussions/75#discussioncomment-576035).

If you view any of the form at https://github.com/expo/expo/tree/master/.github/ISSUE_TEMPLATE you'll see:

> The top-level key `about:` will be deprecated in favor of `description:`. Please use description: instead of about:
> The top-level key `issue_body` is deprecated..

**Comment by cruzach** [comment]
ah awesome, thanks for the warning @lukehefson !

**Comment by lukehefson** [comment]
You're very welcome!

**Pull request merged**
