### PR TITLE
[docs] Fix url to TypeScript website

### PR DESCRIPTION
**Pull request by dennispaagman**
# Why

While reading the docs I noticed the link to the TS website was actually a link to the Flow website.

# How

Simple Markdown change 😄 

# Test Plan

None 👍

### CODE REVIEW

**Review by mauriciord — APPROVED** [review]

**Comment by cruzach** [comment]
thanks! can you make the same changes to the v36 docs? Also, we pull in the react-native docs from react native, so you might want to check upstream if they need the same PR, as well :)

**Comment by djfpaagman** [comment]
Will do! What about the v33 to v35 docs?

**Comment by ide** [comment]
Yes, please go ahead and make this change to all the versions where it looks applicable.

**Comment by djfpaagman** [comment]
@ide: done ✅ the link was only present in the v36 one.

**Review by cruzach — APPROVED** [review]
Thanks!

**Pull request merged**
