### PR TITLE
[camera] add doc comments in source, APISection tweaks

### PR DESCRIPTION
**Pull request by Simek**
# Why

Fixes ENG-1596

To utilize the auto generation feature for API section on the docs website the package source code must contain the relevant documentation.

# How

This PR moves the current documentation of Camera API - https://docs.expo.io/versions/latest/sdk/camera - with tweaks to the package source code:
* avoid export and reimport of the Camera types
* export few missing types

I had also need to add support for the classes methods and properties, to fully support Camera API. This addition affected the other APIs data, so there were small changes required, mostly for the APISection component, but also I had to regenerate `expo-barcode-scanner` data.

One thing which I'm not happy with, is the way in which, Camera constant are exported. Currently all of the constant are visible, but the `Constant` object in which those constants are listed is not visible, we only have `ConstantTypes` object which represents the structure of `Constants` object. The lack of `Constant.<value>` might be a bit confusing for the docs readers. I will look into improving this situation in the future.

# Test Plan

The changes and generated content have been tests running docs website on `localhost`.

`yarn test` run in docs directory was successful.

Lint in docs and package directory also did not yield any errors.

# Preview

Screenshot 2022-01-17 at 13 28 05

# Checklist

- [X] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [X] This diff will work correctly for `expo build` (eg: updated `@expo/xdl`).
- [X] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Review by tsapeta — APPROVED** [review]

**Review by bbarthec — APPROVED** [review]
LGTM 👍

**Comment by ajsmth** [comment]
@Simek looks like these updates break the camera test suite - is it intentional to switch to enums? I don't think they play nice w/ string literals

**Comment by ajsmth** [comment]
disregard the above! missed the PR that fixes already

**Comment by Simek** [comment]
@ajsmth The types were enums earlier, but `ConstantsTypes` has been defined as `typeof` enum, which was the exception in comparison with other Expo modules:
* https://github.com/expo/expo/blob/dfd58c5c102f791ed1b6745ae7ad240e9545a908/packages/expo-camera/src/Camera.types.ts#L246-L254

As I wrote above, generally I don't like the way in which Constants are defined in the Camera package, this leads to the problem with missing `Constants` prefix in docs, and adds a bit of unnecessary complexity because constant are defined as a field of main Camera class. Also TypeDoc was resolving all most of `ConstantsTypes` to `strings` during the JSON data extraction because of that. 

I want to look into possible ways to improve this situation in the future and generally unify the way in which "Constants" are defined across all Expo packages :)

**Comment by ajsmth** [comment]
makes sense - thanks for the explanation!

**Pull request merged**
