### PR TITLE
[android][ci] Add turtle android tarball script

### PR DESCRIPTION
**Pull request by nicknovitski**
Copied mainly from turtle repository.

# Why

This should simplify release work.

# Test Plan

I opened a pr on expo/turtle that used a tarball produced by this pr, and [the smoke tests passed](https://circleci.com/gh/expo/turtle/749).

### CODE REVIEW

**Review by esamelson — APPROVED** [review]
thanks for taking care of this @nicknovitski !! Looks good to me, would just want to get stamp of approval from @dsokal before merging.

**Review by dsokal — APPROVED** [review]
LGTM
We should remove `shell_app_base_android_new` job from expo/universe as a next step: https://github.com/expo/universe/blob/master/.circleci/config.yml#L924

**Comment by nicknovitski** [comment]
@dsokal Agreed.  Should we also remove the tarball script from expo/turtle?

**Comment by dsokal** [comment]
I think we can and should do that. I'll take care of that. Thanks for reminding about this!

**Pull request merged**
