### PR TITLE
Update authentication doc.It  fixes  `Attempted to navigate before mounting the Root Layout component...` issue

### PR DESCRIPTION
**Pull request by mahmut-gundogdu**
# Why
I got the issue
https://github.com/expo/router/issues/740 . I have added a simple fix to that issue.

# How

# Test Plan

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [x] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Comment by aaronksaunders** [comment]
thanks, I should have just submitted the PR instead of posting the code in a comment @mahmut-gundogdu

**Comment by mahmut-gundogdu** [comment]
> thanks, I should have just submitted the PR instead of posting the code in a comment @mahmut-gundogdu

Should I remove the comment in there ?
image

**Comment by e-aleixandre** [comment]
This shows the protected route for a brief moment before actually redirecting to the sign in page. Haven't figured out how to solve that.

**Comment by amandeepmittal** [comment]
Hey @mahmut-gundogdu, we updated the authentication guide with more examples and guided steps to follow. Sorry, you had to face the issue.

Also, we added a [section](https://docs.expo.dev/router/reference/authentication/#navigating-without-navigation) on the specific issue you mentioned

I'm closing this PR for now, but if you still have suggestions or issues, please feel free to open a new one.

**Pull request closed without merging**
