### PR TITLE
[expo-camera] export useful types from CameraModule.types.ts

### PR DESCRIPTION
**Pull request by jarvisluong**
# Why

The constants type such as CameraType, ImageType, ImageParameters, ... are useful to develop an app using expo-camera. An example use case can be:

```js
const [cameraType, setCameraType] = useState<CameraType>(Camera.Constants.Type.back) // More explicit and strict typing.
```

### CODE REVIEW

**Review by tsapeta — COMMENTED** [review]
Thanks @jarvisluong! Could you also run `yarn build` in `expo-camera` directory and commit build files? `expo_sdk` job on CI is failing because of source code not being in sync with build files 😉

**Comment by jarvisluong** [comment]
@tsapeta Right! I forgot to do that. Just pushed the build output

**Review by lukmccall — COMMENTED** [review]
Overall, it's looking good 🥇
However, I'm not sure about changes in `yarn.lock`. Your changes shouldn't modify it.

**Comment by jarvisluong** [comment]
@lukmccall Should I just revert the yarn.lock change?

**Comment by lukmccall** [comment]
> @lukmccall Should I just revert the yarn.lock change?

I believe so, yes.

**Comment by jarvisluong** [comment]
> > @lukmccall Should I just revert the yarn.lock change?
> 
> I believe so, yes.

Done

**Review by lukmccall — APPROVED** [review]
Great job 🎉🥇

**Review by tsapeta — APPROVED** [review]
Thanks @jarvisluong ! 😉

**Pull request merged**
