### PR TITLE
Update Firebase installation guide

### PR DESCRIPTION
**Pull request by rauldeheer**
Add warning to the installation page to make user experience better, since this guide will make your application crash. Check [this issue](https://github.com/firebase/firebase-js-sdk/issues/1824).

### CODE REVIEW

**Comment by AdamJNavarro** [comment]
Hey @rauldeheer,

Thanks for bringing this to our attention. Can you apply those changes to the 32 and 31 versions of the docs? After that, I'll get this merged.

Cheers,
Adam

**Comment by rauldeheer** [comment]
@AdamJNavarro No problem. I'll first try to see what version actually works, because I personally wasn't able to get anything above v6 work. I'll create a repro.

**Comment by AdamJNavarro** [comment]
@rauldeheer I meant apply your docs changes to our SDK31 and 32 versions of our docs. (Right now it's just applied to Unversioned). Sorry for the confusion!

**Comment by sjchmiela** [comment]
The underlying bug in Firebase has been finally fixed, so no extra note is needed as of now! 🎉 

Thank you for contributing to our docs and sorry it took us so long to look into your change proposal. 🙂

**Pull request closed without merging**
