### PR TITLE
[expo-go] Remove unused snackId dev sessions concept

### PR DESCRIPTION
**Pull request by wschurman**
# Why

This is necessary since `Constants.installationId` no longer exists: https://exponent-internal.slack.com/archives/C02T514E4RK/p1706839284791259

This feature was added in https://github.com/expo/expo/commit/5a658e826fd781085505d8d7a6416dd9e4432eb0.

As far as I can tell, the only thing that sends a device ID to dev sessions is https://github.com/expo/expo/blob/main/packages/%40expo/cli/src/start/server/DevelopmentSession.ts#L70, which only gets its devices from `ProjectDevices`, which are only set by https://github.com/expo/expo/blob/main/packages/%40expo/cli/src/start/project/devices.ts#L64, which is only called from https://github.com/expo/expo/blob/main/packages/%40expo/cli/src/start/server/middleware/ManifestMiddleware.ts#L222, which is only `expo-dev-client-id`, which is only sent from dev client.

So, from my investigation, there's nowhere that sends this "snack ID" up to the server in Expo Go, so Expo Go has only ever supported logged-in dev sessions (no device ID based dev sessions). The UI when logged-out backs this hypothesis up:

Screenshot 2024-03-13 at 3 41 32 PM

Would be good to get a review from @brentvatne, the original author, to verify that there isn't somewhere that should be sending up this "snack ID".

# How

Remove the concept.

# Test Plan

`yarn tsc`. Start Expo Go locally, see that it no longer has an error.

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Comment by ide** [comment]
I think the feature you described (account-less sessions based on device) used to work. Don't have a strong opinion on the feature. I might double-check with Cedric to see if he has an opinion on whether to add back the feature or not.

**Comment by wschurman** [comment]
Some history: https://linear.app/expo/issue/ENG-6889/device-id-linking-in-snack-appears-to-be-broken https://github.com/expo/expo/pull/19939#issuecomment-1335978307

I guess the history is that snack used to somehow create a dev session for a device? Not sure I can trace through exactly what it did but the feature was removed from snack and thus this PR is also valid.

**Review by ide — APPROVED** [review]

**Comment by wschurman** [comment]
Home app compilation looks broken in main. Will look into fixing in a separate PR.

**Comment by wschurman** [comment]
Welp nvm this is what broke compilation. No idea why.

**Comment by wschurman** [comment]
Looks like the sha1 import also imported the node types?

**Pull request merged**
