### PR TITLE
[ios] Fix bare notifications in standalone mode

### PR DESCRIPTION
**Pull request by sjchmiela**
# Why

Fixes https://github.com/expo/expo/issues/3223, closes https://github.com/expo/expo/pull/3410.

# How

- do not rely on `experienceId` of the received notification, if it came to our standalone app it must have been addressed to the standalone experience
- in standalone mode redirect all notifications to the standalone experience

# Test Plan

Tested on staging, fixes crash. Unfortunately I also found `notification` initial property to be empty, but this may be a separate issue.

### CODE REVIEW

**Comment by vpontis** [comment]
Thank you for this @sjchmiela!

**Comment by vpontis** [comment]
@sjchmiela I have an ejected app. Do I need to wait for the next cut of Expokit for this fix? Or will updating Expo fix it?

**Comment by vpontis** [comment]
Ah I fixed this by updating `Podfile` and then running `Pod install`

```
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
modified: native/ios/Podfile
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
@ Podfile:7 @ platform :ios, '10.0'
target 'scooter-map' do
  pod 'ExpoKit',
    :git => "http://github.com/expo/expo.git",
    :tag => "ios/2.10.2",
    :tag => "ios/2.10.4",
    :subspecs => [
      "Core"
    ],
```

**Comment by Luckygirlllll** [comment]
@vpontis Hm, I  just see "Pre-downloading: `ExpoKit` from `http://github.com/expo/expo.git`, tag `ios/2.10.4`"  in the console and nothing is going on next during `pod install`

**Comment by vpontis** [comment]
@Luckygirlllll hmm idk how to fix your issue from that info. I would look more into the pod install logs. Could also try `rm -rf` on the pod directory and reinstalling

**Comment by Luckygirlllll** [comment]
@vpontis I have already found the solution, problem was with internet connection, I have tried  to do pod install once again and it worked! Thanks!

**Pull request merged**
