### PR TITLE
Clean up Gyroscope example

### PR DESCRIPTION
**Pull request by Krisztiaan**
# Why

The existing example is highly redundant

# How

Simplified and extracted Gyro handling

### CODE REVIEW

**Comment by brentvatne** [comment]
thanks! can you copy this to the sdk 39 docs directory too?

**Comment by Simek** [comment]
Hi @Krisztiaan, can you rebase you PR and update the example? It would be nice to merge this in! 🙂

**Comment by Krisztiaan** [comment]
Will do

**Comment by brentvatne** [comment]
closing this because it's stale but if you get a chance to clean it up then please open a new pr :)

**Pull request closed without merging**
