### PR TITLE
[video][android] strip non-ascii characters from user agent

### LINKED ISSUE #31647: expo-video user-agent issue in Cyrillic name in app.json
### Summary

The video player does not work if the project is named in Cyrillic. What is the solution? It is also not possible to set the user-agent header manually. When application name is in english, player works normally.

{"message": "A playback exception has occurred: Source error Unexpected IllegalArgumentException: Unexpected char 0x41f at 0 in User-Agent value: Проблема у називању/1.0.0 (Linux;Android 10) AndroidXMedia3/1.4.0"}

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

Android

### Package versions

{
  "name": "expo-issue",
  "version": "1.0.0",
  "main": "expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "expo": "~51.0.28",
    "expo-dev-client": "~4.0.26",
    "expo-status-bar": "~1.12.1",
    "expo-video": "^1.2.6",
    "react": "18.2.0",
    "react-native": "0.74.5"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@types/react": "~18.2.45",
    "typescript": "^5.1.3"
  },
  "private": true
}

### Environment

```text
expo-env-info 1.2.0 environment info:
    System:
      OS: Linux 4.4 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
      Shell: 5.1.16 - /bin/bash
    Binaries:
      Node: 20.17.0 - ~/.nvm/versions/node/v20.17.0/bin/node
      Yarn: 1.22.22 - ~/.nvm/versions/node/v20.17.0/bin/yarn
      npm: 10.8.2 - ~/.nvm/versions/node/v20.17.0/bin/npm
    npmPackages:
      expo: ~51.0.28 => 51.0.32 
      react: 18.2.0 => 18.2.0 
      react-native: 0.74.5 => 0.74.5 
    npmGlobalPackages:
      eas-cli: 12.3.0
    Expo Workflow: managed
```

### Reproducible demo

https://github.com/DomnitskiyOleg/expo-issue

### Stacktrace (if a crash is involved)

_No response_

### PR DESCRIPTION
**Pull request by fobos531**
# Why

Fixes https://github.com/expo/expo/issues/31647 - see that issue for more context.

I'm not aware of this being an issue on iOS, so the change is only done on Android.

# How

Non-ASCII characters are now stripped from the application name.

Additionally, if a `User-Agent` is provided in `headers`, that value is used instead of the default one. This is useful if for any reason, the developer REALLY wants to use their own user agent for logging purposes etc.

# Test Plan

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [X] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Comment by fobos531** [comment]
CleanShot 2024-09-25 at 09 39 31@2x

I see this error in the CI - is there an agreed-upon way to get the application name in SDK packages?

**Review by tsapeta — CHANGES_REQUESTED** [review]
Sadly we can't introduce any new dependencies, even to our own packages, unless there is a strong reason to do so. It's hard to keep them working great for users, especially when multiple versions of the dependency are installed. We've seen a lot of issues caused by this.

I'm also a bit reluctant to add one more `useEffect` that in most cases does nothing. What if we just strip non-ASCII characters on the native side?

**Comment by fobos531** [comment]
> Sadly we can't introduce any new dependencies, even to our own packages, unless there is a strong reason to do so. It's hard to keep them working great for users, especially when multiple versions of the dependency are installed. We've seen a lot of issues caused by this.
> 
> I'm also a bit reluctant to add one more `useEffect` that in most cases does nothing. What if we just strip non-ASCII characters on the native side?

Hey @tsapeta - Thanks for the feedback - I have changed the implementation to be in line with your suggestions, while still giving the user the flexibility to use a custom user agent, if they wish to do so. This is primarily because if the entire app name contains non-ASCII characters, the first part of the user agent string will be just `""`, so if the user wants to enhance the user agent for logging/debugging purposes, they can do that.

**Review by tsapeta — APPROVED** [review]
Thanks for applying my suggestion! Looks good to me now.

**Review by lukmccall — APPROVED** [review]
Looking good. Thanks for your contribution!

**Pull request merged**
