### PR TITLE
[BUG_FIXES] Add types to any-typed props

### PR DESCRIPTION
**Pull request by hbiede**
# Why
Add better typing to expo-camera

# How
I based the results on existing types and the outputs of a current code base.

# Test Plan
Ensure there are no TypeScript errors due to expo-camera typings

# Checklist

- [X] Documentation is up to date to reflect these changes (eg: https://docs.expo.io and README.md).
- [X] This diff will work correctly for `expo build` (eg: updated `@expo/xdl`).
- [X] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Comment by hbiede** [comment]
I don't know what those failed builds are asking me to do...

**Comment by hbiede** [comment]
> > I don't know what those failed builds are asking me to do...
> 
> ```
> The following build files need to be rebuilt and committed:
> build/Camera.js.map
> 
> build/Camera.types.js.map
> 🏁 0 packages passed, 1 package failed: expo-camera
> ```

Yeah, I was more confused by the first one

**Review by bbarthec — CHANGES_REQUESTED** [review]
This looks OK to me 👍 
Regarding failing `DANGER` job - please do not concert yourself about it 😉 
Fix the `check packages` job by rebuilding the `expo-camera` sources and add some CHANGELOG entry and we're ready to go 😉

**Review by bbarthec — APPROVED** [review]
Great work! 🎉 
Thank you very much!
I'm looking forward to many more contributions from you 😊

**Comment by hbiede** [comment]
@bbarthec is there a way to build from my work machine (a PC)? In order to get the source mapping exported with the correct endline characters, I had to build off my personal machine (a Macbook).

**Comment by bbarthec** [comment]
@hbiede, oh! that's interesting. You're saying that on PC (Windows?) running `yarn build` produces a build files/mapping files that are further detected as invalid on CI? 🤔

**Comment by hbiede** [comment]
> @hbiede, oh! that's interesting. You're saying that on PC (Windows?) running `yarn build` produces a build files/mapping files that are further detected as invalid on CI? 🤔

Yeah, if you look at the first commit, you’ll see the maps contain Windows new line escape characters. As far as I can tell, that’s the only difference with the second set of builds

**Pull request merged**
