### PR TITLE
[android][ios][ci] Build clients on github

### PR DESCRIPTION
**Pull request by nicknovitski**
# Why

With this, all of the per-push and per-pull-request workflows are added to GitHub.

For now, the existing release build triggers remain in Circle, but equivalent ones are added to GitHub, usable with `bin/github-repository-dispatch`.

# Test Plan

Something that bothers me is that I have not been able to get the android client building successfully in an environment without secrets.  That is the environment which external pull requests will get run in.  Should `fastlane android build build_type:Release` work when a release key is not present?  If not, I think that we should change that step to only run a release build when the required secrets are in the environment, or only on master and the sdk branches.

### CODE REVIEW

**Review by tsapeta — APPROVED** [review]
Looks good to me! 💪 
In terms of the thing you asked – I'd call @esamelson as I'm not an expert of Android releases.

**Comment by esamelson** [comment]
The only thing we don't want is to have our existing release keystore used in builds from external PRs. We could easily create and use a different release keystore for builds in those environments.

Alternatively, if we can get fastlane to somehow massage the gradle file to use `signingConfigs.debug` instead of `signingConfigs.release` [here](https://github.com/expo/expo/blob/1d75a009c7f21fc7cea810e98f6403c8c633a9b8/android/app/build.gradle#L61) in environments where we don't have the keystore, that would work also, and we wouldn't need to worry about keeping track of two different release keystores depending on the environment.

**Comment by nicknovitski** [comment]
An easy way to do that would be to run `fastlane android build build_type:Debug`.  See `android/app/build.gradle`:
```
# ...
  buildTypes {
    debug {
      debuggable true
    }
    release {
      minifyEnabled true
      proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
      consumerProguardFiles 'proguard-rules.pro'
      signingConfig signingConfigs.release
    }
  }
# ...
```

Are there errors which could be missed if external PRs ran debug builds instead of release builds?  Something like:

```
      - run: |
          if [[ ${ANDROID_KEYSTORE_B64:-unset} = unset ]]; then
            export BUILD_TYPE=Debug
          else
            echo $ANDROID_KEYSTORE_B64 | base64 -d > android/app/release-key.jks
            export BUILD_TYPE=Release
          fi
          fastlane android build "build_type:${BUILD_TYPE}"
```

**Comment by esamelson** [comment]
Running debug builds would be better than no build, but it would be ideal to do release builds, as sometimes where are errors with dexing/proguard that only show up in release builds.

**Comment by nicknovitski** [comment]
Alright, I have (finally) found a working method for everyone to run release builds.

**Pull request merged**
