### PR TITLE
[expo-location][ios] Fix `startLocationUpdatesAsync` requiring background permission

### LINKED ISSUE #12581: [expo-location][sdk41] startLocationUpdatesAsync got broken in permissions refactoring
### Summary

On iOS startLocationUpdatesAsync was working in SDK40 with "foreground" permission only i.e. with "allow when in use", with iOS showing a small UI notification to user on location being active when app was in the background. Refactoring of permissions in SDK41 broke that as startLocationUpdatesAsync checks for background permission on iOS, which is not needed.

For Android this type of location service was enabled with PR #12456 - please note that this capability was available all along for iOS until refactoring in SDK41 broke it.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

SDK41

### Environment

  Expo CLI 4.4.1 environment info:
    System:
      OS: macOS 11.2.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.15.4 - ~/.nvm/versions/node/v14.15.4/bin/node
      Yarn: 1.22.10 - ~/.nvm/versions/node/v14.15.4/bin/yarn
      npm: 7.5.2 - ~/.nvm/versions/node/v14.15.4/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7199119
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ^41.0.0 => 41.0.0
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    npmGlobalPackages:
      expo-cli: 4.4.1
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

Please run @byCedric example app "Office Marathon" in iOS in SDK40 vs. SDK41. 

In SDK40 you can start `startLocationUpdatesAsync` with 'when in use" permissions and you do get the location updates when you app is not in foreground or device display is off, with the similar UI notification as in Android foreground service.

in SDK41 refactoring done / committed by @lukmccall in `EXLocation.m` prevents `startLocationUpdatesAsync` without background permissions, which I understood to be 'always' in iOS UI terminology. Again, note that I do not want to ask from user 'always' permission because it's not needed for this use case - it's the same as in Android.

### PR DESCRIPTION
**Pull request by lukmccall**
# Why

Closes https://github.com/expo/expo/issues/12581

# How

According to https://developer.apple.com/documentation/corelocation/cllocationmanager/1423750-startupdatinglocation?language=objc `startLocationUpdatesAsync` method can be run without the background permission (very similar to https://github.com/expo/expo/pull/12456). However, we can't detect if this method will be run in the foreground or the background. So we can only check the foreground permission which needs to be granted in both cases.

# Test Plan

- bare-expo ✅

# Changelog 

- Fixed `startLocationUpdatesAsync` requiring the background location permission even if was used when the app is in the foreground on iOS.

### CODE REVIEW

**Review by byCedric — APPROVED** [review]
I'm not sure if I'm the best to review here, I'm more Android than iOS

**Comment by bnussman** [comment]
I'm getting 

> LOCATION_BACKGROUND permission is required to do this operation.

on SDK 41 when trying to use startLocationUpdatesAsync() on iOS in a Testflight app.

**Comment by Bashin** [comment]
I applied this change and added $ExpoUseSources = ['expo-location'] to the top of my Podfile and it works for me!

**Comment by MaRaSu** [comment]
Tested also with my app both on simulator and iPhone X + 12 Pro. Indeed works well.

Thanks @Bashin for pointing out the way how to make patching expo packages work! I spent quite some time googling on how to do that with XCode before I noticed your comment (having just started with RN and recently ejected from Expo Managed workflow finding a way around XCode is not trivial...).

**Comment by umarnsisar021** [comment]
> I applied this change and added $ExpoUseSources = ['expo-location'] to the top of my Podfile and it works for me!

Where i will found this Podfile? I am using expo sdk 41 and expo client.. also configured infoPlist in app.json file but still getting NS*LocationDescription.... i tired many fixes but it doesnt work for me.... Now what i do... its very important to do as soon as possible..

**Pull request merged**
