### PR TITLE
[expo-permissions] Add support for limited CAMERA_ROLL permission 

### LINKED ISSUE #9027: Support for new limited access permission to media library (iOS 14)
iOS 14 introduces some new privacy tweaks, one of them is the new way of giving apps the access to media library assets. As an addition to granting access to the entire library, you can now select specific assets that you give the app access to.
We need to make sure it still works well in existing apps (right now it doesn't in Instagram and Messenger) and maybe add some new features related to this.
Another thing worth to mention is that if you don't choose "Allow Access to All Photos" in the first permission request/alert and choose "Select Photos..." instead, then subsequent alerts will give you other options: "Select More Photos..." and "Keep Current Selection".

### PR DESCRIPTION
**Pull request by lukmccall**
# Why

Fixes https://github.com/expo/expo/issues/9027.

# How

Returns `scope` value on iOS - see https://developer.apple.com/documentation/photokit/phauthorizationstatus/phauthorizationstatuslimited?language=objc.

# Test Plan

- simple demo ✅
- test-suite ✅

### CODE REVIEW

**Comment by bbarthec** [comment]
I've added @byCedric as a reviewer as well as he seems to have been working with permissions for a few days recently 😉

**Comment by byCedric** [comment]
Looks great! If you merge this, I'll update my draft PR for the permissions doc update. Just to check, this change is only required in both the `expo-media-library` and `expo-image-picker`, right? Not the `expo-barcode-scanner`, `expo-camera`, or `expo-face-detector`.

**Review by byCedric — APPROVED** [review]

**Review by bbarthec — APPROVED** [review]
LGTM 👍 💪 
Let's wait for some review from @cruzach or @byCedric though

**Comment by byCedric** [comment]
@bbarthec way ahead of you 😉  (a whole 8 minutes)

**Comment by lukmccall** [comment]
> Just to check, this change is only required in both the `expo-media-library` and `expo-image-picker`, right? Not the `expo-barcode-scanner`, `expo-camera`, or `expo-face-detector`.

It's not required in the `expo-barcode-scanner`, `expo-camera`, or `expo-face-detector` cause it changes only `CAMERA_ROLL` permission - not `CAMERA` permission.

**Comment by burivuhster** [comment]
Hi, could you please clarify on how to re-ask permissions for CAMERA_ROLL if the user previously choose "Selected photos" option? I see it is implemented in some native apps (pls see the screenshot attached). 
IMG_2896
But in my app when I call Permissions.askAsync(Permissions.CAMERA_ROLL) it silently just returns 'granted' with accessPrivileges='limited' and do not show the "Select more photos" popup.
I would appreciate your help.

**Comment by lukmccall** [comment]
@burivuhster, this functionality is not implemented yet. However, we're working on it. 

The app will display this prompt when you relaunch it (the app needs to be closed) and ask for permission. The pop-up should show up. However, this behavior is controlled by the system.

**Pull request merged**
