### PR TITLE
[segment] Bump analytics Android library

### PR DESCRIPTION
**Pull request by brentvatne**
# Why

This should fix an issue with Google Play rejecting submissions based on the Segment Analytics library version.

# How

Bump the version based on guidance from @kbrandwijk

### CODE REVIEW

**Review by kbrandwijk — APPROVED** [review]

**Comment by Andrew-Jang** [comment]
How should I implement this solution to my current project?

I'm using expo 44 (bare workflow) using Eas build. Would I need to go through upgrading expo? Would there be a easy solution just to update packages?

**Comment by brentvatne** [comment]
@Andrew-Jang - you can apply this diff manually in your node_modules then use patch-package to persist it

we'll follow up with sdk 44 once we are confident this resolves the issue for everyone on sdk 45

**Comment by npdbilal** [comment]
Please update this for SDK 44

**Comment by CarlosGordo-ux** [comment]
I am not using the Segment library in my app, is there a way to completely remove it? Please !!

**Comment by brentvatne** [comment]
please refer to the pinned thread https://github.com/expo/expo/issues/17845

**Pull request merged**
