### PR TITLE
[local-authentication][android] fix: negative text must be set and non-empty error

### LINKED ISSUE #32075: [expo-local-authentication] Android crashes when disableDeviceFallback is true
### Minimal reproducible example

https://snack.expo.dev/@dcangulo/disabledevicefallback-android-crash

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in a development build, in Expo Go

### Summary

Crashes the Android App:
```
LocalAuthentication.authenticateAsync({
  promptMessage: 'Setup your biometric login',
  disableDeviceFallback: true,
})
```

Does not crash:
```
LocalAuthentication.authenticateAsync({
  promptMessage: 'Setup your biometric login',
  disableDeviceFallback: false,
})
```

Stacktrace from Sentry:
Screenshot 2024-10-16 at 15 32 17

Reproducible in Expo Go (SDK 51):
https://snack.expo.dev/@dcangulo/disabledevicefallback-android-crash

Device:
* Samsung Galaxy S22+ 5G (SM-S906E)
* Android 14

### Environment

```text
expo-env-info 1.2.0 environment info:
  System:
    OS: macOS 14.6
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 18.18.2 - ~/.nvm/versions/node/v18.18.2/bin/node
    Yarn: 1.22.22 - /usr/local/bin/yarn
    npm: 10.2.5 - ~/.nvm/versions/node/v18.18.2/bin/npm
    Watchman: 2024.05.02.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.14.3 - /Users/davidangulo/.asdf/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 15.4/15F31d - /usr/bin/xcodebuild
  npmPackages:
    expo: ^51.0.31 => 51.0.31 
    react: 18.2.0 => 18.2.0 
    react-native: 0.74.5 => 0.74.5 
  Expo Workflow: bare
```

### Expo Doctor Diagnostics

```text
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check if the project meets version requirements for submission to app stores
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check native tooling versions
```

### PR DESCRIPTION
**Pull request by dcangulo**
# Why
`LocalAuthentication.authenticateAsync` on Android crashes when `disableDeviceFallback` is `true`. This line specifically: https://github.com/expo/expo/blob/main/packages/expo-local-authentication/android/src/main/java/expo/modules/localauthentication/LocalAuthenticationModule.kt#L225

Closes #32075 and #30556

# How
The docs (https://docs.expo.dev/versions/latest/sdk/local-authentication/#localauthenticationoptions), says that the `cancelLabel` has a default value of `Cancel`.

I just made it explicit so that it will have the default value whether `disableDeviceFallback` is `true` or `false` and it won't cause a crash due to not providing it.

# Test Plan
This code must not crash on Android:
```
LocalAuthentication.authenticateAsync({
  promptMessage: 'Setup your biometric login',
  disableDeviceFallback: true,
})
```

# Checklist
- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Review by behenate — COMMENTED** [review]
Hi, looks good! Can you just add an entry to  to `packages/expo-local-authentication/CHANGELOG.md` before we merge?

**Comment by dcangulo** [comment]
Hi @behenate, I added an entry now. Thanks.

**Comment by behenate** [comment]
@dcangulo You will also have to run `yarn build` in the `packages/expo-local-authentication` folder an commit the changes from the `build` folder 😅 We should be good to go then, sorry I didn't notice the first time

**Comment by dcangulo** [comment]
@behenate Done!

**Comment by behenate** [comment]
Sorry last thing, there seems to be a lint error:
run `yarn lint --fix` in `packages/expo-local-authentication`
and then `yarn build` in `packages/expo-local-authentication`
after you commit the changes run
`et cp expo-local-authentication` to be sure that the check passes this time 😄

**Comment by dcangulo** [comment]
@behenate Done!

**Review by behenate — APPROVED** [review]

**Comment by MisterCommit** [comment]
jus add        cancelLabel: "Cancel",

 const biometric = await authenticateAsync({
        biometricsSecurityLevel: "strong",
        disableDeviceFallback: true,
        cancelLabel: "Cancel",
      });

**Pull request merged**
