### PR TITLE
[expo-notifications] Add documentation around notification/data Firebase messages

### LINKED ISSUE #10789: expo-notifications cannot properly handle notifications received from Firebase Admin SDK
### Environment
```
Expo CLI 3.28.2 environment info:
    System:
      OS: Windows 10 10.0.18362
    Binaries:
      Node: 12.16.3 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ^39.0.0 => 39.0.3
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz => 0.63.2
      react-native-web: ~0.13.7 => 0.13.18
    Expo Workflow: managed
```

### Issue details

1. When running on Expo's Client, the device push token always issue the following error with FCM: _The credential used to authenticate this SDK does not have permission to send messages to the device corresponding to the provided registration token_.
2. Running on a standalone Android app, the notification is presented on the screen but the Notification object returned by the event of `addNotificationReceivedListener` is the following:
```
{
   "request":{
      "content":{
         "autoDismiss":true,
         "sound":"default",
         "data":null,
         "body":null,
         "sticky":false,
         "badge":null,
         "title":null,
         "subtitle":null
      }, // The values above are not supposed to be null
      "trigger":{
         "remoteMessage":{ // This object was not supposed to be on the "trigger" node
            "originalPriority":1,
            "notification":{
               "usesDefaultVibrateSettings":false,
               "visibility":null,
               "notificationPriority":null,
               "titleLocalizationArgs":null,
               "clickAction":null,
               "color":"#332750",
               "eventTime":null,
               "link":null,
               "usesDefaultSound":false,
               "channelId":null,
               "lightSettings":null,
               "title":"My notification title",
               "imageUrl":null,
               "vibrateTimings":null,
               "tag":null,
               "localOnly":false,
               "bodyLocalizationArgs":null,
               "titleLocalizationKey":null,
               "ticker":null,
               "usesDefaultLightSettings":false,
               "sticky":false,
               "body":"My notification body",
               "sound":"default",
               "icon":null,
               "notificationCount":null,
               "bodyLocalizationKey":null
            },
            "from":"773587893199",
            "ttl":2419200,
            "sentTime":1603496294063,
            "data":{
               "test":"test value",
               "experienceId":"@mateus-araujo/[REDACTED]"
            },
            "to":null,
            "collapseKey":"com.[REDACTED]",
            "messageType":null,
            "priority":1,
            "messageId":"0:1603496294088136%e69c4a24e69c4a24"
         },
         "channelId":null,
         "type":"push"
      },
      "identifier":"0:1603496294088136%e69c4a24e69c4a24"
   },
   "date":1603496294063
}
```
3. Taping on the notification does not trigger the event of `addNotificationResponseReceivedListener`.

 
### Steps to Reproduce

1. The server code used to send the notification is the following:
```
admin.messaging().sendToDevice(
	"MY DEVICE TOKEN",
	{
		notification: {
			title: "My notification title",
			body: "My notification body",
			sound: "default",
			color: "#332750",
		},
		data: {
			experienceId: "@mateus-araujo/[REDACTED]",
			test: "test value",
		}
	},
	{
		collapseKey: "Test key",
		contentAvailable: true,
		priority: "high",
	}
)
```
2. On my "app.json", `android.useNextNotificationsApi` is set to `true`. Setting this property to `false` causes the displayed notification to be blank and no event is ever fired.

### Expected Behavior

1. To receive the notification's "content" object with no null fields, like when using the Expo Push Notification API.
2. For the event of responding to a notification to work.

### PR DESCRIPTION
**Pull request by sjchmiela**
# Why

Fixes https://github.com/expo/expo/issues/10789.

# How

Wrote a hopefully helpful gotcha description around different types of Firebase messages and their handling by `expo-notifications`.

# Test Plan

It seemed to have worked https://github.com/expo/expo/issues/10789#issuecomment-716930785.

### CODE REVIEW

**Review by cruzach — COMMENTED** [review]
it's too bad FCM calls one a "notification" and the other "data", my guess is that's going to confuse quite a few people- all the better that we have a section that clears this up! 

We do have an existing guide on communicating with FCM directly here - https://docs.expo.io/push-notifications/sending-notifications-custom/ - so it might be good to move this section there, what do you think? If you like that idea, I opened a [draft PR with some minor edits](https://github.com/expo/expo/pull/10844/commits/21009f0e17e2342a8a72a0c6576c1973061ac5cb) (although I'd want to make sure it's all still correct)

**Comment by sjchmiela** [comment]
Thank you for adjusting the copy and putting it in the proper guide! ❤️ Personally speaking I find having notifications information spread across guides / API page a bit confusing so imagine the delight when I saw the second commit linking from `Notifications` to the guide! 😍 This PR may be closed by https://github.com/expo/expo/pull/10844 👍

**Comment by cruzach** [comment]
😄 yes _definitely_ couldn't forget linking to it. 

Although that's a good point that we should think about for our docs in general- how do we make sure that different pages that touch the same topic (i.e. `expo-notifications` API and the Expo push service doc pages) are clearly connected and how to make it almost hard for users to read one and not know that they should read the other 🤔

**Comment by cruzach** [comment]
closing in favor of https://github.com/expo/expo/pull/10844

**Pull request closed without merging**
