### PR TITLE
[location] update play services location and smartlocation

### PR DESCRIPTION
**Pull request by g4rb4g3**
# Why

Updated Play Services Location and Smartlocation to latest available versions.

# How

Updated gradle files to latest versions and updated LocationHelper to remove deprecated stuff.

# Test Plan

Built an app and checked location on a real device.

# Checklist

- [-] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- Not required, just module internal changes, nothing changed on the exposed methods.
- [-] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- Not required, see above
- [x] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Comment by AlexanderEggers** [comment]
@g4rb4g3 I had a try with the changes in my project by patching the relevant changes and I have noticed that react-native-maps is not compatible with com.google.android.gms:play-services-location:21.0.0. The version 20.0.0 seems to work fine for me. I would suggest downgrading your PR changes to 20.0.0 to avoid impacting a broader user-base which might be using react-native-maps in combination.

**Comment by g4rb4g3** [comment]
@AlexanderEggers 
Was not aware of it, we are using react-native-maps too in our app and I could not see any issue.
Maybe because we currently use a pretty old release (0.31.1). Could you describe the issue you faced with this PR?

**Comment by AlexanderEggers** [comment]
For example this error which relates to the interface changes Google did: 

`The method 'com.google.android.gms.tasks.Task com.google.android.gms.location.FusedLocationProviderClient.removeLocationUpdates(com.google.android.gms.location.LocationCallback)' was expected to be of type virtual but instead was found to be of type interface (declaration of 'com.airbnb.android.react.maps.FusedLocationSource'`

I'm using the latest react-native-maps.

**Comment by pzatorski** [comment]
@EvanBacon Do you mind looking at this one?

**Comment by alexttyip** [comment]
Hey, `play-services-location` has since been upgraded to `21.0.1` and `react-native-maps@1.8.0` is using the upgraded version of `play-services-location` too.

#23501 downgraded `play-services-location` from `21.0.0` to `20.0.0` since `react-native-maps` wasn't using the upgraded version back then.

Since that's been resolved now, should we upgrade to `play-services-location` to `21.0.1`?

Cheers

**Comment by g4rb4g3** [comment]
Closing since it is not required anymore. I still have mixed feelings on it, I did this PR more then a year ago and no one from the expo team cared about it...

**Pull request closed without merging**
