### PR TITLE
Fix the android getContactByIdAsync issue on Android

### LINKED ISSUE #482: getContactByIdAsync throws an error on android
I have a code that uses `getContactByIdAsync` to get the data of a contact. It works fine on iOS but on Android, I get this error:

> The callback getContactsAsync() exists in module ExponentContacts, but only one callback may be registered to a function in a native module

My guess is that, in [ContactsModule.java#163](https://github.com/expo/expo/blob/ios/sdk19/android/app/src/main/java/abi19_0_0/host/exp/exponent/modules/api/ContactsModule.java#L163), `promise.resolve` gets invoked more than once since it does not quit the `while` loop after fetching the contact.

### PR DESCRIPTION
**Pull request by mohebifar**
Fixes #482.

### CODE REVIEW

**Comment by ccuilla** [comment]
+1

**Comment by arrygoo** [comment]
+1

**Comment by jesseruder** [comment]
Can you share the code that was hitting this bug? Seems like we might want to just put a `break` or `return` after the promise.resolve instead.

**Review by ide — CHANGES_REQUESTED** [review]
I agree with Jesse, if this symptom is related to a missing early return then let's fix it that way.

**Pull request closed without merging**
