### PR TITLE
Docs updated

### LINKED ISSUE #3568: Problem in expo docs
The examples link in payments page of expo docs is down or not working.
### Steps to Reproduce

1.Visit the link [Payments Docs](https://docs.expo.io/versions/latest/sdk/payments/)
2.Click on examples link in the beginning

### Expected Behavior

Takes me to the examples page of expo github repo

### Actual Behavior

Redirected link is not working.

### Screenshot
1.Here is the link not working.
screenshot from 2019-02-25 02-33-31
2.Here is what happened on clicking the link
screenshot from 2019-02-25 02-32-14

### PR DESCRIPTION
**Pull request by ThakurKarthik**
# Why

Please describe the motivation for this PR, and link to relevant GitHub issues, forums posts, or feature requests.

The pr is created to avoid confusion to people who come to documentation for help where some link is broken.The link was broken in the payments sdk page.Once the pr merges it will close #3568
# How

How did you build this feature or fix this bug and why?

I got the working link from other developer and i updated the docs accordingly.
# Test Plan

Please describe how you tested this change and how a reviewer could reproduce your test, especially if this PR does not include automated tests! If possible, please also provide terminal output and/or screenshots demonstrating your test/reproduction.

Go to the [Location](https://github.com/expo/expo/blob/master/docs/pages/versions/unversioned/sdk/payments.md) and click on the examples link.It will be working after the pr merges.

### CODE REVIEW

**Comment by AdamJNavarro** [comment]
Hey @ThakurKarthik,

Thanks for this PR. Is there any chance you could make your changes to the remaining versions in our docs (26-31) so that we have full coverage?

Cheers,
Adam

**Comment by ThakurKarthik** [comment]
@AdamJNavarro  I have covered all the versions.Please review them.

**Comment by ThakurKarthik** [comment]
@AdamJNavarro  did u get time to review the pr?

**Comment by AdamJNavarro** [comment]
Sorry for the delay! We're about to push out a major change to our docs so we're holding off on getting this merged until then. I'll ping you when it's merged.Thanks for checking in!

**Comment by sjchmiela** [comment]
Merged in https://github.com/expo/expo/commit/07c09f913cbbcd96f8a14eff5add940725dc8cad. 🙂

**Pull request closed without merging**
