### PR TITLE
chore(cli): update text for dev client start

### PR DESCRIPTION
**Pull request by EvanBacon**
# Why

Address TODO in CLI

### CODE REVIEW

**Comment by brentvatne** [comment]
```
yarn create expo-app bacon
cd bacon
npx expo run:ios
```

image

i'm not convinced that printing the url or qr code makes much sense in this context given that we're running a bare app and:

- you can't use the qr code or url to open the app in Expo Go
- you can't use the qr code or url to launch the app from your phone unless you passed in `-d` to `npx expo run:ios` and selected your device, in which case it is already running there or you can just tap the icon from the home screen to open it
- the url includes the `expo-development-client` path, but the project doesn't use `expo-dev-client`

that said, i don't know what the best output here is. maybe we just omit the qr code and url? i'd like to get feedback from others on this.

**Comment by brentvatne** [comment]
cc @byCedric @ide for feedback

**Comment by brentvatne** [comment]
also wanted to acknowledge -- one concern about changing the behavior here is that we aren't totally confident that we can reliably detect whether the project uses expo-dev-client.

**Comment by ide** [comment]
In terms of UX alone, it looks like we should show the QR code only when it is relevant to the developer's project. They need to be able to do something with the QR code for us to "spend" the developer's attention and screen space on it.

My understanding is there's little or no objection to having a UX that's customized to the project at hand, and the issues are around figuring out how to customize that UX reliably. In some ways, it's better to always show the QR code than to only sometimes show it at the right times -- the former feels unfinished while the latter feels buggy.

That raises a point related to Brent's last comment: if we had a stable, reliable API for inferring whether the project at hand includes the development client in its development builds, it'd make building this behavior a lot easier. IIRC we've wanted a detection API in one or two other places and maybe it's time to build one we can use in several places.

**Pull request closed without merging**
