### PR TITLE
[emc] fix Kotlin compilation  warning

### PR DESCRIPTION
**Pull request by Simek**
# Why

Screenshot 2022-03-01 at 11 36 02

# How

This PR fixes the deprecated method usage warning, very simple one, but let's keeps logs clean. 😉 

# Test Plan

Package build as expected.

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] This diff will work correctly for `expo build` (eg: updated `@expo/xdl`).
- [X] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Review by barthap — CHANGES_REQUESTED** [review]
The `.uppercase()` was introduced in Kt 1.5 so it won't compile if somebody compiles it with older versions so this is like a breaking change.

We want only do this if we're dropping support for Kotlin <= 1.4, cc @lukmccall as he is more familiar with Kotlin versioning here 😅 

Edit:
I'd rather mark this line with
```kt
@Suppress("Deprecation")
```

**Comment by lukmccall** [comment]
> I'd rather mark this line with
> 
> ```kotlin
> @Suppress("Deprecation")
> ```

I fully agree with @barthap. Please use `Suppress` annotation instead of changing the method.

**Comment by Simek** [comment]
Thank you for the context! I have reverted the change and I have added the suppress deprecation annotation as suggested.

**Review by barthap — APPROVED** [review]
CI looks good now 😁, there are still notes but less offensive:
```
> Task :expo-modules-core:compileDebugKotlin
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
```

**Comment by Simek** [comment]
@barthap There are still few warnings left, do you think is there anything worth looking at?
* https://github.com/expo/expo/runs/5376355072?check_suite_focus=true#step:8:1178

**Pull request merged**
