### PR TITLE
[docs] API expo-image-picker: Fix typo bloc to block

### PR DESCRIPTION
**Pull request by amandeepmittal**
# Why

# How

This PR fixes the typo "bloc" to "block" in [ImagePicker.launchCameraAsync()](https://docs.expo.dev/versions/latest/sdk/imagepicker/#imagepickerlaunchcameraasyncoptions).

For SDK 46 has been cut and is not available as a separate branch, the API docs are only updated with unversioned docs for now.

# Test Plan

The changes have been tested locally.

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] This diff will work correctly for `expo build` (eg: updated `@expo/xdl`).
- [ ] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Review by barthap — COMMENTED** [review]
- Regarding sdk-46, there's no separate branch for docs, all you need to do is:
  ```
  et gdad -p expo-image-picker -s 46
  # which is short of
  et generate-docs-api-data --package expo-image-picker --sdk 46
  ```
  Versioned docs are on main, just in a different directory 😉 

- Pro tip:
  If you're changing code in `packages/expo-*`, you can disable the bot complaining about changelog by pasting `<!-- disable:changelog-checks -->` anywhere in the PR description

**Comment by amandeepmittal** [comment]
Thanks for the details about the process @barthap. Appreciate it! Wasn't aware of it.

One question related to the "diable bot complaints". In this PR, I am fixing a typo in the code comment, is it worth adding that to the changelog?

**Comment by barthap** [comment]
Yeah, I mentioned this bot trick because docs changes, that do not affect real code, are not worth mentioning in changelog 😄

**Comment by amandeepmittal** [comment]
Thanks a lot! Your suggestion worked about updating SDK docs like a charm! Appreciate it 🙏

**Review by barthap — APPROVED** [review]
Good job 👍

**Review by Simek — APPROVED** [review]
LGTM, great work on that fix Aman, thank you! 👍

**Pull request merged**
