### PR TITLE
[docs][expo-constants]: Update the description for manifest and manifest2 properties

### PR DESCRIPTION
**Pull request by amandeepmittal**
# Why

Closes ENG-7120

# How

The updated description to recommend `Constants.ExpoConfig` instead of `manifest` and `manifest2` properties was already there. This PR makes a slight verbiage change to `unversioned` and SDK 47, and backports the updated description 
to SDK 47 docs.

# Test Plan

CleanShot 2023-01-04 at 23 26 48@2x

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Comment by kbrandwijk** [comment]
Is there way to include in that text snippet that it behaves more consistently across _builds_ and updates?
Aside from that, I'm not sold on the 'Prefer using...' verbiage, but I haven't come up with something better either.

**Comment by amandeepmittal** [comment]
@kbrandwijk, I can update the text directly to convey the info about both builds and updates and remove the note. I was initially thinking of going this route to update the description of both fields but then found the note was already there.

**Review by wschurman — APPROVED** [review]

**Comment by amandeepmittal** [comment]
@kbrandwijk, updated the verbiage for the note to mention both Build and Update. Let me know it sounds now.

**Comment by amandeepmittal** [comment]
Closing this since some of the recent TypeDoc changes seems to break even after merging the conflicts. Opened a follow PR for #20816

**Pull request closed without merging**
