### PR TITLE
[test] Rename `unimodules-test-core` -> `expo-modules-tests-core`

### PR DESCRIPTION
**Pull request by lukmccall**
# Why

Closes ENG-4140.
Rename `unimodules-test-core` -> `expo-modules-tests-core`

# How

Rename all appearances of `unimodules-test-core` to `expo-modules-tests-core`.

# TODO (in separate PRs)

- make `expo-modules-tests-core` linkable. 
- add `expo-modules-tests-core` as a dev dependency to packages that are using it. 

# Test Plan

- CI

### CODE REVIEW

**Comment by barthap** [comment]
Side note when looking at this PR: I just noticed that some packages have a `robolectric:4.5.1` dependency while others have `robolectric:4.3.1`. Maybe (perhaps other PR) we could move it to `expo-modules-test-core` as a single source of truth (unless already there)? What do you think?

**Comment by lukmccall** [comment]
> Side note when looking at this PR: I just noticed that some packages have a `robolectric:4.5.1` dependency while others have `robolectric:4.3.1`. Maybe (perhaps other PR) we could move it to `expo-modules-test-core` as a single source of truth (unless already there)? What do you think?

It is already set up like this. `expo-modules-test-core` has all test dependencies as an `api`.

**Comment by tsapeta** [comment]
What do you guys think about `expo-modules-tests-core` name? 😄 (notice `test` -> `tests`)

My reasoning: *modules* in `expo-modules-core` is already plural, because it's the core of expo modules. `expo-modules-tests-core` would be the core of expo modules tests.

**Comment by ide** [comment]
On naming: this is the core package for Expo module tests. Saying `expo-module-tests-core` makes sense but I expect that people look for consistent patterns in npm package names: after seeing `expo-modules-core`, it's natural to think the testing package would be named `expo-modules-...`

Another way to think of this package is that it is the test core for Expo modules: `expo-modules-test-core`, which is what this PR does already.

This is also the testing package for Expo modules: `expo-modules-testing`. Each module would depend on `expo-modules-core` and `expo-modules-testing`.

**Comment by lukmccall** [comment]
I'll go with `expo-modules-tests-core` (notice test**s**) ;)

**Review by tsapeta — APPROVED** [review]

**Pull request merged**
