### PR TITLE
Link to new Amplitude library in old doc

### PR DESCRIPTION
**Pull request by BrodaNoel**
# Why
https://github.com/amplitude/Amplitude-ReactNative/issues?q=is%3Aissue+trackingoptions+is%3Aclosed#issuecomment-1194356579

# Test Plan
Praying. 🙏🏼

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [x] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Comment by brentvatne** [comment]
thanks for sending this pr! i'm not sure yet if this is the right thing to do. let's see what amplitude folks say here: https://github.com/amplitude/Amplitude-ReactNative/issues/132#issuecomment-1205827021

**Comment by brentvatne** [comment]
thanks for sending this pr! i'm not sure yet if this is the right thing to do. let's see what amplitude folks say here: https://github.com/amplitude/Amplitude-ReactNative/issues/132#issuecomment-1205827021

**Comment by BrodaNoel** [comment]
I am implementing that "beta" library right now (I finished 30 seconds ago).
I'll make a deep test, plus a prod release, and see what happens there.

**Comment by BrodaNoel** [comment]
I can confirm Amplitude is properly receiving the data (check on the top-left corner, in grey, the `Dev` environment).

Screen Shot 2022-08-04 at 19 37 18

I understand this doesn't means we can merge the PR. I'm just adding some info about this new library

**Comment by BrodaNoel** [comment]
I think that there are 1 or 2 bugs that may be kind of blocker to fix before migrating to this new library.

https://github.com/amplitude/Amplitude-TypeScript/issues/178
https://github.com/amplitude/Amplitude-TypeScript/issues/177

**Pull request closed without merging**
