### PR TITLE
[expo-gl-cpp] Use array buffer to reanimated worklet runtime

### PR DESCRIPTION
**Pull request by wkozyra95**
# Why

jsi:Runtime pointer sometimes have large enough value that static cast to double is modifying the value

We can't use retinterpret_cast because JSC is tagging values when the number is passed to the js

# How

Use ArrayBuffer to store pointer

This is a breaking change because _WORKLET_RUNTIME from now on has a different pointer. I modified the versioned reanimated code locally, but the same changes will be upstreamed in reanimated

# Test Plan

versioned and unversioned ios client run gl example
unversioned android run gl example

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] This diff will work correctly for `expo build` (eg: updated `@expo/xdl`).
- [ ] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Comment by Kudo** [comment]
thanks for the fix. i can confirm the solution works on android 11.

there're two more points here:
- is it possible to check `_WORKLET_RUNTIME` isNumber and fallback to old casting approach? that would reduce some breaking change risks from reanimated on eas managed apps or bare apps.
- for android reanimated versioned code, we should go through `et remove-sdk` and `et add-sdk` again to get the updated prebuilt lib. i can help with this if necessary.

**Comment by wkozyra95** [comment]
> is it possible to check _WORKLET_RUNTIME isNumber and fallback to old casting approach? that would reduce some breaking change risks from reanimated on eas managed apps or bare apps.

yes, but we leave isNumber, the production builds would still get crashes until new version of reanimated is released and I expect that far more users use expo-gl on android 11 than this worklet integration on all versions of android

> for android reanimated versioned code, we should go through et remove-sdk and et add-sdk again to get the updated prebuilt lib. i can help with this if necessary.

Thanks, It would be great if you could help with that, I'm mostly on linux, and versioning scripts have some incosistances with macos, so I would prefer not to run them on my own(other than just for testing)

**Comment by Kudo** [comment]
> yes, but if we leave isNumber, the standalone builds would still get crashes until new version of reanimated is released and I expect that far more users use expo-gl on android 11 than this worklet integration on all versions of android

all right that makes sense. 

> Thanks, It would be great if you could help with that, I'm mostly on linux, and versioning scripts have some incosistances with macos, so I would prefer not to run them on my own(other than just for testing)

no problem, i can do that after the pr merged.

**Review by Kudo — APPROVED** [review]
🚀 🔥

**Review by tsapeta — APPROVED** [review]

**Pull request merged**
