### PR TITLE
[modules-core] Add permission hook factory

### PR DESCRIPTION
**Pull request by byCedric**
# Why

A while ago I created [`@use-expo/permissions`](https://www.npmjs.com/package/@use-expo/permissions) hooks library, and while we deprecated `expo-permissions`, [this hook might still be useful for a lot of people](https://github.com/byCedric/use-expo/issues/510). 

Even in our own docs, I've seen a lot of examples involving a state hook connected to the permission requesters, e.g.

<details>
<summary><code>expo-barcode-scanner</code></summary>
expo-barcode-scanner-example
</details>

<details>
<summary><code>expo-brightness</code></summary>
expo-brightness-example
</details>

<details>
<summary><code>expo-calendar</code></summary>
expo-calendar-example
</details>

<details>
<summary><code>expo-camera</code></summary>
expo-camera-example
</details>

<details>
<summary><code>expo-contacts</code></summary>
expo-contacts
</details>

<details>
<summary><code>expo-location</code></summary>
expo-location-example
</details>

# How

This adds a permission hook factory for all permission requesters. It's based on our existing [`usePermissions` hook](https://github.com/expo/expo/blob/master/packages/expo-permissions/src/PermissionsHooks.ts#L22), but instead of constants, it accepts the permission getters and requesters.

With this factory we can easily create hooks for single permission requesters:

```js
// In expo-camera
import { createPermissionHook } from 'expo-modules-core';

export const useCameraPermission = createPermissionHook({
  getMethod: getCameraPermissionAsync,
  requestMethod: requestCameraPermissionAsync,
});
```

People would be able to use it like:

```js
import { useCameraPermission } from 'expo-camera';

export function CustomCameraComponent() {
  const [permission, askPermission] = useCameraPermission();

  if (!permission?.granted) {
    return <Button title="Grant camera permission" onPress={askPermission} />;
  }

  return <Camera ... />;
}
```

# API

```ts
// Create a new permission hook
const useXPermission = createPermissionHook({
  /** Method to only fetch the permission status */
  getMethod?: () => Promise<PermissionResult>;
  /** Method to ask the user for permission, if its not granted yet */
  requestMethod?: () => Promise<PermissionResult>;
});

// Use the permission hook
useXPermission({
  /** If the permission should be fetched when mounted, defaults to true */
  get?: boolean;
  /** If the permission should be asked when mounted, defaults to false */
  request?: boolean;
});

// The permission hook return value
useXPermission(...): [
  PermissionStatus | null,
  RequestPermissionMethod,
  GetPermissionMethod,
];
```

# DocBlock result

<details>
<summary>Reference implementation for <code>expo-brightness</code></summary>
expo-brightness-implementation
</details>

<details>
<summary>Reference for generated docblock in editor</summary>
expo-brightness-usage
</details>

<details>
<summary>Reference generated API docs for <code>expo-brightness</code></summary>
expo-brightness-apidocs

expo-brightness-apidocs-interface
</details>

> Note the generated API docs try to anchor-link to the RequestPermissionMethod and GetPermissionMethod types. I think we should not link them if a header with the same ID can't be found. (cc @Simek)

# Test Plan

- Run unit tests in `expo-modules-core`
- Try to use it in a component

# Todos

- [x] Still need to add some unit tests
- [x] Test the result in the generated API docs
- [x] Make sure the docblocks make sense when using in an app

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.io and README.md).
- [ ] This diff will work correctly for `expo build` (eg: updated `@expo/xdl`).
- [ ] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Comment by byCedric** [comment]
@Simek do you know if we can fix this easily?

> The generated API docs try to anchor-link to the RequestPermissionMethod and GetPermissionMethod types. I think we should not link them if a header with the same ID can't be found.

**Comment by Simek** [comment]
@byCedric I you want only to remove links you need to add those types to non-linkable types list in `APISectionUtil`:
* https://github.com/expo/expo/blob/master/docs/components/plugins/api/APISectionUtils.tsx#L54:L65

There is also hardcoded links list, where you can add manual URLs if you want to link those types to external resource.

**Comment by byCedric** [comment]
> @byCedric I you want only to remove links you need to add those types to non-linkable types list in `APISectionUtil`:
> 
> * [`master`/docs/components/plugins/api/APISectionUtils.tsx#L54:L65](https://github.com/expo/expo/blob/master/docs/components/plugins/api/APISectionUtils.tsx#L54:L65)
> 
> There is also hardcoded links list, where you can add manual URLs if you want to link those types to external resource.

This would solve that 😄 Thanks!

**Comment by Simek** [comment]
@byCedric FYI: You can also add `@hidden` tag anywhere in the code comment if you want to prevent the method or type from exporting to the docs data completely. This also might be helpful in case you are describing, example:
* https://github.com/expo/expo/blob/master/packages/expo-task-manager/src/TaskManager.ts#L78

**Comment by byCedric** [comment]
Thanks for that @Simek! I added the non-linkable types and made sure everything works as expected. Should be good to go now! 😄

**Comment by flexbox** [comment]
@byCedric Do you plan to have a simple explanation on the doc with `Linking.openSettings()` 
https://docs.expo.io/versions/latest/sdk/linking/#linkingopensettings

From a user perspective, I noticed recently some people don't know how to "unlock" themselves when they refuse the permissions and it's nice to provide a feedback button "Open Settings"

**Comment by byCedric** [comment]
> @byCedric Do you plan to have a simple explanation on the doc with `Linking.openSettings()`
> [docs.expo.io/versions/latest/sdk/linking/#linkingopensettings](https://docs.expo.io/versions/latest/sdk/linking/#linkingopensettings)
> 
> From a user perspective, I noticed recently some people don't know how to "unlock" themselves when they refuse the permissions and it's nice to provide a feedback button "Open Settings"

That's a good point, thanks for bringing it up! We should mention that [in the permissions guide](https://docs.expo.io/guides/permissions/) (cc @brentvatne). I don't think we should put it inside the hook though, since it's `expo-linking` specific.

**Review by tsapeta — APPROVED** [review]

**Review by brentvatne — APPROVED** [review]
👨‍🍳 💋

**Comment by byCedric** [comment]
Quick status update to monitor missing implementations:

## Done

- [x] `expo-ads-admob`             → [PR #13849](https://github.com/expo/expo/pull/13849)
- [x] `expo-ads-facebook`          → [PR #13850](https://github.com/expo/expo/pull/13850)
- [x] `expo-av`                    → [PR #13851](https://github.com/expo/expo/pull/13851)
- [x] `expo-barcode-scanner`       → [PR #13852](https://github.com/expo/expo/pull/13852)
- [x] `expo-brightness`            → [PR #13853](https://github.com/expo/expo/pull/13853)
- [x] `expo-calendar`              → [PR #13854](https://github.com/expo/expo/pull/13854)
- [x] `expo-camera`                → [PR #13855](https://github.com/expo/expo/pull/13855)
- [x] `expo-contacts`              → [PR #13856](https://github.com/expo/expo/pull/13856)
- [x] `expo-facebook`              → [PR #13857](https://github.com/expo/expo/pull/13857)
- [x] `expo-image-picker`          → [PR #13859](https://github.com/expo/expo/pull/13859)
- [x] `expo-location`              → [PR #13860](https://github.com/expo/expo/pull/13860)
- [x] `expo-tracking-transparency` → [PR #13864](https://github.com/expo/expo/pull/13864)

## Blocked by generics (see #13860)
- [-] `expo-media-library`         → [PR #13862](https://github.com/expo/expo/pull/13862)
- [-] `expo-notifications`         → [PR #13863](https://github.com/expo/expo/pull/13863)

## Missing implementation
- [ ] `expo-file-system` 
- [ ] `expo-sensors`

**Pull request merged**
