### PR TITLE
Prevent errors if podspecPath is undefined

### PR DESCRIPTION
**Pull request by deggertsen**
I ran into a case where the podspecPath was undefined while running yarn prepare. Rather than throwing an error because you can't split something that is undefined, we should simply set it as an empty string. This is assuming we shouldn't instead catch the error and present a meaningful resolution.

# Why

To prevent errors if the podspecPath is undefined.

# How

It was preventing yarn prepare from running successfully and otherwise doesn't seem to have adverse effects.

# Test Plan

It would be good to test with other plugins running yarn prepare, but it's a small change that shouldn't have adverse effects unless there is a reason we should be catching if the podspecPath is not defined. If so, we should instead throw a meaningful error.

# Checklist

- [X] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [X] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [X] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Review by ide — CHANGES_REQUESTED** [review]
Instead of treating the path as an empty string, we should either throw a clear error or write code specifically for this use case that produces output that makes sense. Specifically, it looks like this code intends to replace "podName" in the readme template, and we would need to handle the case where there is no pod name.

**Comment by deggertsen** [comment]
Got the error while running `yarn prepare` after creating an expo plugin. I'm not sure why there would be a missing podName as my plugin wasn't messing with pods at all. I just wanted my plugin to build.

It's fine if we want to close this PR, but I thought I would throw it out there just in case this isn't supposed to prevent plugins from building.

**Comment by wodin** [comment]
> @EvanBacon It sounds like expo-module-scripts is trying to generate a README for some reason. Is this unexpected behavior (I think it is?)?

@ide :point_down: 
image

**Comment by JoshKeenan** [comment]
@ide I am currently unable to complete a build on eas servers as the patch package sadly has no effect on the packages used in the prebuild phase on eas severs. I believe and the fact that this can't generate a readme as I have no associated podspec with my config plugin has completely stopped any build progress. I have been able to build and prepare the plugin on my machine with no issues but can't create a development build as this segment can't find a podspec. Any chances of this being patched anytime soon?

**Comment by ide** [comment]
This is an old PR and I don't recall much of the context behind it other than that is appeared to fix a symptom rather than a cause. My understanding is the root cause needs deeper investigation for a PR to be accepted.

**Comment by JoshKeenan** [comment]
Is there a way to disable this file from running when generating config plugins at all? If not have you got any suggestions for a mitigation/evasion strategy so that config plugins not related to a particular podspecPath could be built in the meantime?

**Review by EvanBacon — APPROVED** [review]

**Comment by EvanBacon** [comment]
Please add a changelog entry for this bugfix

**Comment by ide** [comment]
@byCedric will take a closer look at this PR this week. I suspect there are several changes needed, namely:

1. If `podspecs` is empty, throw a clear error:
```js
throw new Error(
  `The Expo module named "${packageName}" contains an "ios" directory but does not define a Podspec, which is required for modules with iOS implementations.`
)
```
This way, we fail instead of masking a symptom.

2. Call `generateREADME` only when it’s applicable. I’m not sure what those conditions are, but considering that this script starts with `const DEFAULT_HOMEPAGE = 'https://docs.expo.dev/versions/latest/';`, I think this shouldn’t run for modules that aren’t maintained by the Expo team. This is likely related to the root cause of the error at hand.

**Comment by deggertsen** [comment]
I updated the PR so that is not throws an error as suggested by @ide. I'm not exactly sure how to prevent the readme script from running for non-expo packages, but given how little attention this issue has received I'm guessing that it's probably something we don't need to worry about at this time.

I attempted to generate a changelog but the `et add-changelog` didn't work as the "et" command wasn't found. I was not able to easily find what that command is and what I need to install in order to get it working.

**Review by ide — APPROVED** [review]
Approving this PR. For clarity and to set expectations, this PR makes the error message human-friendly and provides a suggestion on how to address it, in contrast with the old error message along the lines of "undefined is not an object".

**Pull request merged**
