### PR TITLE
[docs][tutorial] replace let with const on React.useState()

### PR DESCRIPTION
**Pull request by tkeiyama**
# Why

I think every state must be kept itself immutable.
We could accidentally change the value to something else if we use the `let` declaration.

ref:
[Docs - Hooks: is that `const` a typo ?](https://github.com/facebook/react/issues/13982#issuecomment-433349510)

# How

I just replace `let` with `const` because I'm a React engineer and think the `let` declaration is weird for the state.

# Test Plan

I've done the tutorial by using `const`.

Thank you.

### CODE REVIEW

**Comment by thomasJs8** [comment]
I don't know why the `docs` check is failed.  
Please tell me a solution If I should pass the check

**Comment by brentvatne** [comment]
hi there! the docs check failed only because it can't run on prs from people outside of the expo org, don't worry about it. i don't think it really matters if someone uses let or const for this but i don't mind changing it

**Comment by thomasJs8** [comment]
@brentvatne 
Hi there!!
Thank you for explaining the details to me :)

I've updated the same docs in the `unversioned` directory.
Please check these files and merge this PR if everything is good.

**Review by brentvatne — APPROVED** [review]

**Comment by brentvatne** [comment]
thanks!

**Pull request merged**
