### PR TITLE
[camera] prevent config changes where possible

### PR DESCRIPTION
**Pull request by alanjhughes**
# Why
Because the camera is so sensitive to config changes, we should limit them as much as possible. This also improves performance as the camera is not doing unnecessary setup for default values.

# How
Check that the incoming prop value is different from the current configuration before applying it.

# Test Plan
Bare-expo

### CODE REVIEW

**Review by lukmccall — APPROVED** [review]

**Comment by lukmccall** [comment]
Do you think it would be worth batching the props update? We could use `onViewDidReceiveProps` (or something like this) to only make one update if multiple things were changed.

**Comment by alanjhughes** [comment]
@lukmccall yes, I think it would be useful to have that for some modules where we only want to do the configuration once we have all the prop changes and make them all in a single update on the native side. It'd be particularly useful in this module.

**Comment by lukmccall** [comment]
We have that functionality already built in 😅 Here's an example:  https://github.com/expo/expo/blob/b050aad03e200542567c2af12a46bcc501584d7e/packages/expo-image/android/src/main/java/expo/modules/image/ExpoImageModule.kt#L253-L255

**Comment by alanjhughes** [comment]
I tried that but it doesn't work like I expected or I was using it wrong 😅 it was a while ago so I'll try it again.

**Pull request merged**
