### PR TITLE
Update gradle.groovy

### PR DESCRIPTION
**Pull request by fspugna**
# Why

needed if used with react-native-config having multiple env. Otherwise MainApplication.java file is not found.

# How

# Test Plan

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.io and README.md).
- [ ] This diff will work correctly for `expo build` (eg: updated `@expo/xdl`).
- [ ] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Review by bbarthec — APPROVED** [review]
From my point of view it looks safe, but I'd like others to review it as well 😉

**Review by tsapeta — COMMENTED** [review]
Can I ask you to say something more why is it needed when used with `react-native-config`? Just want to know the use case, to make sure we don't miss anything else 😉

**Comment by brentvatne** [comment]
seconded request from @tsapeta for more information. what's the generic problem that this solves? in the absence of react-native-config, what would the benefit be?

**Comment by brentvatne** [comment]
closing because react-native-unimodules has been replaced by expo modules: https://blog.expo.dev/whats-new-in-expo-modules-infrastructure-7a7cdda81ebc

**Pull request closed without merging**
