### PR TITLE
[docs] Update push notifications setup guide to use development builds

### PR DESCRIPTION
**Pull request by amandeepmittal**
# Why

Closes ENG-7516

# How

- Update screenshots to include/showcase a push notification received on a development build
- Update instructions to include info about `projectId` and why its recommended
  - Also, include `expo-constants` in the installation step
  - Update minimal working example to include `projectId` reference
- Remove Expo Go related info (after discussing with Brent, we thought, Development builds should be the main path)

# Test Plan

Run docs locally and visit http://localhost:3002/push-notifications/push-notifications-setup

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Review by brentvatne — APPROVED** [review]

**Comment by IkeyBenz** [comment]
Hey, I'm investigating an issue where the nativeModule for expo-notifications appears to be undefined when running locally on a simulator. I'm using a managed workflow with eas-builds configured. When I try to run the app using `expo run:ios` or `expo start --ios`, I get a metro bundler issue about "unable to find '__expo_module_name__' of undefined" on import. In fact, the module is undefined in simulator builds. However, I'm perfectly able to run this on a device.

My main point of confusion is that in a fresh expo app (`yarn create expo-app`) installing and importing expo-notifications works fine. Is there anything you can think of that might cause this issue only in simulators? I see the docs say push notifications won't work in simulators, but I think it's expected that the whole package is undefined so want to confirm.

I'm using latest expo 49, and expo-notifications 0.20.1. Any ideas you have would be greatly appreciated!

**Comment by dbarrosoaicor** [comment]
I'm having the same issue. Just importing the library reveals the error `TypeError: Cannot read property '__expo_module_name__' of undefined, js engine: hermes` 
I'm using expo 49.0.13 and expo-notifications 0.20.1 (I've tried other versions and same behaviour)

**Comment by dbarrosoaicor** [comment]
> Hey, I'm investigating an issue where the nativeModule for expo-notifications appears to be undefined when running locally on a simulator. I'm using a managed workflow with eas-builds configured. When I try to run the app using `expo run:ios` or `expo start --ios`, I get a metro bundler issue about "unable to find '**expo_module_name**' of undefined" on import. In fact, the module is undefined in simulator builds. However, I'm perfectly able to run this on a device.
> 
> My main point of confusion is that in a fresh expo app (`yarn create expo-app`) installing and importing expo-notifications works fine. Is there anything you can think of that might cause this issue only in simulators? I see the docs say push notifications won't work in simulators, but I think it's expected that the whole package is undefined so want to confirm.
> 
> I'm using latest expo 49, and expo-notifications 0.20.1. Any ideas you have would be greatly appreciated!
> 
> Edit: It's pretty much what this issue is asking about: #22326

I'm running in the device and couldnt make it work 😢

**Comment by minusleaf** [comment]
Yeah, running into the same issue as well running the EAS build on iOS after just importing.

**Pull request merged**
