### PR TITLE
[expo-updates][ios] Add segmented control for iOS 13

### PR DESCRIPTION
**Pull request by marchenk0va**
# Why

`SegmentedControlIOS` is deprecated in react-native. [Documentation](https://reactnative.dev/docs/segmentedcontrolios) says to use `@react-native-community/segmented-control` instead.

[Issue #7978](https://github.com/expo/expo/issues/7978)

# How

Installed `@react-native-community/segmented-control`.

# Test Plan

Changes should be tested in expo app. Use `SegmentedControl` from `@react-native-community/segmented-control` and run.

### CODE REVIEW

**Comment by tsapeta** [comment]
Hey @marchenk0va,
Unfortunately, it's not enough to make `@react-native-community/segmented-control` available in managed Expo workflow. Because of versioning and supporting multiple SDK versions at once, we have to pull in the native code of 3rd-party libraries to our repository.
We used to be running `et update-vendored-module -m <module_name_to_update>` command to update those libraries, however since it's not pulled and configured yet, you would have to modify the configuration, see `@react-native-community/datetimepicker` for reference:

https://github.com/expo/expo/blob/da65a76036b4dc0a6c00aaf8d5098003eb48449c/tools/expotools/src/commands/UpdateVendoredModule.ts#L282-L295

Let me know if you need any more help!

**Comment by marchenk0va** [comment]
> Hey @marchenk0va, thanks for your contribution! 🙇
> 
> Unfortunately, it's not enough to make `@react-native-community/segmented-control` available in managed Expo workflow. Because of versioning and supporting multiple SDK versions at once, we have to pull in the native code of 3rd-party libraries to our repository.
> We used to be running `et update-vendored-module -m <module_name_to_update>` command to update those libraries, however since it's not pulled and configured yet, you would have to modify the configuration, see `@react-native-community/datetimepicker` for reference:
> 
> https://github.com/expo/expo/blob/da65a76036b4dc0a6c00aaf8d5098003eb48449c/tools/expotools/src/commands/UpdateVendoredModule.ts#L282-L295
> 
> Let me know if you need any more help!

**Comment by marchenk0va** [comment]
@tsapeta I added `segmented-control` on the reference to `datetimepicker`, thanks for help! Have questions about web test suites, I am trying to fix errors but tests seems flaky. Is it the case after adding lib or it's regular issue?

**Review by tsapeta — APPROVED** [review]
Thanks! 🙇‍♂️ Sorry for the delay – I'm gonna merge it right now so it'll be included in SDK38 😉 I'll also take care of updating it again to the latest possible version.

**Pull request merged**
