### PR TITLE
feat: rework fast refresh indicator on web

### PR DESCRIPTION
**Pull request by EvanBacon**
# Why

The refresh indicator UI is a bit outdated. It mentions that updates might not show up— this is from when it was unclear if Fast Refresh would work.

When I wrote Metro web, I reused the native refresh indicator but this is not optimized for mobile devices.

Here's the current design on mobile web:

https://github.com/user-attachments/assets/2b79c768-63ab-4288-93b5-182b97828985

And on desktop:

Screenshot 2024-07-18 at 11 52 10 AM

Another minor issue is that the current implementation uses a lot of React Native for web, which bloats up the base bundle size a bit.

## Design

I originally tried something esoteric, an indeterminate animation that ran in the middle of the screen. The problem with this is that our Fast Refresh is often too fast.

Screenshot 2024-07-16 at 6 53 49 PM

## Badge Design

Last night I went for something a bit simpler. It's a lightning bolt in the corner which pops up and down:

https://github.com/user-attachments/assets/234e8306-acf3-4244-8d99-6272d7e7acb7

Open to other ideas but I think this smaller faster form-factor is ideal. Maybe something with a bit less motion. The refresh events are often so fast that I added a minimum timeout just to give users time to see the change.

# How

- Created a hook to tap the fast refresh events that are sent from `@expo/metro-runtime`.
- Inject a script tag to render the styled elements a bit faster. 
- Animate the badge up, wait a bit, then animate it down.
- If we like the direction and the badge doesn't get too complicated, then we can consider reimplementing on native too.

# Test Plan

- Spam the save button to ensure the animation isn't too janky.
- If you want to try, just run `npx expo` in `apps/sandbox`, open the project on web, and hit ⌘+s on any file in the sandbox project.

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Comment by EvanBacon** [comment]
Here's the hex spinner animation, pretty cool but it's not great at showing concurrent updates. Need something that can be clearly cancelled and re-triggered.

https://github.com/user-attachments/assets/4bcfb07f-8c4b-4dbe-ade2-d55e5ebc5721

**Review by tsapeta — COMMENTED** [review]
Nice! One thing I can nitpick to: it may not be clear what the lightning bolt means, so I would add some text right next to it, e.g. "Fast refreshing...".

**Comment by EvanBacon** [comment]
@tsapeta it often shows for less than 50ms, so text would probably be hard to read.

**Review by tsapeta — COMMENTED** [review]
> it often shows for less than 50ms, so text would probably be hard to read

50ms + the animation duration, which I think is enough to read two words 😅 After reading the code, I'm guessing that you wanted to make it last at least 400ms + animation, right?

**Review by tsapeta — APPROVED** [review]

**Pull request merged**
