### PR TITLE
[router] Fix for push not pushing screens to the stack and working with history

### PR DESCRIPTION
**Pull request by kennethstarkrl**
# Why

It's long been an issue that pushing routes to the stack that use the same base route but different params doesn't push a new screen on the stack. [#25001](https://github.com/expo/expo/issues/25001) [#32338](https://github.com/expo/expo/issues/29928) 

# How

We use React Navigations StackAction.push() directly which allows the new route to push. The previous fix was to create a new key for getId(), however, I found that the key is undefined at that point and adding a key didn't fix the issue. It seems expo-router just lets react navigation generate the keys as it's always passing undefined.

# Test Plan

Tested in a dev build of my prod app. Clicking through pages that using push but have the same path with changing params now pushes a new screen onto the stack properly and works with history.

The setup is to have a page that uses params and pushes when the params change.

(entry)
-test
--[param]
---index.jsx

Navigating to pages /test/1 then /test/2, /test/3 ..etc then navigating back down should now navigate backwards through the stack appropriately.

# Checklist

- [X] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [X] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [X] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Comment by medreres** [comment]
That's great you fixed it, but seems like your code does not conform to formatting rules, does it?

**Comment by kennethstarkrl** [comment]
> That's great you fixed it, but seems like your code does not conform to formatting rules, does it?

I thought it did still kinda rough on the process is there something I missed?

**Comment by kennethstarkrl** [comment]
I found the issue Mark was saying. My app uses a Stack navigator with tabs nested inside with an (entry) folder and subsequent layout. This fix looks like it does not work when you don't use that framework. Looking into it.

**Comment by kennethstarkrl** [comment]
Ok. I'm going to close this. I figured out I was using tabs wrong.
I was using tabs nested inside a stack screen and just expecting the tab routes to push.
As mark said, only stack screens have push.

The solution was to nest a stack navigator inside the tab screen for the subsequent routes to push.
Since in my case it's dynamic, I only needed to nest one stack screen inside the tab route.
This holds the tab screen and pushes the subnested stack screens inside the tab.

-app
--_layout -> tabs screens
---tabs/[id]
----_layout -> stack screens

The starter expo create app has a stack screen at the root navigator. I restructured my project out of that, but if you wanted to keep it I believe you could do this

-app
--_layout -> stack screen
---(entry)
----_layout -> tab screens
-----tabs/[id]
-------_layout -> stack screens

Many have noted, even the react-navigation devs, that the more screens you nest, the weirder things get.

Thanks for your help on this.

**Pull request closed without merging**
