### PR TITLE
[expo-image-picker] Remove READ_MEDIA_IMAGES and READ_MEDIA_VIDEO

### PR DESCRIPTION
**Pull request by aleqsio**
# Why

We want to remove `READ_MEDIA_IMAGES` and `READ_MEDIA_VIDEO` permissions from SDK packages.

These permissions are now sensitive and require justification. See [here](https://support.google.com/googleplay/android-developer/answer/14115180) for more details.

https://linear.app/expo/issue/ENG-13698/remove-read-media-images-and-read-media-video-from-sdk-packages

# How

Did some testing on API>=34, API33 and API28.

I think we can safely remove these from `AndroidManifest.xml` without even adding them to the config plugin options, since having them does not change the behavior of image picker – it either uses the `READ_EXTERNAL_STORAGE` on API<33, or the OS limited access picker that returns only the selected photos for us.

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Comment by alanjhughes** [comment]
Hey @aleqsio! Have you tested using the legacy picker? We can pass an option, `legacy` and this will use the old picker. Bluesky needed this because there was some limitations in the `PhotoPicker`.

**Comment by aleqsio** [comment]
Good catch! 
Will check it out, but if it's broken I would just deprecate it and add a comment that you need to manually add the needed permissions.

**Comment by aleqsio** [comment]
@alanjhughes Confirmed the legacy picker still works on API34, API33 and API28.

**Review by lukmccall — APPROVED** [review]

**Comment by vanGalilea** [comment]
Hey guys, when will this be released? Having the approaching Google's deadline in mind.

**Comment by DanielDanaee** [comment]
Does this mean that we add the permissions ourselves, based on how intensely, or often, we use the expo-image-picker?

**Comment by lucksp** [comment]
> Hey guys, when will this be released? Having the approaching Google's deadline in mind.

+1 to check on release availability...I am on SDK 51 FWIW

**Comment by mrakesh0608** [comment]
I also faced the same issue. For SDK 51 & below, you can add these two permissions to the Android `blockedPermission` list. After that, submit the new build to the Play Store.

```
 android: {
        blockedPermissions: [
            'android.permission.READ_MEDIA_IMAGES',
            'android.permission.READ_MEDIA_VIDEO',
        ],
    },
```


For SDK 52 and above, you don't need to do anything.

**Comment by aleqsio** [comment]
@emarose Perhaps you have a different library adding those permissions? I went through our packages and the only one that could is expo-media-library (by design).

If you still see that in a clean SDK52 project after installing image-picker I'd appreciate you opening a new issue with a minimal repro 🙇‍♂️

**Pull request merged**
