### PR TITLE
[dev-menu][dev-launcher] cleanup usage of extensions

### PR DESCRIPTION
**Pull request by ajsmth**
# Why

This PR aims to remove some of the indirection related to making calls via dev menu - specifically it removes the `dispatchCallable` pattern from internal use and instead makes these method calls more explicit and easier to follow 

From what I can tell, the extensions API is used internally to register related to UI state that was used in the old dev menu (no longer needed), functions that could be called from JS in the old dev menu (simplified by making more explicit), and to register key commands (also made these more explicit) 

I think the next step for a future PR would be to isolate the register / extension API into a helper class as it adds quite a bit of noise to the `DevMenuManager` class 

# How

Updated the `DevMenuInternalModule` api by adding explicit calls for each dev menu function, and then mapping those to `DevMenuManager` and refactored the `DevMenuDevToolsDelegate` to the `DevMenuDevSettings` class

Updated where we register key commands by explicitly stating them in `DevMenuManager` (Android) and  `DevMenuKeyCommandInterceptor` (iOS)

# Test Plan

The changes are primarily internal but I've ensured that all the dev menu buttons and hotkeys still work on both platforms

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] This diff will work correctly for `expo build` (eg: updated `@expo/xdl`).
- [x] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Review by lukmccall — COMMENTED** [review]
I'm not a big fan of those changes. First of all, the native dev menu code starts to know about dev-launcher that way. Also, I don't see the benefits of explicitly calling the dev menu functions. Yea, the code is more explicit and may be easier to follow but you also added more code to handle those calls. And we lost one thing that way - the extension API can handle multiple screens. If you'll have another screen in the menu and you'll try to invoke an action there, it works differently than without that screen.  For instance, the keyboard shortcut will be scoped to the particle screen.

**Comment by ajsmth** [comment]
@lukmccall thanks for the feedback!

>>> First of all, the native dev menu code starts to know about dev-launcher that way. 

The home button is hard coded in the dev menu, I suppose we could change the name of the delegate to be more related to "Home" but it makes sense for it to know about the button and delegate that call IMO

>>> Also, I don't see the benefits of explicitly calling the dev menu functions. Yea, the code is more explicit and may be easier to follow but you also added more code to handle those calls

This can easily be converted to a string call and a switch statement if you really want, but I think in general native modules usually declare their functions explicitly like this. 

In either case, the general sentiment here is that it makes things easier to understand because tracking down what is actually doing the call is a matter of one or two steps instead of several layers of indirection, and generally has removed a lot of code 

>>> And we lost one thing that way - the extension API can handle multiple screens. If you'll have another screen in the menu and you'll try to invoke an action there, it works differently than without that screen. For instance, the keyboard shortcut will be scoped to the particle screen.

can you explain what you mean here?

**Comment by ajsmth** [comment]
@lukmccall @esamelson  I thought about this a bit over the weekend - what if we were to provide a mechanism to pass a JS bundle to the dev-menu module - this would give us the flexibility to customize as much as we'd like for a given use case (in terms of markup, layout, functionality etc) while maintaining the core features of handling dev setting / bridge functions and the bottom sheet, and wouldn't add any additional major API surface to the dev menu itself. Let me know if this makes sense to you two

**Comment by lukmccall** [comment]
> @lukmccall @esamelson I thought about this a bit over the weekend - what if we were to provide a mechanism to pass a JS bundle to the dev-menu module - this would give us the flexibility to customize as much as we'd like for a given use case (in terms of markup, layout, functionality etc) while maintaining the core features of handling dev setting / bridge functions and the bottom sheet, and keep the API / features of the dev menu relatively small

Yes, that makes sense. However, this is what we want to achieve with the extension API. I'm currently moving that extension API to JS, but for now, we have its native implementation. Moreover, we have documentation about that https://docs.expo.dev/development/extending-the-dev-menu (it's a little bit outdated)

**Comment by ajsmth** [comment]
I think we should try and avoid locking into a native api that dictates things like layout and UI in favour of using React, but it makes sense to me to use the extensions API to easily register native functions that could be used in the JS app

**Review by lukmccall — APPROVED** [review]
So after our internal discussion, we can merge that ;)

**Comment by ajsmth** [comment]
> So after our internal discussion, we can merge that ;)

Awesome thanks - going to hold off on merging this until the extensions API is solidified!

**Comment by ajsmth** [comment]
I will take another look at this and create a new PR when this is scoped: https://linear.app/expo/issue/ENG-5311/cleanup-unused-deprecated-code-in-dev-menu-and-dev-launcher

**Pull request closed without merging**
