### PR TITLE
[expo-camera] Play shutter click sound, when picture is taken.

### PR DESCRIPTION
**Pull request by pranavbabu**
# Why
This pull request introduces a new feature that enables system sound playback in the Kotlin codebase. 

Please review this pull request and provide any feedback or suggestions for improvement.

# How

It leverages the MediaActionSound class from the Android framework to play predefined system sounds.
This feature enhances the application's user experience by providing audible feedback to take picture action.
# Test Plan

Build app, add expo-camera default setup, take picture, hear the shutter sound.

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Comment by hirbod** [comment]
I think this should be controllable via prop.

**Comment by hirbod** [comment]
I think this should be controllable via prop.

**Comment by fobos531** [comment]
> I think this should be controllable via prop.

@pranavbabu 

Adding to this, could you add this feature to iOS so that there's feature parity between platforms? See https://stackoverflow.com/a/32280264

**Review by lukmccall — COMMENTED** [review]
Looks good, but could you kindly attend to the comments provided earlier?

**Comment by frederikocmr** [comment]
@lukmccall This PR should be closed, is not valid anymore since this has been already added to the latest version of expo-camera following a different code. I just pushed a fix because it was not obeying the phone's mute state and even tho playing the sound.

**Pull request closed without merging**
