### PR TITLE
[docs] Drop sdk 35 from the docs

### PR DESCRIPTION
**Pull request by byCedric**
# Why

SDK 39 also brings in the deprecation of SDK 35 (I think).

> **Blocked by SDK 39 release**

# How

Docs change

# Test Plan

Docs change

### CODE REVIEW

**Comment by bbarthec** [comment]
@esamelson, do this need to wait for `pushing to production` phase or not really? 🤔

**Comment by byCedric** [comment]
@bbarthec maybe its better to merge to keep it open. If you merge this one, it will be deployed right away.

**Comment by esamelson** [comment]
Yeah, we'll need to wait until we release SDK 39 to merge this, as there's no way to prevent it from being pushed to production in the meantime,.

**Comment by byCedric** [comment]
I'll move it to a draft PR, just to emphasize this isn't ready for merging 😄

**Comment by byCedric** [comment]
I'm going to redo this PR.

**Pull request closed without merging**
