### PR TITLE
Make expo-notifications compatible with Mac Catalyst

### PR DESCRIPTION
**Pull request by robertying**
# Why

Make expo-notifications compatible with Mac Catalyst

# How

Add a macro check to disable `Location Trigger` for Mac Catalyst.

### CODE REVIEW

**Review by sjchmiela — APPROVED** [review]
Wow, that's great, thank you for the contribution! :tada: Do you use this module with Mac Catalyst?

Please note since we don't target this platform at the moment with any of our packages we won't be able to provide full support for it (as we strive to do with iOS, Android and Web platforms).

**Comment by sjchmiela** [comment]
Could you please add a CHANGELOG entry under `master`—`Bug fixes` mentioning this fix? 🙏

**Comment by robertying** [comment]
> Wow, that's great, thank you for the contribution! 🎉 Do you use this module with Mac Catalyst?
> 
> Please note since we don't target this platform at the moment with any of our packages we won't be able to provide full support for it (as we strive to do with iOS, Android and Web platforms).

Yes! Usually most of expo's modules can work for Mac Catalyst as long as it uses the latest APIs.

**Comment by robertying** [comment]
> Could you please add a CHANGELOG entry under `master`—`Bug fixes` mentioning this fix? 🙏

Just pushed!

> Could you please add a CHANGELOG entry under `master`—`Bug fixes` mentioning this fix? 🙏

Just pushed one commit

**Pull request merged**
