### PR TITLE
Updated web constants

### LINKED ISSUE #8004: [web] appOwnership should not be expo
appOwnership refers to where something is running, on web this is not expo client.

### PR DESCRIPTION
**Pull request by EvanBacon**
# How

- Fix linking URIs 
- Make app ownership return null on bare and web. fix https://github.com/expo/expo/issues/8004
- Add basic headless mode

### CODE REVIEW

**Comment by cruzach** [comment]
What do you think about `appOwnership` returning `standalone` in the bare workflow? That way it matches the description of appOwnership anyways:
> If expo, the experience is running inside of the Expo client. If standalone, it is a standalone app

**Comment by bbarthec** [comment]
@cruzach, isn't `standalone` confusing a little bit? 🤔
`standalone` = `build by turtle` ⬅️ that's my understanding of `standalone`, maybe we need some further clarification in docs? 🤔 
`bare` = just `bare workflow`
`expo` = app in `Expo Client`

**Comment by cruzach** [comment]
I thought standalone app was just anything that's **not** running in the Expo Client app (i.e. it is an app capable of running on it's own)

**Comment by EvanBacon** [comment]
@cruzach standalone should dictate that the app is running in a static environment built by turtle. This means that checks to standalone could be used for knowing that `scheme` from the app.config is a valid redirect URI, etc..

**Comment by cruzach** [comment]
Okay, we should make it clear in the docs that that's what `appOwnership === standalone` means, and/or make it clear that `appOwnership` returns `null` on bare/web

**Review by brentvatne — APPROVED** [review]

**Review by bbarthec — APPROVED** [review]

**Pull request merged**
