### PR TITLE
chore: use asset registry directly

### PR DESCRIPTION
**Pull request by EvanBacon**
# Why

`react-native/Libraries/Image/AssetRegistry` is [an alias](https://github.com/facebook/react-native/blob/5a7ae618a28d148d5a66f7c6e09a024405ce21f8/packages/react-native/Libraries/Image/AssetRegistry.js#L13) for `@react-native/assets-registry/registry.js`. Deep imports to `react-native` is bad for web because the alias of `react-native` -> `react-native-web` doesn't work for any nested imports.

This change also updates the nested import for metro web so we no longer pull in react-native on web.
Any modules in expo-asset with nested imports to react-native have been switched to not be the default module, e.g. `.ts` -> `.native.ts` which also revealed a type issue.

If I remember correctly, @Kudo tried to do this same migration but had to revert a while ago. I'm assuming that was just due to how new the import was.

# Test Plan

- TBD. Most E2E tests should cover this change.

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Review by Kudo — APPROVED** [review]
code changes are looking good.

the `react-native/Libraries/Image/AssetRegistry` import was introduced from #21559 that to prevent  `@react-native/assets` -> `@react-native/assets-registry` breaking changes from react-native 0.72. since we run 0.72 for a while, now we can just import from `@react-native/assets-registry` without problems.

just one question where `@react-native/assets-registry` is a transitive dependency, not pretty sure whether we can just import the package without breaking pnpm isolated mode. cc @byCedric for more insights.

**Review by aleqsio — APPROVED** [review]
Can confirm I saw a lot of issues around AssetRegistry when attempting to migrate bare-expo web to metro. Thanks for taking care of the fix!

**Comment by brycnguyen** [comment]
This change broke my assets from appearing in my monorepo after upgrading SDK 49 to SDK 50. More details [here](https://discord.com/channels/695411232856997968/1212854474196910080/1213173154818695239) Not entirely sure what's the cause yet, but I was able to fix it by overriding assetRegistryPath back to `react-native/Libraries/Image/AssetRegistry`

**Comment by kirill3333** [comment]
@EvanBacon expo-image still have some react native internal aliases like this:

```js
import resolveAssetSource from 'react-native/Libraries/Image/resolveAssetSource';
```

https://github.com/expo/expo/blob/main/packages/expo-image/src/utils/resolveAssetSource.tsx

**Pull request merged**
