### PR TITLE
[docs] Update `expo-battery` docs to use function component

### PR DESCRIPTION
**Pull request by ccheever**
# Why

Reviewing docs as part of docs jam. Thought it would be worthwhile to update the `expo-battery` example

# How

This updates the expo-battery docs to use a function
component instead of a class component. This is how most modern
React users will likely want to use this.
    
This change also adds a visualization of a battery to the example
Snack, just to make it more visual and fun. The code for this is
hidden from the docs so that it is not a distraction.

# Test Plan

Tested on iOS and Android devices manually

image

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.io and README.md).
- [ ] This diff will work correctly for `expo build` (eg: updated `@expo/xdl`).
- [ ] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Comment by ide** [comment]
The PR looks like it brought along a bunch of other commits / needs to be rebased.

**Comment by ccheever** [comment]
Yes. I messed this up. I’ll make a new PR

**Comment by Simek** [comment]
It would be nice to have this example updated, @ccheever will you have a free while in the near future to work on new PR? 🙂

**Comment by tsapeta** [comment]
@ccheever I'm closing it for now (see reasons mentioned above). Feel free to update the PR or create a new one, I'll be happy to review it 😉

**Pull request closed without merging**
