### PR TITLE
[android] remove Branch module, make Branch SDK compileOnly in expoview

### PR DESCRIPTION
**Pull request by esamelson**
# Why

Forward-looking version of https://github.com/expo/expo/commit/0f1d68c2b0f21ab9de9e6971d97bc0eedbf91977

We need to remove Branch from Android standalone apps (plus it's not used in the client anyway), but keeping the dependency as compileOnly in expoview will allow people to install the `react-native-branch` package themselves in an ExpoKit project, or include it in a customizable turtle build if we decide to support it.

# How

- Make dependency compileOnly in expoview and remove from app/build.gradle.
- Add checks around all Branch calls to make sure the class can be found.
- Try to call `react-native-branch` module directly rather than through RNObject.

# Test Plan

Expo client without the versioned expoviews (which still include a branch dependency) compiles and runs without crashing. Also, it does not include the Branch SDK (I unpacked the .apk to verify this).

### CODE REVIEW

**Review by ide — APPROVED** [review]

**Comment by n-sviridenko** [comment]
I'm trying to make branch work again w/ sdk 33 (detached):

```diff
diff --git a/android/app/build.gradle b/android/app/build.gradle
index e2e894c..c5e8c90 100644
--- a/android/app/build.gradle
+++ b/android/app/build.gradle
@@ -186,6 +186,11 @@ dependencies {
 
   implementation project(':expo-payments-stripe')
 
+  // this is enough due to https://github.com/expo/expo/commit/8e8d25c23ab26f3e32a2c285210cd71907a17659#r34132089
+  // (see the comment)
+  // related PR: https://github.com/expo/expo/pull/4058
+  implementation project(':react-native-branch')
+
   implementation 'com.facebook.android:facebook-android-sdk:4.34.0'
   implementation project(':react-native-fbsdk')
 
diff --git a/android/app/proguard-rules.pro b/android/app/proguard-rules.pro
index 562f72f..fef4e16 100644
--- a/android/app/proguard-rules.pro
+++ b/android/app/proguard-rules.pro
@@ -161,3 +161,6 @@
 ##### Firebase #####
 -keep class io.invertase.firebase.** { *; }
 -dontwarn io.invertase.firebase.**
+
+##### Branch #####
+-dontwarn io.branch.**
diff --git a/android/app/src/main/AndroidManifest.xml b/android/app/src/main/AndroidManifest.xml
index 1387975..c912c75 100644
--- a/android/app/src/main/AndroidManifest.xml
+++ b/android/app/src/main/AndroidManifest.xml
@@ -387,7 +387,7 @@
     <!-- Branch init -->
     <meta-data android:name="io.branch.sdk.BranchKey" android:value="key_live_icPjVJrhIOQZJ6QaCzGqjhkgzzlN6Nk0" />
     <meta-data android:name="io.branch.sdk.BranchKey.test" android:value="key_test_cfScRMxpGIV3UWRpwEO2idajyspK4Lvf" />
-    <meta-data android:name="io.branch.sdk.TestMode" android:value="false" />
+    <meta-data android:name="io.branch.sdk.TestMode" android:value="true" />
 
     <!-- Branch install referrer tracking (optional) -->
     <receiver android:name="io.branch.referral.InstallListener" android:exported="true">
diff --git a/android/app/src/main/java/host/exp/exponent/MainApplication.java b/android/app/src/main/java/host/exp/exponent/MainApplication.java
index b29766b..e36b44e 100644
--- a/android/app/src/main/java/host/exp/exponent/MainApplication.java
+++ b/android/app/src/main/java/host/exp/exponent/MainApplication.java
@@ -15,6 +15,7 @@ import okhttp3.OkHttpClient;
 
 // Needed for `react-native link`
 // import com.facebook.react.ReactApplication;
+import io.branch.rnbranch.RNBranchPackage;
 import com.facebook.reactnative.androidsdk.FBSDKPackage;
 import io.invertase.firebase.RNFirebasePackage;
 import io.invertase.firebase.instanceid.RNFirebaseInstanceIdPackage;
@@ -50,6 +51,7 @@ public class MainApplication extends ExpoApplication implements AppLoaderPackage
 
         // Needed for `react-native link`
         // new MainReactPackage(),
+        new RNBranchPackage(),
         new FBSDKPackage(mCallbackManager),
         new RNFirebasePackage(),
         new RNFirebaseInstanceIdPackage(),
diff --git a/android/app/src/main/java/host/exp/exponent/generated/DetachBuildConstants.java b/android/app/src/main/java/host/exp/exponent/generated/DetachBuildConstants.java
index cc7d9a3..36cb19d 100644
--- a/android/app/src/main/java/host/exp/exponent/generated/DetachBuildConstants.java
+++ b/android/app/src/main/java/host/exp/exponent/generated/DetachBuildConstants.java
@@ -3,6 +3,6 @@ package host.exp.exponent.generated;
 // This file is auto-generated. Please don't rename!
 public class DetachBuildConstants {
 
-  public static final String DEVELOPMENT_URL = "";
+  public static final String DEVELOPMENT_URL = "voypost://127.0.0.1:19000";
 
 }
diff --git a/android/settings.gradle b/android/settings.gradle
index 9961d8a..1f4a82d 100644
--- a/android/settings.gradle
+++ b/android/settings.gradle
@@ -1,5 +1,8 @@
 include ':app'
 
+include ':react-native-branch'
+project(':react-native-branch').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-branch/android')
+
 include ':react-native-fbsdk'
 project(':react-native-fbsdk').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-fbsdk/android')
 
diff --git a/ios/Podfile.lock b/ios/Podfile.lock
index b3a04ad..4fa8352 100644
--- a/ios/Podfile.lock
+++ b/ios/Podfile.lock
@@ -819,6 +819,6 @@ SPEC CHECKSUMS:
   UMTaskManagerInterface: 296793ab2a7e181fe5ebe2ba9b40ae208ab4b8fa
   yoga: 92b2102c3d373d1a790db4ab761d2b0ffc634f64
 
-PODFILE CHECKSUM: 2d1ff786b8de8a4d146601fc6678319ef0619fa2
+PODFILE CHECKSUM: 668ed53ce24233042437bfda35b2f9746f024c5b
 
 COCOAPODS: 1.7.2
```

It logs the following:

```
E/RNBranch: Branch native Android SDK not initialized in openURL
```

How can I make it work? @esamelson @ide

**Comment by esamelson** [comment]
Hey @n-sviridenko - my bad, in this PR I attempted to import from the wrong `react-native-branch` library in the reflection so the module never got properly initialized. I've pushed out a fix to ExpoKit for SDK 33. If you install `expokit@33.0.4` then you'll receive the fix. Note, however, that in general our Branch support is experimental and untested at the moment, and we can't provide support for it beyond obvious bugfixes like this one.

**Comment by n-sviridenko** [comment]
@esamelson thanks for a quick fix! I'm testing the solution. In the meanwhile, why this version tagged as `next` and not as `current`?

**Comment by esamelson** [comment]
fixed! 🙂

**Comment by n-sviridenko** [comment]
@esamelson please check my comment in your commit, it seems like it's not yet fixed :(

**Pull request merged**
