### PR TITLE
[expo] Loosen version dependencies on unimodules packages

### PR DESCRIPTION
**Pull request by brentvatne**
# Why

The APIs are stable at this point and by loosening the deps a bit here we can reduce the odds of conflicting versions in a bare project.

# How

Change `~` to `^` in package.json. Not sure if this is sufficient to handle cases where we update this automatically with `et`.

### CODE REVIEW

**Review by ide — COMMENTED** [review]
I thought we used minor version numbers to signal a breaking change in the interface between Objective-C/Java and JS. That is, the JS from `@unimodules/core` 7.1.0 is not guaranteed to work with the Obj-C/Java from `@unimodules/core` 7.0.0.

If these dependencies have stabilized, wouldn't that be reflected in their minor versions being stable?

**Comment by brentvatne** [comment]
my understanding is that the js/native interface is stable, while the native API is something that is more likely to change. cc @tsapeta a penny for your thoughts

**Comment by ide** [comment]
I still don't understand the premise of this. If the JS-native interface is stable and there are non-breaking changes on solely either the JS or native side, that'd be a patch version bump and this PR would make no difference. We follow a more restrictive versioning scheme than semver.

When we break the JS-native interface, that's a minor version bump, and we don't want newer versions of the packages to get pulled in.

If we want to switch from our restrictive version of semver to regular semver (any breaking change = major version bump), we can do that but it would result in more major versions over time. Alternatively, every package with native code could be split into two packages: one with JS and one with native code and the major version number of the native code package would get bumped whenever its interface changes, but this would add a lot of peerDep-like coordination.

**Comment by tsapeta** [comment]
In my opinion, since `expo` package itself doesn't have any native code and uses `@unimodules/core` JS API that is not going to be changed (`NativeModulesProxy` and `Platform`) using `^` is good but only for this case. In other words, any non-breaking native change (patch or minor) can't break anything in `expo` package.
I agree that we should keep our restrictive semver.

**Comment by brentvatne** [comment]
@tsapeta @ide - the case i am concerned about here is when people eject and then install some newer version of react-native-unimodules, they'll need to use yarn resolutions to ensure they have only one copy of @unimodules/core and @unimodules/react-native-adapter in their project

**Comment by ide** [comment]
Yarn resolutions shouldn't be necessary -- if it is, it indicates that other dependencies need to be updated so that they all use the same semver range of `@unimodules/core` and `@unimodules/react-native-adapter`.

If the minor version of `@unimodules/core` or `@unimodules/react-native-adapter` has been bumped, that means there was a JS-native breaking change and it's unsafe for the app to have some dependencies that want one version of `@unimodules/core` and other dependencies that want another version. Or, it means someone on our team unnecessarily bumped the minor version in which case that's on us. But if we follow our convention correctly, it is not safe to treat `@unimodules/core` 7.0.0 and 7.1.0 as interchangeable.

**Pull request closed without merging**
