### PR TITLE
[expo] Upgrade vendored modules

### PR DESCRIPTION
**Pull request by sjchmiela**
# Why

In preparation for SDK 35.

# How

Went through the list of outdated vendored modules and:
- updated to latest: `react-native-{webview, appearance, safe-area-context, screens, reanimated, maps}`
- updated to not latest: `react-native-svg` (`9.8.[0,1]` still has some bugs)
- not updated: `react-native-{branch, gesture-handler, view-shot, netinfo}` due to required AndroidX upgrade; `lottie-react-native` due to required Swift integration

We will need to maintain our own fork of `react-native-webview` for one release cycle until we upgrade to AndroidX. We needed changes in v7 (removal of `UIWebView`) and v6 introduced AndroidX. I cloned upstream to `expo/react-native-webview` and reverted AndroidX change.

Due to this we have to decide whether to put `https://…/expo/react-native-webview` under `react-native-webview` to `bundledNativeDependencies` (will make sure that when people eject their Android projects will build, otherwise they will get the official release which won't work due to AndroidX support) or leave it as `~7.0.0` (and put somewhere the instructions for ExpoKit?)

# Test Plan

Projects build, went quickly through NCL, looked more or less ok.

### CODE REVIEW

**Comment by ide** [comment]
I think pointing to `https://…/expo/react-native-webview` is better. People who don't want this can use `7.0.0` from npm and patch it themselves, but to me, "making my app work" seems more important than "use the npm package".

**Review by ide — APPROVED** [review]

**Review by tsapeta — APPROVED** [review]

**Comment by brentvatne** [comment]
i think it's worth updating screens to 2.0.0-alpha1 that @kmagiera released today

**Comment by sjchmiela** [comment]
True, but doesn't v2 require RN0.60? According to the documentation it does and I don't know whether it's just for AndroidX or some more changes?

**Comment by brentvatne** [comment]
cc @kmagiera halp

**Comment by kmagiera** [comment]
I actually put 0.60 as required version but only thing that’s needed is androidx appcompat@1.1.0

**Comment by sjchmiela** [comment]
If so, I'll update it and just replace the AndroidX import with a Support one 🙂

**Comment by kmagiera** [comment]
This won't work as I am using features that are only added in androidX appcompat 1.1.0

**Comment by kmagiera** [comment]
latest support library (28) is only compatible with androidx 1.0.0

**Comment by sjchmiela** [comment]
Ok, thanks for clarifying! Then either we'll merge https://github.com/expo/expo/pull/5521 in and then update screens to latest or… not.

**Comment by kmagiera** [comment]
I'm using this thing for back button support which has been added to AppCompatActivity in 1.1.0 only: https://developer.android.com/reference/androidx/activity/OnBackPressedCallback

**Comment by esamelson** [comment]
would prefer to hold off on merging the big AndroidX PR for this release and hold off on updating RN screens if that's necessary. I'd rather not merge something that big this late in the process and increase our QA load.

**Pull request merged**
