### PR TITLE
[docs] Fix errors in API Documentation for Camera (Next)

### PR DESCRIPTION
**Pull request by Eli-code1**
# Why

I was trying to write code using the all new barcode scanner for iOS and ran into errors because the docs listed the wrong functions. I wanted to fix this through an update to prevent other people from having this issue.  

WARNING: this is my first pull request and I may well be doing it wrong. If I am, feel free to not accept it. But please help me update the docs somehow to fix the function names.

# How

I looked through the docs to figure out how they were configured, and updated the Next.js JSON appropriately.

# Test Plan

Not testable, simply docs update. Works in dev environment.

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Comment by amandeepmittal** [comment]
Hey @Eli-code1, the JSON file you updated (I'm assuming manually) is auto-generated when any API is updated from Expo SDK package. We list the steps here: https://github.com/expo/expo/blob/main/docs/README.md#update-api-reference-docs. Please go through it and you'll have to regenerate the JSON file as described in the steps.

Also, I apologize fo the inconvenience that you weren't able to find this info. We'll look into surfacing the link to update API docs more clearly. Let me know if you hit a roadblock.

**Comment by Eli-code1** [comment]
Hi @amandeepmittal,

I'm struggling to get expo tools installed to run on my computer (I can't seem to find the right command), so I can't build the updated docs. Would it be easier if I add the few docs issues as issues (instead of a PR if I can't make one for this repo) and we can go from there?

Thanks,

Eli

**Comment by Eli-code1** [comment]
After further review, it looks like the issue that I have with the docs is fixed in the repo, it just isn't fixed in SDK 50 (so probably will be released in the next SDK?). I can make do for now, I suppose 😔.

Thanks,

Eli

**Comment by amandeepmittal** [comment]
@Eli-code1, yeah can open docs related issues using the [documentation bug template](https://github.com/expo/expo/issues/new?assignees=&labels=docs&projects=&template=documentation.yml&title=%5Bdocs%5D+). 

Also, to understand better and get the context, what's was the issue that you referring to that has been fixed in the repo but not in SDK 50?

**Comment by Eli-code1** [comment]
@amandeepmittal The issue has to do with how the docs reference a function called `launchScanner`, but that function doesn't exist. Rather, it has been replaced by something called `launchModernScanner`. In the repo, it appears someone fixed this by changing the name back to `launchScanner`, but this wasn't the case in the version of the package I installed. Also, the type of data the `launchScanner` function accepts is a `ModernScanningOptions` object, not a `ScanningOptions` object as it says in the docs.

Not sure if it's worth submitting an issue for docs for this since I _think_ it's gonna be fixed in the next release. What do you think?

**Pull request closed without merging**
