### PR TITLE
[andorid][av] Add events to module definition

### LINKED ISSUE #26401: [Expo 50][Expo AV][Android] NativeEventEmitter called without add and remove listeners
### Minimal reproducible example

https://github.com/ajpaulingalls/bugRepro

### Summary

Using the latest builds of expo and expo-av and trying to play a sound on Android causes the following yellow box:

```
 WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `addListener` method.
 WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `removeListeners` method.
```
And the sound does not play.  In debugging the code, it appears in the EventEmitter constructor that, for expo-av, both `nativeModule.__expo_module_name__` && `NativeModules.EXReactNativeEventEmitter` are null, so the temp hack isn't executed, and eventually the native module is not created down in NativeEventEmitter.

### Environment

```  
expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.2.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 21.3.0 - /opt/homebrew/bin/node
      Yarn: 1.22.21 - /opt/homebrew/bin/yarn
      npm: 10.2.4 - /opt/homebrew/bin/npm
      Watchman: 2023.12.04.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.14.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
      Android SDK:
        Android NDK: 24.0.8215888
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11255304
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.0-preview.10 => 50.0.0-preview.10
      react: 18.2.0 => 18.2.0
      react-native: 0.73.2 => 0.73.2
    Expo Workflow: bare
```

### PR DESCRIPTION
**Pull request by alanjhughes**
# Why
Closes #26401
Events were not added to the module definition resulting in a warning.

# How
Added the event names

# Test Plan
test-suite. Warnings are removed

### CODE REVIEW

**Review by Kudo — APPROVED** [review]

**Comment by christophemenager** [comment]
@alanjhughes thanks a lot for the fix! Do you know when it will be released? (The issue is still reproduced with expo sdk 50 and expo-av 13.10.3.

**Comment by Haseebshah936** [comment]
@brentvatne The issue is not yet fixed I am still facing this issue in sdk 50.0.4.

**Comment by Haseebshah936** [comment]
Yup

**Comment by alanjhughes** [comment]
@Haseebshah936 - the latest release of expo go won't have this fix. You need a development client if you want to take advantage of the latest fixes.

**Comment by alanjhughes** [comment]
@Haseebshah936 - expo go doesn't get a new release for minor fixes. When a few accumulate, we release a new version. It's a sandbox environment, suitable for testing, and learning. For building an app, we recommend development clients.

**Comment by Haseebshah936** [comment]
@alanjhughes ok got thanks for clarifying it. I will test it. There is an other bug which I am facing in expo-av in audio playback when using "setOnAudioSampleReceived" which is causing the app to crash. This issue is only happening in IOS it cause the app to freeze and then crash. Should I create a separate issue for that?

**Comment by alanjhughes** [comment]
@Haseebshah936 - yes, please, open an issue and provide an example project demonstrating the problem and I can look in to it 👍

**Comment by Haseebshah936** [comment]
@alanjhughes Also is there any other way to get the audio waveform(audio DB) in expo-av. Right now I have to store the metering values which I get while recording the audio and store it along with the audio file. I want to make a dynamic audio player with audio waveforms like whatsapp.

**Comment by alanjhughes** [comment]
@Haseebshah936 this isn't the best place for questions, I recommend going into our discord server, lots of people in there will be able to help with you with development questions https://discord.com/invite/expo

**Pull request merged**
