### PR TITLE
[ENG-9026][docs] better eas update file names

### PR DESCRIPTION
**Pull request by quinlanj**
# Why

If an EAS Update doc has a verbose path, rename it to something equivalent, but shorter

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Comment by kbrandwijk** [comment]
This is going to break existing links and bookmarks. We should consider adding redirects (temporarily).

**Comment by quinlanj** [comment]
Updated the PR with the following changes:
- added redirects to all the renamed files
- renamed more files that were suboptimally named, but referenced elsewhere in our codebase

Will followup with the renames in the affected codebases as well.  If you feel this change will cause more headache/breakages than it's worth, please let me know. This is meant to be a small optimization.

**Review by kbrandwijk — APPROVED** [review]
My _functional_ concerns have been addressed with the redirects, and I like the improvement.

I'm leaving the technical review to Aman or Simek, because I remember vaguely there used to be 2 places where redirects were defined, and my knowledge is not up to date enough to be sure.

**Comment by quinlanj** [comment]
@amandeepmittal I've updated the PR so we track redirects in both `deploy.sh` (server side) and `error-utilities.ts` (client side)

**Review by amandeepmittal — APPROVED** [review]
Thank your for adding client side redirects as well 🙏

**Review by brentvatne — APPROVED** [review]
nice

**Pull request merged**
