### PR TITLE
[notifications][android] upgrade firebase messaging and replace "getInstanceId" call

### LINKED ISSUE #14860: [expo-notifications] getDevicePushTokenAsync incompatible with latest Firebase APIs
### Summary

`react-native-firebase` v12 (released May 2021) followed the latest changes upstream Firebase SDKs, which included the removal of Firebase Instance IDs.  See https://github.com/invertase/react-native-firebase/blob/master/CHANGELOG.md#breaking-changes and https://firebase.google.com/docs/projects/manage-installations#retrieving-an-identifier

Latest version of expo-notifications still seems to be using the now unsupported method of getting a token, see: https://github.com/expo/expo/blob/5a8b4ede46d96231a87da87dc924a037aa7be882/packages/expo-notifications/android/src/main/java/expo/modules/notifications/tokens/PushTokenModule.java#L64

This results in the error:

> Error: Encountered an exception while calling native method: Exception occurred while executing exported method getDevicePushTokenAsync on module ExpoPushTokenManager: Failed resolution of: Lcom/google/firebase/iid/FirebaseInstanceId;

**Workaround**: Downgrading to `react-native-firebase` v11 solves the issue.

I couldn't find anything in the docs talking about this incompatibility.  All I see is recommendations like *"You are free to use any native Firebase packages such as react-native-firebase in the bare workflow."* in https://docs.expo.dev/guides/setup-native-firebase/#bare-workflow-setup

Related issues: #14482

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

_No response_

### Environment

```
  Expo CLI 4.12.1 environment info:
    System:
      OS: Linux 5.14 Arch Linux
      Shell: 5.1.8 - /bin/bash
    Binaries:
      Node: 12.16.2 - ~/.nvm/versions/node/v12.16.2/bin/node
      Yarn: 1.22.4 - ~/.nvm/versions/node/v12.16.2/bin/yarn
      npm: 6.14.4 - ~/.nvm/versions/node/v12.16.2/bin/npm
    SDKs:
      Android SDK:
        API Levels: 28, 29, 30
        Build Tools: 28.0.3, 29.0.0, 29.0.2, 29.0.3, 30.0.2, 31.0.0
    npmPackages:
      expo: ^43.0.0 => 43.0.0 
      react: 17.0.2 => 17.0.2 
      react-native: 0.66.1 => 0.66.1 
    npmGlobalPackages:
      expo-cli: 4.12.1
    Expo Workflow: bare
```

### Reproducible demo or steps to reproduce from a blank project

- Create a bare React Native project.
- Follow Expo docs to add the Notifications module, including installing latest `react-native-firebase`.
- Make a call to `Notifications.getDevicePushTokenAsync()`

### PR DESCRIPTION
**Pull request by cruzach**
# Why

closes https://github.com/expo/expo/issues/14860

also users no longer need to manually add the firebase instance ID library if they are using a higher version of Firebase in their app (see https://forums.expo.dev/t/cant-get-expotoken-in-expo-notification-due-to-failed-resolution-of-lcom-google-firebase-iid-firebaseinstanceid/53265)

# How

https://firebase.google.com/docs/projects/manage-installations#retrieving-an-identifier

# Test Plan

Tested in a bare app, expo push token and device push token are the same as before the changes

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] This diff will work correctly for `expo build` (eg: updated `@expo/xdl`).
- [x] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Comment by dqii** [comment]
Is there any update on this?

**Comment by dqii** [comment]
Btw, if pushed this fix would only be available in the next Expo SDK update (45?), is that right?

**Comment by dqii** [comment]
Just wanted to check on this again

**Comment by Kudo** [comment]
since it's a major version bump for `firebase-messaging`, i would prefer to have it in new sdk. is it okay for you?

**Comment by dqii** [comment]
Of course it's your decision. Would it make it to SDK 45? I'm guessing that won't be released for one or two months?

Since this is completely breaking push notifications for us, we may switch to Firebase FCM. Would nonetheless love to see it as soon as possible for future projects.

**Comment by brentvatne** [comment]
@dqii - you could pull in this patch to your project with `patch-package`, that will likely be easier than switching tools. sdk 45 will be out in late april

**Comment by dqii** [comment]
Thanks for the super quick reply. I did not realize that was an option since this uses native code and I'm using the EAS flow. I use EAS Build; would I need to add the native code to my project and rebuild?

**Comment by AronBe** [comment]
@dqii you can use an expo config plugin in the meantime, just import it to plugins in app.json

```
// https://github.com/expo/expo/pull/15010
const expoConfigPlugins = require('@expo/config-plugins');

const firebaseIID = 'com.google.firebase:firebase-iid';
const iidVersion = '17.0.2';

function addDependency(buildGradle) {
  if (!buildGradle.includes(firebaseIID)) {
    // TODO: Find a more stable solution for this
    buildGradle = buildGradle.replace(
      /dependencies\s?{/,
      `dependencies {
        implementation '${firebaseIID}:${iidVersion}'`,
    );
  }
  return buildGradle;
}

/**
 * Update `app/build.gradle` by adding firebase-iid dependency
 */
module.exports = function withAndroidFirebaseId(config) {
  return expoConfigPlugins.withAppBuildGradle(config, (config) => {
    config.modResults.contents = addDependency(config.modResults.contents);
    return config;
  });
};
```

**Comment by dqii** [comment]
Thanks Aaron!

**Comment by Kudo** [comment]
as promising to have this fix on new sdk, i am going to work with this pr. basically based on Charlie's pr but updating to latest fcm version (`'com.google.firebase:firebase-messaging:23.0.2'`)

**Comment by Kudo** [comment]
oh no, i get to know why Charlie downgraded the version to v21. because there're other firebase sdks depending on `firebase-iid` and newer firebase-messaging internally has related classes. that would cause build error like
```
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class com.google.firebase.iid.FirebaseInstanceIdReceiver found in modules jetified-firebase-iid-20.0.2-runtime (com.google.firebase:firebase-iid:20.0.2) and jetified-firebase-messaging-23.0.2-runtime (com.google.firebase:firebase-messaging:23.0.2)
```

i'll stick on v21 ( 'com.google.firebase:firebase-messaging:21.1.0' ) anyway.

**Comment by Kudo** [comment]
i've confirmed the device token and push token not changed as well. the ci failures are not introduced by this change. i'll merge this anyway.

**Comment by dqii** [comment]
Will this be released with the next expo-notifications? Just wondering, is there an ETA on that?

**Comment by Kudo** [comment]
@dqii yes, this will be released in expo-notifications with the next expo sdk. we are targeting release it probably at early may.

**Comment by luklapp** [comment]
@Kudo Does this PR also fix [this issue](https://github.com/expo/expo/issues/15990) on iOS? The config plugin by @AronBe didn't fix it on iOS unfortunately.

**Pull request merged**
