### PR TITLE
[expo-server] Fix http server response to allow for multiple "Set-Cookie" headers

### LINKED ISSUE #26612: [Expo Router] Unable to set multiple cookies in response
### Minimal reproducible example

https://github.com/hdwatts/expo-recreation-playground

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

metro

### Summary

Expo Router API Routes do not properly return multiple `Set-Cookie` headers. Ideally, I can use the `headers.append` method to set multiple cookies in a single response.

### Reproduction Steps

I've also set up an express server to show how it should work. Run `npm run express-demo` to turn that on. It runs on port 8082.

Go to tab 1
image

Click Expo API Route and inspect the response in the network tab.
image

Click Express Route and inspect the response in the network tab
image

Both of these routes are very simple and use same logic:

**Expo**
```ts
export function GET(request: ExpoRequest) {
  const headers = new Headers();
  headers.set("Set-Cookie", "a=1;");
  headers.append("Set-Cookie", "b=2;");
  console.log("Headers setting", headers);
  return ExpoResponse.json(
    { hello: "world" },
    {
      headers,
    }
  );
}
```

**Express**
```js
app.get("/cookie", (req, res) => {
  res.setHeader("Set-Cookie", "a=1;");
  res.appendHeader("Set-Cookie", "b=2;");
  res.json({ hello: "world" });
});
```

I believe this stems from the usage of an older version of `remix`, as I see a few issues in their repo about this problem. Would it be non-trivial to upgrade to v2?

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.2.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.8.1 - ~/Library/Caches/fnm_multishells/4396_1705978127572/bin/node
      npm: 10.1.0 - ~/Library/Caches/fnm_multishells/4396_1705978127572/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9619390
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.2 => 50.0.2
      expo-router: ~3.4.3 => 3.4.4
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.73.2 => 0.73.2
      react-native-web: ~0.19.6 => 0.19.10
    npmGlobalPackages:
      eas-cli: 5.7.0
    Expo Workflow: managed

### PR DESCRIPTION
**Pull request by hdwatts**
# Why

Fixes #26612

# How

Set-Cookie is special, and should return multiple values. Currently, any API route attempting to return multiple values will collapse them into the last one.

It might be that the condition is unnecessary and we should always use `appendHeader`, but I wanted to keep this low impact (I'll note that the other vendor files all appear to use their append equivalent for all headers).

Note: This is my first contribution here, and I couldn't get the build commands to work properly so the changes are just to the .ts files. Any guidance here on getting the build files updated (if necessary) would be appreciated 🙇 

# Test Plan

```ts
import { ExpoRequest, ExpoResponse } from "expo-router/server";

export function GET(request: ExpoRequest) {
  const headers = new Headers();

  headers.set("set-cookie", "a=1");
  headers.append("set-cookie", "b=2");
  return ExpoResponse.json(
    { hello: "world" },
    {
      headers,
    }
  );
}
```
Try this route and investigate your cookies afterwards. 

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [x] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Review by EvanBacon — APPROVED** [review]

**Comment by EvanBacon** [comment]
You need to rebuild the build files and commit them to get the SDK check to pass. Would also be cool if you could do the same in the other adapters, specifically looks like the express adapter needs this change.

**Comment by hdwatts** [comment]
> You need to rebuild the build files and commit them to get the SDK check to pass. Would also be cool if you could do the same in the other adapters, specifically looks like the express adapter needs this change.

On it!

**Comment by hdwatts** [comment]
> Would also be cool if you could do the same in the other adapters, specifically looks like the express adapter needs this change.

I don't think that it is necessary for express actually. The express module uses `res.append`, which according to their docs should handle that automatically.

I think we should apply the same logic and always use `appendHeader` in the `http` adapter as well for consistency. I've updated the code to reflect.

image

image

**Comment by hdwatts** [comment]
@EvanBacon good morning, happy Monday! Anything else I can do to help get this merged?

**Comment by EvanBacon** [comment]
@hdwatts thanks for the great work on this!

**Pull request merged**
