### PR TITLE
[core][Android] Improve the initial loading speed of the native view

### LINKED ISSUE #21921: [expo-image] considerable slower than RN Image
### Minimal reproducible example

https://github.com/RRaideRR/expo-image-slow

### Summary

I have a view inside my app where I display GIFs. For Android, using the Image component from React Native is a lot faster rendering these media files. With expo-image, it will take (on my Android phone) around **5 seconds** before the screen comes into view (see attached video). 

Notes: 
- after successfully rendering the expo-image screen for the first time, the next opening of the screen is super fast. 
- its also super slow when displaying the same media files in webp format.

The github repro also contains a build of the sample app build-1680256008378.apk.

https://user-images.githubusercontent.com/3411292/229103707-bd0eb848-94c5-4843-919b-6962bb7c34e8.mp4

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.3
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
      Watchman: 2023.03.06.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.0 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9619390
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~48.0.9 => 48.0.9 
      react: 18.2.0 => 18.2.0 
      react-native: 0.71.4 => 0.71.4 
    npmGlobalPackages:
      eas-cli: 3.8.1
    Expo Workflow: bare
```

### PR DESCRIPTION
**Pull request by lukmccall**
# Why

Fixes https://github.com/expo/expo/issues/21921.

# How

The initial invocation of `declaredMemberProperties` appears to be slow, as Kotlin must deserialize metadata internally. This is a known issue that may be resolved by the new K2 compiler in the future. However, until then, we must find a way to address this problem. Therefore, we have decided to dispatch a lambda that invokes `declaredMemberProperties` during module creation.

# Test Plan

- https://github.com/RRaideRR/expo-image-slow

### CODE REVIEW

**Review by Kudo — APPROVED** [review]

**Review by tsapeta — APPROVED** [review]

**Comment by RRaideRR** [comment]
@tsapeta @Kudo  is there a rough estimate when this will be published? I'm feeling bad to ask and to be the one who is a little bit pushy here - sorry :-(

**Comment by tsapeta** [comment]
@RRaideRR We're sorry you've been waiting for it 🙇 We were a bit blocked with publishing new changes in `expo-modules-core` package, but I hope it'll get unblocked this week. I'll let you know once it's out!

**Comment by TMesdo** [comment]
Hi, i'm experiencing the same issue, any idea of when this will be fixed ?

**Comment by tsapeta** [comment]
I just published `expo@48.0.16`, may I ask someone to confirm that it works now?

**Comment by RRaideRR** [comment]
Unfortunately, it does not work if I didn't do something wrong here.

I see in my yarn.lock, that expo-modules-core 1.2.7 is used (which is the version that you just published).

The steps I did:
- `npx expo prebuild --clean --skip-dependency-update expo` (without the skip-dependency, it would fallback to expo 48.0.15).
- `eas build --platform android --local --profile preview`

I've updated my [reproducible example accordingly](https://github.com/RRaideRR/expo-image-slow). The result is the following behavior on my Android phone. RN Image still waaaay faster on the initial rendering of the view :'(. 

https://user-images.githubusercontent.com/3411292/235898010-3f25a282-6003-43e5-b141-7ef1785eecaa.mp4

**Comment by lukmccall** [comment]
@RRaideRR I'll check that today and will come back with more information.

**Comment by lukmccall** [comment]
Here is a link to my apk: https://drive.google.com/file/d/1P8HiRaD7QmGzZN65NARJf6sICGH1H0jj/view?usp=sharing

> Regarding the build link from my project: do you mean the eas build link? (I just built it locally, but I can do an eas build)

Ohh, I see. Sorry, I missed the local flag.

**Comment by RRaideRR** [comment]
Thanks for sharing that apk with me :-). Unfortunately, I cannot install it on my moto g8 power / Android 11.

I'll try it out tomorrow on other test devices.

Here, you have a link to my [eas build](https://expo.dev/accounts/raider/projects/expo-image-slow/builds/55ae3dc7-f6e7-4360-b2ea-a5316f4a5470) :-).

**Comment by tsapeta** [comment]
@RRaideRR I see in the "Run gradlew" step that this build used `expo-modules-core` version `1.2.6` 🤔

**Comment by RRaideRR** [comment]
> @RRaideRR I see in the "Run gradlew" step that this build used `expo-modules-core` version `1.2.6` 🤔

Yes you are right @tsapeta 🙏. I think I'm missing some knowledge about expo-modules-core and about the build process then. I do not have `expo-modules-core` as a dependency inside my package.json. I thought that it would be installed automatically when installing expo 48.0.16? My yarn.lock lists the 1.2.7 version as a dependency of expo@48.0.16.

I'm feeling like a noob but can you guide me how I can resolve this? 😬

**Comment by RRaideRR** [comment]
No need to answer me. I figured out that expo@48.0.15 got the right expo-modules-core dependency. I'll share my results tomorrow morning. On a first glance it appears a lot faster - however not as fast as RN Image.

**Comment by RRaideRR** [comment]
Sorry for the confusion that I caused and sorry for the extra work you both put into this 🙇. 

It's way faster now. I'd still say there is some perceivable lag on low-end / medium-end Android devices but for my use case that's alright :-).

https://user-images.githubusercontent.com/3411292/236131704-0ab51add-f793-40fb-8592-c47b510b8e1f.mp4

**Pull request merged**
