### PR TITLE
[sqlite] Fix iOS crash on int overflow

### LINKED ISSUE #25321: [sqlite] `expo-sqlite/next` crashes iOS app on int overflow
### Minimal reproducible example

https://github.com/peterferguson/sqlite-hook-test

### Summary

Trying to insert a timestamp into an integer field crashes iOS without any warning or error.

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.0
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.18.0 - ~/.nvm/versions/node/v16.18.0/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 9.8.1 - ~/.nvm/versions/node/v16.18.0/bin/npm
      Watchman: 2023.08.07.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.14.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10671973
      Xcode: 15.0.1/15A507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.0-alpha.6 => 50.0.0-alpha.6 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.5 => 0.72.5 
    npmGlobalPackages:
      eas-cli: 5.7.0
    Expo Workflow: bare

### PR DESCRIPTION
**Pull request by peterferguson**
Fixes #25321 by adding a guard in `bindStatementParam`

### CODE REVIEW

**Comment by Kudo** [comment]
thanks @peterferguson for the fix. we actually have a backlog to support BigInt and i think that's a better solution. let me clarify whether i can add BigInt support soon. otherwise i will merge the fix from you. does that sound good to you?

**Comment by peterferguson** [comment]
Perfect that is much better 👍

**Comment by Kudo** [comment]
hey @peterferguson! i just remembered that BigInt is still not supported on JSCRuntime. we may need more time to design a proper compatible API for BigInt. so we may better to resolve the crash first. at least to support support integer lower than `Number.MAX_SAFE_INTEGER`. considering iOS devices are nowadays all in 64 bits, i think we can just use int64. we also use Long to convert sqlite int64 on android. would you like to update the pr for this patch?

```diff
diff --git a/apps/test-suite/tests/SQLiteNext.ts b/apps/test-suite/tests/SQLiteNext.ts
index cfe0d3ae8c..18fc06337b 100644
--- a/apps/test-suite/tests/SQLiteNext.ts
+++ b/apps/test-suite/tests/SQLiteNext.ts
@@ -48,6 +48,18 @@ CREATE TABLE IF NOT EXISTS Users (user_id INTEGER PRIMARY KEY NOT NULL, name VAR
       await db.closeAsync();
     });
 
+    it('should support bigger integer than int32_t', async () => {
+      const db = await SQLite.openDatabaseAsync(':memory:');
+      const value = 1700007974511;
+      const row = await db.getAsync<{ value: number }>(`SELECT ${value} as value`);
+      expect(row['value']).toBe(value);
+      const row2 = await db.getAsync<{ value: number }>('SELECT $value as value', {
+        $value: value,
+      });
+      expect(row2['value']).toBe(value);
+      await db.closeAsync();
+    });
+
     it('should support PRAGMA statements', async () => {
       const db = await SQLite.openDatabaseAsync(':memory:');
       await db.execAsync(`
diff --git a/packages/expo-sqlite/ios/SQLiteModuleNext.swift b/packages/expo-sqlite/ios/SQLiteModuleNext.swift
index ea77177b10..ff43231acd 100644
--- a/packages/expo-sqlite/ios/SQLiteModuleNext.swift
+++ b/packages/expo-sqlite/ios/SQLiteModuleNext.swift
@@ -432,7 +432,7 @@ public final class SQLiteModuleNext: Module {
 
     switch type {
     case SQLITE_INTEGER:
-      return sqlite3_column_int(instance, index)
+      return sqlite3_column_int64(instance, index)
     case SQLITE_FLOAT:
       return sqlite3_column_double(instance, index)
     case SQLITE_TEXT:
@@ -460,8 +460,8 @@ public final class SQLiteModuleNext: Module {
       sqlite3_bind_null(instance, index)
     case _ as NSNull:
       sqlite3_bind_null(instance, index)
-    case let param as Int:
-      sqlite3_bind_int(instance, index, Int32(param))
+    case let param as Int64:
+      sqlite3_bind_int64(instance, index, Int64(param))
     case let param as Double:
       sqlite3_bind_double(instance, index, param)
     case let param as String:

```

**Comment by peterferguson** [comment]
@Kudo Just added the patch code and removed the other test I had written 👍

**Review by Kudo — APPROVED** [review]
thanks much @peterferguson for your help 🔥

**Pull request merged**
