### PR TITLE
feat(repo): add star gif to readme

### PR DESCRIPTION
**Pull request by EvanBacon**
# Why

Add a gif to the bottom of the readme which reminds users to star the repo with a lot of fanfare.

- Demo https://github.com/expo/expo/blob/@evanbacon/repo/readme-star-cta/README.md#license

### CODE REVIEW

**Comment by Simek** [comment]
I like the idea, but I don't like the quality of the gif (and especially preview still). 🤷‍♂️ Can try to achieve better with Kap on macOS or LICEcap on Win.

Screenshot 2022-08-16 225905

**Comment by brentvatne** [comment]
> I like the idea, but I don't like the quality of the gif (and especially preview still). 🤷‍♂️
> 
> Can try to achieve better quality with custom setting using Kap on macOS or LICEcap on Win tomorrow.
> 
> Screenshot 2022-08-16 225905

I quite like Gifski for this: https://apps.apple.com/ca/app/gifski/id1351639930?mt=12

**Comment by EvanBacon** [comment]
@Simek this was made with Kap filming this pen https://codepen.io/EvanBacon/full/BarGmqO feel free to retry if you'd like

**Comment by Simek** [comment]
t3

I think this looks better, but is it only me, or the labels are misaligned?

**Comment by Simek** [comment]
@EvanBacon Updated GIF below.

tloop2

**Review by Simek — APPROVED** [review]
LGTM! 👍 

Btw. I wasn't aware that you can overwrite the motion setting in your GH account, so the GIFs plays automatically again after latest accessibility changes. Happy to have autoplay back. 😉 

Screenshot 2022-08-18 170824

**Comment by bfelbo** [comment]
I really like this animation, hope it's alright if I use a variation of it for another open-source repo?

I'm thinking that I'd make a light theme version as well and show that to people [viewing the repo using light theme](https://stackoverflow.com/a/72333336/1452257) to make the animation blend with the background. If that's of interest to you, here's a media query that does that. You can just add it to your codepen, set your browser to light theme, and record.
```
@media (prefers-color-scheme: light) {
  body {
    background: #ffffff;
  }

  #main-content {
    background: #ffffff;
  }

  #text, .title {
    color: #333333;
  }

  #button {
    background-color: #f6f8fa;
    border-color: #d1d5da;
  }

  #button:active {
    background-color: #e1e4e8;
  }
}
```

**Pull request merged**
