### PR TITLE
[image-picker] Allow modal to be displayed in landscape orientation

### LINKED ISSUE #2020: ImagePicker orientation iOS (portrait only)
I'm experiencing some strange behavior with the ImagePicker only appearing in portrait orientation. My app is landscape only as set in app.json.

    {
        "expo": {
            "sdkVersion": "25.0.0",
            "orientation": "landscape",
            "platforms": [
                "ios"
            ],
            "privacy": "unlisted",
            "splash": {
                "image": "./assets/splashscreen.png"
            },
            "icon": "./assets/app_icon.png",
            "slug": "my-app",
            "name": "my-app"
        }
    }

I'm having this issue on SDK 25 on iOS iPad Air 2. When I started the project everything worked fine, but it seems since the "no-more-barcode-on-iOS"-update of the Expo client rolled out, this issue started to appear. I'm trying to open the ImagePicker modal in landscape, but its opening in portrait mode. The app itself stays landscape though. The ImagePicker modal even moves back down to bottom correctly.

    let result = await ImagePicker.launchImageLibraryAsync({
        mediaTypes: "Images",
        base64: true,
        quality: 1
    });

Heres a link to a screencast: https://youtu.be/LA_jKWh2tC4

Another thing I was wondering about is if it is possible to change the text of the "Cancel" label in the header of the ImagePicker.

### PR DESCRIPTION
**Pull request by lukmccall**
# Why

Resolve #2020.

# How

I've changed the` modal presentation style` for `ImagePicker` modal. Sadly, I'm not sure if it what we want. For some reason, we put there `UIModalPresentationOverFullScreen` earlier.

On iOS 13 `UIModalPresentationOverFullScreen` matches to app's orientation. However, on earlier systems, it forces portrait orientation. Also, I've done some research and checked what was used in `react-native-image-picker`. They used  `UIModalPresentationCurrentContext` (https://github.com/react-native-community/react-native-image-picker/blob/085d0b7d087f603bea530be2cb94cf3c1719f036/ios/ImagePickerManager.m#L185).

cc @tsapeta.
# Test Plan

- https://snack.expo.io/@lukaszkosmaty/github---image-picker---fix-landscape-orientation - now ImagePicker can be shown in landscape orientation.

### CODE REVIEW

**Comment by bbarthec** [comment]
Does your change affect behaviour on iOS prior version 13?

**Comment by lukmccall** [comment]
> Does your change affect behaviour on iOS prior version 13?

Yes, but only those applications which are using `landscape` orientation.

**Comment by tsapeta** [comment]
How does it work with the dev menu (the modal that we display when you shake the device)?
Also, take a look at the PR that changed it from `UIModalPresentationCurrentContext` to `UIModalPresentationOverFullScreen`: https://github.com/expo/universe/pull/2379

**Comment by lukmccall** [comment]
> How does it work with the dev menu (the modal that we display when you shake the device)?
> Also, take a look at the PR that changed it from `UIModalPresentationCurrentContext` to `UIModalPresentationOverFullScreen`: [expo/universe#2379](https://github.com/expo/universe/pull/2379)

Dev menu displays and works properly.

**Review by tsapeta — APPROVED** [review]

**Pull request merged**
