### PR TITLE
[android][image-picker] use correct MIME types in ImageLibraryContract when mediaTypes is ALL

### LINKED ISSUE #22602: [expo-image-picker] android app get crashed while selecting PDF file
### Minimal reproducible example

https://github.com/deepakOptimizeApp/Image-picker-issue.git

### Summary

[expo-image-picker] android app get crashed while selecting PDF file

If we are passing  `mediaTypes:ImagePicker.MediaTypeOptions.All,` in `launchImageLibraryAsync` then we are able to see the PDF files for selection in android and on selection of PDF file app is get crashed with no errors in callback.

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 19.3.0 - /opt/homebrew/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 9.2.0 - /opt/homebrew/bin/npm
      Watchman: 2022.12.12.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 14.3/14E222b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~48.0.15 => 48.0.17 
      react: 18.2.0 => 18.2.0 
      react-native: 0.71.8 => 0.71.8 
    npmGlobalPackages:
      expo-cli: 6.3.2
    Expo Workflow: managed

### PR DESCRIPTION
**Pull request by fobos531**
# Why

Fixes https://github.com/expo/expo/issues/22602

The problem with the current contract implementation is that if you passed "ALL" as the accepted media types, it would allow `*/*`, which means anything would work, including e.g. `.pdf`s. I think we can safely assume that we should only accept `image/*` and `video/*` in that case. 

# How

This PR makes use of `Intent.EXTRA_MIME_TYPES` to achieve this functionality. 

# Test Plan

Verified that I can no longer select `.pdf`s when MediaTypes is ALL

CleanShot 2023-05-22 at 21 00 36

Also ensured that the tests pass (not sure why the `launchCameraAsync` one failed - I assume it has something to do with the fact that I was testing in an emulator).
CleanShot 2023-05-22 at 21 01 45

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [X] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Review by Kudo — APPROVED** [review]
thanks for the fix @fobos531!
i'll still leave @lukmccall for the final review and merging.

**Comment by thespacemanatee** [comment]
We actually have an internal patch that does the exact same thing, however this does not prevent users from using third-party file explorers and not all of them respect this extra mimeType property, is there a fix for that? @lukmccall

**Comment by fobos531** [comment]
> We actually have an internal patch that does the exact same thing, however this does not prevent users from using third-party file explorers and not all of them respect this extra mimeType property, is there a fix for that? @lukmccall

Gotcha - I hope this PR will cover as many cases as possible, but in the example that you outline, in case there isn't an elegant solution, maybe we could perform additional checks in `parseResult` and throw an error if the picked file's MIME type doesn't fall under the ones covered my `input.options`

**Review by lukmccall — APPROVED** [review]
Looking good 🏅

> However this does not prevent users from using third-party file explorers and not all of them respect this extra mimeType property, is there a fix for that?

Unfortunately, we can't fix it. It all depends on the underlying implementation of those third-party file explorers. Some of them may have different properties that we could set. Although, it won't be possible to cover all cases.

**Comment by thespacemanatee** [comment]
> Looking good 🏅
> 
> > However this does not prevent users from using third-party file explorers and not all of them respect this extra mimeType property, is there a fix for that?
> 
> Unfortunately, we can't fix it. It all depends on the underlying implementation of those third-party file explorers. Some of them may have different properties that we could set. Although, it won't be possible to cover all cases. 

I think a good fix would be to introduce `Error` result as well, the library only supports `Canceled` and `Success` at the moment and uses `requireNotNull` in a few places and we have quite a few crashes on Sentry that could've been easily mitigated.

**Comment by flodev** [comment]
hi, when do you plan to release a new version containing this fix? thanks in advance

**Pull request merged**
