### PR TITLE
[video][ios] Fix unable to call presentFullScreenPlayer twice

### LINKED ISSUE #8239: [AV][Video][iOS] presentFullscreenPlayer only works once in iOS
### Environment

Expo CLI 3.17.23 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.1 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.13.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6308749
      Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~37.0.3 => 37.0.5 
      react: ~16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz => 0.61.4 
    npmGlobalPackages:
      expo-cli: 3.17.23

iOS, and android app targets

### Steps to Reproduce

Use Expo video player. Call `videoRef?.current?.presentFullscreenPlayer();`

Close the player by tapping the close icon with native controls. Now call presentFullscreenPlayer again. On iOS it throws "Fullscreen player is already being presented"

On android it works perfectly. It will let me tap a button to go to full screen, close it, tap it again. Here's the full code inside a component

```js
<Text
        onPress={async () => {
          await ScreenOrientation.lockAsync(
            ScreenOrientation.OrientationLock.LANDSCAPE_LEFT,
          );
          await videoRef?.current?.playAsync();
          videoRef?.current?.presentFullscreenPlayer();
        }}
      >
        Press for full screen and rotate
      </Text>
      <Video
        ref={videoRef}
        onFullscreenUpdate={async ({ fullscreenUpdate }) => {
          if (
            fullscreenUpdate === Video.FULLSCREEN_UPDATE_PLAYER_WILL_DISMISS
          ) {
            await ScreenOrientation.lockAsync(
              ScreenOrientation.OrientationLock.PORTRAIT_UP,
            );
          }
        }}
        source={{
          uri: data?.videoUrl as string,
        }}
        onLoad={() => setLoading(false)}
        rate={1.0}
        volume={1.0}
        isMuted={false}
        resizeMode="cover"
        useNativeControls
        shouldPlay={autoStart}
        style={{ width: '100%', height: 300, borderRadius: 8 }}
      />
```
### Expected Behavior

Allow me to call present fullscreen a second time after the user closes the video.

### Actual Behavior

Can only call the method one time, then it throws an error even when the video is no longer in full screen

### Reproducible Demo

https://snack.expo.io/@zachrebuild/eager-waffle

This runs on ios just fine, but has an issue running on the snack player. just open it inside the expo app on your phone.

Tap the text. it works. close full screen. tap again. video does not enter full screen mode.

### PR DESCRIPTION
**Pull request by IjzerenHein**
# Why

Calling `presentFullScreenPlayer` on the Video component for the second time, throws error "Fullscreen player is already being presented". This happens only when the `useNativeControls` prop is also set.

Fixes #8239

# How

When useNativeControls is set, it re-creates the PlayerViewController every time the full-screen view-controller is closed. This in turn caused the “videoBounds” key observer handler to be called which incorrectly assumed the regular ViewController was transitioning from full-screen to non full-screen. An additional check has been added to ensure this detection is not triggered when the full-screen viewcontroller is used.

# Test Plan

- Tested with NCL on expo-bare
- Tested with test-app code (see #8230) on Expo client

## Steps to reproduce

- Open NCL and go to "Components" -> "Video"
- Enable "Native controls"
- Press "Open fullscreen"
- Close video-player
- Press "Open fullscreen" again

## Before

May-18-2020 13-43-47

## After

May-18-2020 13-41-03

### CODE REVIEW

**Comment by IjzerenHein** [comment]
cc @FiberJW

**Comment by zackify** [comment]
Thanks for this! I found one other issue with audio. I can make a snack if you’d like. Just haven’t had the time. It’s explained here though: https://stackoverflow.com/a/60152015/1487687

If you try ignoring the silent switch. It does not work with the video player UNLESS you turn auto play on. Very weird!

P.S expo is awesome and I appreciate the quick turn around. 🙏🏻🙏🏻

**Comment by IjzerenHein** [comment]
> Thanks for this! I found one other issue with audio. I can make a snack if you’d like. Just haven’t had the time. It’s explained here though: https://stackoverflow.com/a/60152015/1487687
> 
> If you try ignoring the silent switch. It does not work with the video player UNLESS you turn auto play on. Very weird!
> 
> P.S expo is awesome and I appreciate the quick turn around. 🙏🏻🙏🏻

You're welcome :D

So please create a separate issue for the audio problem so we can keep the discussions on top 👍

**Review by mczernek — APPROVED** [review]
💯 🎉 💯

**Comment by IjzerenHein** [comment]
@lukmccall If I merge this, would it correctly generate the CHANGELOG and what would that changelog entry be?
Would it be possible to see a preview of the changelog entry before merging?

**Comment by lukmccall** [comment]
@IjzerenHein, unfortunately, the danger is still in the test phase :/ So, you need to add it manually.

You can see how it will look like [her](https://github.com/expo/expo/pull/8304). It won't add anything to your code without your confirmation. Firstly, the script will generate a message with information about all missing entries - https://github.com/expo/expo/pull/8304#issuecomment-628732653. Then, it will create a new branch with data from the body of your PR. Where you can correct messages, just by adding a suggestion to generated code - https://github.com/expo/expo/pull/8306#discussion_r425299451.

I think it will be available after the coming release. Cause, I'm still working on fixing some issues with permissions on CI.

**Review by bbarthec — APPROVED** [review]

**Comment by IjzerenHein** [comment]
@lukmccall No worries, looking forward to have this automated though 😃

**Pull request merged**
