### PR TITLE
[expo-gl-cpp] implement getInternalformatParameter

### PR DESCRIPTION
**Pull request by zenios**
# Why

Pixi 5.3  is using it

### CODE REVIEW

**Review by bbarthec — CHANGES_REQUESTED** [review]
Please add CHANGELOG entry for this package and elaborate more in this PR description. See https://github.com/expo/expo/blob/master/CONTRIBUTING.md.
I understand this method is used by `pixiJS@5.3.x` right and therefore it has to do the actual work right?

**Comment by zenios** [comment]
Hi

I am working on using pixi v5 and v6 and expo-gl. Expo's current implementation works only on pixi v4. The problem is that v5 and v6 is using that method which was unimplemented and the application was crashing

Hence the implementation

**Comment by bbarthec** [comment]
@zenios, I see the point of this RP and I understand your reasoning, but I'm asking you about adding CHANGELOG entry (this one is mandatory, before merge could happen), and possibly creating a better PR description (this one is optional at this point, because of our small conversation) 😉

**Comment by zenios** [comment]
> @zenios, I see the point of this RP and I understand your reasoning, but I'm asking you about adding CHANGELOG entry (this one is mandatory, before merge could happen), and possibly creating a better PR description (this one is optional at this point, because of our small conversation)

There is no CHANGELOG inside expo-gl-cpp. Shoud i create one / add the change to expo-gl instead or add it to master CHANGELOG?

**Review by tsapeta — COMMENTED** [review]
@zenios Thanks for the PR! Sorry for confusing in terms of the changelog — you're right, `expo-gl-cpp` doesn't have its own changelog, but changes made there should be noted in `expo-gl` changelog 😉 
I'll need to add a note about this in the readme or somewhere 😄

**Comment by zenios** [comment]
@tsapeta @bbarthec Done

**Review by tsapeta — APPROVED** [review]

**Pull request merged**
