### PR TITLE
[docs] Fix typo in Firebase Recaptcha example

### PR DESCRIPTION
**Pull request by abhisheksahdev**
FirebaseRecaptchaVerifierModal was written as FirebaseRecaptchaModalVerifier

# Why

# How

# Test Plan

### CODE REVIEW

**Comment by IjzerenHein** [comment]
Thank you for finding this!
Could you also make the same change to the SDK40 and SDK39 versions? Thanks a lot!

**Review by IjzerenHein — CHANGES_REQUESTED** [review]
Thank you for finding this!
Could you also make the same change to the SDK40 and SDK39 versions? Thanks a lot!

**Comment by Abhishek12345679** [comment]
@IjzerenHein I did not know how to do all the pull requests together, so i made the changes in seperate pull requests for SDKv39 and SDKv40.

here are the links.

1. [https://github.com/expo/expo/pull/11570](url)
2. [https://github.com/expo/expo/pull/11571](url)

**Comment by IjzerenHein** [comment]
Closing this as it has been fixed by 9c100235c96908961c8261e7a5f2ff1086df6587

**Pull request closed without merging**
