### PR TITLE
fix: replace AsyncStorage with community package

### PR DESCRIPTION
**Pull request by jaulz**
# Why

`AsyncStorage` is deprecated as you can see here: https://reactnative.dev/docs/asyncstorage

# How

All `AsyncStorage` occurrences should be replaced with: https://github.com/react-native-community/async-storage

For web support I think we need to wait for https://github.com/react-native-community/async-storage/pull/317 on the legacy branch.

# Test Plan

n/a

### CODE REVIEW

**Comment by jaulz** [comment]
I hope I found all the spots 😊

**Comment by tsapeta** [comment]
Hey @jaulz, thanks for this PR!
Unfortunately it's not enough that needs to be done in order to add support for any 3rd-party library. We also need to add its native code to our codebase so it gets versioned correctly for every SDK. I'll come back to this PR and merge it when the time comes 🙂

**Comment by superyarik** [comment]
looks like https://github.com/react-native-community/async-storage/pull/317 is merged

**Comment by sjchmiela** [comment]
Superseded by https://github.com/expo/expo/pull/8315.

**Pull request closed without merging**
