### PR TITLE
[image] Fix jest generate a long snapshot for the image component

### LINKED ISSUE #26087: [SDK 50] `expo-image` jest snapshot is 6000 lines long and may cause `RangeError: Invalid string length
### Minimal reproducible example

https://github.com/matthieugicquel/expo-sdk-50-issue

### Summary

When using expo SDK 50 (preview 7) with the associated package versions applied by `expo install --fix`, rendering an `<Image>` component from `expo-image` (v1.10.1) results in a 6000 lines long snapshot.

In real-world tests, it can cause  `pretty-format` reaching the max allowed string length in V8/node, and the test failing with  `RangeError: Invalid string length`.

**A test generating the 6000 lines snapshot:**
```jsx
render(<Image source={backgroundImage} />);

expect(screen).toMatchSnapshot();
```

[Here's a resulting snapshot example](https://github.com/matthieugicquel/expo-sdk-50-issue/blob/main/__snapshots__/App.test.js.snap). It's hard to read, but it looks like there's something circular/repeating in there.

*Package versions where it's reproduced (all are up-to-date):*

```
    "@testing-library/react-native": "^12.4.2",
    "expo": "~50.0.0-preview.7",
    "expo-image": "^1.10.1",
    "expo-status-bar": "~1.11.1",
    "jest": "^29.7.0",
    "jest-expo": "^50.0.1",
    "react": "18.2.0",
    "react-native": "0.73.1"
```

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.2
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 21.1.0 - ~/Library/Caches/fnm_multishells/68501_1703194778649/bin/node
      Yarn: 3.6.1 - /opt/homebrew/bin/yarn
      npm: 10.2.0 - ~/Library/Caches/fnm_multishells/68501_1703194778649/bin/npm
      Watchman: 2023.12.04.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /Users/matthieugicquel/.gem/ruby/3.1.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
      Android SDK:
        API Levels: 33, 33
        Build Tools: 30.0.3, 33.0.0, 33.0.2
        System Images: android-33-ext5 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10811636
      Xcode: 15.0/15A240d - /usr/bin/xcodebuild
    npmPackages:
      expo: next => 50.0.0-preview.7 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.73.1 => 0.73.1 
    Expo Workflow: bare
```

### PR DESCRIPTION
**Pull request by lukmccall**
# Why

Fixes jest generate a long snapshot for the image component.
Closes https://github.com/expo/expo/issues/26087. 

# How

The code uses the `JSON.stringify` function to serialize the react refs. However, most of them are removed from the snapshots by default because there is a logic that treats the `ref` prop differently. Unfortunately, this logic does not apply to our `nativeViewRef` prop, so it's serialized, resulting in a large snapshot. To change this default behavior, I added the `toJSON` function. Additionally, the logic was added to the `expo-modules-core` because we will need this in different packages too, such as `expo-video` or `expo-camera`.

# Test Plan

- run bare-expo ✅
- check if jest generates a smaller snapshot ✅

### CODE REVIEW

**Review by Kudo — APPROVED** [review]
looks good but i'm more lean toward to have these testing methods inside jest-expo.

**Comment by lukmccall** [comment]
> i'm more lean toward to have these testing methods inside jest-expo.

I understand your point, but I don't want to overwrite the global `React.createRef` method. Therefore, we would still have to use some generic method to create the reference when testing. I don't see many benefits in that approach. It would look very similar to the current solution but require more steps to set up.

**Comment by Kudo** [comment]
> I understand your point, but I don't want to overwrite the global React.createRef method.

sorry i didn't express my thoughts clearly. i was thinking to have the `createSnapshotFriendlyRef()` implementation for jest-expo

```ts
export function createSnapshotFriendlyRef<T>(): React.RefObject<T> {
  const ref = React.createRef<T>();
  Object.defineProperty(ref, 'toJSON', {
    value: () => '[React.ref]',
  });
  return ref;
}
```

and this is for standard code

```ts
export function createSnapshotFriendlyRef<T>(): React.RefObject<T> {
  return React.createRef<T>();
}
```

that's safer where we don't do any hack into React.createRef.

**Review by Kudo — APPROVED** [review]
thanks for the following up 💛

**Comment by Kudo** [comment]
the expo-modules-core's sdk ci was failed, please rebuild js files before merging

**Review by tsapeta — APPROVED** [review]

**Comment by stephenmatthews** [comment]
Hey @lukmccall, do you know when this will be released?

**Comment by MarcHbb** [comment]
Hello @lukmccall 
Is this fix already released ?

**Comment by lukmccall** [comment]
That fix was released. Should be available in the newest sdk

**Comment by MarcHbb** [comment]
Just updated to SDK 51. Problem fixed ✅

**Pull request merged**
