### PR TITLE
[expo-font][ios] fix crash when accessing dictionary from multiple threads

### LINKED ISSUE #31563: Font crash on ios after sdk 51 - Dictionary.subscript.getter (FontFamilyAliasManager.swift)
### Minimal reproducible example

unable

### What platform(s) does this occur on?

iOS

### Where did you reproduce the issue?

--

### Summary

Unable to reproduce on personal devices, but from Sentry reports (and other related font crash threads) a great deal of users are experiencing the same crash on ios devices after updating to sdk 51. Here are the relevant Sentry reports. 
We are using .ttf fonts, and tried loading them using loadAsync, useFonts and app config. The same error always remains. The trouble is that I was not able to reproduce the issue on my iPhone 11, even though there are iPhone 11s among the crash reports.

Please don't close the thread, I was asked by @lukmccall to create a new thread to make it easier to keep track.

image
image

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 20.11.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD  
      npm: 8.18.0 - C:\Program Files\nodejs\npm.CMD   
    IDEs:
      Android Studio: AI-223.8836.35.2231.10406996    
    npmPackages:
      expo: ~51.0.31 => 51.0.32 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.5 => 0.74.5 
    Expo Workflow: managed

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check if the project meets version requirements for submission to app stores
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

### LINKED ISSUE #33552: crash when excluding expo-font module
### Minimal reproducible example

n/a

### What platform(s) does this occur on?

Android, iOS

### Where did you reproduce the issue?

in a standalone app

### Summary

In our bare app, we're seeing crashes in production environment from expo-font noted in https://github.com/expo/expo/issues/31563

we're attempted exclude expo-font from the project as we dont use it.

we've added to package.json
```
"expo": {
    "autolinking": {
      "exclude": [
        "expo-font",
        "expo-keep-awake"
      ]
    }
  },
  ```

this does exclude expo-font from the build but the app crashes at runtime in release mode.

It seems its still attempting to load expo-font

```
*** Terminating app due to uncaught exception 'RCTFatalException: Unhandled JS Exception: Error: Cannot find native module 'ExpoFontLoader', js engine: hermes', reason: 'Unhandled JS Exception: Error: Cannot find native module 'ExpoFontLoader', js engine: hermes, stack:
requireNativeModule@202056:21
anonymous@292586:86
loadModuleImplementation@157:13
guardedLoadModule@96:37
metroRequire@38:91
anonymous@292358:54
loadModuleImplementation@157:13
guardedLoadModule@96:37
metroRequire@38:91
anonymous@292268:21
loadModuleImplementation@157:13
guardedLoadModule@96:37
metroRequire@38:91
anonymous@292168:44
loadModuleImplementation@157:13
guardedLoadModule@96:37
metroRequire@38:91
anonymous@292139:53
loadModuleImplementation@157:13
guardedLoadModule@96:37
```

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 15.0.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.19.1 - /opt/homebrew/opt/node@18/bin/node
      Yarn: 3.6.4 - /opt/homebrew/opt/node@18/bin/yarn
      npm: 10.2.4 - /opt/homebrew/opt/node@18/bin/npm
      Watchman: 2024.01.22.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /Users/phil/.rbenv/versions/2.7.4/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.0, iOS 18.0, macOS 15.0, tvOS 18.0, visionOS 2.0, watchOS 11.0
      Android SDK:
        API Levels: 28, 29, 30, 31, 32, 33, 34
        Build Tools: 28.0.3, 30.0.2, 30.0.3, 31.0.0, 33.0.0, 33.0.1, 34.0.0, 35.0.0
        System Images: android-33 | ARM 64 v8a, android-33 | Google APIs ARM 64 v8a, android-33 | Google Play ARM 64 v8a, android-34 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2024.2 AI-242.21829.142.2421.12409432
      Xcode: 16.0/16A242d - /usr/bin/xcodebuild
    npmPackages:
      expo: ^51.0.0 => 51.0.39 
      react: 18.3.1 => 18.3.1 
      react-dom: 18.3.1 => 18.3.1 
      react-native: 0.75.4 => 0.75.4 
    npmGlobalPackages:
      eas-cli: 3.17.1
      expo-cli: 6.3.10
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

```text
✖ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check for common project setup issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for issues with Metro config
✖ Check for app config fields that may not be synced in a non-CNG project
✔ Check if the project meets version requirements for submission to app stores
✔ Check npm/ yarn versions
✖ Check Expo config (app.json/ app.config.js) schema
✔ Check native tooling versions
✖ Check that packages match versions required by installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK
```

### PR DESCRIPTION
**Pull request by chrfalch**
# Why

We've received a Sentry crash that was evident for a lot of the client's users.

It wasn't reproducible in development builds, so I started looking around. The crash report crashed in Dictionary.subscript.getter in swift - which made me think about concurrent access to the dictionary.

Closes #31563
Closes #33552 

# How

The fix here protects accessing the `fontFamilyAliases` member by using a DispatchQueue.

# Test Plan

Follow Sentry reports

# Checklist

- [X] I added a `changelog.md` entry and rebuilt the package sources according to [this short guide](https://github.com/expo/expo/blob/main/CONTRIBUTING.md#-before-submitting)
- [X] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Review by tsapeta — COMMENTED** [review]
I think the best and fastest solution here would be to check on which threads the swizzled `_expo_fontNames` is called, and if this is always one thread (I assume it's always main thread/queue), running the exported `loadAsync` method on the same thread would solve the issue without unnecessary blocking jumps between queues.

Creating too many dispatch queues is generally not good, especially for private concurrent queues which may waste thread resources, according to [the docs](https://developer.apple.com/documentation/dispatch/dispatchqueue):

> Another way that apps consume too many threads is by creating too many private concurrent dispatch queues. Because each dispatch queue consumes thread resources, creating additional concurrent dispatch queues exacerbates the thread consumption problem. Instead of creating private concurrent queues, submit tasks to one of the global concurrent dispatch queues.

Also, you're always scheduling that code synchronously, so effectively the queue is not concurrent if my assumption is right that the font names are always read on the same thread.

**Comment by chrfalch** [comment]
> I think the best and fastest solution here would be to check on which threads the swizzled `_expo_fontNames` is called, and if this is always one thread (I assume it's always main thread/queue), running the exported `loadAsync` method on the same thread would solve the issue without unnecessary blocking jumps between queues.

Good point, thanks. I checked this, and it is a combination of the JS thread and the `FontLoaderModule`'s async function queue. This is the same as I've seen with `expo-screen-orientation` and causes some nasty threading crashes that are hard to track down. 

In swift I think the suggestion solution to protect against threading issues like this is to use a serial dispatch queue - looks like other alternatives like Mutex (Swift 6) and locks (iOS 16+) doesn't fit our needs 100%.

**Review by alanjhughes — APPROVED** [review]

**Review by tsapeta — APPROVED** [review]
Ideal approach would be to use Swift Concurrency and actors, but we can't do this since the swizzled method must stay synchronous 😞

**Comment by chrfalch** [comment]
> Ideal approach would be to use Swift Concurrency and actors, but we can't do this since the swizzled method must stay synchronous 😞

**Comment by techied** [comment]
Hey, we applied this fix as a patch to our project but we're still seeing crashes on Dictionary.subscript.getter. Here is the stacktrace:

https://terros-tech.sentry.io/share/issue/5799b094a9ea4fd0b3ee72a2c8fc132c/

**Comment by techied** [comment]
I believe there is still a possible race condition when we write to the dictionary (`setAlias`). I think a barrier would fix this?

**Comment by fkrein1** [comment]
@chrfalch Thanks so much, this fixed it for me!
I was at about 99.5% crash-free sessions, and now I'm back to nearly 100% on iOS.

**Comment by chrfalch** [comment]
Congrats, @fkrein1 - that sounds awesome :) :)

**Comment by dev2xl** [comment]
Hi! Would it be possible to release a v12 version that includes this fix? I believe it would be really helpful for users who aren’t able to upgrade their iOS version yet. Thanks so much for your work!

**Pull request merged**
