### PR TITLE
[android][image] Add `defaultSource` prop to `ExpoImage` component

### PR DESCRIPTION
**Pull request by kkafar**
# Why

Extending functionality of ExpoImage component.

# How

* Added a react property following [this guideline](https://reactnative.dev/docs/native-components-android#3-expose-view-property-setters-using-reactprop-or-reactpropgroup-annotation)
* Made use of [`thumbnail`](https://bumptech.github.io/glide/javadocs/400/com/bumptech/glide/RequestBuilder.html#thumbnail-com.bumptech.glide.RequestBuilder-) method  to implement the property
* Also handle case when `defaultSource={null}` or undefined

# Test Plan

- https://github.com/kkafar/expo/pull/2

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.io and README.md).
- [x] This diff will work correctly for `expo build` (eg: updated `@expo/xdl`).

### CODE REVIEW

**Review by bbarthec — CHANGES_REQUESTED** [review]
It looks good to me 👍 
I need you to provide, either in this PR or separately an example screen in ncl that presents the behaviour of this property - use some large image asset to visualise the difference between loading small `defaultSource` image and the actual bigger `source` image 💪

**Comment by kkafar** [comment]
Added test's here:

* https://github.com/kkafar/expo/pull/2

@bbarthec

**Review by barthap — APPROVED** [review]
LGTM 👍 As I understand, we should wait with merging this, until the stacked PR gets merged.

**Review by bbarthec — APPROVED** [review]
LGTM 👍

**Pull request merged**
