### PR TITLE
[github] switch Updates E2E runner to macOS

### PR DESCRIPTION
**Pull request by Simek**
# Why

This is an attempt to improve the workflow stability.

# How

Change runner to macOS from Linux, which is recommended when using AVDs:
* https://github.com/ReactiveCircus/android-emulator-runner

# Test Plan

Run the CI.

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] This diff will work correctly for `expo build` (eg: updated `@expo/xdl`).
- [ ] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Comment by Simek** [comment]
Refs #17362

**Comment by esamelson** [comment]
As mentioned in Slack, the move to linux was intentional (https://github.com/expo/expo/pull/16862) and would rather only move back to macOS as a last resort. It does seem like the failure rate is significantly higher on API 31, wondering if there was a specific reason for upgrading beyond just staying up to date? I think it's possible that running an API 31 emulator is just more resource intensive for the linux runners right now.

**Comment by brentvatne** [comment]
talking with @esamelson about this right now, we have a couple of thoughts for alternatives:

1. we could combine the ios and android updates e2e tests into one job that run on the macos runner, so we get the android tests running on a mac worker without making updates e2e test all consume 2 mac workers
2. we could roll back the android test to run on an older android api level, because it seemed like these tests ran pretty reliably before we updated to api level 31

ultimately, we need more workers, but until then we can use one of the above workarounds or something else.

i'm merging this in order to get CI more reliably green again but we can revert it depending on what you think about the above alternatives @tsapeta @Kudo

**Comment by Kudo** [comment]
i don't have strong opinion for this because updates e2e tests are fast (compared to other ci jobs). as well as we have ios updates e2e tests now, it makes sense to merge them on a macos runner.

**Pull request merged**
