### PR TITLE
[guides] Add guide on release branches and cherry-picking commits

### PR DESCRIPTION
**Pull request by ide**
This is a guide on how we structure our release branches, perform releases from them, and how to commit bug-fixes and where those commits belong.

### CODE REVIEW

**Comment by ide** [comment]
@tsapeta @sjchmiela you should see this too.

**Review by sjchmiela — APPROVED** [review]
Sounds great, thanks for writing that up, this should clarify any leftover misunderstandings! 🥇

**Comment by sjchmiela** [comment]
Two things that we could also add to this document would be:
- how to do version changes — where to commit them? Previously we would do them on the release branch and then cherry-pick/merge the release branch to master. From now on, if I understand correctly, we could either
  - commit them on `master`, then cherry-pick to `sdk-XX` and release from there — _feels icky?_
  - commit on `sdk-XX` and not cherry-pick to `master`, resulting in `master` version being some static big number (like [`1000.0.0` in `react-native`](https://github.com/facebook/react-native/blob/fa6add7d4bc68467862385f153915e4b4b713f83/package.json#L3))  — _if we would release only one package from our repo this wouldn't be that big of a problem, but since we release more than 80 NPM packages — we would need to implement some script that would automatically pick the version to set for each of these packages on the release branch (the `1000.0.0` ➡️ `6.0.0` change). For SDK34 some packages were on `1`, some on `2`, some on `6`, some on `34`…_
- how to handle prerelease publishes, when we want to publish a next-SDK unimodule from `master`, like in https://github.com/expo/expo/commit/a6224bf8f8fb814e63ee51715712b0ebae4692e0
  - should we publish from `master` and change the `1000.0.0` to `7.0.0-rc.0` and leave it as it would be — _when would the version go back to `100.0.0`? never?_
  - should we publish from `master` and not commit the `7.0.0-rc.0` change — _if another RC would need to be published one would need to manually check what was the last RC version, manual labor_
  - should we create a new release branch then — _then when actually cutting a new branch we would need to merge `master` to it_

**Comment by ide** [comment]
@sjchmiela These are great questions -- Tomasz and I talked about versioning yesterday (it is complicated). I will add a proposal to this document.

**Comment by ide** [comment]
I added some guidance around version numbers here: https://github.com/expo/expo/commit/4e258a278e6e2f1ca570cd96bd37431bbb07f216. The guidance is somewhat hand-wavy because of the complexity, but I think this invariant is good (it's not 100% fool-proof but works in most scenarios):

> when we create the next release branch, all of the versions on the newest release branch must be equal to or greater than the greatest versions we've published.

**Review by esamelson — COMMENTED** [review]
this looks good and makes sense to me. One thing that isn't explicitly addressed in this doc is the complexity around when to actually cut the release branch. This is tricky because a fair amount of versioning and QA work needs to be done before shipping the release, but we also need all of this to land on master eventually. However, we don't want other PRs to be merged to master during this time (since they could affect QA or break things we've already tested). We've tried a number of different solutions for this in the past (candidate branches, merging release branches to master, etc) but the simplest seems to be to just do most of the versioning work on master and be careful about merging PRs to master before cutting the release branch. Just want to make sure this is the approach we want to take here.

**Comment by ide** [comment]
I'll add a note about slowing down commits to master when versioning is happening as a soft policy. We need to keep the team running though and able to commit to master / not causing issues if PRs are merged to master.

**Pull request merged**
