### PR TITLE
Image Picker was only checking videoExportPreset on the legacy picker

### PR DESCRIPTION
**Pull request by pedroaosuna**
# Why
Image picker takes way to long to return the videos when using PHPickerViewController 

# How
Image Picker was only checking videoExportPreset on the legacy picker, and it needed to set preferredAssetRepresentationMode to current on the PHPickerConfiguration when videoExportPreset is passthrough, otherwise loadFileRepresentation in ExpoImagePicker/MediaHandler.swift takes way too long

# Test Plan
Calling the image picker with the following configuration, select videos with different extensions and durations, and verify that it does indeed return almost immediately, compared to the current behavior that can take more than 5 seconds
```
      const result = await ImagePicker.launchImageLibraryAsync({
        allowsEditing: false,
        mediaTypes: ImagePicker.MediaTypeOptions.Videos,
        allowsMultipleSelection: false,
      });
```

# See also
Issues:
[#19463](https://github.com/expo/expo/issues/19463)

### CODE REVIEW

**Review by lukmccall — APPROVED** [review]
Thanks for your contribution.
Please add a entry to the changelog

**Comment by posuna-cameo** [comment]
> Thanks for your contribution. Please add a entry to the changelog

Added :)

**Comment by richliu9** [comment]
Hello, is there any update on this? Thank you!

**Review by lukmccall — APPROVED** [review]

**Comment by lukmccall** [comment]
Closed in favor of https://github.com/expo/expo/pull/22456.

**Pull request closed without merging**
