### PR TITLE
[camera] Fix scanning ean13 barcodes

### LINKED ISSUE #28671: expo-camera 15.0.4 does not return 'data' in BarcodeScanningResult
### Minimal reproducible example

https://github.com/jordandreassen/camera-test

### What platform(s) does this occur on?

iOS

### Did you reproduce this issue in a development build?

No (tested in Expo Go)

### Summary

barcodeScanningResult from CameraView does not return any 'data', just the barcode type, bounds etc.

<CameraView
          style={styles.camera}
          facing='back'
          onBarcodeScanned={(result) => {
            setShowScanner(false);
            console.log(result)
          }}
          barcodeScannerSettings={{
            barcodeTypes: ['ean13'],
          }}
        >
        </CameraView>
        
console.log outputs:
       
`       {"bounds": {"origin": {"x": 0.503399133682251, "y": 0.2688171863555908}, "size": {"height": 0.39584094285964966, "width": 0.12417763471603394}}, "cornerPoints": [{"x": 0.5033991402520154, "y": 0.6502986846868529}, {"x": 0.5957219076605399, "y": 0.664658125031103}, {"x": 0.6275767591372067, "y": 0.28813123145347164}, {"x": 0.5033991235769288, "y": 0.26881718620701023}], "target": 1299, "type": "org.gs1.EAN-13"}`
       
       
       
       

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.17.1 - /usr/local/bin/node
      npm: 9.6.7 - /usr/local/bin/npm
    IDEs:
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.0 => 51.0.0 
      expo-router: ~3.5.10 => 3.5.10 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.1 => 0.74.1 
      react-native-web: ~0.19.10 => 0.19.11 
    npmGlobalPackages:
      eas-cli: 7.6.2
    Expo Workflow: managed

### Expo Doctor Diagnostics

N/A

### PR DESCRIPTION
**Pull request by alanjhughes**
# Why
Closes #28671
Fixes a small regression from #28233 where `ean13` barcodes would not have the `data` value set. This was caused by the workaround needed to return correct values for `upc_a` barcodes.

# How
Set this value regardless.

# Test Plan
Bare-expo scanning `ean13` barcodes works as expected

### CODE REVIEW

**Review by lukmccall — APPROVED** [review]

**Comment by mantcz** [comment]
I am on:

```
   "expo": "~51.0.2",
    "expo-camera": "~15.0.5",
    "expo-constants": "~16.0.1",
    "expo-linking": "~6.3.1",
    "expo-router": "~3.5.11",
    "expo-status-bar": "~1.12.1",
    "react": "18.2.0",
    "react-native": "0.74.1",
    "react-native-paper": "^5.12.3",
    "react-native-safe-area-context": "4.10.1",
    "react-native-screens": "3.31.1",
    "react-native-vector-icons": "^10.1.0",
    "react-native-reanimated": "~3.10.1"
```

and still `data` comes as undefined. I check and this code change is included locally. I'll see if I can manage to get a example at some point.

**Comment by Cbridger-mywellabee** [comment]
I have the same issue, data is coming back undefined 
```
{
  "cornerPoints": [
    {
      "x": 0.40644187763180306,
      "y": 0.7351851802236653
    },
    {
      "x": 0.5922972066685155,
      "y": 0.7351851720996705
    },
    {
      "x": 0.5922971870388667,
      "y": 0.28611117197950797
    },
    {
      "x": 0.40644185800215427,
      "y": 0.2861111801035028
    }
  ],
  "type": "org.gs1.EAN-13",
  "target": 193,
  "bounds": {
    "origin": {
      "y": 0.28611117601394653,
      "x": 0.406441867351532
    },
    "size": {
      "height": 0.44907402992248535,
      "width": 0.18585532903671265
    }
  }
}
```

**Comment by andrconstruction** [comment]
the same

**Comment by ezoharSB** [comment]
Update: I ran this on iOS and Android and seems like the issue is **only on iOS**. What's strange is that it's happening only for type **"org.gs1.EAN-13"**. For android it reads as type **"32"** and goes through. The depreciated "BarCodeScanner" still works for iOS though.

**Comment by ezoharSB** [comment]
@alanjhughes Sorry to bug but any updates on this?

**Comment by alanjhughes** [comment]
@ezoharSB are you using expo go?

**Comment by ezoharSB** [comment]
> @ezoharSB are you using expo go?

Yea, I am

**Comment by ezoharSB** [comment]
@alanjhughes Wait sorry, no I'm using a dev build. I migrated off Expo Go a few months ago.

**Comment by alanjhughes** [comment]
@ezoharSB Can you provide a barcode that I can test with?

**Comment by andrconstruction** [comment]
cd18aceff0a26e91c10cbbd2edba31d317fb3267

**Comment by ezoharSB** [comment]
@alanjhughes sure thing: 
IMG_6590

**Comment by ezoharSB** [comment]
@alanjhughes Hey sorry to bug man, I'm sure you got a lot on your plate. Has there been any developments on this issue? Just need a status update so I can let my team know. I'd also be happy to open a direct channel between the two of us if that will streamline anything I can do to help.

**Comment by alanjhughes** [comment]
Hi @ezoharSB - I've tested against your provided barcode and the one @andrconstruction provided. In both cases it is working as expected. I'm using the latest version of expo-camera in a development build.

IMG_4907

IMG_4908

This is the result in JSON
```json
{
  "bounds": {
    "origin": {
      "x": 109.19202026724815,
      "y": 268.37358647584915
    },
    "size": {
      "height": 59.35727524757385,
      "width": 209.53583532571793
    }
  },
  "cornerPoints": [
    {
      "x": 111.34323525454619,
      "y": 268.3735913515204
    },
    {
      "x": 109.1920190259811,
      "y": 299.13749694250015
    },
    {
      "x": 314.57718637000437,
      "y": 327.73085475424296
    },
    {
      "x": 318.72785334314904,
      "y": 268.3735792647605
    }
  ],
  "data": "2050011464603",
  "target": 3209,
  "type": "org.gs1.EAN-13"
}
```

**Comment by ezoharSB** [comment]
@alanjhughes Hey I just came back around to this issue to see if I could make it work and it's rather stubborn. Is it possible to get a snack of your environment to see if I can work through bridging the gap in my app?

**Pull request merged**
