### PR TITLE
[docs] HIPAA compliance doc

### PR DESCRIPTION
**Pull request by ccheever**
# Why

People ask about HIPAA compliance and Expo all the time

# How

I took some text Cruzan wrote and I put it in a webpage

# Test Plan

I did markdown preview to the side in VSCode

### CODE REVIEW

**Comment by ccheever** [comment]
I think it might be worth having a whole section on regulatory compliance in the docs and then having a separate page for HIPAA, Privacy Shield,  GDPR, etc.

I think people will Google those things and it will give them more confidence if there is a whole URL dedicated to them, not just a section of a page labeled HIPAA.

Thoughts?

**Comment by cruzach** [comment]
Yeah individual pages sound better to me- whatever makes this info as easy to find as it can be

**Comment by ccheever** [comment]
OK. Let's move it to different pages.

**Comment by cruzach** [comment]
@ccheever created a new `Regulatory Compliance` section now, with a base page w/ a high level overview, which then links to the HIPAA, GDPR, and Privacy Shield pages

Screen Shot 2020-06-17 at 3 37 33 PM

lmk if that's what you had in mind

**Comment by ccheever** [comment]
Looks good!

**Pull request merged**
