### PR TITLE
Discussion: Note Web support for Picker component

### PR DESCRIPTION
**Pull request by tazsingh**
# Why

I went to implement the `Picker` component, expecting to have to write another `Picker.web.tsx` component for the Web platform. However, the `Picker` appears to work just fine on Web?

It renders a native `<select>` tag with proper `<option>` elements. It appears, to my naive eyes, to be accessible.

**I'm creating this PR for discussion purposes, if Web support was purposely omitted from the docs for some other reason?**

# How

I simply installed the `@react-native-picker/picker` package as instructed and ran it on Expo Web:

```sh
expo install @react-native-picker/picker
```

```tsx
import React, { FC } from 'react'
import { Picker } from '@react-native-picker/picker'

export const MyPickerComponent: FC = () => {
  return (
    <Picker
      selectedValue='TEST'
      onValueChange={console.log}
    >
      <Picker.Item label='Test' value='TEST' />
      <Picker.Item label='Option 2' value='OPTION_2' />
    </Picker>
  )
}
```

# Test Plan

One should be able to run the above snippets in a fresh Expo project. I can create one in a repo with this done if preferable, however, I'm hoping that this change should be small and straightforward enough to not require a repo that describes the behaviour?

Thanks again for the lovely tool! ❤️

### CODE REVIEW

**Comment by brentvatne** [comment]
it looks like our docs are just out of date on this. @EvanBacon worked on the web support for picker (https://github.com/react-native-picker/picker/pull/76 / https://github.com/react-native-picker/picker/pull/91 / https://github.com/react-native-picker/picker/pull/92 etc), but we didn't update our docs to reflect web support once it landed. care to open a pr? 🙏

**Comment by tazsingh** [comment]
@brentvatne Awesome, thanks for helping me identify that the Picker does in fact support the Web platform 🚀 Thanks @EvanBacon for saving me writing my own Web implementation 😄 

I've updated the `unversioned` docs too. Let me know if there are any other ways I can assist with this!

**Comment by Simek** [comment]
Hi @tazsingh, thank you for catching this, I would like to see this change merged in! 🙂 

Can you update the PR, for the last time, and include the change in the SDK 41 and 42 doc file too?

**Comment by Simek** [comment]
Thank you so much for catching this up and the contribution! 👍 

The changes has been incorporated into #14508 changeset, which make this PR no longer needed.

**Pull request closed without merging**
