### PR TITLE
[expo-audio][ios] lock screen controls

### PR DESCRIPTION
**Pull request by danieloi**
# Why

This adds notification center and lock screen controls for expo-audio.
Even though there are config plugins and custom dev clients that provide a solid workaround, the small extra setup might not be pleasant for hobbyists and first-time expo users.
# How

Took inspiration from https://github.com/doublesymmetry/SwiftAudioEx

# Test Plan

https://github.com/user-attachments/assets/bde4a5d3-067d-4c67-a180-94f43d601684

iOS only for now. Lock screen controls don't show up in simulators for some reason. Physical device required.
run the bare expo app and visit the audio section in the APIs screen and play one of the sample tracks there.

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Comment by ckhicks** [comment]
Would love to see this one go through. A more minimal alternative to RNTP would be so nice to keep within the Expo ecosystem. 🙏

**Comment by ckhicks** [comment]
I'm a bit lost on the errors that broke the tests [here](https://github.com/expo/expo/actions/runs/11220331941/job/31188264467?pr=31894#step:13:6730):
```
› Compiling BareExpo » AppDelegate.mm
› Linking   BareExpo » BareExpo
⚠️  ld: ignoring duplicate libraries: '-lc++'
❌  duplicate symbol '__ZN8facebook5react25RNCViewPagerComponentNameE' in
┌─ libReactCodegen.a[x86_64][60](ShadowNodes-319ea1b32d20565740cf11caede28989.o)
└─ libreact-native-pager-view.a[x86_64][14](RNCViewPagerShadowNode.o)

› Linking   BareExpo » BareExpo
⚠️  ld: ignoring duplicate libraries: '-lc++'
❌  duplicate symbol '__ZN8facebook5react25RNCViewPagerComponentNameE' in
┌─ libReactCodegen.a[arm64][60](ShadowNodes-319ea1b32d20565740cf11caede28989.o)
└─ libreact-native-pager-view.a[arm64][14](RNCViewPagerShadowNode.o)
```

Seems like it's a namespace issue? Does that lib come from somewhere external?

**Comment by ckhicks** [comment]
@alanjhughes or @behenate do you have any thoughts on this or is it something for @danieloi to weed out to get the bot to do another pass?

**Comment by albingroen** [comment]
Would really love this!

**Comment by eeston** [comment]
Keeping an eye on this...would be a really nice addition

**Comment by willashley23** [comment]
+ Would really love this

**Comment by yagudaev** [comment]
This would be a wonderful addition, especially with the new architecture.

The <audio /> tag in html gives you all that for free. I expected native to do the same AND give more control.

So I think expo should indeed strive to be closer to web on this and in general.

**Comment by syed-shoaib-ali** [comment]
Hi Devs!

when this will be merged?

**Comment by saraspaudel** [comment]
Subscribing

**Comment by samlaycock** [comment]
Comparing the failed CI step to other more recent builds in other PRs, those duplicate symbols are only warnings elsewhere (e.g. [here](https://github.com/expo/expo/actions/runs/12253607590/job/34182697137?pr=33558#step:13:5314)).

@danieloi There are conflicts somewhere. Might be worth catching the branch up and running that CI step again?

Thanks for working on this, very keen to see this in 🙏

**Comment by danieloi** [comment]
Last contribution I did had CI warnings I could ignore so I figured it wasn't an issue this time. 

Here's some code review from a non-maintainer I got in the discord if anyone's interested 

https://discord.com/channels/695411232856997968/1009056414028812299/1293517890234089524

**Comment by brentvatne** [comment]
this will be a useful feature but we can't accept the code in the state that it's in with this pr, it appears to be mostly generated by ai and otherwise copy+pasted from another repo.

**Comment by danieloi** [comment]
Would've appreciated a more specific review since putting this together wasn't trivial @brentvatne 

I don't write swift everyday so I did this as a learning exercise. Some direction on what to improve or alternate attack plan would've been appreciated.

The code 
- doesn't have unused variables, 
- doesn't have difficult to follow logic
- is additive and doesn't refactor large swaths of existing code and so is less likely to break things

What's a better MVP for this feature people have wanted for years than to use open source with a liberal license as a starting point? Bending it to the existing style was hard and I was hoping a review would give some direction. I had an mvp in mind and that's why I put iOS out first to get feedback before I invested any more time tackling android. 

AI-generated != low effort

I reviewed and understood every single character it spit out. 

Still love expo though this might discourage future PRs from me and others watching.

**Comment by alanjhughes** [comment]
@danieloi - We appreciate the contribution and are not trying to discourage further contributions but you must also look at it from our perspective. Accepting and merging this code means we are taking responsibility for it. It is up to the reviewer to determine if we feel comfortable doing that. As a baseline, the author must at least understand what they have written and be able to communicate why they have made the decisions they have made. You have expressed here and on discord that you have generated large portions of this code and copied others code in its entirety. 

> AI-generated != low effort

Maybe not but it also often incorrect and if you are inexperienced in the language it is generating, sometimes, it's difficult to see the issues. LLMs are useful but nowhere near a point where they could be trusted to implement a large feature like this. This feature is on our roadmap and will be implemented. For now, the priority is getting this library to stability.

I encourage you to continue your learning and your contributions are always welcome but for this case we are just not comfortable accepting it.

**Comment by ckhicks** [comment]
Can we expect to see this functionality on the Expo Audio roadmap, at the least? There's clearly community interest and other solutions like RNTP are feeling heavier and slower by the day. I think this sort of feature expansion would let developers remain within the Expo ecosystem and backfill the missing functionality common to media plugins.

**Comment by brentvatne** [comment]
@ckhicks - we are working on expo-audio but can't make any promises about timelines of specific features at the moment

**Comment by bhkangw** [comment]
Disappointing :'(

**Comment by tesgoexperience** [comment]
Any update on this at all? React native track player has become quite unreliable. Especially with the new architecture. The only other alternative seems to be to write native code and completely disregard what expo is made for. 

Given the lack of alternatives, we would really appreciate it if you could give us some information regarding this feature.  So that we can make a more informed decision. Is it in the works or  is there nothing even planned?

**Comment by tesgoexperience** [comment]
Here is a discussion to keep an eye on https://github.com/expo/expo/discussions/31809

**Comment by stuckj** [comment]
I found this rejected PR while looking for a way to make `expo-audio` play audio in the background on Android. It seems it's not in the current version, but the unpublished stuff on `main` looks like they're adding the ability. I made a patch-package patch against 1.0.14 (what we're currently using) that adds background playback for android as well as lock screen controls on both platforms. I was going to make a PR, but realized the existing work on `main` takes a bit of a different approach (controls per player whereas I have an `activePlayer` and global controls).

I did this because we needed this now. I didn't realize it wasn't there when switching from `react-native-track-player` during an SDK upgrade. We don't want to downgrade and it's broken in the live version so this addresses what's broken.

Feel free to use the patch if it's helpful.

NOTE: It's large since it patches the native code for both iOS/Android and TS code.

There are some new TS functions that are added to support changing the artwork in the media controls.

DISCLAIMER: You should look through the code (before or after patching) instead of blindly applying someone else's patch and pushing it. :-P This is working for us, however.

[expo-audio+1.0.14.patch](https://github.com/user-attachments/files/23972047/expo-audio%2B1.0.14.patch)

## Patch API

**Plugin Config:**
```ts
['expo-audio', { supportsBackgroundPlayback: true }]

New Functions:
- updateNotificationMetadataAsync({ title?, artist?, artworkUrl? }) - Sets lock screen / notification metadata
- stopBackgroundAudioAsync() - Stops foreground service and removes lock screen controls
- configureBackgroundAudio({ artworkUrlValidation? }) - Optional security config for artwork URL validation

**Pull request closed without merging**
