### PR TITLE
[android][ios] Upgrade react-native to 0.67.2 in Expo Go

### PR DESCRIPTION
**Pull request by Kudo**
# Why

upgrade for sdk 45

# How

## upgrade react native fork

code in https://github.com/expo/react-native/tree/sdk-45
basically cherry pick most necessary commits from sdk-44 branch but not these two:

1. https://github.com/expo/react-native/commit/125b36ac6d76e702bea4d7c41a8a402d68cdb1f1: because ExpoKit is already deprecated.
2. https://github.com/expo/react-native/commit/82d3ff5218cc576b5c7ea44c7adbf8b5aa5d985c: [use the official way to set metro server address](https://github.com/facebook/react-native/commit/e2b5b6504cb4dee8f2ec67f1d3a410801e1ca09a)

## migrate project setup

basically reference from: https://react-native-community.github.io/upgrade-helper/?from=0.64.2&to=0.67.2

## other build errors or launch errors

just to deal with these mess one by one.

# Test Plan

- [android] unversioned expo-go build + launch + load unversioned NCL
- [ios] unversioned expo-go build + launch + load unversioned NCL

# Review Tips

i have tried to have each commits to be meaningful. basically, to exclude the `et update-rn` commit, that would be easier enough to review this large pr.

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] This diff will work correctly for `expo build` (eg: updated `@expo/xdl`).
- [x] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Comment by Kudo** [comment]
oops! CI android unit test is broken. please let me set the pr back to draft state. please review after i fixed the broken ci jobs.

**Comment by Kudo** [comment]
getting ci jobs passed. i guess there're too many changed files, so github actions doesn't trigger some jobs. i've started some jobs manually.
- [ios client](https://github.com/expo/expo/runs/5296926676?check_suite_focus=true)
- [ios shell app](https://github.com/expo/expo/runs/5296930029?check_suite_focus=true)

please help to review this pr when you get a chance.

**Review by bbarthec — APPROVED** [review]
I've went through the commits and I guess everything looks fine.
I think that these changes are so exotic that nobody is really able to review it accurately 🤔 
As long as all the processes are working (CI, et commands, etc) I'm ok with the change 👍

**Review by tsapeta — APPROVED** [review]

**Comment by Kudo** [comment]
thanks @bbarthec and @tsapeta! yep, these mess changes are not easy to review. thanks for taking time to take a look. i am going to merge it and will take care if there's anything broken.

**Pull request merged**
