### PR TITLE
fix(AppLoading): call new SplashScreen methods instead of the deprecated

### PR DESCRIPTION
**Pull request by brunohkbx**
# Why
The component `AppLoading` was calling the deprecated methods of SplashScreen. Thus, giving warnings like this:
`SplashScreen.preventAutoHide() is deprecated in favour of SplashScreen.preventAutoHideAsync()`

# How
I changed to call the new methods.

# Test Plan
Check whether the component is giving warnings about deprecated calls.

### CODE REVIEW

**Comment by brunohkbx** [comment]
@tsapeta @ide Hey, how do I fix this step?

```
The following build files need to be rebuilt and committed:

build/launch/AppLoadingNativeWrapper.js
```

**Comment by barthap** [comment]
@brunohkbx You edited wrong file. You should edit files inside `packages/.../**src**` instead of `packages/.../build`, and run `yarn run build` to generate js inside `build`.
This is the file you should edit: https://github.com/expo/expo/blob/master/packages/expo/src/launch/AppLoadingNativeWrapper.tsx

**Comment by byCedric** [comment]
Hi @brunohkbx, thanks for your PR! Once Splash Screen is available in managed, we will merge a rewrite for AppLoading in a different module. This is most likely fixed for SDK 39, but it depends how fast we can make the new splash screen work in managed.

As @barthap mentioned, you should never edit the `build/` files directly, only the `src/` files. After that you can run `yarn build` to update the build files.

**Review by byCedric — CHANGES_REQUESTED** [review]
As @barthap mentioned, you should never edit the `build/` files directly, only the `src/` files. After that you can run `yarn build` to update the build files.

**Comment by brunohkbx** [comment]
Sorry! I didn't realize that it was in the `build` directory.
Done :+1: @byCedric

**Review by tsapeta — APPROVED** [review]
Looks good to me! 👍
However, as Cedric said, SplashScreen now has its own `expo-splash-screen` package and possibly SDK39 will be the first SDK where importing it from `expo` package will be deprecated. Anyway for at least one SDK we will need to provide backwards compatibility, so this PR still makes sense, thank you 🙂

**Comment by brunohkbx** [comment]
Hey @byCedric. Please take a look again when you have a chance. :smiley:

**Pull request closed without merging**
