### PR TITLE
chore(expo-module-scripts): bump config plugins to Node 14

### PR DESCRIPTION
**Pull request by EvanBacon**
# Why

- Node LTS is on 14 now.

# How

- Bumped the tsconfigs preset to 14.
- Ran `et cp --no-test --fix-lint --no-uniformity-check  -a` to rebuild packages.
- Will manually update changelogs

### CODE REVIEW

**Review by tsapeta — COMMENTED** [review]
I'm kinda against marking this change as a breaking change and in general the impact of changes in config plugins on the package version.
From the user perspective, there is no change in the API of the package and these packages are intended to be used on mobile devices and not in Node. Users don't run this code directly, so it should be the Expo CLI that enforces the Node version, not the individual package. On EAS we're good since it uses Node 16 by default now.

If the config plugin of `X` was a separate package, would you bump major version of `X` when the new version of the plugin is out?

Another thing I don't like here is that we've just published packages for SDK46 (some of them involving breaking changes and so major bumps) and now, after a few days, we would have to bump them again. If we really need to do breaking changes, it's always better to batch them and release at once. Personally, I don't trust packages that release major versions that often.
cc @brentvatne

**Review by ide — APPROVED** [review]
Approving but we may want to support Active LTS instead of Maintenance LTS. Node 18 Maintenance LTS runs until April 2025 and Node 22 will probably be out by then.

**Comment by brentvatne** [comment]
this seems fine to me. i'm not super concerned about bundling this in the release but i understand @tsapeta's concern given that we did already do a major version bump in some places. @EvanBacon maybe we can merge this to main after we cut the sdk-46 branch?

**Review by brentvatne — APPROVED** [review]
let's ship this now that sdk 46 is wrapped up

**Pull request merged**
