### PR TITLE
[updates] always setup UpdatesController

### PR DESCRIPTION
**Pull request by Kudo**
# Why

since we have the disabled updates controller now, to reduce various edge cases, just initialize updates controller to prevent accessing `UpdatesController.instance`.
following up the [thread](https://exponent-internal.slack.com/archives/C1QP38NQ5/p1711977484549519?thread_ts=1711877071.025899&cid=C1QP38NQ5)

# How

- remove the support for configurable auto setup
- always call UpdatesController.initialize
- refactoring expo-updates-interface on android and introduce the `UpdatesControllerRegistry` like we did on ios. so that expo-dev-launcher doesn't have direct dependency to expo-updates and prevents calling its `initializeAsDevLauncherWithoutStarting()`. the initialization for UpdatesController is now all lived inside expo-updates. 
- the updates controller type is now more deterministic

| build settings                        | controller type        |
| ------------------------------------- | ---------------------- |
| release build                         | Enabled Controller     |
| release build with invalid config     | Disabled Controller    |
| debug build + EX_UPDATES_NATIVE_DEBUG | Enabled Controller     |
| debug build + expo-dev-client         | DevLauncher Controller |
| debug build                           | Disabled Controller    |

# Test Plan

- ci passed
- test bare-expo debug build on android (originally it had crash that #27993 trying to resolve)

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [x] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Review by lukmccall — APPROVED** [review]

**Review by gabrieldonadel — APPROVED** [review]

**Review by tsapeta — APPROVED** [review]

**Review by wschurman — APPROVED** [review]
This change is definitely the direction we want to go. Fewer independent conditional codepaths into the library reduces complexity.

A few questions:
- if there is an update, will it apply over the development bundle? Assuming no since we still return null for the bundle methods in the package in this case.
- how does this affect assets in development? When expo-updates is installed, it overrides expo-asset asset resolution: https://github.com/expo/expo/blob/main/packages/expo-asset/src/PlatformUtils.ts

**Review by douglowder — APPROVED** [review]

**Comment by Kudo** [comment]
trying to refactor more and the controller is now more deterministic

| build settings                        | controller type        |
| ------------------------------------- | ---------------------- |
| release build                         | Enabled Controller     |
| release build with invalid config     | Disabled Controller    |
| debug build + EX_UPDATES_NATIVE_DEBUG | Enabled Controller     |
| debug build + expo-dev-client         | DevLauncher Controller |
| debug build                           | Disabled Controller    |

**Comment by Kudo** [comment]
back to the original question

> if there is an update, will it apply over the development bundle? Assuming no since we still return null for the bundle methods in the package in this case.

correct, it's a no. we would only override the loading bundle URL when using EnabledUpdatesController (which [`isActiveController is true`](https://github.com/expo/expo/blob/a059426a0c8de62d13a2bc3202f33b73ecdc2b47/packages/expo-updates/android/src/main/java/expo/modules/updates/IUpdatesController.kt#L51-L55). 

> how does this affect assets in development? When expo-updates is installed, it overrides expo-asset asset resolution: https://github.com/expo/expo/blob/main/packages/expo-asset/src/PlatformUtils.ts

Now it depends. If it's a DisabledUpdatesController, then assets are not affected. for DevLauncherUpdatesController and EnabledUpdatesController, assets would be affected.

**Comment by Kudo** [comment]
@wschurman when you get a chance, please help to review once again since it has some major changes from last review.

**Review by douglowder — APPROVED** [review]

**Review by wschurman — APPROVED** [review]

**Review by wschurman — CHANGES_REQUESTED** [review]
Actually I think this makes a pretty major change to how this behaves when the updates configuration `ENABLED` is set to false (or when theres an initialization error) and DisabledUpdatesController is set up. Previously, DisabledUpdatesController would load the embedded update and the package would still use that. Now it seems that it no longer does this?

I think it's okay, but last time I made this change there was pushback. I'll try to find the PR.

**Comment by wschurman** [comment]
Here it is: https://github.com/expo/expo/pull/24330. The relevant bit was:

> Clearer what it means to have a "disabled" state. Previously, disabled still ran a bunch of expo-updates code to simulate as if it were not installed, which was liable to be buggy. Now, the way to disable it is to actually remove it which means that the code that runs the bundle is again react native, which is I think what most users expect.

The proposal was to remove the "disabled" state altogether. This would mean that `getJSBundleFile` and `getBundleAssetName` would always delegate to the enabled controller (ish, the concepts were in development at the time). We instead decided that keeping the disabled state was preferable. What this meant was that we still wanted the disabled controller to load the embedded update and the UpdatesPackage to still defer to that controller for the bundle.

As far as I can tell, this PR now won't defer to that controller for the bundle. I think this is good. But we need to know exactly what that means and whether the disabled controller makes sense any more if it's sole purpose (setting the bundle to the embedded update) is no longer performed.

**Comment by Kudo** [comment]
thanks for sharing all these insights. generally speaking, i like the idea to show early errors and deprecate the enabled property. this makes the setup more predictable. for example, when i added expo-updates to bare-expo in #27195. i wasn't aware that updates was not enabled because bare-expo doesn't have a valid updates.url until #28022.

i checked #24330 and [ENG-9880](https://linear.app/expo/issue/ENG-9880/one-should-be-able-to-specify-enabledfalse-in-updates-configuration), these cover a lot feedback of why we should keep the disabled state and makes it as silent warnings than early errors. but i didn't see why a disabled controller should load embedded updates and go through `getJSBundleFile`/`getBundleAssetName`. could you elaborate more on this?

**Comment by wschurman** [comment]
So I think there are two questions:
1. Should we have the enabled setting at all?
2. Should we defer responsibility back to react native for bundle/assets when updates is disabled? It is currently disabled in a few cases:
    - enabled setting being false (if we choose to keep that setting)
    - as of this PR, when in development and not using dev client
    - there not being a URL or other misconfiguration (should it throw instead?)
    - there being an initialization error during setup like out of disk space

My feeling for (1) is that we should remove the setting so that it’s one less thing to worry about. Outside the scope of this PR though. But in order to do so we need to figure out what to do when configuration is invalid. Currently it prints a warning in logcat and then starts in disabled mode. Historically, we decided that we don’t want to crash when incorrectly configured, though I could be convinced that invalid configuration should crash.

For (2), it’s tough to know since it might be different depending on why it was started in disabled mode. Thinking out loud for the cases above:
- If enabled is false, I think we should defer to RN for bundle/assets (what this PR does)
- If in dev, we should defer to RN (what this PR does)
- If misconfigured, IMO it should crash, but assuming we don’t go that direction I think it should probably warn and then defer to RN, but this one I’m less certain about. I think it's fine to defer to RN (what this PR does)
- If there's an initialization error, I think deferring to RN is fine, but we’ll want to ensure error reporting code in DisabledUpdatesController/NoDatabaseLauncher still runs.

So I guess overall, deferring to RN is fine!

**Review by wschurman — APPROVED** [review]

**Comment by Kudo** [comment]
Thanks for clarifying the questions and making it clear.

>  Should we have the enabled setting at all?

My two cents is that as long as we need to support misconfiguration, it doesn't introduce extra maintenance effort. The enabled is just like a misconfiguration.

> If there's an initialization error, I think deferring to RN is fine, but we’ll want to ensure the error reporting code in DisabledUpdatesController/NoDatabaseLauncher still runs.

I didn't change the initialization error flow for DisabledUpdatesController. All the existing mechanisms should work as-is. We just defer the bundle/assets loading to RN.

> Crash, log, or throw config-plugin error when misconfiguration happens

There is some debate on this question. My general idea is to raise the problems as early as possible, i.e. build time problems. Since people feel that build time errors are too strong. How about showing a build time warning when misconfiguration happens? We could also check that at app.manifest generation time. Checking Expo.plist using shell script should be easy. Checking AndroidManifest.xml should be feasible from gradle plugin. If we would like to go for this direction, feel free to create a Linear task to me, i can help in the next SDK cycle.

**Comment by Kudo** [comment]
There is no direct action items for this PR. I am rebasing to fix conflicts and merge. If there's anything we should follow up, feel free to create a Linear task.

**Pull request merged**
