### PR TITLE
[constants][updates] Fix ios script phase error from zsh extendedglob

### LINKED ISSUE #16525: source-login-scripts.sh breaks with some zsh options
### Summary

if one has `zsh` configured with `setopt extendedglob`, the the following line fails to execute:
https://github.com/expo/expo/blob/main/packages/expo-module-scripts/templates/scripts/source-login-scripts.sh#L10

```
setopt extendedglob
current_shell=$(ps -cp "$$" -o comm="" | sed s/^-//)
> zsh: no matches found: s/^-//
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

_No response_

### Environment

  expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 12.2.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.19.0 - ~/.nvm/versions/node/v14.19.0/bin/node
      Yarn: 1.22.10 - ~/Workspace/mobile-app/node_modules/.bin/yarn
      npm: 6.14.16 - ~/.nvm/versions/node/v14.19.0/bin/npm
      Watchman: 2022.02.21.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /Users/dseelig/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
      Android SDK:
        API Levels: 28, 29, 30, 31, 32
        Build Tools: 28.0.3, 29.0.2, 31.0.0, 32.0.0, 32.0.0
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8193401
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: 44.0.6 => 44.0.6
      react: 17.0.2 => 17.0.2
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.67.2 => 0.67.2
      react-native-web: 0.17.0 => 0.17.0
    Expo Workflow: bare

### Reproducible demo

```
# running zsh
setopt extendedglob
current_shell=$(ps -cp "$$" -o comm="" | sed s/^-//)
# fails

unsetopt extendedglob
current_shell=$(ps -cp "$$" -o comm="" | sed 's/^-//')
# works

```

### LINKED ISSUE #17004: Shell detection breaks the build
### Summary

In `source-login-scripts.sh`:
https://github.com/expo/expo/blob/8c4ddbbcb9b2fdfe24d0dc34f3d6cc45718fe4ed/packages/expo-module-scripts/templates/scripts/source-login-scripts.sh#L10

That `sed s/^-//` command expects `extendedglob` to be disabled.
Otherwise, it causes the following error:

```
PhaseScriptExecution [CP-User]\ Generate\ app.config\ for\ prebuilt\ Constants.manifest ... (in target 'EXConstants' from project 'Pods')
```
image

In that situation, doing `unsetopt extendedglob` or commenting out that line proves that this is the origin of the crash.

Many `zsh` users have `setopt extendedglob` among their profile files, is it possible to replace that line by something that won't conflict with `extendedglob`?

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

_No response_

### Environment

expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 12.2.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
      npm: 8.5.5 - ~/Development/cameoapp/node_modules/.bin/npm
      Watchman: 2022.03.21.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /Users/sarahstauber/.rvm/gems/ruby-2.6.6/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7042882
      Xcode: 13.3/13E113 - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ~0.16.2 => 0.16.19
      babel-preset-expo: 9.0.2 => 9.0.2
      expo: ^44.0.0 => 44.0.6
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
      react-navigation: ^4.4.3 => 4.4.4
    Expo Workflow: bare

### Reproducible demo

1. In a `zsh` shell
2. Add `setopt extendedglob` before https://github.com/expo/expo/blob/8c4ddbbcb9b2fdfe24d0dc34f3d6cc45718fe4ed/packages/expo-module-scripts/templates/scripts/source-login-scripts.sh#L10
3. Build

### PR DESCRIPTION
**Pull request by Kudo**
# Why

fix #16525
fix #17004

# How

add single-quotes to the sed statement

# Test Plan

```
$ zsh

$ cat test.sh
unsetopt extendedglob
current_shell=$(ps -cp "$$" -o comm="" | sed s/^-//)
echo "test case1: $current_shell"

setopt extendedglob
current_shell=$(ps -cp "$$" -o comm="" | sed s/^-//)
echo "test case2: $current_shell"

setopt extendedglob
current_shell=$(ps -cp "$$" -o comm='' | sed 's/^-//')
echo "test case3: $current_shell"

$ source test.sh
test case1: zsh
test.sh:6: no matches found: s/^-//
test case2:
test case3: zsh
```

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] This diff will work correctly for `expo build` (eg: updated `@expo/xdl`).
- [x] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Review by ide — APPROVED** [review]
Approving but I recommend using single quotes when possible (like when $shell_expansion is not needed), especially in regex patterns because it is common to use backslashes for regex character classes like `\d` and `\w`.

**Comment by Kudo** [comment]
> Approving but I recommend using single quotes when possible (like when $shell_expansion is not needed), especially in regex patterns because it is common to use backslashes for regex character classes like `\d` and `\w`.

i used single quotes initially and changed to double quotes because of consistency with other code. does it make sense to you if i change another double quotes from the `comm=""` together? so that's the

`current_shell=$(ps -cp "$$" -o comm='' | sed 's/^-//')`

**Comment by ide** [comment]
Yes, it makes sense to change both places we unnecessarily use double quotes. That way when people see that one place uses double quotes and another place uses single quotes, they are less likely to wonder if we intentionally used different types of quotes.

**Comment by Kudo** [comment]
that's so true! i was the person wondering for the different types of quotes 😂 
the latest commit is updated to single quotes already. let's merge it. thanks for the great review.

**Pull request merged**
