### PR TITLE
[dev-menu] fix wrong js import after expo modules api migration

### LINKED ISSUE #23183: [SDK 49][dev-menu] Cannot read property 'addDevMenuCallbacks' of null
### Summary

Upgraded with `yarn add expo@^49.0.0-beta`, and ran `npx expo install --fix`, followed [React Native Upgrade helper](https://react-native-community.github.io/upgrade-helper/?from=0.71.11&to=0.72.0).

This line `ExpoDevMenu.registerDevMenuItems(devMenuItems)` fails with the following error:

simulator_screenshot_6422396B-E5C8-4F71-9E94-E17843651FA8

### Managed or bare workflow?

bare

### What platform(s) does this occur on?

Android, iOS

### Package versions

```json
{
  ...
  "expo": "^49.0.0-beta",
  "expo-dev-client": "~2.4.2",
  "expo-dev-menu": "~3.1.2",
  ...
}
```

### Environment

```
expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.15.0 - ~/.asdf/installs/nodejs/16.15.0/bin/node
      Yarn: 1.22.19 - ~/.asdf/installs/nodejs/16.15.0/bin/yarn
      npm: 8.5.5 - ~/.asdf/plugins/nodejs/shims/npm
      Watchman: 2023.04.17.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /Users/thespacemanatee/.asdf/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Xcode: 14.3/14E222b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^49.0.0-beta => 49.0.0-beta.0 
    npmGlobalPackages:
      eas-cli: 3.14.0
    Expo Workflow: bare
```

### Reproducible demo

```ts
const devMenuItems = [
  {
    name: '🖥️ Connection Config',
    callback: () =>
      navigate('DevMenuNavigator', {
        screen: 'ConnectionConfigScreen',
      }),
  },
]


registerDevMenuItems(devMenuItems)
```

### Stacktrace (if a crash is involved)

_No response_

### PR DESCRIPTION
**Pull request by Kudo**
# Why

since we've migrated expo-dev-menu to expo modules api. we should use the new way to get native module from js side.
fixes #23183
close ENG-9166

# How

use `requireNativeModule()` to get native module

# Test Plan

```sh
$ yarn create expo -t blank@sdk-49 sdk49
$ cd sdk49
$ npx expo install expo-dev-client
$ npx expo prebuild -i ios
# patch expo-dev-menu's code
```

add the code to App.js

```js
import { registerDevMenuItems } from "expo-dev-menu";

const devMenuItems = [
  {
    name: "My Custom Button",
    callback: () => console.log("Hello world!"),
  },
];

registerDevMenuItems(devMenuItems);
```

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [x] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Review by gabrieldonadel — APPROVED** [review]
LGTM

**Comment by matt-42** [comment]
Hi @Kudo 
This is breaking my app in release IOS build only:
```
*** Terminating app due to uncaught exception 'RCTFatalException: Unhandled JS Exception: Error: Cannot find native
 module 'ExpoDevMenu', js engine: hermes', reason: 'Unhandled JS Exception: Error: Cannot 
find native module 'ExpoDevMenu', js engine: hermes, stack:

requireNativeModule@52684:21
anonymous@52242:58
loadModuleImplementation@206:13
guardedLoadModule@137:37
metroRequire@64:91
anonymous@52189:55
loadModuleImplementation@206:13
guardedLoadModule@137:37
metroRequire@64:91
anonymous@905:51
loadModuleImplementation@206:13
guardedLoadModule@137:37
metroRequire@64:91
anonymous@877:13
loadModuleImplementation@206:13
guardedLoadModule@129:46
metroRequire@64:91
```

FYI, reverting the ExpoDevMenu.js fixed the issue.

**Comment by Kudo** [comment]
that sounds strange. did you have any code to import js code from `expo-dev-menu` ? if so, could you share how did you use the import code?

**Comment by matt-42** [comment]
I had ```import 'expo-dev-client';``` as first line of my `index.js`
I think I got it when I first ran expo create app last year.
I removed it and everything is fine now. Thanks!

**Comment by ahilles107** [comment]
I had this same issue, it took me a day to figure out what's wrong. 

Pasting my error message here so it's more searchable to others:

```Terminating app due to uncaught exception 'RCTFatalException: Unhandled JS Exception: Error: Cannot find native module 'ExpoDevMenu', js engine: hermes', reason: 'Unhandled JS Exception: Error: Cannot find native module 'ExpoDevMenu', js engine: hermes```

**Comment by bj97301** [comment]
@ahilles107 Me too. Had to revert back to 48

**Comment by ahilles107** [comment]
Revert is not needed. Simply remove ‘expo-dev-client’ import from the code.

**Comment by bj97301** [comment]
> Revert is not needed. Simply remove ‘expo-dev-client’ import from the code. 

Thank you for the advice 😊

From what code?  This repo?  If so, I'd rather not have to fork it n whatnot. If from my code, nothing is referencing it.

**Comment by ahilles107** [comment]
Yes, from your code. There may be an import of the package. At some point it was an requirement for dev client usage. Check your App.tsx or the index.js.

**Comment by thespacemanatee** [comment]
@ahilles107 it is still a required step in https://docs.expo.dev/bare/install-dev-builds-in-bare/. This should be fixed.

**Pull request merged**
