### PR TITLE
[WebBrowser] Add support for secondaryToolbarColor

### PR DESCRIPTION
**Pull request by jdanthinne**
# Why

I needed to be able to change the secondaryToolbarColor of Custom Tabs in the Android version.

# How

Just added a new property to pass to the native module.

### CODE REVIEW

**Review by tsapeta — COMMENTED** [review]
Hey @jdanthinne, congrats for your first contribution here! 👏 
Could you please also update documentation here https://github.com/expo/expo/blob/master/docs/pages/versions/unversioned/sdk/webbrowser.md and add changelog entry here https://github.com/expo/expo/blob/master/packages/expo-web-browser/CHANGELOG.md ? 🙏

**Review by mczernek — APPROVED** [review]
Thanks a lot for this contribution! Great work!

**Comment by mczernek** [comment]
Hey @jdanthinne! Could you please let us know what is your use case for this additional parameter? We decided to add it, because it does not break anything, but as far as we can tell it is intended to be used only in secondary toolbar, which we do not support currently.
Asking just out of curiosity ;) And to be able to add some test case for that.

**Comment by jdanthinne** [comment]
🥵I think you're right. I've been given the task to convert an older non-expo app that was using another dependency that was using this prop to change to color of the icons in the toolbar, but I see that it is not (yet) relevant here… sorry.

**Comment by mczernek** [comment]
No worries! It doesn't break anything in here and maybe it'll help someone :)

**Pull request merged**
