### PR TITLE
[camera] Support toggling `autoFocus` on and off

### LINKED ISSUE #26869: Camera focus stuck after initial focus on iOS
### Minimal reproducible example

https://github.com/yoanhg421/Expo-Camera-Error

### Summary

I have an app in production that was using SDK48, after upgrading to SDK 49 and 50 the Camera doesn't focus anymore.
I created a couple of different apps using the expo camera and they all have the same problem.

The camera opens and focuses but after a few seconds if you move the camera around it doesn't refocus.
I tried the camera/next, adding useCamera2Api, autoFocus, but nothing seems to work. The production app works fine but I need to make an update and this is breaking the current functionality.  

I tested on different computers as well, iPhone 12 and 15ProMax. Testing was done in Expo Go, local development app, eas build, and local build. I do most of my work on Windows so using react-native-vision-camera is not an option at the moment. 

Please help. 

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 21.6.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
      npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~50.0.5 => 50.0.5
      react: 18.2.0 => 18.2.0
      react-native: 0.73.2 => 0.73.2
    Expo Workflow: managed

### PR DESCRIPTION
**Pull request by alanjhughes**
# Why
Closes #26869
Adding support for setting the focus mode of the device.

# How
Added a prop to activate or disable auto focus. The default is `off`. Also removed `locked` from legacy camera and replaced it with `continuousAutoFocus` as the the original settings gave users no way to select it and would leave them with unfocused images. 
Regenerated the docs.

# Test Plan
bare-expo ✅ Moving the camera while the focus is locked so the image becomes unfocused, then toggling the option off to confirm the image is refocused.

### CODE REVIEW

**Review by lukmccall — APPROVED** [review]

**Comment by PMalaret** [comment]
Will this PR go to the SDK 50?

**Comment by seba9999** [comment]
I'm still experiencing blurry image with an iphone 14 pro and expo-camera@15.0.16 ... 

```

  const [autoFocus, setAutoFocus] = useState('on'); // I've tried "on" and "off" without any changes
  const [useModernScanner, setUseModernScanner] = useState(false); // To try modernScan on iOS but doesn't change anything !

<CameraView
      ref={cameraRef}
      style={ {
           height: '100%',
           width: '100%'
       }}
      facing="back"
      ratio="1:1"
      autofocus={autoFocus}
      barcodeScannerSettings={{
        barcodeTypes: ['qr'],
      }}
      onModernBarcodeScanned={isiOS && useModernScanner ? onScan : undefined}
      onBarcodeScanned={!isiOS || !useModernScanner ? onScan : undefined}
 />
```

**Comment by alanjhughes** [comment]
Auto focus should be off for the camera to refocus after moving. It works fine in my testing on an older device than that.

Regarding the modern scanner. It doesn't work for multiple reasons
1. There is no `onModernBarcodeScanned` prop on the view. It's a static function on the view `CameraView.onModernBarcodeScanned()`.
2. You are not calling `CameraView.launchScanner()`. This scanner is launched modally and not part of the existing preview.

**Comment by nidasarac** [comment]
"expo": "50.0.20", and "expo-camera": "~14.1.3",
autoFocus={"on"} works on android, but on iOS it only focuses and locks once and does not refocus as the camera moves? What is the solution for android and ios?

**Pull request merged**
