### PR TITLE
Gracefully handle font observer failure and extend timeout

### LINKED ISSUE #12382: Expo vector icons are not loading up and is producing "3000ms timeout exceeded" loops on Brave Browser
### Summary

Upon closer investigation, it has to do with node_module/fontfaceobserver not loading or failing to load from multiple requests resulting in Expo Vector Icons not showing up.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Web

### SDK Version (managed workflow only)

_No response_

### Environment

Expo CLI 4.3.2 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 12.18.3 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.1.0.0 AI-201.8743.12.41.6858069
    npmPackages:
      expo: ~40.0.0 => 40.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: ^0.64.0 => 0.64.0
      react-native-web: ^0.15.0 => 0.15.0
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

Refreshing the web browser will either Load the icon or produce an "Error: 3000ms timeout exceeded" loop with a bunch of requests from bundle.js.map. Most likely it will produce the error.

I think it is the same issue with [#5935](https://github.com/expo/expo/issues/5935). I am using Brave Browser in debugging.

all Expo Vector Icon would either show up or not at all.

### PR DESCRIPTION
**Pull request by bradjones1**
# Why

Fixes https://github.com/expo/expo/issues/12382

# How

The font observer can time out and throw an uncaught exception, as noted by many bug reporters. There are many cases (e.g., unsupported browsers) where the observer is early-returned, so catching an exception on web is a safe no-op.

# Test Plan

This is tough to write a new test for since this is mostly a product of network conditions; does this need new test coverage?

# Checklist

- `[N/A]` Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- `[N/A]` Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [x] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Review by EvanBacon — APPROVED** [review]

**Comment by SleeplessByte** [comment]
FYI this just hides the warning instead of fixing the underlying issue, although having 6 seconds helps, as explained here: https://github.com/expo/expo/issues/12382#issuecomment-829338711

**Comment by bradjones1** [comment]
@SleeplessByte I get where you're going with your note about "hiding the warning," however this functionality doesn't work in the majority of browsers in the wild and in those cases the Expo font loader simply early-returns. So catching and then ignoring an exception in any failure case is no different than running in an unsupported browser. See https://github.com/bradjones1/expo/blob/ba1bbc359756311b9231eb5d7809a93089cdd00c/packages/expo-font/src/ExpoFontLoader.web.ts#L88

This has the advantage of not throwing an uncaught exception that could needlessly crash the broader application.

**Comment by SleeplessByte** [comment]
The least I would expect is for this to be in the docs.

The problem I have with this implementation is that you've now taken away the only way for me to _detect_ that it has failed. I used it to then try to load the font via https://developer.mozilla.org/en-US/docs/Web/API/FontFace/load , which is supported by WebKit / Safari etc.

**Comment by bradjones1** [comment]
I'm not an expert on font loading specifically but I don't _think_ any additional action should be necessary as a backup?

Expo is an open source project and so contributors like myself are doing the best we can with the information we have, and I have also contributed quite a bit to the docs as well. I would suggest that if you think there's a need for a fallback (such as the one you describe) perhaps it could be contributed to make this more robust.

**Comment by SleeplessByte** [comment]
We disagree about a _detectable_ failure now no longer being detectable and an unsupported browser being the same thing. I personally feel that that should be mentioned in the docs. Not as an additional PR but as part of this one. Feel free to ignore it, and/or not agree.

I have been patch-packaging this specfic bug for the past two years, after doing the investigation on two earlier issues. The linked issues in the code that presumably are there because the font face observer doesn't work in those browsers are outdated, stale, or resolved. This PR _hides_ the problem even further instead of fixing it. That is my contribution. I am ok with that happening, it's not affecting me as I still patch-package this dependency :)

I currently have no interest in making another PR that may or may not be merged, with a long discussion that may or may not take place, when I am pumping over thousands of dollars a month to 650 industries, which I'll continue to do, in order to make use of and support the great service, but I do appreciate people like you taking the time and energy to contribute --

**Comment by bradjones1** [comment]
@SleeplessByte Fair enough and understandable... I think the issue here was mostly that the error during the `init` call isn't easily catchable because it's executed when the code is included, rather than explicitly called. But perhaps I'm misunderstanding something there.

**Comment by SleeplessByte** [comment]
The original issue (12382) was / is mostly about the font loader _failing_ (for various reasons, most likely just timeout). In these cases, generally, the font doesn't load at all.

The original issue regarding the API not being available in some browsers would make it _crash_ (so instead of a failed promise, it would throw), which is... also not great! Most of that has been resolved since, but alas, that's probably why the isSupportedCheck was added.

The errors don't happen when loading (importing) the code.

**Pull request merged**
