### PR TITLE
[camera] Fix maxDuration

### LINKED ISSUE #28746: [expo-camera][ANDROID] Cannot record video on new expo camera sdk 51 on Android
### Minimal reproducible example

https://github.com/timbabs1/example-exposdk51-camera-not-working-android.git

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

Yes

### Summary

After upgrading to Expo 51 SDK, cannot record video while using the new camera view module

Getting error recording video [Error: Video recording failed: Video recording Failed: Unknown error]

Reproducible in expo go and expo development client

I have linked a minimal reproducible example with this. Give camera permission, microphone permissions and tap 'Record Camera' which should reproduce the issue

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.17.0 - ~/.nvm/versions/node/v18.17.0/bin/node
      Yarn: 1.22.15 - /usr/local/bin/yarn
      npm: 9.6.7 - ~/.nvm/versions/node/v18.17.0/bin/npm
      Watchman: 2023.10.02.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.13.0 - /opt/homebrew/Cellar/cocoapods/1.13.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
      Android SDK:
        API Levels: 26, 30, 31, 33, 34
        Build Tools: 26.0.2, 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0, 33.0.0, 33.0.1, 34.0.0
        System Images: android-29 | Google Play ARM 64 v8a, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play ARM 64 v8a, android-31 | ARM 64 v8a
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.9971841
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.2 => 51.0.2 
      expo-router: ~3.5.11 => 3.5.11 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.1 => 0.74.1 
      react-native-web: ~0.19.10 => 0.19.11 
    npmGlobalPackages:
      eas-cli: 8.0.0
    Expo Workflow: managed

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

### PR DESCRIPTION
**Pull request by alanjhughes**
# Why
Closes #28746
`maxDuration` was not handled correctly on android.

# How
Resolve the picture correctly when the `maxDuration` or `maxFileSize` is reached

# Test Plan
bare-expo and in users repro ✅

### CODE REVIEW

**Review by lukmccall — APPROVED** [review]

**Review by amandeepmittal — APPROVED** [review]

**Comment by alanjhughes** [comment]
Sorry guys, fix wasn't correct for iOS. We need to accept the value in seconds. Updated the PR

**Review by lukmccall — APPROVED** [review]

**Comment by Dart-Sharma** [comment]
maxDuration is not fixed still

**Comment by alanjhughes** [comment]
@Dart-Sharma - please provide a minimal example that demonstrates the broken behaviour

**Comment by Dart-Sharma** [comment]
@alanjhughes -    
```
   const options = {
      maxDuration: 600,
    };
    try {
      const video = await camera.recordAsync(options);
      props.setImage(video);
      setIsRecording(false);
      camera.stopRecording();
      props.setModalVisible();
    } catch (e) {
      console.log(e);
    } 
``` when i try to pass options inside the recordAsync function it hit an error loading camera failed. but now it is working in dev-build. why not working in expo?, when i try to use useref  **`videoRef?.current?._reactInternals?.ref?.current?.recordAsync()`** to fetch record async function it is too much complicated. why?

**Comment by alanjhughes** [comment]
@Dart-Sharma - 600ms is .6 of a second. That's too short to be useful. Theres a limit on android to how small you can make it. I'm also not sure why you are using the ref like that. `cameraRef.current.recordAsync()` is how you use it.

**Comment by Dart-Sharma** [comment]
@alanjhughes  that  is seconds i checked a lot. useref is not working in expo sdk 51 - expo camera   cameraRef.current.recordAsync() this way gives me error as record async undefined. so i use use state to store the ref of cameraview.

**Comment by alanjhughes** [comment]
@Dart-Sharma here is an example of how to use the camera https://github.com/expo/examples/blob/master/with-camera/App.tsx

**Comment by Dart-Sharma** [comment]
@alanjhughes  can i use this method in expo go app to check in emulator. it is possible?

**Comment by alanjhughes** [comment]
@Dart-Sharma - No, to record video you need a real device

**Comment by scottsoif** [comment]
So is it seconds for ios and milliseconds for android?

**Pull request merged**
