### PR TITLE
[camera][docs] Fix Missing ratio prop

### PR DESCRIPTION
**Pull request by amandeepmittal**
# Why

Closes ENG-12538 #29761

# How

**Unversioned**
- Since the Ratio prop was removed from the latest version of Expo Camera, this PR updates `takepictureasync` definition to remove the instruction about setting ratio as a prop for Android.
- Also improve the wall of text in the return statement.

CleanShot 2024-06-17 at 16 05 21@2x

**SDK 51**
- Will follow up in a separate PR on `sdk-51` branch (after discussing with Simek about why it is a bad idea to stash and pop those changes from SDK 51 branch :D)

# Test Plan

By running docs locally.

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Review by alanjhughes — APPROVED** [review]

**Comment by alanjhughes** [comment]
Thanks for fixing that @amandeepmittal!

**Comment by 0x6D70** [comment]
Is there any default value for the ratio now? Or is there no way to control the ratio in the new expo-camera version?
I want a photo with a ratio of 16:9, but currently all photos on android are 1:1

@amandeepmittal @alanjhughes

**Review by Simek — APPROVED** [review]
LGTM! And thank you for a great discussion about the docs backport processes! 👍

**Review by lukmccall — APPROVED** [review]

**Comment by DudeFactory** [comment]
I'm not really get it, so we can't make camera as square anymore? We have camera in popup, and it is 1:1 any solution to do it? And we even can't put it crop box becase camera is not affected by overflow hidden too.

**Pull request merged**
