### PR TITLE
[unimodules-react-native-adapter] Flush UI blocks when needed

### LINKED ISSUE #2288: [Camera] camera.takePictureAsync() responds only after second call
The issue is that I receive response from takePictureAsync only after second press on button

Here is my code

```
takePicture() {
    this.setState({
        takeImageText: "... PROCESSING PICTURE ..."
    });
    this.camera.takePictureAsync({ skipProcessing: true }).then((data) => {
        this.setState({
            takeImageText: "PICTURE TAKEN",
            photo: data.uri
        }, console.log(data.uri))
    })
}

<Camera
    ref={ref => { this.camera = ref; }}
    type={this.state.type} >
    <View
        style={{
            flex: 1,
            backgroundColor: 'transparent',
            flexDirection: 'row',
        }}>
        <TouchableOpacity
            onPress={() => {
                this.setState({
                    type: this.state.type === Camera.Constants.Type.back
                        ? Camera.Constants.Type.front
                        : Camera.Constants.Type.back,
                });
            }}>
            <Text>
                Flip
            </Text>
        </TouchableOpacity>
    </View>
</Camera>
<View>
    <TouchableOpacity
        onPress={this.takePicture.bind(this)} >
        <Text>Take photo</Text>
    </TouchableOpacity>
</View>
```
package.json
```
  "dependencies": {
    "@expo/samples": "2.1.1",
    "expo": "^30.0.0",
    "react": "16.3.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz",
    "react-native-camera": "^1.2.0",
    "react-native-datepicker": "^1.7.2",
    "react-native-keyboard-aware-scroll-view": "^0.7.2",
    "react-native-segmented-control-tab": "^3.3.1",
    "react-native-svg": "^6.5.2",
    "react-native-svg-charts": "^5.2.0",
    "react-native-tab-view": "^1.0.2",
    "react-navigation": "^2.9.3",
    "whatwg-fetch": "^2.0.4"
  },
  "devDependencies": {
    "jest-expo": "30.0.0"
  }
```
app.json
`"sdkVersion": "30.0.0",`

### PR DESCRIPTION
**Pull request by sjchmiela**
# Why

Fixes https://github.com/expo/expo/issues/2288.

# How

Adding a UI block wasn't making React run the blocks as soon as possible. 🤷‍♂ 

# Test Plan

With this fix applied `Camera.takePicture` works as expected.

### CODE REVIEW

**Comment by ide** [comment]
`setNeedsLayout` actually performs layout and might be expensive on every `addUIBlock` call (I have not profiled this, though) -- alternatively, what do you think about mirroring UIManager's API and exposing a `setNeedsLayout` method that the Unimodule is responsible for calling?

**Comment by sjchmiela** [comment]
From my short debugging investigation it looked like React doesn’t do much if the layout hasn’t changed. (In `_layoutAndMount`, the first `_dispatch`es return early, `uiBlockWithLayoutUpdate` too.) Is there some other place layout is being recalculated? 🤔

**Comment by ide** [comment]
I didn't look into the implementation `_layoutAndMount` very deeply, so it may be cheap to call it. My main concerns with this PR are (a) whether `_layoutAndMount` is expensive to call frequently and (b) whether there are other non-performance reasons we want to add a UI block without triggering layout. (Why does RN's UIManager not run `_layoutAndMount` when adding a UI block?)

**Comment by sjchmiela** [comment]
a) `_layoutAndMount` seems to be cheap to call frequently
b) Other React Native libraries dispatch calls to view managers via [`UIManager.dispatchViewManagerCommand`](https://github.com/react-native-community/react-native-webview/blob/406241462f7edf8360eb6efb29f7b30f90ca0b02/src/WebView.ios.tsx#L149-L153), which somehow ensures that batch of calls is executed right away and afterwards, `batchDidComplete` is called, which triggers `_layoutAndMount` on `RCTUIManager`.

I think we could either change `addUIBlock` into `executeUIBlock`, which would 1. add and then 2. trigger `_layoutAndMount` (similar to `UIManager.dispatchViewManagerCommand`, but probably not batched) or use `UIM.dVMC` in our unimodules' code (like other libraries do), but then write our own implementation of handling Promises for these functions.

**Review by ide — APPROVED** [review]
> change addUIBlock into executeUIBlock

I think this is a good idea -- we probably want a native API to add a block in addition to a JS API.

**Comment by sjchmiela** [comment]
What do you think about running UI blocks synchronously on the main thread?

**Comment by ide** [comment]
I think it'd be better to execute the UI blocks asynchronously by default for a few reasons:

- `dispatch_sync` can lead to deadlock. If we need synchronous execution, I think we should have a separate way to do that: either introduce a new method like `[UIManager dangerouslyExecuteUIBlockSynchronously]`.
- If there are other UI blocks in the queue, we would run all of them. This might be a little expensive, and it'd be better to run the UI blocks at the start of the next frame so we have a full 16ms to run them.
- Generally, it is easier to change asynchronous code to be synchronous code instead of the other direction. So if we decide that synchronous execution makes more sense, perhaps with Fabric, it will be easier to make that change.

Additionally, it looks like UIManager handles running UI blocks in `flushUIBlocksWithCompletion`. It gathers all the currently pending UI blocks, and then executes them on the main thread (with `dispatch_async`). Since that behavior works for the rest of RN, I'd naively expect it to work for Unimodules too.

**Review by ide — APPROVED** [review]

**Pull request merged**
