### PR TITLE
Add UMFileSystemInterface dependency to expo-media-library podspec

### PR DESCRIPTION
**Pull request by Ashoat**
# Why

This is necessary to build `expo-media-library` in a bare config that uses `use_frameworks!` in its `Podfile` on iOS. I think `expo-media-library` was overlooked in #6503. It uses `UMFileSystemInterface` [here](https://github.com/expo/expo/blob/master/packages/expo-media-library/ios/EXMediaLibrary/EXMediaLibrary.m#L14).

# Test Plan

This is my first PR to Expo, so not entirely sure how to proceed. I made sure `pod install` worked.

### CODE REVIEW

**Review by lukmccall — APPROVED** [review]
LGTM 🎉
However, you need to commit modified pods files. So, please run `pod install` and commit changes.

**Comment by Ashoat** [comment]
For some reason, simply following the `CONTRIBUTING.md`, making this edit, and then running `pod install` leads to a whole bunch of untracked files in my working copy. It's hard for me to understand which of these files I need to be committing and which I don't.

I've made an educated guess based on #6503, but would appreciate further guidance if there is something I've missed.

There seems to be some issue where XCode/Cocoapods is generating separate `[debug|release].xcconfig` files, whereas the existing stuff just has a single `.xcconfig` for both. Here is what I am seeing in my working copy: https://gist.github.com/Ashoat/0f5602bdad7d77234a493ee0193f200e

**Comment by lukmccall** [comment]
@Ashoat,  I've created a new PR from your - https://github.com/expo/expo/pull/7861, which contains all the needed files. I believe you may use a different version of `cocoapods` (we're using `1.8.4`). 

Thanks for  contributing 🎉🥇

Also, I'm closing this PR in favor of the new one.

**Comment by Ashoat** [comment]
Perfect, thank you @lukmccall. You’re right - I’m on 1.9.1.

**Pull request closed without merging**
