### PR TITLE
Pass in serverClientID for serverClientID instead of clientId for GoogleSignIn

### PR DESCRIPTION
**Pull request by peterpme**
Related: #241

### CODE REVIEW

**Comment by Josh-ES** [comment]
Would love to see this get merged in, as it's currently blocking some work we're doing, let me know if there's anything I can do to help with this! :-)

**Comment by peterpme** [comment]
Hey @Josh-ES!

We have a thread going here you can chime in at:
https://forums.expo.io/t/issues-with-linking-from-webbrowser-in-standalone-app/779/20

Also check this out:
https://github.com/expo/examples/tree/master/with-webbrowser-redirect

Instead of redirecting back to the app, I just have a message that pops ups up and says "You can now tap done to close this". Its not the best solution, but a hotfix until Expo fixes it up 😄

**Comment by Josh-ES** [comment]
Hey @peterpme!

Many thanks, I'll take a look through that material. For now we've been able to achieve what we want to achieve (which is effectively just Google sign-in for the foreseeable future) by passing ID tokens to our services and calling out to the Google `/tokeninfo` endpoint, but it's not ideal. For some, that might be a potential solution though!

**Comment by terribleben** [comment]
Hey there - we ended up going with a slightly more complex fix which will ship this week: https://github.com/expo/expo/commit/c636874a803b1cb4c2d805f557b205f4d20f7812

From conferring with @janicduplessis, I think that should solve this same issue. Let me know if that sounds wrong.

**Comment by absolutpauer** [comment]
https://github.com/expo/expo/commit/c636874a803b1cb4c2d805f557b205f4d20f7812 seems to fix the problem for native login, but not for web login. It looks like serverClientId isn't being passed for web login. Is there a plan to address this?

**Pull request closed without merging**
