### PR TITLE
[updates] Fix updates test

### PR DESCRIPTION
**Pull request by alanjhughes**
# Why
Updates tests are failing on CI because they currently won't compile.

# How
Implemented the new Interface correctly but I haven't added any test code as I'm completely unfamiliar with this code

# Test Plan
CI

### CODE REVIEW

**Review by douglowder — COMMENTED** [review]
I'll take a look @alanjhughes and pull in @wschurman if needed.

**Comment by wschurman** [comment]
Ah, this is definitely due to my changes. I can take this if you want.

**Comment by douglowder** [comment]
Thanks Will -- it would be great if you can have a look at this. I'll do some testing locally on my machine to see if anything obvious pops up, but you are more familiar with this code.

**Comment by wschurman** [comment]
Superseded by https://app.graphite.dev/github/pr/expo/expo/32204/expo-updates-android-Fix-instrumentation-test (easier for me to create a new PR)

**Pull request closed without merging**
