### PR TITLE
[go] update lottie-react-native to 6.1.2

### PR DESCRIPTION
**Pull request by matinzd**
# Why

There have been a lot of changes in Lottie React Native and there are some issues for users using Expo Go. 

May fix:
- https://github.com/lottie-react-native/lottie-react-native/issues/1075
- https://github.com/lottie-react-native/lottie-react-native/issues/999
- https://github.com/lottie-react-native/lottie-react-native/issues/1005

# How

- Changed source type to `npm` in expoGoConfig
- Ran `et uvm -m lottie-react-native -c 6.1.2`
- Updated NCL example

# Test Plan

- [x] Lottie React Native should work as expected in Expo Go

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [x] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Comment by matinzd** [comment]
Can someone help me with testing this? @Kudo @tsapeta

**Comment by matinzd** [comment]
@Kudo It appears that everything is in order, except for the fact that there are internal issues causing the EAS workflow to fail.

**Comment by Kudo** [comment]
these ci failures are expected and i verified it works for NCL. let's merge this pr and thanks for your awesome contribution!

**Review by Kudo — APPROVED** [review]

**Comment by jcohenho** [comment]
@matinzd I tested this using `.lottie` files instead of `.json` files and the animations won't render in Expo Go for either ios or android simulators. I configured the project following the configuration docs [here](https://github.com/lottie-react-native/lottie-react-native#if-you-want-to-use-lottie-files). Am I missing something else to get `.lottie` files working?

**Comment by brentvatne** [comment]
@jcohenho - you should post that to the lottie repository.

however, i would strongly recommend following these instructions for extending the metro config: https://docs.expo.dev/guides/customizing-metro/ - and adapt the instructions from lottie to this

**Comment by matinzd** [comment]
> @jcohenho - you should post that to the lottie repository.
> 
> 
> 
> however, i would strongly recommend following these instructions for extending the metro config: https://docs.expo.dev/guides/customizing-metro/ - and adapt the instructions from lottie to this

A lot of people had an issue while using Expo Go and `.lottie` files. 
I feel like they do not configure their metro bundler according to docs but I don't know if that's the case. 🤷

**Comment by jcohenho** [comment]
@brentvatne I configured metro as well, still doesn't work. I'll create an issue in the lottie repo as you suggested, thanks.

**Comment by matinzd** [comment]
> > @jcohenho - you should post that to the lottie repository.
> > 
> > 
> > 
> > however, i would strongly recommend following these instructions for extending the metro config: https://docs.expo.dev/guides/customizing-metro/ - and adapt the instructions from lottie to this
> 
> A lot of people had an issue while using Expo Go and `.lottie` files. 
> I feel like they do not configure their metro bundler according to docs but I don't know if that's the case. 🤷
But we had a lot of fixes and features I and would recommend you to update lottie to the next version if you find some time for the next SDK.

**Pull request merged**
