### PR TITLE
[docs] Add Aptabase Analytics

### PR DESCRIPTION
**Pull request by goenning**
# Why

One of our users mentioned they couldn't find Aptabase on this list, and I thought it would be a good fit adding it here.

Aptabase is an open source and privacy-friendly analytics for apps, including React Native and Expo :)

# How

Added a new BoxLink like the other options.

# Test Plan

N/A

# Checklist

N/A

### CODE REVIEW

**Comment by amandeepmittal** [comment]
Hey @goenning, the dos or the page you link you added to the Expo Docs do not have specific instructions about how to use it in an Expo project. It might get confusing for some developers who use Expo as to learn if there are differences or require specific instructions. From reading the docs here: https://github.com/aptabase/aptabase-react-native it sounds like plug-n-play, can you confirm?

**Comment by goenning** [comment]
hey @amandeepmittal 

I tried it today on a fresh new Expo app and it was plug and play. I just had to install the NPM package and called the init + trackEvent functions. 

The SDK is 95% javascript, with just a tiny native module using `constantsToExport` to get the appVersion and appBuildNumber.

When I first opened the emulator it asked if I wanted to use `Expo Go`, I said yes and it worked fine, I didn't have to use the "Development Build".

**Review by brentvatne — APPROVED** [review]
ah very cool! thanks for the pr!

**Review by amandeepmittal — APPROVED** [review]
Thank you for the clarification and your contribution!

Congratulations on your first contribution, and welcome to the community 🎉

**Comment by goenning** [comment]
@brentvatne @amandeepmittal Thanks all for reviewing and merging.

I tried using Aptabase with Expo Go on a real device and it worked ok, with the exception that appVersion and appBuildNumber are not sent to the analytics server because this information comes from native modules.

The [Use Analytics](https://docs.expo.dev/guides/using-analytics/) page explicitly mentions that all services requires configuring custom native code, which is no longer correct.

Can I submit another PR to mention that Aptabase is an exception and it works with Expo Go as some people might be interested in knowing that?

I thought about changing "Each analytics SDK" to "Some analytics SDK" and add a green check and "Works with Expo Go" to Aptabase box (see below). Looking for some feedback before acting coding it.

Thanks!

image

**Pull request merged**
