### PR TITLE
Add Transporter

### PR DESCRIPTION
**Pull request by daniel-nagy**
# Why

The motivation for this PR is to demonstrate how [Transporter](https://github.com/daniel-nagy/transporter) may be used to facilitate communication between the native app and the web app.

Transporter was created specifically for this type of problem. Some of the advantages of using Transporter include the following:

* Functions may be passed as properties of an object.
* Transporter is a server-client architecture that handles scoping to avoid collisions.
* Transporter absorbs the complexity of message passing.
* Transporter's SuperJson data transfer format supports most JavaScript data types.
* Transporter can be independently developed and tested, and it has some test coverage.

I'm indifferent to whether or not this PR gets merged. I just wanted to bring awareness to Transporter and see if it could provide value for this feature.

# How

With these changes, there is a well-defined API contract between the native app and the web app. The global-event bridge has been removed. Expo can provide context to the web app from the native app using the `WebContext` React context. This enables high-level communication between the native app and the web app without needing to do any explicit message passing.

# Drawbacks

* Transporter uses the [`Crypto`](https://developer.mozilla.org/en-US/docs/Web/API/Crypto) module internally. However, Hermes does not support the `crypto` API. To workaround this, I'm using expo-crypto as a polyfill. This obviously isn't great, and I can make some changes to Transporter to allow injecting a custom function for generating UUIDs.
* Transporter uses the [`FinalizationRegistry`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/FinalizationRegistry) API to perform garbage collection. Again, unfortunately, Hermes does not support the `FinalizationRegistry` API. Technically, this creates the possibility of a memory leak, but only inside the WebView (not the native app) and only if developers are passing functions as callbacks (or using the `proxy` API from Transporter to proxy objects instead of cloning them).
* Transporter is still in beta, and I am not currently using it or actively working on it.
* If bug fixes or changes are required in Transporter, it could slow down development because Transporter is external.

### CODE REVIEW

**Comment by daniel-nagy** [comment]
Does Expo not support the [`exports`](https://nodejs.org/api/packages.html#exports) feature of Node?

**Comment by ide** [comment]
Hi, thanks for the PR. I don't think we'll merge this because of the external dependency that implements quite a bit of functionality, and we have another experimental implementation of WebView DOM <=> native communication that is not in this repo.

The package.json exports feature is partially supported I believe by the Expo dev tools. There may be edge cases that are not supported, especially around when to treat a dual-mode module as CJS vs. ESM. @EvanBacon will have the most up-to-date knowledge of "exports" support.

**Comment by marklawlor** [comment]
While other Transporter and Expo Router are both trying to solve the problem of cross realm communication, they are both very different from a philosophical perspective.

For example, Transporter relies on the `useClient` and `useServer` hooks with a seperate defined API. But Expo Router aligns itself with React Server Components which use a component's props as the contract between Server/Client (not a seperate API). Because of these differences, it would be hard to use Transporter along side other Expo Router features such as RSC and server rendering.

I think a better way to move forward is to PR individual features instead of replacing the entire protocol. For that reason I'm going to close this PR.

> Transporter is still in beta, and I am not currently using it or actively working on it.

I'm also not sure that we want to actively rely on a package that is not maintained.

**Comment by daniel-nagy** [comment]
Thanks, @ide and @marklawlor, for the replies. I understand not wanting to use an external dependency.

> Expo Router aligns itself with React Server Components which use a component's props as the contract between Server/Client

To be clear, this is still using props as the contract between native and web. However, unlike RSCs, you need some way of pushing prop changes from native to web in real time.

I suppose you could use Transporter to send an RSC payload to the web app. The RSC payload would replace the `SuperJson` transfer format. However, wrapping a web component is not the same as rendering a React component on the server. You need some way of maintaining a communication channel between the native app and the web app, and that is where Transporter comes in.

**Pull request closed without merging**
