### PR TITLE
[image-picker] fix: view being transparent on iOS 14.5

### LINKED ISSUE #12009: ImagePicker opens under RNS screen modal
**Summary**

ImagePicker opens under RNS screen modal

**Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!**

managed

**What platform(s) does this occur on?**

iOS

**SDK Version (managed workflow only)**

40

**Environment**

  Expo CLI 4.0.8 environment info:
    System:
      OS: macOS 11.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.16.3 - ~/.nvm/versions/node/v12.16.3/bin/node
      Yarn: 1.22.10 - ~/.nvm/versions/node/v12.16.3/bin/yarn
      npm: 6.14.9 - ~/.nvm/versions/node/v12.16.3/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.1 - /usr/local/bin/pod
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6953283
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: ~40.0.0 => 40.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    npmGlobalPackages:
      expo-cli: 4.0.8
    Expo Workflow: managed

**Reproducible demo or steps to reproduce from a blank project**

https://snack.expo.io/@jbiesiada/image-picker-rns

https://user-images.githubusercontent.com/28870390/108758201-1c233b00-754b-11eb-8b17-bc68a499faf8.MP4

https://user-images.githubusercontent.com/28870390/108758247-2b09ed80-754b-11eb-9147-d901528a2117.MP4

### LINKED ISSUE #12771: ImagePicker.launchCameraAsync displays the Camera under Modal on iOS 14.5
### Summary

**Problem**: 
The Camera is displayed under Modal after upgrading to iOS 14.5

**Expected behavior**:
Display Camera over Modal

**Source Code**
```javascript
import { StatusBar } from 'expo-status-bar';
import React from 'react';
import { Button, StyleSheet, Text, View, Modal } from 'react-native';
import * as ImagePicker from 'expo-image-picker';

export default function App() {
  return (
    <View style={styles.container}>
      <StatusBar style="auto" />
      <Modal
        visible={true}
        animationType="slide"
        hardwareAccelerated={true}
        transparent={true}
      >
        <View style={styles.modal}>
          <View style={{ width: 200, height: 200, backgroundColor: "#fff" }}>
            <Button title="Camera" onPress={async () => {
              const { status: cameraStatus } = await ImagePicker.requestCameraPermissionsAsync()
                .catch(err => console.log(`camera_permission_err: ${err}`));
              const { status: cameraRollStatus } = await ImagePicker.requestMediaLibraryPermissionsAsync()
                .catch(err => console.log(`camera_roll_permission_err: ${err}`));
              if (cameraStatus !== 'granted' || cameraRollStatus !== 'granted') {
                Alert.alert(
                  'Permission not granted',
                  'Please allow this app to access camera and photo library in your phone\'s setting.',
                  [
                    {
                      text: 'OK',
                      onPress: async () => {
                        if (cameraStatus !== 'granted') {
                          await ImagePicker.requestCameraPermissionsAsync();
                        }
                        if (cameraRollStatus !== 'granted') {
                          await ImagePicker.requestMediaLibraryPermissionsAsync();
                        }
                      },
                    },
                  ],
                  { cancelable: true },
                );
                return;
              }
              const capturedImage = await ImagePicker.launchCameraAsync({
                allowsEditing: false,
                aspect: [4, 3],
                base64: true,
              }).catch(err => {
                console.log(err)
              });
              console.log(capturedImage)
            }} />
          </View>
        </View>
      </Modal>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modal: {
    flex: 1,
    backgroundColor: '#fff0',
    alignItems: 'center',
    justifyContent: 'center',
  },
});

```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

41

### Environment

  Expo CLI 4.4.3 environment info:
    System:
      OS: Windows 10 10.0.18363
    Binaries:
      Node: 10.16.3 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.19.1 - C:\Users\xidanzheng\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.8 - C:\Users\xidanzheng\AppData\Roaming\npm\npm.CMD
    npmPackages:
      expo: ~41.0.1 => 41.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

**Demo**
https://snack.expo.io/@macroview.dbs/test

https://user-images.githubusercontent.com/34149063/116500022-36c5b780-a8e0-11eb-9ae6-09d49225e75a.mp4

### PR DESCRIPTION
**Pull request by cruzach**
# Why

closes https://github.com/expo/expo/issues/12771
closes https://github.com/expo/expo/issues/12009

# How

reading through https://developer.apple.com/library/archive/featuredarticles/ViewControllerPGforiPhoneOS/PresentingaViewController.html#//apple_ref/doc/uid/TP40007457-CH14-SW1, and after testing a couple of the different UIModalPresentationStyles, it seems like `UIModalPresentationPageSheet` is what we're after. it actually looks like UIModalPresentationOverCurrentContext is the only one of that enum to cause that problem, bc part of its purpose is to allow for a transparent view.

worth mentioning that `UIModalPresentationPageSheet` is [_usually_ the default used by iOS ](https://developer.apple.com/documentation/uikit/uimodalpresentationstyle/uimodalpresentationautomatic?language=objc)

# Test Plan

Tested using the repro in the issue linked, and the modal is no longer visible underneath. see screenshots for behavior:
Without the fix, you can see that the modal containing the `Camera` button is visible when the picker is open. The major change that this PR introduces is that on iPads, the imagepicker is no longer presented as full screen (this should match the behavior of `expo-docement-picker` since it has the same `UIModalPresentationPageSheet` setting.

## ios 14.5 without fix:
Screen Shot 2021-05-11 at 3 48 51 PM
Screen Shot 2021-05-11 at 3 48 44 PM

## ipad without fix:
Screen Shot 2021-05-11 at 3 46 07 PM
Screen Shot 2021-05-11 at 3 45 59 PM

## ios 14.5 with fix:
Screen Shot 2021-05-11 at 3 50 52 PM
Screen Shot 2021-05-11 at 3 50 47 PM

## ipad with fix:
Screen Shot 2021-05-11 at 3 43 06 PM
Screen Shot 2021-05-11 at 3 43 00 PM

## ios 12 with fix:
(included to check to make sure no issues on older versions of iOS)
Screen Shot 2021-05-11 at 4 03 57 PM
Screen Shot 2021-05-11 at 4 03 42 PM

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.io and README.md).
- [x] This diff will work correctly for `expo build` (eg: updated `@expo/xdl`).
- [x] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Review by lukmccall — APPROVED** [review]
LGTM 🚀

**Review by bbarthec — APPROVED** [review]
💪

**Comment by karanmartian** [comment]
Amazing Work! When will this be merged and when can we have a release?

**Comment by cruzach** [comment]
Failing SDK check is unrelated to this PR, so merging now

**Comment by chunyenHuang** [comment]
Is this released yet?

**Comment by cruzach** [comment]
https://github.com/expo/expo/issues/12771#issuecomment-847113976

**Pull request merged**
