### PR TITLE
Fixes .zlogin sourcing

### PR DESCRIPTION
**Pull request by vrgimael**
Just fixes a typo, I doubt it makes much of a difference in most people's setup

### CODE REVIEW

**Comment by Kudo** [comment]
good catch and thanks for the contribution. the script is actually cloned to multiple places. could you help us to update them together?

- https://github.com/expo/expo/blob/main/packages/expo-updates/scripts/source-login-scripts.sh
- https://github.com/expo/expo/blob/main/packages/expo-constants/scripts/source-login-scripts.sh
- https://github.com/expo/expo/blob/main/packages/expo-module-scripts/templates/scripts/source-login-scripts.sh

we would also like to update changelogs for the community to know what we changed in the new releases.
- https://github.com/expo/expo/blob/main/packages/expo-updates/CHANGELOG.md
- https://github.com/expo/expo/blob/main/packages/expo-constants/CHANGELOG.md
- https://github.com/expo/expo/blob/main/packages/expo-module-scripts/CHANGELOG.md
you can update under the Unpublished > Bug Fixes section.

**Comment by vrgimael** [comment]
Done

**Review by ide — APPROVED** [review]

**Review by Kudo — APPROVED** [review]
looks good, thanks for your great help!

**Comment by ismaelbarry** [comment]
I recently upgraded from Expo SDK 45 to SDK 46, and I'm running into issue with `expo constants`. Before upgrading my app would build successfully in Xcode. However, after upgrading to SDK 46, I'm getting the EXConstants Command PhaseScriptExecution failed with a nonzero exit code

I tried the above solutions, with the most recent one provided by @aprilmintacpineda, and nothing seems to work. The app still fails to build.

Anyone have any ideas for solutions? Is this still a know issue/bug?

Thanks and I appreciate any help! :)

**Pull request merged**
