### PR TITLE
[dev-launcher] Expose method to determine if you are running in a development build

### PR DESCRIPTION
**Pull request by lukmccall**
# Why

Closes ENG-2627.

# How

Checks if the `EXDevLauncher` module exists. It will only exist in the development build. 

# Test Plan

Run:
```js
export default function App() {
  return (
    <View style={styles.container}>
      <Text>{ DevClient. isDevelopmentBuild() }</Text>
  	  <StatusBar style="auto" />
    </View>
  );
}
```
inside:
- development build ✅
- expo go ✅

### CODE REVIEW

**Review by esamelson — APPROVED** [review]
I would lean towards a more concise name for this method like `isDevelopmentBuild`; otherwise this LGTM 👌

**Comment by pors** [comment]
How can this be used in an app? I tried:

```
import DevClient from 'expo-dev-client';

console.log(DevClient.isDevelopmentBuildO;
```

but that doesn't work.

**Comment by lukmccall** [comment]
Hi @pors, I think you use the wrong import 🤔 
```
import * as DevClient from 'expo-dev-client';
console.log(DevClient.isDevelopmentBuild);
```
should do the job

**Comment by pors** [comment]
@lukmccall Yes, that fixes it, thanks!

**Pull request merged**
