### PR TITLE
[sqlite] Export WebSQLDatabase and Query

### PR DESCRIPTION
**Pull request by tkrajina**
# Why

The current `d.ts` file for SQLIte is:

```typescript
import './polyfillNextTick';
declare type InternalResultSet = {
    error: Error;
} | {
    insertId?: number;
    rowsAffected: number;
    rows: Array<{
        [column: string]: any;
    }>;
};
export declare type SQLiteCallback = (error?: Error | null, resultSet?: InternalResultSet) => void;
export declare function openDatabase(name: string, version?: string, description?: string, size?: number, callback?: (db: WebSQLDatabase) => void): WebSQLDatabase;
declare type WebSQLDatabase = unknown;
declare const _default: {
    openDatabase: typeof openDatabase;
};
export default _default;
```

Since `WebSQLDatabase` is `unknown` it forces the user to work with the result of `openDatabase()` as with any other type-unsafe object. Basically erasing any improvement from a typescript declaration file.

Note that even the DefinitelyTyped `.d.ts` has (almost) everything needed to make the API completely typesafe (one thing missing is probably `openDatabase()` returning a `Database` instead of `any`): https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/expo/index.d.ts#L2595

# How

This PR adds a new interface `WebSQLDatabase` with the following method:

```
exec(queries: Query[], readOnly: boolean, callback: SQLiteCallback): void
```

and makes `openDatabase()` return that interface. 

In addition to that it also exposes `Query` and `ResultSet`. They are renamed from `InternalQuery` and `InternalResultSet`, since they aren't really "internal" types, but exposed to the user in the APIs.

This PR is just an idea, feedback is welcome.

### CODE REVIEW

**Comment by tkrajina** [comment]
Another thing I'd suggest is this:

```typescript
 export type Query = { sql: string; args: unknown[] };
 
-export type ResultSet =
-  | { error: Error }
-  | {
-      insertId?: number;
-      rowsAffected: number;
-      rows: Array<{ [column: string]: any }>;
-    };
-
-export type SQLiteCallback = (error?: Error | null, resultSet?: ResultSet) => void;
+export type ResultSetError = {
+  error: Error;
+};
+export type ResultSet = {
+  insertId?: number;
+  rowsAffected: number;
+  rows: Array<{ [column: string]: any }>;
+};
+
+export type SQLiteCallback = (error?: Error | null, resultSet?: ResultSetError|ResultSet) => void;
```
Because in normal javascript you'd just `if (rs.error) {...}`, but in typescript it's handy to have a type for casting with `if ((<rs>resultSet).error) { ... } else { const resultSet = <ResultSet>rs; ... }`

**Review by tsapeta — APPROVED** [review]
Looks good to me! Thanks for your contribution 👍 I'm also fine with changing the type of `resultSet` parameter as you proposed - would you like to change it as well?

**Comment by tkrajina** [comment]
@tsapeta Thanks. The update is here.

**Comment by tkrajina** [comment]
Ops, I just realised there is another problem. And I think the problem isn't in my code, but it was here even before (correct me if I'm wrong). 

So, originally (without my PR), the callback is:
```
type InternalResultSet =
  | { error: Error }
  | {
      insertId?: number;
      rowsAffected: number;
      rows: Array<{ [column: string]: any }>;
    };
export type SQLiteCallback = (error?: Error | null, resultSet?: InternalResultSet) => void;
```
...but, the callback is called here:
```
    ExponentSQLite.exec(this._name, queries.map(_serializeQuery), readOnly).then(
      nativeResultSets => {
        callback(null, nativeResultSets.map(_deserializeResultSet));
      },
```
The result of `nativeResultSets.map(_deserializeResultSet)` is an *array*, not *one* deserializedResultSet. So, originally, the last parameter of the callback should have been `resultSet?: InternalResultSet[]` (instead of `resultSet?: InternalResultSet`).

**Comment by tsapeta** [comment]
Hey @tkrajina, sorry for late response 😅 Yeah, it should probably be an array of result sets. I'm going to merge this anyway and fix it right after. Thanks for contribution! 💪

**Pull request merged**
