### PR TITLE
Update location.md

### PR DESCRIPTION
**Pull request by jkhales**
Clean up imports and add stylesheet.

### CODE REVIEW

**Review by tsapeta — COMMENTED** [review]
Hi JJ 👋 Could you also apply the same changes to `docs/pages/versions/unversioned/sdk/location.md`? This is required when we want to keep docs changes for future SDKs 😉

**Comment by cruzach** [comment]
The actual js that the "Open this in snack" button pulls is in the `examples/` directory - https://github.com/expo/expo/blob/master/docs/static/examples/unversioned/location.js

This way we can keep the length of doc pages down by not needing to include **all** the code the snack requires to run. But I definitely agree with removing the `Constants` import from the .md code block

**Comment by jkhales** [comment]
> The actual js that the "Open this in snack" button pulls is in the `static/examples/` directory - https://github.com/expo/expo/blob/master/docs/static/examples/unversioned/location.js
> 
> This way we can keep the length of doc pages down by not needing to include **all** the code the snack requires to run. But I definitely agree with removing the `Constants` import from the .md code block

Some people (me) copy paste code directly into an editor, seems like a bad experience to give them broken code.

**Comment by cruzach** [comment]
Oh I gotchya.. maybe we can make the entire code block clickable then? 

what makes you copy/paste rather than clicking the button- is it just that you don't scroll down enough to see it?

**Comment by jkhales** [comment]
Just paired with @cruzach , issue is a bit more complicated than I realized, but we are going to keep the PR as is for now. Committed changes directly to unversioned: https://github.com/expo/expo/blob/master/docs/pages/versions/unversioned/sdk/location.md

**Review by tsapeta — APPROVED** [review]

**Pull request merged**
