### PR TITLE
[android][navigation-bar] Add androidNavigationBar options in configure app.json

### PR DESCRIPTION
**Pull request by vivianzzhu91**
# Why

Because of those feature requests, https://expo.canny.io/feature-requests/p/android-navigation-bar-color-change, https://expo.canny.io/feature-requests/p/dark-mode-for-android-navigation-bar, https://expo.canny.io/feature-requests/p/hide-android-bottom-buttons--fullscreen-mode, I decided to add a `androidNavigationBar` option in `app.json` to configure navigation bar on Android.

# How

Add three options for `androidNavigationBar`:
```javascript
{
  "androidNavigationBar": {
     /*
        Determines to show or hide bottom navigation bar.
        "true" to show, "false" to hide.
        If set to false, status bar will also be hide. As it's a general rule to hide both status bar and navigation bar on Android developer official docs.
      */
    "visible": BOOLEAN,
    /*
      Configure the navigation bar icons to have light or dark color.
      Valid values: "light-content", "dark-content".
    */
    "barStyle": STRING,

    /*
      Configuration for android navigation bar.
      6 character long hex color string, eg: "#000000"
    */
    "backgroundColor": STRING
  }
}
```

# Test Plan

Tested on Android devices, and all configurations worked as expected.
Screen Shot 2019-08-09 at 3 29 57 PM
Screen Shot 2019-08-09 at 4 01 37 PM
Screen Shot 2019-08-09 at 3 49 13 PM
Screen Shot 2019-08-09 at 3 38 20 PM

### CODE REVIEW

**Comment by GollyJer** [comment]
This is really cool! Being based on app.json I assume it won't be adjustable at runtime. Is that correct?

We have an issue with our app when the user chooses a dark theme the navigation bar remains white (on some android devices).

**Comment by jaroslav009** [comment]
Not worked

**Comment by MattKoboski** [comment]
Great piece of work @vivianzzhu91!
Have you tried to make the configuration work in a runtime?

**Comment by vivianzzhu91** [comment]
This feature `barStyle:dark-content` is only available after `Andriod O`. See [`here`](https://developer.android.com/reference/android/view/View.html#SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR) for more information. And it cannot be adjustable at runtime and can only be predefined in `app.json`.

**Comment by maytinhdibo** [comment]
> This feature `barStyle:dark-content` is only available after `Andriod O`. See [`here`](https://developer.android.com/reference/android/view/View.html#SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR) for more information. And it cannot be adjustable at runtime and can only be predefined in `app.json`.

@vivianzzhu91 it does not work, please support it can change when run.

**Comment by EeoBryan** [comment]
Hi, I tried and it didnt work for me. Can you help me take a look. I included these in my app.json and it gave me error saying that "android navigation bar isn't supposed to be in app json"
expo3
expo4

**Comment by vivianzzhu91** [comment]
Hi @EeoBryan you should include `"androidNavigationBar"` in the same level with `"ios"`. So the first pic seemed to be the right way to do it. Remove the `"androidNavigationBar"` in the `"android"` because it doesn't exist in the configuration we set.

**Comment by EeoBryan** [comment]
@vivianzzhu91 hmm, i tried that but apparently I still got the same error heh. Maybe I should wait for the next SDK update or something?

**Comment by ide** [comment]
This will go out with SDK 35.

**Comment by ksairi** [comment]
@ide how can I test this in my app from the source code in master branch as I see that this has been merged already?
Which of the packages in `expo/packages` have been updated with this merge so I can use them in my node_modules?
cheers!

**Comment by ide** [comment]
These are the instructions for building from source: https://github.com/expo/expo/blob/56f502adbc56f10659744a730cbba3ddd2a0930b/README.md#set-up. If you get stuck I recommend waiting for the next SDK release.

**Comment by ksairi** [comment]
@ide thanks much!

**Comment by adamsolomon1986** [comment]
is this availabe in SDK 35?

**Comment by adamsolomon1986** [comment]
does it work in SDK 35?

**Comment by sidlovskyy** [comment]
> does it work in SDK 35? I saw that it hides it on launch but once you navigate to another screen in your app, the nav bar shows up again!!!! any idea?

The same for me

**Comment by zcduthie** [comment]
Thank you for implementing this. I'm sure many people will be very grateful (myself included). Could the `SYSTEM_UI_FLAG_IMMERSIVE_STICKY` flag be added as well? Based on the docs at https://developer.android.com/training/system-ui/immersive and having a quick look at the code, it looks like the code currently enables something closer to 'Lean back' mode?

**Comment by Rafnexx** [comment]
> does it work in SDK 35? I saw that it hides it on launch but once you navigate to another screen in your app, the nav bar shows up again!!!! any idea?

Same here, any possible solutions?
It's hidden on startup until I click something in screen, then it shows.

**Comment by sungsong88** [comment]
Yea... I'm also wondering if there is a way to re-hide the navigation bar...

**Comment by zcduthie** [comment]
To clarify, I believe the existing implementation is not quite right, and instead of:

```java
/*** THIS CODE IMPLEMENTS LEAN BACK MODE ***/

if (!visible) {
	// Hide both the navigation bar and the status bar. The Android docs recommend, "you should
	// design your app to hide the status bar whenever you hide the navigation bar."
	View decorView = activity.getWindow().getDecorView();
	int flags = decorView.getSystemUiVisibility();
	flags |= (View.SYSTEM_UI_FLAG_HIDE_NAVIGATION | View.SYSTEM_UI_FLAG_FULLSCREEN);
	decorView.setSystemUiVisibility(flags);
}
```

it should be something like:

```java
/*** THIS CODE IMPLEMENTS STICKY IMMERSIVE MODE ***/

if (!visible) {
	View decorView = activity.getWindow().getDecorView();
	int flags = decorView.getSystemUiVisibility();
	flags |= (View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY // Need this flag!
		// Hide the nav bar and status bar
		| View.SYSTEM_UI_FLAG_HIDE_NAVIGATION
		| View.SYSTEM_UI_FLAG_FULLSCREEN);
	decorView.setSystemUiVisibility(flags);
}
```

**Comment by lotrgollum87** [comment]
Someone filed a bug the navigation bar displaying after first touch -> https://github.com/expo/expo/issues/6525

**Comment by stevemarksd** [comment]
Is this working?

**Comment by lehongvan** [comment]
are there no solutions?

**Comment by cyprientertrais** [comment]
Up any solution ?

**Comment by nkaramarko** [comment]
this doesnt work when keyboard is showing. color goes back to default..
will this be fixed soon?

**Comment by binh27112004** [comment]
Doesn't Work :(
image

**Comment by YahiaBadr** [comment]
is it possible to change the color based on the current screen?

**Comment by hucek** [comment]
> this doesnt work when keyboard is showing. color goes back to default..
> will this be fixed soon?

The same happens when a Modal is opened. it goes back to the default color.

**Comment by m3yevn** [comment]
unfortunately, not working for me although i set it exactly the same as instruction, any idea why?

**Comment by Slapbox** [comment]
Is there any plan to support dynamic configuration of the color/to fix the issues that have been reported with modals?

https://expo.canny.io/feature-requests/p/android-navigation-bar-background-color-change-on-the-fly

**Comment by EzeMortal** [comment]
> 
> 
> > this doesnt work when keyboard is showing. color goes back to default..
> > will this be fixed soon?
> 
> The same happens when a Modal is opened. it goes back to the default color.

Same here, but thanks anyway. This is great!

**Comment by lucasnr** [comment]
> > > this doesnt work when keyboard is showing. color goes back to default..
> > > will this be fixed soon?
> > 
> > 
> > The same happens when a Modal is opened. it goes back to the default color.
> 
> Same here, but thanks anyway. This is great!

Also happening here. I hope it'll be fixed soon

**Comment by gpbaculio** [comment]
not working with fullscreen on sdk 37

**Comment by Scor0806** [comment]
Not sure why, but doesn't seem to work with my Samsung S8. Though, it works with my Android Emulator. SDK 38

**Comment by ilikebuttons** [comment]
I'm getting a validation error when I try to hide the status/nav bars:

Error: Problems validating fields in app.json. See https://docs.expo.io/workflow/configuration/
 • Field: androidNavigationBar.visible - should be string.
 • Field: androidNavigationBar.visible - should be equal to one of the allowed values.

**app.json:**
`"androidNavigationBar": {
      "visible": false
    },`

**Comment by thisBrian** [comment]
@ilikebuttons 
That field is no longer boolean but is either `leanback`, `immersive`, or `sticky-immersive`. 
It was merged [in this PR](https://github.com/expo/expo/pull/7049).
Might also want to double check the [changelog](https://github.com/expo/expo/blob/master/CHANGELOG.md#-breaking-changes-2) for other breaking changes when upgrading expo versions.

**Comment by Amosao** [comment]
not working on android 10, sdk 38

**Comment by brentvatne** [comment]
> not working on android 10, sdk 38

open an issue, fill out the requested information

**Pull request merged**
