### PR TITLE
[apps][templates][go] bump to react-native 0.71.4

### PR DESCRIPTION
**Pull request by Kudo**
# Why

bump react-native@0.71.4 for sdk 48 patch release

# How

- bump packages
  - react-native: 0.71.3 -> 0.71.4
  - metro-react-native-babel-preset: 0.73.7 -> 0.73.8
- [react-native-lab] mainly react-native bump and hermes bump
- reversion ios and android sdk 48 code, mainly for versioned hermes.

# Test Plan

ci passed
versioned expo go + ncl

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [x] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Review by brentvatne — APPROVED** [review]

**Comment by xpario** [comment]
simply updated to react-native@0.71.4 (works fine with 0.71.3) causes the following when running the app:

nvariant Violation: Failed to call into JavaScript module method RCTDeviceEventEmitter.emit(). Module has not been registered as callable. Bridgeless Mode: false. Registered callable JavaScript modules (n = 0): .
        A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native., js engine: hermes
Invariant Violation: No callback found with cbID 9177 and callID 4588 for module <unknown>. Args: '[4060]', js engine: hermes
Invariant Violation: No callback found with cbID 9179 and callID 4589 for module <unknown>. Args: '[4061]', js engine: hermes
Invariant Violation: No callback found with cbID 9181 and callID 4590 for module <unknown>. Args: '[4062]', js engine: hermes

**Comment by brentvatne** [comment]
@xpario - can you please share a minimal reproducible example?

**Comment by xpario** [comment]
@brentvatne I am not able to pinpoint the cause. We simply install 0.71.4 w/ Expo (latest) and the error would occur. We narrowed it down to referencing a invalid Context - we think. When we rolled back to 0.71.3 there was no issue.

**Comment by brentvatne** [comment]
@xpario - is this is a development build or expo go? you can see the list of changes in 0.71.4 here: https://github.com/facebook/react-native/releases/tag/v0.71.4

**Comment by xpario** [comment]
@Kudo yes exactly. We are still debugging but we (believe) that it is due to other NPM packages that were built on 48.06 / 0.71.3. that are included in the 0.71.4 project. To be clear when we downgraded to 0.71.3 but left the new Expo 48.09 it worked fine. upgrade to 0.71.4 again and same error. The error I pasted above was repeating in an infinite loop when the project was executed (npx expo start -c) . The console (command line) showed nothing. the Web debugger displayed the error I pasted.

**Comment by Kudo** [comment]
@xpario that's strange, as 0.71.4 does not have any related changes to `RCTDeviceEventEmitter`. did you test on a development build or expo go?

**Comment by xpario** [comment]
@Kudo We have figured out what was causing it, but not why it was happening. We have other NPM packages that are built with expo. These packages were Expo 48.06 / RN 0.71.3 and were installed in our application. We simply rebuilt the NPM packages with Expo 48.09 / RN 0.71.4 and updated them in our app and the problem magically went away.

**Comment by xpario** [comment]
> I'm at a bit of a loss for what we are experiencing related to this. We pinned our Expo version back to 48.0.6 because React Native libraries 0.71.4 are causing our app to crash on boot, with no log or explanation. However even pinning our version to 48.0.6 and using package.json "resolutions" to pin react native to 0.71.3, when we build with Expo Dev the Pods still install React Native 0.71.4 and everything crashes back to OS. Pretty sure React Native 0.71.4 wasn't intended to kill us? Can you confirm? ;)
> 
> I'm very confused though as to why React Native 0.71.4 would get installed in Pods process but its killing our builds on Expo.dev. This application doesn't have imported packages we built ourselves. Is there some way we can have our ./node_modules rebuilt with RN 0.71.4 in mind? I don't know of such a thing.

@nickwelp See my post above. We figured out how to resolve what you are seeing as we had the same exact thing with Expo.

**Comment by Kudo** [comment]
thanks @xpario for your information. i'm glad you find a way to fix the problem. i'm still wondering why the inconsistent react-native versions will come out the `RCTDeviceEventEmitter.emit()` problem. would love to investigate further if you could help to have a repro example for us.

@nickwelp no log or expalanation are not good. could you elaborate more about your problem? e.g. does it happen on android or ios? is it development builds or expo go? do you use eas build, if so, could you share the eas build url like [this](https://expo.dev/accounts/kudochien/projects/sdk48/builds/b07e25f7-7e4f-422b-b599-2a9d88b687d4)?

**Comment by nickwelp** [comment]
We did manage to fix the issue. The issue was that following some advice somewhere else for rn/metro we had used resolutions to lock metro at 0.71.3. We deleted the resolutions section of our package.json and it appears all is working as intended. When I first started debugging the logs weren't helpful because the app built and looked like succesful logs, we did find the same output in the JS console that was posted in the first comment, leading us via Google to here.

**Comment by Kudo** [comment]
cool good to know thanks @nickwelp

**Pull request merged**
