### PR TITLE
[android][ios] Upgrade to react-native 0.68

### PR DESCRIPTION
**Pull request by Kudo**
# Why

targeting react-native 0.68 in sdk 45 even though it's rc now.

# How

- [x] upgrade package.json
- [x] migrate bare-expo
- [x] migrate expo-template-bare-minimum
- [x] migrate bare-sandbox

❗️ reanimated build error because our previous integration is broken on AGP 7. solution in [the pr](https://github.com/software-mansion/react-native-reanimated/pull/3113). since the pr is not landed yet, i have a [temporarily workaround to patch reanimated](https://github.com/expo/expo/pull/16532/commits/8e5662bec377ea11edc21ec6114c39f6580cb56a).

# Test Plan

- android bare-expo launch test
- ios bare-expo launch test

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] This diff will work correctly for `expo build` (eg: updated `@expo/xdl`).
- [x] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Comment by Kudo** [comment]
CLI CI failure because of the api server response code change. i am not going to fix it in the pr.
finally to get most ci green as i can. the pr is ready to review. if reviewing the whole changes at once is difficult, maybe checking commits one by one is easier.

**Review by tsapeta — APPROVED** [review]
I think you could have divided this PR for those three projects, but I'm fine as is. I'm not really happy that we have to put so much code just to support the new architecture though 😞

**Comment by AlexanderEggers** [comment]
@Kudo Just curious, instead of patching reanimated, wouldn't it make more sense to suggest that people should exclude that package for expo linking?

```
"expo": {
    "autolinking": {
      "exclude": [
        "react-native-reanimated"
      ]
    }
  },
```

Or is that in not possible/recommended in certain cases?

**Comment by Kudo** [comment]
@AlexanderEggers the broken part is from the code we added directly into reanimated's gradle file. i am afraid excluding reanimated from expo autolinking doesn't help. (at least, to build a release build, it doesn't work for me). the next version of reanimated should fix the problem. we also have a new approach for 3rd party libraries' integration, next time, exclude from autolinking will work.

**Comment by Kudo** [comment]
the pr easily get conflict with yarn.lock or Podfile.lock when we start to vendor 3rd party libraries and takes much time to wait for ci jobs ready. i am going to merge this pr. if there's any comments from post-review, i can address then.

**Comment by zxcvbnm3057** [comment]
So finally expo support new react native 0.68? Will this be able to work with new TurboModules and Hermes futures?

**Comment by tsapeta** [comment]
@zxcvbnm3057 Yes, Expo SDK45 will be based on React Native 0.68. We're not going to support the new architecture in this SDK yet, though. Mainly because it's not well-tested yet and there are just a few libraries that can make use of Fabric.

**Comment by zxcvbnm3057** [comment]
Thanks. The new architecture is ...... very complicated to use. Need a faster and easier tool chain for it.

**Pull request merged**
