### PR TITLE
[dev-launcher][splash-screen] Fix no native splash screen for dev-client integration

### LINKED ISSUE #14703: Expo Splash Screen throws error on release and dev client builds
### Summary

Appears to be a new issue with Expo SDK 43 beta, tried with and without `<AppLoading>`, keep getting the same error:

```
No native splash screen registered for given view controller. Call 'SplashScreen.show' for given view controller first.
at node_modules/react-native/Libraries/Utilities/RCTLog.js:34:8 in logIfNoNativeHook

[Unhandled promise rejection: Error: No native splash screen registered for given view controller. Call 'SplashScreen.show' for given view controller first.]
at node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:104:50 in promiseMethodWrapper
at node_modules/expo-modules-core/build/NativeModulesProxy.native.js:15:23 in moduleName.methodInfo.name
at node_modules/expo-splash-screen/build/SplashScreen.js:11:17 in preventAutoHideAsync
at node_modules/expo-splash-screen/build/SplashScreen.js:7:7 in preventAutoHideAsync
at node_modules/expo-app-loading/build/AppLoadingNativeWrapper.js:9:8 in AppLoading#constructor
at node_modules/@react-navigation/native/src/useThenable.tsx:26:18 in resolve

[Unhandled promise rejection: Error: No native splash screen registered for given view controller. Call 'SplashScreen.show' for given view controller first.]
at node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:104:50 in promiseMethodWrapper
at node_modules/expo-modules-core/build/NativeModulesProxy.native.js:15:23 in moduleName.methodInfo.name
at node_modules/expo-splash-screen/build/SplashScreen.js:23:17 in hideAsync
at node_modules/expo-splash-screen/build/SplashScreen.js:19:7 in hideAsync
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

43

### Environment

```
  Expo CLI 4.12.1 environment info:
    System:
      OS: macOS 11.6
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.11.0 - /opt/homebrew/bin/node
      npm: 8.0.0 - /opt/homebrew/bin/npm
      Watchman: 2021.10.04.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.0 - /Users/mark/.nix-profile/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7621141
      Xcode: 13.0/13A233 - /usr/bin/xcodebuild
    npmPackages:
      expo: next => 43.0.0-beta.3 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.2 => 0.64.2 
    npmGlobalPackages:
      expo-cli: 4.12.1
    Expo Workflow: managed
```

### Reproducible demo or steps to reproduce from a blank project

I have exactly this logic in my app: https://docs.expo.dev/versions/v43.0.0/sdk/splash-screen/#usage. Worked just fine on Expo SDK 42.

### PR DESCRIPTION
**Pull request by Kudo**
# Why

dev-client heavily relies on `devLauncherController:didStartWithSuccess:` to show splash screen. however, as we tried to decouple splash screen with other modules. we didn't call `showSplashScreenFor:` in sdk 43 dev-client config plugin. after dev-client loaded the app, splash screen has no chances to show.

fix #14703

# How

- for launch from home, the dev-launcher ui case, i further register rootViewController KVO and re-show splash again.
  with #14519, we didn't replace rootViewController but only rootView in expo-updates. considering dev-client still uses the `initializeReactNativeApp` style with rootViewController replacement. i should further support rootViewController KVO here.
- for launch from deeplink, just make the current window as keyWindow. so that splash-screen rootViewController KVO can re-show splash after rootViewController setup in `initializeReactNativeApp`.

# Test Plan

1. `EXPO_BETA=1 expo init sdk43`
2. `expo install expo-dev-client`
3. patch code in node_modules
4. `expo run:ios` # launch from deeplink
5. kill the app and click the app from home # launch from home
6. check if "No native splash screen registered for given view controller."  happens or not.

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] This diff will work correctly for `expo build` (eg: updated `@expo/xdl`).
- [x] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Comment by Kudo** [comment]
> Confirming that this should also fix it for `release` standalone builds in addition to `dev-client`?

did you mean `expo run:ios --configuration Release`? please help to describe more about the release standalone build.

**Review by bbarthec — COMMENTED** [review]
As I'm complete noob in terms of `expo-dev-launcher` code I summon @lukmccall to take a look at that part 🧙 
I think some explanation in the code is necessary as we're supporting two splash-screen flows now 🤔

**Review by lukmccall — APPROVED** [review]
LGTM 🚀 Thanks for taking care of the splash screen integration 🥇

**Comment by Kudo** [comment]
@pheuter i guess this is different to eas release build. well, i will test eas release build and let's follow up in #14703

**Review by bbarthec — APPROVED** [review]

**Comment by eeynard** [comment]
Hi ! Thank you for the fix 🙏🏻  I struggled with it for ages. Are you planning on a release soon with this fix ?

**Pull request merged**
