### PR TITLE
[docs] removed `facebookScheme` from docs since it's not available in SDK 48+

### PR DESCRIPTION
**Pull request by mrakesh0608**
# Why

Closes this #22026. Follow up #21018

# How

# Test Plan

# Checklist

- [X] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [X] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Review by amandeepmittal — APPROVED** [review]
Thank you!

**Comment by mrakesh0608** [comment]
@amandeepmittal can you please close this issue #22026 ?

**Comment by amandeepmittal** [comment]
@mrakesh0608 done!

**Comment by mrakesh0608** [comment]
@amandeepmittal Thanks 😊

**Pull request merged**
