### PR TITLE
Adds camera stabilization

### PR DESCRIPTION
**Pull request by n8**
Implements these RNCamera changes in Expo: https://github.com/react-native-community/react-native-camera/pull/1606/files

To support iOS camera stabilization

### CODE REVIEW

**Comment by tsapeta** [comment]
Thanks @n8 for your contribution, it looks good for me but I'd like @bbarthec to take a look at this as well 🙂

**Comment by n8** [comment]
Do you guys have any tips on manually testing Expo with an Expo app I created on the same computer?

In that app, I've given it an sdkVersion="UNVERSIONED" which I think I need to do. But then whats the best way of getting the new Expo SDK over to that other app. Is there a build process I run first in Expo? Or do I point the expo dependency in my app to somewhere in Expo? Like: 

```  "dependencies": {
    "expo": "file:something/something"
```

How do you all do this type of testing with an app?

**Comment by n8** [comment]
Also @tsapeta and @bbarthec I’m happy to pay some kind of bounty to help get this to production sooner. I’m at nate.kontny@gmail.com if you want to talk off channel some more about how I can help more here.

**Comment by bbarthec** [comment]
@n8 your PR is planned to be included in next sdk release.
cc @ide in terms of using this repository for testing new not-released features.

**Pull request merged**
