### PR TITLE
migrate parts of repo to expo cli

### PR DESCRIPTION
**Pull request by EvanBacon**
# Why

- React Native community CLI keeps breaking.

# How

- Move various scripts over to Expo CLI.

### CODE REVIEW

**Review by byCedric — APPROVED** [review]
👍

**Review by douglowder — APPROVED** [review]
Looks good -- we may want to have a look at making similar changes in the bare-minimum template (e.g. the bundling build phase in Xcode target).

**Comment by EvanBacon** [comment]
@douglowder [the bare template uses expo cli](https://github.com/expo/expo/pull/21396/)

**Comment by douglowder** [comment]
> the bare template uses Expo CLI

@EvanBacon that is true for the most part. I was thinking specifically of the "Bundle React Native code and images" build phase inside the Xcode project, which is using an internal shell script from the React Native core repo, and not using Expo CLI. But agreed, other parts of the template are using our CLI.

**Review by tsapeta — APPROVED** [review]

**Pull request merged**
