### PR TITLE
[expo-updates] fix: issue where launch screen wouldn't show

### PR DESCRIPTION
**Pull request by hannojg**
# Why

We encountered an issue where using 
- a custom dev client 
- expo-updates
- expo-splashscreen

caused our splash screen not to show up.

Watch this video:

https://user-images.githubusercontent.com/16821682/152138009-8dfc6030-cfff-4633-b0fa-4067b9a04bfc.mov

The green screen that you can see is the background color of the `RCTRootView`
<details>
  <summary>(this code part)</summary>
  
```objc
@implementation AppDelegate

- (RCTBridge *)initializeReactNativeApp
{
  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:self.launchOptions];
  RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge moduleName:@"main" initialProperties:nil];
  id rootViewBackgroundColor = [[NSBundle mainBundle] objectForInfoDictionaryKey:@"RCTRootViewBackgroundColor"];
  if (rootViewBackgroundColor != nil) {
    rootView.backgroundColor = [RCTConvert UIColor:rootViewBackgroundColor];
  } else {
    rootView.backgroundColor = [UIColor greenColor]; // <- ⚠️ The green flashing you can see in the video
  }
// ...
```
</details>

[As you can see the splash screen opens up for the first second but I think that's just the default native iOS launch screen configuration showing up, and the expo splashscreen that should be opened after that one isn't actually being opened.]

# How

Upon debugging I saw that in `EXUpdatesAppController` the rootViewController has been null (also has been null for the `ExSplashScreenService`, thus I guess it wasn't able to spawn the splash screen on its own).

The code I added adds a rootViewController and force shows it.

With these changes the splash screen is being opened after the native one:

https://user-images.githubusercontent.com/16821682/152139511-073afdc9-0a4f-42ab-a774-e19f12c8ee44.mov

# Test Plan

I have no clue how to test this properly. Also, I have no real native iOS development experience. I can't explain whether this is a lucky fix I found and should be applied totally different, or is just a hot patch for a problem going on elsewhere.

HOWEVER, there are several issues that point out that upon expo updates reloading the app there is just a white screen. The part that I changed to green is usually set to white. I think this fix could fix these issues as well.
Example issue: https://github.com/expo/expo/issues/13017

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] This diff will work correctly for `expo build` (eg: updated `@expo/xdl`).
- [ ] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Comment by esamelson** [comment]
Hi @hannojg -- thanks very much for the investigation and the fix. Before merging I'd like to consult with another team member who is offline until next week, so hang tight!

**Comment by Kudo** [comment]
hi there! thanks for the fix and long waiting. i would like to know more information and try to repro the issue locally.

- is the project a bare worlflow project?
- is it a release build (not debug build)?
- please help to share package versions of `expo`, `expo-dev-client`, `expo-updates`, and `expo-splash-screen`. you could run, e.g. `yarn why expo`
- please share your AppDelegate.m content if feasible. from the code snippet you shared, i'm assuming the project is not expo sdk 44 because it has `RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:self.launchOptions];` but not `RCTBridge *bridge = [self.reactDelegate createBridgeWithDelegate:self launchOptions:launchOptions];`

**Comment by hannojg** [comment]
@Kudo 

1. Yes, bare workflow, using expo dev client
2. Yes, that is a release build
3. 
```json
"expo": "^44.0.6",
"expo-application": "~4.0.2",
"expo-av": "~10.2.1",
"expo-constants": "~13.0.0",
"expo-dev-client": "~0.8.3",
"expo-device": "~4.1.0",
"expo-linear-gradient": "^11.0.2",
"expo-notifications": "~0.14.1",
"expo-splash-screen": "~0.14.2",
"expo-status-bar": "~1.2.0",
"expo-updates": "~0.11.6",
```
4. It is expo SDK 44. The thing is that I had to do the manual setup for expo updates to work on ios with our custom dev client. Otherwise, it never started pulling updates. So I was following this guide: https://docs.expo.dev/bare/installing-updates/#customizing-automatic-setup-for-ios

<details>
  <summary>Full AppDelegate.m</summary>
  
```objc
#import "AppDelegate.h"
#import <Firebase.h>
#import <FBSDKCoreKit/FBSDKCoreKit.h>
#import <RNGoogleSignin/RNGoogleSignin.h>

#import "SDImageCodersManager.h"
#import <SDWebImageWebPCoder/SDImageWebPCoder.h>

#if defined(EX_DEV_MENU_ENABLED)
@import EXDevMenu;
#endif

#if defined(EX_DEV_LAUNCHER_ENABLED)
#include <EXDevLauncher/EXDevLauncherController.h>
#import <EXUpdates/EXUpdatesDevLauncherController.h>
#endif

#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>
#import <React/RCTLinkingManager.h>
#import <React/RCTConvert.h>

#if defined(FB_SONARKIT_ENABLED) && __has_include(<FlipperKit/FlipperClient.h>)
#import <FlipperKit/FlipperClient.h>
#import <FlipperKitLayoutPlugin/FlipperKitLayoutPlugin.h>
#import <FlipperKitUserDefaultsPlugin/FKUserDefaultsPlugin.h>
#import <FlipperKitNetworkPlugin/FlipperKitNetworkPlugin.h>
#import <SKIOSNetworkPlugin/SKIOSNetworkAdapter.h>
#import <FlipperKitReactPlugin/FlipperKitReactPlugin.h>

static void InitializeFlipper(UIApplication *application) {
  FlipperClient *client = [FlipperClient sharedClient];
  SKDescriptorMapper *layoutDescriptorMapper = [[SKDescriptorMapper alloc] initWithDefaults];
  [client addPlugin:[[FlipperKitLayoutPlugin alloc] initWithRootNode:application withDescriptorMapper:layoutDescriptorMapper]];
  [client addPlugin:[[FKUserDefaultsPlugin alloc] initWithSuiteName:nil]];
  [client addPlugin:[FlipperKitReactPlugin new]];
  [client addPlugin:[[FlipperKitNetworkPlugin alloc] initWithNetworkAdapter:[SKIOSNetworkAdapter new]]];
  [client start];
}
#endif

@interface AppDelegate () <RCTBridgeDelegate>

@property (nonatomic, strong) NSDictionary *launchOptions;

@end

@implementation AppDelegate

- (RCTBridge *)initializeReactNativeApp
{
  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:self.launchOptions];
  RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge moduleName:@"main" initialProperties:nil];
  id rootViewBackgroundColor = [[NSBundle mainBundle] objectForInfoDictionaryKey:@"RCTRootViewBackgroundColor"];
  if (rootViewBackgroundColor != nil) {
    rootView.backgroundColor = [RCTConvert UIColor:rootViewBackgroundColor];
  } else {
    rootView.backgroundColor = [UIColor colorWithRed:3.0/255.0 green:4.0/255.0 blue:43.0/255.0 alpha:1.0];
  }

  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];

  return bridge;
}


- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
#if defined(FB_SONARKIT_ENABLED) && __has_include(<FlipperKit/FlipperClient.h>)
  InitializeFlipper(application);
#endif

  if ([FIRApp defaultApp] == nil) {
    [FIRApp configure];
  }

  [[FBSDKApplicationDelegate sharedInstance] application:application
                           didFinishLaunchingWithOptions:launchOptions];



  // Setup fast image to support webp images
  [SDImageCodersManager.sharedManager addCoder:SDImageWebPCoder.sharedCoder];

  self.launchOptions = launchOptions;
  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
#if defined(EX_DEV_LAUNCHER_ENABLED)
  EXDevLauncherController *controller = [EXDevLauncherController sharedInstance];
        controller.updatesInterface = [EXUpdatesDevLauncherController sharedInstance];
  [controller startWithWindow:self.window delegate:(id<EXDevLauncherControllerDelegate>)self launchOptions:launchOptions];
#else
  #ifdef DEBUG
    [self initializeReactNativeApp];
  #else
    EXUpdatesAppController *controller = [EXUpdatesAppController sharedInstance];
    controller.delegate = self;
    [controller startAndShowLaunchScreen:self.window];
  #endif
#endif

  [super application:application didFinishLaunchingWithOptions:launchOptions];

  return YES;
}

- (NSArray<id<RCTBridgeModule>> *)extraModulesForBridge:(RCTBridge *)bridge
{
  // If you'd like to export some custom RCTBridgeModules that are not Expo modules, add them here!
  return @[];
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge {
 #ifdef DEBUG
    #if defined(EX_DEV_LAUNCHER_ENABLED)
      return [[EXDevLauncherController sharedInstance] sourceUrl];
    #else
      return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
    #endif
 #else
  return [[EXUpdatesAppController sharedInstance] launchAssetUrl];
 #endif
}

- (void)appController:(EXUpdatesAppController *)appController didStartWithSuccess:(BOOL)success {
  appController.bridge = [self initializeReactNativeApp];
}

// Linking API
- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options {
  #if defined(EX_DEV_LAUNCHER_ENABLED)
  if ([EXDevLauncherController.sharedInstance onDeepLink:url options:options]) {
    return true;
  }
  #endif

  if ([[FBSDKApplicationDelegate sharedInstance] application:application openURL:url options:options]) {
    return YES;
  }

  if ([RNGoogleSignin application:application openURL:url options:options]) {
    return YES;
  }

  return [RCTLinkingManager application:application openURL:url options:options];
}

// Universal Links
- (BOOL)application:(UIApplication *)application continueUserActivity:(nonnull NSUserActivity *)userActivity restorationHandler:(nonnull void (^)(NSArray<id<UIUserActivityRestoring>> * _Nullable))restorationHandler {
  return [RCTLinkingManager application:application
                   continueUserActivity:userActivity
                     restorationHandler:restorationHandler];
}

@end

#if defined(EX_DEV_LAUNCHER_ENABLED)
@implementation AppDelegate (EXDevLauncherControllerDelegate)

- (void)devLauncherController:(EXDevLauncherController *)developmentClientController
    didStartWithSuccess:(BOOL)success
{
  self.launchOptions = [EXDevLauncherController.sharedInstance getLaunchOptions];
  developmentClientController.appBridge = [self initializeReactNativeApp];
}

@end
#endif

```
</details>

**Comment by Kudo** [comment]
@hannojg the information to have manual setup is super helpful. i can repro and confirm it's a regression issue when i tried to decouple expo-updates and expo-splash-screen. the solution makes sense to me, too.

there's just one remaining thing. please help us to add a [changelog](https://github.com/expo/expo/blob/main/packages/expo-updates/CHANGELOG.md) item under bug fixes section.

**Comment by hannojg** [comment]
Added the changelog entry, not sure if it's correct (first time contributing to expo), feel free to correct if I messed up 😅 👍

**Review by Kudo — APPROVED** [review]
the changelog LGTM! thanks for your fix. even that's a first time pr, it's great 🔥

**Review by esamelson — APPROVED** [review]

**Pull request merged**
