### PR TITLE
[android][sharing] Fix shareAsync not resolving

### LINKED ISSUE #21418: expo-share shareAsync not resolving and causing issues
### Minimal reproducible example

https://github.com/RehmatFalcon/mr-expo-sharing-bug

### Summary

When we migrated to sdk48, we faced some issues regarding the sharing

The call Sharing.shareAsync never resolves. This means that the codes after it does not run. This also means that we cannot perform another share. It says that a share is in progress.

image

The reproduction example shows it.

When you press the `Share` button for the first time, only the before console.logs are performed. The console.log("After sharing") is never called. 
When you press the `Share` button again, it says that a share is already in progress.

This code used to work in previous versions.

Are we doing something wrong? Or is there a breaking change documented that we missed?

Facing the issue for android apps. Have not yet tested on ios

This works for expo sdk 47.

https://snack.expo.dev/@upretymadan45/sharing

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 5.19 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
      Shell: Unknown
    Binaries:
      Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.16.0/bin/yarn
      npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
    npmPackages:
      expo: ~48.0.4 => 48.0.4 
      react: 18.2.0 => 18.2.0 
      react-native: 0.71.3 => 0.71.3 
    npmGlobalPackages:
      eas-cli: 2.6.0
      expo-cli: 6.3.2
    Expo Workflow: managed

### PR DESCRIPTION
**Pull request by alanjhughes**
# Why
Closes #21418

# How
# Test Plan
Tested in the bare expo app

### CODE REVIEW

**Review by Kudo — APPROVED** [review]
nice fix, thanks @alanjhughes !

**Comment by fobos531** [comment]
Hey @Kudo , is it possible for you to publish a new version of `expo-sharing` to NPM with this fix applied?

**Comment by Kudo** [comment]
published expo-sharing@11.2.2

**Comment by axelmy318** [comment]
I am using expo-sharing@11.2.2 but it is still not fixed... It works on IOS but not on android devices

```javascript
const exportAsPDF = async() => {
        const html = exportArticleListAsPDF(data)

        const file = await printToFileAsync({
            html: html,
            base64: false,
            width: 2480,
            height: 3508 
        })
        
        await shareAsync(file.uri)
}
```

**Comment by alanjhughes** [comment]
I don't think this change has been published yet

**Comment by axelmy318** [comment]
> I don't think this change has been published yet

I figured is was based on this comment...

> published expo-sharing@11.2.2

I even went and checked inside my node_modules folder to see if the changes were there, which is the case but the issue still persist

**Comment by alanjhughes** [comment]
Sorry, missed the messages above. Did you rebuild your app after updating?

**Comment by axelmy318** [comment]
Yes. I actually started using the package after @Kudo 's reply

**Comment by alanjhughes** [comment]
@axelmy318  I just tried it. Seems to be an issue in expo go only. If you build a dev client it works as expected

**Pull request merged**
