### PR TITLE
[android][audio] set playThroughEarpieceAndroid default to false

### LINKED ISSUE #8465: setAudioModeAsync with partial options changes audio sink
### Environment

  Expo CLI 3.13.8 environment info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.2 LTS (Bionic Beaver)
      Shell: 4.4.19 - /bin/bash
    Binaries:
      Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
      Yarn: 1.22.1 - ~/.nvm/versions/node/v12.16.1/bin/yarn
      npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
    npmPackages:
      expo: ~37.0.3 => 37.0.12 
      react: ~16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4 
    npmGlobalPackages:
      expo-cli: 3.13.8

Target: Android

### Steps to Reproduce

On Android, when using `setAudioModeAsync` with a partial set of values

```
  Audio.setAudioModeAsync({
    playsInSilentModeIOS: false
    , allowsRecordingIOS: false
  }
```

the audio is set to "in-call" and the audio goes to the internal speaker, instead of the speaker.

### Expected Behavior
Setting `playsInSilentModeIOS` and `allowsRecordingIOS` options with `setAudioModeAsync` does not change the audio sink.

### Actual Behavior
Audio sink is set to the internal speaker as opposed to staying on the speaker.

### Reproducible Demo

I put together [this sample app](https://github.com/vgrocha/ExpoAndroidInCallBug), which a bare `expo init` with a Button that `setAudioModeAsync` with the options above.

Before pressing the  `Bug It` button, when changing the volume, it correctly changes the volume:

After pressing the `Bug It` button, when changing volume, sound becomes "In-Call" (and if you play a sound, it goes to the internal speaker):

### PR DESCRIPTION
**Pull request by vgrocha**
# Why

Fix https://github.com/expo/expo/issues/8465

# How

Changed default value to `false`  and updates documentation.

# Test Plan
Built `packages/expo-av` with `yarn build`

### CODE REVIEW

**Review by bbarthec — COMMENTED** [review]
It looks good to me, but I'll let @byCedric take care of it 💪

**Comment by byCedric** [comment]
Hi @vgrocha! Sorry for the delay! Looks good to me too 😄 Thanks for the review @bbarthec! There is one thing though that might be a bit weird, I see `react-native-unimodules` is added to the lock file. Could you rebase this on the latest master and use that one? I don't think we have to modify the lock file for this change 😄 

Thanks for the PR!

**Comment by vgrocha** [comment]
Cool! I updated it to remove the yarn.lock changes :)

**Comment by byCedric** [comment]
Awesome, LGTM! 😄

**Review by byCedric — APPROVED** [review]

**Pull request merged**
