### PR TITLE
[camera] Fix barcodeTypes prop in types and in Swift

### PR DESCRIPTION
**Pull request by byudaniel**
# Why

Android was not receiving the barCodeTypes prop, so when scanning barcodes it was scanning for every type of barcode.

# How

I fixed the casing on the prop to be consistent with iOS and the docs.

# Test Plan

Tested manually with Galaxy 21 and S22 Ultra to ensure it only picked up the specified barcode type.

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [x] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Comment by alanjhughes** [comment]
Hi @byudaniel - The name of the prop is correct, `barcodeTypes` is what is should be. If you are passing `barCodeTypes` from javascript it will not work

**Comment by byudaniel** [comment]
> Hi @byudaniel - The name of the prop is correct, `barcodeTypes` is what is should be. If you are passing `barCodeTypes` from javascript it will not work

If you do a case search in `./packages/expo-camera` the only place it is `barcodeTypes` is within `packages/expo-camera/android/src/main/java/expo/modules/camera/next/ExpoCameraView.kt` and `packages/expo-camera/android/src/main/java/expo/modules/camera/next/records/CameraRecords.kt`. Before this change it worked properly with `barcodeTypes` on `iOS`, but not on Android.

**Comment by alanjhughes** [comment]
@byudaniel - yes so the correct fix is to fix the casing on the Typescript type

**Comment by byudaniel** [comment]
@alanjhughes - OK, so I'll update the PR to update the Swift code and the types and revert the changes to the Kotlin files.

**Comment by alanjhughes** [comment]
@byudaniel - yes, that'd be great!

**Comment by alanjhughes** [comment]
@byudaniel - looking good. Have you checked that everything is working correctly on the `CameraScreenNext` example?

**Comment by alanjhughes** [comment]
@byudaniel the example screen isn't using the correct name now.

**Comment by byudaniel** [comment]
@alanjhughes  I confirmed that it is working in `CameraScreenNext.tsx` with an Android and an iOS device. I also updated the `barcodeTypes` property to the right casing in that file.

**Review by alanjhughes — APPROVED** [review]
Great! Thank you for your contribution! 👍

**Pull request merged**
