### PR TITLE
Extract react-native-web color utility into linear gradient

### LINKED ISSUE #9999: [expo-linear-gradient] imports react-native-web/src directly
### Summary of Issue 
when trying to build with webpack something that use expo-linear-gradient you get an error, as expo-linear-gradient imports normalizeColor directly from react-native-web/src which is in typescript.

see line 3 in this file:
https://github.com/expo/expo/blob/master/packages/expo-linear-gradient/src/NativeLinearGradient.web.tsx

this is the webpack error:

```
Failed to compile.
.../node_modules/react-native-web/src/modules/normalizeColor/index.js: Unexpected token (13:30)
  11 | import processColor from '../../exports/processColor';
  12 | 
> 13 | const normalizeColor = (color?: number | string, opacity?: number = 1) => {
     |                               ^
  14 |   if (color == null) return;
  15 | 
  16 |   if (typeof color === 'string' && isWebColor(color)) {
```

### Expected Behavior vs Actual Behavior
the module should import things from react-native-web/dist (or even only react-native-web if possible) instead of from react-native-web/src.

### PR DESCRIPTION
**Pull request by EvanBacon**
# Why

Fix https://github.com/expo/expo/issues/9999

# How

Extract method into linear gradient.

# Test Plan

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] This diff will work correctly for `expo build` (eg: updated `@expo/xdl`).
- [ ] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Review by Simek — APPROVED** [review]
LGTM, this should help with few issues, thanks!

**Comment by Simek** [comment]
Also superseeds #15245

**Review by brentvatne — APPROVED** [review]

**Comment by EvanBacon** [comment]
I don't think this is published yet (publishing out of cycle is pretty tricky, we're working on improving this), you can apply the changes locally using `patch-package` with https://patch-diff.githubusercontent.com/raw/expo/expo/pull/16098.patch to apply the change locally in the meantime (add `.patch` to the end of the PR URL).

**Comment by SkySails** [comment]
Got it, I will do that until the next release. Thank you for the tip!

**Pull request merged**
