### PR TITLE
[go] update lottie-react-native to 6.2.0

### PR DESCRIPTION
**Pull request by matinzd**
# Why

Release link: 

https://github.com/lottie-react-native/lottie-react-native/releases/tag/v6.2.0

# How

- Ran `et uvm -m lottie-react-native -c 6.2.0 -p all`

# Test Plan

- [x] Lottie React Native should work as expected in Expo Go

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [x] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Comment by brentvatne** [comment]
hey there! fyi we update vendored modules once every sdk release. we can land changes like this and appreciate you sending them, but just to set expectations - this won't be available until sdk 50

**Comment by matinzd** [comment]
> hey there! fyi we update vendored modules once every sdk release. we can land changes like this and appreciate you sending them, but just to set expectations - this won't be available until sdk 50

Ok thanks. I'll convert this to draft so that we can merge it later for next release. 
Unfortunately this fix is needed for crash on release mode but if it's not totally possible that's ok with me as well. Let's stick to the plan :)

**Comment by brentvatne** [comment]
@matinzd - if you're able to backport that fix to a patch version for the [version of lottie used in sdk 49](https://github.com/expo/expo/blob/sdk-49/packages/expo/bundledNativeModules.json#L84) we can patch it and ship that! but we avoid shipping any breaking changes to a package already included in an sdk release unless absolutely necessary

**Comment by brentvatne** [comment]
we'll be including the latest version in sdk 50, hope to have the beta out this month :)

**Comment by matinzd** [comment]
> we'll be including the latest version in sdk 50, hope to have the beta out this month :)

Thanks! Please go with the latest version.

**Pull request closed without merging**
