### PR TITLE
[templates] Add missing react test render and upgrade jest

### LINKED ISSUE #14991: Test fails on fresh project with tabs template (Cannot find module 'react-test-renderer')
### Summary

Tests fail on a fresh project with the tabs template. Error message: `Cannot find module 'react-test-renderer' from 'components/__tests__/StyledText-test.js'`

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS, Web

### SDK Version (managed workflow only)

SDK 43

### Environment

```
  Expo CLI 4.12.10 environment info:
    System:
      OS: Linux 5.14 Manjaro Linux
      Shell: 5.1.8 - /bin/bash
    Binaries:
      Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
      npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
    IDEs:
      Android Studio: AI-203.7717.56.2031.7784292
    npmPackages:
      expo: ~43.0.0 => 43.0.1 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.2 => 0.64.2 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 4.12.10
    Expo Workflow: managed
```

### Reproducible demo or steps to reproduce from a blank project

```
expo init --template tabs foo
cd foo
npm test
```

### PR DESCRIPTION
**Pull request by byCedric**
# Why

Fixes #14991 

Although I did not commit the snapshot, maybe we should?

# How

- Added `react-test-render@17.0.1` as dev dependency
- Upgraded `jest-expo@43.0.1`

# Test Plan

- `$ cd templates/expo-template-tabs`
- `$ yarn`
- `$ yarn test`
- _Should pass_

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] This diff will work correctly for `expo build` (eg: updated `@expo/xdl`).
- [ ] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Review by brentvatne — APPROVED** [review]
no need to commit snapshot

**Review by Simek — CHANGES_REQUESTED** [review]
Can you also update the `expo-template-bare-minimum` package.json and add `react-test-renderer` in the dev dependencies in there?

It looks like the renderer it also used in test example in this template, but renderer is missing in dependencies:
* https://github.com/expo/expo/blob/master/templates/expo-template-bare-minimum/__tests__/App.js#L6

**Comment by byCedric** [comment]
> Can you also update the `expo-template-bare-minimum` package.json and add `react-test-renderer` in the dev dependencies in there?
> 
> It looks like the renderer it also used in test example in this template, but renderer is missing in dependencies:
> 
> * https://github.com/expo/expo/blob/master/templates/expo-template-bare-minimum/__tests__/App.js#L6

@Simek I see that we don't even install jest in the bare minimum. I think just removing the test would be a better solution here. (cc @brentvatne)

**Comment by Simek** [comment]
> @Simek I see that we don't even install jest in the bare minimum. I think just removing the test would be a better solution here. (cc @brentvatne)

Ohh, hmm, maybe removing tests from this template is a right call. 😉 

Now I'm curious how does it work earlier or maybe those tests were added in latest RN bump?

**Comment by byCedric** [comment]
They have [the same test](https://github.com/facebook/react-native/blob/main/template/__tests__/App-test.js), [jest installed (+ test script)](https://github.com/facebook/react-native/blob/main/template/package.json#L22), and include eslint

**Comment by byCedric** [comment]
Thanks for the help @Simek!

**Pull request merged**
