### PR TITLE
Remove admob, amplitude, branch, facebook-ads, facebook, google-sign-in, segment

### PR DESCRIPTION
**Pull request by brentvatne**
# Why

[These were deprecated in SDK 45](https://blog.expo.dev/expo-sdk-45-f4e332954a68).

Note that I wasn't actually able to delete the packages for amplitude and branch yet. For amplitude, we still depend on it in home. For branch, it seems that older versioned branch pods depend on EXBranch (I didn't look into this further, just un-deleted).

Closes ENG-5653

# How

- Remove docs for all modules (from unversioned and SDK 46)
- Remove NCL screens for all modules
- Remove test-suite tests for all modules
- Remove most modules from bundledNativeModules
- Delete most modules

# Test Plan

Let CI run

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] This diff will work correctly for `expo build` (eg: updated `@expo/xdl`).
- [x] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Comment by brentvatne** [comment]
Looks like CI failure is just the docs OOM issue.

One other thought occurred to me about this PR though - maybe we should leave the README around for these packages and add a note that they are now deleted. Old docs versions point to the README for bare workflow installation. If you agree, let me know and I'll add that back.

**Comment by Simek** [comment]
Can you also ensure that you have removed the `static` files from docs related to those pages (like API data JSON, diffs or images)?

I can also see the benefits of leaving the removed packages Readme files for a while in repository, I think that it is a good idea.

**Comment by Simek** [comment]
Please also remove the packages entries from docs data generation script in Tools:
* https://github.com/expo/expo/blob/main/tools/src/commands/GenerateDocsAPIData.ts

**Review by tsapeta — APPROVED** [review]

**Review by Kudo — APPROVED** [review]

**Comment by brentvatne** [comment]
@Simek - I think I covered everything from the docs, thanks for the heads up

@Kudo - good idea, I moved the source code to those separate packages!

**Pull request merged**
