### PR TITLE
[camera] Add missing mute property

### PR DESCRIPTION
**Pull request by wcandillon**
# Why

Add missing mute property as documented at https://docs.expo.io/versions/latest/sdk/camera/#recordasync

### CODE REVIEW

**Comment by cruzach** [comment]
```
The following build files need to be rebuilt and committed:
build/Camera.types.d.ts
build/Camera.types.js.map
```
Can you rebuild the `expo-camera` package with `yarn build`? That should fix the sdk CI check

**Review by bbarthec — CHANGES_REQUESTED** [review]
Thank @wcandillon for your contribution 💯🎉 Apart from ensuring package is build correctly, please add entry in CHANGELOG according to the style you'll find in it 😊

**Comment by wcandillon** [comment]
is npx required in order to build the package? I have never used it

**Comment by bbarthec** [comment]
@wcandillon, all you need to do is:
- navigate to appropriate package directory (in this case `packages/expo-camera`
- run `yarn build`

**Comment by wcandillon** [comment]
Thanks @bbarthec! The build still seem to be failing however.

**Comment by bbarthec** [comment]
@wcandillon I'm going to take care of this PR and fix anything that is broken directly directly on master 😉

**Pull request merged**
