### PR TITLE
[expo] Improve the "Expo SDK requires Expo" to run confusing message

### PR DESCRIPTION
**Pull request by brentvatne**
# Why

> The Expo SDK requires Expo to run. It appears the native Expo modules are unavailable and this code is not running on Expo. Visit https://docs.expo.io to learn more about developing an Expo project.

This error message is very confusing. It makes a bit more sense in a world where it might show up if you install the `expo` package in a bare React Native app and try to import from it, but now you will never actually reach this code in that context because it's only executed when the bundler supports the `.expo` file extension. And yet somehow users end up here, I think only on Android. I don't know how or why, but I would like them to try to explain it to us. It seems [possibly related to network connectivity](https://twitter.com/workingcactus/status/1307062933378215942), but it's unclear to me why that would impact the availability of the `Constants` native module.

Regardless, the error message should cause less confusion rather than more, even if we can't exactly help them.

# How

Changed it to:

> Expo native runtime is not available: something went wrong and we aren't sure what it was. Please post more information and get support at https://forums.expo.io.

### CODE REVIEW

**Comment by ide** [comment]
Should we just remove the whole file?

**Comment by brentvatne** [comment]
possibly. i'm not sure what errors developers would encounter if the app loads but expo native modules aren't available. but perhaps best to remove this and find out

**Review by ide — APPROVED** [review]

**Comment by buzali** [comment]
We stumbled upon this error while making an OTA update to a bare workflow app in SDK 39. The app works when built in XCode but instatly crashes with this error after an OTA update.

Details here: https://forums.expo.io/t/unable-to-publish-ota-updates-in-expo-bare-app/38690/9?u=fragmnt02

Is this a bug or an expected behaviour?

**Comment by brentvatne** [comment]
when you run `expo publish` with a recent version of expo-cli from a bare project it will automatically set the target to "bare" which results in excluding any `.expo.js` files. this means that the file with this error message would not be included in your bundle. you can see the target when you run the publish command:

```
╭─~/code/brentapp ‹master›
╰─$ expo publish

- Release channel: default
- Workflow: Bare
```

if you publish from a branch where you haven't ejected and see `Workflow: managed` on running the command then it will not be compatible with your binary. i don't know exactly what happened in your case but i suspect something like this

**Pull request merged**
