### PR TITLE
chore: update `body-parser`

### PR DESCRIPTION
**Pull request by SimenB**
# Why

1.19.x pulls in quite a bit of old deps

# How

Editing file and running `yarn`. Also updated the `express` version here so it pulls in the same version of `body-parser`

# Test Plan

Not sure. It should work perfectly fine

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Review by EvanBacon — APPROVED** [review]

**Comment by alxpub** [comment]
This update has been reset to 1.19.0 again
And now have vulnerability via qs
`qs vulnerable to Prototype Pollution`
https://github.com/advisories/GHSA-hrpp-h998-j3pp
Need to update again..

**Comment by karlhorky** [comment]
@tsapeta your commit https://github.com/expo/expo/commit/ccda6f1a6a29edca74ba7436a506b0c4a9c77bd2#diff-42fb32ae1ead30e5a4051488f4260b02932fd002e9bcc979fd096fb4f77ddbc7 reverted the changes in this PR.

What do you think about bumping `body-parser` to `1.20.1`? (now that there is a patch fix for the `qs` vulnerability)

**Comment by tsapeta** [comment]
Hi! Sorry for my mistake, that was the script that brought back 1.19.0 version, I'm not really sure why so I'm gonna investigate that further 🤔
I just bumped the dependency on `body-parser` to `^1.20.1` and released `expo@47.0.10` with that change 🙂

**Comment by karlhorky** [comment]
Thanks!

**Comment by karlhorky** [comment]
True, just tried it out, and found this out too 😬 @tsapeta Would it be possible to get this bumped in `@expo/cli` and `@expo/dev-server`?

**Comment by tsapeta** [comment]
I'm sorry, it was bumped in `@expo/dev-server` but `@expo/cli` still used the old dev server.
I just fixed that, let's try with `expo@47.0.11` 😉

**Comment by karlhorky** [comment]
Thanks, new releases look good! 🙌

**Pull request merged**
