### PR TITLE
[expo-calendar] fix relativeOffSet type avoid crash with createEventAsync function

### PR DESCRIPTION
**Pull request by vivianzzhu91**
# Why

During the process of reproducing issues of https://github.com/expo/expo/issues/5010 and https://github.com/expo/expo/issues/2449 and another comment https://github.com/expo/expo/pull/4905#issuecomment-515701947, I found that my app would crash if I call `createEventAsync` with attribute `relativeOffset`.

# How

I looked into Android Studio Logcat and found the same error with https://stackoverflow.com/questions/56821645/calendar-createeventasync-crashes-on-android-only-expo. 

```
java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.Integer
       at expo.modules.calendar.CalendarModule.createRemindersForEvent(CalendarModule.java:869)
       at expo.modules.calendar.CalendarModule.saveEvent(CalendarModule.java:751)
       at expo.modules.calendar.CalendarModule.access$500(CalendarModule.java:34)
       at expo.modules.calendar.CalendarModule$6.run(CalendarModule.java:161)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:257)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:784)” 
```

So it seemed like `relativeOffset ` is a double but the code tries to cast it into an Integer with `(int)`, so I rewrite the casting into `.intValue()`.

# Test Plan

I used this snack: https://snack.expo.io/@appleckp/0a1707 to reproduce the problem and try to add events with negative `relativeOffset` value and it worked without crashing the app. And now we are able to set a reminder without crashing.

Screen Shot 2019-07-31 at 5 41 34 PM

### CODE REVIEW

**Comment by vinagrito** [comment]
👍 👍

**Comment by vinagrito** [comment]
@vivianzzhu91 
Running your snack on my device actually crashed the app... 😬 what might I be missing?

**Comment by vivianzzhu91** [comment]
My PR is still open and not merged to master yet, so the code on snack has not been fixed yet. You could try and test it after this pr is merged.

**Comment by vinagrito** [comment]
gotcha

**Review by esamelson — COMMENTED** [review]
thanks for fixing! i'm not sure why there are changes to the expo package in this PR, so could you revert those? also, if you could add an entry to the CHANGELOG for this, that would be great.

**Comment by esamelson** [comment]
@vinagrito this bugfix will likely be released in SDK 35.

**Review by esamelson — APPROVED** [review]

**Comment by davidli3100** [comment]
installed this package today. Still doesn't seem to work, should I reinstall/update the main expo package as well?

**Pull request merged**
