### PR TITLE
[bare-expo][ios] Add flipper support

### PR DESCRIPTION
**Pull request by lukmccall**
# Why

I was checking if the flipper will work with the `dev-client`. To do that I had to add flipper support into the bare-expo project. Also, I think this's a nice addition to our project. 

# How

- Follow the installation guide - https://fbflipper.com/docs/getting-started/react-native-ios
- Add `-DFB_SONARKIT_ENABLED` into swift compiler flags - this should be added automatically via the flipper package, but for some reason, it doesn't work in swift files.

> **Note:** I didn't touch Android yet, but I'll add support for the flipper in the separate PR.

# Test Plan

- tested with `bare-expo`
Screenshot 2020-10-20 at 14 31 23

# Important files (for reviewers) 

- apps/bare-expo/ios/BareExpo/AppDelegate.swift
- apps/bare-expo/ios/Podfile
- https://github.com/expo/expo/blob/bbcf58c514e6b43bfc521cfdacd892a54917385c/apps/bare-expo/ios/BareExpo.xcodeproj/project.pbxproj#L516 - adding `DFB_SONARKIT_ENABLED`

### CODE REVIEW

**Review by sjchmiela — APPROVED** [review]
If it works! LGTM! 👍

**Comment by IjzerenHein** [comment]
@lukmccall It seems that this PR is causing `pod install` to fail in bare-expo. It only happens when `pod install` makes no changes to the `Pods` directory because of incremental installation. I've investigated and documented the problem here:
https://github.com/expo/expo/pull/10812#issuecomment-717114590

This is currently causing `et publish` to fail and prevents us from publishing package updates. @brentvatne 

Can you take a look at this? We might want to disable/revert this for now until we have a solution.

**Comment by lukmccall** [comment]
I'm working on it 😅

**Comment by IjzerenHein** [comment]
Awesome =D

**Pull request merged**
