### PR TITLE
[template] fix hermes simulator build error on m1

### PR DESCRIPTION
**Pull request by Kudo**
# Why

this is a known issue for react-native 0.64 + hermes https://github.com/facebook/hermes/issues/468. i think we can workaround this in sdk 43.

# How

force to use x86_64 arch for simulator build.

# Test Plan

```sh
# on m1 mac
$ expo init -t /path/to/expo/expo/templates/expo-template-bare-minimum sdk43
# add "jsEngine: "hermes" to app.json
$ expo run:ios
```

# Checklist

- n/a Documentation is up to date to reflect these changes (eg: https://docs.expo.io and README.md).
- [x] This diff will work correctly for `expo build` (eg: updated `@expo/xdl`).
- [x] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Review by brentvatne — APPROVED** [review]

**Review by tsapeta — APPROVED** [review]

**Comment by smn-snkl** [comment]
@Kudo is there a way to use this in a managed project? I don't want to manually modify the `Podfile` so I can stay in the managed workflow.

**Comment by brentvatne** [comment]
@smn-snkl - can you clarify your use case? are you trying use `expo run:ios` on a managed project on an m1 mac?

**Comment by smn-snkl** [comment]
@brentvatne exactly. I’m running a managed project with Hermes turned on on a M1 and I’d like to use the dev-client instead of Expo Go. But the `expo run:ios` command fails because of the arm64 issue tackled here.

**Comment by brentvatne** [comment]
@smn-snkl - you could add a config plugin that modifies your Podfile to add the block from https://github.com/expo/expo/commit/0b9b3223c213e2d8e637136d4df63ba45ab8a5fe.

or you can do it manually - run `expo prebuild -p ios` and then add the block manually to your Podfile, then run `npx pod-install` and then `expo run:ios`

you could also run your dev-client build on eas build then download it locally

**Comment by smn-snkl** [comment]
@brentvatne Thanks! Just to make sure:
In cases 1 (plugin) and 3 (eas build) I can stay within the managed workflow, but case 2 (prebuild) I’d either leave the managed workflow or have to reapply the change everytime I want to create a new prebuild, right?

**Comment by brentvatne** [comment]
if you don't commit your ios and android directories to git and you don't modify them directly then you can consider that managed workflow. running `expo prebuild` is done automatically when you run `expo run:ios`. it's also done on eas build in order to produce your build.

**Comment by brentvatne** [comment]
more info on cleaning up after prebuild, if you want to: https://expo.fyi/prebuild-cleanup

**Pull request closed without merging**
