### PR TITLE
Feat/add drm

### PR DESCRIPTION
**Pull request by onizam95**
# Why
To provide DRM support in expo-av 
it supports WIDEVINE for Android
And Fairplay for ios
Inspired from this discussion thread: https://github.com/expo/expo/discussions/19807 

# How
I have updated the native android and ios files to provide drm support if drm configs are passed. 
the drm configs can be passed in the headers and key value object of source. 
Here are the example configs
for Android: 
`source={uri: 'https://media.axprod.net/TestVectors/v7-MultiDRM-SingleKey/Manifest_1080p.mpd', headers: {drm : {type: 'widevine', licenseServer: 'https://drm-widevine-licensing.axtest.net/AcquireLicense', drmHeaders: {
              'X-AxDRM-Message': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ2ZXJzaW9uIjoxLCJjb21fa2V5X2lkIjoiYjMzNjRlYjUtNTFmNi00YWUzLThjOTgtMzNjZWQ1ZTMxYzc4IiwibWVzc2FnZSI6eyJ0eXBlIjoiZW50aXRsZW1lbnRfbWVzc2FnZSIsImZpcnN0X3BsYXlfZXhwaXJhdGlvbiI6NjAsInBsYXlyZWFkeSI6eyJyZWFsX3RpbWVfZXhwaXJhdGlvbiI6dHJ1ZX0sImtleXMiOlt7ImlkIjoiOWViNDA1MGQtZTQ0Yi00ODAyLTkzMmUtMjdkNzUwODNlMjY2IiwiZW5jcnlwdGVkX2tleSI6ImxLM09qSExZVzI0Y3Iya3RSNzRmbnc9PSJ9XX19.FAbIiPxX8BHi9RwfzD7Yn-wugU19ghrkBFKsaCPrZmU'
            }}}}`
            
 For IOS
 `source=       {uri: '', headers: {drm : {type: 'fairplay', licenseServer: '', certificateUrl: '', base64Cert: false }}}
`

For Android
Just the `SimpleExoPlayerData.java` class is changed and if drm configs exists the mediaSource build function is modified. 

SImilarly for IOS
`EXAVPlayerData.m` file is modified and a resourceLoader delegate class is added to handle the drm support
# Test Plan

To Test this I cloned the expo sdk and passed the above mentioned sources in VideoPlayer files in apps/native-components-list 
tested them with both DRM encrypted and non encrypted data streams. 

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Comment by dgocoder** [comment]
this would be great to add. We have had to use react native video instead of expo av due to this

**Comment by JustJoostNL** [comment]
Same here, can't wait!

**Comment by onizam95** [comment]
Due to a very silly mistake. This repo history is messed up. I will create new PR and post the link here Thank you.

**Comment by onizam95** [comment]
updated PR link 
https://github.com/expo/expo/pull/26433

**Pull request closed without merging**
