### PR TITLE
[linking] isExpoHosted was returning false when running EAS updates in Expo Go

### PR DESCRIPTION
**Pull request by confraria**
# Why

When running eas updates in expo go `isExpoHosted` was returning false.
This was causing a crash after logging in with Google using `expo-auth-session` with the Expo authentication proxy and default redirect URI.

# How

Added the eas updates domain to the regex.

# Test Plan
Using expo-auth-session, before the patch the redirect URI that was being passed to the login URL was: `exp://u.expo.dev/update/07bf1d3-8810-4857-9d49-f6971fb2118expo-auth-session` and after the patch the redirect URI looks like `exp://u.expo.dev/update/07bf1d3-8810-4857-9d49-f6971fb2118/--/expo-auth-session` and everything works correctly.

### CODE REVIEW

**Comment by confraria** [comment]
@keith-kurak here is is the PR we discussed. The existing unit tests are passing, but you may want to add some more.

**Review by jonsamp — APPROVED** [review]
Thanks for submitting this PR with the fix! Would love to get a +1 from one of the other reviewers before merging.

**Review by tsapeta — APPROVED** [review]
Looks good to me, thanks for your contribution 🙏

**Comment by simoneb** [comment]
Thanks all. As we're waiting for this to be released so we can remove the workaround we have in our project [here](https://github.com/nearform/optic-expo/blob/master/package.json#L20), is there a way to know when this change will be included in a future release @tsapeta @jonsamp ?

**Pull request merged**
