### PR TITLE
[bare-expo][camera] integrate autolinking aar project

### PR DESCRIPTION
**Pull request by Kudo**
# Why

integrate aar autolinking from #30706 to expo-camera which original use a config-plugin to add local maven dependency.
close ENG-12425

# How

- [bare-expo] remove pulled expo-camera maven repo
- [camera] remove config-plugin code to add maven repo
- [camera] migrate to aar autolinking

# Test Plan

bare-expo should build as-is.

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [x] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Comment by Kudo** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/expo/expo/30707?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#30707** <a href="https://app.graphite.dev/github/pr/expo/expo/30707?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#30706** <a href="https://app.graphite.dev/github/pr/expo/expo/30706?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @Kudo and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by alanjhughes — APPROVED** [review]

**Review by lukmccall — APPROVED** [review]

**Comment by Kudo** [comment]
### Merge activity

* **Jul 31, 12:41 AM EDT**: @Kudo started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/expo/expo/30707).

**Comment by efstathiosntonas** [comment]
@Kudo Hi, I'm using cli with expo-modules-core. After upgrading to rn@0.76 and expo@52.preview.2 the expo-camera@16 module fails to install on Android (I build rn from source if that matters)

On my `build.gradle`:

```gradle
allprojects {
    repositories {
        google()
        mavenCentral()
        maven {
            // expo-camera bundles a custom com.google.android:cameraview
            url "$rootDir/../node_modules/expo-camera/android/maven"
        }
        maven {
            url 'https://api.mapbox.com/downloads/v2/releases/maven'
            authentication {
                basic(BasicAuthentication)
            }
            credentials {
                // Do not change the username below.
                // This should always be `mapbox` (not your username).
                username = 'mapbox'
                // Use the secret token you stored in gradle.properties as the password
                password = project.properties['MAPBOX_DOWNLOADS_TOKEN'] ?: ""
            }
        }
    }
```

I removed this part:

```gradle
  maven {
            // expo-camera bundles a custom com.google.android:cameraview
            url "$rootDir/../node_modules/expo-camera/android/maven"
        }
```

cleaned the project, and for some weird reason I get this stacktrace on Android Studio when building:

```log
Build file '/Users/stathis/IdeaProjects/xxxx/android/build.gradle' line: 56

A problem occurred evaluating root project 'xxxxx'.
> Basedir /Users/stathis/IdeaProjects/xxxx/node_modules/expo-camera/android/build/expo-camera$cameraview-aar does not exist
```

and line 56 on build.gradle from the error is this line 🤷‍♂️ :

`password = project.properties['MAPBOX_DOWNLOADS_TOKEN'] ?: ""`

**Comment by Kudo** [comment]
@efstathiosntonas could you share your output of `./gradlew :app:dependencies`?

**Comment by efstathiosntonas** [comment]
@Kudo unfortunately I can't, seconds after running the command it throws:

``` ./gradlew :app:dependencies                                                                                                        ✔  3.2.2 Ruby  at 11:43:48 
Starting a Gradle Daemon, 1 stopped Daemon could not be reused, use --status for details

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/stathis/IdeaProjects/hiki_mobile/android/build.gradle' line: 56
```

**Comment by efstathiosntonas** [comment]
feels like it fails to copy or it expects the `cameraview-1.0.0.aar` to be in the `build` folder of the module instead of `android/libs/cameraview-1.0.0.aar`

**Comment by Kudo** [comment]
@efstathiosntonas interesting! it looks like gradle cannot create the directory for you. could you try to apply the patch and see if that works for you?
```diff
--- a/node_modules/expo-modules-autolinking/scripts/android/autolinking_implementation.gradle
+++ b/node_modules/expo-modules-autolinking/scripts/android/autolinking_implementation.gradle
@@ -245,7 +245,11 @@ if (rootProject instanceof ProjectDescriptor) {
       }
       for (moduleAarProject in module.aarProjects) {
         include(":${moduleAarProject.name}")
-        project(":${moduleAarProject.name}").projectDir = new File(moduleAarProject.projectDir)
+        def projectDir = new File(moduleAarProject.projectDir)
+        if (!projectDir.exists()) {
+          projectDir.mkdirs()
+        }
+        project(":${moduleAarProject.name}").projectDir = projectDir
       }
     }

```

**Comment by efstathiosntonas** [comment]
@Kudo life got back to normal!

Screenshot 2024-10-25 at 13 02 10


thank you for the quick fix, glad we caught this early!

**Comment by Kudo** [comment]
thanks much @efstathiosntonas for trying out and sharing the problem. the fix is landed from #32349 and would be available in next release.

**Comment by efstathiosntonas** [comment]
perfect, thanks Kudos! keep it up!!

**Pull request merged**
