### PR TITLE
[danger] Warn instead of fail when the changelog isn't modified

### PR DESCRIPTION
**Pull request by ide**
Why
---
"Fail" is the strongest level of warning that Danger supports and makes sense for things like test failures but comes across as overly strong for a missing changelog entry. There are also several legitimate cases where a changelog entry might not be necessary.

How
---
Changed the `fail` call to a `warn` call.

Test Plan
---------
Add a dummy commit after this one that edits a changelog-tracked package without editing the changelog.

Screen Shot 2021-04-20 at 6 29 45 PM

### CODE REVIEW

**Review by bbarthec — APPROVED** [review]
I'm ok with this change 👌

**Comment by bbarthec** [comment]
@lukmccall, I suspect something is not right with danger task, because of this comment: https://github.com/expo/expo/pull/12629#issuecomment-823707100
None of the files from `expo-device` were modified, but we still have this suggestion 🤔

**Review by lukmccall — APPROVED** [review]
LGTM

> I suspect something is not right with danger task, because of this comment: #12629 (comment) None of the files from expo-device were modified, but we still have this suggestion 🤔

I think this message was generated because of the https://github.com/expo/expo/commit/31d07fa76bb4c8934dbef0b62aba9d06aa5f5037 commit. I assume that this branch had more changes but because of the `force push`, they were overwritten. The danger should remove the previous comment but for some reason, it didn't od it 🤔 So it looks like the danger library has a bug. However, I think we can ignore it. Especially because right now the danger check is green.

**Comment by ide** [comment]
> I think this message was generated because of the 31d07fa commit. 

Yes, that's correct. The expo-device change was part of the test plan.

**Pull request merged**
