### PR TITLE
[expo-av][iOS] Auto `unloadAsync` in `Video` before unmount occurs

### PR DESCRIPTION
**Pull request by Pickleboyonline**
# Why

This branch is a pure JS approach to the issue that [this PR](https://github.com/expo/expo/pull/18076) was meant to address. Essentially, there is Obj C cleanup code that must run on the main thread but `dealloc` has no guarantee of which thread it runs on. 

# How

To fix this problem we send out the `unloadAsync` command before the Video component begins to unmount in the `componentWillUnmount` method. We could have left this to users but they would have to use the `useLayoutEffect` rather than the `useEffect` hook, which is not obvious at first. I believe automatically doing this is a cleaner approach.

# Test Plan

I set a breakpoint on the `setSource` method in `EXVideoView.m` to confirm that the source was `nil` and cleanup initiates before deallocation occurs.

# Checklist

- [X] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [X] This diff will work correctly for `expo build` (eg: updated `@expo/xdl`).
- [X] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Review by barthap — COMMENTED** [review]
cc @hirbod 😉 

Looks legit to me, glad it's a JS-only change.
How does this behave on Android? I'm wondering if this change should be iOS-only

**Review by bbarthec — COMMENTED** [review]
Hello @Pickleboyonline 👋 
Overall this solution of yours seems fine to me 👍
Thank you for looking into this 😁 
The one thing that is left and I think should be taken care is adding some note to the docs about this auto-call to `unloadAsync` in `componentWillUnmount`. What would you say about documenting it here: https://github.com/expo/expo/blob/main/docs/pages/versions/unversioned/sdk/video.md#unified-api?

**Comment by hirbod** [comment]
Thats a good idea, even for Android if you ask me. And yes, a documentation should be done.
What happens if unloadAsync gets called twice? No-op?

**Comment by Pickleboyonline** [comment]
Alright, I updated the docs.

On both platforms calling `unloadAsync` like this twice had no effect. Looking at the underlying methods it would seem this call is idempotent.

Devices tested on:
- Samsung Galaxy S10 on Android 12
- iPhone 12 and Simulator running iOS 15.5
- Android Emulator on Android 11

**Review by barthap — APPROVED** [review]

**Pull request merged**
