### PR TITLE
[expo-asset][bare] downloadAsync should not download if file exists

### PR DESCRIPTION
**Pull request by awinograd**
# Why

Docs say the following for `Asset.downloadAsync`

> The asset is only downloaded if an up-to-date local file for the asset isn't already present due to an earlier download.

# How

I would have expected this method to return the local file immediately if present rather than red-download it. Otherwise, there's no reason to preload assets in the bare workflow.

# Test Plan

I check this patch against my bare app and it works as expected

### CODE REVIEW

**Comment by brentvatne** [comment]
this isn't sufficient because we can't determine if the download actually completed or was valid unless the `hashAssetFiles` asset plugin is included. see what we do in the managed env equivalent: https://github.com/expo/expo/blob/929e1e291fe5546a26f170f285cbf290d4dac237/packages/expo-asset/src/PlatformUtils.ts#L54-L73

**Comment by awinograd** [comment]
@brentvatne thanks for your response. I agree it's not quite the same functionality as managed due to the lack of integrity check. I'm not quite clear as to what that protects against though, since to me it looks like the remote asset filename is hashed already (though perhaps it's just the filename hash?). 

The use case i'm trying to improve here is the preloading described here: https://docs.expo.io/guides/preloading-and-caching-assets/#pre-loading-and-caching-assets

I have some audio files I don't want included in my native bundle (therefore are excluded from the assetBundlePatterns) because they are large and aren't needed at app start. However, I don't want to have to re-download them every time the app runs

**Comment by awinograd** [comment]
Here's the current workaround I have implemented in userland:
```ts
import { Asset } from 'expo-asset';
import computeMd5 from 'blueimp-md5';
import * as FileSystem from 'expo-file-system';

// a workaround until https://github.com/expo/expo/pull/8222 is merged
export async function checkIfBareAssetExists(asset: Asset) {
  const { uri, hash, type } = asset;

  if (uri.startsWith('file://')) {
    return uri;
  }
  const cacheFileId = hash || computeMd5(uri);
  const localUri = `${FileSystem.cacheDirectory}ExponentAsset-${cacheFileId}.${type}`;
  const { exists } = await FileSystem.getInfoAsync(localUri);
  if (exists) {
    asset.localUri = localUri;
    asset.downloaded = true;
    asset._downloadCallbacks.forEach(({ resolve }) => resolve());
  }
  return exists;
}
```

**Comment by awinograd** [comment]
@brentvatne docs also say that `hashAssetFiles` is used when using `expo publish --target bare`

> Note that in order to use expo-asset successfully, you must use the --assetPlugins option to provide the Metro bundler with the node_modules/expo-asset/tools/hashAssetFiles plugin when you create your JavaScript bundle. If you use expo export or expo publish to create your update, this will be done automatically for you.

https://github.com/expo/expo/blob/9d88422587fd88adf7bf4eaee7b467e70823ecd0/docs/pages/bare/updating-your-app.md#embedding-assets

**Comment by brentvatne** [comment]
yup, if you are using expo-updates and loading from a bundle published over-the-air then it will be there. but we can't assume that is the case and i think it would be a bit confusing to have some behavior change between development and production, and between different scenarios in production.

**Comment by brentvatne** [comment]
> I have some audio files I don't want included in my native bundle (therefore are excluded from the assetBundlePatterns) because they are large and aren't needed at app start. However, I don't want to have to re-download them every time the app runs

This is definitely something we would like to have recommendations for how to build in bare workflow, I'll get back to you next week.

**Comment by awinograd** [comment]
> yup, if you are using expo-updates and loading from a bundle published over-the-air then it will be there. but we can't assume that is the case and i think it would be a bit confusing to have some behavior change between development and production, and between different scenarios in production.

Fair enough. I didn't consider other workflows using the bare expo that may not be using expo publish. I suppose if someone is coming from normal react native they could be doing something else.

> This is definitely something we would like to have recommendations for how to build in bare workflow, I'll get back to you next week.

I look forward to seeing what you recommend! In the meantime, I do have a userland solution that's working for me:

```ts
import { Platform } from 'react-native';
import { Asset } from 'expo-asset';
// @ts-ignore
import computeMd5 from 'blueimp-md5';
import * as FileSystem from 'expo-file-system';

export async function checkIfBareAssetExists(asset: Asset) {
  if (Platform.OS === 'web') return false;

  const { uri, hash, type } = asset;
  // TODO: does this make sense to bail out if it's already at a file URL
  // because it's already available locally?
  if (uri.startsWith('file://')) {
    return uri;
  }
  const cacheFileId = hash || computeMd5(uri);
  const localUri = `${FileSystem.cacheDirectory}ExponentAsset-${cacheFileId}.${type}`;
  const { exists } = await FileSystem.getInfoAsync(localUri);
  if (exists) {
    asset.localUri = localUri;
    asset.downloaded = true;
    asset._downloadCallbacks.forEach(({ resolve }) => resolve());
  }
  return exists;
}

const AUDIO = Asset.fromModule(require('...'));
checkIfBareAssetExists(AUDIO).then((exists) => {
  if (!exists) {
    AUDIO.downloadAsync();
  }
});
```

**Comment by brentvatne** [comment]
so, we added a dependency on `hashAssetFiles` for usage with `expo-updates` (https://github.com/expo/expo/blob/master/packages/expo-updates/README.md#expo-asset) , and we can document that the `hashAssetFiles` plugin will be necessary to perform integrity checks with `expo-asset`in the `expo-asset` README. 

now we need to update this check so that rather than just checking if `IS_MANAGED_ENV` we detect if `hashAssetFiles` is enabled - i *believe* this is when `hash` is not `null`.

https://github.com/expo/expo/blob/929e1e291fe5546a26f170f285cbf290d4dac237/packages/expo-asset/src/PlatformUtils.ts#L41-L48

then we may want to rename the private methods `_downloadAsyncManagedEnv` and `_downloadAsyncUnmanagedEnv` to `_downloadAsyncWithIntegrityCheck` and `_downloadAsyncWithoutIntegrityCheck`

want to give this a try?

**Comment by awinograd** [comment]
@brentvatne thanks for the update. I'll make another pass based on your comment and update this PR

**Comment by awinograd** [comment]
Ready for another look

**Comment by brentvatne** [comment]
we're currently doing a bunch of stuff around release and so i don't have time to review this and test it adequately right now. let me know if you use this in your app successfully! either way, i will revisit once time opens up. it's not necessary to land it for a sdk release because it's only a js-level change and impacts bare workflow, so we can release at any time.

**Comment by awinograd** [comment]
No worries. I don't use this patch in my own app. I have a previous
workaround that's been great for me to date. Happy to wait to figure this
out until things die down

**Comment by awinograd** [comment]
For those coming here these days, I'm not currently sure if this "fix" / change makes a difference in the no-publish expo-updates workflow. 

@brentvatne I've asked some clarifying questions (https://github.com/expo/expo/issues/8221#issuecomment-694327747) about the assets in no-publish. Are the changes you were discussing in your last comment already reflected in the latest expo-update docs? Or are they still yet to come?

**Comment by jpstrikesback** [comment]
It looks like the second commit here that changed method names reversed the initial change to check if the file exists locally, was that intended @awinograd?

**Comment by awinograd** [comment]
@jpstrikesback I haven't looked at this for a year, but the code branches before the exists check you're talking about. I believe we can't perform that check properly without an integrity hash... but again, it's been a while since i've looked at this!

**Comment by jpstrikesback** [comment]
Good to know @awinograd, cheers!

**Comment by brentvatne** [comment]
apologies for not circling back to this, we've been focused on other things. i believe the solution here is reasonable and we'll try to land this for sdk 43

**Comment by brentvatne** [comment]
moving this to #8222

**Pull request closed without merging**
