### PR TITLE
Upgrade xml2js to address security vulnerability

### PR DESCRIPTION
**Pull request by karlhorky**
# Why

Address security vulnerability in `xml2js` below version `0.5.0`

Ref: https://github.com/Leonidas-from-XIV/node-xml2js/issues/663#issuecomment-1501088667

# How

Upgrade `xml2js` version

# Test Plan

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [x] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Comment by karlhorky** [comment]
Ah, seems maybe this is already done over here:

- https://github.com/expo/expo/pull/22071

**Comment by Simek** [comment]
Hello @karlhorky, thank you for preparing a bump PR! 👍  Unfortunately, it looks like some tests are failing after the package upgrade:
* https://github.com/expo/expo/actions/runs/4665172035/jobs/8258221627?pr=22080

Would you like to look at the failures and try to find the root cause of that? Maybe there were some breaking changes in new version, besides the vulnerability fix, since they have bumped the minor?

**Comment by tambor81** [comment]
is anybody looking at this? 
the fix seems to be good on xml2js on 0.5.0 but the vulnerability is still failing in our daily builds

**Comment by rikur** [comment]
Could this be addressed? Using `resolutions` to fix the vulnerability (which will trigger a pentest failure) breaks expo-plugins:

```
TypeError: [android.manifest]: withAndroidManifestBaseMod: androidManifest.manifest.hasOwnProperty is not a function
```

**Comment by brentsmyth** [comment]
It seems a primary change in xml2js 0.5.0 was to start using  `Object.create(null);` vs `{}` to resolve a CVE where properties like `__proto__` or `hasOwnProperty` could be passed via the XML.  If any logic is relying on these traditional JS properties (which looks to be the case) then it would need cleaning up.

**Comment by brentvatne** [comment]
we use xml2js@0.6.0 now, thanks for the PR though! sorry i didn't follow up here

**Pull request closed without merging**
