### PR TITLE
[android] Remove "share" and "save to launcher" actions from the persistent notification

### LINKED ISSUE #10301: (Expo Development Client, Android app) - Pinning an app from the Expo notification crashes Expo
### Summary of Issue

When running an app via the Expo Development Client, a persistent notification is shown. In there, there's an option to pin the app to the Home Screen of the Android device. Pressing this action crashes the Expo app.

### Environment

- Latest Expo Development Client (2.17.2). Although this already occurred with the previous version;
- Oneplus 6 device running Android 10 (OxygenOS);
- Using Nova launcher;
 
### Steps to Reproduce

- Start any app from Expo CLI;
- Scan QR code with Expo Development Client;
- After having the app running, go to the persistent notification and press the "pin" button;
- An "AlertDialog" will say that this will pin the app to the HomeScreen;
- After pressing OK, app crashes;

### Expected Behaviour vs Actual Behaviour
Expected: Expo Development Client should pin the app in the Home screen;
Actual behaviour: Expo Development Client crashes;

### PR DESCRIPTION
**Pull request by sjchmiela**
# Why

Kind of fixes https://github.com/expo/expo/issues/10301 (well, removing the buggy feature is kind of a fix).

# How

First I found out where the layout for the notification is held (`notification{.xml,_shell_app.xml}`). I noticed that `notification_shell_app.xml` defines exactly the layout we would like to keep, so I replaced `notification.xml` (used in Expo client) with `notification_shell_app.xml` (used in shell apps if `androidShowExponentNotificationInShellApp` manifest flag is `true`), removing the original one (now there's only one layout).

After removing buttons from the layout I had to also remove the code that bound actions to the buttons. I then went down the rabbit hole to code that was called and removed it too (see `ExponentIntentService`, `Kernel#installShortcut`).

**Note:** I left code responsible for handling shortcut opens so this is still supported.

# Test Plan

I have run Expo client with these changes and verified that there are no share or pin icons anymore.

### CODE REVIEW

**Review by brentvatne — APPROVED** [review]
hurray! i totally forgot about `androidShowExponentNotificationInShellApp` - perhaps we should remove that at some point too.

**Review by bbarthec — APPROVED** [review]

**Comment by zacnelson** [comment]
@sjchmiela This was a feature that I had used consistently and was surprised today when I updated the Expo client on Android and the feature was gone. Suddenly I'm scrambling to address this. Could you share the suggested path forward? Why remove something that was working?

**Comment by brentvatne** [comment]
we looked at analytics for these features and you may have been one of the three people using them.

we didn't want to continue to maintain largely unused features, and "save to launcher" had presented some new issues recently, so we decided that it wasn't worth the engineering time for us to fix it and continue to ensure that it works in the future.

i imagine you were using save to launcher, yeah? if so, i recommend building an apk and installing it on your device instead. alternatively, i think you can also create a shortcut (in the same way as you can for a website) to a specific deep link in userspace (eg: `exp://exp.host/@zacnelson/your-app`) that would deep link into expo client.

sorry for the hassle! i'm sure you can appreciate the need to prioritize engineering efforts on features that are used.

**Comment by zacnelson** [comment]
Hi Brent, appreciate the response. We've started down the APK route and the functionality is great - you install an APK and it auto updates! I should have known about that sooner... So while the initial snag was pretty frustrating, the current state is certainly an improvement. Thanks.

**Pull request merged**
