### PR TITLE
[intent-launcher] add doc comments in source, introduce `ActivityAction`

### PR DESCRIPTION
**Pull request by Simek**
# Why

To utilize the auto generation feature for API section the package source code must contain the relevant documentation.

Fixes ENG-1806

# How

This PR moves the current documentation of `IntentLauncher` component API - https://docs.expo.io/versions/latest/sdk/intent-launcher - with major tweaks to the package source code.

The changeset includes breaking change - refactor of stand-alone activity action constants (strings) to the `ActivityAction` String Enum. In my opinion this change tidy up the exports as well as improves the DX, because it would be easier now to suggest or list the available action types.  

I have included the simple example how to migrate to the `ActivityAction` in the Changelog and I have also tweaked few types to include `ResultCode` and `ActivityAction` instead of `number` and `string`.

P.S. @bbarthec Hope you like this String Enum usecase. 😄 

# Test Plan 

The changes and generated content have been tests running docs website on `localhost`.

# Preview

Screenshot 2021-08-16 at 18 17 46

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.io and README.md).
- [x] This diff will work correctly for `expo build` (eg: updated `@expo/xdl`).
- [x] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Review by bbarthec — APPROVED** [review]
It looks good 👍
Nice idea of wrapping these constants in one enum namespace 👏

**Review by tsapeta — APPROVED** [review]

**Comment by maticzav** [comment]
@tsapeta @bbarthec @Simek is there a way to launch an intent not defined in the enumerator? Maybe the `activityAction` type could accept an enum value as well as a string.

**Comment by Simek** [comment]
Hi @maticzav, thanks for the suggestion! 👍 

The change was not intended and types have been already loosen in the PR below, but there was no new release of the intent package since then:
* https://github.com/expo/expo/pull/15671

**Comment by tsapeta** [comment]
I'm going to publish some packages this or next week — I'll let you know here 😉

**Comment by DavidUnzue** [comment]
@tsapeta Looking forward to this fix, any news on the package release? 😃 Thanks!

**Comment by tsapeta** [comment]
I just released `expo-intent-launcher@10.1.1` with this fix 😉 Let me know if it works!

**Comment by bbarthec** [comment]
@rbuffat, I've just re-published the missing change in [`expo-intent-launcher@10.1.3`](https://www.npmjs.com/package/expo-intent-launcher?activeTab=versions). Let me know if it's there! 😁

**Comment by rbuffat** [comment]
@bbarthec This solved the issue! Thanks for the quick release of the new package!

**Pull request merged**
