### PR TITLE
[expo-manifests] Fix error in handling nested array

### LINKED ISSUE #23549: Nested array `plugins:` configuration crashes in Expo 49
### Minimal reproducible example

https://github.com/dejagersh/broken-expo-49/blob/main/app.json

### Summary

I was upgrading my v48 project which uses `expo-image-picker`, configured as such:

`app.json`:

```
plugins: [['expo-image-picker']]
```

After following the upgrade guide, I tried to ran my app and Expo Go immediately crashed. Even before bundling started:

image

Solution is to remove the `[]` around `expo-image-picker`:

```
plugins: ['expo-image-picker']
```

I don't necessarily expect this syntax to work, but it would be great if:

- It was mentioned in the upgrade guide. Forgive me if I missed it.
- A not so cryptic error was triggered somewhere, pointing me towards the solution.

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.2.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 20.0.0 - /opt/homebrew/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 9.6.4 - /opt/homebrew/bin/npm
      Watchman: 2023.05.08.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: Flamingo 2022.2.1 Patch 2 Flamingo 2022.2.1 Patch 2
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ^49.0.3 => 49.0.3 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.3 => 0.72.3 
      react-native-web: ~0.19.6 => 0.19.6 
    npmGlobalPackages:
      eas-cli: 3.15.1
    Expo Workflow: managed
```

### PR DESCRIPTION
**Pull request by douglowder**
# Why

Fix crash on iOS if a plugin is passed in as an array, but with only the name element and not the props element.

Also fix corresponding code on Android, where an exception is thrown.

Fixes #23549.

# How

Modified `Manifest.swift` and `Manifest.kt` to handle the above case correctly.

# Test Plan

- Tested with Expo Go and the project provided in the above issue
- New unit tests for both iOS and Android

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [x] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Review by wschurman — COMMENTED** [review]
Blame is https://github.com/expo/expo/pull/22701. Adding @Kudo as a primary reviewer.

We also need to make this fix on android I believe?

**Comment by douglowder** [comment]
@wschurman thanks, I'll take a look at Android as well, and see why iOS unit test CI is breaking

**Review by wschurman — APPROVED** [review]
This looks good to me. Definitely need @Kudo to review for correctness though before landing.

**Comment by douglowder** [comment]
@wschurman I think we need to merge this. In looking at `@expo/config-types` for plugins:

```ts
/**
 * Config plugins for adding extra functionality to your project. [Learn more](https://docs.expo.dev/guides/config-plugins/).
 */
  plugins?: (string | [] | [string] | [string, any])[];
```

it seems that

```json
{ "plugins": [[ "my-plugin" ]] }
```

is valid, and should be supported. If we want to prevent users from having a plugin be an array with only the name and no props, we should be enforcing that in the CLI, and not waiting until the app is built and running to crash, or throw an exception.

@EvanBacon does this seem reasonable?

**Pull request merged**
