### PR TITLE
chore(uuid): refactor to v7 import style

### PR DESCRIPTION
**Pull request by giautm**
# Why

I want to lock the version of `uuid` to v7, but Expo contains an old-style import that no longer supports v7. This PR fix that issue.

# How

# Test Plan

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.io and README.md).
- [ ] This diff will work correctly for `expo build` (eg: updated `@expo/xdl`).
- [ ] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Review by tsapeta — APPROVED** [review]
Looks good, thank you for doing this! 🙏

**Comment by tsapeta** [comment]
👆 In the PR above I updated `uuid` to v8 in all packages, so hopefully you won't need to lock to v7 once we publish them 😉

**Comment by giautm** [comment]
Thanks @tsapeta, <3

**Comment by tsapeta** [comment]
Unfortunately it turned that we can't just upgrade `uuid` in the packages, as its newer versions depend on `crypto.getRandomValues` implementation which is not polyfilled by us and we don't want to do that (to not modify users' environment without knowledge). We'll address this in the future with different solution.

**Comment by giautm** [comment]
Yeah, just change the way you import the package `uuid` in Expo is enough for me. 😄

**Pull request merged**
