### PR TITLE
[expo-modules] Fix failing instrumentation test

### PR DESCRIPTION
**Pull request by aleqsio**
# Why

Fixes failing instrumentation tests

# How

Added additional mocking logic in expo-modules-core

# Test Plan

Passes CI

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Comment by Kudo** [comment]
thanks for caring this failure. trying to dispatch an android instrumentation test and it failed still: https://github.com/expo/expo/actions/runs/5004323240/jobs/8966745531
```
expo.modules.JavaScriptViewModule > view_functions_should_be_callable[avd-33(AVD) - 13] FAILED 
```
is that something you've tried to address?

**Comment by aleqsio** [comment]
Yes 😅
You mean you run it on this branch?

**Comment by Kudo** [comment]
because the pr doesn't trigger the android instrumentation test automatically, so i ran it maunally
Screenshot 2023-05-18 at 8 32 32 AM
this was on the pr's branch and [the commit](https://github.com/expo/expo/pull/22518/commits/a490530daca488a50561f8d5093c22b777d04b8b)

**Comment by aleqsio** [comment]
Oh no, it fixed the issue on my local when running `expotools android-native-unit-tests --type instrumented`

image

**Review by tsapeta — APPROVED** [review]

**Comment by aleqsio** [comment]
@Kudo Any idea why when running manually the cache restore part takes ~1/2 hours?
image

**Comment by Kudo** [comment]
> @Kudo Any idea why when running manually the cache restore part takes ~1/2 hours?

building hermes 😑
well, let me try the test locally as well.

**Comment by Kudo** [comment]
the test passed locally. i have no idea what's going on for github actions. let's merge it and see 👀

**Review by Kudo — APPROVED** [review]

**Pull request merged**
