### PR TITLE
[ios][et] Fix creating a shell app locally

### LINKED ISSUE #4887: [ios] `pod install` in shellAppWorkspaces causes machine to run out of disk space and crash
This has been an issue for at least a few months now -- when I try to run the `gulp ios-shell-app` task locally and generate a shellAppWorkspaces folder, the `pod install` step in this folder never completes, causing my machine to quickly run out of disk space and then crash. My recollection is that running in verbose mode, it fails after logging `    - Generating deterministic UUIDs`. This makes local debugging of both turtle issues and failing CI jobs significantly more difficult. We should figure out why this is happening and make the shellAppWorkspaces project lightweight/possible to run locally.

### PR DESCRIPTION
**Pull request by tsapeta**
# Why

Fixes #4887 and a lot of other issues I found during QA.

# How

- Moved `ExpoKit.podspec` from the root folder to `ios` folder – that solves an issue with `pod install` running out of disk space (#4887).
- Migrated to CocoaPods CDN source – the CI won't need to download the entire CocoaPods repository and will use CDN instead of GitHub – that should result in smaller job time.
- Since we removed `expo-cli` dependency from the root directory and its binstub, shell app's build phase running `expo prepare-detached-build` couldn't find `expo` command. I added this dependency to `exponent-view-template` so `expo-cli` only gets installed when building iOS shell app. I updated build phase script accordingly.
- I removed `Bundle Expo Assets` build phase from `exponent-view-template` – it's been failing since `app.json` is no longer required and so there is no way the project may not have any config – which was checked by `xdl` in a few places causing it to use different and unexpected logic. Also, it wasn't used in shell apps but only in projects ejected to ExpoKit which we no longer support so it is safe to remove it.
+ https://github.com/expo/expo-cli/pull/2246

# Test Plan

Running `gulp ios-shell-app --action build --type archive --verbose true --skipRepoUpdate --shellAppSdkVersion UNVERSIONED` in `tools-public` passes `pod install` step and no longer crashes when ran locally.

# To do

- [x] Update `xdl` in `tools-public` and `expo-cli` in `exponent-view-template` once https://github.com/expo/expo-cli/pull/2246 is merged and published.

### CODE REVIEW

**Review by esamelson — CHANGES_REQUESTED** [review]
I think it's actually fine for this PR to land on master, but as we discussed earlier today, we do need to keep ExpoKit intact and releasable from the sdk-38 branch. If that means keeping ExpoKit.podspec in the root directory, we can take comfort in the fact that this is the last release we'll have to deal with #4887 -- or we can have a separate sdk-38-expokit branch. (We'll also need to keep the Bundle Expo Assets build phase on the release/expokit branch.)

**Comment by tsapeta** [comment]
> I think it's actually fine for this PR to land on master, but as we discussed earlier today, we do need to keep ExpoKit intact and releasable from the sdk-38 branch.

Yeah, agreed, I'll merge this to master as is (without ExpoKit.podspec in the root dir), then cherry-pick this to `sdk-38` branch and bring back root's podspec on that branch – so later it will be included in ExpoKit tag 😉 

> We'll also need to keep the Bundle Expo Assets build phase on the release/expokit branch.

I think we don't need to keep it – we already don't support making new ejects to ExpoKit (but we do support updates). In other words, this bundle assets build phase will still exists in users' projects 🙂 For standalone apps this build phase does nothing.

**Comment by ide** [comment]
Do you know why moving ExpoKit.podspec into the ios folder solved the issue with disk space? (I might be misremembering but I think we were running out of disk space because enormous amounts of swap space were being used, which would hint that CocoaPods allocated many large data structures internally...)

**Comment by tsapeta** [comment]
Yeah, I also noticed that `ruby` process has been doing a lot of disk read operations and no writes, which makes me think that it entered some kind of reading loop when resolving pods and their dependencies 🤔 I can guess moving it to `ios` folder solved that because there are no any other podspecs in subdirs (that depend on ExpoKit?). I would try find the root cause if only I have more time, SDK release is more important now and we no longer need this podspec to be in the root folder since it's the last SDK that supports upgrading ExpoKit 😉

**Pull request merged**
