### PR TITLE
[expo-facebook] Add the types to the export of the package

### PR DESCRIPTION
**Pull request by dbritto-dev**
Extract the types from the main file and enable an easy way to add support for web

# Why

This PR add the same behaviour of expo-document-picker, so ... when you need add support for web for example you can import the types of expo-facebook just importing this from the sources like

```
import { FacebookOptions, FacebookLoginResult } from "expo-facebook"
```

and now you can use this types on your index.web.ts

# How

How did you build this feature or fix this bug and why?

This is a feature. I build this feature from expo/packages/expo-facebook.  You can read the reason above.

# Test Plan

This PR are just decoupling/splitting some stuff for a better support for web and other things

### CODE REVIEW

**Comment by ide** [comment]
We should just re-export the types from index.ts. Any kind of import of the form `packagename/privatedetails` could break in a patch release unless it's documented as part of the intentional public interface. Reaching into `src` is the kind of thing that won't be covered in a changelog.

**Comment by danilobrinu** [comment]
> We should just re-export the types from index.ts. Any kind of import of the form `packagename/privatedetails` could break in a patch release unless it's documented as part of the intentional public interface. Reaching into `src` is the kind of thing that won't be covered in a changelog.

so we should access to the types from the packages itself

**Comment by danilobrinu** [comment]
@ide can you take of this from this latest changes ??

**Comment by ide** [comment]
> so we should access to the types from the packages itself

Yes, that's what I meant. That way the types are part of the public interface.

**Comment by danilobrinu** [comment]
> > so we should access to the types from the packages itself
> 
> Yes, that's what I meant. That way the types are part of the public interface.

but know when import expo-facebook I can't access to the types (FacebookOptions and FacebookLoginResult) I push some changes about that.

@ide can you take care of this PR from this point ??

**Pull request closed without merging**
