### PR TITLE
[unimodules] Add deprecation notices to CHANGELOGs and READMEs

### PR DESCRIPTION
**Pull request by tsapeta**
# Why

Next step of deprecating unimodules packages

# How

Cleared out READMEs and put deprecation notices in there and changelogs

# Test Plan

Nothing to test

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.io and README.md).
- [ ] This diff will work correctly for `expo build` (eg: updated `@expo/xdl`).
- [ ] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Comment by chrisbobbe** [comment]
Hello! I think the https://expo.fyi/expo-modules-core-migration link is broken. I'm getting redirected to https://github.com/expo/fyi/blob/master/expo-modules-core-migration.md, for which GitHub says "Page not found".

**Comment by chrisbobbe** [comment]
Ah, also, in `expo-modules-core`'s README, it says:

> # Installation in bare React Native projects
> 
> For bare React Native projects, you must ensure that you have [installed and configured the `react-native-unimodules` package](https://github.com/expo/expo/tree/master/packages/react-native-unimodules) before continuing.

Should I keep `react-native-unimodules` installed, then, or is it deprecated and not to be used? 🙂 Thanks very much!

**Comment by tsapeta** [comment]
@chrisbobbe
We're in the process of migrating from `unimodules` packages to `expo-modules-core`, but for now it's happening only in the repo, so some things are not really published yet. The link to the migration guide doesn't work because we haven't written it yet — since some of those things are not fully migrated and we don't want to mislead you and others to migrate your apps too early 😉 We plan to finish all required work soon, so probably it'll be in time with the next SDK release (43), but to be honest we should make it in a week or so. By then, some files in the repo might be out of date — I'm really sorry for that, but there is no other way 😞. If you're looking for valid READMEs, I recommend using those that are on npm (that relates to versions you're using) or use https://docs.expo.dev

For now, keep using `react-native-unimodules` 🙂 We'll be posting updates on Twitter, once we officially release everything 😉

**Comment by chrisbobbe** [comment]
Oh OK, understood, thanks!

> I'm really sorry for that, but there is no other way 😞

It's OK, don't worry about it! 🙂

**Pull request merged**
