### PR TITLE
[docs][rfc] Add scopeKey top-level field to Expo Updates spec

### PR DESCRIPTION
**Pull request by wschurman**
# Why

The current client implementation does not have a method of deriving `scopeKey`, `stableLegacyID`, or `projectId` in new manifests: https://github.com/expo/expo/blob/master/packages/expo-updates/android/src/main/java/expo/modules/updates/manifest/raw/NewRawManifest.kt#L30

The proposal here is to put those three fields in the following places:
- `scopeKey` - top-level since it's fairly core to the way things work, including the kernel and expo updates library itself. This could also arguably go inside `extra.expoClient`, `extra.expoGo`, or even another extra sub-field, but I think top-level is most correct since it will be needed everywhere one of these manifests is used which even self-hosted apps need.
- `stableLegacyID` - This will be in `extra.expoClient` for now. While we'd like to remove this as a dependency, it will take some time so we'll probably keep including it for now, even in new manifests. It is currently used in notifications and the amplitude module. It is being removed from them, but would be good to decouple launching this from their removal.
- `projectId` - This is already documented to be in `extra.eas.projectId` in this document. It is being codified where manifests are served in https://github.com/expo/universe/pull/7896.

# How reviewers can help

Help me decide the pros and cons of this being a top-level field. We need to answer the question: "Would a custom implementation of this spec find the field useful, or is it only useful for the `Expo Client` or `Expo Go`?"

# Test Plan

N/A

### CODE REVIEW

**Comment by wschurman** [comment]
There is a good question @jkhales brought up: Why wouldn't scopeKey (a stable, unique, immutable string) be hardcoded in the build akin to how we are hardcoding `EXUpdatesURL` in the plist? There are two reasons we didn't do this in the past:
- Expo Go doesn't have a plist. This argument breaks down for this new format of manifest though as there's an `extra.expoGo` key that would be the correct place for the scope key if this it only needed in the manifest for Expo Go.
- We didn't have a method of requiring creating EAS apps on the server before being able to run outside of Expo Go. I believe it is the case now that we'll always have an App on the server now anytime outside of `expo start` on Expo Go.

Some things to think about with this approach:
- How much work is it to read this value from the plist/android equivalent in all the places we currently get this value from the manifest?
- How much work is it to write this value automatically into the plist when not being run in Expo Go? How much work is it to write this value into the `extra.expoGo` field when it is being run in Expo Go? Is there a way to know it's being run in Expo Go at time of manifest being served, or do we need to always include it?
- How does this work for self-hosted manifests/projects outside of EAS? Will they need to add the value manually to their plist?

**Review by ide — COMMENTED** [review]
The plans for stableLegacyId (we use "Id" instead of "ID" in all the other places in the manifest) and projectId sound great. Need to think more about scopeKey since it's needed only for Expo Go, really.

**Comment by wschurman** [comment]
> Need to think more about scopeKey since it's needed only for Expo Go, really.

I think it's fairly difficult to remove the dependency on scopeKey from the client in the short term (grep for usages of `ExperienceKey` and `getScopeKey`). Just looking at android, it seems to be used for a of things like the ExperienceDB, notifications, manifest caching in expo updates, shared preferences, etc, and for some of these we may not actually be able to remove the dependency if the data is keyed on the scope key.

That being said, in an ideal world only Expo Go would need scope key and it is something we can move toward slowly.

**Comment by ide** [comment]
We're on the same page, I think. Conceptually, since scoping is needed only for Expo Go, it follows that only Expo Go needs `scopeKey`. But because of historical reasons coming from a roadmap that was Expo Go-centric, much more of our code is currently accidentally coupled to `scopeKey`.

Since `scopeKey` protects the security of a project in Expo Go, perhaps we should think about how we want to secure it (i.e. make it unfalsifiable) for projects served from Expo CLI, hosted by EAS, and hosted on other servers. As we discussed, maybe we want a certificate chain and a root Expo CA certificate. Additionally, we might want to use this same signing mechanism for other fields of the manifest, especially assets URLs and hashes. Once we figure that out it might be clearer where the `scopeKey` field belongs.

**Comment by wschurman** [comment]
I think the ideal state is for non-expo-go manifests to not even have a scope key, and for the client code (non-JS) to throw when they try to access it in a standalone or dev-client build. This would help create a strong guarantee that expo apps don't scope data in production, which is very useful for things like project transfer, ejection, etc. That being said, I don't think it's currently possible to get to this state since we currently use scopeKey in un-scoped modules on both platforms. Some examples:
- [ConstantsBinding (Android)](https://github.com/expo/expo/blob/master/android/expoview/src/main/java/versioned/host/exp/exponent/modules/universal/ConstantsBinding.java#L82) - used in TaskManager for task registration, even in unscoped context
- On iOS, I believe we use scoped modules throughout? It's a bit harder for me to trace than on Android, but as far as I can tell all the modules on iOS in standalone apps are the scoped versions unless I'm wrong (cc @esamelson). [Link](https://github.com/expo/expo/blob/2615299d6f239b13775058768fba66b2e91967b7/ios/Exponent/Versioned/Core/EXVersionManager.mm#L366)

So, if I'm understanding the state of the code correctly, for us to move to this ideal world we'd need to refactor iOS and write migrators for a lot of things to move scoped data out.

Thus, I think we're probably stuck with scope key in both production apps and expo go at least for the foreseeable future, or at least until log after we'd like to launch Expo Updates. Because of this, and because we'd also need to do a pretty significant amount of refactoring to move it out of the manifest, my gut says it does need to be in the manifest, but since we're trying to move off it maybe it should live outside the root (in an extra field) so that the spec isn't guaranteed to include it forever. Also it doesn't make sense to spend time moving it to be a hardcoded thing in a plist if we're eventually going to try to get rid of it.

---

> Since `scopeKey` protects the security of a project in Expo Go, perhaps we should think about how we want to secure it (i.e. make it unfalsifiable) for projects served from Expo CLI, hosted by EAS, and hosted on other servers. As we discussed, maybe we want a certificate chain and a root Expo CA certificate. Additionally, we might want to use this same signing mechanism for other fields of the manifest, especially assets URLs and hashes. Once we figure that out it might be clearer where the `scopeKey` field belongs.

Yeah, this is something I was somewhat hoping to decouple, but when you put it that way it does seem like we'd probably only want to sign top-level fields, but we'd probably want to sign fields like `projectId` and `stableLegacyID` as well so that apps couldn't impersonate via those either.

So we have some cases to think about:
- online `expo start && GET localhost:7000/update-manifest-experimental` - needs to sign, can embed root Expo public CA cert in Expo Go, vend cert during start for (scope key, project ID), serve cert locally as an asset or something and download during manifest download bundle download and verify
- offline `expo start && GET localhost:7000/update-manifest-experimental` - can just have similar behavior to what Expo Go currently does and not attach any scoped behavior when not verified (need to double check that this is what is done currently)
- `GET exp.host/--/:app_id/update-manifest-experimental` - this is a different problem than the two items above since scoping isn't an issue (app is isolated via OS isolation, scoping theroetically shouldn't be used as mentioned above). The problem here we'd try to solve is to have "code/asset signing", and is pretty straightforward about how to solve: user embeds public key in app, signs bundle and assets with private keys during publish, new bundles/asset signatures are verified by the client.
- `GET /externally-hosted-mainfest-url` - this will be similar to the code signing above since it is fairly independent of a server.

So, the two categories are:
- Code signing for production apps, independent of scoping and probably a separate problem. Essentially we just compute the hash of the bundle and assets and put them in a signed string/JWT/other format. Then, when downloading an update, compare the signed hashes against the bundle/assets actual hashes.
- Securing scoping - Could implement various ways. I like the idea of being able to download a cert for a particular project (when auth'ed) that grants scoping access for a scopeKey/projectID. Could alternatively use something similar to the signing currently in use for classic manifests.

Finally, how does this affect where the fields are in the manifest for securing scoping? I don't think it necessarily matters. With the cert approach, the cert would contain two fields approved for use in Expo Go (scopeKey, projectId), and then the client code would compare those with what the manifest is requesting to use for those values and reject it if there's a mismatch. Side note: there may even be a world in which those values aren't in the manifest for expo go either, and are just gotten from the cert.

**Comment by wschurman** [comment]
Okay, my proposal is now:
```
{
   ...,
   extra: {
      clientScoping: {
          scopeKey: "...",
      },
   },
}
```

This will keep it separate from Expo Go (`extra.expoGo`) since it is used in the client, and it will keep it separate from Expo Client (`extra.expoClient`) since it should logically be separate and may be separable in the future if we change it to only being required in Expo Go (or maybe not require it at all for anything).

**Comment by ide** [comment]
I agree with what you wrote [above](https://github.com/expo/expo/pull/13646#issuecomment-886862162). I think it's worth thinking through what it would look like to sign a scope key vs. signing a subset/fragment of the manifest vs. signing the whole manifest.

Scope key signing is necessary for scoping to be secure. Manifest fragment signing is possibly useful for letting enterprise developers sign part of their manifests while letting the hosting service e.g. EAS add in other fields like rollout tokens. Full manifest signing, which could include a signed fragment, is useful to ensure it came from a trusted server. Variants of this like signing multiple fragments might also be useful.

The reason I mention fragment signing is that the scopeKey itself is a fragment.

**Comment by jkhales** [comment]
> Side note: there may even be a world in which those values aren't in the manifest for expo go either, and are just gotten from the cert.

This seems like the right world.

**Comment by wschurman** [comment]
Closing this since changes to the spec are no longer required. Thanks to all reviewers for the help and input!

**Pull request closed without merging**
