### PR TITLE
Bump up react-native-gesture-handler

### PR DESCRIPTION
**Pull request by zocoi**
per https://github.com/kmagiera/react-native-gesture-handler/pull/372#discussion_r250565656

# Why

Expo is broken for new app with examples using `react-native-gesture-handler` due to a broken import. https://github.com/kmagiera/react-native-gesture-handler/pull/372#discussion_r250565656

The new version is out which fixed this

### CODE REVIEW

**Comment by brentvatne** [comment]
this PR title is quite sensationalist, it's usually helpful to include at least some code that demonstrates the issue being fixed when making a change. for example, i just created a new app and used rngh in it and as expected it worked. that said, we should bump the rngh version as suggested here, so thanks!

**Comment by zocoi** [comment]
@brentvatne sorry if the title is misleading, it seems that `@react-navigation/native` was using `react-native-gesture-handler "^1.0.0"` which is automatically fixed once the new version is out. It did break for me before 1.0.14 was released. The culprit wasn't in expo dependencies.

**Comment by brentvatne** [comment]
ooh thank you for pointing that out! very helpful

**Comment by dev-esoftplay** [comment]
image

now this issue appears again, please fix it

**Pull request merged**
