### PR TITLE
Compile jsx in all packages

### PR DESCRIPTION
**Pull request by EvanBacon**
# Why

Shipping JSX means the end-user has to transpile while developing. 

# How

- Change `packages/expo-module-scripts/tsconfig.base.json` - `jsx` to `react` from `react-native`.
- Rebuilt the native packages that have components.

# Test Plan

- Running NCL in web didn't render any new warnings. 
- I added an error to BlurView to see how the source maps would format:

Screen Shot 2020-05-21 at 4 44 48 PM
Screen Shot 2020-05-21 at 4 44 44 PM

## iOS

In a new project I used a custom version of `expo-blur` that throws an error in the render method. Here is the before and after:

### Before

<p>

Screen Shot 2020-05-21 at 5 29 34 PM
</p>

### After

<p>

Screen Shot 2020-05-21 at 5 30 10 PM
</p>

### CODE REVIEW

**Comment by ide** [comment]
There are some React-related Babel optimizations (look at the Babel preset and its dependencies) IIRC. I am not sure if they expect to operate on JSX or React.createElement. (Another way to figure this out is to see whether the React optimizations need to run before the JSX compilation.)

If the optimization plugins still work with createElement, this looks good to me.

**Comment by EvanBacon** [comment]
We may lose some optimizations on native if we do this (haven't measured the exact impact). 

We could use the `react-native` field in the `package.json` which would give properly symbolicate to the TS files when an error occurs but this is not supported in Webpack so the Expo web source would be different -- this is a no-op.

For now it may be better to do nothing as the current setup is the fairest compromise between web and native.

**Comment by ide** [comment]
Discussed this more with Evan. We already compile TS to JSX, so compiling TS to ES2020 shouldn't be fundamentally more disruptive. Bundlers still need to compose source maps regardless.

The main difference is that these Babel plugins won't be applied:
https://babeljs.io/docs/en/babel-plugin-transform-react-jsx-self
https://babeljs.io/docs/en/babel-plugin-transform-react-jsx-source

Given that using tsc to compile JSX works fine for the web, I suspect it will work fine elsewhere. Publishing standard ES2020 in our packages will give all bundlers standards-compliant source to consume.

**Review by ide — APPROVED** [review]
Approving assuming that CI passes: https://github.com/expo/expo/pull/8421/checks?check_run_id=711608929

**Pull request merged**
