### PR TITLE
[notifications][expoview] scope ExpoFcmMessagingService in the android client

### PR DESCRIPTION
**Pull request by cruzach**
# Why

When standalone apps would receive remote push notifications, they would then be turned into `ScopedNotificationRequest`s, but that should only occur in the Expo client where we need scoping.

# How

- remove `createNotificationRequest` method override from `ExpoFcmMessagingService`, use that in shell apps ([XDL PR here](https://github.com/expo/expo-cli/pull/2772))
- create `ScopedExpoFcmMessagingService` to be used in the expo client app

# Test Plan

Tested in a local android shell app (`et android-shell-app -s 39.0.0 -u https://exp.host/@charliecruzan/sdk38`), remote notifications are coming through to the app

### CODE REVIEW

**Review by sjchmiela — COMMENTED** [review]
In my opinion it would be much easier if we guarded the `createNotificationRequest` inside with `if (Constants.isStandaloneApp())` (and return `super` if it is).

We already do so in more than several places + it doesn't require any changes in XDL (which is a pain to patch/fix/use).

What do you think about such a solution?

PS. I think I'd rather use scoped category identifiers in both Expo client and standalone apps scenarios which was the way before https://github.com/expo/expo/pull/9287 landed (if I understand the description of https://github.com/expo/expo/pull/10608 correctly). I'm currently in the process of revisiting the offending big refactor and remigrating it back to service-based structure (having doze mode in mind) so one day we I may fix this organically. 🙂

**Comment by cruzach** [comment]
`if (Constants.isStandaloneApp())` works for me! I like that much better, wasn't aware we did that

> I think I'd rather use scoped category identifiers in both Expo client and standalone apps scenarios

I don't have a strong opinion for or against this, I think whatever option that allows us to treat notifications in the three scenarios (client, standalone, and bare) as equally as we can, within reason, is best. And hides any of the scoping away from users 👍

**Comment by cruzach** [comment]
@sjchmiela do you mean to save you'd just rather continue to use scoped category IDs in standalone apps (as well as the expo client), or you'd also prefer both the expo client and standalone apps to rely on `ScopedNotificationRequests`?

**Comment by sjchmiela** [comment]
Yes, that's what I meant — by using the same native category ID (scoped identifier) we ensure that a notification sent by Expo servers with a scoped category ID will be properly handled by both Expo client and standalone apps.

**Pull request merged**
