### PR TITLE
Fix react-native-svg version in bundledNativeModules

### LINKED ISSUE #2241: Invalid `RNSVG.podspec` file: undefined method `visionos' for #<Pod::Specification name="RNSVG">.
Pod install error 

"react": "18.2.0",
"react-native": "0.72.11",
"react-native-svg": "^15.1.0",

[!] Invalid `Podfile` file: 
[!] Invalid `RNSVG.podspec` file: undefined method `visionos' for #<Pod::Specification name="RNSVG">.

 #  from /Users/mac/Desktop/WorkSpace/Rootchat/RootchatRN/node_modules/react-native-svg/RNSVG.podspec:18
 #  -------------------------------------------
 #    s.tvos.exclude_files = '**/*.macos.{h,m,mm}'
 >    s.visionos.exclude_files = '**/*.macos.{h,m,mm}'
 #    s.osx.exclude_files = '**/*.ios.{h,m,mm}'
 #  -------------------------------------------
.

 #  from /Users/mac/Desktop/WorkSpace/Rootchat/RootchatRN/ios/Podfile:29
 #  -------------------------------------------
 #  target 'rootsapp' do
 >    config = use_native_modules!
 #  
 #  -------------------------------------------

### PR DESCRIPTION
**Pull request by mogusbi-motech**
# Why

Fixes [this issue](https://github.com/software-mansion/react-native-svg/issues/2241) with `react-native-svg` when building iOS app

# How

Update to `react-native-svg@15.3.0`

# Test Plan

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [x] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Comment by mogusbi-motech** [comment]
Would it be possible to get a review on this, please? @ide @tsapeta @brentvatne

**Comment by tsapeta** [comment]
Hi @mogusbi-motech,

The `bundledNativeModules.json` used to be updated by us only before the SDK release. It contains versions that we've tested as part of our QA process. Can't you just update to this version in your project instead?

**Comment by mogusbi-motech** [comment]
We could, but doing so breaks our build pipeline as that runs Expo Doctor and updating this dependency causes it to fail.

**Comment by tsapeta** [comment]
Have you checked this guide https://docs.expo.dev/more/expo-cli/#configuring-dependency-validation ?

**Comment by mogusbi-motech** [comment]
I had not come across that so thanks for pointing me towards that workaround. I'll keep this PR open until you do get a chance to test it just so that I can remove the exclusion once it's been updated

**Comment by tsapeta** [comment]
@mogusbi-motech I'm going to close this PR then – we'll update all packages in this file when the SDK release process starts. You can remove the exclusion once you update to the upcoming SDK 52 😉

**Pull request closed without merging**
