### PR TITLE
[modules][Android] Prevent proguard from striping `PromiseImpl.<init>` and `ExpectedType` methods

### PR DESCRIPTION
**Pull request by lukmccall**
# Why

Fixes JNI crashes in the release builds.

# How

- Fixed `PromiseImpl.<init>` being removed by proguard by adding and `@DoNotStrip` annotation.
- Fixed `ExpectedType` properties being removed by using normal functions instead. 

# Test Plan

- bare-expo ✅

### CODE REVIEW

**Review by tsapeta — APPROVED** [review]
Interesting, does that mean ProGuard strips class members and doesn't strip functions?

**Comment by Kudo** [comment]
the changes look good, but updates e2e is still broken. could you take a look for it?

**Comment by Kudo** [comment]
> Interesting, does that mean ProGuard strips class members and doesn't strip functions?

i feel that proguard rules cannot target the kotlin generated methods.

**Comment by lukmccall** [comment]
> I feel that proguard rules cannot target the kotlin generated methods.

That's not true. If you investigate a combined class file, you will see metadata about generated setters and getters for properties. So, the call from Kotlin will work because the compiler would use that information to deduce the correct obfuscated function. However, calls via reflections won't work because the property's name was changed. I believe it is not about how proguard works but how Kotlin compiler generates properties. Probably, reflection from Kotlin std calls the correct functions even after obfuscation. It has access to the class metadata at the runtime.

**Comment by Kudo** [comment]
> > I feel that proguard rules cannot target the kotlin generated methods.
> 
> That's not true. If you investigate a combined class file, you will see metadata about generated setters and getters for properties. So, the call from Kotlin will work because the compiler would use that information to deduce the correct obfuscated function. However, calls via reflections won't work because the property's name was changed. I believe it is not about how proguard works but how Kotlin compiler generates properties. Probably, reflection from Kotlin std calls the correct functions even after obfuscation. It has access to the class metadata at the runtime.

that's fair. nice to know more details from kotlin 👍

**Review by Kudo — APPROVED** [review]
✅ updates e2e ci passed 👏

**Pull request merged**
