### PR TITLE
[dev-menu] fix release build crash when importing `expo-dev-client`

### LINKED ISSUE #23401: [SDK 49] Cannot find native module 'ExpoDevMenu', js engine: hermes
### Minimal reproducible example

https://github.com/thespacemanatee/expo-dev-menu-repro

### Summary

#23219 has broken iOS Release builds that import `expo-dev-menu`. A simple `import "expo-dev-client";` will cause a crash at launch with the following stacktrace:

```
[CoreFoundation] *** Terminating app due to uncaught exception 'RCTFatalException: Unhandled JS Exception: Error: Cannot find native module 'ExpoDevMenu', js engine: hermes', reason: 'Unhandled JS Exception: Error: Cannot find native module 'ExpoDevMenu', js engine: hermes, stack:
requireNativeModule@53668:21
anonymous@58299:58
loadModuleImplementation@205:13
guardedLoadModule@136:37
metroRequire@64:91
anonymous@58246:55
loadModuleImplementation@205:13
guardedLoadModule@136:37
metroRequire@64:91
anonymous@58131:51
loadModuleImplementation@205:13
guardedLoadModule@136:37
metroRequire@64:91
anonymous@58101:13
loadModuleImplementation@205:13
guardedLoadModule@136:37
metroRequire@64:91
anonymous@878:47
loadModuleImplementation@205:13
guardedLoadModule@128:46
metroRequire@64:91
global@58537:3
```

At the very least, the docs here should be updated to say that the imports should be conditional to the build environment: https://docs.expo.dev/bare/install-dev-builds-in-bare/#optional-configuration

I believe this could have been avoided if it was tested on Release builds before releasing it to the public.

### Environment

```
expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.15.0 - ~/.asdf/installs/nodejs/16.15.0/bin/node
      Yarn: 1.22.19 - ~/.asdf/installs/nodejs/16.15.0/bin/yarn
      npm: 8.5.5 - ~/.asdf/plugins/nodejs/shims/npm
      Watchman: 2023.06.26.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /Users/thespacemanatee/.asdf/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
      Android SDK:
        API Levels: 23, 26, 29, 30, 31, 33
        Build Tools: 26.0.3, 29.0.2, 30.0.3, 31.0.0, 33.0.0, 33.0.2, 34.0.0
        System Images: android-24 | Google APIs ARM 64 v8a, android-26 | Google APIs ARM 64 v8a, android-26 | Google APIs Intel x86_64 Atom, android-26 | Google Play Intel x86 Atom, android-29 | Google Play ARM 64 v8a, android-33 | Google APIs ARM 64 v8a
    IDEs:
      Xcode: 14.3/14E222b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.0 => 49.0.0 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.1 => 0.72.1 
    npmGlobalPackages:
      eas-cli: 3.15.0
    Expo Workflow: bare
```

### PR DESCRIPTION
**Pull request by Kudo**
# Why

previously we suggested people to import `expo-dev-client` in their index.js file. after the new module api migration and using `requireNativeModule`, it will be a hard crash if the native module is not found. expo-dev-menu native module is typically not there because it's debug build only. that's why the crash happens in release build only.

fixes https://github.com/expo/expo/pull/23219#issuecomment-1625899685
fixes #23401

# How

try-catch the `requireNativeModule`

# Test Plan

test the repro from #23401

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [x] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Review by lukmccall — APPROVED** [review]

**Review by gabrieldonadel — APPROVED** [review]
LGTM

**Comment by sreuter** [comment]
@Kudo This looks all good to be merged now? Hopefully this will unblock us and many other users wanting to move to Expo SDK 49.

**Comment by Kudo** [comment]
> @Kudo This looks all good to be merged now? Hopefully this will unblock us and many other users wanting to move to Expo SDK 49. Currently using `expo-updates` also seems to trigger this issue.

merged and should be available for today or tomorrow's publish round. sorry for waiting

**Comment by brentvatne** [comment]
@sreuter - good catch, usually our publish script includes changes in dependent packages. republished it - expo-dev-client@2.4.5

**Comment by sreuter** [comment]
Wohoo, quickest turnaround ever, thanks heaps @brentvatne and team! Testing now and then hopefully moving to SDK 49 today 🙌

**Pull request merged**
