### PR TITLE
[menu][ios] Try to fix crashes connected with reloads

### LINKED ISSUE #17283: Expo SDK 45 - [iOS][hermes][expo-dev-client] - Reloading when dev-menu slides up (also causing crashes under certain circumstances)
### Summary

Hi @ajsmth @lukmccall and @tsapeta,

as announced in other tickets and via DMs, with the help of @ramiel1999 I was finally able to reproduce the bug that has been plaguing us since SDK 44.

It is enough to create a simple project with custom-dev-client and jsEngine "hermes" to reproduce the bug.

The problem occurs as soon as the dev menu starts up. It reconnects to Metro (even though the connection is already established, as Fast-Refresh works flawlessly) and downloads the bundle again. Also, you can see in the CLI that "iOS Bundling complete" appears. Under normal circumstances, the whole thing is just annoying, because you constantly lose your state (by the reload) but you can move on without restarting the app. This problem does not occur again once the bundle has been "re-downloaded". All further dev menu openings work until the next restart of the app. However, the problem with the whole story is that as soon as you use expo-notifications, react-native-mmkv or react-native-random-values-jsi-helper, the app crashes due to the reload or whatever is happening. The problem with expo-notification is known to you, but it looks like this very issue is causing other apps to have problems with it as well. Of course, the whole issue could be due to @mrousavy  install method, anyway he can't reproduce the problem in a bare React-Native project.

[Related packages: jsi-helper](https://github.com/mateioprea/react-native-random-values-jsi-helper)
[Related react-native-mmkv issue](https://github.com/mrousavy/react-native-mmkv/issues/294)

Your PR for expo-notifications might help for that particular package, but I think its not the root cause. The expo-notifications crash was not reproducible with JSC btw, only with Hermes. 

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare (custom-dev-client)

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

SDK 44 and SDK 45

### Environment

```
  expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.3.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.19.1 - /usr/local/opt/node@14/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 6.14.16 - /usr/local/opt/node@14/bin/npm
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6953283
      Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 0.51.0
      expo-cli: 5.4.3
    Expo Workflow: bare
```

### Reproducible demo

https://github.com/ramiel1999/dev-client-menu-reload

https://user-images.githubusercontent.com/504909/165965583-3448f024-2bfd-4003-8f02-f53c0b3ad291.mp4

The reproducible demo is not crashing, because it does not include react-native-mmkvv or expo-notifications. It just demonstrates the reload.

### PR DESCRIPTION
**Pull request by lukmccall**
# Why

Try to fix https://github.com/expo/expo/issues/17283.

# How

Similar to the https://github.com/expo/expo/pull/17282.

# Test Plan

- bare-expo ✅

### CODE REVIEW

**Review by Kudo — APPROVED** [review]

**Comment by axeldelafosse** [comment]
Thank you ❤️

**Comment by hirbod** [comment]
@lukmccall the expo-dev-menu does not show up for me anymore, instead the RN Dev Menu pops up - but no crashes so far. Is that intended?

**Comment by lukmccall** [comment]
It's not intended. We're working on that.

**Comment by hirbod** [comment]
I can live with the default menu :D
At least no crashes haha!

**Pull request merged**
