### PR TITLE
[packages] add react-native 0.71 support

### PR DESCRIPTION
**Pull request by Kudo**
# Why

backport react-native 0.71 support to sdk 47

# How

backport changes from these commits:

- e68edf7a5
- d4cd4dfca
- 26bee5e9
- 4ef7fe1bb

# Test Plan

- ci passed
- test on react-native 0.71 project

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [x] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Comment by Kudo** [comment]
though we've published some modules from main branch, i'm just cherry-pick those 0.71 commits together in this pr to sdk-47 branch for reference. we can still publish those modules from main.

**Review by lukmccall — APPROVED** [review]

**Comment by ottob** [comment]
Is it ok to use 0.71 with expo 47? `expo-cli doctor` (6.1.0) warns if I try to use it.

**Comment by Kudo** [comment]
@ottob it's theoretically work on expo-modules layers (for a bare project). the official 0.71 support will be available in sdk 48.

**Comment by ottob** [comment]
great, thanks!

**Comment by Roka20012** [comment]
@ottob have you already added expo modules to the bare project?

I have a bare project created with RN 0.71, and I want to use expo modules
Did you check if it's working without any conflicts?

**Comment by ottob** [comment]
nope, we will wait for sdk 48.

**Comment by VivekNeel** [comment]
> nope, we will wait for sdk 48.

beta is available!

**Comment by affcue25** [comment]
We cant use RN 0.71 with Expo SDK 47? Is it still not compatible?

**Comment by Roka20012** [comment]
> We cant use RN 0.71 with Expo SDK 47? Is it still not compatible?

Your could use expo sdk 48
It has been released

**Pull request merged**
