### PR TITLE
[expo-notifications] Remove the large icon from managed workflow

### LINKED ISSUE #10469: [expo-notifications] Mixed notification icons on Android after udpate to SDK v39
### Summary of Issue 

After updating to SDK v39 and using the next notifications API the Android notifications icons are not mixed in the way that status bar icon is the Expo icon and notification media image (or what ever the name is) is our app icon. The example shown below is the app screenshot from OnePlus 6 running Anroid 10. I don't have the information if the behavior is some on other Android phones (@Lorezz mentioned in #9062 that this issue is only on some Android OS versions).

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

Our `app.json` config related to notifications is empty, while the android part looks like:

```
    "android": {
      ...
      "icon": "./assets/icon.png",
      "adaptiveIcon": {
        "foregroundImage": "./assets/android/icon.png",
        "backgroundColor": "#50dbb6"
      },
      "useNextNotificationsApi": true
    },
```

Expo diagnostics:

```
  Expo CLI 3.27.10 environment info:
    System:
      OS: Linux 5.4 Ubuntu 18.04.5 LTS (Bionic Beaver)
      Shell: 4.4.20 - /bin/bash
    Binaries:
      Node: 10.22.1 - /usr/bin/node
      Yarn: 1.22.5 - /usr/bin/yarn
      npm: 6.14.6 - /usr/bin/npm
    npmPackages:
      expo: ^39.0.0 => 39.0.3 
      react: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.0.tar.gz => 0.63.2 
      react-navigation: ^4.4.0 => 4.4.0 
    npmGlobalPackages:
      expo-cli: 3.27.10
    Expo Workflow: managed
```

### Reproducible Demo

I don't have the reproducible demo, as you need to build the app to expect the correct notifications icon.
 
### Steps to Reproduce

-

### Expected Behavior vs Actual Behavior

Both icons should be set correctly.

### PR DESCRIPTION
**Pull request by lukmccall**
# Why

Fixes https://github.com/expo/expo/issues/10469.

# How

The `largeIcon` isn't set correctly. Moreover, for now, we don't have enough tools to config it properly. So we temporarily remove it. This functionality will be reimplemented in the future. 

# Test Plan

- NCL ✅

### CODE REVIEW

**Review by cruzach — COMMENTED** [review]
since this required androidmanifest changes to be made in order to set it up, this was a bare workflow only feature, right?

**Review by brentvatne — APPROVED** [review]
seems reasonable but will wait for @sjchmiela to verify

**Comment by sjchmiela** [comment]
> this was a bare workflow only feature, right?

Yes it was, it sneaked in to managed workflow.

> seems reasonable but will wait for @sjchmiela to verify

We talked about this on Slack and decided to remove the feature only from the managed workflow and leave it in bare in case somebody uses it (large icon will still be fetched from `AndroidManifest` which in managed workflow will render "no icon" and bare workflow users may want to customize [even though I would imagine "large icon" to be usually set per-notification, not per-app, but for this we'd need to support attachments on Android and we don't {yet}]).

**Comment by brentvatne** [comment]
sounds good! @lukmccall - i think we can land this pr if you revert the bare workflow related changes then.

**Comment by lukmccall** [comment]
> is `ScopedExpoNotificationBuilder` used in standalone apps (not just expo client)?

Yes, it's used in standalone apps too.

**Comment by pavelmasek** [comment]
Hi 👋, are there any plans to reintroduce the large notification icon in managed flow?

**Pull request merged**
