### PR TITLE
[docs] Sentry & EAS Build

### PR DESCRIPTION
**Pull request by gregfenton**
Add section to direct people to additional information for EAS Build.

# Why

Because I didn't find this information easily.  Hopefully will save others time and effort.

### CODE REVIEW

**Comment by cruzach** [comment]
thanks @gregfenton ! I'll have to give the readme a look-over, since I think it could be organized better (the EAS Build section is really only for bare workflow people, the config-plugin takes care of it for you if you're managed workflow).

**Comment by gregfenton** [comment]
Does it if you are using a dev-client?  I'm getting mixed signals on this
(via Discord).

Greg Fenton
--
email: ***@***.*** ***@***.***>*
linkedin: *http://ca.linkedin.com/in/fentongreg*
<http://ca.linkedin.com/in/fentongreg>
twitter: ***@***.****

**Comment by gregfenton** [comment]
Does it if you are using a dev-client?  I'm getting mixed signals on this
(via Discord).  And on that page that I linked to (the README) it says:

>  If you plan on running your project outside of Expo Go, you should also perform these steps:


---
**Sema Reaction:** :hammer_and_wrench: This code needs a fix

**Comment by cruzach** [comment]
The config plugin should be applied if you have a managed project (whether you're using EAS Build, `expo run:*`, and/or the dev client)

**Comment by gregfenton** [comment]
The instruction of 
> Run `yarn add @sentry/react-native` 

seems to have been required.  Prior to running that I was getting the error:

```
Sentry Logger [Error]: Error while triggering instrumentation handler.
Type: console
Name: callback
Error: SentryError: Native Client is not available, can't start on native.
at node_modules/@sentry/integrations/node_modules/@sentry/utils/dist/logger.js:89:23 in consoleSandbox$argument_0
at node_modules/@sentry/integrations/node_modules/@sentry/utils/dist/logger.js:24:4 in consoleSandbox
. . . . . .
```


Discord thread here: https://discord.com/channels/695411232856997968/809586753719238656/910636371402715186

**Comment by gregfenton** [comment]
Testing a plugin

**Comment by cruzach** [comment]
Addressed by https://github.com/expo/expo/pull/15254

**Pull request closed without merging**
