### PR TITLE
doc, add ALL_BUT_UPSIDE_DOWN

### PR DESCRIPTION
**Pull request by slorber**
this exists in SDK 36 values / typedefs

### CODE REVIEW

**Comment by cruzach** [comment]
Great! can you make the same changes to the `v36.0.0` docs, as well?

**Comment by slorber** [comment]
done :)

**Comment by cruzach** [comment]
thanks! just moved the option up so it's next to the other "ALL" option

**Comment by cruzach** [comment]
Ah, @slorber taking a closer look at the source, it seems that `ALL_BUT_UPSIDE_DOWN` is actually deprecated

**Comment by slorber** [comment]
ah, didn't know, just looked at typedefs :)

**Review by lukmccall — CHANGES_REQUESTED** [review]
Great job 🎉
However, `ALL_BUT_UPSIDE_DOWN` will be removed in `37.0.0` (https://github.com/expo/expo/pull/6760). So, please add it only to `v36.0.0`.

**Comment by slorber** [comment]
done

**Review by lukmccall — APPROVED** [review]

**Pull request merged**
