### PR TITLE
Upgrade google-services gradle plugin to 4.4.1

### PR DESCRIPTION
**Pull request by buraks**
# Why

Latest version of Crashlytics requires the google-services gradle plugin's version to be 4.4.1+
Source: https://firebase.google.com/docs/crashlytics/upgrade-to-crashlytics-gradle-plugin-v3#minimum-requirements

Otherwise [build](https://expo.dev/accounts/nvapps/projects/muslimai/builds/cd005261-15ed-41ff-bb08-e720c591657e) fails.

# How

Changing this value in node_modules and running expo prebuild generated the build.gradle with the expected version. Built on Android Studio and it worked.

# Test Plan

My build that was failing before this PR has successfully built afterwards.

# Checklist

- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [x] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Comment by jonluca** [comment]
@ChromeQ @brentvatne can we merge this in?

**Comment by jonluca** [comment]
Fixes https://github.com/expo/expo/issues/29140

**Comment by alanjhughes** [comment]
Hi @buraks - looks good but can you rebuild the JS please?
```bash
cd packages/@expo/config-plugins
yarn build
```

**Comment by buraks** [comment]
@alanjhughes I have just rebased and rebuilt the JS

**Review by alanjhughes — APPROVED** [review]

**Comment by kevinhylant** [comment]
@alanjhughes Sorry to pester - but given this blocks android builds for anyone with crashlytics integrated - how long until this will be released to SDK 51? ish
_I looked for the commit in the sdk-51 branch but don't see it yet_

**Pull request merged**
