### PR TITLE
Migrate to `@expo/whatwg-url` to fix `SharedArrayBuffer` issue.

### PR DESCRIPTION
**Pull request by EvanBacon**
# Why

`whatwg-url-without-unicode` hasn't been updated in a while and it uses an older version of `whatwg-url` -> `webidl-conversions` that doesn't support environments that are missing `SharedArrayBuffer` (support was added back [here](https://github.com/jsdom/webidl-conversions/commit/0449cdd5c6c96e609d225e44e40157587f8b0002)). To fix, I forked the latest `whatwg-url` to `@expo/whatwg-url` and stripped unicode support (pending native integration).

# Test Plan

- iOS and Android tests should no longer fail.

### CODE REVIEW

**Review by tsapeta — APPROVED** [review]

**Comment by tsapeta** [comment]
^ but please fix the SDK check 😄

**Review by ide — APPROVED** [review]

**Comment by marklawlor** [comment]
I'm happy to maintain a fork, but I'll tag @charpeni in case he is interested in updating `whatwg-url-without-unicode` and we can switch back. While `whatwg-url-without-unicode` hasn't been updated, the parent library `react-native-url-polyfill` is still active, so he may be interested in maintaining it this multi-environment react native use case.

**Comment by charpeni** [comment]
Thanks for the ping!

Both libraries are still active. I tried to update `whatwg-url-without-unicode` in different branches recently, but I'm always facing weird issues because the latest version of `whatwg-url` isn't really meant for non-web environments. If I remember correctly, it had to do with the lack of `AsyncIterator` support on React Native.

> To fix, I forked the latest `whatwg-url` to `@expo/whatwg-url` and stripped unicode support.

That's exactly the role of `whatwg-url-without-unicode` and `react-native-url-polyfill`, it would be good to align initiatives around URL and prevent creating another fork, if possible. 🙏

**Comment by ide** [comment]
AFAIK `react-native-url-polyfill` already works with Expo. Separately, the change in this PR is a step towards adding URL as a built-in to Expo core rather than polyfilling it.

**Comment by charpeni** [comment]
👋 James

Ah, perfect, cause I have a bunch of tests in `react-native-url-polyfill` to make sure it is well tested against Expo. ❤️ 

I read all the commits, and that's the gotcha that happened, the initial implementation used a beta version of `whatwg-url-without-unicode` (one of my experiments to use the latest version of `whatwg-url` that failed because of `SharedArrayBuffer`).

I also see that it was reverted (89dff0c02d4c57a1615fc05e1846c781b537c24f) in favor of the latest non-beta version of `whatwg-url-without-unicode`, which should be well-supported even though the implementation of `whatwg-url` is older. Using `whatwg-url-without-unicode@8.0.0-3` should be perfect for Expo core and should prevent the need to fork into `@expo/whatwg-url`.

If you would really like to have the latest implementation of `whatwg-url`, I can find more time to dig into that, but I'm sure we'll also need to polyfill a bunch of other things too, which is growing to the size of the bundle. 😅 The maintainer of `whatwg-url` was quite explicit that it isn't meant for non-web platforms and therefore it's been quite tedious to follow up.

**Comment by EvanBacon** [comment]
@charpeni yes the latest version of `whatwg-url` requires at least `SharedArrayBuffer`, async iterators, and `TextEncoder`/`TextDecoder` (we're investigating adding encoding natively too).

**Pull request merged**
