### PR TITLE
Add check for bundleIn${targetName}

### PR DESCRIPTION
**Pull request by rickysullivan**
Enable manifest creation for targets other than release.

### CODE REVIEW

**Review by esamelson — APPROVED** [review]
Thank you @rickysullivan !

**Comment by jamsea** [comment]
@rickysullivan I just want to let you know, you're a gentleman and a scholar. Literally spent the last 6 hours trying to figure out what was wrong here, narrowed it down to this line, and just noticed it was merged 4 hours ago. Thank you.

**Comment by sunny-lirr** [comment]
This PR is the cause of #8637, whose solution appears to force the use of the new no-publish workflow. Was this an intentional change?

**Comment by esamelson** [comment]
@sunny-lirr - thanks for the heads up, breaking the old publish workflow was not intentional. I've just released expo-updates@0.2.11 which should fix this issue. However, please note that support for the publish workflow will likely be removed in a future version of expo-updates and we highly recommend migrating to the no-publish workflow.

**Pull request merged**
