### PR TITLE
[android][expo-go] Add legacy splashscreen 

### PR DESCRIPTION
**Pull request by alanjhughes**
# Why
Expo go still relies on the legacy splashscreen behaviour so we can now add it directly.

# How
Moves the legacy splashscreen implementation in to expoview

# Test Plan
Expo go, splashscreen works as before

### CODE REVIEW

**Comment by alanjhughes** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/expo/expo/32475?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#32475** <a href="https://app.graphite.dev/github/pr/expo/expo/32475?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#23882** <a href="https://app.graphite.dev/github/pr/expo/expo/23882?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @alanjhughes and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by brentvatne — APPROVED** [review]
let's land this despite updates ci failures, which are unrelated and being worked on by @wschurman

**Review by wschurman — COMMENTED** [review]
The e2e failures look related:
```
Prebuild failed
TypeError: [android.dangerous]: withAndroidDangerousBaseMod: (0 , _imageUtils(...).generateImageBackgroundAsync) is not a function
TypeError: [android.dangerous]: withAndroidDangerousBaseMod: (0 , _imageUtils(...).generateImageBackgroundAsync) is not a function
    at /home/runner/work/expo/expo/updates-e2e/node_modules/@expo/prebuild-config/build/plugins/unversioned/expo-splash-screen/withAndroidSplashImages.js:161:79
    at Array.map (<anonymous>)
    at setSplashImageDrawablesForThemeAsync (/home/runner/work/expo/expo/updates-e2e/node_modules/@expo/prebuild-config/build/plugins/unversioned/expo-splash-screen/withAndroidSplashImages.js:154:27)
    at setSplashImageDrawablesAsync (/home/runner/work/expo/expo/updates-e2e/node_modules/@expo/prebuild-config/build/plugins/unversioned/expo-splash-screen/withAndroidSplashImages.js:134:22)
    at async /home/runner/work/expo/expo/updates-e2e/node_modules/@expo/prebuild-config/build/plugins/unversioned/expo-splash-screen/withAndroidSplashImages.js:117:5
    at async action (/home/runner/work/expo/expo/updates-e2e/node_modules/@expo/config-plugins/build/plugins/withMod.js:199:23)
    at async interceptingMod (/home/runner/work/expo/expo/updates-e2e/node_modules/@expo/config-plugins/build/plugins/withMod.js:104:21)
    at async interceptingMod (/home/runner/work/expo/expo/updates-e2e/node_modules/@expo/config-plugins/build/plugins/withMod.js:104:21)
    at async interceptingMod (/home/runner/work/expo/expo/packages/@expo/config-plugins/build/plugins/withMod.js:104:21)
    at async interceptingMod (/home/runner/work/expo/expo/packages/@expo/config-plugins/build/plugins/withMod.js:104:21)
/home/runner/work/expo/expo/node_modules/@expo/spawn-async/src/spawnAsync.ts:67
          : new Error(`${command}${argumentString} exited with non-zero code: ${code}`);
            ^
```

**Comment by brentvatne** [comment]
@wschurman - see https://linear.app/expo/issue/ENG-13991/updates-e2e-test-doesnt-use-local-versions-of-all-packages

we updated this in another pr and then it failed due to fingerprint issue

**Comment by alanjhughes** [comment]
### Merge activity

* **Oct 30, 8:26 PM EDT**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/expo/expo/32475).

**Comment by DrZoidberg09** [comment]
For me it also breaks prebuild on the newest version of Expo 52 preview with the exact same error by wschurman

**Comment by roni-castro** [comment]
The error seems fixed in version `^52.0.0-preview.18` @DrZoidberg09.  I'll just need to look into this new [issue](https://github.com/expo/expo/issues/32515) now. I'm encountering it too with the splash screen.

**Comment by sajorahasan** [comment]
I am facing the below issue with expo 52.0.0-preview.18

````
✔ Cleared android, ios code
✔ Created native directories
✔ Updated package.json | no changes
✖ Prebuild failed
Error: [android.dangerous]: withAndroidDangerousBaseMod: It was not possible to generate splash screen './assets/adaptive-icon.png'. Expected positive integer for width but received 31.200000000000003 of type number
Error: [android.dangerous]: withAndroidDangerousBaseMod: It was not possible to generate splash screen './assets/adaptive-icon.png'. Expected positive integer for width but received 31.200000000000003 of type number
    at resizeAsync (/Users/Hasan/Desktop/Hasan/Workspace/time-of-my-life/node_modules/@expo/image-utils/src/Image.ts:89:11)
    at async generateImageAsync (/Users/Hasan/Desktop/Hasan/Workspace/time-of-my-life/node_modules/@expo/image-utils/src/Image.ts:235:14)
    at async generateIconAsync (/Users/Hasan/Desktop/Hasan/Workspace/time-of-my-life/node_modules/@expo/prebuild-config/src/plugins/icons/withAndroidIcons.ts:406:34)
    at async /Users/Hasan/Desktop/Hasan/Workspace/time-of-my-life/node_modules/@expo/prebuild-config/src/plugins/icons/withAndroidIcons.ts:308:21
    at async Promise.all (index 0)
    at async generateMultiLayerImageAsync (/Users/Hasan/Desktop/Hasan/Workspace/time-of-my-life/node_modules/@expo/prebuild-config/src/plugins/icons/withAndroidIcons.ts:307:3)
    at async setIconAsync (/Users/Hasan/Desktop/Hasan/Workspace/time-of-my-life/node_modules/@expo/prebuild-config/src/plugins/icons/withAndroidIcons.ts:132:3)
    at async /Users/Hasan/Desktop/Hasan/Workspace/time-of-my-life/node_modules/@expo/prebuild-config/src/plugins/icons/withAndroidIcons.ts:60:7
    at async action (/Users/Hasan/Desktop/Hasan/Workspace/time-of-my-life/node_modules/@expo/prebuild-config/node_modules/@expo/config-plugins/src/plugins/withMod.ts:228:23)
    at async interceptingMod (/Users/Hasan/Desktop/Hasan/Workspace/time-of-my-life/node_modules/@expo/prebuild-config/node_modules/@expo/config-plugins/src/plugins/withMod.ts:109:21)
error: script "prebuild" exited with code 1
````

**Comment by izakfilmalter** [comment]
Running into the same error.

**Comment by ludwig-pro** [comment]
So do I, with `"expo-splash-screen": "~0.29.1",`

image

**Comment by elfennani** [comment]
Anybody managed to fix it?

**Comment by mubinansari** [comment]
Facing the same issue 😞

**Comment by meftunca** [comment]
I can't get android build because of this issue. Please share an update for this issue

**Comment by shiroyasha9** [comment]
I was able to get my android builds working by adding the below `resolutions` to my package.json 

```json
	"resolutions": {
		"@expo/image-utils": "^0.6.3",
		"@expo/config-plugins": "~9.0.7"
	},
```

This is not a proper fix, but yeah it works.

**Comment by meftunca** [comment]
It worked properly for me after removing the .expo directory

**Pull request merged**
