### PR TITLE
[docs] Fix typo in expo-contacts documentation

### PR DESCRIPTION
**Pull request by ttebify**
# Why

This pull request fixes a typo in the expo-contacts documentation. The phrase "You can configure expo-calendar" should be changed to "You can configure expo-contacts". This is a small but important fix that will improve the accuracy of the documentation and make it easier for developers to use the library.

# How

The phrase "You can configure expo-calendar" was changed to "You can configure expo-contacts". 

# Test Plan
The application was built successfully

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [x] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Review by amandeepmittal — COMMENTED** [review]
Thanks for catching this typo @ttebify! Can I ask you to backport these changes to `unversioned` docs so the for `expo-contacts`: https://github.com/expo/expo/tree/main/docs/pages/versions?

**Comment by ttebify** [comment]
> 

Sure, I will do that now.

**Comment by ttebify** [comment]
> Thanks for catching this typo @ttebify! Can I ask you to backport these changes to `unversioned` docs so the for `expo-contacts`: https://github.com/expo/expo/tree/main/docs/pages/versions?

Done

**Review by amandeepmittal — APPROVED** [review]
Thank you so much for fixing this and backporting these changes! Also, congrats on your first contribution and welcome to the community 🎉

**Pull request merged**
