### PR TITLE
[TS] Upgrade packages to TypeScript 4.0

### PR DESCRIPTION
**Pull request by barthap**
# Why

Upgraded TypeScript to 4.0.2 to keep us more up-to-date. All new features are described [here](https://devblogs.microsoft.com/typescript/announcing-typescript-4-0)

One of them is support for `@deprecated` annotation, I opened a separate PR: #9959.

One breaking change is that now `delete` can be used only on optionals:
```ts
type SomeType = {
  a?: number;
  b: number;
};
const someObj: SomeType = { a: 1, b: 2 };

delete someObj.a;   // OK
delete someObj.b;   // ERROR: The operand of a 'delete' operator must be optional.
```

# How

Followed #8280 and did it the same way.

Updated `typescript` and `ts-jest` in `expo-module-scripts`, resolved breaking change conflicts, rebuilt packages.

# Test Plan
Ran `et check-packages -a` until all packages passed.

### CODE REVIEW

**Review by ide — APPROVED** [review]
Make sure that this CI failure is not related before committing:

```
[12:00:08] Module not found: Error: Can't resolve 'react-native-reanimated' in '/home/runner/work/expo/expo/node_modules/@react-navigation/drawer/lib/module/views'
[12:00:08] Error: Module not found: Error: Can't resolve 'react-native-reanimated' in '/home/runner/work/expo/expo/node_modules/@react-navigation/drawer/lib/module/views'
    at /@expo/xdl@57.9.32/src/Webpack.ts:281:23
    at finalCallback (/home/runner/.config/yarn/global/node_modules/webpack/lib/Compiler.js:257:39)
    at onCompiled (/home/runner/.config/yarn/global/node_modules/webpack/lib/Compiler.js:265:20)
    at /home/runner/.config/yarn/global/node_modules/webpack/lib/Compiler.js:670:21
    at eval (eval at create (/home/runner/.config/yarn/global/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:46:1)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by barthap** [comment]
Hey @ide,
I have already asked about it, and @tsapeta told me that it was caused by @bbarthec doing _Reanimated v2_ stuff.

**Review by bbarthec — APPROVED** [review]

**Review by sjchmiela — APPROVED** [review]
Looks ok to me, the CI fail should be gone by now on `master`, so just rebase to see it fixed! 👍

**Comment by barthap** [comment]
After rebasing onto current master the CI passes 🎉

**Review by lukmccall — APPROVED** [review]
LGTM 🎉🎉🎉 Awesome 🚀🚀🚀

**Pull request merged**
