### PR TITLE
[android] remove GCM

### PR DESCRIPTION
**Pull request by esamelson**
# Why

GCM is now fully deprecated -- according to https://developers.google.com/cloud-messaging the server APIs were turned off in May -- so we are safe to fully remove it from the client and standalone apps. This should fix the issue described in https://github.com/expo/expo/issues/4207

# How

Grepped for GCM in the Android directory and removed all references

# Test Plan

Made debug and release mode builds of the Expo client and tested push notifications from published NCL. I was able to get an FCM token and receive a notification just fine.

### CODE REVIEW

**Review by tsapeta — APPROVED** [review]
Looks good 😉 👍

**Comment by esamelson** [comment]
It turns out the client's GCM implementation still works perfectly fine even though Google says they shut down the server APIs 😕 will leave this unmerged for now, we'll need to be more careful about this since people might still be relying on GCM in prod.

**Comment by sjchmiela** [comment]
I may be wrong, but I think in SDK37 we fully deprecated the ability to use notifications without an FCM project, so we should be safe to remove GCM in SDK39, so this pull request could be updated and merged. What do you think?

**Comment by esamelson** [comment]
seems reasonable to me! I might be able to find some spare minutes next week to update this PR but would also welcome if someone else wanted to take it over. 😇

**Comment by ide** [comment]
With expo-notifications, we probably can go ahead and do this, if it's even necessary anymore.

**Pull request closed without merging**
