### PR TITLE
[constants][updates] Disable build phase for simulator debug builds

### PR DESCRIPTION
**Pull request by fson**
# Why

`expo-constants` and `expo-updates` modules include scripts that are executed in the iOS build process as a part of the "Bundle React Native code and images" build phase.
- `expo-constants/scripts/get-app-config-ios.sh`: evaluates app config and copies it to the resource bundle of the app
- `expo-updates/scripts/create-manifest-ios.sh`: builds an asset manifest using Metro and writes it to the resource bundle of the app

These scripts take time to execute and our data shows they're also a key source of build errors in custom development client builds. However, executing the scripts when making a development build is unnecessary and can be avoided. (The app config / manifest is loaded from the 

# How

These scripts now follow the logic from [`react-native-xcode.sh`](https://github.com/expo/react-native/blob/0e9b4f9eea0f8ee316fa7ba6b7d2ad26325f8077/scripts/react-native-xcode.sh#L30-L35). If this is a simulator build using the `Debug` configuration, the scripts won't run. This behavior can be overridden using environment variables `FORCE_BUNDLING` (always run) and `SKIP_BUNDLING` (never run).

I believe we could also speed up `Debug` builds for *physical devices* by adding `SKIP_BUNDLING` to this phase in our Xcode templates, same way as we do in BareExpo:
https://github.com/expo/expo/blob/2765aaa598b50e086bbd3bc51b6c6f4619a7f8c2/apps/bare-expo/ios/BareExpo.xcodeproj/project.pbxproj#L395
However, I'd like to hear if others think this is a good idea before implemeting that change – thus saving it for a separate PR. This PR only affects simulator builds.

# Test Plan

Manually tested, both in a custom dev client and in Expo Go, that following code works after these changes:
- `<Image style={{ width: 200, height: 200 }} source={require('./assets/icon.png')} />` – image loading not affected by omitting the manifest/config from the resource bundle
- `<Text>{JSON.stringify(ExpoConstants.manifest)}</Text>` – manifest is still accessible through constants package

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.io and README.md).
- [ ] This diff will work correctly for `expo build` (eg: updated `@expo/xdl`).
- [ ] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Review by bbarthec — APPROVED** [review]
It looks fine to me 👍

**Review by esamelson — COMMENTED** [review]
Looks good, thanks for the comprehensive test plan.

My only comment is that I think a lot of the debug builds on EAS build are in fact for physical devices, and so might still run into issues with this script. I think that neither of these scripts should be necessary for debug builds, regardless of the target, so I wonder if we can just remove the `&& [[ "$PLATFORM_NAME" == *simulator ]]` piece from each.

Alternatively, I like your suggestion of adding the `SKIP_BUNDLING` flag to all debug builds because we could keep the logic the same within all three scripts, and also the actual bundling script would also be skipped (which is slow). However, I don't have a good understanding of why react-native-xcode.sh doesn't skip bundling by default for physical device debug builds (is there some issue with loading bundles or assets over LAN on a physical device??) and would want to understand that better before making that call.

**Comment by fson** [comment]
Thanks for the reviews @bbarthec and @esamelson!

I've changed the code to skip these scripts for debug builds targeting physical devices too.

As for `SKIP_BUNDLING`, I'll try to find out why it isn't the default in `react-native-xcode.sh`. If there isn't a good reason for that, changing this upstream might also be a good idea as it would bring the speedups to existing projects as well (eventually), and not just new/ejected projects.

**Review by esamelson — APPROVED** [review]
Cool, sounds great. This looks good to me.

**Pull request merged**
