### PR TITLE
[Location][Android] Check for null value of mLocationClient to prevent a crash

### LINKED ISSUE #11089: Unable to start receiver expo.modules.taskManager.TaskBroadcastReceiver: java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.android.gms.tasks.Task com.google.android.gms.location.FusedLocationProviderClient.getLastLocation()' on a null object reference
### Summary of Issue 

Only for some users, the apps crashes randomly on background

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

image

image

### Reproducible Demo

crashlytics screenshot
image

sample code
image

 
### Expected Behavior vs Actual Behavior

The app run normally

### PR DESCRIPTION
**Pull request by zakharchenkoAndrii**
# Why

Resolves #11089 

PR Fixes android crash that is produced by `mLocationClient.getLastLocation()` when `mLocationClient` is `null`

```
java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.android.gms.tasks.Task com.google.android.gms.location.FusedLocationProviderClient.getLastLocation()' on a null object reference
    at expo.modules.location.taskConsumers.LocationTaskConsumer.didReceiveBroadcast(LocationTaskConsumer.java:114)
    at expo.modules.taskManager.TaskService.handleIntent(TaskService.java:313)
    at expo.modules.taskManager.TaskBroadcastReceiver.onReceive(TaskBroadcastReceiver.java:15)
    at android.app.ActivityThread.handleReceiver(ActivityThread.java:4478)
    at android.app.ActivityThread.access$1600(ActivityThread.java:301)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2169)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:246)
    at android.app.ActivityThread.main(ActivityThread.java:8595)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

java.lang.RuntimeException: Unable to start receiver expo.modules.taskManager.TaskBroadcastReceiver: java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.android.gms.tasks.Task com.google.android.gms.location.FusedLocationProviderClient.getLastLocation()' on a null object reference
    at android.app.ActivityThread.handleReceiver(ActivityThread.java:4487)
    at android.app.ActivityThread.access$1600(ActivityThread.java:301)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2169)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:246)
    at android.app.ActivityThread.main(ActivityThread.java:8595)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

# How

Why:
After killing the app and destroying the Main Activity `didReceiveBroadcast` has been called and since objects were unregistered (`didUnregister`) we are calling `mLocationClient.getLastLocation()` on a null object hence receiving a crash.

How:
Added null check to prevent a crash.

# Test Plan
Unfortunately, I haven't managed to reproduce this issue on my devices. But since we are receiving Sentry crash reports about that, the issue is still valid.

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] This diff will work correctly for `expo build` (eg: updated `@expo/xdl`).
- [x] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Review by lukmccall — COMMENTED** [review]
Thanks for your contribution. Looks good 🚀
However, we shouldn't clean the `TaskConsumer` somehow rather than just omitting this case by adding if? cc @byCedric

**Comment by zakharchenkoAndrii** [comment]
> Thanks for your contribution. Looks good 🚀 However, we shouldn't clean the `TaskConsumer` somehow rather than just omitting this case by adding if? cc @byCedric

Hi @lukmccall, not sure that I get your point right 😅 .
Do you mean to stop/null everything like that and return after that?
```
    stopForegroundService();
    mTask = null;
    mPendingIntent = null;
    mLocationRequest = null;
 ```

**Comment by lukmccall** [comment]
Not exactly 😅 
Maybe I missed understanding something, but I think the `LocationTaskConsumer` should be unregistered. So it shouldn't get an intent in the `didReceiveBroadcast` anyway. But for now, I'll merge your fix and I'll try to investigate that deeper later.

**Review by lukmccall — APPROVED** [review]
🥇

**Comment by islamouzou** [comment]
Is this fixed already or it's for SDK 44  ? because i still receive the error .

**Pull request merged**
