### PR TITLE
Fix issue with es-419 locale

### LINKED ISSUE #21414: [expo-localization] Exception: Unsupported ISO 3166 country: es_419
### Minimal reproducible example

https://gist.github.com/andresribeiro/569e4d70afe1778e8f2541e301433017

### Summary

The following error appears on Play Console pre-launch report:

```
Exception com.facebook.react.common.JavascriptException: Error: Call to function 'ExpoLocalization.getLocales' has been rejected.
→ Caused by: java.lang.IllegalArgumentException: Unsupported ISO 3166 country: es_419, js engine: hermes, stack:
_construct@1:105491
Wrapper@1:105136
_createSuperInternal@1:645189
CodedError@1:645474
findBestAvailableLanguage@1:703297
getBestAvailableLanguage@1:703599
setBestAvailableDayJsLocale@1:692514
anonymous@1:692458
loadModuleImplementation@1:73062
guardedLoadModule@1:72611
metroRequire@1:72239
anonymous@1:690154
loadModuleImplementation@1:73062
guardedLoadModule@1:72611
metroRequire@1:72239
anonymous@1:79390
loadModuleImplementation@1:73062
guardedLoadModule@1:72568
metroRequire@1:72239
global@1:71823
  at com.facebook.react.modules.core.ExceptionsManagerModule.reportException (ExceptionsManagerModule.java:72)
  at java.lang.reflect.Method.invoke
  at com.facebook.react.bridge.JavaMethodWrapper.invoke (JavaMethodWrapper.java:372)
  at com.facebook.react.bridge.JavaModuleWrapper.invoke (JavaModuleWrapper.java:188)
  at com.facebook.jni.NativeRunnable.run
  at android.os.Handler.handleCallback (Handler.java:938)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage (MessageQueueThreadHandler.java:27)
  at android.os.Looper.loop (Looper.java:223)
  at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run (MessageQueueThreadImpl.java:228)
  at java.lang.Thread.run (Thread.java:923)
```

It might be related to these 2 issues from `react-native-localize`:

https://github.com/zoontek/react-native-localize/issues/31
https://github.com/zoontek/react-native-localize/issues/36

### Environment

System:
  OS: Linux 5.4 Linux Mint 20.3 (Una)
  Shell: 5.8 - /usr/bin/zsh
Binaries:
  Node: 19.7.0 - /usr/bin/node
  Yarn: 1.22.19 - /usr/bin/yarn
  npm: 9.5.0 - /usr/bin/npm
  Watchman: 20220605.192726.0 - /usr/local/bin/watchman
npmPackages:
  expo: ~48.0.4 => 48.0.4 
  react: 18.2.0 => 18.2.0 
  react-native: 0.71.3 => 0.71.3 
npmGlobalPackages:
  eas-cli: 3.7.2
  expo-cli: 6.3.2
Expo Workflow: managed

### PR DESCRIPTION
**Pull request by aleqsio**
# Why

Fixes https://github.com/expo/expo/issues/21414

# How

Was able to narrow down the reproduction steps thanks to @newfylox.

# Test Plan

Tested to make sure it returns correct null values on the es-419 locale.

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Review by alanjhughes — APPROVED** [review]

**Comment by newfylox** [comment]
@aleqsio Thanks for the quick fix. I just wanted to know if it only fixes `es-419` locale of if it fixes other locales with the same bug?

https://github.com/expo/expo/issues/21414#issuecomment-1745039086

`es_IC, en, pl_SP, es_419, nl, ar_XB` It also bugs with `nl` and `en` alone, even `fr`will crash.

Thanks

**Comment by aleqsio** [comment]
it will nullify just the currencySymbol and currencyCode on those locales - should fix all of them

**Comment by Voznov** [comment]
When do you plan to release new version of expo-localization with this fix?

**Comment by aleqsio** [comment]
@newfylox actually languageTag will never be null on the return object - it should also always include at least one element.

**Pull request merged**
