### PR TITLE
[expo] Remove deprecated module errors

### PR DESCRIPTION
**Pull request by EvanBacon**
# Why

The modules exposed from expo `import { ... } from 'expo'` have been removed for well over a year now.

# How

- Delete all import errors, with exception `Notifications`, and `Linking` which only had alternatives added a couple versions ago.
- Delete `DangerZone`
- Deleted `expo/DangerZone` -- this file wasn't even included in the package.json files array so it's unused.

### CODE REVIEW

**Review by brentvatne — APPROVED** [review]

**Review by ide — CHANGES_REQUESTED** [review]
* Some dependencies like `expo-file-system` are no longer used and can be removed from package.json
* CHANGELOG needs to be updated and marked with a breaking change

After this, does it also make sense to remove `deprecated.ts`? Linking was deprecated on June 4 last year before SDK 38 and Notifications was deprecated on August 3 before SDK 39.
* If we decide to remove Notifications, it might make sense to do that in its own commit since there's a whole Notifications directory to remove.
* After removing `DangerZone.ts` and `deprecated.ts`, does it make sense to remove the build step that creates ExpoLazy.ts with Babel and just use `tsc`?

**Comment by brentvatne** [comment]
@ide - those will be removed in another pr where we removed globals https://github.com/expo/expo/blob/master/packages/expo/src/globals.ts

**Comment by ide** [comment]
Some of the dependencies are used in globals but there are a few that are completely unused after this PR, like FS and secure store.

**Comment by brentvatne** [comment]
epxo-file-system is a peer dep of some of the other globals i believe - like expo-asset: https://github.com/expo/expo/blob/master/packages/expo-asset/src/PlatformUtils.ts#L4

**Review by ide — APPROVED** [review]

**Pull request merged**
