### PR TITLE
[docs] Fix missing rename and add clarification of common concrete values

### PR DESCRIPTION
**Pull request by brentvatne**
# Why

In https://github.com/expo/expo/pull/12881 I believe we forgot to update some text. While there I also thought it would be useful to clarify some possible / common values for this string.

### CODE REVIEW

**Comment by randomhajile** [comment]
I believe @wkozyra95 wanted to keep the field as `schemeBuildConfiguration` for now (comment [here](https://github.com/expo/eas-cli/pull/394#issuecomment-838048395)).

**Comment by brentvatne** [comment]
interesting. what stood out to me was that we updated it here: https://github.com/expo/expo/blame/eb3eb8aea82b2dee6701c03c1f337e16365cb4c2/docs/pages/build/eas-json.md#L198 but then didn't update it below where we provide descriptions for the fields, so maybe we should roll back the docs change on line 198 instead of making the change proposed in this PR?

**Comment by randomhajile** [comment]
Right, this PR made me realize that I used the wrong name in the JSON schema. I think changing that one back to `schemeBuildConfiguration` is the correct solution.

**Comment by wkozyra95** [comment]
Yes we want to keep old field, it just error in docs, fixed it here https://github.com/expo/expo/commit/7f355146fca16f119bd83fd6550c01c3552254c4

**Comment by wkozyra95** [comment]
A sorry @brentvatne, I didn't notice that you also had other changes there, please reopen PR if you still want to add them

**Comment by brentvatne** [comment]
np, added it in 49bb247e43b70e1c3951b4503932a15c59febd33

**Pull request closed without merging**
