### PR TITLE
fix(expo-file-system): remove uuid-js dependency

### PR DESCRIPTION
**Pull request by jaulz**
# Why

`uuid-js` is very old and it not really necessary for the generation of a simple UUID.

# How

The UUID generation comes from https://gist.github.com/jed/982883 (which is linked by https://github.com/uuidjs/uuid for the smallest possible UUID generation).

# Test Plan

Use `createDownloadReusable` in any form.

### CODE REVIEW

**Comment by sjchmiela** [comment]
Hey @jaulz, thank you for taking your time to submit this pull request — was there any issue with using `uuid-js` or is it just an effort to keep `expo-file-system` clear of any old dependencies?

**Comment by SimenB** [comment]
If you don't mind keeping the dep, you might consider switching to `uuid` instead - it has 21M weekly downloads vs 100k weekly downloads for `uuid-js`.

(fwiw, uuid is probably coming to JS natively as well, but still stage 1: https://github.com/tc39/proposal-uuid)

**Comment by jaulz** [comment]
Actually, I found it because there was no proper license information in the package and then I thought I could remove it at the same time 😉 What do you prefer? I can also change it and add `uuid` instead.

**Comment by ide** [comment]
We use uuid-js in many other packages so removing it here doesn't have any immediate term effect. What is the actual file size of `uuid/v4` compared to `uuid-js`? (Runtime speed probably does not matter since we are generating on the order of tens to hundreds of UUIDs on the client, not millions.)

**Comment by jaulz** [comment]
Following the sizes of the two packages. Though, while doing a quick research I saw that there might be an even smaller option called [nanoid](https://github.com/ai/nanoid). The only thing is that it just generates random strings and no UUIDs but is that something we should worry about?

## uuid
Keep in mind that this is the size of the whole package and not just `uuid/v4`.

image


## uuid-js
image


## nanoid
image

**Comment by ide** [comment]
uuid/v4 seems fine then but please change it across the board instead of in just one place.

**Comment by jaulz** [comment]
Okay, now it's updated in every package. Though, it still exist in some `package.json` in `ios` folder. What about those?

**Comment by ide** [comment]
Thanks. I’ll take a look at this today.

**Pull request closed without merging**
