### PR TITLE
[Android] drop support for Android 4.4

### PR DESCRIPTION
**Pull request by bbarthec**
# What

Drops support for Android 4.4 (KitKat)
Updated `targetSdkVersion = 28` (Android Pie)
Updated `Gradle = 4.10.2`
Added local `CreditCardEntry.aar` lib with version `1.4.9` as this [version](https://github.com/dbachelder/CreditCardEntry/releases) on github is not pushed to any maven/gradle/android repo. 

# Test Plan

NCL up & running

### CODE REVIEW

**Review by esamelson — COMMENTED** [review]
Thanks! This generally looks good to me, just a few questions:
- was all of the .gradle reformatting intentional? there are so many changes in this diff it's pretty hard to tell what the actual changes are.
- last time we updated the targetSdkVersion (to 26) we had to add support for notification channels and adaptive icons. Are there any changes like that for targeting SDK 28 that you're aware of, and did you try tapping through all of the screens in NCL to see if anything broke?

Let's hold off on merging this for now until after the release, since we're not upgrading the JSC version this release and so don't need to drop support for 4.4 yet.

**Comment by bbarthec** [comment]
@esamelson regarding `.gradle` files: yes, it was intentional as AndroidStudio suggests reformatting over & over, so most changes swaps `4 spaces` with `2 spaces` indents.
Regarding upgrading `targetSdkVersion` I've briefly checked some random screens, but I'll check them all then.

**Comment by ide** [comment]
@esamelson looked at the API changes between 26 and 28 and it seems like there are very few breaking changes so I'll let him decide whether we want to separate this PR or take it as-is. In the future, separating unrelated changes is helpful so that it's easier to review and revert PRs and compartmentalize risk.

**Comment by bbarthec** [comment]
Moved upgrading part into https://github.com/expo/expo/pull/2446

**Review by esamelson — APPROVED** [review]
looks great. Thank you!!

Let's wait on merging this until #2330 lands so that we can be sure to get working shell app bases for SDK 25-30 with Android 4.4 support.

**Pull request merged**
