### PR TITLE
[android][file-system] adds constant externalDirectory

### PR DESCRIPTION
**Pull request by dsgrillo**
# Why

Adds support for reading/writing to the external directory in Android (usually the SD Card).
https://expo.canny.io/feature-requests/p/external-storage-api

# How

Added a new constant in the Android version, following the same convention as the others constants.

# Test Plan

Make sure it doesn't break in android and ios builds.

### CODE REVIEW

**Review by sjchmiela — COMMENTED** [review]
Thank you very much for the contribution! Unfortunately, there is one problem with this change which should be fixed before merging:

as per [the method's documentation](https://developer.android.com/reference/android/content/Context#getExternalFilesDir(java.lang.String)):
- > Shared storage may not always be available, since removable media can be ejected by the user. Media state can be checked using Environment#getExternalStorageState(File).
- > The returned path may change over time if different shared storage media is inserted, so only relative paths should be persisted.

I'm afraid adding this value as a constant may make it seem like it's a constant (while it can change), moreover, it can become unavailable in runtime! In my opinion it would be better to create an exported method which would resolve to a current value of `getExternalFilesDir()` (or `null`).

Let me know if you'd be still interested in implementing this feature, sorry for the delay! 🙇

**Comment by yfunk** [comment]
Any updates on this feature? Since internal storage has limited space for app-specific data ([anywhere from ~500MB to 6.5GB](https://stackoverflow.com/questions/9198440/is-there-a-maximum-size-to-android-internal-storage-allocated-for-an-app)) access to external storage would be very important to have if you are handling larger files. This would not benefit Expo users, but since `react-native-fs` and `rn-fetch-blob` are both now essentially dead a lot of people are also pointing to `expo-file-system` for the bare workflow.

**Comment by yfunk** [comment]
> I'm afraid adding this value as a constant may make it seem like it's a constant (while it can change), moreover, it can become unavailable in runtime! In my opinion it would be better to create an exported method which would resolve to a current value of `getExternalFilesDir()` (or `null`).

@sjchmiela I don't think something like `FileSystem.externalDocumentDirectory` by itself would suggest the value being a constant. Assuming it updates nicely when the path changes or becomes unavailable it may be better for consistency to leave it a value that can be a `string` or `null` (just like `documentDirectory` and `cacheDirectory` in the current type definitions) and let each developer handle that case themselves (just like they would have to if it was a method).

In theory `getExternalFilesDir()` should resolve to the primary shared storage (`/storage/emulated/0/Android/data/{app}`) most of the time, which is located on the devices internal storage and therefore should not change or become unavailable. Still this change could mean that functions get called with `null` as the `uriStr` parameter more often, which currently causes the promise to be rejected with the following error message:
```
[Error: Attempt to invoke virtual method 'boolean java.io.File.exists()' on a null object reference]
```
The reason being that `checkIfFileExists`/`checkIfFileDirExists` try to call `exists()` on a null reference. To make this issue easier to catch these methods could be adjusted to throw a clearer error message.

@dsgrillo Also i would (again for better consistency) suggest to add **two** new values `externalDocumentDirectory` and `externalCacheDirectory` which resolve to `getExternalFilesDir()` and `getExternalCacheDir()` accordingly.

If i can get some feedback on these suggestions i would also be willing to implement them.

**Comment by brentvatne** [comment]
>  I don't think something like FileSystem.externalDocumentDirectory by itself would suggest the value being a constant. Assuming it updates nicely when the path changes or becomes unavailable it may be better for consistency to leave it a value that can be a string or null (just like documentDirectory and cacheDirectory in the current type definitions) and let each developer handle that case themselves (just like they would have to if it was a method).

i think this leads to an inconsistent api. everywhere in the expo sdk where we expose a property like this it is a constant. i would not expect the value to change over time if i was interacting with a property like this, especially if that is true for the adjacent documentDirectory and cacheDirectory properties. i think we should do two things:

- `getExternalFilesDirectory()` as @sjchmiela suggested
- add some mechanism to be notified when the external file directory changes (becomes null or something else).
- on top of this, we can build a hook `useExternalFilesDirectory()`

**Pull request closed without merging**
