### PR TITLE
[docs][clipboard] Fixes & update examples

### PR DESCRIPTION
**Pull request by barthap**
# Why

To keep our docs clean, beautiful and pleasant to read (etc.) ☺️ 

Resolves ENG-4380, part of ENG-3319

# How

- Updated example on the docs page
- Added smaller examples to image methods
- Fixed some casing issues

# Test Plan

Ran docs locally

### CODE REVIEW

**Comment by barthap** [comment]
Maybe I should add a full Snack example for images? sth like this https://snack.expo.dev/@barthap10/clipboard-image
Or HTML 🤔

**Review by tsapeta — APPROVED** [review]

**Comment by Simek** [comment]
> Maybe I should add a full Snack example for images? sth like this https://snack.expo.dev/@barthap10/clipboard-image Or HTML 🤔

I think It would be nice to add this example before the API section, in the form similar to `ScreenCapture` docs for example:
* https://docs.expo.dev/versions/v44.0.0/sdk/screen-capture/#usage

**Review by Simek — APPROVED** [review]
LGTM! 👍

**Comment by barthap** [comment]
> think It would be nice to add this example before the API section

Yeah that's what I mean, there's already such example for plain text content 😁

**Review by bbarthec — APPROVED** [review]

**Pull request merged**
