### PR TITLE
[router] fix router.push not pushing the same route multiple times

### PR DESCRIPTION
**Pull request by marklawlor**
# Why

This PR reinstates the usage of the `NAVIGATE` action for navigation instead of the PUSH action. However, it modifies the behaviour of "PUSH" actions to be determined by the route key instead of relying on the getID() function.

According to the React Navigation documentation for push:

> "The push action adds a route on top of the stack and navigates forward to it. This differs from navigate in that navigate will pop back to earlier in the stack if a route of the given name is already present there. push will always add on top, so a route can be present multiple times."
[Source: React Navigation Documentation](https://reactnavigation.org/docs/stack-actions/#push)

However, the documentation can be misleading, as push actually operates in two different modes. If no getID() function is present, it behaves as described above. Otherwise, it determines the IDs of the screens, and if a match in history is found, that screen is spliced out of history and pushed to the top ([source](https://github.com/react-navigation/react-navigation/blob/13d4aa270b301faf07960b4cd861ffc91e9b2c46/packages/routers/src/StackRouter.tsx#L269-L290)).

Expo Router should adhere to the default behavior of React Navigation, as it is what most applications use, so the `getID()` behaviour is not ideal.

Additionally, the NAVIGATION action also has multiple modes, depending on whether getId() is present. The first mode checks for a unique key, then falls back to getId(), and finally to name. If a unique key is passed in the payload, NAVIGATE works the same as a push.

## Issues with this approach

This approach fixes Expo Router's APIs, but doesn't fix 3rd party Navigators/Actions that manually send `PUSH` actions.

# How

# Test Plan

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Comment by dpsoccerdude101** [comment]
Hi @marklawlor, 

I noticed that the markdown for the source in your PR description leads to `chat.openai.com` instead of a relevant source. Can you please add the correct source URL in the markdown again? 

Many thanks,
Dennis.

**Comment by marklawlor** [comment]
@dpsoccerdude101 the one time I try to use chatgpt to write clearer descriptions :man_facepalming: I updated the source link

**Comment by dpsoccerdude101** [comment]
> @dpsoccerdude101 the one time I try to use chatgpt to write clearer descriptions 🤦‍♂️ I updated the source link

Don’t worry; it happens to me, too!

Thank you for updating the document and your work for Expo Router. I am excited to try out the `dismiss` & `dismissAll` APIs when released!

**Review by EvanBacon — APPROVED** [review]
lgtm. Ensure this runs in development mode before landing

**Comment by kennethstarkrl** [comment]
@marklawlor Just a heads up this broke push again for me. Version 3.5.2. It's back to not pushing screens that have the same path but different slugs. I'm currently using a patch of https://github.com/expo/expo/pull/26678 to get working. I don't know why a new Id isn't getting seen by the navigator when the path is the same but the slug params are different.

**Pull request merged**
