### PR TITLE
[docs][ios][clipboard] Clarify documentation about `setUrlAsync`

### PR DESCRIPTION
**Pull request by mhammerc**
# Why

While reading the documentation about `Clipboard.setUrlAsync()`, I was wondering what this is about.

https://docs.expo.dev/versions/v46.0.0/sdk/clipboard/#seturlasyncurl

# How

According to the iOS source code:

https://github.com/expo/expo/blob/54b2c8c7e4d619b3ea0f6ad60dc4765079346f2b/packages/expo-clipboard/ios/ClipboardModule.swift#L40-L50

The function just set the `url` property instead of the `string` property from `UIPasteboard.general`.

According to iOS documentation:

https://developer.apple.com/documentation/uikit/uipasteboard?language=objc (see section “Pasteboard Items and Representation Types”)

https://developer.apple.com/documentation/uikit/uipasteboard/1622081-url?language=objc

The reason to use `url` instead of `string` is just what I documented.

There may be other behaviors I am not aware of from using `setUrlAsync`.

# Test Plan

Not applicable.

# Checklist

- [X] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [X] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] *Not tested as this is just documentation.* This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

# Footnote

I usually don't make such small PRs for typos or little things like this.

But, I ended up wondering multiple times what is `setUrlAsync` and why does it exist. I'm probably not the only one.

### CODE REVIEW

**Review by barthap — COMMENTED** [review]
I'm ok with your clarification 👍 

However, editing the `.ts` file is not enough. To pass the CI, you need to run `yarn build` inside the `packages/expo-clipboard` directory, as described in [contributing guide](https://github.com/expo/expo/blob/main/CONTRIBUTING.md#%EF%B8%8F-editing-sdk-packages).
The docs metadata should also be updated (`expotools generate-docs-api-data -p expo-clipboard` command), but I can take care of that.

**Comment by mhammerc** [comment]
> I'm ok with your clarification 👍
> 
> However, editing the `.ts` file is not enough. To pass the CI, you need to run `yarn build` inside the `packages/expo-clipboard` directory, as described in [contributing guide](https://github.com/expo/expo/blob/main/CONTRIBUTING.md#%EF%B8%8F-editing-sdk-packages). The docs metadata should also be updated (`expotools generate-docs-api-data -p expo-clipboard` command), but I can take care of that.

I updated the built Typescript files and the documentation with `expotools`!

**Review by barthap — APPROVED** [review]
Looks good, thanks!

I'll wait for CI and then merge

**Review by barthap — CHANGES_REQUESTED** [review]
The CI failed with linter error:
```
🏃‍♀️ Running yarn lint --max-warnings 0
lint script failed, see process output:
stdout > yarn run v1.22.19
stdout > $ expo-module lint --max-warnings 0
stdout > 
stdout > /home/runner/work/expo/expo/packages/expo-clipboard/src/Clipboard.ts
stdout >   107:3  warning  Delete `·`  prettier/prettier
stdout > 
stdout > ✖ 1 problem (0 errors, 1 warning)
stdout >   0 errors and 1 warning potentially fixable with the `--fix` option.
```

You can run `yarn lint --fix` then again `yarn build` and this should be fixed.

**Comment by mhammerc** [comment]
There was a trailing space left in the comment I wrote. It should be fixed.

I'm sorry for this back-and-forth that loose time for each of us.

**Review by barthap — APPROVED** [review]

**Pull request merged**
