### PR TITLE
[dev-menu][android] simplify relationship between dev-menu and dev-client

### PR DESCRIPTION
**Pull request by ajsmth**
# Why

This is the Android side of the refactor done by #16067, which simplifies the relationship between dev menu and dev launcher

# How

- removing the dev menu manager provider / delegate pattern 
- removing the now unused dev menu manager provider file 
- adding manifest / manifestURL props onto the dev menu manager, and passing these manifest values from dev-launcher through to the RN App

# Test Plan

you can pull in these changes and run a local build of the app - specifically testing whether updates to the manifest are passed through to the dev menu

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] This diff will work correctly for `expo build` (eg: updated `@expo/xdl`).
- [x] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Review by esamelson — APPROVED** [review]
LGTM (pending a fix for the one unit test) 🚀

**Comment by ajsmth** [comment]
@esamelson @lukmccall any idea what's wrong with the unit tests here? I'm not sure why it doesn't pick up the new fields in dev menu manager

**Comment by esamelson** [comment]
@ajsmth you might need to add those properties to the `release` version of DevMenuManager (in android/src/release) -- right now it looks like they are only in `debug`.

**Comment by lukmccall** [comment]
Still, something is not right:
```
e: /Users/runner/work/expo/expo/packages/expo-dev-launcher/android/src/release/java/expo/modules/devlauncher/DevLauncherController.kt: (50, 3): 'maybeInitDevMenuDelegate' overrides nothing

e: /Users/runner/work/expo/expo/packages/expo-dev-launcher/android/src/release/java/expo/modules/devlauncher/DevLauncherController.kt: (66, 3): 'maybeSynchronizeDevMenuDelegate' overrides nothing
```

You can actually test that locally by changing the build variant to the releas (https://developer.android.com/studio/run#changing-variant).

**Pull request merged**
