### PR TITLE
[docs] Fix Android Studio menu names, screenshots

### PR DESCRIPTION
**Pull request by karlhorky**
# Why

The Android Studio UI changed, and the old names of the menu items are outdated now

# How

I started the new version of Android Studio and took screenshots

# Test Plan

I tested with the new version of Android Studio

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] This diff will work correctly for `expo build` (eg: updated `@expo/xdl`).
- [x] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Review by Simek — CHANGES_REQUESTED** [review]
Hello @karlhorky, thank you for the update! 👍 

Can you retake the screenshots with transparent background and resize them to 800px in width?

**Comment by karlhorky** [comment]
Hm, <kbd>cmd</kbd>-<kbd>shift</kbd>-<kbd>4</kbd> + <kbd>space</kbd> (to take the transparent background) doesn't seem to also capture the context menu unfortunately... Or did you have other ideas to take it?

**Comment by Simek** [comment]
Oh, that's might be a bit more effort consuming task then. I would take the window and context menu screenshot separately, then merge them in one of graphical programs. If it is too much to ask, please let me know, I can update the problematic image soon.

**Comment by karlhorky** [comment]
Probably won't get around to that soon, so feel free to take over

**Comment by karlhorky** [comment]
@Simek FWIW I think that having the background in the images both:

1. Makes the images smaller (transparent images are larger)
2. Doesn't make too much of a difference with UX, since the background is visible in the images (see the slight variations in background color of the images in screenshots below - it looks almost like they have a color in the background already)

Screen Shot 2022-03-03 at 20 43 22
Screen Shot 2022-03-03 at 20 43 30

**Comment by Simek** [comment]
Sorry, but I have forgot about this issue. 😅  

Let's use those images:
Screenshot 2022-04-12 at 13 01 01
Screenshot 2022-04-12 at 12 57 26

**Comment by Simek** [comment]
It would be also nice to mention that the AVD Manager moves to the corner "dot" menu, when user have at least one project already. There is screenshot for that.

Screenshot 2022-04-12 at 13 06 03

@karlhorky Please, let me know if you are still interested in updating this PR. 🙂

**Comment by karlhorky** [comment]
@Simek sure, so I'll take those images and put them into the docs as they are then, with a small text addition to talk about the top right three dots menu.

**Comment by karlhorky** [comment]
@Simek done, uploaded the images and added the note about the alternate position

**Review by Simek — APPROVED** [review]
Thank you ping on this and for the updates! 🙏  LGTM, let's ship it!

**Comment by Simek** [comment]
> (it avoids installing the latest emulator, which doesn't currently work with Expo).

Can you elaborate on this a bit more? I'm not aware of such issue. 

Also, since it is a bit of topic of this PR, can you create issue or discussion for that instead of continuing the conversation in there?

> If you're interested in these changes, watch that repo for my commits in the next hour or so.

Thanks, I will take a look at this in my free time.

**Comment by karlhorky** [comment]
Here's the commit 🙌 https://github.com/upleveled/system-setup/commit/da62141c087cc4400a97fcb57e1d5fd37d6b11b2

Rendered:

- https://github.com/upleveled/system-setup/blob/main/windows.md#user-content-expo-react-native
- https://github.com/upleveled/system-setup/blob/main/macos.md#user-content-expo-react-native
- https://github.com/upleveled/system-setup/blob/main/linux.md#user-content-expo-react-native

> Can you elaborate on this a bit more? I'm not aware of such issue.

Just installed the latest Android Studio using the **Standard** install like 5 times today on an M1 chip, and every time I tried starting the demo app (`expo init --template blank`) in an API 32 virtual device (Pixel 3A), it failed with `INSTALL_FAILED_INSUFFICIENT_STORAGE`, kind of similar to https://github.com/expo/expo/issues/4186

I tried increasing the storage space to 2000MB, but nothing was helping 🤔 Created a fresh API 30 (Pixel 3A) and no problems.

I'll see if I have time to create an issue over the next weeks...

**Pull request merged**
