### PR TITLE
[ios][splash-screen] Fixed 'No native splash screen registered for given view controller.' warning being shown when app is started in the background (i.e. headless)

### PR DESCRIPTION
**Pull request by grigorigoldman**
# Why

Some times a React Native app maybe started in the background, i.e. headless. For example, when using a push notifications SDK such as `react-native-firebase/messaging`. When a message is received by the device and the app is not running, the app is launched in the background, registers a background message handler, which is then receives the message. 

In this scenario, a `No native splash screen registered for given view controller. Call 'SplashScreen.show' for given view controller first.` is shown when the app is started (in background).

# How

This is an iOS specific issue. I added a conditional check, to ensure that the app is actually active (in foreground) before logging the warning.

# Test Plan

✅ Tested in `apps/bare-expo` to make sure no unexpected side effects are present
✅ Included the fix into custom app, which integrates with `react-native-firebase/messaging` to ensure that when the app is launched in the background, warning is not shown.

### CODE REVIEW

**Review by Kudo — APPROVED** [review]
the change makes sense, thanks for the contribution!

**Comment by krisgerhard** [comment]
Still seeing this error while using expo-splash-screen@0.18.2

**Comment by krisgerhard** [comment]
@Kudo @grigorigoldman I'm still getting this error with SDK 48 when expo-background-fetch@11.1.1 task runs on iOS. Let me know if I can provide some additional information. expo-splash-screen@0.18.2

**Comment by AdityaVandan** [comment]
Although this warning is not breaking anything, but I am getting a lot of Warnings as errors in production because of the mentioned issue

**Comment by GregPetropoulos** [comment]
I am using expo 51 and the **`'SplashScreen.show' has already been called for given view controller`** warning came up after creating a dev build on an ios simulator.

My fix was to wrap the `SplashScreen.hideAsync()` in `async` in the `useEffect` body.

Here's my `_layout` page for the initial `index` page of the app. 

``` javascript
import { ThemeProvider } from '@rneui/themed';
import { useFonts } from 'expo-font';
import { Stack } from 'expo-router';
import * as SplashScreen from 'expo-splash-screen';
import React, { useEffect } from 'react';
import 'react-native-reanimated';
import { SafeAreaProvider } from 'react-native-safe-area-context';
import { StatusBar } from 'expo-status-bar';
import HeaderRight from '@/components/navigation/HeaderRight';
import { BlurView } from 'expo-blur';
import ThemeText from '@/components/ThemeText';
import theme from '@/theme';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { useReactQueryDevTools } from '@dev-plugins/react-query';
// Prevent the splash screen from auto-hiding before asset loading is complete.
SplashScreen.preventAutoHideAsync();

// State management
const queryClient = new QueryClient();

export default function RootLayout() {
	useReactQueryDevTools(queryClient);

	const customFonts = {
		LibreBaskervilleBold: require('../assets/fonts/LibreBaskerville_Bold.ttf'),
		LibreBaskervilleItalic: require('../assets/fonts/LibreBaskerville_Italic.ttf'),
		LibreBaskerville: require('../assets/fonts/LibreBaskerville_Regular.ttf'),
		MontserratExtraBold: require('../assets/fonts/Montserrat_ExtraBold.ttf'),
		MontserratItalic: require('../assets/fonts/Montserrat_Italic.ttf'),
		Montserrat: require('../assets/fonts/Montserrat_Regular.ttf'),
		MontserratBold: require('../assets/fonts/Montserrat_Bold.ttf')
	};
	const [loaded] = useFonts(customFonts);

	useEffect(() => {
		if (loaded) {
			// The async IIFE is what solved the issue
			(async () => await SplashScreen.hideAsync())(); // <--------my solution
		}
	}, [loaded]);

	if (!loaded) {
		return null;
	}

return (
<>
    <StatusBar style='auto' />
         <QueryClientProvider client={queryClient}>
            <ThemeProvider theme={theme}>
                <SafeAreaProvider>
                    <Stack 
                        screenOptions={{
                           headerBlurEffect: 'regular', headerTransparent: true,
                           headerRight(props) { return (<HeaderRight tintColor={theme?.darkColors?.secondary} />);},
                          headerLeft: (props) => (<ThemeText textContent='Paragon' Title={true} textStyle={{ color: theme?.darkColors?.secondary }}/>
                          )}}>
                        <Stack.Screen name='index' options={{headerShown: true}}/>
                       <Stack.Screen name='(tabs)' options={{headerShown: false}}/>
                       <Stack.Screen name='+not-found' />
                    </Stack>
                </SafeAreaProvider>
            </ThemeProvider>
        </QueryClientProvider>
</>
	);
}
```

**Pull request merged**
