### PR TITLE
[iOS][image] SDWebImage support for 3rd party privacy manifest

### PR DESCRIPTION
**Pull request by aparedes**
SDWebImage has been marked by Apple as an sdk that requires a 3rd party privacy manifest.

# Why

Apple has marked SDWebImage as an SDK that requires a [3rd Party Privacy Manifest](https://developer.apple.com/support/third-party-SDK-requirements/)

# How

SDWebImage has been updated on 5.18.7 to include the privacy manifest https://github.com/SDWebImage/SDWebImage/releases/tag/5.18.7

# Test Plan

Built and ran bare-expo app, went through all Components -> Image tasks
image

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Review by tsapeta — COMMENTED** [review]
Looks good now, thank you! Just one more thing – could you revert changes in `expo-image/build/*.js.map`? Looks like you're using version of Node.js below v20 that produces a bit different results 🤔

**Review by tsapeta — APPROVED** [review]
I'm approving it, but will wait for the CI to finish before merging 🙂

**Comment by aparedes** [comment]
@tsapeta It fails on unrelated tests. Is there something I can do about it?

**Comment by tsapeta** [comment]
@aparedes it's fine, this check is failing on the main branch as well. I'm merging it, but I can't tell yet when we'll publish this. See our tracking issue for privacy manifests: https://github.com/expo/expo/issues/27796

**Comment by aparedes** [comment]
Thanks, no worries from me for the release, we are considering expo-image as a replacement of react-native-fast-image, but we haven't made the change, so no rush from me.
But I guess it should be out before the 1st of May. If Apple does really hold to their deadlines https://developer.apple.com/news/?id=3d8a9yyh

**Comment by tsapeta** [comment]
Cool, we'll for sure do it before this date. It will need to be backported to SDK 50 and potentially SDK 49 as well, so it's quite a lot of effort though 😅 Thanks again for helping us!

**Pull request merged**
