### PR TITLE
[expo-calendar] fix Alarm's relativeOffset's type

### PR DESCRIPTION
**Pull request by tasn**
According to the docs the correct type is number though here it was
string. This commit fixes that.

Docs: https://docs.expo.io/versions/latest/sdk/calendar/#alarm

# Why

Typing is wrong.

# How

Changed the type.

# Test Plan

Try using it, it doesn't work. It expects a number but the type in typescript is a string.

### CODE REVIEW

**Review by tsapeta — APPROVED** [review]
Thanks! 👍

**Comment by vinagrito** [comment]
@tasn Thx for the commit 💪
Although your fix makes total sense I still experience the crash when I define the `relativeOffset` attribute. Might some dependency be the cause of this? (I just upgraded my expo to **34.0.1**).

**Comment by tasn** [comment]
Works for me, though I haven't upgraded yet. (Also, I think I'm on 33, not
sure and not near my computer at the moment)

**Comment by vinagrito** [comment]
does your code looks something like this? (I'm testing on Android)
```javascript
export const addEventToCalendar = async (event) => {
  const calendar = await getReminderCalendar();

  Calendar.createEventAsync(calendar.id, {
    title: `${event.name} - TEST !!!!!!`,
    startDate: moment(event.starts_at).toDate(),
    endDate: moment(event.ends_at).toDate(),
    location: "Tel Aviv",
    timeZone: "Asia/Jerusalem",
    alarms: [{
       relativeOffset: -60,
       method: Calendar.AlarmMethod.ALARM,
    }]
  })
}
```

**Comment by tasn** [comment]
I'm testing on iOS. Are those even implemented on Android? Also, Shalom. ;)

--
Tom

**Comment by vinagrito** [comment]
:)
It is implemented, according to the [documentation](https://docs.expo.io/versions/latest/sdk/calendar/#alarm)
Oh dear, I hope it won't be one of those features that work on a platform but not in the other. Also, trusting my MEIZU phone might not be a good idea

**Comment by vinagrito** [comment]
Nop, It's somehow the type of the `relativeOffset` attribute. If I pass `"-60"` (as string) is saves the event without crashing (& without the alarm - which at least is something)

**Comment by vinagrito** [comment]
I do see that someone else went into (most probably) [the same issue](https://stackoverflow.com/questions/56821645/calendar-createeventasync-crashes-on-android-only-expo). He actually has some more insights
```
java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.Integer
```

**Pull request merged**
