### PR TITLE
[docs][modules] fix import references to config plugins in native module tutorial

### PR DESCRIPTION
**Pull request by fobos531**
# Why

https://discord.com/channels/695411232856997968/1009056414028812299/1156993204718141521

# How

Update the references to the config plugins imports

# Test Plan

N/A

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Comment by fobos531** [comment]
@amandeepmittal I just took another look at the docs, and it looks like `expo/config-plugins` is being recommended at other places as well. Can you shed some insight into why this is recommended, compared to Alan's recommendation to use `@expo/config-plugins` ?

**Comment by Simek** [comment]
@fobos531 Scoped import (with `@` before package name) is a legacy approach, used for SDK 46 and older. For the current SDK the `expo/config-plugins` is the recommended import. You can read a bit more about that here:
* https://docs.expo.dev/config-plugins/plugins-and-mods/#using-sdk-46-or-lower

**Comment by fobos531** [comment]
> @fobos531 Scoped import (with `@` before package name) is a legacy approach, used for SDK 46 and older. For the current SDK the `expo/config-plugins` is the recommended import. You can read a bit more about that here:
> 
> * [docs.expo.dev/config-plugins/plugins-and-mods/#using-sdk-46-or-lower](https://docs.expo.dev/config-plugins/plugins-and-mods/#using-sdk-46-or-lower)

With that said, what would be the reason behind it not being installed in the Expo modules SDK example project?

When I try to build a config plugin according to the `create an expo module with a config plugin` tutorial, I am unable to access the `expo/config-plugins` export at all. 

CleanShot 2023-10-05 at 10 25 42@2x


I can only find it under `@expo/config-plugins`. Maybe it has something to do with the fact that `expo` is defined as a peerDependency in the module project? Cause I've seen it work just fine in full-fledged app, I can access `expo/config-plugins` in that instance. That's what caused the confusion for me and what's the motivation behind this PR in the first place.

**Comment by Simek** [comment]
The `expo` package should also be included as a developer dependency of package which includes plugin. This should fix the import issue, you can follow the more detailed guide on developing plugins on:
* https://docs.expo.dev/config-plugins/development-and-debugging/

If following the steps listed in docs do not work for you let me know, and we can try then debug your specific case (if you will be able to share the code), but hopefully the mentioned article will address the issues and help you with the correct config plugin setup.

**Comment by amandeepmittal** [comment]
Hey @fobos531, hopefully, you were able to resolve the issue on your end. I'm closing this PR as it seems not a valid docs change in this case.

**Pull request closed without merging**
