### PR TITLE
[ios] Fix expo-file-system not compiling for testing

### PR DESCRIPTION
**Pull request by tsapeta**
# Why

Fixes compilation errors when building `expo-file-system` for testing (https://github.com/expo/expo/actions/runs/4226952702)
For reference: https://github.com/expo/expo/pull/21196#issuecomment-1437311832

# How

I'm not sure what's exactly the root cause of these errors (they are cryptic, mostly segmentation faults in the compiler), but I narrowed down the problem to the `NSData+EXFileSystem` extension. I moved its functionality to the class that uses it and the error disappeared.

Also I think using the extension for such a thing was not the right choice – imho extensions should be used only as the last resort when there is no other way to achieve what we want. For example it makes sense when we want to make the existing class conform to a protocol (like convertibles in expo-modules-core), but in this case the `md5String` method could be defined anywhere else.

# Test Plan

The iOS native unit tests for `expo-file-system` are passing now

### CODE REVIEW

**Review by gabrieldonadel — APPROVED** [review]
LGTM, tests are green 🟢

**Comment by tsapeta** [comment]
*Hi there! 👋 I'm a bot whose goal is to ensure your contributions meet our guidelines.*

I've found some issues in your pull request that should be addressed (click on them for more details) 👇

<details>
  <summary><strong>⚠️ Suggestion</strong>: Missing changelog entries</summary>

&NewLine;
Your changes should be noted in the changelog. Read [Updating Changelogs](https://github.com/expo/expo/blob/main/guides/contributing/Updating%20Changelogs.md) guide and consider adding an appropriate entry to the following changelogs: 
- [`packages/expo-file-system/CHANGELOG.md`](https://github.com/expo/expo/blob/@tsapeta/fix-file-system-tests/packages/expo-file-system/CHANGELOG.md)
</details>


---
*Generated by ExpoBot 🤖 against 7246ffc53bcbf5d971d3e956eb38fb03721f4c67*

**Comment by tsapeta** [comment]
*Hi there! 👋 I'm a bot whose goal is to ensure your contributions meet our guidelines.*

I've found some issues in your pull request that should be addressed (click on them for more details) 👇

<details>
  <summary><strong>⚠️ Suggestion</strong>: Missing changelog entries</summary>

&NewLine;
Your changes should be noted in the changelog. Read [Updating Changelogs](https://github.com/expo/expo/blob/main/guides/contributing/Updating%20Changelogs.md) guide and consider adding an appropriate entry to the following changelogs: 
- [`packages/expo-file-system/CHANGELOG.md`](https://github.com/expo/expo/blob/@tsapeta/fix-file-system-tests/packages/expo-file-system/CHANGELOG.md)
</details>


---
*Generated by ExpoBot 🤖 against 7246ffc53bcbf5d971d3e956eb38fb03721f4c67*

**Comment by Kudo** [comment]
great investigation 👏

**Pull request merged**
