### PR TITLE
[iOS][sdk-39] Version iOS codebase

### PR DESCRIPTION
**Pull request by bbarthec**
# Why

https://github.com/expo/expo/blob/master/guides/releasing/Release%20Workflow.md#14-versioning-code-for-the-new-sdk

# How

- `et add-sdk --platform ios`
- adjusted `39_0_0ExpoKit.podspec`, because of `ReanimatedV2` integration into `ExpoKit`

# Test Plan

- [x] iOS project compiles
- [x] `home` runs
- [x] `ncl` UNVERSIONED runs

Right now I have some issues running managed apps with `SDK 39`:
- [x] `ncl` 39.0.0 runs
- [x] `test-suite` 39.0.0 runs

# Issues
- [x] `expo-random` is versioned properly
- [x] runtime crash for SDK39 coming from unregistered modules `ABI39_0_0RCT{DeviceEventEmitter, EventEmitter, Log}` https://github.com/expo/expo/pull/9978

### CODE REVIEW

**Review by esamelson — CHANGES_REQUESTED** [review]
I just ran into an issue with the Android versioning with the `expo-random` module -- namely, it is not versioned at all by the `add-sdk` script because its unimodule.json has been deleted. Since iOS has autolinking I am guessing you had the same issue but it was not as apparent (on Android the build failed!). But from a quick glance at this PR it does indeed look like there is no header for ABI39_0_0EXRandom.

**Comment by bbarthec** [comment]
Versioning is done, time for Versioned QA 😉 cc @esamelson

**Review by esamelson — CHANGES_REQUESTED** [review]
Sorry for the confusion -- we do not want to add a unimodule.json to expo-random as it is no longer a unimodule! Rather, we want to include in the versioning regardless of this fact. I suggest we use a solution like https://github.com/expo/expo/pull/9986/commits/01a93be1d581c4c58307c843407cf7394587e311, perhaps just merging as is in this PR but testing after the fact that the change I made in https://github.com/expo/expo/pull/9986/commits/01a93be1d581c4c58307c843407cf7394587e311 works for iOS as well.

Also, I noticed that there is no ABI39_0_0EXUpdates included in this PR, likely due to the fact that `expo-updates` was listed in `unversionablePackages.json` -- I've corrected this [here](https://github.com/expo/expo/pull/9986/commits/01a93be1d581c4c58307c843407cf7394587e311#diff-6946192a0aecde17812d138325c665bc) but we need versioned ABI39 code for that module as well.

**Comment by bbarthec** [comment]
The most recent force status (few problems spotted):
- versioned `expo-updates` - I had to manually remove `EX_UNVERSIONED` and one dangling `)` cc @esamelson  - https://github.com/expo/expo/blob/445d9ef23113475c01ffb8825e4abe1d485d5145/ios/versioned-react-native/ABI39_0_0/Expo/ExpoKit/Core/UniversalModules/ABI39_0_0EXScopedModuleRegistryAdapter.m#L43-L46
- Reanimated seems to have problems on some testing screens - I'll investigate deeper

**Comment by bbarthec** [comment]
Almost all the testing is green on iOS 13 and 14, so I'm merging this PR to unblock next release steps. Known issues would be fixed separately 💪

**Pull request merged**
