### PR TITLE
[docs] Remove unused dependencies and split dev dependencies

### PR DESCRIPTION
**Pull request by byCedric**
# Why

This cleans up our docs dependencies by
- Removing unused dependencies
- Moving dependencies not used in Next output, like loaders and compilers, to dev dependencies

# How

Updated `package.json` and [deployed the website here](https://cedrics-expo.s3-website.eu-central-1.amazonaws.com/).

# Test Plan

See [deployed website](https://cedrics-expo.s3-website.eu-central-1.amazonaws.com/).

### CODE REVIEW

**Comment by brentvatne** [comment]
oh no, this is pretty old now. cc @Simek - a man who cares deeply about dependencies

**Comment by Simek** [comment]
@byCedric All changes here looks reasonable, it would be nice to rebase this PR and merge it.  👍 

So far only the `babel` dependencies has been moved to the developer dependencies, other than that, there will be some versions conflicts, but I hope it will be relative easy to resolve. Of course you can always open new PR to avoid dealing with lock conflicts. 😉

**Comment by byCedric** [comment]
Haha yeah, it's pretty old now. I'll see what I can do with a newer version!

**Comment by byCedric** [comment]
Closing, we can circle back to this later

**Pull request closed without merging**
