### PR TITLE
[web][expo-image-picker] Fix cancelled picker dialog not resolving expected result on web

### PR DESCRIPTION
**Pull request by raqso**
# Why

Issue same as here: https://github.com/expo/expo/issues/11817
Was fixed a long time ago in: https://github.com/expo/expo/pull/11847 but don't work now 

# How

https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/cancel_event#canceling_an_input_element
Added listener to 'onChange' event on the file input.

# Test Plan

https://snack.expo.dev/@raqsasg/expo-image-picker-cancelled-on-web

Added also simple unit tests to verify the fix.

### CODE REVIEW

**Comment by masoud-msk** [comment]
@lukmccall @alanjhughes  Would someone please review this fix?

**Comment by acrazing** [comment]
Any updates?

**Review by lukmccall — APPROVED** [review]
Everything looks great! Could you please rebase the branch? Once that’s done, I’ll merge it.

**Comment by raqso** [comment]
> Everything looks great! Could you please rebase the branch? Once that’s done, I’ll merge it.

Sure, it's rebased now

**Pull request merged**
