### PR TITLE
[android] Add Firebase integration to Segment

### PR DESCRIPTION
**Pull request by sjchmiela**
# Why

To be able to add Firebase as Segment events destination, one needs to add a native dependency.

# How

- upgraded Firebase and GMS dependencies
- added and integrated `'com.segment.analytics.android.integrations:firebase:1.2.0'`.

# Test Plan

A standalone app built with this library is able to send events both to Segment and to Firebase.

zrzut ekranu 2019-02-28 o 13 37 13

### CODE REVIEW

**Review by Szymon20000 — APPROVED** [review]
Looks good!

**Comment by alexbchr** [comment]
Is there any documentation on this somewhere? Segment/Firebase integration works on iOS too, or only Android?

If it is only available on Android, would it be possible to get it on iOS?

**Comment by pablopoggiog** [comment]
same concern/request, is there any doc about how to use this implementation?
@alexbchr , did you solve how to add it to your app?
thanks in advance!

**Comment by alexbchr** [comment]
> same concern/request, is there any doc about how to use this implementation?
> @alexbchr , did you solve how to add it to your app?
> thanks in advance!

Sorry @pablopoggiog, but I didn't get a change to test this again, I will post back here if I ever get the chance to do so

**Comment by pablopoggiog** [comment]
@alexbchr no problem man, thanks for answering!

**Pull request merged**
