### PR TITLE
Fixed spelling for documentation

### PR DESCRIPTION
**Pull request by awaisabir**
# Why

There was a grammatical error in the documentation.

# How

N/A

# Test Plan

There is no test-plan as it is a documentation change.

### CODE REVIEW

**Comment by sjchmiela** [comment]
Thanks! 👏

**Comment by sjchmiela** [comment]
Could you also make this change to `unversioned` version of files? You've edited `v32.0.0` folder, there's an `unversioned` one too. This way your change will be included in future docs too!

**Comment by awaisabir** [comment]
Sounds good 🙌

**Review by sjchmiela — APPROVED** [review]
Thanks a lot! 💯

**Pull request merged**
