### PR TITLE
[android][maps] add MapsPackage handling

### LINKED ISSUE #4791: [MapView][Android] getCamera results in "null is not an object `AirMapModule.getCamera`"
### Environment

Expo CLI 2.21.1 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.9.2 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.1 AI-173.4819257
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^33.0.0 => 33.0.7 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.11.0 => 3.11.0 
    npmGlobalPackages:
      expo-cli: 2.21.1

react-native-maps: 0.24.2

### Steps to Reproduce

MapView getCamera() method is not working on android but is fine on IOS

### Expected Behavior

Should work for both platforms

### Actual Behavior

When I use this code (on ios and android) it produces an error  on android (but is fine on ios):

  async getCamera() {
    const camera = await this.map.getCamera();
    console.log('Current camera', JSON.stringify(camera));
  }

The error is:
[Unhandled promise rejection: TypeError: null is not an object (evaluating '_reactNative.NativeModules.AirMapModule.getCamera')]

It appears to me that AirMapModule is missing inside of NativeModules

### PR DESCRIPTION
**Pull request by cruzach**
# Why

closes https://github.com/expo/expo/issues/4791 and https://github.com/expo/expo/issues/5996

# Test Plan

Tested locally on `sdk-36` branch, rebuilt expoview, built Expo client & standalone and made sure methods like `getMapBoundaries` and `getCamera` work as expected

### CODE REVIEW

**Review by sjchmiela — APPROVED** [review]
Thank you for taking care of this! 🎉

**Comment by vincentvella** [comment]
What's the timeline for this to be released into the client app/sdks?
This is an observed a bug with documented functionality in the `sdk-36` release. Is there a way we can get this released now or will it be as part of the future `sdk-37`?

**Comment by cruzach** [comment]
It most likely won't be released in the client app until the next SDK release

However, it should be available to standalones on SDK 36 before that, once we deploy the fix to the builders

**Comment by Triyugi** [comment]
@cruzach I am still getting this issue in SDK 36.

**Comment by cruzach** [comment]
Patch has just been deployed, you'll need to rebuild your app with `expo build:android` to get the fix

**Comment by Triyugi** [comment]
@cruzach Thanks. One little help more as my app is still in development. I have not created any build so far. So, how can I apply this patch to my development app?

**Comment by sjchmiela** [comment]
We will probably release an update of Expo client app with a fix. 🙂

**Comment by RyanTG** [comment]
I made a build on Feb 1 at 8:20 PM (PST). Does that mean my build included this and the [other hotfix](https://github.com/expo/expo/pull/6825)? It's unclear to me if I need to make another build in order to capture these fixes - not sure how to test. When were the fixes deployed to the builder, and would I have needed expo-cli 3.11.9 to get them (I was on 3.11.7)?

**Comment by cruzach** [comment]
@RyanTG your apk will already have the fix if you built on Feb 1, even if you were using expo-cliv3.11.7 👍

**Comment by NeOMakinG** [comment]
Is this patch working with Expo android client app ? I've an app under development which got this issue :(

**Pull request merged**
