### PR TITLE
docs added expo-server-sdk-dotnet to list

### PR DESCRIPTION
**Pull request by glyphard**
# Why

Added dotnet sdk version link discussed here
https://forums.expo.io/t/expo-expo-server-sdk-dotnet/33807

# How

implemented in dotnet and then updated docs

# Test Plan

Used preview to check formatting on docs

### CODE REVIEW

**Comment by ide** [comment]
Before adding this, could you please add rate-limiting to the library so that it opens at most 6 HTTP connections at a time?

**Review by ide — CHANGES_REQUESTED** [review]
The Node SDK demonstrates how to do rate limiting and also how to compress requests.

**Comment by byCedric** [comment]
This might also help fixing the concurrent connections, https://codeburst.io/throttling-concurrent-outgoing-http-requests-in-net-core-404b5acd987b

**Comment by glyphard** [comment]
Added connection throttling limit to 6 concurrent connections and updated.
No change required to the documentation.

**Pull request merged**
