### PR TITLE
[camera][android] Rewrite module to kotlin

### PR DESCRIPTION
**Pull request by mstach60161**
# Why

Modules written in java are rewritten to Kotlin.

# How

- Convert Java code to kotlin.
- Fix bugs and clean up code.

# Test Plan

- Test suite
- Native component list

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.io and README.md).

### CODE REVIEW

**Review by kkafar — COMMENTED** [review]
Looks good

**Review by bbarthec — APPROVED** [review]
As far as I see it everything looks ok. I've got just one question 👇

**Review by barthap — APPROVED** [review]

**Review by lukmccall — COMMENTED** [review]
LGMT 🚀

**Review by kkafar — COMMENTED** [review]
After applying remaining suggestions -- it'll look fine to me

**Pull request merged**
