### PR TITLE
[expo-facebook][android] Upgrade FBSDK to 5.12.1

### LINKED ISSUE #6427: Facebook Platform Policy Violation SDK 35.0.0
### Environment

Expo CLI 3.9.1 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 13.2.0 - ~/.nvm/versions/node/v13.2.0/bin/node
      Yarn: 1.19.2 - /usr/local/bin/yarn
      npm: 6.13.1 - ~/.nvm/versions/node/v13.2.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      @storybook/react-native: ^3.2.10 => 3.4.12 
      expo: ^35.0.0 => 35.0.0 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
      react-navigation: ^4.0.10 => 4.0.10 
    npmGlobalPackages:
      expo-cli: 3.9.1

Target: iOS, Android

### Actual Behavior

After upgrading to the latest Expo SDK, 35.0.0, we received an email from Facebook saying that our app, which uses Facebook Login, violates Facebook Platform Policy 8.2:

> Platform Policy 8.2: Native iOS and Android apps that implement Facebook Login must use our official SDKs for Login.
>
> Please make sure your Android app is using the most recent version of our SDK for Login. You can find more information on our Android SDK for Login and other Login-related products here: https://developers.facebook.com/docs/facebook-login/android.

They also provided an image of what the login should look like:

image

As a result, Facebook has restricted our application and we can no longer use Facebook Login on Android devices.

In SDK 35.0.0, it looks like FBSDK*Kit was upgraded to `v5.4.1`, but the Android FBSDK is still `v5.0.2` (current version is `v5.11.2`).

I'm also noticing inconsistent behavior with `Facebook.logInWithReadPermissionsAsync` on our Android builds.  Most of the time when I execute `logInWithReadPermissionsAsync`, I get this modal login screen:

fb_modal_sanitized

However, occasionally I get this screen instead (on the same device):

fb_screen_sanitized

I'm assuming that Facebook doesn't allow the first screen, only the second. With the [behavior options now gone](https://github.com/expo/expo/pull/5499), I'm not sure how to enforce this screen type.
### Reproducible Demo

It's very hard to create a reproducible Demo since it requires Facebook auditing the app and putting the restriction on it.

### PR DESCRIPTION
**Pull request by sjchmiela**
# Why

Should help fix https://github.com/expo/expo/issues/6427.

# How

Upgraded FBSDK on Android to latest version.

**Maybe it should get backported to SDK36?**

# Test Plan

Facebook Login NCL screen opened a WebView on emulator and opened Facebook app on the real device with the Facebook app installed (this resulted in an error, I believe because the app ID that is used in NCL is for an in-development app with Szczepan Czekan not added to testers. When changed to my `expotest` app where Szczepan is a tester, the login went flawlessly.)

### CODE REVIEW

**Comment by esamelson** [comment]
Interesting -- is it expected that the login behavior should differ between emulator and device? 🤔 It seems like the original issue author was also reporting some inconsistent behavior. I'm ok with backporting this to SDK 36 but would want to be fairly sure it actually fixes the issue first.

Also, is it easy to verify that this upgrade doesn't cause any regressions with the autologging behavior?

**Comment by sjchmiela** [comment]
> Interesting -- is it expected that the login behavior should differ between emulator and device? 🤔 It seems like the original issue author was also reporting some inconsistent behavior. I'm ok with backporting this to SDK 36 but would want to be fairly sure it actually fixes the issue first.

The login behavior differs between the emulator and the device not because it's an emulator and a device, but because the device had Facebook app installed and the emulator did not. Sorry for not stating that earlier. The behavior was correct.

> Also, is it easy to verify that this upgrade doesn't cause any regressions with the autologging behavior?

You mean like… going through the changelog? 😃 Nothing changed in that area.

**Review by esamelson — APPROVED** [review]
OK, thanks for the clarification!

**Comment by adamhake** [comment]
@esamelson just to clarify from my original issue (#6427), the inconsistent login behavior wasn't between an emulator and a device.  It was always on the device, and it always had the Facebook app installed.  But this PR could very well have solved the issue.  Thanks for the quick turnaround @sjchmiela!

**Pull request merged**
