### PR TITLE
[expo-updates] Add expo-eas-client-id to package.json

### PR DESCRIPTION
**Pull request by wschurman**
# Why

Noticed by @ajsmth. I forgot to add the dependency here.

# How

Add the dependency, `yarn`

# Test Plan

`yarn`

### CODE REVIEW

**Review by ide — APPROVED** [review]

**Comment by ide** [comment]
This CI failure is present though
```
Run yarn add file:../expo/packages/expo-updates file:../expo/packages/expo file:../expo/packages/expo-eas-client-id file:../expo/packages/expo-modules-core file:../expo/packages/expo-json-utils file:../expo/packages/expo-manifests file:../expo/packages/expo-structured-headers file:../expo/packages/expo-updates-interface
yarn add v1.22.1[8](https://github.com/expo/expo/runs/5728758049?check_suite_focus=true#step:10:8)
[1/4] Resolving packages...
error Couldn't find package "expo-eas-client-id@~0.1.0" required by "file:../expo/packages/expo-updates" on the "npm" registry.
```

**Comment by wschurman** [comment]
Maybe I need to change the ordering? Trying now.

**Comment by wschurman** [comment]
Or maybe I need to publish? But it should use the linked version?

**Comment by wschurman** [comment]
Published to npm, retrying.

**Comment by ide** [comment]
It could be that `yarn add file:parent file:child` still tries to contact npm for the version of `child` listed in `parent`'s package.json file. Publishing `expo-eas-client-id@0.1.0` to npm would fix the symptom but perhaps result in two copies of expo-eas-client-id under node_modules. Even if yarn dedupes the packages, it's still a gotcha that the package needs to be published.

Perhaps what we need to do is make the test app's package.json file be a Yarn workspace root with `"workspaces": ["packages/expo", "packages/expo-updates", "packages/"expo-eas-client-id", ...]`.

**Comment by esamelson** [comment]
> It could be that `yarn add file:parent file:child` still tries to contact npm for the version of `child` listed in `parent`'s package.json file. Publishing `expo-eas-client-id@0.1.0` to npm would fix the symptom but perhaps result in two copies of expo-eas-client-id under node_modules. Even if yarn dedupes the packages, it's still a gotcha that the package needs to be published.
> 
> Perhaps what we need to do is make the test app's package.json file be a Yarn workspace root with `"workspaces": ["packages/expo", "packages/expo-updates", "packages/"expo-eas-client-id", ...]`. However, this uses symlinks, which Metro/Watchman has trouble with (expo-yarn-workspaces gets symlinks working precariously).

I think we should be able to get this working without workspaces -- perhaps by utilizing yarn resolutions for children in the example above rather than adding all the children as dependencies. I can investigate this tomorrow separately from this PR (which it seems like we should land, assuming the test passes now).

**Review by esamelson — APPROVED** [review]

**Pull request merged**
