### PR TITLE
feat(expo): add fast refresh web runtime modules

### PR DESCRIPTION
**Pull request by EvanBacon**
# Why

- Resolves ENG-5426

# How

The code in this PR installs the required runtime code for using Metro to bundle web apps in development. This runtime code is responsible for:

- Setting up websocket controls like 'press `r` to reload' in the Expo CLI Terminal UI in web.
- Installing Fast Refresh and sending UI events.
- Configuring hot module reloading.

Unlike `react-native` DevSupport, this does not currently configure `react-devtools-core`.

Expo Webpack users didn't need a folder like this because `@expo/webpack-config` utilized the built-in systems provided by both Webpack and Create React App -- this is suboptimal in size and doesn't implement Fast Refresh.

The `HMRClient` communicates with the [Metro runtime HMR module](https://github.com/facebook/metro/blob/main/packages/metro-runtime/src/modules/HMRClient.js) over a websocket connection. The `HMRClient` module is a fork of the [upstream `react-native` module](https://github.com/facebook/react-native/blob/main/Libraries/Utilities/HMRClient.js#L1) but web-only (code like this would typically live in `react-native-web`).

Currently blocked on having some mechanism to include this module for web-only, projects that aren't bundled by Webpack -- the untranspiled `metro-runtime` code breaks Webpack.

# Test Plan

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `expo build` (eg: updated `@expo/xdl`).
- [ ] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Comment by LinusU** [comment]
@EvanBacon is there anything the community could do to help with this? Is there a way to try this out in our Expo projects?

**Comment by LinusU** [comment]
That's awesome! I'm currently stuck at #20456, so I need to find a fix for that before I can try it out properly. But I'm very excited to have the same bundler both for native and web! 🎉

**Comment by EvanBacon** [comment]
Closing as this now lives [here](https://github.com/expo/router/tree/main/packages/expo-metro-runtime) pending expo router getting merged into expo/expo.

**Comment by EvanBacon** [comment]
@LinusU ok, I opened a ticket for this.

**Pull request closed without merging**
