### PR TITLE
[router]: Fix Screen.getId assignment

### PR DESCRIPTION
**Pull request by stephentuso**
# Why

I need to be able to push the same route with different params to the stack, but it was always replacing the current one (see #33175). I found the cause:

If a route is customized with `Stack.Screen` as a child of `Stack` (wasn't happening for routes using `Screen` at render time), `getId` is passed as undefined to `routeToScreen`, which was overriding the required `getId` function `expo-router` uses.

Additionally, if `getId` was manually set on a `Screen`, the internal `__EXPO_ROUTER_key` query param was not removed, which is visible in the address bar on web.

# How

Updated `routeToScreen` to always wrap `getId`. If an override is passed, it will just remove the internal query param and then call the override.

# Test Plan

Added automated tests

# Checklist

- [x] I added a `changelog.md` entry and rebuilt the package sources according to [this short guide](https://github.com/expo/expo/blob/main/CONTRIBUTING.md#-before-submitting)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)

### CODE REVIEW

**Comment by stephentuso** [comment]
Side note: changelog only has 4.0.10 but latest published version is 4.0.11

**Review by marklawlor — APPROVED** [review]

**Comment by kimchouard** [comment]
I'm facing this issue too. Glad this is fixed, thanks! 🙏🙏🙏 @marklawlor any clues on when this will be realsed to a npm version? 😇

**Comment by oscklm** [comment]
I'd love to know when this will be released too? Any updates

**Comment by xgiovio** [comment]
same here

**Comment by stephentuso** [comment]
@marklawlor @EvanBacon sorry to ping but any update on getting this released?

**Comment by marklawlor** [comment]
I'll release this tomorrow 👍

**Comment by sungsong88** [comment]
> I'll release this tomorrow 👍

Thank you! looking forward to it!!!!!

**Comment by oscklm** [comment]
Awesome 🎉

**Comment by mrkpatchaa** [comment]
Hi @marklawlor is this published? I see here that it's still unpublished https://github.com/expo/expo/blob/main/packages/expo-router/CHANGELOG.md
Thank you.

**Comment by tysteiger** [comment]
Bump on this please. Still seeing issue on Expo 52.0.33 and expo-router 4.0.17!

**Comment by samsonroy** [comment]
@marklawlor When would this be released ?

**Comment by oscklm** [comment]
I'm curious about the same thing. Really hoping this releases soon ✌️

**Comment by ajayvikas** [comment]
Can u please publish this. This fix is very important for us.

**Comment by tysteiger** [comment]
hello why is this still not listed a published in the changelog?

**Comment by j3lev** [comment]
Will this be released?

**Comment by mrkpatchaa** [comment]
@j3lev seems like it's in preview right now. Check here https://github.com/expo/expo/blob/main/packages/expo-router/CHANGELOG.md#500-preview0--2025-04-04

**Comment by j3lev** [comment]
Yeah but ideally it can be backported to the current stable version. We're about to release to production next week and I definitely would like to to avoid a major upgrade to a preview version for something as critical as the routing framework

**Comment by j3lev** [comment]
@marklawlor any way we can backport this to v4 so it can be used in production?

**Comment by mrkpatchaa** [comment]
I totally agree with you. I've been waiting for so long, that I even forgot about it :) 
And it's unsafe to push a preview version to production....

**Comment by mrkpatchaa** [comment]
BTW I can confirm it's working well in the preview version ;)

**Comment by RahulMandyal1** [comment]
@marklawlor  Could you please confirm in which version of Expo Router this issue was fixed? I'm still experiencing the same issue with version "expo-router": "~4.0.20".

**Comment by marklawlor** [comment]
This was fixed in SDK 53. As it requires a version bump of React Navigation and React Native Screens we cannot backport it to SDK 52

**Comment by RahulMandyal1** [comment]
@marklawlor I recently upgraded to SDK 52, but I can't afford to move to SDK 53 due to some breaking changes.
Would a custom patch applied locally work to fix this in SDK 52?
Or is there another way to resolve this issue while staying on SDK 52?

**Pull request merged**
