### PR TITLE
[docs] Add resizeMode enum in `expo-av` example

### PR DESCRIPTION
**Pull request by devpolo**
# Why

Fixing type error: Type '"contain"' is not assignable to type 'ResizeMode | undefined'.

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Comment by amandeepmittal** [comment]
Hi @devpolo, running the [Snack exmaple](https://docs.expo.dev/versions/v47.0.0/sdk/video/#usage) doesn't throw that error you described. Is the error message you are getting when using TypeScript?

**Comment by devpolo** [comment]
Yes! 
Capture d’écran 2023-02-20 à 11 16 37

**Comment by alanjhughes** [comment]
@devpolo Yid need to use `ResizeMode` enum provided by `expo-av`

**Comment by devpolo** [comment]
> You need to use ResizeMode enum provided by expo-av

**Comment by alanjhughes** [comment]
@devpolo Yes, sorry I misread 😅

**Comment by amandeepmittal** [comment]
@devpolo I appreciate you opening this PR but I'm going to hold this off for some time. We are currently discussing of moving all examples to be TypeScript first and that requires some re-writing of type definitions in the API docs. This PR acts as a great reference point for us. Apologies for any inconvenience 🙏

**Comment by amandeepmittal** [comment]
This was resolved in [PR](https://github.com/expo/expo/pull/21925/files#diff-8634543a3fce09f4536ad5604fee12c127e352a96f0b4333d73c3ef4e819b17e) and [here is more in-depth context on the follow-up plans we have](https://github.com/expo/expo/pull/21925#pullrequestreview-1368677815).

**Pull request closed without merging**
