### PR TITLE
[docs][build-properties-example] Fix expo-build-properties usage example in app.config.js

### PR DESCRIPTION
**Pull request by alanjhughes**
# Why
After speaking to someone on discord https://discord.com/channels/695411232856997968/943206692332658688/1097597491760861275 they had issues using the example code in `app.config.js`. 

# How
Updated the usage example.

# Test Plan
n/a

### CODE REVIEW

**Comment by fobos531** [comment]
I also found that I needed to list the `expo-build-properties` plugin first (before any other plugins), otherwise the changes would not get applied. Not sure if this is the relevant place, but I felt it was worth mentioning.

**Review by amandeepmittal — APPROVED** [review]
Thanks for updating this and your contribution, @alanjhughes 🎉

**Comment by amandeepmittal** [comment]
@alanjhughes, would you mind updating the SDK 48 doc usage section too: https://docs.expo.dev/versions/v48.0.0/sdk/build-properties/#example-appconfigjs-usage?

**Comment by alanjhughes** [comment]
@amandeepmittal No problem 👍

**Review by amandeepmittal — APPROVED** [review]
Thanks for backporting changes to the SDK 48.

**Pull request merged**
