### PR TITLE
[video] Add seekTo method for Android, iOS and Web

### PR DESCRIPTION
**Pull request by JustJoostNL**
# Why
Fixes the gap I encountered in the new expo-video library in beta. There currently is no way to seek to a specific time (only adjusting is possible)

# How
I added a new method called `seekTo` on all platforms.

# Test Plan
There are no tests for the new expo-video library yet.

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [x] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Review by tsapeta — COMMENTED** [review]
Thanks for the contribution!
Isn't the `currentTime` property setter doing the same thing? 😉 To be honest I'm not even sure if we really need `seekBy` if we already have `currentTime` 😅

**Comment by JustJoostNL** [comment]
> Thanks for the contribution! Isn't the `currentTime` property setter doing the same thing? 😉 To be honest I'm not even sure if we really need `seekBy` if we already have `currentTime` 😅

Whoops, sorry! I completely missed that, my excuses. Feel free to close this then I guess, except when you think this is "needed" on top of the `currentTime` setter. 😅

**Comment by brentvatne** [comment]
thank you! @behenate is OOO for a week but he can review when he is back!

**Comment by behenate** [comment]
I think we can close this, this is the same as using the `currentTime` setter. Nevertheless thank you a lot for the contribution!


@tsapeta Yeah, `seekBy` is a leftover from before the setter for `currentTime` existed, but it's probably a common usage so I think we should keep it

**Pull request closed without merging**
